# -*- coding: utf-8 -*-
"""Dữ liệu nội dung SET (sinh từ file Word bằng tools/gen_units.py rồi có thể chỉnh tay).
Đáp án + giải thích: xem file *_dapan.py cùng tên."""

SET = {'id': 'lop10-u1-botro',
 'title': 'Unit 1 – Family life: Bài tập bổ trợ',
 'grade': 10,
 'unit': 1,
 'theory': '<p><b>A. VOCABULARY</b> (Từ vựng)</p><table '
           'class="th"><tr><th>Word</th><th>Type</th><th>Pronunciation</th><th>Meaning</th></tr><tr><td>Achievement</td><td>(n)</td><td>/əˈtʃiːvmənt/</td><td>thành '
           'tựu</td></tr><tr><td>Appreciate</td><td>(v)</td><td>/əˈpriːʃieɪt/</td><td>biết ơn, trân '
           'trọng</td></tr><tr><td>Benefit</td><td>(n)</td><td>/ˈbenɪfɪt/</td><td>lợi '
           'ích</td></tr><tr><td>Bond</td><td>(n)</td><td>/bɒnd/</td><td>sự gắn '
           'bó</td></tr><tr><td>Breadwinner</td><td>(n)</td><td>/ˈbredwɪnə(r)/</td><td>trụ cột gia '
           'đình</td></tr><tr><td>Celebrate</td><td>(v)</td><td>/ˈselɪbreɪt/</td><td>tổ chức '
           'tiệc</td></tr><tr><td>Character</td><td>(n)</td><td>/ˈkærəktə(r)/</td><td>tính cách</td></tr><tr><td>Cheer '
           'up</td><td>(v)</td><td>/tʃɪə(r) ʌp/</td><td>làm cho vui lên, cổ vũ</td></tr><tr><td>Choice</td><td>(n)</td><td>/tʃɔɪs/</td><td>lựa '
           'chọn</td></tr><tr><td>Cook</td><td>(v)</td><td>/kʊk/</td><td>nấu ăn</td></tr><tr><td>Damage</td><td>(v)</td><td>/ˈdæmɪdʒ/</td><td>phá '
           'hỏng</td></tr><tr><td>Difficulty</td><td>(n)</td><td>/ˈdɪfɪkəlti/</td><td>vấn đề khó '
           'khăn</td></tr><tr><td>Discuss</td><td>(v)</td><td>/dɪˈskʌs/</td><td>thảo '
           'luận</td></tr><tr><td>Divide</td><td>(v)</td><td>/dɪˈvaɪd/</td><td>chia</td></tr><tr><td>Fair</td><td>(adj)</td><td>/feə(r)/</td><td>công '
           'bằng</td></tr><tr><td>Gratitude</td><td>(n)</td><td>/ˈɡrætɪtjuːd/</td><td>lòng biết '
           'ơn</td></tr><tr><td>Grocery</td><td>(n)</td><td>/ˈɡrəʊsəri/</td><td>thực phẩm và tạp hóa</td></tr><tr><td>Grow '
           'up</td><td>(v)</td><td>/ɡrəʊ ʌp/</td><td>trưởng thành</td></tr><tr><td>Heavy lifting</td><td>(n)</td><td>/ˌhevi ˈlɪftɪŋ/</td><td>mang '
           'vác nặng</td></tr><tr><td>Homemaker</td><td>(n)</td><td>/ˈhəʊmmeɪkə(r)/</td><td>người nội '
           'trợ</td></tr><tr><td>Honest</td><td>(adj)</td><td>/ˈɒnɪst/</td><td>thật thà</td></tr><tr><td>Household '
           'chore</td><td>(n)</td><td>/ˈhaʊshəʊld tʃɔː(r)/</td><td>công việc '
           'nhà</td></tr><tr><td>Housework</td><td>(n)</td><td>/ˈhaʊswɜːk/</td><td>công việc nhà</td></tr><tr><td>Instead '
           'of</td><td>(adv)</td><td>/ɪnˈsted əv/</td><td>thay cho</td></tr><tr><td>Laundry</td><td>(n)</td><td>/ˈlɔːndri/</td><td>quần áo, đồ giặt '
           'là</td></tr><tr><td>Life skill</td><td>(n)</td><td>/ˈlaɪf skɪl/</td><td>kĩ năng '
           'sống</td></tr><tr><td>List</td><td>(n)</td><td>/lɪst/</td><td>danh '
           'sách</td></tr><tr><td>Manage</td><td>(v)</td><td>/ˈmænɪdʒ/</td><td>xoay '
           'sở</td></tr><tr><td>Manner</td><td>(n)</td><td>/ˈmænə(r)/</td><td>tác phong, cách ứng '
           'xử</td></tr><tr><td>Prepare</td><td>(v)</td><td>/prɪˈpeə(r)/</td><td>chuẩn bị</td></tr><tr><td>Put out</td><td>(v)</td><td>/pʊt '
           'aʊt/</td><td>vứt</td></tr><tr><td>Raise</td><td>(v)</td><td>/reɪz/</td><td>nuôi '
           'nấng</td></tr><tr><td>Respect</td><td>(n)</td><td>/rɪˈspekt/</td><td>sự tôn '
           'trọng</td></tr><tr><td>Responsibility</td><td>(n)</td><td>/rɪˌspɒnsəˈbɪləti/</td><td>trách '
           'nhiệm</td></tr><tr><td>Result</td><td>(n)</td><td>/rɪˈzʌlt/</td><td>kết '
           'quả</td></tr><tr><td>Routine</td><td>(n)</td><td>/ruːˈtiːn/</td><td>công việc hằng '
           'ngày</td></tr><tr><td>Rubbish</td><td>(n)</td><td>/ˈrʌbɪʃ/</td><td>rác '
           'rưởi</td></tr><tr><td>Spotlessly</td><td>(adv)</td><td>/ˈspɒtləsli/</td><td>không tì '
           'vết</td></tr><tr><td>Strengthen</td><td>(v)</td><td>/ˈstreŋkθn/</td><td>củng cố, làm '
           'mạnh</td></tr><tr><td>Success</td><td>(n)</td><td>/səkˈses/</td><td>sự thành '
           'công</td></tr><tr><td>Support</td><td>(n,v)</td><td>/səˈpɔːt/</td><td>sự ủng hộ, hỗ '
           'trợ</td></tr><tr><td>Task</td><td>(n)</td><td>/tɑːsk/</td><td>nhiệm '
           'vụ</td></tr><tr><td>Truthful</td><td>(adj)</td><td>/ˈtruːθfl/</td><td>trung '
           'thực</td></tr><tr><td>Value</td><td>(n)</td><td>/ˈvæljuː/</td><td>giá trị</td></tr><tr><td>Washing-up</td><td>(n)</td><td>/ˌwɒʃɪŋ '
           'ˈʌp/</td><td>việc rửa chén bát</td></tr></table><p><b>B. GRAMMAR</b> (Ngữ pháp)</p><p><b>I. PRESENT SIMPLE (Thì hiện tại '
           'đơn)</b></p><p><b>1. Công thức</b></p><table class="th"><tr><th>Thể</th><th>Cấu trúc</th></tr><tr><td>Khẳng định</td><td><b>S + V1 / '
           'V-s/es</b></td></tr><tr><td>Phủ định</td><td><b>S + do not (don’t) / does not (doesn’t) + V0</b></td></tr><tr><td>Nghi '
           'vấn</td><td><b>(Wh-) + do (not) / does (not) + S + V0 ?</b></td></tr></table><p><u>Cách thêm “s/es” cho động từ:</u></p><p>- Động từ kết '
           'thúc bằng <b>sh, ch, ss, o, x, z</b> thì thêm “es”. Vd: wash – washes, go – goes, watch – watches, miss – misses, mix – mixes, buzz – '
           'buzzes…</p><p>- Động từ tận cùng là phụ âm + “y”: đổi “y” thành “i” rồi thêm “es”. Vd: study – studies, fly – flies, cry – cries… <b>Lưu '
           'ý:</b> play – plays, pay – pays (nguyên âm + “y”).</p><p>- Riêng động từ “have” biến đổi thành “has”.</p><p><b>2. Cách sử dụng:</b> diễn '
           'tả hành động lặp lại theo <b>thói quen</b>, sự thật hiển nhiên.</p><p><b>Dấu hiệu:</b> always, usually, often, sometimes, seldom, '
           'rarely, never, every day, once a day/week/month…, twice a day/week/month…, 3 times a day/week/month…</p><p><b>Ví dụ:</b> a. My brother '
           '<mark>goes</mark> (go) to school every day. b. He <mark>is</mark> (be) often tired. c. We usually <mark>go</mark> (go) to the cinema '
           'twice a week. d. My mom <mark>cooks</mark> (cook) once a day. e. They always <mark>prepare</mark> (prepare) dinner in the '
           'evening.</p><p><b>II. PRESENT CONTINUOUS (Thì hiện tại tiếp diễn)</b></p><p><b>1. Công thức</b></p><table '
           'class="th"><tr><th>Thể</th><th>Cấu trúc</th></tr><tr><td>Khẳng định</td><td><b>S + am/is/are + V-ing</b></td></tr><tr><td>Phủ '
           'định</td><td><b>S + am/is/are + not + V-ing</b></td></tr><tr><td>Nghi vấn</td><td><b>(Wh-) + am/is/are + (not) + S + V-ing '
           '?</b></td></tr></table><p><u>Cách thêm đuôi “-ing” cho động từ:</u></p><p>- Động từ tận cùng là “e”: bỏ “e” trước khi thêm “-ing”. Vd: '
           'have – having, write – writing…</p><p>- Động từ tận cùng là “ee”: giữ nguyên “ee”. Vd: see – seeing, agree – agreeing…</p><p>- Động từ 1 '
           'âm tiết, hoặc 2 âm tiết có trọng âm rơi vào âm 2 (kết thúc bằng 1 nguyên âm + 1 phụ âm): gấp đôi phụ âm cuối. Vd: sit – sitting, prefer '
           '– preferring, swim – swimming, begin – beginning… <b>Lưu ý:</b> flow – flowing.</p><p>- die, lie, tie… : die – dying, lie – lying, tie – '
           'tying…</p><p><b>2. Cách sử dụng:</b> diễn tả hành động <b>đang diễn ra</b> ở hiện tại, ngay lúc nói.</p><p><b>Dấu hiệu:</b> now, at the '
           'moment, at present, Look!, Listen!, Be careful!, Be quiet!, today, this term, this month…</p><p><b>Lưu ý:</b> KHÔNG dùng thì hiện tại '
           'tiếp diễn với động từ chỉ trạng thái (stative verbs): like, love, hate, need, want, know, agree, understand, feel, seem, smell, hear, '
           'see…</p><p><b>Ví dụ:</b> a. I <mark>am waiting</mark> (wait) for the bus at the moment. b. Where <mark>are</mark> you <mark>going</mark> '
           '(go) now? c. Listen! Someone <mark>is singing</mark> (sing). d. I <mark>am facing</mark> (face) difficulties in learning English this '
           'term. e. She <mark>is learning</mark> (learn) English at present.</p>',
 'pages': [{'id': 'phat-am',
            'title': 'Phát âm & trọng âm',
            'mode': 'practice',
            'groups': [{'id': 'ph1',
                        'instr': 'E1: Mark the letter A, B, C or D to indicate the word whose underlined part differs from the other three in '
                                 'pronunciation in each of the following questions.',
                        'items': [{'id': 'ph1.1',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['gr<u>o</u>cery', 'h<u>o</u>memaker', 't<u>o</u>gether', 'prom<u>o</u>tion']},
                                  {'id': 'ph1.2',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['gr<u>a</u>titude', 'ch<u>a</u>racter', '<u>a</u>ctivate', '<u>a</u>greement']},
                                  {'id': 'ph1.3',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['pr<u>e</u>pare', 'str<u>e</u>ngthen', 'resp<u>e</u>ct', 'sp<u>e</u>cial']},
                                  {'id': 'ph1.4',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['h<u>u</u>sband', 'r<u>u</u>bbish', 'contrib<u>u</u>te', 'v<u>u</u>lnerable']},
                                  {'id': 'ph1.5',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['benef<u>i</u>t', 'rout<u>i</u>ne', 'ch<u>i</u>ldren', 'f<u>i</u>nance']},
                                  {'id': 'ph1.6', 't': 'mcq', 'q': '', 'o': ['pl<u>a</u>ytime', 'v<u>a</u>lue', 'gr<u>a</u>teful', 't<u>a</u>ble']},
                                  {'id': 'ph1.7',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['gener<u>a</u>tion', 'gr<u>a</u>teful', 'educ<u>a</u>te', 'gr<u>a</u>ndparents']}]},
                       {'id': 'ph2',
                        'instr': 'E2: Mark the letter A, B, C, or D to indicate the word that differs from the other three in the position of the '
                                 'primary stress in each of the following questions.',
                        'items': [{'id': 'ph2.1', 't': 'mcq', 'q': '', 'o': ['grocery', 'character', 'develop', 'homemaker']},
                                  {'id': 'ph2.2', 't': 'mcq', 'q': '', 'o': ['spotlessly', 'experience', 'society', 'responsible']},
                                  {'id': 'ph2.3', 't': 'mcq', 'q': '', 'o': ['routine', 'laundry', 'household', 'picnic']},
                                  {'id': 'ph2.4', 't': 'mcq', 'q': '', 'o': ['similar', 'important', 'atmosphere', 'breadwinner']}]}]},
           {'id': 'tu-vung-ngu-phap',
            'title': 'Từ vựng & Ngữ pháp',
            'mode': 'practice',
            'groups': [{'id': 'vg1',
                        'instr': 'E3: Mark the letter A, B, C or D to indicate the correct answer to each of the following questions.',
                        'items': [{'id': 'vg1.1',
                                   't': 'mcq',
                                   'q': 'Family ______ are important because they teach children what is right or wrong in life.',
                                   'o': ['bonds', 'values', 'holidays', 'connections']},
                                  {'id': 'vg1.2',
                                   't': 'mcq',
                                   'q': '______ the rubbish in the early morning is a part of my daily routine.',
                                   'o': ['Putting out', 'Coming out', 'Pulling out', 'Bringing out']},
                                  {'id': 'vg1.3',
                                   't': 'mcq',
                                   'q': '______ is a person who works at home and takes care of the house and family.',
                                   'o': ['Breadwinner', 'Homemaker', 'Servant', 'Houseman']},
                                  {'id': 'vg1.4',
                                   't': 'mcq',
                                   'q': 'My mother ______ the responsibility for running the household.',
                                   'o': ['holds', 'takes', 'runs', 'bears']},
                                  {'id': 'vg1.5',
                                   't': 'mcq',
                                   'q': 'Doing chores as a family will help strengthen ______.',
                                   'o': ['family bonds', 'generation gap', 'family trees', 'family values']},
                                  {'id': 'vg1.6',
                                   't': 'mcq',
                                   'q': 'Linh can’t go out with us to see a movie now because she’s ______ dinner.',
                                   'o': ['preparing', 'making', 'arranging', 'keeping']},
                                  {'id': 'vg1.7',
                                   't': 'mcq',
                                   'q': "He's a man of strong ______. He always fights for what is right and you can rely on him.",
                                   'o': ['health', 'character', 'hands', 'influence']},
                                  {'id': 'vg1.8',
                                   't': 'mcq',
                                   'q': 'When his wife gave birth to a baby boy, Mr. Nam became the sole ______.',
                                   'o': ['housemaid', 'housekeeper', 'father', 'breadwinner']},
                                  {'id': 'vg1.9',
                                   't': 'mcq',
                                   'q': 'Doing housework brings great ______ to children as it helps them develop necessary life skills.',
                                   'o': ['benefits', 'hard work', 'results', 'practices']},
                                  {'id': 'vg1.10',
                                   't': 'mcq',
                                   'q': 'She does two jobs at the same time as she is the main ______ of the family.',
                                   'o': ['breadwinner', 'homemaker', 'housewife', 'bread maker']},
                                  {'id': 'vg1.11',
                                   't': 'mcq',
                                   'q': 'Kindness and responsibility are two ______ that many parents want to teach to their children.',
                                   'o': ['family values', 'customs', 'cultures', 'ideas']},
                                  {'id': 'vg1.12',
                                   't': 'mcq',
                                   'q': 'Sarah is a(n) ______ girl. She never cheats in exams.',
                                   'o': ['generous', 'sociable', 'frank', 'honest']},
                                  {'id': 'vg1.13',
                                   't': 'mcq',
                                   'q': 'Instead of giving me answers to questions, my parents always ______ me to think for myself.',
                                   'o': ['support', 'encourage', 'respect', 'strengthen']},
                                  {'id': 'vg1.14',
                                   't': 'mcq',
                                   'q': 'Ms. Mai asked me how she could ______ household chores equally in her family.',
                                   'o': ['make', 'divide', 'give', 'contribute']},
                                  {'id': 'vg1.15',
                                   't': 'mcq',
                                   'q': "She's such a good wife. She's ______ her husband through difficult times.",
                                   'o': ['taught', 'left', 'supported', 'provided']},
                                  {'id': 'vg1.16',
                                   't': 'mcq',
                                   'q': "Jim's main ______ in his home is to keep the house clean.",
                                   'o': ['right', 'honour', 'part', 'responsibility']},
                                  {'id': 'vg1.17',
                                   't': 'mcq',
                                   'q': 'When all members of the family share housework, the family ______ will become stronger.',
                                   'o': ['joys', 'happiness', 'life', 'bonds']},
                                  {'id': 'vg1.18',
                                   't': 'mcq',
                                   'q': 'Preparing and cooking meals are some of the essential ______ for teens.',
                                   'o': ['soft skills', 'life skills', 'table manners', 'netiquette']},
                                  {'id': 'vg1.19',
                                   't': 'mcq',
                                   'q': 'When I lived in this city, I used to shop for ______ at this supermarket.',
                                   'o': ['heavy lifting', 'groceries', 'housework', 'laundry']},
                                  {'id': 'vg1.20',
                                   't': 'mcq',
                                   'q': 'The kids deeply ______ their grandfather for his great knowledge about the world.',
                                   'o': ['create', 'develop', 'respect', 'discuss']},
                                  {'id': 'vg1.21',
                                   't': 'mcq',
                                   'q': 'She decided to find a job to ______ money instead of just living at home and being a housekeeper.',
                                   'o': ['lend', 'earn', 'borrow', 'raise']},
                                  {'id': 'vg1.22',
                                   't': 'mcq',
                                   'q': "I'm lucky to have such a(n) ______ brother who always gives me help when I need it.",
                                   'o': ['support', 'supporting', 'supported', 'supportive']},
                                  {'id': 'vg1.23',
                                   't': 'mcq',
                                   'q': 'In my family, my father always takes charge of doing the ______ lifting.',
                                   'o': ['strong', 'hard', 'heavy', 'huge']},
                                  {'id': 'vg1.24', 't': 'mcq', 'q': 'Do you have to ______ the rubbish out?', 'o': ['put', 'make', 'empty', 'do']},
                                  {'id': 'vg1.25',
                                   't': 'mcq',
                                   'q': 'My mother told me to do the ______ yesterday but I forgot about it since I had much homework to finish.',
                                   'o': ['wash-up', 'laundry', 'childcare', 'exercises']},
                                  {'id': 'vg1.26',
                                   't': 'mcq',
                                   'q': 'His parents give him full ______ for his choice of school.',
                                   'o': ['support', 'change', 'value', 'bond']},
                                  {'id': 'vg1.27',
                                   't': 'mcq',
                                   'q': 'My mother and I often go to the supermarket to shop for ______ at weekends.',
                                   'o': ['cook', 'groceries', 'heavy lifting', 'the chores']},
                                  {'id': 'vg1.28',
                                   't': 'mcq',
                                   'q': "It's not easy for some tenth-graders to get into high school ______.",
                                   'o': ['works', 'routines', 'times', 'responsibilities']},
                                  {'id': 'vg1.29',
                                   't': 'mcq',
                                   'q': 'After eating dinner, I have to do the ______ and then do my homework every day.',
                                   'o': ['washing-up', 'wash-up', 'washing-ups', 'washings-up']},
                                  {'id': 'vg1.30',
                                   't': 'mcq',
                                   'q': "My mother is a ______. She doesn't go to work, but stays at home to look after the family.",
                                   'o': ['breadwinner', 'homemaker', 'housemaid', 'solider']},
                                  {'id': 'vg1.31',
                                   't': 'mcq',
                                   'q': 'My eldest son is strong enough to do the ______ for the family.',
                                   'o': ['heavy lifting', 'household chores', 'cooking', 'laundry']},
                                  {'id': 'vg1.32',
                                   't': 'mcq',
                                   'q': 'Mr Lewis is the ______ of the family, but he still helps his wife with the housework whenever he has time.',
                                   'o': ['breadwinner', 'homemaker', 'housemaid', 'solider']},
                                  {'id': 'vg1.33',
                                   't': 'mcq',
                                   'q': 'My mother is ______ for taking care of the home and the family.',
                                   'o': ['responsible', 'takes the responsibility', 'take the duty', 'Both B & C are correct.']},
                                  {'id': 'vg1.34',
                                   't': 'mcq',
                                   'q': 'Do you have to do ______?',
                                   'o': ['the mess', 'your bed', 'the washing-up', 'the cook']},
                                  {'id': 'vg1.35',
                                   't': 'mcq',
                                   'q': 'My responsibility is to wash the dishes and ______ the rubbish.',
                                   'o': ['take up', 'get out', 'get up', 'put out']}]},
                       {'id': 'vg2',
                        'instr': 'E4: Mark the letter A, B, C or D to indicate the correct answer to each of the following questions.',
                        'items': [{'id': 'vg2.1',
                                   't': 'mcq',
                                   'q': 'He ______ to the cinema yesterday evening.',
                                   'o': ['has gone', 'goes', 'went', 'had gone']},
                                  {'id': 'vg2.2',
                                   't': 'mcq',
                                   'q': 'Jim ______ a book at the moment.',
                                   'o': ['is reading', 'had read', 'reads', 'has read']},
                                  {'id': 'vg2.3',
                                   't': 'mcq',
                                   'q': 'I’m busy at the moment, ______ on the computer.',
                                   'o': ['I work', 'I’m worked', 'I’m working', 'I worked']},
                                  {'id': 'vg2.4',
                                   't': 'mcq',
                                   'q': 'Don’t bother me while I ______.',
                                   'o': ['am working', 'was working', 'will work', 'will have completed']},
                                  {'id': 'vg2.5',
                                   't': 'mcq',
                                   'q': 'My brother ______ out at weekend.',
                                   'o': ['doesn’t usually go', 'does usually not go', 'doesn’t usually goes', 'usually doesn’t goes']},
                                  {'id': 'vg2.6',
                                   't': 'mcq',
                                   'q': 'Every day, my sister ______ the floor.',
                                   'o': ['usually clean', 'cleans usually', 'usually cleaned', 'usually cleans']},
                                  {'id': 'vg2.7', 't': 'mcq', 'q': 'Listen! Someone ______.', 'o': ['is singing', 'are singing', 'sings', 'sing']},
                                  {'id': 'vg2.8',
                                   't': 'mcq',
                                   'q': 'First thing in the morning, I ______ a cup of milk tea.',
                                   'o': ['has', 'am having', 'have', 'will have']},
                                  {'id': 'vg2.9',
                                   't': 'mcq',
                                   'q': 'Anita ______ very hard at the moment.',
                                   'o': ['is studying', 'studies', 'studied', 'has studied']},
                                  {'id': 'vg2.10',
                                   't': 'mcq',
                                   'q': 'I usually ______ to school by bus.',
                                   'o': ['went', 'am going', 'go', 'have gone']},
                                  {'id': 'vg2.11',
                                   't': 'mcq',
                                   'q': 'Our friends ______ for the fashion show now.',
                                   'o': ['is preparing', 'are preparing', 'prepares', 'prepare']},
                                  {'id': 'vg2.12',
                                   't': 'mcq',
                                   'q': 'All staff in this restaurant ______ an urgent meeting right now.',
                                   'o': ['are attending', 'is attending', 'attends', 'attend']},
                                  {'id': 'vg2.13',
                                   't': 'mcq',
                                   'q': 'Yesterday morning I ______ up early.',
                                   'o': ['got', 'get', 'was getting', 'had got']},
                                  {'id': 'vg2.14',
                                   't': 'mcq',
                                   'q': 'Please don’t make so much noise. I ______.',
                                   'o': ['studying', 'study', 'am studying', 'studied']},
                                  {'id': 'vg2.15',
                                   't': 'mcq',
                                   'q': 'I ______ a bike to school every day but today I ______ to school by bus because it was stolen yesterday.',
                                   'o': ['rode - went', 'ride - am going', 'ride - go', 'is riding - am going']},
                                  {'id': 'vg2.16',
                                   't': 'mcq',
                                   'q': 'Water ______ at 100 degrees Celsius.',
                                   'o': ['boils', 'boiled', 'is boiling', 'will boil']},
                                  {'id': 'vg2.17',
                                   't': 'mcq',
                                   'q': 'Who ______ the guitar in that room, Hoa?',
                                   'o': ['playing', 'is playing', 'play', 'plays']},
                                  {'id': 'vg2.18',
                                   't': 'mcq',
                                   'q': 'My mother often ______ to the market in the morning, but today she ______ at noon.',
                                   'o': ['goes/goes', 'go/goes', 'goes/is going', 'is going/goes']},
                                  {'id': 'vg2.19',
                                   't': 'mcq',
                                   'q': 'Bich sometimes ______ chicken noodle soup for breakfast.',
                                   'o': ['are having', 'is having', 'have', 'has']},
                                  {'id': 'vg2.20',
                                   't': 'mcq',
                                   'q': '______ she ______ in Hue at the moment?',
                                   'o': ['Does/live', 'Is/living', 'Did/live', 'Was/living']},
                                  {'id': 'vg2.21',
                                   't': 'mcq',
                                   'q': 'Jenny often ______ jeans and T-shirt at school but she ______ a gorgeous dress today.',
                                   'o': ['wears - is wearing', 'is wearing - wears', 'wear - is wearing', 'wears - wears']},
                                  {'id': 'vg2.22',
                                   't': 'mcq',
                                   'q': 'He usually ______ her at weekend but now he ______ in bed because of his severe illness.',
                                   'o': ['visits/stays', 'visits/staying', 'visited/stays', 'visits/is staying']},
                                  {'id': 'vg2.23',
                                   't': 'mcq',
                                   'q': 'Hoang and Phong ______ football as they’re having class now.',
                                   'o': ['don’t play', 'are playing', 'doesn’t play', 'aren’t playing']},
                                  {'id': 'vg2.24',
                                   't': 'mcq',
                                   'q': 'Don’t make noise, children! Parents ______.',
                                   'o': ['sleep', 'are sleeping', 'were sleeping', 'slept']},
                                  {'id': 'vg2.25',
                                   't': 'mcq',
                                   'q': 'Look! Minh ______ on stage. She looks so beautiful.',
                                   'o': ['sings', 'are singing', 'is singing', 'sang']},
                                  {'id': 'vg2.26',
                                   't': 'mcq',
                                   'q': 'I am busy at the moment, I ______ my home assignment.',
                                   'o': ['do', 'am doing', 'have been doing', 'will do']},
                                  {'id': 'vg2.27',
                                   't': 'mcq',
                                   'q': 'After the physics lesson, the children know that water ______ at 100 degrees C.',
                                   'o': ['will boil', 'is boiling', 'boils', 'boil']},
                                  {'id': 'vg2.28',
                                   't': 'mcq',
                                   'q': 'Hoang ______ his email four times a week in order not to miss anything important.',
                                   'o': ['checks', 'will check', 'is checking', 'check']},
                                  {'id': 'vg2.29',
                                   't': 'mcq',
                                   'q': 'At the moment, my sister ______ her homework, my brother ______ games.',
                                   'o': ['is making - is playing', 'is doing - is playing', 'does - plays', 'makes - is playing']},
                                  {'id': 'vg2.30',
                                   't': 'mcq',
                                   'q': 'Hurry up, Linh. Other friends ______ for us.',
                                   'o': ['are waiting', 'waits', 'wait', 'is waiting']},
                                  {'id': 'vg2.31',
                                   't': 'mcq',
                                   'q': 'It’s 7.00 p.m. now and we ______ meal together. We usually ______ dinner at that time.',
                                   'o': ['have - eat', 'have - are eating', 'are having - eat', 'are having - are eating']},
                                  {'id': 'vg2.32',
                                   't': 'mcq',
                                   'q': 'Ms. Kim ______ very well when she’s under pressure.',
                                   'o': ['not work', 'don’t work', 'isn’t working', 'doesn’t work']},
                                  {'id': 'vg2.33',
                                   't': 'mcq',
                                   'q': 'Hoa usually ______ charge of doing the washing-up in her family.',
                                   'o': ['takes', 'is taking', 'take', 'will take']},
                                  {'id': 'vg2.34',
                                   't': 'mcq',
                                   'q': 'My mom ______ to the supermarket every Sunday for shopping.',
                                   'o': ['goes', 'go', 'is going', 'are going']},
                                  {'id': 'vg2.35',
                                   't': 'mcq',
                                   'q': 'I’m sorry, Lan is busy now. She ______ her document on the second floor.',
                                   'o': ['are checking', 'check', 'checks', 'is checking']}]},
                       {'id': 'vg3',
                        'instr': 'E5: Complete the following sentences with the correct forms of the words in capitals.',
                        'items': [{'id': 'vg3.1',
                                   't': 'fill',
                                   'q': "It is parents' duty and {_} to join hands to take care of their children and give them a happy home.",
                                   'hint': 'RESPONSIBLE'},
                                  {'id': 'vg3.2',
                                   't': 'fill',
                                   'q': 'I would like to express my {_} to everyone for their hard work.',
                                   'hint': 'GRATEFUL'},
                                  {'id': 'vg3.3', 't': 'fill', 'q': 'The measures should help create jobs and {_} the economy.', 'hint': 'STRONG'},
                                  {'id': 'vg3.4', 't': 'fill', 'q': 'He needs all the support and {_} he can get.', 'hint': 'ENCOURAGE'},
                                  {'id': 'vg3.5', 't': 'fill', 'q': 'She cleans up {_} after she has finished cooking.', 'hint': 'SPOTLESS'}]}]},
           {'id': 'nghe',
            'title': 'Nghe',
            'mode': 'practice',
            'audio': 'botro_nghe.mp3',
            'groups': [{'id': 'li1',
                        'instr': 'E6 – Task 1: Listen to a family expert talking about how the roles of men and women in families have changed. '
                                 'Decide whether the following statements are true (T) or false (F).',
                        'items': [{'id': 'li1.1', 't': 'tf', 'q': 'Men’s and women’s roles in the family have become similar.'},
                                  {'id': 'li1.2', 't': 'tf', 'q': 'Both men and women now work to contribute to the family finances.'},
                                  {'id': 'li1.3',
                                   't': 'tf',
                                   'q': "According to 'equally shared parenting', both men and women have equal chances for recreation."},
                                  {'id': 'li1.4',
                                   't': 'tf',
                                   'q': "According to 'equally shared parenting', the husband’s career is less important than the wife’s."},
                                  {'id': 'li1.5', 't': 'tf', 'q': "Families following 'equally shared parenting' are happier."}]},
                       {'id': 'li2',
                        'instr': 'E6 – Task 2: Answer the questions (tự luận – đối chiếu đáp án mẫu).',
                        'items': [{'id': 'li2.1', 't': 'open', 'q': 'How has the role of men in the family changed?'},
                                  {'id': 'li2.2', 't': 'open', 'q': 'How have men’s and women’s roles become alike?'},
                                  {'id': 'li2.3', 't': 'open', 'q': 'What is the result of ‘equally shared parenting’?'}]}]},
           {'id': 'noi',
            'title': 'Nói (hội thoại)',
            'mode': 'practice',
            'groups': [{'id': 'sp1',
                        'instr': 'E7: Complete the conversations by circling the best answers. Then practise reading them.',
                        'items': [{'id': 'sp1.1',
                                   't': 'mcq',
                                   'q': '<b>Lan:</b> Nam, do you think family routines are necessary?<br><b>Nam:</b> Yes. ______ each family should '
                                        'have some routines to help build strong family bonds.',
                                   'o': ["I'm not sure that", 'I strongly believe that', 'I agree that', 'I hope that']},
                                  {'id': 'sp1.2',
                                   't': 'mcq',
                                   'q': '<b>Lan:</b> What do you think about the British family value of being truthful and honest?<br><b>Nam:</b> '
                                        "______, it's one of the first things parents should teach their children.",
                                   'o': ['In their opinion', 'In a nutshell', 'In my own way', 'In my opinion']},
                                  {'id': 'sp1.3',
                                   't': 'mcq',
                                   'q': '<b>Lan:</b> Nam, do you think parents should help their children do their homework?<br><b>Nam:</b> Well, '
                                        '______ parents should let their children do their homework by themselves so they can become independent.',
                                   'o': ["I don't think", 'I wish that', 'I believe that', 'I hope that']},
                                  {'id': 'sp1.4',
                                   't': 'mcq',
                                   'q': '<b>Lan:</b> Do you think teens should learn how to cook?<br><b>Nam:</b> Well, ______ they can learn it when '
                                        'they start their own families. As teens, they should spend all their time on study.',
                                   'o': ['I suppose that', 'I hope that', 'I doubt that', 'I agree that']}]},
                       {'id': 'sp2',
                        'instr': 'E8: Talk about why children should or should not do housework. (nói/viết – đối chiếu bài mẫu)',
                        'items': [{'id': 'sp2.1', 't': 'open', 'q': 'Talk about why children should or should not do housework.'}]}]},
           {'id': 'doc',
            'title': 'Đọc hiểu',
            'mode': 'practice',
            'groups': [{'id': 're1',
                        'instr': 'E9: Read the following passage and mark the letter A, B, C, or D to indicate the correct word or phrase that best '
                                 'fits each of the numbered blanks.',
                        'passage': '<p>A recent study shows that an unequal share of household chores is still the norm in many households, <b>(1) '
                                   '______</b> the fact that many more women now have jobs. In a survey of 1,256 people <b>(2) ______</b> between 18 '
                                   'and 65, men said they contributed an average of 37 per cent of the total housework, while the women <b>(3) '
                                   '______</b> their share to be nearly double that, at 70 per cent. This ratio was not affected by <b>(4) '
                                   '______</b> the woman was working or not.</p><p>When they were asked what they thought was a fair division of '
                                   'labour, women with jobs felt that housework should <b>(5) ______</b> shared equally between male and female '
                                   'partners. Women who did not work outside the home were satisfied to perform 80 per cent - the majority of '
                                   'housework - if their husbands did the <b>(6) ______</b>. Research has shown that if levels increase beyond these '
                                   'percentages, women become unhappy and anxious, and feel they are <b>(7) ______</b>.</p><p>After marriage, a '
                                   'woman is reported to increase her household workload <b>(8) ______</b> 14 hours per week, but for men <b>(9) '
                                   '______</b> amount is just 90 minutes. So the division of labour becomes unbalanced, <b>(10) ______</b> the man’s '
                                   'share increases much less than the woman’s. It is the inequality and <b>(11) ______</b> of respect, not the '
                                   'actual number of hours, which leads to <b>(12) ______</b> and depression. The research even <b>(13) ______</b> '
                                   'housework as thankless and unfulfilling.</p>',
                        'items': [{'id': 're1.1', 't': 'mcq', 'q': 'Blank (1)', 'o': ['in spite', 'despite', 'although', 'even']},
                                  {'id': 're1.2', 't': 'mcq', 'q': 'Blank (2)', 'o': ['aged', 'aging', 'age', 'ages']},
                                  {'id': 're1.3', 't': 'mcq', 'q': 'Blank (3)', 'o': ['guessed', 'judged', 'estimated', 'valued']},
                                  {'id': 're1.4', 't': 'mcq', 'q': 'Blank (4)', 'o': ['what', 'whether', 'which', 'that']},
                                  {'id': 're1.5', 't': 'mcq', 'q': 'Blank (5)', 'o': ['being', 'been', 'to be', 'be']},
                                  {'id': 're1.6', 't': 'mcq', 'q': 'Blank (6)', 'o': ['remaining', 'remain', 'remainder', 'remained']},
                                  {'id': 're1.7', 't': 'mcq', 'q': 'Blank (7)', 'o': ['essential', 'slight', 'worthy', 'unimportant']},
                                  {'id': 're1.8', 't': 'mcq', 'q': 'Blank (8)', 'o': ['by', 'to', 'at', 'in']},
                                  {'id': 're1.9', 't': 'mcq', 'q': 'Blank (9)', 'o': ['a', 'an', 'the', 'some']},
                                  {'id': 're1.10', 't': 'mcq', 'q': 'Blank (10)', 'o': ['as', 'so', 'but', 'then']},
                                  {'id': 're1.11', 't': 'mcq', 'q': 'Blank (11)', 'o': ['waste', 'loss', 'disadvantage', 'death']},
                                  {'id': 're1.12', 't': 'mcq', 'q': 'Blank (12)', 'o': ['anxiety', 'anxious', 'anxiously', 'anxiousness']},
                                  {'id': 're1.13', 't': 'mcq', 'q': 'Blank (13)', 'o': ['draws', 'expresses', 'reports', 'describes']}]},
                       {'id': 're2',
                        'instr': 'E10: Read the following passage and mark the letter A, B, C, or D to indicate the correct answer to each of the '
                                 'questions.',
                        'passage': '<p>Family types vary in different countries and among different cultures. In Western, industrialized societies, '
                                   'the nuclear family ranks as the most common family type. It consists of a father, a mother and their children. '
                                   'But nuclear families exist together with many other types of family units. In the single-parent family, for '
                                   'example, a mother or a father heads the family alone. A <u>blended</u> family is formed when a divorced or '
                                   'widowed parent remarries. As divorce rates have risen, the number of single-parent and blended families has '
                                   'increased.</p><p>In many parts of the world, parents and children live together with other family members under '
                                   'the same roof. These complex families usually contain several generations of family members, including '
                                   'grandparents, parents and children. They may also include brothers or sisters and their families, uncles, aunts '
                                   'and cousins. Even when relatives do not live together, they still consider themselves members of the same '
                                   'extended family, which includes grandparents, uncles, aunts and cousins.</p>',
                        'items': [{'id': 're2.1',
                                   't': 'mcq',
                                   'q': 'The nuclear family ranks as the most common family type ______.',
                                   'o': ['in many industrialized countries',
                                         'in countries with nuclear weapons',
                                         'that consists of more than two generations',
                                         'that leads to the divorce of parents']},
                                  {'id': 're2.2',
                                   't': 'mcq',
                                   'q': 'In the single-parent family, ______.',
                                   'o': ['there are often no children',
                                         'only one parent lives with his or her child or children',
                                         'the number of blended children has increased',
                                         'children live with their grandparents']},
                                  {'id': 're2.3',
                                   't': 'mcq',
                                   'q': 'Grandparents, parents and children are mentioned as ______.',
                                   'o': ['the three typical generations of an extended family',
                                         'three branches of a family tree',
                                         'the closest and happiest relatives in family units',
                                         'a complex combination']},
                                  {'id': 're2.4',
                                   't': 'mcq',
                                   'q': 'The second paragraph is about ______.',
                                   'o': ['American culture',
                                         'relatives and family members',
                                         'the relationship between family members',
                                         'the extended family']},
                                  {'id': 're2.5',
                                   't': 'mcq',
                                   'q': 'The word “<u>blended</u>” in paragraph 1 is closest in meaning to ______.',
                                   'o': ['complex', 'married', 'mixed', 'formed']}]},
                       {'id': 're3',
                        'instr': 'E11: Read the following passage and mark the letter A, B, C, or D to indicate the correct answer to each of the '
                                 'questions.',
                        'passage': '<h4>Building positive family relationships</h4><p>The ordinary, everyday things that families do together can '
                                   'help build strong relationships with teenagers. Regular family meals are a great chance for everyone to chat '
                                   'about their day, or about interesting things that are going on or coming up. If parents encourage everyone to '
                                   'have a say, no one will feel they’re being put on the spot to talk. Also, many families find that meals are more '
                                   'enjoyable when the TV isn’t turned on!</p><p>We should all take turns choosing outdoor activities for our '
                                   'families. A relaxing holiday or weekend away together as a family can also build togetherness.</p><p>One-on-one '
                                   'time with the child gives the parents the chance to stay connected and enjoy each other’s company. It can also '
                                   'be a chance to share thoughts and feelings.</p><p>Parents should celebrate the child’s accomplishments, share '
                                   'his disappointments, and show interest in his hobbies. Sometimes it’s just a matter of showing up to watch the '
                                   'child play sport or music, or giving him a lift to extracurricular activities.</p><p>Family traditions, routines '
                                   'and rituals can help parents and their children set aside regular dates and special times. For example, we might '
                                   'have a movie night together, a favourite meal or cooking session on a particular night, a family games afternoon '
                                   'or an evening walk together.</p><p>Agreed household responsibilities give kids of all ages the sense that '
                                   'they’re making an important contribution to family life. These could be things like chores, shopping or helping '
                                   'older or younger members of the family.</p>',
                        'items': [{'id': 're3.1',
                                   't': 'mcq',
                                   'q': 'Regular family meals are a great chance for everyone ______.',
                                   'o': ['to have an opportunity to share their daily activities',
                                         'to talk about TV programmes during the meal',
                                         'to have the spot to talk about',
                                         'to talk about interesting things that are coming soon']},
                                  {'id': 're3.2',
                                   't': 'mcq',
                                   'q': 'The following things are true about outdoor activities for our families EXCEPT ______.',
                                   'o': ['all family members try to find out suitable activities',
                                         'they should be held on holidays or at weekends',
                                         'they offer a chance to share secret thoughts and feelings',
                                         'they offer the pleasant feeling of being united']},
                                  {'id': 're3.3',
                                   't': 'mcq',
                                   'q': 'Parents can show their attention to their child by all these things EXCEPT ______.',
                                   'o': ['watching the child play sport or music',
                                         'giving him a lift to extracurricular activities',
                                         'having a movie night together',
                                         'setting aside regular dates to do housework']},
                                  {'id': 're3.4',
                                   't': 'mcq',
                                   'q': 'Children who share household chores with their parents will ______.',
                                   'o': ['enjoy each other’s company',
                                         'make the family life better',
                                         'be given a chance to do extracurricular activities',
                                         'have a family games afternoon or an evening walk together']},
                                  {'id': 're3.5',
                                   't': 'mcq',
                                   'q': 'The main idea of the passage is ______.',
                                   'o': ['to give advice on staying connected and enjoying each other’s company',
                                         'how to share household chores between family members',
                                         'to offer pieces of advice to improve family relationships',
                                         'the important role of family traditions, routines and rituals']}]}]},
           {'id': 'viet',
            'title': 'Viết',
            'mode': 'practice',
            'groups': [{'id': 'wr1',
                        'instr': 'E12: Use the verbs in their correct forms and add some words where necessary to make meaningful sentences.',
                        'items': [{'id': 'wr1.1',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> Mr Thanh / hate / do / housework / but / he still / clean / the house / once / '
                                        'week.<br>Câu hoàn chỉnh: {_}'},
                                  {'id': 'wr1.2',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> I / have / a holiday / my family / in Mai Chau / now. / We / spend / our summer holidays '
                                        'here / every year.<br>Câu hoàn chỉnh: {_}'},
                                  {'id': 'wr1.3',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> It / be / important / children / learn / some life skills / home.<br>Câu hoàn chỉnh: {_}'},
                                  {'id': 'wr1.4',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> Parents / have / teach / their children / be honest and show respect to older people / an '
                                        'early age.<br>Câu hoàn chỉnh: {_}'},
                                  {'id': 'wr1.5',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> Jane / think of / apply / another job. / She / think / her present job / be / '
                                        'boring.<br>Câu hoàn chỉnh: {_}'},
                                  {'id': 'wr1.6',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> Doing housework / help / children / learn / take care / themselves.<br>Câu hoàn chỉnh: '
                                        '{_}'},
                                  {'id': 'wr1.7',
                                   't': 'fill',
                                   'long': True,
                                   'q': "<b>Từ gợi ý:</b> Family routines / connected / children's health / academic achievement.<br>Câu hoàn chỉnh: "
                                        '{_}'},
                                  {'id': 'wr1.8',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> Children / should / learn / choose / right / kind of clothes / right occasion.<br>Câu hoàn '
                                        'chỉnh: {_}'}]},
                       {'id': 'wr2',
                        'instr': 'E13: Write a paragraph (120 – 150 words) about one of your family routines. (tự luận – xem bài mẫu)',
                        'items': [{'id': 'wr2.1',
                                   't': 'open',
                                   'q': 'Write a paragraph (120 – 150 words) about one of your family routines. Use the following questions as '
                                        'cues:<ol><li>What is the routine?</li><li>How often / When do you do it?</li><li>What are the activities? '
                                        'What does each family member do?</li><li>How do you feel about the routine?</li></ol>'}]}]}]}
