# -*- coding: utf-8 -*-
"""Dữ liệu nội dung SET (sinh từ file Word bằng tools/gen_units.py rồi có thể chỉnh tay).
Đáp án + giải thích: xem file *_dapan.py cùng tên."""

SET = {'id': 'lop10-u3-botro',
 'title': 'Unit 3 – Music: Bài tập bổ trợ',
 'grade': 10,
 'unit': 3,
 'theory': '<p><b>A. VOCABULARY</b> (Từ vựng)</p><table '
           'class="th"><tr><th>Word</th><th>Type</th><th>Pronunciation</th><th>Meaning</th></tr><tr><td>ancient</td><td>(adj)</td><td>/ˈeɪnʃənt/</td><td>cổ '
           'xưa</td></tr><tr><td>argument</td><td>(n)</td><td>/ˈɑːɡjumənt/</td><td>cuộc tranh '
           'cãi</td></tr><tr><td>artist</td><td>(n)</td><td>/ˈɑːtɪst/</td><td>người nghệ '
           'sĩ</td></tr><tr><td>audience</td><td>(n)</td><td>/ˈɔːdiəns/</td><td>khán '
           'giả</td></tr><tr><td>award</td><td>(n)</td><td>/əˈwɔːd/</td><td>giải thưởng</td></tr><tr><td>bamboo '
           'clapper</td><td>(n)</td><td>/ˌbæmˈbuː ˈklæpə(r)/</td><td>phách</td></tr><tr><td>band</td><td>(n)</td><td>/bænd/</td><td>ban '
           'nhạc</td></tr><tr><td>be eliminated</td><td>(v)</td><td>/biː ɪˈlɪmɪneɪtɪd/</td><td>bị '
           'loại</td></tr><tr><td>career</td><td>(n)</td><td>/kəˈrɪə(r)/</td><td>sự '
           'nghiệp</td></tr><tr><td>combine</td><td>(v)</td><td>/kəmˈbaɪn/</td><td>kết '
           'hợp</td></tr><tr><td>comment</td><td>(n)</td><td>/ˈkɒment/</td><td>lời bình '
           'luận</td></tr><tr><td>competition</td><td>(n)</td><td>/ˌkɒmpəˈtɪʃn/</td><td>cuộc '
           'thi</td></tr><tr><td>concert</td><td>(n)</td><td>/ˈkɒnsət/</td><td>buổi hòa '
           'nhạc</td></tr><tr><td>costume</td><td>(n)</td><td>/ˈkɒstjuːm/</td><td>trang '
           'phục</td></tr><tr><td>culture</td><td>(n)</td><td>/ˈkʌltʃə(r)/</td><td>văn '
           'hóa</td></tr><tr><td>decide</td><td>(v)</td><td>/dɪˈsaɪd/</td><td>quyết '
           'định</td></tr><tr><td>decoration</td><td>(n)</td><td>/ˌdekəˈreɪʃn/</td><td>việc trang '
           'trí</td></tr><tr><td>delay</td><td>(v)</td><td>/dɪˈleɪ/</td><td>hoãn lại</td></tr><tr><td>depend on</td><td>(v)</td><td>/dɪˈpend '
           'ɒn/</td><td>phụ thuộc vào</td></tr><tr><td>dress up</td><td>(v)</td><td>/dres ʌp/</td><td>ăn mặc đẹp '
           'đẽ</td></tr><tr><td>drum</td><td>(n)</td><td>/drʌm/</td><td>cái '
           'trống</td></tr><tr><td>eliminate</td><td>(v)</td><td>/ɪˈlɪmɪneɪt/</td><td>loại ra, loại '
           'trừ</td></tr><tr><td>enjoy</td><td>(v)</td><td>/ɪnˈdʒɔɪ/</td><td>thích, tận '
           'hưởng</td></tr><tr><td>famous</td><td>(adj)</td><td>/ˈfeɪməs/</td><td>nổi '
           'tiếng</td></tr><tr><td>festival</td><td>(n)</td><td>/ˈfestɪvl/</td><td>buổi lễ '
           'hội</td></tr><tr><td>friendship</td><td>(n)</td><td>/ˈfrendʃɪp/</td><td>tình '
           'bạn</td></tr><tr><td>guest</td><td>(n)</td><td>/ɡest/</td><td>khách '
           'mời</td></tr><tr><td>hesitate</td><td>(v)</td><td>/ˈhezɪteɪt/</td><td>do dự</td></tr><tr><td>hold</td><td>(v)</td><td>/həʊld/</td><td>tổ '
           'chức</td></tr><tr><td>identify with</td><td>(v)</td><td>/aɪˈdentɪfaɪ wɪð/</td><td>hòa nhập với</td></tr><tr><td>in search '
           'of</td><td>(v)</td><td>/ɪn sɜːtʃ əv/</td><td>tìm kiếm</td></tr><tr><td>information</td><td>(n)</td><td>/ˌɪnfəˈmeɪʃn/</td><td>thông '
           'tin</td></tr><tr><td>judge</td><td>(n)</td><td>/dʒʌdʒ/</td><td>giám '
           'khảo</td></tr><tr><td>live</td><td>(adj,adv)</td><td>/lɪv/</td><td>trực '
           'tiếp</td></tr><tr><td>location</td><td>(n)</td><td>/ləʊˈkeɪʃn/</td><td>vị trí, địa '
           'điểm</td></tr><tr><td>main</td><td>(adj)</td><td>/meɪn/</td><td>chính</td></tr><tr><td>moon-shaped lute</td><td>(n)</td><td>/muːn-ʃeɪpt '
           'luːt/</td><td>đàn nguyệt</td></tr><tr><td>musical instrument</td><td>(n)</td><td>/ˈmjuːzɪkəl ˈɪnstrəmənt/</td><td>nhạc '
           'cụ</td></tr><tr><td>opinion</td><td>(n)</td><td>/əˈpɪnjən/</td><td>ý '
           'kiến</td></tr><tr><td>ordinary</td><td>(adj)</td><td>/ˈɔːdnri/</td><td>bình '
           'thường</td></tr><tr><td>organiser</td><td>(n)</td><td>/ˈɔːɡənaɪzə(r)/</td><td>người tổ '
           'chức</td></tr><tr><td>origin</td><td>(n)</td><td>/ˈɒrɪdʒɪn/</td><td>nguồn '
           'gốc</td></tr><tr><td>participant</td><td>(n)</td><td>/pɑːˈtɪsɪpənt/</td><td>người tham dự</td></tr><tr><td>participate '
           'in</td><td>(v)</td><td>/pɑːrˈtɪsəpeɪt ɪn/</td><td>tham gia vào</td></tr><tr><td>perform</td><td>(v)</td><td>/pəˈfɔːm/</td><td>trình '
           'diễn</td></tr><tr><td>performance</td><td>(n)</td><td>/pəˈfɔːməns/</td><td>buổi trình '
           'diễn</td></tr><tr><td>performer</td><td>(n)</td><td>/pəˈfɔːmə(r)/</td><td>người biểu '
           'diễn</td></tr><tr><td>popular</td><td>(adj)</td><td>/ˈpɒpjələ(r)/</td><td>phổ '
           'biến</td></tr><tr><td>praise</td><td>(v)</td><td>/preɪz/</td><td>ca '
           'ngợi</td></tr><tr><td>preparation</td><td>(n)</td><td>/ˌprepəˈreɪʃn/</td><td>sự chuẩn '
           'bị</td></tr><tr><td>programme</td><td>(n)</td><td>/ˈprəʊɡræm/</td><td>chương '
           'trình</td></tr><tr><td>reach</td><td>(v)</td><td>/riːtʃ/</td><td>đạt '
           'được</td></tr><tr><td>reality</td><td>(n)</td><td>/riˈæləti/</td><td>thực '
           'tế</td></tr><tr><td>receive</td><td>(v)</td><td>/rɪˈsiːv/</td><td>nhận được</td></tr><tr><td>runner-up</td><td>(n)</td><td>/ˌrʌnər '
           'ˈʌp/</td><td>người về nhì, á quân</td></tr><tr><td>semi-final</td><td>(n)</td><td>/ˌsemi ˈfaɪnl/</td><td>vòng bán '
           'kết</td></tr><tr><td>singer</td><td>(n)</td><td>/ˈsɪŋə(r)/</td><td>ca '
           'sĩ</td></tr><tr><td>single</td><td>(n)</td><td>/ˈsɪŋɡl/</td><td>đĩa đơn</td></tr><tr><td>social media</td><td>(n)</td><td>/soʊʃəl '
           'ˈmiːdiə/</td><td>mạng xã hội</td></tr><tr><td>spread</td><td>(v)</td><td>/spred/</td><td>trải '
           'rộng</td></tr><tr><td>stage</td><td>(n)</td><td>/steɪdʒ/</td><td>sân khấu</td></tr><tr><td>take place</td><td>(v)</td><td>/teɪk '
           'pleɪs/</td><td>tổ chức</td></tr><tr><td>talented</td><td>(adj)</td><td>/ˈtæləntɪd/</td><td>tài '
           'năng</td></tr><tr><td>ticket</td><td>(n)</td><td>/ˈtɪkɪt/</td><td>vé</td></tr><tr><td>trumpet</td><td>(n)</td><td>/ˈtrʌmpɪt/</td><td>kèn '
           'trumpet</td></tr><tr><td>tv series</td><td>(n)</td><td>/ˌtiːˈviː ˈsɪriːz/</td><td>phim truyền hình dài '
           'tập</td></tr><tr><td>upload</td><td>(v)</td><td>/ˌʌpˈləʊd/</td><td>tải '
           'lên</td></tr><tr><td>voice</td><td>(n)</td><td>/vɔɪs/</td><td>giọng</td></tr><tr><td>worship</td><td>(v)</td><td>/ˈwɜːʃɪp/</td><td>tôn '
           'thờ</td></tr></table><p><b>B. GRAMMAR</b> (Ngữ pháp)</p><p><b>I. COMPOUND SENTENCES (Câu ghép)</b></p><p><b>Câu ghép</b> là câu gồm 2 '
           'hoặc nhiều <b>mệnh đề độc lập</b>, nối với nhau bằng liên từ (conjunction): <b>Mệnh đề + LIÊN TỪ + Mệnh đề</b>. Các liên từ thường gặp '
           '(FANBOYS):</p><table class="th"><tr><th>Liên từ</th><th>Nghĩa</th><th>Cách dùng</th></tr><tr><td><b>F</b>or</td><td>bởi vì</td><td>chỉ '
           'nguyên nhân</td></tr><tr><td><b>A</b>nd</td><td>và</td><td>thêm ý</td></tr><tr><td><b>N</b>or</td><td>cũng không</td><td>bổ sung một ý '
           'phủ định (đảo ngữ sau nor)</td></tr><tr><td><b>B</b>ut</td><td>nhưng</td><td>chỉ sự trái '
           'ngược</td></tr><tr><td><b>O</b>r</td><td>hoặc</td><td>chỉ sự lựa chọn</td></tr><tr><td><b>Y</b>et</td><td>nhưng (vẫn)</td><td>chỉ ý trái '
           'ngược, bất ngờ</td></tr><tr><td><b>S</b>o</td><td>vì vậy</td><td>chỉ kết quả</td></tr></table><p><b>Ví dụ:</b></p><p>- Her family '
           'planned to travel this summer, <b>but</b> the father was sick.</p><p>- Nam’s house is very old, <b>so</b> he is going to move to a new '
           'apartment.</p><p>- My son wants to have a puppy for his birthday, <b>for</b> dogs are very cute.</p><p>- My brother is a doctor, '
           '<b>and</b> my sister is a nurse.</p><p>- We don’t go out, <b>nor</b> do we want to do anything on the weekend.</p><p>- You should call '
           'her back, <b>or</b> she will come here to talk to you.</p><p>- My children don’t like vegetables, <b>yet</b> they eat them '
           'anyway.</p><p><b>II. TO-INFINITIVE AND BARE INFINITIVE (Động từ To V0 và V0)</b></p><p><b>1. Động từ + TO V0 (V + to V0)</b></p><table '
           'class="th"><tr><td>afford (đủ khả năng)</td><td>agree (đồng ý)</td><td>appear (xuất hiện)</td><td>arrange (sắp '
           'xếp)</td></tr><tr><td>decide (quyết định)</td><td>demand (yêu cầu)</td><td>deserve (xứng đáng)</td><td>expect (mong '
           'đợi)</td></tr><tr><td>fail (thất bại)</td><td>hesitate (do dự)</td><td>hope (hi vọng)</td><td>learn (học)</td></tr><tr><td>manage (xoay '
           'sở)</td><td>mean (có ý định)</td><td>need (cần)</td><td>offer (đề nghị)</td></tr><tr><td>plan (lên kế hoạch)</td><td>prepare (chuẩn '
           'bị)</td><td>pretend (giả vờ)</td><td>promise (hứa)</td></tr><tr><td>refuse (từ chối)</td><td>seem (dường như)</td><td>threaten (đe '
           'doạ)</td><td>volunteer (tình nguyện)</td></tr><tr><td>wait (đợi)</td><td>want (muốn)</td><td>wish (mong)</td><td>would like '
           '(muốn)</td></tr><tr><td>would love (yêu thích)</td><td></td></tr></table><p><b>Ví dụ:</b> Maria <b>decided to continue</b> her education '
           'after a gap year. / He <b>manages to fix</b> his daughter’s bicycle. / Most women <b>expect to get</b> more help with the housework from '
           'their husbands. / I’m <b>planning to take</b> my children to the new amusement park this weekend.</p><p><b>2. Động từ + tân ngữ + TO V0 '
           '(V + O + to V0)</b></p><table class="th"><tr><td>advise (khuyên)</td><td>allow (cho phép)</td><td>invite (mời)</td><td>ask (yêu '
           'cầu)</td></tr><tr><td>permit (cho phép)</td><td>challenge (thách thức)</td><td>persuade (thuyết phục)</td><td>convince (thuyết '
           'phục)</td></tr><tr><td>remind (nhắc nhở)</td><td>dare (dám)</td><td>require (đòi hỏi)</td><td>encourage (khuyến '
           'khích)</td></tr><tr><td>teach (dạy)</td><td>expect (mong đợi)</td><td>tell (bảo)</td><td>urge (thúc giục)</td></tr><tr><td>force '
           '(buộc)</td><td>want (muốn)</td><td>hire (thuê)</td><td>warn (cảnh báo)</td></tr></table><p><b>Ví dụ:</b> He somehow persuades <u>his '
           'parents</u> <b>to buy</b> him a motorbike. / I’ve warned <u>you</u> many times <b>not to leave</b> the front door unlocked. / His '
           'parents encourage <u>him</u> <b>to take part</b> in the competition.</p><p><b>3. Động từ + tân ngữ + V0 (V + O + V0)</b></p><table '
           'class="th"><tr><th>Cấu trúc</th><th>Nghĩa</th></tr><tr><td><b>make + O + V0</b></td><td>khiến/bắt ai làm gì</td></tr><tr><td><b>let + O '
           '+ V0</b></td><td>để cho ai làm gì</td></tr><tr><td><b>help + O + (to) V0</b></td><td>giúp ai làm gì</td></tr><tr><td><b>Let’s + '
           'V0</b></td><td>chúng ta hãy</td></tr><tr><td><b>see / hear / smell / feel / notice / watch + O + V0</b></td><td>thấy/nghe… ai làm gì '
           '(chứng kiến toàn bộ hành động)</td></tr></table><p><b>Ví dụ:</b> I heard <u>him</u> <b>open</b> the window last night. / Our teacher '
           'made <u>us</u> <b>apologise</b> for our rudeness. / Lucy helps <u>me</u> <b>(to) do</b> my homework. / Mary’s parents let <u>her</u> '
           '<b>go</b> to the movie with her friends. / <b>Let’s go</b> out for dinner!</p>',
 'pages': [{'id': 'phat-am',
            'title': 'Phát âm & trọng âm',
            'mode': 'practice',
            'groups': [{'id': 'ph1',
                        'instr': 'E1: Mark the letter A, B, C, or D to indicate the word that differs from the other three in the position of the '
                                 'primary stress in each of the following questions.',
                        'items': [{'id': 'ph1.1', 't': 'mcq', 'q': '', 'o': ['become', 'idol', 'comment', 'season']},
                                  {'id': 'ph1.2', 't': 'mcq', 'q': '', 'o': ['perform', 'release', 'receive', 'talent']},
                                  {'id': 'ph1.3', 't': 'mcq', 'q': '', 'o': ['talent', 'artist', 'award', 'famous']},
                                  {'id': 'ph1.4', 't': 'mcq', 'q': '', 'o': ['theatre', 'movie', 'famous', 'attend']},
                                  {'id': 'ph1.5', 't': 'mcq', 'q': '', 'o': ['enjoy', 'perform', 'suffer', 'agree']},
                                  {'id': 'ph1.6', 't': 'mcq', 'q': '', 'o': ['weather', 'birthday', 'boring', 'expect']},
                                  {'id': 'ph1.7', 't': 'mcq', 'q': '', 'o': ['singer', 'receive', 'programme', 'lyrics']},
                                  {'id': 'ph1.8', 't': 'mcq', 'q': '', 'o': ['compose', 'careful', 'second', 'album']},
                                  {'id': 'ph1.9', 't': 'mcq', 'q': '', 'o': ['upload', 'theatre', 'receive', 'guitar']},
                                  {'id': 'ph1.10', 't': 'mcq', 'q': '', 'o': ['singer', 'compose', 'common', 'programme']},
                                  {'id': 'ph1.11', 't': 'mcq', 'q': '', 'o': ['favour', 'enjoy', 'reveal', 'perform']},
                                  {'id': 'ph1.12', 't': 'mcq', 'q': '', 'o': ['common', 'music', 'people', 'perform']},
                                  {'id': 'ph1.13', 't': 'mcq', 'q': '', 'o': ['melody', 'festival', 'positive', 'contestant']}]},
                       {'id': 'ph2',
                        'instr': 'E2: Mark the letter A, B, C or D to indicate the word whose underlined part differs from the other three in '
                                 'pronunciation in each of the following questions.',
                        'items': [{'id': 'ph2.1', 't': 'mcq', 'q': '', 'o': ['<u>s</u>ingle', 'mu<u>s</u>ic', 'conte<u>s</u>t', 'relea<u>s</u>e']},
                                  {'id': 'ph2.2',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['compo<u>se</u>', 'purcha<u>se</u>', 'relea<u>se</u>', 'increa<u>se</u>']},
                                  {'id': 'ph2.3',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['ver<u>s</u>ion', 'proce<u>ss</u>', 'mode<u>s</u>t', 'conte<u>s</u>tant']},
                                  {'id': 'ph2.4', 't': 'mcq', 'q': '', 'o': ['instr<u>u</u>ment', 'platin<u>u</u>m', 'deb<u>u</u>t', 'alb<u>u</u>m']},
                                  {'id': 'ph2.5',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['elimin<u>ate</u>', 'nomin<u>ate</u>', 'origin<u>ate</u>', 'passion<u>ate</u>']},
                                  {'id': 'ph2.6', 't': 'mcq', 'q': '', 'o': ['mom<u>ent</u>', 'cont<u>ent</u>', 'par<u>ent</u>', 'tal<u>ent</u>']},
                                  {'id': 'ph2.7', 't': 'mcq', 'q': '', 'o': ['lat<u>est</u>', 'cont<u>est</u>', 'requ<u>est</u>', 'sugg<u>est</u>']},
                                  {'id': 'ph2.8',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['deb<u>ate</u>', 'commemor<u>ate</u>', 'certific<u>ate</u>', 'educ<u>ate</u>']},
                                  {'id': 'ph2.9', 't': 'mcq', 'q': '', 'o': ['cure<u>nt</u>', 'mom<u>ent</u>', 'tale<u>nt</u>', 'comm<u>ent</u>']},
                                  {'id': 'ph2.10',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['prot<u>est</u>', 'arr<u>est</u>', '<u>est</u>ablish', 'n<u>est</u>']}]}]},
           {'id': 'tu-vung-ngu-phap',
            'title': 'Từ vựng & Ngữ pháp',
            'mode': 'practice',
            'groups': [{'id': 'vg1',
                        'instr': 'E3: Mark the letter A, B, C or D to indicate the correct answer to each of the following questions.',
                        'items': [{'id': 'vg1.1',
                                   't': 'mcq',
                                   'q': 'Nguyen Thuc Thuy Tien left a positive impression on both judges and ______ because of her friendliness and '
                                        'natural beauty.',
                                   'o': ['spectators', 'viewers', 'audience', 'passer-by']},
                                  {'id': 'vg1.2',
                                   't': 'mcq',
                                   'q': 'When he was a teenager, he ______ at the local theatre in his home town during the tourist season.',
                                   'o': ['performed', 'attracted', 'decided', 'relaxed']},
                                  {'id': 'vg1.3',
                                   't': 'mcq',
                                   'q': 'She has joined the panel of ______ the popular TV talent show.',
                                   'o': ['audience', 'judges', 'viewers', 'watchers']},
                                  {'id': 'vg1.4',
                                   't': 'mcq',
                                   'q': "I didn't enjoy the performance because I couldn't ______ with any of the main characters.",
                                   'o': ['identify', 'deal', 'cope', 'cooperate']},
                                  {'id': 'vg1.5',
                                   't': 'mcq',
                                   'q': 'Judges travel all round America ______ search of the best singers and bring them to Hollywood.',
                                   'o': ['on', 'in', 'at', 'for']},
                                  {'id': 'vg1.6',
                                   't': 'mcq',
                                   'q': 'Can you play any ______? - Yes. I can play the flute and the guitar.',
                                   'o': ['musical tools', 'pieces of music', 'musical instruments', 'musical devices']},
                                  {'id': 'vg1.7',
                                   't': 'mcq',
                                   'q': "Two of the four contestants will be ______ after tonight's show.",
                                   'o': ['composed', 'removed', 'eliminated', 'terminated']},
                                  {'id': 'vg1.8',
                                   't': 'mcq',
                                   'q': 'Our music teacher has been invited to be a ______ in many music competitions and talent shows.',
                                   'o': ['singer', 'competitor', 'contestant', 'judge']},
                                  {'id': 'vg1.9',
                                   't': 'mcq',
                                   'q': 'American singer Michael Jackson made a record when he had got 13 Billboard Hot 100 number-one ______.',
                                   'o': ['singles', 'single', 'singer', 'singers']},
                                  {'id': 'vg1.10',
                                   't': 'mcq',
                                   'q': 'The judges ______ an important role in the competition.',
                                   'o': ['work', 'play', 'rest', 'put']},
                                  {'id': 'vg1.11',
                                   't': 'mcq',
                                   'q': 'The X-factor is a television singing competition ______ in the United Kingdom.',
                                   'o': ['originate', 'originated', 'originating', 'origination']},
                                  {'id': 'vg1.12',
                                   't': 'mcq',
                                   'q': 'Lina, the ______ album of the new music band in our city, will be uploaded on the website next week. I’m '
                                        'looking forward to listening to it.',
                                   'o': ['debut', 'only', 'best-selling', 'individual']},
                                  {'id': 'vg1.13',
                                   't': 'mcq',
                                   'q': 'I passionately love the show “Familiar Faces” and this is the 4th ______ I’ve seen.',
                                   'o': ['show', 'chapter', 'season', 'episode']},
                                  {'id': 'vg1.14',
                                   't': 'mcq',
                                   'q': 'This concert marks nine years since the death of Trinh Cong Son, a prominent ______ of modern Vietnamese '
                                        'music.',
                                   'o': ['comedian', 'actor', 'contributor', 'figure']},
                                  {'id': 'vg1.15',
                                   't': 'mcq',
                                   'q': 'The best singer ______ went to Alan Walker for “Faded”.',
                                   'o': ['rank', 'prize', 'reward', 'award']},
                                  {'id': 'vg1.16',
                                   't': 'mcq',
                                   'q': 'Van Cao’s “Tien Quan Ca” was made into the national ______ of the Socialist Republic of Viet Nam.',
                                   'o': ['song', 'music', 'melody', 'anthem']},
                                  {'id': 'vg1.17',
                                   't': 'mcq',
                                   'q': 'Fantasia Barrino, the winner of American Idol’s season 3 in 2004, released her ______ Free Yourself which '
                                        'earned three Grammy Award nominations.',
                                   'o': ['debut album', 'live performance', 'local version', 'live programme']},
                                  {'id': 'vg1.18',
                                   't': 'mcq',
                                   'q': 'The “Marching song” was adopted as the national ______ of Viet Nam in 1945.',
                                   'o': ['anthem', 'song', 'flag', 'identity']},
                                  {'id': 'vg1.19',
                                   't': 'mcq',
                                   'q': 'I’m a fan of ______ music. It consists of simple tunes so it is easy to listen and remember.',
                                   'o': ['pop', 'rock', 'classical', 'jazz']},
                                  {'id': 'vg1.20',
                                   't': 'mcq',
                                   'q': 'The ______ cheered loudly when the singers came out on the stage.',
                                   'o': ['audience', 'spectator', 'public', 'watcher']},
                                  {'id': 'vg1.21',
                                   't': 'mcq',
                                   'q': 'Celine Dion has been my ______ since I was young.',
                                   'o': ['idol', 'talent', 'fan', 'icon']},
                                  {'id': 'vg1.22',
                                   't': 'mcq',
                                   'q': 'We were surprised to know that over 150000 ______ packed into the stadium to support Vietnamese football '
                                        'team.',
                                   'o': ['people', 'fans', 'visitors', 'watchers']},
                                  {'id': 'vg1.23',
                                   't': 'mcq',
                                   'q': 'But for your support, our band couldn’t have won the Grand Music ______.',
                                   'o': ['show', 'quiz', 'competition', 'tour']},
                                  {'id': 'vg1.24',
                                   't': 'mcq',
                                   'q': 'Our performance was ______ to be the best one in this competition last night.',
                                   'o': ['cheered', 'appeared', 'judged', 'seen']},
                                  {'id': 'vg1.25',
                                   't': 'mcq',
                                   'q': 'In the last quarter of this year, our entertainment company had a big success in signing a lot of ______ '
                                        'with celebrities.',
                                   'o': ['bargains', 'contracts', 'arrangements', 'profits']},
                                  {'id': 'vg1.26',
                                   't': 'mcq',
                                   'q': 'Chopin was considered to be one of the greatest Romantic piano ______ of the 19th century.',
                                   'o': ['singers', 'writers', 'composers', 'poets']},
                                  {'id': 'vg1.27',
                                   't': 'mcq',
                                   'q': 'We’re seeking the ______ musician to join our entertainment company.',
                                   'o': ['good', 'famous', 'great', 'talented']},
                                  {'id': 'vg1.28',
                                   't': 'mcq',
                                   'q': 'These games are challenging, ______ it’s not easy to spend little time playing them.',
                                   'o': ['so', 'and', 'for', 'or']},
                                  {'id': 'vg1.29',
                                   't': 'mcq',
                                   'q': 'I didn’t want to continue watching the show ______ it was more and more boring later.',
                                   'o': ['for', 'or', 'but', 'and']},
                                  {'id': 'vg1.30',
                                   't': 'mcq',
                                   'q': 'He can’t decide whether to buy the tickets for the music show online ______ at the box office',
                                   'o': ['and', 'or', 'yet', 'so']},
                                  {'id': 'vg1.31',
                                   't': 'mcq',
                                   'q': 'Smoking is extremely detrimental to health, ______ many people continue to smoke anyway.',
                                   'o': ['nor', 'so', 'yet', 'then']},
                                  {'id': 'vg1.32', 't': 'mcq', 'q': 'Do you like singing ______ dancing?', 'o': ['but', 'yet', 'so', 'or']},
                                  {'id': 'vg1.33',
                                   't': 'mcq',
                                   'q': 'I admire Celine Dion ______ she has a nice voice.',
                                   'o': ['so', 'and', 'but', 'for']},
                                  {'id': 'vg1.34',
                                   't': 'mcq',
                                   'q': "He lost the key, ______ he couldn't get into the house.",
                                   'o': ['yet', 'or', 'so', 'for']},
                                  {'id': 'vg1.35',
                                   't': 'mcq',
                                   'q': 'We were lost in the forest, ______ luckily my friend had a map in his backpack.',
                                   'o': ['and', 'so', 'for', 'but']},
                                  {'id': 'vg1.36',
                                   't': 'mcq',
                                   'q': 'Pop music is so popular, ______ the melody is simple and memorable.',
                                   'o': ['for', 'so', 'and', 'nor']},
                                  {'id': 'vg1.37',
                                   't': 'mcq',
                                   'q': 'Would you like a cup of milk tea ______ a cup of hot chocolate after dinner?',
                                   'o': ['and', 'or', 'yet', 'so']},
                                  {'id': 'vg1.38',
                                   't': 'mcq',
                                   'q': 'Minh had his teeth decayed, ______ he refused to see the dentist.',
                                   'o': ['and', 'so', 'or', 'but']},
                                  {'id': 'vg1.39',
                                   't': 'mcq',
                                   'q': 'You must do well in the test, ______ you will not graduate.',
                                   'o': ['so', 'or', 'for', 'and']},
                                  {'id': 'vg1.40',
                                   't': 'mcq',
                                   'q': 'Anna thinks she ought to go to the university, ______ she wants to get qualifications for her dream job.',
                                   'o': ['and', 'yet', 'for', 'so']},
                                  {'id': 'vg1.41',
                                   't': 'mcq',
                                   'q': 'You can go to the theatre with us ______ you can go there alone.',
                                   'o': ['or', 'but', 'and', 'for']},
                                  {'id': 'vg1.42',
                                   't': 'mcq',
                                   'q': 'He invested a lot of money in this business, ______ it went bankrupt in a very short time.',
                                   'o': ['but', 'and', 'for', 'nor']},
                                  {'id': 'vg1.43',
                                   't': 'mcq',
                                   'q': 'It rained heavily, ______ the show was cancelled.',
                                   'o': ['but', 'for', 'so', 'yet']},
                                  {'id': 'vg1.44',
                                   't': 'mcq',
                                   'q': 'The students didn’t revise for their exams, ______ did they realise how important the exams were.',
                                   'o': ['nor', 'but', 'so', 'for']},
                                  {'id': 'vg1.45',
                                   't': 'mcq',
                                   'q': 'Peter wonders whether he should stay home and watch TV, ______ he should go out and have dinner with his '
                                        'friends.',
                                   'o': ['so', 'or', 'and', 'nor']},
                                  {'id': 'vg1.46',
                                   't': 'mcq',
                                   'q': 'The boys are playing games, ______ the girls are watching TV.',
                                   'o': ['so', 'nor', 'and', 'yet']},
                                  {'id': 'vg1.47',
                                   't': 'mcq',
                                   'q': 'Linda practices singing every day ______ she wants to become a singer.',
                                   'o': ['for', 'but', 'yet', 'or']},
                                  {'id': 'vg1.48',
                                   't': 'mcq',
                                   'q': 'The show was postponed ______ the singer had a serious accident',
                                   'o': ['or', 'but', 'for', 'so']},
                                  {'id': 'vg1.49',
                                   't': 'mcq',
                                   'q': 'I tried my best in the final test, ______ the result was not as good as I expected.',
                                   'o': ['but', 'so', 'for', 'or']},
                                  {'id': 'vg1.50',
                                   't': 'mcq',
                                   'q': 'She loves comedies, ______ her husband is interested in action films.',
                                   'o': ['for', 'yet', 'or', 'and']},
                                  {'id': 'vg1.51',
                                   't': 'mcq',
                                   'q': 'My family really loves Japanese food, ______ we order it twice a week.',
                                   'o': ['yet', 'so', 'but', 'nor']},
                                  {'id': 'vg1.52',
                                   't': 'mcq',
                                   'q': 'Van Cao was a gifted composer, ______ he won many national prizes, including Ho Chi Minh prize.',
                                   'o': ['or', 'and', 'so', 'yet']},
                                  {'id': 'vg1.53',
                                   't': 'mcq',
                                   'q': "I should practice more for the competition, ______ my health hasn't been excellent recently.",
                                   'o': ['and', 'so', 'but', 'or']},
                                  {'id': 'vg1.54',
                                   't': 'mcq',
                                   'q': 'You can go to the movies with me, ______ you can go to the concert alone.',
                                   'o': ['and', 'or', 'so', 'yet']},
                                  {'id': 'vg1.55',
                                   't': 'mcq',
                                   'q': 'Would you like to go to the cinema ______ watch at home?',
                                   'o': ['for', 'or', 'but', 'so']},
                                  {'id': 'vg1.56',
                                   't': 'mcq',
                                   'q': 'She has a potential voice, ______ she doesn’t intend to pursue a career in music.',
                                   'o': ['but', 'so', 'yet', 'for']},
                                  {'id': 'vg1.57',
                                   't': 'mcq',
                                   'q': 'He has an emotive voice ______ skillful performance.',
                                   'o': ['and', 'or', 'for', 'but']},
                                  {'id': 'vg1.58',
                                   't': 'mcq',
                                   'q': 'John’s voice is nice, ______ his performance style is not good enough.',
                                   'o': ['and', 'so', 'or', 'but']},
                                  {'id': 'vg1.59',
                                   't': 'mcq',
                                   'q': 'This singer was nominated for 10 Grammys, ______ he won two.',
                                   'o': ['and', 'so', 'for', 'but']},
                                  {'id': 'vg1.60',
                                   't': 'mcq',
                                   'q': 'Mike was a famous singer, ______ he had a bad singing voice.',
                                   'o': ['and', 'or', 'but', 'for']},
                                  {'id': 'vg1.61',
                                   't': 'mcq',
                                   'q': 'Close the window ______ turn off the lights when you leave the room.',
                                   'o': ['yet', 'so', 'for', 'and']},
                                  {'id': 'vg1.62',
                                   't': 'mcq',
                                   'q': 'His performance was dull, ______ I fell asleep.',
                                   'o': ['for', 'but', 'so', 'or']},
                                  {'id': 'vg1.63',
                                   't': 'mcq',
                                   'q': 'She wanted to become a violinist, ______ her parents didn’t allow.',
                                   'o': ['yet', 'for', 'so', 'or']},
                                  {'id': 'vg1.64',
                                   't': 'mcq',
                                   'q': 'The show was fascinating at the beginning, ______ it got dull later.',
                                   'o': ['yet', 'so', 'and', 'for']}]},
                       {'id': 'vg2',
                        'instr': 'E4: Mark the letter A, B, C or D to indicate the correct answer to each of the following questions.',
                        'items': [{'id': 'vg2.1',
                                   't': 'mcq',
                                   'q': 'My parents decided ______ a taxi because it was late.',
                                   'o': ['take', 'to take', 'taking', 'took']},
                                  {'id': 'vg2.2',
                                   't': 'mcq',
                                   'q': 'It began ______ when I was in London last Saturday.',
                                   'o': ['rain', 'to rain', 'rained', 'rains']},
                                  {'id': 'vg2.3', 't': 'mcq', 'q': 'I saw her ______ the street.', 'o': ['to cross', 'crossed', 'crosses', 'cross']},
                                  {'id': 'vg2.4',
                                   't': 'mcq',
                                   'q': "It's customary ______ a gift from someone at least once or twice before finally accepting in Japan.",
                                   'o': ['refuse', 'to refuse', 'refused', 'refusing']},
                                  {'id': 'vg2.5',
                                   't': 'mcq',
                                   'q': "We've decided ______ the music contest at the end of this year.",
                                   'o': ['to attend', 'attending', 'attends', 'attend']},
                                  {'id': 'vg2.6',
                                   't': 'mcq',
                                   'q': 'We managed ______ their first album on social media.',
                                   'o': ['found', 'founded', 'finding', 'to find']},
                                  {'id': 'vg2.7',
                                   't': 'mcq',
                                   'q': "Don't let him ______ about his mother's illness now.",
                                   'o': ['know', 'knowing', 'to know', 'known']},
                                  {'id': 'vg2.8',
                                   't': 'mcq',
                                   'q': "It's dangerous ______ out alone late at night.",
                                   'o': ['gone', 'going', 'go', 'to go']},
                                  {'id': 'vg2.9',
                                   't': 'mcq',
                                   'q': "My parents didn't encourage me ______ Music at university.",
                                   'o': ['to study', 'studying', 'study', 'studied']},
                                  {'id': 'vg2.10',
                                   't': 'mcq',
                                   'q': 'I’m happy ______ that you’ve passed your driving test. Congratulations!',
                                   'o': ['not hearing', 'hear', 'hearing', 'to hear']},
                                  {'id': 'vg2.11',
                                   't': 'mcq',
                                   'q': "Blake didn't invite her boyfriend ______ to her graduation ceremony.",
                                   'o': ['coming', 'comes', 'to come', 'come']},
                                  {'id': 'vg2.12',
                                   't': 'mcq',
                                   'q': 'The clerk required me ______ in the form before letting me in.',
                                   'o': ['sings', 'to sing', 'to sang', 'singing']},
                                  {'id': 'vg2.13',
                                   't': 'mcq',
                                   'q': 'I allow my little daughter ______ with her friends in the flower garden.',
                                   'o': ['not to play', 'to play', 'playing', 'play']},
                                  {'id': 'vg2.14',
                                   't': 'mcq',
                                   'q': "He didn't deserve ______ by the locals like that.",
                                   'o': ['to be treated', 'treating', 'to treat', 'being treated']},
                                  {'id': 'vg2.15',
                                   't': 'mcq',
                                   'q': "It's impolite ______ off your shoes before stepping into a Japanese house.",
                                   'o': ['to take', 'not take', 'not to take', 'take']},
                                  {'id': 'vg2.16',
                                   't': 'mcq',
                                   'q': 'Jimmy forgot ______ the house, so it was broken into.',
                                   'o': ['to be locked', 'locked', 'lock', 'to lock']},
                                  {'id': 'vg2.17',
                                   't': 'mcq',
                                   'q': 'Anna learnt how ______ cakes from her grandmother.',
                                   'o': ['making', 'to make', 'to made', 'make']},
                                  {'id': 'vg2.18',
                                   't': 'mcq',
                                   'q': "They intended ______ Paris last year but they didn't have enough time.",
                                   'o': ['visited', 'visiting', 'visit', 'to visit']},
                                  {'id': 'vg2.19',
                                   't': 'mcq',
                                   'q': 'John made me ______ a lot with his hilarious jokes.',
                                   'o': ['laughing', 'to laugh', 'laugh', 'laughed']},
                                  {'id': 'vg2.20',
                                   't': 'mcq',
                                   'q': 'Nothing can make Alex ______ her mind now.',
                                   'o': ['not to change', 'to change', 'change', 'changing']},
                                  {'id': 'vg2.21',
                                   't': 'mcq',
                                   'q': 'Someone saw him ______ to a restaurant with his friends.',
                                   'o': ['to go', 'be gone', 'went', 'go']},
                                  {'id': 'vg2.22',
                                   't': 'mcq',
                                   'q': 'Hurry up! The train is about ______ in five minutes.',
                                   'o': ['leave', 'to leave', 'left', 'leaving']},
                                  {'id': 'vg2.23',
                                   't': 'mcq',
                                   'q': 'There are not enough candies ______ among all the children here.',
                                   'o': ['share', 'shared', 'to share', 'sharing']},
                                  {'id': 'vg2.24',
                                   't': 'mcq',
                                   'q': 'I’d like ______ all of you to enjoy my party on this Friday.',
                                   'o': ['to invite', 'inviting', 'invite', 'not invite']},
                                  {'id': 'vg2.25',
                                   't': 'mcq',
                                   'q': 'I saw my little sister ______ the dog yesterday.',
                                   'o': ['fed', 'to feed', 'feeds', 'feed']},
                                  {'id': 'vg2.26',
                                   't': 'mcq',
                                   'q': 'You can use my car but you must promise ______ it before Friday.',
                                   'o': ['to return', 'returns', 'to be returned', 'return']},
                                  {'id': 'vg2.27',
                                   't': 'mcq',
                                   'q': "I didn't have enough money ______ the coat, so I just bought a sweater.",
                                   'o': ['buy', 'bought', 'to buy', 'buying']},
                                  {'id': 'vg2.28',
                                   't': 'mcq',
                                   'q': 'My mother made me ______ at home at night.',
                                   'o': ['staying', 'to stay', 'stayed', 'stay']},
                                  {'id': 'vg2.29',
                                   't': 'mcq',
                                   'q': 'He reminded me ______ to give the book back to John',
                                   'o': ['not forget', 'not to forget', 'forgot', 'forgetting']},
                                  {'id': 'vg2.30',
                                   't': 'mcq',
                                   'q': 'You’d better ______ out with your friends as it is very dangerous in the evening.',
                                   'o': ['went', 'go', 'going', 'to go']},
                                  {'id': 'vg2.31',
                                   't': 'mcq',
                                   'q': 'She refused ______ back again',
                                   'o': ['not to coming', 'is coming', 'coming', 'to come']},
                                  {'id': 'vg2.32',
                                   't': 'mcq',
                                   'q': 'Everybody would like ______ to a higher position.',
                                   'o': ['to be promoted', 'being promoted', 'promoting', 'to promote']},
                                  {'id': 'vg2.33',
                                   't': 'mcq',
                                   'q': 'Please let me ______ your decision as soon as possible.',
                                   'o': ['to know', 'know', 'known', 'knowing']},
                                  {'id': 'vg2.34',
                                   't': 'mcq',
                                   'q': 'We expect John ______ to the airport late as the plane will take off in 15 minutes.',
                                   'o': ['to come', 'not to come', 'not coming', 'coming']},
                                  {'id': 'vg2.35',
                                   't': 'mcq',
                                   'q': 'My father promised ______ me a comic book on my 9th birthday.',
                                   'o': ['to be bought', 'buy', 'to buy', 'buying']},
                                  {'id': 'vg2.36',
                                   't': 'mcq',
                                   'q': 'This song makes everybody ______ comfortable.',
                                   'o': ['to feel', 'feel', 'feeling', 'feels']},
                                  {'id': 'vg2.37',
                                   't': 'mcq',
                                   'q': 'We were encouraged ______ foreign languages at school.',
                                   'o': ['to learn', 'learning', 'learn', 'to learning']},
                                  {'id': 'vg2.38',
                                   't': 'mcq',
                                   'q': "She is mature enough ______ her family's problems with her parents.",
                                   'o': ['discussing', 'to discussing', 'discusses', 'to discuss']},
                                  {'id': 'vg2.39',
                                   't': 'mcq',
                                   'q': 'It takes me 30 minutes ______ to school every day.',
                                   'o': ['go', 'to go', 'going', 'to going']},
                                  {'id': 'vg2.40',
                                   't': 'mcq',
                                   'q': 'We are not allowed ______ jeans at school.',
                                   'o': ['wear', 'to wear', 'wearing', 'worn']},
                                  {'id': 'vg2.41',
                                   't': 'mcq',
                                   'q': 'My parents let my sister ______ camping with her friends in the mountain.',
                                   'o': ['not go', 'going', 'go', 'to go']},
                                  {'id': 'vg2.42',
                                   't': 'mcq',
                                   'q': 'Did you manage ______ the book you were looking for?',
                                   'o': ['to find', 'found', 'finding', 'find']},
                                  {'id': 'vg2.43',
                                   't': 'mcq',
                                   'q': 'Mr.Thompson is learning Vietnamese ______ to read Kim Van Kieu.',
                                   'o': ['so that', 'so as to', 'in order not to', 'so as not to']},
                                  {'id': 'vg2.44',
                                   't': 'mcq',
                                   'q': 'I determine ______ all my homework today.',
                                   'o': ['to finish', 'finish', 'finishes', 'finishing']},
                                  {'id': 'vg2.45',
                                   't': 'mcq',
                                   'q': 'He advised them ______ in the class',
                                   'o': ['to not talk', 'not to talk', 'to talk not', 'don’t talk']},
                                  {'id': 'vg2.46',
                                   't': 'mcq',
                                   'q': "She didn't know whether ______ to her friend's wedding or not.",
                                   'o': ['to coming', 'to come', 'coming', 'come']},
                                  {'id': 'vg2.47',
                                   't': 'mcq',
                                   'q': 'When he lived in the countryside, he ______ walk along the port to watch the ships up and down the river.',
                                   'o': ['got used to', 'was used to', 'used to', 'uses to']},
                                  {'id': 'vg2.48',
                                   't': 'mcq',
                                   'q': 'Dad promised ______ us to the circus on Sunday.',
                                   'o': ['to take', 'taking', 'take', 'took']},
                                  {'id': 'vg2.49',
                                   't': 'mcq',
                                   'q': 'I’m planning ______ my children to the new amusement park this weekend.',
                                   'o': ['taking', 'to take', 'take', 'to taking']},
                                  {'id': 'vg2.50', 't': 'mcq', 'q': "Let's ______ out to dinner.", 'o': ['go', 'going', 'come', 'coming']},
                                  {'id': 'vg2.51',
                                   't': 'mcq',
                                   'q': 'Tom said that he could ______ me with this assignment.',
                                   'o': ['helped', 'helping', 'to help', 'help']},
                                  {'id': 'vg2.52', 't': 'mcq', 'q': 'Mai agreed ______ my old laptop.', 'o': ['buying', 'bought', 'buys', 'to buy']},
                                  {'id': 'vg2.53',
                                   't': 'mcq',
                                   'q': 'His teacher made him ______ for his bad behaviour.',
                                   'o': ['to apologised', 'apologising', 'to apologise', 'apologise']},
                                  {'id': 'vg2.54',
                                   't': 'mcq',
                                   'q': "Please don't hesitate ______ me when you arrive in Frankfurt.",
                                   'o': ['to call', 'calling', 'to calling', 'call']},
                                  {'id': 'vg2.55',
                                   't': 'mcq',
                                   'q': 'They decided ______ to the live concert.',
                                   'o': ['go', 'gone', 'to go', 'going']},
                                  {'id': 'vg2.56',
                                   't': 'mcq',
                                   'q': 'We intend ______ him the truth for fear that he’ll fly into a fit of madness.',
                                   'o': ['to tell', 'telling', 'not tell', 'not to tell']},
                                  {'id': 'vg2.57',
                                   't': 'mcq',
                                   'q': "I'd love ______ Paris one day.",
                                   'o': ['to visits', 'to visit', 'visiting', 'visit']},
                                  {'id': 'vg2.58',
                                   't': 'mcq',
                                   'q': "His parents didn't let him ______ to music school.",
                                   'o': ['to go', 'goes', 'going', 'go']},
                                  {'id': 'vg2.59',
                                   't': 'mcq',
                                   'q': 'My younger sister is not reliable enough ______ my secrets to her.',
                                   'o': ['revealing', 'reveal', 'to reveal', 'to revealing']},
                                  {'id': 'vg2.60',
                                   't': 'mcq',
                                   'q': 'I heard him ______ the window last night.',
                                   'o': ['to open', 'opened', 'opens', 'open']},
                                  {'id': 'vg2.61',
                                   't': 'mcq',
                                   'q': 'He really wants ______ to play a musical instrument this summer.',
                                   'o': ['to lean', 'learning', 'leaning', 'to learn']}]},
                       {'id': 'vg3',
                        'instr': 'E4 (bài 2 – nguồn đánh trùng nhãn E4): Make compound sentences using the conjunctions in brackets.',
                        'items': [{'id': 'vg3.1',
                                   't': 'fill',
                                   'long': True,
                                   'q': "<b>Nối hai câu bằng liên từ (but):</b> I'd like to go to the party. I'm too busy.<br>{_}"},
                                  {'id': 'vg3.2',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Nối hai câu bằng liên từ (so):</b> It was sunny. Lan took an umbrella.<br>{_}'},
                                  {'id': 'vg3.3',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Nối hai câu bằng liên từ (and):</b> Anna is an amazing dancer. Her parents are proud of her.<br>{_}'},
                                  {'id': 'vg3.4',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Nối hai câu bằng liên từ (or):</b> You can vote online for your favourite singer. You can send text '
                                        'messages.<br>{_}'},
                                  {'id': 'vg3.5',
                                   't': 'fill',
                                   'long': True,
                                   'q': "<b>Nối hai câu bằng liên từ (but):</b> Lisa went shopping yesterday. She didn't buy anything.<br>{_}"},
                                  {'id': 'vg3.6',
                                   't': 'fill',
                                   'long': True,
                                   'q': "<b>Nối hai câu bằng liên từ (and):</b> John's parents own a restaurant. Sometimes he helps in the kitchen "
                                        'at weekends.<br>{_}'},
                                  {'id': 'vg3.7',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Nối hai câu bằng liên từ (or):</b> Go inside. You will catch a cold.<br>{_}'},
                                  {'id': 'vg3.8',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Nối hai câu bằng liên từ (so):</b> Rita is a good drummer. She will probably be invited to join the '
                                        'band.<br>{_}'}]}]},
           {'id': 'nghe',
            'title': 'Nghe',
            'mode': 'practice',
            'audio': 'botro_nghe.mp3',
            'groups': [{'id': 'li1',
                        'instr': 'E5: Listen to the information about American Idol and decide whether the statements are True (T) or False (F).',
                        'items': [{'id': 'li1.1', 't': 'tf', 'q': 'American Idol began in June 11, 2003.'},
                                  {'id': 'li1.2', 't': 'tf', 'q': 'The founder of British Pop Idol is Simon Fuller.'},
                                  {'id': 'li1.3', 't': 'tf', 'q': 'The finalists will be decided by the vote of the judges.'},
                                  {'id': 'li1.4', 't': 'tf', 'q': 'At the 13th season, American Idol has four judges.'},
                                  {'id': 'li1.5', 't': 'tf', 'q': 'Vietnamese viewers can watch American Idol on Star World channel.'}]}]},
           {'id': 'noi',
            'title': 'Nói',
            'mode': 'practice',
            'groups': [{'id': 'sp1',
                        'instr': 'IV – Speaking: Talk about a TV music show that you like. (nói – đối chiếu bài mẫu)',
                        'items': [{'id': 'sp1.1',
                                   't': 'open',
                                   'q': 'Talk about a TV music show that you like. You can use the following questions as cues: <ul><li>What is '
                                        'it?</li><li>How do you know it?</li><li>What is it like?</li><li>Why do you like it?</li></ul><b>Useful '
                                        'vocabulary:</b> The Voice of Vietnam, Vietnam Idol, The X Factor, The Remix; through the Internet / TV / '
                                        'friends / magazines; popular, new, interesting, celebrities’ appearance; focusing on voice, relaxing, '
                                        'professional performances.<br><b>Useful structures:</b> Among many TV music shows … / I am a big fan of … / '
                                        'One of my favourite TV music shows is … / I like … most. / I know this programme through … / I watched the '
                                        'show for the first time on … / In this programme, … / There are some reasons why I like the show. / '
                                        'Firstly, … Secondly, … In addition, …<br><b>Give your answer using the following cues (speak for 1–2 '
                                        'minutes):</b><ol><li>Among many TV music shows these days, I like ... most.</li><li>It is a competion in '
                                        'which ...</li><li>I know this program through ...</li><li>The show is rated as ...</li><li>I am a big fan '
                                        'of the show for some reasons.</li><li>Firstly, ... Secondly, ... In addition, ...</li></ol>'}]}]},
           {'id': 'doc',
            'title': 'Đọc hiểu',
            'mode': 'practice',
            'groups': [{'id': 're1',
                        'instr': 'E6: Read the following passage and mark the letter A, B, C, or D to indicate the correct answer to each of the '
                                 'questions.',
                        'passage': '<p>Based on the original The Voice of Holland, The Voice of America, or sooner The Voice, officially aired on '
                                   'NBC on April 26, 2011 aiming to find new singing talent and soon became a big hit.</p><p>The Voice process '
                                   'includes Blinds Audition, Battles Rounds, Knockout Rounds, and the final live performance phase. Only those '
                                   'fifteen and over are eligible for the competition. There are four coaches, themselves well-known performing '
                                   "artists, who critique contestants' performances and form their own teams of contestants and give them guidance "
                                   'through the rest of the season. Coaches also have the power to decide on which contestants to advance in the '
                                   'next rounds. One celebrity key advisor gives assistance to the coaches and their teams during the preparation '
                                   'process.</p><p>The coaches and the television audience have equal power to decide who moves on to the final four '
                                   'phase. However, the winner is determined by votes from the television audience by online voting on the official '
                                   "website, SMS text and iTunes stores purchases of the contestants' performances. The declared winner receives US$ "
                                   '100, 000 and a record contract with Universal Music Group.</p><p>As an incredible success in both Holland and '
                                   'the U.S., The Voice has been franchised out to many other countries in the world, and has been a big rival to '
                                   'the Idol franchise.</p>',
                        'items': [{'id': 're1.1',
                                   't': 'mcq',
                                   'q': 'What is TRUE about The Voice program?',
                                   'o': ['It originated in Holland.',
                                         'The Voice of Holland first aired on NBC.',
                                         'It was a failure in Holland.',
                                         'The Voice of Holland first aired on BBC.']},
                                  {'id': 're1.2',
                                   't': 'mcq',
                                   'q': 'What is a requirement for contestants?',
                                   'o': ['Contestants must be over 10 old.',
                                         'Contestants must be at least 15 years old.',
                                         'Contestants must be at least 13 years old.',
                                         'Contestants must be over 30 years old.']},
                                  {'id': 're1.3',
                                   't': 'mcq',
                                   'q': 'Who decide on the winner of each season?',
                                   'o': ['Coaches and television audience',
                                         'Coaches and the celebrity key advisor',
                                         'Television audience',
                                         "The contestants' parents."]},
                                  {'id': 're1.4',
                                   't': 'mcq',
                                   'q': 'By what means can people vote for their favourite contestant?',
                                   'o': ['Text messages, internet, and post letters',
                                         'Youtube views and online voting on the official website',
                                         'Facebook’s sharing and voting from the audiences.',
                                         "Text messages and online buying of the contestants' performances"]},
                                  {'id': 're1.5',
                                   't': 'mcq',
                                   'q': 'What is the prize for winning a The Voice season?',
                                   'o': ['A music company and US$ 100,000',
                                         'A large amount of money and becoming a The Voice coach',
                                         'A record contract worth US$ 100,000',
                                         'A large amount of money and chance to work with a music company']}]},
                       {'id': 're2',
                        'instr': 'E7: Read the following passage and mark the letter A, B, C, or D to indicate the correct word or phrase that best '
                                 'fits each of the numbered blanks.',
                        'passage': "<p>Rock began in the USA in the early 1950s. At that time 'rhythm and blues’ music was very <b>(1) ______</b> "
                                   'with black Americans. ‘R&B’ was a mixture <b>(2) ______</b> black religious music and jazz. It had strong '
                                   'rhythms that you could dance to and simple, fast music.</p><p><b>(3) ______</b> the success of R&B music, white '
                                   "musicians started to copy the same style. By the mid 1950s, <b>(4) ______</b> new white R&B music, called 'rock "
                                   '‘n’ roll’ had become very popular. Singers like Elvis Presley and Bill Haley <b>(5) ______</b> millions of '
                                   'teenage fans. Their music was fast and loud. Many older people thought that rock ‘n’ roll was very <b>(6) '
                                   '______</b>.</p><p>By the early 1960s, even rock ‘n’ roll had become old-fashioned. Many of the songs had begun '
                                   'to sound the <b>(7) ______</b>. It was at that time that a new group from England became popular: The '
                                   'Beatles.</p><p>The Beatles first started <b>(8) ______</b> singing American style songs, but they soon developed '
                                   'their own style, with more <b>(9) ______</b> melodies. They also introduced different instruments, <b>(10) '
                                   '______</b> as the Indian sitar. Groups like The Beatles had a very important influence <b>(11) ______</b> the '
                                   'style of popular music. By the <b>(12) ______</b> 1970s, rock ‘n’ roll had developed into a new form of music. '
                                   'Electronics had <b>(13) ______</b> the amplified guitars and drums of rock ‘n’ roll. Rock had arrived.</p>',
                        'items': [{'id': 're2.1', 't': 'mcq', 'q': 'Blank (1)', 'o': ['accepted', 'popular', 'common', 'famous']},
                                  {'id': 're2.2', 't': 'mcq', 'q': 'Blank (2)', 'o': ['to', 'with', 'of', 'by']},
                                  {'id': 're2.3', 't': 'mcq', 'q': 'Blank (3)', 'o': ['Noticing', 'Detecting', 'Warning', 'Perceiving']},
                                  {'id': 're2.4', 't': 'mcq', 'q': 'Blank (4)', 'o': ['those', 'its', 'their', 'this']},
                                  {'id': 're2.5', 't': 'mcq', 'q': 'Blank (5)', 'o': ['attached', 'attacked', 'attracted', 'attained']},
                                  {'id': 're2.6', 't': 'mcq', 'q': 'Blank (6)', 'o': ['dangerous', 'endangered', 'dangerously', 'in danger']},
                                  {'id': 're2.7', 't': 'mcq', 'q': 'Blank (7)', 'o': ['equal', 'same', 'corresponding', 'twin']},
                                  {'id': 're2.8', 't': 'mcq', 'q': 'Blank (8)', 'o': ['to', 'at', 'with', 'by']},
                                  {'id': 're2.9', 't': 'mcq', 'q': 'Blank (9)', 'o': ['complicated', 'complicate', 'complicating', 'complication']},
                                  {'id': 're2.10', 't': 'mcq', 'q': 'Blank (10)', 'o': ['same', 'such', 'like', 'so']},
                                  {'id': 're2.11', 't': 'mcq', 'q': 'Blank (11)', 'o': ['in', 'for', 'to', 'on']},
                                  {'id': 're2.12', 't': 'mcq', 'q': 'Blank (12)', 'o': ['early', 'opening', 'first', 'advance']},
                                  {'id': 're2.13', 't': 'mcq', 'q': 'Blank (13)', 'o': ['switched', 'returned', 'replaced', 'changed']}]}]},
           {'id': 'viet',
            'title': 'Viết',
            'mode': 'practice',
            'groups': [{'id': 'wr1',
                        'instr': 'E8: Complete each of the following sentences using the cues given. You can change the cues and use other words in '
                                 'addition to the cues to complete the sentences.',
                        'items': [{'id': 'wr1.1',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> I / admire / My Tam / since / I / be / university / student.<br>Câu hoàn chỉnh: {_}'},
                                  {'id': 'wr1.2',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> She / be / only / beautiful / singer / also / talented / composer.<br>Câu hoàn chỉnh: {_}'},
                                  {'id': 'wr1.3',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> She / participate / judge / famous / TV / programs / such / Vietnam Idol / The voice of '
                                        'Vietnam / few years / ago.<br>Câu hoàn chỉnh: {_}'},
                                  {'id': 'wr1.4',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> She / win / a lot / international / national / prizes / so far.<br>Câu hoàn chỉnh: {_}'},
                                  {'id': 'wr1.5',
                                   't': 'fill',
                                   'long': True,
                                   'q': '<b>Từ gợi ý:</b> My Tam / become / first / Southeast Asian / artist / hold / own / concert / Jangchung '
                                        'Gymnasium / Korea / 2018.<br>Câu hoàn chỉnh: {_}'}]},
                       {'id': 'wr2',
                        'instr': 'E9: You have an English friend and want to tell him / her about your favourite singer. Write an email (120 – 150 '
                                 'words). (tự luận – xem bài mẫu)',
                        'items': [{'id': 'wr2.1',
                                   't': 'open',
                                   'q': 'You have an English friend and want to tell him / her about your favourite singer. Write an email (120 – '
                                        '150 words) to tell him / her about it. Use the following questions as cues:<ul><li>What is his / her '
                                        'name?</li><li>What type of music does he / she sing?</li><li>What type of people listen to his / her '
                                        'songs?</li><li>Why do you admire him / her?</li></ul><i>To: … / Subject: … / Dear …, … / Best '
                                        'wishes,</i>'}]}]}]}
