# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'t1.1': 'goodbye',
 't1.10': ['thank you'],
 't1.11': ['How are you, Lan?'],
 't1.12': ['Hello, Quan.'],
 't1.13': ["I'm Phong."],
 't1.14': {'blanks': [['Hi!'], ['Bye.'], ['Fine, thanks.'], ['Nice to meet you, too!']]},
 't1.15': ['Goodbye, Miss Hoa.'],
 't1.16': 'hi',
 't1.17': 'night',
 't1.18': 'fine',
 't1.19': 'Nice',
 't1.2': "I'm fine, thanks.",
 't1.20': ['hello'],
 't1.21': ['o'],
 't1.3': "Hello, Mai. I'm Nam.",
 't1.4': 'hi',
 't1.5': 'you',
 't1.6': ['morning'],
 't1.7': ['you'],
 't1.8': ['later'],
 't1.9': ['How']}

EXPLANATIONS = {'t1.1': 'Từ được đọc là goodbye.',
 't1.10': 'thank you',
 't1.11': 'How are you, Lan?',
 't1.12': 'Hello, Quan.',
 't1.13': "I'm Phong.",
 't1.14': 'Mỗi câu nói có một câu đáp.',
 't1.15': 'Goodbye, Miss Hoa.',
 't1.16': 'hi = chào.',
 't1.17': 'Good night.',
 't1.18': "I'm fine.",
 't1.19': 'Nice to meet you.',
 't1.2': 'Hỏi thăm → trả lời khỏe.',
 't1.20': 'hello',
 't1.21': 'goodbye',
 't1.3': 'Chào lại.',
 't1.4': 'bye, goodbye = tạm biệt.',
 't1.5': 'Nice to meet you.',
 't1.6': 'Good morning = chào buổi sáng.',
 't1.7': 'thank you',
 't1.8': 'See you later.',
 't1.9': 'How are you?'}

GHI_CHU_RA_SOAT = []
