# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'t1.1': 'teacher',
 't1.10': 'Hi, Mary.',
 't1.11': ['Hello', 'Hi'],
 't1.12': ['is'],
 't1.13': ['Hello', 'Hi'],
 't1.14': ['This'],
 't1.15': ['this'],
 't1.16': ['Hello, Mr Long.'],
 't1.17': ['This is Mary.'],
 't1.18': ['This is my friend Linh.'],
 't1.19': ["That's my teacher, Ms Hoa."],
 't1.2': "It's",
 't1.20': {'blanks': [['Hi, Mary.'], ['Hello, Mr Long.'], ["I'm fine, thank you."], ['Yes, it is.']]},
 't1.3': 'friend',
 't1.4': 'Thank',
 't1.5': 'this',
 't1.6': 'that',
 't1.7': 'Mr',
 't1.8': 'đây, cái này (ở gần)',
 't1.9': 'kia, cái kia (ở xa)'}

EXPLANATIONS = {'t1.1': 'teacher = giáo viên.',
 't1.10': 'This is Mary. → Hi, Mary.',
 't1.11': 'Chào lại: Hello / Hi.',
 't1.12': 'This is Nam.',
 't1.13': 'Chào thầy: Hello, Mr Long.',
 't1.14': 'This is Mary.',
 't1.15': 'this',
 't1.16': 'Hello, Mr Long.',
 't1.17': 'This is Mary.',
 't1.18': 'This is my friend Linh.',
 't1.19': "That's my teacher, Ms Hoa.",
 't1.2': "It's Lucy.",
 't1.20': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 't1.3': 'friend = bạn.',
 't1.4': 'Thank you.',
 't1.5': 'this = đây, cái này (ở gần) (👇)',
 't1.6': 'that = kia, cái kia (ở xa) (👉)',
 't1.7': 'yes, no là trả lời; Mr là "ông/thầy".',
 't1.8': 'this = đây, cái này (ở gần)',
 't1.9': 'that = kia, cái kia (ở xa)'}

GHI_CHU_RA_SOAT = []
