# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u3-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['teacher', 'friend', 'Mr'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "giáo viên":',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ["It's", 'Is', 'This'],
                                   'plain': True,
                                   'q': "Is this Lan? – No, it isn't. ___ Lucy.",
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['friend', 'teacher', 'that'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "bạn":',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Thank', 'This', 'That'],
                                   'plain': True,
                                   'q': '___ you, Ben. – (cảm ơn)',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ['no', 'Mr', 'this'], 'plain': True, 'q': '<span class="emo">👇</span>', 't': 'mcq'},
                                  {'id': 't1.6',
                                   'o': ['yes', 'that', 'this'],
                                   'plain': True,
                                   'q': '<span class="emo">👉</span>',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['yes', 'no', 'Mr'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['kia, cái kia (ở xa)', 'giáo viên', 'đây, cái này (ở gần)'],
                                   'plain': True,
                                   'q': 'Nghĩa của "this" là:',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['nó', 'bạn', 'kia, cái kia (ở xa)'],
                                   'plain': True,
                                   'q': 'Nghĩa của "that" là:',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ["I'm fine, thank you.", "No, it isn't. It's Minh.", 'Hi, Mary.'],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'This is Mary.',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': "That's Lucy. – {_}, Lucy.", 't': 'fill'},
                                  {'id': 't1.12', 'q': 'Hi, Lucy. – This {_} Nam.', 't': 'fill'},
                                  {'id': 't1.13', 'q': "That's my teacher, Mr Long. – {_}, Mr Long.", 't': 'fill'},
                                  {'id': 't1.14', 'q': '{_} is Mary. (người ở gần)', 't': 'fill'},
                                  {'id': 't1.15', 'q': 'itsh → {_}', 't': 'fill'},
                                  {'id': 't1.16', 'q': '', 't': 'order', 'words': ['Mr', 'Hello,', 'Long.']},
                                  {'id': 't1.17', 'q': '', 't': 'order', 'words': ['Mary.', 'is', 'This']},
                                  {'id': 't1.18', 'q': '', 't': 'order', 'words': ['my', 'is', 'Linh.', 'friend', 'This']},
                                  {'id': 't1.19', 'q': '', 't': 'order', 'words': ['teacher,', 'Ms', 'Hoa.', 'my', "That's"]},
                                  {'id': 't1.20',
                                   'left': ['This is Mary.', "That's Mr Long.", 'How are you?', 'Is this Bill?'],
                                   'o': ["I'm fine, thank you.", 'Yes, it is.', 'Hello, Mr Long.', 'Hi, Mary.'],
                                   'q': 'Nối:',
                                   't': 'match'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 3 – Our friends: Kiểm tra 3',
 'unit': 3}
