# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'t1.1': 'Me too.',
 't1.10': 'Me too.',
 't1.11': ['running'],
 't1.12': ['walking'],
 't1.13': ['drawing'],
 't1.14': ['painting'],
 't1.15': ['drawing'],
 't1.16': ['I like running.'],
 't1.17': ['He likes walking.'],
 't1.18': ["What's your hobby?"],
 't1.19': ["It's singing."],
 't1.2': 'likes',
 't1.20': {'blanks': [['Me too.'], ["I'm fine, thanks."], ["My name's Nam."], ["It's singing."]]},
 't1.3': 'running',
 't1.4': 'dancing',
 't1.5': 'cooking',
 't1.6': 'walking',
 't1.7': 'swimming',
 't1.8': 'nấu ăn',
 't1.9': 'đi bộ'}

EXPLANATIONS = {'t1.1': 'Me too = mình cũng vậy.',
 't1.10': 'I like dancing. → Me too.',
 't1.11': 'running = chạy',
 't1.12': 'walking = đi bộ',
 't1.13': 'drawing = vẽ',
 't1.14': 'painting = tô màu',
 't1.15': 'drawing',
 't1.16': 'I like running.',
 't1.17': 'He likes walking.',
 't1.18': "What's your hobby?",
 't1.19': "It's singing.",
 't1.2': 'He + likes',
 't1.20': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 't1.3': '🏃 = running.',
 't1.4': '💃 = dancing.',
 't1.5': 'cooking = nấu ăn (🍳)',
 't1.6': 'walking = đi bộ (🚶)',
 't1.7': 'drawing, painting là hoạt động vẽ/tô; swimming là bơi.',
 't1.8': 'cooking = nấu ăn',
 't1.9': 'walking = đi bộ'}

GHI_CHU_RA_SOAT = []
