# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u2-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 15 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'o': ['name', 'fine', 'bye'], 'plain': True, 'q': "What's your ___?", 't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['My', 'You', 'How'],
                                   'plain': True,
                                   'q': "___ name's Nam. Nice to meet you.",
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['name', 'spell', 'hello'],
                                   'plain': True,
                                   'q': 'How do you ___ your name?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Goodbye.', "Hi, Linda. I'm Mai.", 'Fine, thanks.'],
                                   'plain': True,
                                   'q': "— Hello. I'm Linda. — ___",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ['Peter', 'Linda', 'how'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.6', 'q': "What's {_} name?", 't': 'fill'},
                                  {'id': 't1.7', 'q': "{_} name's Tim.", 't': 'fill'},
                                  {'id': 't1.8', 'q': 'How do you {_} your name?', 't': 'fill'},
                                  {'id': 't1.9', 'q': 'Nice to {_} you.', 't': 'fill'},
                                  {'id': 't1.10', 'o': ['am', 'is', 'are'], 'plain': True, 'q': 'How ___ you, Mai?', 't': 'mcq'},
                                  {'id': 't1.11', 'o': ['What', "What's", 'Hello'], 'plain': True, 'q': '___ her name?', 't': 'mcq'},
                                  {'id': 't1.12', 'q': '', 't': 'order', 'words': ['your', 'name?', "What's"]},
                                  {'id': 't1.13', 'q': '', 't': 'order', 'words': ['name', 'is', 'Linda.', 'My']},
                                  {'id': 't1.14', 'q': '', 't': 'order', 'words': ['you', 'name?', 'do', 'spell', 'How', 'your']},
                                  {'id': 't1.15',
                                   'left': ["What's your name?", 'How do you spell your name?', 'How are you?', "Hello. I'm Mary."],
                                   'o': ["I'm fine, thank you.", 'Hi, Mary.', 'N-A-M.', "My name's Tony."],
                                   'q': 'Nối:',
                                   't': 'match'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': "Unit 2 – What's your name?: Kiểm tra",
 'unit': 2}
