# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u1-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['hello', 'goodbye', 'hi'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "tạm biệt":',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['fine', 'name', 'how'], 'plain': True, 'q': 'Chọn từ nghĩa "khỏe":', 't': 'mcq'},
                                  {'id': 't1.3', 'o': ['See', 'Fine', 'How'], 'plain': True, 'q': 'Bye. ___ you later.', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ["Hi, Nam. I'm Lan.", 'Fine, thanks.', 'Bye.'],
                                   'plain': True,
                                   'q': "— Hello, I'm Nam. — ___",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ['hi', 'hello', 'thanks'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Thank {_}, Mai.', 't': 'fill'},
                                  {'id': 't1.7', 'q': '{_} fine, thanks.', 't': 'fill'},
                                  {'id': 't1.8', 'q': 'Hi! How {_} you?', 't': 'fill'},
                                  {'id': 't1.9', 'q': 'Nice to {_} you.', 't': 'fill'},
                                  {'id': 't1.10', 'q': 'nefi → {_}', 't': 'fill'},
                                  {'id': 't1.11', 'q': '', 't': 'order', 'words': ['Minh.', 'Goodbye,']},
                                  {'id': 't1.12', 'q': '', 't': 'order', 'words': ['Minh.', 'Hi,', "I'm", 'Mai.']},
                                  {'id': 't1.13', 'q': '', 't': 'order', 'words': ['later.', 'Bye.', 'you', 'See']},
                                  {'id': 't1.14',
                                   'left': ['hello', 'goodbye', 'thank you', 'fine'],
                                   'o': ['cảm ơn', 'khỏe', 'tạm biệt', 'xin chào'],
                                   'q': 'Nối từ với nghĩa:',
                                   't': 'match'},
                                  {'id': 't1.15', 'q': '', 't': 'order', 'words': ['you,', 'Ben.', 'Thank']},
                                  {'id': 't1.16',
                                   'o': ['Thanks.', 'Hello.', 'How are you?'],
                                   'plain': True,
                                   'q': '— Thank you. — ___',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ["I'm", 'How', 'Bye'], 'plain': True, 'q': 'Hello, ___ Linda.', 't': 'mcq'},
                                  {'id': 't1.18', 'o': ['are', 'am', 'is'], 'plain': True, 'q': 'How ___ you, Ben?', 't': 'mcq'},
                                  {'id': 't1.19', 'q': 'ohw → {_}', 't': 'fill'},
                                  {'id': 't1.20', 'q': 'G{_}odbye', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 1 – Hello: Kiểm tra 2',
 'unit': 1}
