# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'a.1': 'singing',
 'a.2': 'dancing',
 'a.3': 'drawing',
 'a.4': 'swimming',
 'a.5': 'cooking',
 'a.6': 'walking',
 'a.7': 'painting',
 'a.8': 'running',
 'b.1': 'hobby',
 'b.2': 'like',
 'b.3': 'swimming',
 'b.4': 'hobby',
 'c1.1': ['g'],
 'c1.10': ['k'],
 'c1.2': ['c'],
 'c1.3': ['w'],
 'c1.4': ['m'],
 'c1.5': ['k'],
 'c1.6': ['k'],
 'c1.7': ['t'],
 'c1.8': ['n'],
 'c1.9': ['b'],
 'c2.1': ['singing'],
 'c2.10': ['like'],
 'c2.2': ['dancing'],
 'c2.3': ['drawing'],
 'c2.4': ['swimming'],
 'c2.5': ['cooking'],
 'c2.6': ['walking'],
 'c2.7': ['painting'],
 'c2.8': ['running'],
 'c2.9': ['hobby'],
 'd.1': {'blanks': [["It's singing."], ["It's drawing."], ['Me too.'], ["I'm fine, thanks."], ["My name's Nam."]]},
 'e.1': ['hobby'],
 'e.2': ['like'],
 'e.3': ['and'],
 'e.4': ['hobbies'],
 'e.5': ['singing'],
 'e.6': ['dancing'],
 'e.7': ['swimming'],
 'e.8': ['cooking'],
 'e2.1': "It's singing.",
 'e2.10': 'likes',
 'e2.11': 'running',
 'e2.12': 'dancing',
 'e2.2': 'like',
 'e2.3': 'likes',
 'e2.4': 'hobbies',
 'e2.5': 'swimming',
 'e2.6': 'drawing',
 'e2.7': 'cooking',
 'e2.8': 'hobby',
 'e2.9': 'Me too.',
 'f.1': ["What's your hobby?"],
 'f.2': ["It's singing."],
 'f.3': ['I like dancing.'],
 'f.4': ['I like swimming.'],
 'f.5': ['My hobby is painting.'],
 'f.6': ['She likes singing and dancing.'],
 'f2.1': ['running'],
 'f2.2': ['walking'],
 'f2.3': ['drawing'],
 'f2.4': ['painting'],
 'f2.5': ['drawing', 'singing', 'dancing', 'cooking', 'swimming', 'walking', 'painting', 'running'],
 'f2.6': ['likes'],
 'g2.1': ['Our hobbies are swimming and cooking.'],
 'g2.2': ["It's cooking."],
 'g2.3': ['I like running.'],
 'g2.4': ['He likes walking.'],
 'm1.1': {'blanks': [['hát'], ['nhảy, múa'], ['vẽ'], ['bơi'], ['nấu ăn'], ['đi bộ']]},
 'm1.2': {'blanks': [['tô màu, sơn'], ['chạy'], ['sở thích'], ['thích']]},
 'n1.1': 'singing',
 'n1.2': 'dancing',
 'n1.3': 'drawing',
 'n1.4': 'swimming',
 'n1.5': 'cooking',
 'n1.6': 'walking',
 'n2.1': "It's singing.",
 'n2.2': "It's drawing.",
 'n2.3': 'Me too.',
 'n2.4': "I'm fine, thanks.",
 'n2.5': "My name's Nam.",
 'n3.1': ['singing'],
 'n3.2': ['dancing'],
 'n3.3': ['drawing'],
 'n3.4': ['swimming'],
 'n3.5': ['cooking'],
 'n4.1': ["What's your hobby?"],
 'n4.2': ["It's singing."],
 'n4.3': ['I like dancing.'],
 'r1.1': {'blanks': [['1'], ['2'], ['3'], ['4']]},
 'r2.1': 'T',
 'r2.2': 'F',
 'r2.3': 'T',
 'r3.1': 'T',
 'r3.2': 'F',
 'r3.3': 'T'}

EXPLANATIONS = {'a.1': 'singing = hát (🎤)',
 'a.2': 'dancing = nhảy, múa (💃)',
 'a.3': 'drawing = vẽ (✏️)',
 'a.4': 'swimming = bơi (🏊)',
 'a.5': 'cooking = nấu ăn (🍳)',
 'a.6': 'walking = đi bộ (🚶)',
 'a.7': 'painting = tô màu, sơn (🖌️)',
 'a.8': 'running = chạy (🏃)',
 'b.1': 'singing, dancing là hoạt động cụ thể; hobby là "sở thích".',
 'b.2': 'running, walking là hoạt động; like là "thích".',
 'b.3': 'drawing, painting là hoạt động vẽ/tô; swimming là bơi.',
 'b.4': 'hobby là danh từ chung.',
 'c1.1': 'singing',
 'c1.10': 'like',
 'c1.2': 'dancing',
 'c1.3': 'drawing',
 'c1.4': 'swimming',
 'c1.5': 'cooking',
 'c1.6': 'walking',
 'c1.7': 'painting',
 'c1.8': 'running',
 'c1.9': 'hobby',
 'c2.1': 'singing',
 'c2.10': 'like',
 'c2.2': 'dancing',
 'c2.3': 'drawing',
 'c2.4': 'swimming',
 'c2.5': 'cooking',
 'c2.6': 'walking',
 'c2.7': 'painting',
 'c2.8': 'running',
 'c2.9': 'hobby',
 'd.1': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 'e.1': 'hobby = sở thích',
 'e.2': 'I like … = Mình thích …',
 'e.3': 'and = và',
 'e.4': 'hobbies = các sở thích',
 'e.5': 'singing = hát',
 'e.6': 'dancing = nhảy',
 'e.7': 'swimming = bơi',
 'e.8': 'cooking = nấu ăn',
 'e2.1': "Hỏi sở thích → It's + hoạt động.",
 'e2.10': 'He + likes',
 'e2.11': '🏃 = running.',
 'e2.12': '💃 = dancing.',
 'e2.2': 'I like …',
 'e2.3': 'She + likes',
 'e2.4': 'Số nhiều: hobbies.',
 'e2.5': 'swimming = bơi.',
 'e2.6': 'drawing = vẽ.',
 'e2.7': 'cooking = nấu ăn.',
 'e2.8': "What's your hobby? – It's singing.",
 'e2.9': 'Me too = mình cũng vậy.',
 'f.1': "What's your hobby?",
 'f.2': "It's singing.",
 'f.3': 'I like dancing.',
 'f.4': 'I like swimming.',
 'f.5': 'My hobby is painting.',
 'f.6': 'She likes singing and dancing.',
 'f2.1': 'running = chạy',
 'f2.2': 'walking = đi bộ',
 'f2.3': 'drawing = vẽ',
 'f2.4': 'painting = tô màu',
 'f2.5': "Trả lời bằng một sở thích, ví dụ: It's drawing.",
 'f2.6': 'He/She + likes',
 'g2.1': 'Our hobbies are swimming and cooking.',
 'g2.2': "It's cooking.",
 'g2.3': 'I like running.',
 'g2.4': 'He likes walking.',
 'm1.1': 'singing = hát; dancing = nhảy, múa; drawing = vẽ; swimming = bơi; cooking = nấu ăn; walking = đi bộ',
 'm1.2': 'painting = tô màu, sơn; running = chạy; hobby = sở thích; like = thích',
 'n1.1': 'Từ được đọc là: singing.',
 'n1.2': 'Từ được đọc là: dancing.',
 'n1.3': 'Từ được đọc là: drawing.',
 'n1.4': 'Từ được đọc là: swimming.',
 'n1.5': 'Từ được đọc là: cooking.',
 'n1.6': 'Từ được đọc là: walking.',
 'n2.1': "What's your hobby? → It's singing.",
 'n2.2': "What's your hobby, Mary? → It's drawing.",
 'n2.3': 'I like dancing. → Me too.',
 'n2.4': "How are you? → I'm fine, thanks.",
 'n2.5': "What's your name? → My name's Nam.",
 'n3.1': 'singing',
 'n3.2': 'dancing',
 'n3.3': 'drawing',
 'n3.4': 'swimming',
 'n3.5': 'cooking',
 'n4.1': "What's your hobby?",
 'n4.2': "It's singing.",
 'n4.3': 'I like dancing.',
 'r1.1': "Thứ tự đúng: Mary: What's your hobby, Nam? → Nam: It's running. What's your hobby? → Mary: It's drawing. → Nam: I like drawing, "
         'too. → Mary: Thank you.',
 'r2.1': 'My hobby is drawing.',
 'r2.2': 'Mai thích drawing và painting.',
 'r2.3': 'My friend Nam likes swimming.',
 'r3.1': "It's singing.",
 'r3.2': 'Tom thích singing và dancing.',
 'r3.3': 'Me too!'}

GHI_CHU_RA_SOAT = []
