# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u1-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'o': ['Hello', 'Fine', 'Bye'], 'plain': True, 'q': "___, I'm Tony.", 't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ["I'm fine, thank you.", "I'm Mai.", 'Goodbye.'],
                                   'plain': True,
                                   'q': '— How are you? — ___',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['Bye, Mai.', 'Hello.', 'Fine.'],
                                   'plain': True,
                                   'q': '— Goodbye, Nam. — ___',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Nice to meet you, too.', 'Bye.', 'How are you?'],
                                   'plain': True,
                                   'q': '— Nice to meet you. — ___',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ['bye', 'goodbye', 'hello'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.6', 'q': "Hello, I'm Mai. Nice to meet {_}.", 't': 'fill'},
                                  {'id': 't1.7', 'q': 'How {_} you?', 't': 'fill'},
                                  {'id': 't1.8', 'q': "I'm {_}, thanks.", 't': 'fill'},
                                  {'id': 't1.9', 'q': 'Goodbye. See you {_}.', 't': 'fill'},
                                  {'id': 't1.10', 'q': 'eyb → {_}', 't': 'fill'},
                                  {'id': 't1.11', 'q': '', 't': 'order', 'words': ['Miss', 'Hoa.', 'Hello,']},
                                  {'id': 't1.12', 'q': '', 't': 'order', 'words': ['fine,', 'thanks.', "I'm"]},
                                  {'id': 't1.13', 'q': '', 't': 'order', 'words': ['are', 'you?', 'How']},
                                  {'id': 't1.14',
                                   'left': ['How are you?', 'Goodbye!', 'Nice to meet you!', 'Hello!'],
                                   'o': ['Hello!', 'Fine, thanks.', 'Nice to meet you, too!', 'Bye. See you later.'],
                                   'q': 'Nối:',
                                   't': 'match'},
                                  {'id': 't1.15', 'q': '', 't': 'order', 'words': ['Miss', 'Hoa.', 'Goodbye,']},
                                  {'id': 't1.16',
                                   'o': ['thank you', 'fine', 'bye'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "cảm ơn":',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['bye', 'goodbye', 'hi'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "xin chào":',
                                   't': 'mcq'},
                                  {'id': 't1.18', 'o': ['How', 'What', "I'm"], 'plain': True, 'q': 'Hi, Mai. ___ are you?', 't': 'mcq'},
                                  {'id': 't1.19', 'q': 'Thank {_}.', 't': 'fill'},
                                  {'id': 't1.20', 'q': 'lehol → {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 1 – Hello: Kiểm tra 1',
 'unit': 1}
