# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'t1.1': 'Yes, it is.',
 't1.10': 'Yes, it is.',
 't1.11': ['thank you', 'thanks'],
 't1.12': ['Is'],
 't1.13': ['that'],
 't1.14': ['Mr'],
 't1.15': ['friend'],
 't1.16': ['This is my friend Linh.'],
 't1.17': ["That's my teacher, Ms Hoa."],
 't1.18': ['Is this Bill?'],
 't1.19': ['Yes, it is.'],
 't1.2': 'is',
 't1.20': {'blanks': [['Yes, it is.'], ["No, it isn't. It's Minh."], ['Hi, Mary.'], ['Hello, Mr Long.']]},
 't1.3': "isn't",
 't1.4': 'This',
 't1.5': 'friend',
 't1.6': 'teacher',
 't1.7': 'yes',
 't1.8': 'bạn',
 't1.9': 'giáo viên'}

EXPLANATIONS = {'t1.1': 'Is this …? → Yes, it is.',
 't1.10': 'Is this Bill? → Yes, it is.',
 't1.11': "I'm fine, thank you.",
 't1.12': 'Câu hỏi bắt đầu bằng Is: Is this Lan?',
 't1.13': 'Is that Mai? (người ở xa)',
 't1.14': 'Mr Long = thầy/ông Long.',
 't1.15': 'friend',
 't1.16': 'This is my friend Linh.',
 't1.17': "That's my teacher, Ms Hoa.",
 't1.18': 'Is this Bill?',
 't1.19': 'Yes, it is.',
 't1.2': 'This is …',
 't1.20': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 't1.3': "No, it isn't.",
 't1.4': 'This = ở gần.',
 't1.5': 'friend = bạn (👫)',
 't1.6': 'teacher = giáo viên (👩\u200d🏫)',
 't1.7': 'Mr, Ms dùng trước tên người; yes là "vâng".',
 't1.8': 'friend = bạn',
 't1.9': 'teacher = giáo viên'}

GHI_CHU_RA_SOAT = []
