# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u4-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'o': ['Touch', 'Open', 'That'], 'plain': True, 'q': '___ your nose! (sờ mũi)', 't': 'mcq'},
                                  {'id': 't1.2', 'o': ['an', 'a', 'no'], 'plain': True, 'q': "What's that? 👁️ – It's ___ eye.", 't': 'mcq'},
                                  {'id': 't1.3', 'o': ['a', 'an', 'is'], 'plain': True, 'q': "What's this? 🙂 – It's ___ face.", 't': 'mcq'},
                                  {'id': 't1.4', 'o': ['ear', 'eye', 'hand'], 'plain': True, 'q': 'Chọn từ nghĩa "tai":', 't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['face', 'mouth', 'eye'],
                                   'plain': True,
                                   'q': '<span class="emo">👁️</span>',
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'o': ['ear', 'nose', 'hand'],
                                   'plain': True,
                                   'q': '<span class="emo">👂</span>',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['nose', 'mouth', 'touch'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.8', 'o': ['tóc', 'tai', 'mắt'], 'plain': True, 'q': 'Nghĩa của "eye" là:', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['khuôn mặt', 'sờ, chạm', 'tai'],
                                   'plain': True,
                                   'q': 'Nghĩa của "ear" là:',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ["My name's Mai.", 'Yes, it is.', "It's an eye."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': "What's that?",
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': "It's {_} ear.", 't': 'fill'},
                                  {'id': 't1.12', 'q': '👃 Touch your {_}.', 't': 'fill'},
                                  {'id': 't1.13', 'q': '👂 Touch your {_}.', 't': 'fill'},
                                  {'id': 't1.14', 'q': '👄 Open your {_}.', 't': 'fill'},
                                  {'id': 't1.15', 'q': 'sneo → {_}', 't': 'fill'},
                                  {'id': 't1.16', 'q': '', 't': 'order', 'words': ['your', 'ears.', 'Touch']},
                                  {'id': 't1.17', 'q': '', 't': 'order', 'words': ['eyes.', 'Open', 'your']},
                                  {'id': 't1.18', 'q': '', 't': 'order', 'words': ['hair.', 'your', 'Touch']},
                                  {'id': 't1.19', 'q': '', 't': 'order', 'words': ['this?', "What's"]},
                                  {'id': 't1.20',
                                   'left': ["What's that?", 'How are you?', "What's your name?", 'Is this Bill?'],
                                   'o': ['Yes, it is.', "It's an eye.", "My name's Mai.", "I'm fine, thanks."],
                                   'q': 'Nối:',
                                   't': 'match'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 4 – Our bodies: Kiểm tra 2',
 'unit': 4}
