# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u3-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Yes, it is.', 'Yes, I am.', 'Fine, thanks.'],
                                   'plain': True,
                                   'q': 'Is this Bill? – ___',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['is', 'are', 'am'], 'plain': True, 'q': 'This ___ my friend.', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["isn't", 'is', 'am'],
                                   'plain': True,
                                   'q': "Is that Nam? – No, it ___. It's Minh.",
                                   't': 'mcq'},
                                  {'id': 't1.4', 'o': ['This', 'That', 'It'], 'plain': True, 'q': '___ is Mary. (người ở gần)', 't': 'mcq'},
                                  {'id': 't1.5', 'o': ['no', 'Mr', 'friend'], 'plain': True, 'q': '<span class="emo">👫</span>', 't': 'mcq'},
                                  {'id': 't1.6',
                                   'o': ['yes', 'that', 'teacher'],
                                   'plain': True,
                                   'q': '<span class="emo">👩\u200d🏫</span>',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['Mr', 'Ms', 'yes'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['kia, cái kia (ở xa)', 'giáo viên', 'bạn'],
                                   'plain': True,
                                   'q': 'Nghĩa của "friend" là:',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['nó', 'bạn', 'giáo viên'],
                                   'plain': True,
                                   'q': 'Nghĩa của "teacher" là:',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ["I'm fine, thank you.", "No, it isn't. It's Minh.", 'Yes, it is.'],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'Is this Bill?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': "How are you, Minh? – I'm fine, {_}.", 't': 'fill'},
                                  {'id': 't1.12', 'q': "{_} this Lan? – No, it isn't. It's Lucy.", 't': 'fill'},
                                  {'id': 't1.13', 'q': 'Is {_} Mai? – Yes, it is.', 't': 'fill'},
                                  {'id': 't1.14', 'q': "That's {_} Long. – Hello, Mr Long.", 't': 'fill'},
                                  {'id': 't1.15', 'q': 'dinfer → {_}', 't': 'fill'},
                                  {'id': 't1.16', 'q': '', 't': 'order', 'words': ['Linh.', 'friend', 'my', 'This', 'is']},
                                  {'id': 't1.17', 'q': '', 't': 'order', 'words': ["That's", 'Hoa.', 'my', 'Ms', 'teacher,']},
                                  {'id': 't1.18', 'q': '', 't': 'order', 'words': ['Bill?', 'this', 'Is']},
                                  {'id': 't1.19', 'q': '', 't': 'order', 'words': ['it', 'is.', 'Yes,']},
                                  {'id': 't1.20',
                                   'left': ['Is this Bill?', 'Is that Nam?', 'This is Mary.', "That's Mr Long."],
                                   'o': ['Hi, Mary.', 'Hello, Mr Long.', "No, it isn't. It's Minh.", 'Yes, it is.'],
                                   'q': 'Nối:',
                                   't': 'match'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 3 – Our friends: Kiểm tra 1',
 'unit': 3}
