# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'a.1': 'bye',
 'a.2': 'how',
 'a.3': 'name',
 'a.4': 'hi',
 'a.5': 'fine',
 'b.1': ['Peter'],
 'b.2': ['Linda'],
 'b.3': ['goodbye'],
 'b.4': ['name'],
 'b.5': ['spell'],
 'c.1': {'blanks': [["Hi, Mary. I'm Phuong."],
                    ["My name's Tony."],
                    ['N-A-M.'],
                    ["I'm fine, thank you."],
                    ["My name's Ha. Nice to meet you, too."]]},
 'd.1': ["What's"],
 'd.2': ["name's", 'name is'],
 'd.3': ['Linda'],
 'd.4': ['Nice'],
 'd.5': ['How'],
 'e.1': ["What's"],
 'e.2': ['My'],
 'e.3': ['How'],
 'e.4': ['name'],
 'e.5': ['are'],
 'e.6': ['to'],
 'f.1': ['What is your name?'],
 'f.2': ['My name is Mary.'],
 'f.3': ['I am Linda.'],
 'f.4': ['How do you spell your name?'],
 'f.5': ['Her name is Mai.'],
 'g.1': ['Tommy'],
 'g.2': ['Bella'],
 'g.3': ['Lola'],
 'g.4': ['Lily'],
 'h.1': 'are',
 'h.2': 'See',
 'h.3': 'Hello',
 'h.4': 'soon',
 'h.5': "What's",
 'm1.1': {'blanks': [['cái gì'], ['của bạn'], ['của tôi'], ['tên'], ['đánh vần'], ['như thế nào']]}}

EXPLANATIONS = {'a.1': 'Hi, hello là chào; bye là tạm biệt.',
 'a.2': 'Peter, Linda là tên; how là từ để hỏi.',
 'a.3': 'Bye, goodbye là tạm biệt; name là tên.',
 'a.4': 'what, how là từ để hỏi; hi là lời chào.',
 'a.5': 'Tony, Peter là tên người; fine là khỏe.',
 'b.1': 'P-e-t-e-r = Peter.',
 'b.2': 'L-i-n-d-a = Linda.',
 'b.3': 'g-o-o-d-b-y-e = goodbye.',
 'b.4': 'n-a-m-e = name.',
 'b.5': 's-p-e-l-l = spell.',
 'c.1': 'Chào – chào lại; hỏi tên – nói tên; hỏi cách đánh vần – đánh vần; hỏi thăm – trả lời khỏe; làm quen – đáp lại.',
 'd.1': "What's your name? = Tên bạn là gì?",
 'd.2': "my name's / my name is = tên mình là.",
 'd.3': 'Gọi tên bạn đang nói chuyện: Linda.',
 'd.4': 'Nice to meet you, too.',
 'd.5': 'How do you spell your name?',
 'e.1': "What's your name?",
 'e.2': "My name's Tim.",
 'e.3': 'How do you spell your name?',
 'e.4': 'My name is Mary.',
 'e.5': 'How are you?',
 'e.6': 'Nice to meet you.',
 'f.1': 'What is your name? = Tên bạn là gì?',
 'f.2': 'My name is Mary.',
 'f.3': 'I am Linda. = Mình là Linda.',
 'f.4': 'How do you spell your name?',
 'f.5': 'Her name is Mai. = Tên bạn ấy là Mai.',
 'g.1': 'He is Tommy.',
 'g.2': 'She is Bella.',
 'g.3': 'She is Lola.',
 'g.4': 'She is Lily.',
 'h.1': 'Chủ ngữ you → are: How are you?',
 'h.2': 'See you later. = Hẹn gặp lại.',
 'h.3': 'Giới thiệu bản thân → Hello.',
 'h.4': 'See you soon. = Hẹn sớm gặp lại.',
 'h.5': "What's her name? = Tên bạn ấy là gì?",
 'm1.1': 'what = cái gì, your = của bạn, my = của tôi, name = tên, spell = đánh vần, how = như thế nào.'}

GHI_CHU_RA_SOAT = []
