# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u5-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["It's singing.", "I'm fine.", 'Yes, it is.'],
                                   'plain': True,
                                   'q': "What's your hobby? – ___",
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['like', 'likes', 'is'], 'plain': True, 'q': 'I ___ dancing.', 't': 'mcq'},
                                  {'id': 't1.3', 'o': ['likes', 'like', 'am'], 'plain': True, 'q': 'She ___ singing.', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['hobbies', 'hobby', 'like'],
                                   'plain': True,
                                   'q': 'Our ___ are swimming and cooking.',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['drawing', 'cooking', 'singing'],
                                   'plain': True,
                                   'q': '<span class="emo">🎤</span>',
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'o': ['swimming', 'painting', 'dancing'],
                                   'plain': True,
                                   'q': '<span class="emo">💃</span>',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['singing', 'dancing', 'hobby'],
                                   'plain': True,
                                   'q': 'Chọn từ khác loại:',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['vẽ', 'chạy', 'hát'], 'plain': True, 'q': 'Nghĩa của "singing" là:', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['nhảy, múa', 'chạy', 'vẽ'],
                                   'plain': True,
                                   'q': 'Nghĩa của "dancing" là:',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ["It's singing.", "It's drawing.", "My name's Nam."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': "What's your hobby?",
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': "What's your {_}? – It's singing.", 't': 'fill'},
                                  {'id': 't1.12', 'q': 'I {_} dancing.', 't': 'fill'},
                                  {'id': 't1.13', 'q': 'She likes singing {_} dancing.', 't': 'fill'},
                                  {'id': 't1.14', 'q': 'Our {_} are swimming and cooking.', 't': 'fill'},
                                  {'id': 't1.15', 'q': 'ngnisgi → {_}', 't': 'fill'},
                                  {'id': 't1.16', 'q': '', 't': 'order', 'words': ['your', 'hobby?', "What's"]},
                                  {'id': 't1.17', 'q': '', 't': 'order', 'words': ['singing.', "It's"]},
                                  {'id': 't1.18', 'q': '', 't': 'order', 'words': ['dancing.', 'like', 'I']},
                                  {'id': 't1.19', 'q': '', 't': 'order', 'words': ['like', 'swimming.', 'I']},
                                  {'id': 't1.20',
                                   'left': ["What's your hobby?", "What's your hobby, Mary?", 'I like dancing.', 'How are you?'],
                                   'o': ["It's singing.", "I'm fine, thanks.", 'Me too.', "It's drawing."],
                                   'q': 'Nối:',
                                   't': 'match'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 5 – My hobbies: Kiểm tra 1',
 'unit': 5}
