# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'t1.1': 'swimming',
 't1.10': "It's drawing.",
 't1.11': ['singing'],
 't1.12': ['dancing'],
 't1.13': ['swimming'],
 't1.14': ['cooking'],
 't1.15': ['dancing'],
 't1.16': ['My hobby is painting.'],
 't1.17': ['She likes singing and dancing.'],
 't1.18': ['Our hobbies are swimming and cooking.'],
 't1.19': ["It's cooking."],
 't1.2': 'drawing',
 't1.20': {'blanks': [["It's drawing."], ['Me too.'], ["I'm fine, thanks."], ["My name's Nam."]]},
 't1.3': 'cooking',
 't1.4': 'hobby',
 't1.5': 'drawing',
 't1.6': 'swimming',
 't1.7': 'like',
 't1.8': 'vẽ',
 't1.9': 'bơi'}

EXPLANATIONS = {'t1.1': 'swimming = bơi.',
 't1.10': "What's your hobby, Mary? → It's drawing.",
 't1.11': 'singing = hát',
 't1.12': 'dancing = nhảy',
 't1.13': 'swimming = bơi',
 't1.14': 'cooking = nấu ăn',
 't1.15': 'dancing',
 't1.16': 'My hobby is painting.',
 't1.17': 'She likes singing and dancing.',
 't1.18': 'Our hobbies are swimming and cooking.',
 't1.19': "It's cooking.",
 't1.2': 'drawing = vẽ.',
 't1.20': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 't1.3': 'cooking = nấu ăn.',
 't1.4': "What's your hobby? – It's singing.",
 't1.5': 'drawing = vẽ (✏️)',
 't1.6': 'swimming = bơi (🏊)',
 't1.7': 'running, walking là hoạt động; like là "thích".',
 't1.8': 'drawing = vẽ',
 't1.9': 'swimming = bơi'}

GHI_CHU_RA_SOAT = []
