# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u5-luyentap',
 'pages': [{'groups': [{'id': 'm1',
                        'instr': 'Nối từ tiếng Anh với nghĩa tiếng Việt.',
                        'items': [{'id': 'm1.1',
                                   'left': ['singing', 'dancing', 'drawing', 'swimming', 'cooking', 'walking'],
                                   'o': ['nấu ăn', 'vẽ', 'nhảy, múa', 'bơi', 'đi bộ', 'hát'],
                                   'q': '',
                                   't': 'match'},
                                  {'id': 'm1.2',
                                   'left': ['painting', 'running', 'hobby', 'like'],
                                   'o': ['tô màu, sơn', 'thích', 'chạy', 'sở thích'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'a',
                        'instr': 'Nhìn hình và chọn từ đúng.',
                        'items': [{'id': 'a.1',
                                   'o': ['running', 'walking', 'singing'],
                                   'plain': True,
                                   'q': '<span class="emo">🎤</span>',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['dancing', 'swimming', 'running'],
                                   'plain': True,
                                   'q': '<span class="emo">💃</span>',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['swimming', 'dancing', 'drawing'],
                                   'plain': True,
                                   'q': '<span class="emo">✏️</span>',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['cooking', 'drawing', 'swimming'],
                                   'plain': True,
                                   'q': '<span class="emo">🏊</span>',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['walking', 'running', 'cooking'],
                                   'plain': True,
                                   'q': '<span class="emo">🍳</span>',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['dancing', 'swimming', 'walking'],
                                   'plain': True,
                                   'q': '<span class="emo">🚶</span>',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['swimming', 'dancing', 'painting'],
                                   'plain': True,
                                   'q': '<span class="emo">🖌️</span>',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['drawing', 'cooking', 'running'],
                                   'plain': True,
                                   'q': '<span class="emo">🏃</span>',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Chọn từ khác loại.',
                        'items': [{'id': 'b.1', 'o': ['singing', 'dancing', 'hobby'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['running', 'walking', 'like'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['drawing', 'painting', 'swimming'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['cooking', 'singing', 'hobby'], 'plain': True, 'q': '', 't': 'mcq'}]}],
            'id': 'tu-vung',
            'mode': 'practice',
            'title': 'Từ vựng'},
           {'groups': [{'id': 'd',
                        'instr': 'Nối câu hỏi / lời nói (cột A) với câu trả lời (cột B).',
                        'items': [{'id': 'd.1',
                                   'left': ["What's your hobby?",
                                            "What's your hobby, Mary?",
                                            'I like dancing.',
                                            'How are you?',
                                            "What's your name?"],
                                   'o': ["I'm fine, thanks.", "My name's Nam.", "It's singing.", "It's drawing.", 'Me too.'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'e',
                        'instr': 'Điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'e.1', 'q': "What's your {_}? – It's singing.", 't': 'fill'},
                                  {'id': 'e.2', 'q': 'I {_} dancing.', 't': 'fill'},
                                  {'id': 'e.3', 'q': 'She likes singing {_} dancing.', 't': 'fill'},
                                  {'id': 'e.4', 'q': 'Our {_} are swimming and cooking.', 't': 'fill'},
                                  {'id': 'e.5', 'q': "🎤 It's {_}.", 't': 'fill'},
                                  {'id': 'e.6', 'q': "💃 It's {_}.", 't': 'fill'},
                                  {'id': 'e.7', 'q': "🏊 It's {_}.", 't': 'fill'},
                                  {'id': 'e.8', 'q': "🍳 It's {_}.", 't': 'fill'}]},
                       {'id': 'f',
                        'instr': 'Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'f.1', 'q': '', 't': 'order', 'words': ['hobby?', 'your', "What's"]},
                                  {'id': 'f.2', 'q': '', 't': 'order', 'words': ['singing.', "It's"]},
                                  {'id': 'f.3', 'q': '', 't': 'order', 'words': ['dancing.', 'I', 'like']},
                                  {'id': 'f.4', 'q': '', 't': 'order', 'words': ['swimming.', 'like', 'I']},
                                  {'id': 'f.5', 'q': '', 't': 'order', 'words': ['painting.', 'is', 'hobby', 'My']},
                                  {'id': 'f.6', 'q': '', 't': 'order', 'words': ['and', 'singing', 'likes', 'She', 'dancing.']}]}],
            'id': 'mau-cau',
            'mode': 'practice',
            'title': 'Mẫu câu'},
           {'groups': [{'id': 'e2',
                        'instr': 'Chọn đáp án đúng.',
                        'items': [{'id': 'e2.1',
                                   'o': ["It's singing.", "I'm fine.", 'Yes, it is.'],
                                   'plain': True,
                                   'q': "What's your hobby? – ___",
                                   't': 'mcq'},
                                  {'id': 'e2.2', 'o': ['like', 'likes', 'is'], 'plain': True, 'q': 'I ___ dancing.', 't': 'mcq'},
                                  {'id': 'e2.3', 'o': ['likes', 'like', 'am'], 'plain': True, 'q': 'She ___ singing.', 't': 'mcq'},
                                  {'id': 'e2.4',
                                   'o': ['hobbies', 'hobby', 'like'],
                                   'plain': True,
                                   'q': 'Our ___ are swimming and cooking.',
                                   't': 'mcq'},
                                  {'id': 'e2.5',
                                   'o': ['swimming', 'running', 'walking'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "bơi":',
                                   't': 'mcq'},
                                  {'id': 'e2.6',
                                   'o': ['drawing', 'painting', 'cooking'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "vẽ":',
                                   't': 'mcq'},
                                  {'id': 'e2.7',
                                   'o': ['cooking', 'singing', 'dancing'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "nấu ăn":',
                                   't': 'mcq'},
                                  {'id': 'e2.8',
                                   'o': ['hobby', 'like', 'friend'],
                                   'plain': True,
                                   'q': "What's your ___? – It's singing.",
                                   't': 'mcq'},
                                  {'id': 'e2.9',
                                   'o': ['Me too.', 'Goodbye.', 'Yes, it is.'],
                                   'plain': True,
                                   'q': 'I like singing. – ___',
                                   't': 'mcq'},
                                  {'id': 'e2.10', 'o': ['likes', 'like', 'are'], 'plain': True, 'q': 'He ___ running.', 't': 'mcq'},
                                  {'id': 'e2.11',
                                   'o': ['running', 'swimming', 'cooking'],
                                   'plain': True,
                                   'q': "What's your hobby? 🏃 – It's ___.",
                                   't': 'mcq'},
                                  {'id': 'e2.12',
                                   'o': ['dancing', 'singing', 'drawing'],
                                   'plain': True,
                                   'q': "What's your hobby? 💃 – It's ___.",
                                   't': 'mcq'}]},
                       {'id': 'f2',
                        'instr': 'Điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'f2.1', 'q': '🏃 I like {_}.', 't': 'fill'},
                                  {'id': 'f2.2', 'q': '🚶 I like {_}.', 't': 'fill'},
                                  {'id': 'f2.3', 'q': '✏️ My hobby is {_}.', 't': 'fill'},
                                  {'id': 'f2.4', 'q': '🖌️ I like {_}.', 't': 'fill'},
                                  {'id': 'f2.5', 'q': "What's your hobby, Mary? – It's {_}.", 't': 'fill'},
                                  {'id': 'f2.6', 'q': 'He {_} running.', 't': 'fill'}]},
                       {'id': 'g2',
                        'instr': 'Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'g2.1', 'q': '', 't': 'order', 'words': ['cooking.', 'are', 'swimming', 'hobbies', 'and', 'Our']},
                                  {'id': 'g2.2', 'q': '', 't': 'order', 'words': ['cooking.', "It's"]},
                                  {'id': 'g2.3', 'q': '', 't': 'order', 'words': ['I', 'running.', 'like']},
                                  {'id': 'g2.4', 'q': '', 't': 'order', 'words': ['walking.', 'likes', 'He']}]}],
            'id': 'mau-cau-2',
            'mode': 'practice',
            'title': 'Mẫu câu 2'},
           {'groups': [{'id': 'n1',
                        'instr': 'Nghe 1. Bấm 🔊 (nghe lại được nhiều lần) và chọn từ em nghe được.',
                        'items': [{'id': 'n1.1',
                                   'o': ['hobby', 'walking', 'singing'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'singing',
                                   't': 'mcq'},
                                  {'id': 'n1.2',
                                   'o': ['swimming', 'dancing', 'singing'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'dancing',
                                   't': 'mcq'},
                                  {'id': 'n1.3',
                                   'o': ['painting', 'singing', 'drawing'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'drawing',
                                   't': 'mcq'},
                                  {'id': 'n1.4',
                                   'o': ['like', 'drawing', 'swimming'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'swimming',
                                   't': 'mcq'},
                                  {'id': 'n1.5',
                                   'o': ['hobby', 'walking', 'cooking'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'cooking',
                                   't': 'mcq'},
                                  {'id': 'n1.6',
                                   'o': ['swimming', 'dancing', 'walking'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'walking',
                                   't': 'mcq'}]},
                       {'id': 'n2',
                        'instr': 'Nghe 2. Nghe câu và chọn câu trả lời phù hợp.',
                        'items': [{'id': 'n2.1',
                                   'o': ["My name's Nam.", "It's drawing.", "It's singing."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': "What's your hobby?",
                                   't': 'mcq'},
                                  {'id': 'n2.2',
                                   'o': ["It's singing.", "I'm fine, thanks.", "It's drawing."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': "What's your hobby, Mary?",
                                   't': 'mcq'},
                                  {'id': 'n2.3',
                                   'o': ['Me too.', "I'm fine, thanks.", "It's singing."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'I like dancing.',
                                   't': 'mcq'},
                                  {'id': 'n2.4',
                                   'o': ["My name's Nam.", "It's drawing.", "I'm fine, thanks."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'How are you?',
                                   't': 'mcq'},
                                  {'id': 'n2.5',
                                   'o': ["My name's Nam.", "It's drawing.", "I'm fine, thanks."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': "What's your name?",
                                   't': 'mcq'}]},
                       {'id': 'n3',
                        'instr': 'Nghe 3. Nghe và viết lại từ.',
                        'items': [{'id': 'n3.1', 'q': '{_}', 'say': 'singing', 't': 'fill'},
                                  {'id': 'n3.2', 'q': '{_}', 'say': 'dancing', 't': 'fill'},
                                  {'id': 'n3.3', 'q': '{_}', 'say': 'drawing', 't': 'fill'},
                                  {'id': 'n3.4', 'q': '{_}', 'say': 'swimming', 't': 'fill'},
                                  {'id': 'n3.5', 'q': '{_}', 'say': 'cooking', 't': 'fill'}]},
                       {'id': 'n4',
                        'instr': 'Nghe 4. Nghe và viết lại cả câu.',
                        'items': [{'id': 'n4.1', 'q': '{_}', 'say': "What's your hobby?", 't': 'fill'},
                                  {'id': 'n4.2', 'q': '{_}', 'say': "It's singing.", 't': 'fill'},
                                  {'id': 'n4.3', 'q': '{_}', 'say': 'I like dancing.', 't': 'fill'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Nghe'},
           {'groups': [{'id': 'c1',
                        'instr': 'Điền chữ cái còn thiếu.',
                        'items': [{'id': 'c1.1', 'q': 'sin{_}ing', 't': 'fill'},
                                  {'id': 'c1.2', 'q': 'dan{_}ing', 't': 'fill'},
                                  {'id': 'c1.3', 'q': 'dra{_}ing', 't': 'fill'},
                                  {'id': 'c1.4', 'q': 'swim{_}ing', 't': 'fill'},
                                  {'id': 'c1.5', 'q': 'coo{_}ing', 't': 'fill'},
                                  {'id': 'c1.6', 'q': 'wal{_}ing', 't': 'fill'},
                                  {'id': 'c1.7', 'q': 'pain{_}ing', 't': 'fill'},
                                  {'id': 'c1.8', 'q': 'run{_}ing', 't': 'fill'},
                                  {'id': 'c1.9', 'q': 'ho{_}by', 't': 'fill'},
                                  {'id': 'c1.10', 'q': 'li{_}e', 't': 'fill'}]},
                       {'id': 'c2',
                        'instr': 'Sắp xếp lại chữ cái thành từ đúng.',
                        'items': [{'id': 'c2.1', 'q': 'ginisng → {_}', 't': 'fill'},
                                  {'id': 'c2.2', 'q': 'adncngi → {_}', 't': 'fill'},
                                  {'id': 'c2.3', 'q': 'gnwiadr → {_}', 't': 'fill'},
                                  {'id': 'c2.4', 'q': 'imwmisng → {_}', 't': 'fill'},
                                  {'id': 'c2.5', 'q': 'conkgoi → {_}', 't': 'fill'},
                                  {'id': 'c2.6', 'q': 'niawlgk → {_}', 't': 'fill'},
                                  {'id': 'c2.7', 'q': 'ptigiann → {_}', 't': 'fill'},
                                  {'id': 'c2.8', 'q': 'gnrniun → {_}', 't': 'fill'},
                                  {'id': 'c2.9', 'q': 'hybob → {_}', 't': 'fill'},
                                  {'id': 'c2.10', 'q': 'iekl → {_}', 't': 'fill'}]}],
            'id': 'chinh-ta',
            'mode': 'practice',
            'title': 'Chính tả'},
           {'groups': [{'id': 'r1',
                        'instr': 'Sắp xếp hội thoại: chọn số thứ tự (câu đầu tiên là số 0: "Mary: What\'s your hobby, Nam?").',
                        'items': [{'id': 'r1.1',
                                   'left': ["Nam: It's running. What's your hobby?",
                                            "Mary: It's drawing.",
                                            'Nam: I like drawing, too.',
                                            'Mary: Thank you.'],
                                   'o': ['1', '2', '3', '4'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'r2',
                        'instr': 'Đọc và chọn True (Đúng) hoặc False (Sai).',
                        'items': [{'id': 'r2.1', 'q': "Mai's hobby is drawing.", 't': 'tf'},
                                  {'id': 'r2.2', 'q': 'Mai likes cooking.', 't': 'tf'},
                                  {'id': 'r2.3', 'q': 'Nam likes swimming.', 't': 'tf'}],
                        'passage': "<p>Hello. I'm Mai. My hobby is drawing. I like painting, too. My friend Nam likes swimming.</p>"},
                       {'id': 'r3',
                        'instr': 'Đọc và chọn True (Đúng) hoặc False (Sai).',
                        'items': [{'id': 'r3.1', 'q': "Tom's hobby is singing.", 't': 'tf'},
                                  {'id': 'r3.2', 'q': 'Tom likes running.', 't': 'tf'},
                                  {'id': 'r3.3', 'q': 'Mary likes dancing, too.', 't': 'tf'}],
                        'passage': "<p><b>Mary:</b> What's your hobby?<br><b>Tom:</b> It's singing. I like dancing, too.<br><b>Mary:</b> "
                                   'Me too!</p>'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'}],
 'theory': '<h3>Từ vựng</h3><table class="th"><tr><th>English</th><th>Tiếng Việt</th></tr><tr><td>singing '
           '🎤</td><td>hát</td></tr><tr><td>dancing 💃</td><td>nhảy, múa</td></tr><tr><td>drawing ✏️</td><td>vẽ</td></tr><tr><td>swimming '
           '🏊</td><td>bơi</td></tr><tr><td>cooking 🍳</td><td>nấu ăn</td></tr><tr><td>walking 🚶</td><td>đi bộ</td></tr><tr><td>painting '
           '🖌️</td><td>tô màu, sơn</td></tr><tr><td>running 🏃</td><td>chạy</td></tr><tr><td>hobby</td><td>sở '
           "thích</td></tr><tr><td>like</td><td>thích</td></tr></table><h3>Mẫu câu</h3><ul><li><b>What's your hobby?</b> – Sở thích của "
           "bạn là gì? &rarr; <b>It's singing.</b> – Là hát.</li><li><b>I like dancing.</b> – Mình thích nhảy.</li><li><b>She likes "
           'singing.</b> – Bạn ấy thích hát. (ngôi thứ ba thêm <i>s</i>: likes)</li><li><b>Our hobbies are swimming and cooking.</b> – Sở '
           'thích của chúng mình là bơi và nấu ăn.</li></ul>',
 'title': 'Unit 5 – My hobbies: Luyện tập',
 'unit': 5}
