# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u2-luyentap',
 'pages': [{'groups': [{'id': 'm1',
                        'instr': 'Nối từ tiếng Anh với nghĩa tiếng Việt.',
                        'items': [{'id': 'm1.1',
                                   'left': ['what', 'your', 'my', 'name', 'spell', 'how'],
                                   'o': ['tên', 'như thế nào', 'cái gì', 'đánh vần', 'của tôi', 'của bạn'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'a',
                        'instr': 'Task 1. Chọn từ khác loại.',
                        'items': [{'id': 'a.1', 'o': ['Hi', 'bye', 'hello'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.2', 'o': ['how', 'Peter', 'Linda'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.3', 'o': ['Bye', 'goodbye', 'name'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.4', 'o': ['what', 'how', 'hi'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.5', 'o': ['Tony', 'Peter', 'fine'], 'plain': True, 'q': '', 't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Task 2. Nhìn hình, sắp xếp chữ cái và viết từ đúng.',
                        'items': [{'id': 'b.1', 'img': 'image7.jpeg', 'q': 'trePe → {_}', 't': 'fill'},
                                  {'id': 'b.2', 'img': 'image8.jpeg', 'q': 'Lnadi → {_}', 't': 'fill'},
                                  {'id': 'b.3', 'img': 'image9.jpeg', 'q': 'begodyo → {_}', 't': 'fill'},
                                  {'id': 'b.4', 'img': 'image10.jpeg', 'q': 'neam → {_}', 't': 'fill'},
                                  {'id': 'b.5', 'img': 'image11.jpeg', 'q': 'plsel → {_}', 't': 'fill'}]}],
            'id': 'tu-vung',
            'mode': 'practice',
            'title': 'Từ vựng'},
           {'groups': [{'id': 'c',
                        'instr': 'Task 3. Nối câu (cột A) với câu đáp (cột B).',
                        'items': [{'id': 'c.1',
                                   'left': ["Hello. I'm Mary.",
                                            "What's your name?",
                                            'How do you spell your name?',
                                            'How are you?',
                                            "My name's Nam. Nice to meet you."],
                                   'o': ["I'm fine, thank you.",
                                         'N-A-M.',
                                         "My name's Tony.",
                                         "Hi, Mary. I'm Phuong.",
                                         "My name's Ha. Nice to meet you, too."],
                                   'q': '',
                                   't': 'match'}]},
                       {'bank': ['hi', "What's", 'Linda', 'name', 'nice', 'How'],
                        'id': 'd',
                        'instr': "Task 4. Hoàn thành đoạn hội thoại bằng các từ: names – how – nice – hi – What's – Linda.",
                        'items': [{'id': 'd.1', 'q': "Linda: Hi, I'm Linda. {_} your name?", 't': 'fill'},
                                  {'id': 'd.2', 'q': 'Mai: Hello, my {_} Mai.', 't': 'fill'},
                                  {'id': 'd.3', 'q': 'Mai: Nice to meet you, {_}.', 't': 'fill'},
                                  {'id': 'd.4', 'q': 'Linda: {_} to meet you, too.', 't': 'fill'},
                                  {'id': 'd.5', 'q': 'Mai: {_} do you spell your name?', 't': 'fill'}]},
                       {'id': 'e',
                        'instr': 'Task 5. Chọn từ đúng điền vào chỗ trống.',
                        'items': [{'id': 'e.1', 'q': '{_} your name?', 't': 'fill'},
                                  {'id': 'e.2', 'q': "{_} name's Tim.", 't': 'fill'},
                                  {'id': 'e.3', 'q': '{_} do you spell your name?', 't': 'fill'},
                                  {'id': 'e.4', 'q': 'My {_} is Mary.', 't': 'fill'},
                                  {'id': 'e.5', 'q': 'How {_} you?', 't': 'fill'},
                                  {'id': 'e.6', 'q': 'Nice {_} meet you.', 't': 'fill'}]},
                       {'id': 'f',
                        'instr': 'Task 6. Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'f.1', 'q': '', 't': 'order', 'words': ['is', 'your', 'name?', 'What']},
                                  {'id': 'f.2', 'q': '', 't': 'order', 'words': ['Mary.', 'My', 'is', 'name']},
                                  {'id': 'f.3', 'q': '', 't': 'order', 'words': ['am', 'Linda.', 'I']},
                                  {'id': 'f.4', 'q': '', 't': 'order', 'words': ['do', 'How', 'spell', 'name?', 'you', 'your']},
                                  {'id': 'f.5', 'q': '', 't': 'order', 'words': ['is', 'Her', 'Mai.', 'name']}]}],
            'id': 'mau-cau',
            'mode': 'practice',
            'title': 'Mẫu câu'},
           {'groups': [{'id': 'g',
                        'instr': 'Task 7. Nhìn hình và viết: What is his / her name? – He / She is …',
                        'items': [{'id': 'g.1', 'img': 'image26.png', 'q': 'What is his name? – He is {_}.', 't': 'fill'},
                                  {'id': 'g.2', 'img': 'image28.png', 'q': 'What is her name? – She is {_}.', 't': 'fill'},
                                  {'id': 'g.3', 'img': 'image30.png', 'q': 'What is her name? – She is {_}.', 't': 'fill'},
                                  {'id': 'g.4', 'img': 'image31.png', 'q': 'What is her name? – She is {_}.', 't': 'fill'}]},
                       {'id': 'h',
                        'instr': 'Task 8. Chọn đáp án đúng.',
                        'items': [{'id': 'h.1', 'o': ['am', 'is', 'are', 'it'], 'plain': True, 'q': 'How ___ you, Mai?', 't': 'mcq'},
                                  {'id': 'h.2',
                                   'o': ['How', 'See', 'Nice', 'are'],
                                   'plain': True,
                                   'q': 'Goodbye. ___ you later.',
                                   't': 'mcq'},
                                  {'id': 'h.3',
                                   'o': ['Hello', 'Good-bye', 'Bye', 'See you'],
                                   'plain': True,
                                   'q': '___, I am Linda.',
                                   't': 'mcq'},
                                  {'id': 'h.4', 'o': ['soon', 'late', 'do', 'am'], 'plain': True, 'q': 'Goodbye. See you ___.', 't': 'mcq'},
                                  {'id': 'h.5',
                                   'o': ['Hello', 'Goodbye', 'What', "What's"],
                                   'plain': True,
                                   'q': '___ her name?',
                                   't': 'mcq'}]}],
            'id': 'doc-viet',
            'mode': 'practice',
            'title': 'Đọc – Viết'}],
 'theory': '<h3>Từ vựng</h3><table class="th"><tr><th>English</th><th>Tiếng Việt</th></tr><tr><td>what</td><td>cái '
           "gì</td></tr><tr><td>what's (= what is)</td><td>là cái gì</td></tr><tr><td>your</td><td>của bạn</td></tr><tr><td>my</td><td>của "
           'tôi / của mình</td></tr><tr><td>name</td><td>tên</td></tr><tr><td>how</td><td>như thế nào</td></tr><tr><td>spell</td><td>đánh '
           "vần</td></tr></table><h3>Mẫu câu</h3><ul><li><b>What's your name?</b> – Tên bạn là gì? &rarr; <b>My name's Quynh.</b> / <b>I'm "
           "Quynh.</b></li><li><b>What's his / her name?</b> – Tên bạn ấy là gì? &rarr; <b>His / Her name's Mai.</b></li><li><b>How do you "
           'spell your name?</b> – Bạn đánh vần tên thế nào? &rarr; <b>L-I-N-D-A.</b></li></ul>',
 'title': "Unit 2 – What's your name?: Luyện tập",
 'unit': 2}
