# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u2-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'o': ['name', 'old', 'how'], 'plain': True, 'q': 'Chọn từ nghĩa "tên":', 't': 'mcq'},
                                  {'id': 't1.2', 'o': ['what', 'my', 'your'], 'plain': True, 'q': 'Chọn từ nghĩa "cái gì":', 't': 'mcq'},
                                  {'id': 't1.3', 'o': ['name', 'old', 'fine'], 'plain': True, 'q': 'My ___ is Linda.', 't': 'mcq'},
                                  {'id': 't1.4', 'o': ['old', 'name', 'fine'], 'plain': True, 'q': "I'm ten years ___.", 't': 'mcq'},
                                  {'id': 't1.5', 'o': ['my', 'your', 'seven'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.6', 'q': "What's your {_}?", 't': 'fill'},
                                  {'id': 't1.7', 'q': 'How old {_} you?', 't': 'fill'},
                                  {'id': 't1.8', 'q': "I'm nine {_} old.", 't': 'fill'},
                                  {'id': 't1.9', 'q': 'ruyo → {_}', 't': 'fill'},
                                  {'id': 't1.10', 'q': 'woh lod → {_}', 't': 'fill'},
                                  {'id': 't1.11', 'q': '', 't': 'order', 'words': ['Mary.', 'My', 'is', 'name']},
                                  {'id': 't1.12', 'q': '', 't': 'order', 'words': ['seven', 'years', 'old.', 'Bill', 'is']},
                                  {'id': 't1.13', 'q': '', 't': 'order', 'words': ['name', 'is', 'Nam.', 'Hello,', 'my']},
                                  {'id': 't1.14',
                                   'left': ['what', 'your', 'my', 'name'],
                                   'o': ['tên', 'của tôi', 'cái gì', 'của bạn'],
                                   'q': 'Nối từ với nghĩa:',
                                   't': 'match'},
                                  {'id': 't1.15', 'q': '', 't': 'order', 'words': ['your', 'name?', "What's"]},
                                  {'id': 't1.16',
                                   'o': ["Hello, Bill. My name's Nam.", "I'm fine.", 'Bye.'],
                                   'plain': True,
                                   'q': "— Hi. I'm Bill. What's your name? — ___",
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ["I'm fine, thanks.", "I'm ten.", "My name's Ben."],
                                   'plain': True,
                                   'q': '— How are you? — ___',
                                   't': 'mcq'},
                                  {'id': 't1.18', 'o': ['My', 'You', 'Fine'], 'plain': True, 'q': "Hello. ___ name's Mai.", 't': 'mcq'},
                                  {'id': 't1.19', 'q': 'Số 5 viết là: {_}', 't': 'fill'},
                                  {'id': 't1.20', 'q': 'theig → {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': "Unit 2 – What's your name?: Kiểm tra 2",
 'unit': 2}
