# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u1-luyentap',
 'pages': [{'groups': [{'id': 'm1',
                        'instr': 'Nối từ tiếng Anh với nghĩa tiếng Việt. (Chọn nghĩa ở ô bên phải.)',
                        'items': [{'id': 'm1.1',
                                   'left': ['hello', 'goodbye', 'thank you', 'fine', 'name', 'school'],
                                   'o': ['tạm biệt', 'cảm ơn', 'trường học', 'xin chào', 'khỏe', 'tên'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'a',
                        'instr': 'Task 1. Nhìn hình và chọn từ đúng.',
                        'items': [{'id': 'a.1',
                                   'img': 'image6.png',
                                   'o': ['How are you?', 'hello', "I'm Nam"],
                                   'plain': True,
                                   'q': '',
                                   't': 'mcq'},
                                  {'id': 'a.2', 'img': 'image7.png', 'o': ['goodbye', 'name', 'how'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.3', 'img': 'image8.png', 'o': ['I', 'thank you', 'you'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.4', 'img': 'image9.png', 'o': ['nice', 'are', 'hi'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.5',
                                   'img': 'image10.png',
                                   'o': ['fine', 'bye', 'thank you'],
                                   'plain': True,
                                   'q': '',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Task 2. Chọn từ khác loại.',
                        'items': [{'id': 'b.1', 'o': ['hi', 'hello', 'bye'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['how', 'Peter', 'Tony'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['pink', 'yellow', 'ten'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['bye', 'goodbye', 'hello'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.5', 'o': ['thanks', 'bye', 'thank you'], 'plain': True, 'q': '', 't': 'mcq'}]},
                       {'id': 'c',
                        'instr': 'Task 3. Nhìn hình, sắp xếp lại chữ cái và viết từ đúng.',
                        'items': [{'id': 'c.1', 'img': 'image12.png', 'q': 'hlole → {_}', 't': 'fill'},
                                  {'id': 'c.2', 'img': 'image13.png', 'q': 'ih → {_}', 't': 'fill'},
                                  {'id': 'c.3', 'img': 'image14.png', 'q': 'hankts → {_}', 't': 'fill'},
                                  {'id': 'c.4', 'img': 'image15.png', 'q': 'eyb → {_}', 't': 'fill'},
                                  {'id': 'c.5', 'img': 'image16.jpeg', 'q': 'ouy → {_}', 't': 'fill'}]}],
            'id': 'tu-vung',
            'mode': 'practice',
            'title': 'Từ vựng'},
           {'groups': [{'id': 'd',
                        'instr': 'Task 4. Nối câu hỏi / lời nói (cột A) với câu trả lời (cột B).',
                        'items': [{'id': 'd.1',
                                   'left': ['How are you?', "Hi! I'm Mai.", 'Goodbye!', 'Hello. I am Thuy.', 'Nice to meet you!'],
                                   'o': ['Hi!', 'Bye. See you later.', 'Hello!', 'Nice to meet you, too!', 'Fine, thanks.'],
                                   'q': '',
                                   't': 'match'}]},
                       {'bank': ['Hello', 'How', 'fine', 'you', 'thanks'],
                        'id': 'e',
                        'instr': 'Task 5. Hoàn thành đoạn hội thoại bằng các từ: Hello – How – fine – you – thanks.',
                        'items': [{'id': 'e.1', 'q': 'Quan: Hi, Tony.<br>Tony: {_}, Quan and Phong.', 't': 'fill'},
                                  {'id': 'e.2', 'q': 'Quan: {_} are you?', 't': 'fill'},
                                  {'id': 'e.3', 'q': "Tony: I'm {_}, thanks. And you?", 't': 'fill'},
                                  {'id': 'e.4', 'q': "Quan: I'm fine. Thank {_}.", 't': 'fill'},
                                  {'id': 'e.5', 'q': 'Tony: And how are you, Phong?<br>Phong: Fine, {_}.', 't': 'fill'}]},
                       {'id': 'f',
                        'instr': 'Task 6. Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'f.1', 'q': '', 't': 'order', 'words': ['Phong.', 'Hello,', "I'm", 'Quan.']},
                                  {'id': 'f.2', 'q': '', 't': 'order', 'words': ['thanks.', 'fine,', "I'm"]},
                                  {'id': 'f.3', 'q': '', 't': 'order', 'words': ['are', 'you?', 'How']},
                                  {'id': 'f.4', 'q': '', 't': 'order', 'words': ['too.', 'Nice', 'you,', 'to', 'meet']},
                                  {'id': 'f.5', 'q': '', 't': 'order', 'words': ['Hoa.', 'Miss', 'Goodbye,']}]}],
            'id': 'mau-cau',
            'mode': 'practice',
            'title': 'Mẫu câu'}],
 'theory': '<h3>Từ vựng</h3><table class="th"><tr><th>English</th><th>Tiếng Việt</th></tr><tr><td>hi / hello</td><td>xin '
           'chào</td></tr><tr><td>goodbye / bye</td><td>tạm biệt</td></tr><tr><td>fine</td><td>khỏe</td></tr><tr><td>thank you / '
           'thanks</td><td>cảm ơn</td></tr><tr><td>nice to meet you</td><td>rất vui được gặp '
           'bạn</td></tr><tr><td>name</td><td>tên</td></tr><tr><td>school</td><td>trường học</td></tr><tr><td>class</td><td>lớp '
           'học</td></tr></table><h3>Mẫu câu</h3><ul><li><b>Hello. / Hi.</b> – Xin chào. (<i>Hi</i> thân mật hơn, dùng với bạn '
           "bè.)</li><li><b>I'm + tên.</b> – Mình là … &nbsp; <i>I'm Mai.</i></li><li><b>How are you?</b> – Bạn có khỏe không? &rarr; "
           "<b>I'm fine, thank you. / Fine, thanks.</b> – Mình khỏe, cảm ơn.</li><li><b>Nice to meet you.</b> – Rất vui được gặp bạn. "
           '&rarr; <b>Nice to meet you, too.</b></li><li><b>Goodbye. / Bye.</b> – Tạm biệt. &rarr; <b>Bye. See you later.</b> – Hẹn gặp '
           'lại.</li></ul>',
 'title': 'Unit 1 – Hello: Luyện tập',
 'unit': 1}
