# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'a.1': 'bye',
 'a.2': 'how',
 'a.3': 'name',
 'a.4': 'hi',
 'a.5': 'fine',
 'b.1': ['Peter'],
 'b.2': ['Linda'],
 'b.3': ['goodbye'],
 'b.4': ['name'],
 'b.5': ['spell'],
 'c.1': {'blanks': [["Hi, Mary. I'm Phuong."],
                    ["My name's Tony."],
                    ['N-A-M.'],
                    ["I'm fine, thank you."],
                    ["My name's Ha. Nice to meet you, too."]]},
 'c1.1': ['u'],
 'c1.2': ['y'],
 'c1.3': ['w'],
 'c1.4': ['a'],
 'c1.5': ['o'],
 'c1.6': ['m'],
 'c2.1': ['my'],
 'c2.2': ['what'],
 'c2.3': ['your'],
 'c2.4': ['name'],
 'c2.5': ['our'],
 'c2.6': ['how old'],
 'd.1': ["What's"],
 'd.2': ["name's", 'name is'],
 'd.3': ['Linda'],
 'd.4': ['Nice'],
 'd.5': ['How'],
 'e.1': ["What's"],
 'e.2': ['My'],
 'e.3': ['How'],
 'e.4': ['name'],
 'e.5': ['are'],
 'e.6': ['to'],
 'e2.1': ['your'],
 'e2.2': ['old'],
 'e2.3': ['years'],
 'e2.4': ['name'],
 'e2.5': ['are'],
 'f.1': ['What is your name?'],
 'f.2': ['My name is Mary.'],
 'f.3': ['I am Linda.'],
 'f.4': ['How do you spell your name?'],
 'f.5': ['Her name is Mai.'],
 'f2.1': 'your',
 'f2.2': "name's",
 'f2.3': 'old',
 'f2.4': 'nine',
 'g.1': ['Tommy'],
 'g.2': ['Bella'],
 'g.3': ['Lola'],
 'g.4': ['Lily'],
 'g2.1': ["What's your name?"],
 'g2.2': ['My name is Mary.'],
 'g2.3': ['How old are you?'],
 'g2.4': ["I'm ten years old."],
 'g2.5': ['Bill is seven years old.'],
 'g2.6': ['Hello, my name is Nam.'],
 'g2.7': ['His name is Keith.'],
 'g2.8': ["She's eight years old."],
 'h.1': 'are',
 'h.2': 'See',
 'h.3': 'Hello',
 'h.4': 'soon',
 'h.5': "What's",
 'm1.1': {'blanks': [['cái gì'], ['của bạn'], ['của tôi'], ['tên'], ['đánh vần'], ['như thế nào']]},
 'n1.1': '3',
 'n1.2': '7',
 'n1.3': '10',
 'n1.4': '8',
 'n1.5': '5',
 'n2.1': "My name's Nam.",
 'n2.2': "I'm eight years old.",
 'n2.3': "I'm fine, thanks.",
 'n2.4': "Hi, Linda. I'm Tom.",
 'n3.1': ['two'],
 'n3.2': ['six'],
 'n3.3': ['nine'],
 'n3.4': ['four'],
 'n3.5': ['ten'],
 'n4.1': ["What's your name?"],
 'n4.2': ['How old are you?'],
 'n4.3': ["I'm eight years old.", 'I am eight years old.'],
 'r1.1': {'blanks': [['1'], ['2'], ['3'], ['4']]},
 'r2.1': 'T',
 'r2.2': 'F',
 'r2.3': 'T',
 'r3.1': 'T',
 'r3.2': 'F',
 'r3.3': 'T',
 'r3.4': 'F',
 's1.1': {'blanks': [['one'], ['two'], ['three'], ['four'], ['five']]},
 's2.1': {'blanks': [['six'], ['seven'], ['eight'], ['nine'], ['ten']]},
 's3.1': ['one'],
 's3.3': ['three'],
 's3.5': ['five'],
 's3.7': ['seven'],
 's3.9': ['nine'],
 's4.1': ['ten'],
 's4.2': ['seven'],
 's4.3': ['five'],
 's4.4': ['nine'],
 's4.5': ['four'],
 's4.6': ['eight'],
 's4.7': ['six']}

EXPLANATIONS = {'a.1': 'Hi, hello là chào; bye là tạm biệt.',
 'a.2': 'Peter, Linda là tên; how là từ để hỏi.',
 'a.3': 'Bye, goodbye là tạm biệt; name là tên.',
 'a.4': 'what, how là từ để hỏi; hi là lời chào.',
 'a.5': 'Tony, Peter là tên người; fine là khỏe.',
 'b.1': 'P-e-t-e-r = Peter.',
 'b.2': 'L-i-n-d-a = Linda.',
 'b.3': 'g-o-o-d-b-y-e = goodbye.',
 'b.4': 'n-a-m-e = name.',
 'b.5': 's-p-e-l-l = spell.',
 'c.1': 'Chào – chào lại; hỏi tên – nói tên; hỏi cách đánh vần – đánh vần; hỏi thăm – trả lời khỏe; làm quen – đáp lại.',
 'c1.1': 'our',
 'c1.2': 'my',
 'c1.3': 'how old',
 'c1.4': 'what',
 'c1.5': 'your',
 'c1.6': 'name',
 'c2.1': 'my',
 'c2.2': 'what',
 'c2.3': 'your',
 'c2.4': 'name',
 'c2.5': 'our',
 'c2.6': 'how old',
 'd.1': "What's your name? = Tên bạn là gì?",
 'd.2': "my name's / my name is = tên mình là.",
 'd.3': 'Gọi tên bạn đang nói chuyện: Linda.',
 'd.4': 'Nice to meet you, too.',
 'd.5': 'How do you spell your name?',
 'e.1': "What's your name?",
 'e.2': "My name's Tim.",
 'e.3': 'How do you spell your name?',
 'e.4': 'My name is Mary.',
 'e.5': 'How are you?',
 'e.6': 'Nice to meet you.',
 'e2.1': "What's your name?",
 'e2.2': 'How old are you?',
 'e2.3': 'five years old',
 'e2.4': "What's your name?",
 'e2.5': 'How old are you?',
 'f.1': 'What is your name? = Tên bạn là gì?',
 'f.2': 'My name is Mary.',
 'f.3': 'I am Linda. = Mình là Linda.',
 'f.4': 'How do you spell your name?',
 'f.5': 'Her name is Mai. = Tên bạn ấy là Mai.',
 'f2.1': "What's your name?",
 'f2.2': "My name's Nam.",
 'f2.3': 'How old are you?',
 'f2.4': "I'm nine years old.",
 'g.1': 'He is Tommy.',
 'g.2': 'She is Bella.',
 'g.3': 'She is Lola.',
 'g.4': 'She is Lily.',
 'g2.1': "What's your name?",
 'g2.2': 'My name is Mary.',
 'g2.3': 'How old are you?',
 'g2.4': "I'm ten years old.",
 'g2.5': 'Bill is seven years old.',
 'g2.6': 'Hello, my name is Nam.',
 'g2.7': 'His name is Keith. = Tên bạn ấy là Keith.',
 'g2.8': "She's eight years old. = Bạn ấy 8 tuổi.",
 'h.1': 'Chủ ngữ you → are: How are you?',
 'h.2': 'See you later. = Hẹn gặp lại.',
 'h.3': 'Giới thiệu bản thân → Hello.',
 'h.4': 'See you soon. = Hẹn sớm gặp lại.',
 'h.5': "What's her name? = Tên bạn ấy là gì?",
 'm1.1': 'what = cái gì, your = của bạn, my = của tôi, name = tên, spell = đánh vần, how = như thế nào.',
 'n1.1': 'three = 3',
 'n1.2': 'seven = 7',
 'n1.3': 'ten = 10',
 'n1.4': 'eight = 8',
 'n1.5': 'five = 5',
 'n2.1': "What's your name? → My name's…",
 'n2.2': "How old are you? → I'm … years old.",
 'n2.3': "How are you? → I'm fine.",
 'n2.4': 'Chào lại và giới thiệu.',
 'n3.1': 'two',
 'n3.2': 'six',
 'n3.3': 'nine',
 'n3.4': 'four',
 'n3.5': 'ten',
 'n4.1': "What's your name?",
 'n4.2': 'How old are you?',
 'n4.3': "I'm eight years old.",
 'r1.1': "Thứ tự: 0 Linh: Hello, I'm Linh. → 1 Mary: Hello, Linh. I'm Mary. → 2 Mary: How old are you? → 3 Linh: I'm eight... → 4 Mary: "
         "I'm eight, too.",
 'r2.1': "My name's Linda.",
 'r2.2': 'Bạn ấy 9 tuổi (nine).',
 'r2.3': 'Bài đọc mở đầu bằng Hello.',
 'r3.1': "Bill hỏi What's your name?",
 'r3.2': 'Nam 8 tuổi.',
 'r3.3': 'Bill hỏi tuổi Nam.',
 'r3.4': 'Bill là tên của Bill; Nam là Nam.',
 's1.1': '1 one, 2 two, 3 three, 4 four, 5 five.',
 's2.1': '6 six, 7 seven, 8 eight, 9 nine, 10 ten.',
 's3.1': '1 = one',
 's3.3': '3 = three',
 's3.5': '5 = five',
 's3.7': '7 = seven',
 's3.9': '9 = nine',
 's4.1': 'ten',
 's4.2': 'seven',
 's4.3': 'five',
 's4.4': 'nine',
 's4.5': 'four',
 's4.6': 'eight',
 's4.7': 'six'}

GHI_CHU_RA_SOAT = []
