# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'t1.1': "It's singing.",
 't1.10': "It's singing.",
 't1.11': ['hobby'],
 't1.12': ['like'],
 't1.13': ['and'],
 't1.14': ['hobbies'],
 't1.15': ['singing'],
 't1.16': ["What's your hobby?"],
 't1.17': ["It's singing."],
 't1.18': ['I like dancing.'],
 't1.19': ['I like swimming.'],
 't1.2': 'like',
 't1.20': {'blanks': [["It's singing."], ["It's drawing."], ['Me too.'], ["I'm fine, thanks."]]},
 't1.3': 'likes',
 't1.4': 'hobbies',
 't1.5': 'singing',
 't1.6': 'dancing',
 't1.7': 'hobby',
 't1.8': 'hát',
 't1.9': 'nhảy, múa'}

EXPLANATIONS = {'t1.1': "Hỏi sở thích → It's + hoạt động.",
 't1.10': "What's your hobby? → It's singing.",
 't1.11': 'hobby = sở thích',
 't1.12': 'I like … = Mình thích …',
 't1.13': 'and = và',
 't1.14': 'hobbies = các sở thích',
 't1.15': 'singing',
 't1.16': "What's your hobby?",
 't1.17': "It's singing.",
 't1.18': 'I like dancing.',
 't1.19': 'I like swimming.',
 't1.2': 'I like …',
 't1.20': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 't1.3': 'She + likes',
 't1.4': 'Số nhiều: hobbies.',
 't1.5': 'singing = hát (🎤)',
 't1.6': 'dancing = nhảy, múa (💃)',
 't1.7': 'singing, dancing là hoạt động cụ thể; hobby là "sở thích".',
 't1.8': 'singing = hát',
 't1.9': 'dancing = nhảy, múa'}

GHI_CHU_RA_SOAT = []
