# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u3-luyentap',
 'pages': [{'groups': [{'id': 'm1',
                        'instr': 'Nối từ tiếng Anh với nghĩa tiếng Việt.',
                        'items': [{'id': 'm1.1',
                                   'left': ['friend', 'teacher', 'Mr', 'Ms', 'this', 'that'],
                                   'o': ['giáo viên', 'bạn', 'cô', 'đây, cái này (ở gần)', 'ông, thầy', 'kia, cái kia (ở xa)'],
                                   'q': '',
                                   't': 'match'},
                                  {'id': 'm1.2', 'left': ['yes', 'no', 'it'], 'o': ['nó', 'vâng, đúng', 'không'], 'q': '', 't': 'match'}]},
                       {'id': 'a',
                        'instr': 'Nhìn hình và chọn từ đúng.',
                        'items': [{'id': 'a.1',
                                   'o': ['Ms', 'that', 'friend'],
                                   'plain': True,
                                   'q': '<span class="emo">👫</span>',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['this', 'no', 'teacher'],
                                   'plain': True,
                                   'q': '<span class="emo">👩\u200d🏫</span>',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['friend', 'teacher', 'Mr'],
                                   'plain': True,
                                   'q': '<span class="emo">👨</span>',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['that', 'Ms', 'friend'],
                                   'plain': True,
                                   'q': '<span class="emo">👩</span>',
                                   't': 'mcq'},
                                  {'id': 'a.5', 'o': ['Ms', 'that', 'this'], 'plain': True, 'q': '<span class="emo">👇</span>', 't': 'mcq'},
                                  {'id': 'a.6', 'o': ['this', 'no', 'that'], 'plain': True, 'q': '<span class="emo">👉</span>', 't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['friend', 'teacher', 'yes'],
                                   'plain': True,
                                   'q': '<span class="emo">✅</span>',
                                   't': 'mcq'},
                                  {'id': 'a.8', 'o': ['that', 'Ms', 'no'], 'plain': True, 'q': '<span class="emo">❌</span>', 't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Chọn từ khác loại.',
                        'items': [{'id': 'b.1', 'o': ['Mr', 'Ms', 'yes'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['friend', 'teacher', 'this'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['yes', 'no', 'Mr'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['this', 'that', 'no'], 'plain': True, 'q': '', 't': 'mcq'}]}],
            'id': 'tu-vung',
            'mode': 'practice',
            'title': 'Từ vựng'},
           {'groups': [{'id': 'd',
                        'instr': 'Nối câu hỏi / lời nói (cột A) với câu trả lời (cột B).',
                        'items': [{'id': 'd.1',
                                   'left': ['Is this Bill?', 'Is that Nam?', 'This is Mary.', "That's Mr Long.", 'How are you?'],
                                   'o': ['Yes, it is.', 'Hello, Mr Long.', "No, it isn't. It's Minh.", "I'm fine, thank you.", 'Hi, Mary.'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'e',
                        'instr': 'Điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'e.1', 'q': "How are you, Minh? – I'm fine, {_}.", 't': 'fill'},
                                  {'id': 'e.2', 'q': "{_} this Lan? – No, it isn't. It's Lucy.", 't': 'fill'},
                                  {'id': 'e.3', 'q': 'Is {_} Mai? – Yes, it is.', 't': 'fill'},
                                  {'id': 'e.4', 'q': "That's {_} Long. – Hello, Mr Long.", 't': 'fill'},
                                  {'id': 'e.5', 'q': 'This is my {_} Nam. – Hi, Nam.', 't': 'fill'},
                                  {'id': 'e.6', 'q': "That's my teacher, {_} Hoa.", 't': 'fill'},
                                  {'id': 'e.7', 'q': 'Is that Mr Long? – {_}, it is.', 't': 'fill'},
                                  {'id': 'e.8', 'q': "Is this Lan? – {_}, it isn't. It's Mary.", 't': 'fill'}]},
                       {'id': 'f',
                        'instr': 'Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'f.1', 'q': '', 't': 'order', 'words': ['This', 'my', 'friend', 'Linh.', 'is']},
                                  {'id': 'f.2', 'q': '', 't': 'order', 'words': ['Ms', 'Hoa.', "That's", 'teacher,', 'my']},
                                  {'id': 'f.3', 'q': '', 't': 'order', 'words': ['Bill?', 'this', 'Is']},
                                  {'id': 'f.4', 'q': '', 't': 'order', 'words': ['it', 'Yes,', 'is.']},
                                  {'id': 'f.5', 'q': '', 't': 'order', 'words': ["isn't.", 'No,', 'it']},
                                  {'id': 'f.6', 'q': '', 't': 'order', 'words': ['Mai?', 'that', 'Is']}]}],
            'id': 'mau-cau',
            'mode': 'practice',
            'title': 'Mẫu câu'},
           {'groups': [{'id': 'e2',
                        'instr': 'Chọn đáp án đúng.',
                        'items': [{'id': 'e2.1',
                                   'o': ['Yes, it is.', 'Yes, I am.', 'Fine, thanks.'],
                                   'plain': True,
                                   'q': 'Is this Bill? – ___',
                                   't': 'mcq'},
                                  {'id': 'e2.2', 'o': ['is', 'are', 'am'], 'plain': True, 'q': 'This ___ my friend.', 't': 'mcq'},
                                  {'id': 'e2.3',
                                   'o': ["isn't", 'is', 'am'],
                                   'plain': True,
                                   'q': "Is that Nam? – No, it ___. It's Minh.",
                                   't': 'mcq'},
                                  {'id': 'e2.4', 'o': ['This', 'That', 'It'], 'plain': True, 'q': '___ is Mary. (người ở gần)', 't': 'mcq'},
                                  {'id': 'e2.5',
                                   'o': ["That's", "This's", 'Are'],
                                   'plain': True,
                                   'q': '___ Mr Long. (người ở xa)',
                                   't': 'mcq'},
                                  {'id': 'e2.6',
                                   'o': ['Hi, Nam.', 'Goodbye.', 'Yes, it is.'],
                                   'plain': True,
                                   'q': 'Hi, Mary. This is my friend Nam. – ___',
                                   't': 'mcq'},
                                  {'id': 'e2.7',
                                   'o': ['Hello, Ms Hoa.', "It's Nam.", "I'm fine."],
                                   'plain': True,
                                   'q': "That's Ms Hoa. – ___",
                                   't': 'mcq'},
                                  {'id': 'e2.8',
                                   'o': ['Yes, it is.', "I'm Long.", 'Goodbye.'],
                                   'plain': True,
                                   'q': 'Is that Mr Long? – ___',
                                   't': 'mcq'},
                                  {'id': 'e2.9',
                                   'o': ['teacher', 'friend', 'Mr'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "giáo viên":',
                                   't': 'mcq'},
                                  {'id': 'e2.10',
                                   'o': ["It's", 'Is', 'This'],
                                   'plain': True,
                                   'q': "Is this Lan? – No, it isn't. ___ Lucy.",
                                   't': 'mcq'},
                                  {'id': 'e2.11',
                                   'o': ['friend', 'teacher', 'that'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "bạn":',
                                   't': 'mcq'},
                                  {'id': 'e2.12',
                                   'o': ['Thank', 'This', 'That'],
                                   'plain': True,
                                   'q': '___ you, Ben. – (cảm ơn)',
                                   't': 'mcq'}]},
                       {'id': 'f2',
                        'instr': 'Điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'f2.1', 'q': "That's Lucy. – {_}, Lucy.", 't': 'fill'},
                                  {'id': 'f2.2', 'q': 'Hi, Lucy. – This {_} Nam.', 't': 'fill'},
                                  {'id': 'f2.3', 'q': "That's my teacher, Mr Long. – {_}, Mr Long.", 't': 'fill'},
                                  {'id': 'f2.4', 'q': '{_} is Mary. (người ở gần)', 't': 'fill'},
                                  {'id': 'f2.5', 'q': "{_}'s Mr Long. (người ở xa)", 't': 'fill'},
                                  {'id': 'f2.6', 'q': 'Is this Bill? – Yes, it {_}.', 't': 'fill'}]},
                       {'id': 'g2',
                        'instr': 'Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'g2.1', 'q': '', 't': 'order', 'words': ['Thank', 'Ben.', 'you,']},
                                  {'id': 'g2.2', 'q': '', 't': 'order', 'words': ["That's", 'Long.', 'Mr']},
                                  {'id': 'g2.3', 'q': '', 't': 'order', 'words': ['Mr', 'Long.', 'Hello,']},
                                  {'id': 'g2.4', 'q': '', 't': 'order', 'words': ['is', 'Mary.', 'This']}]}],
            'id': 'mau-cau-2',
            'mode': 'practice',
            'title': 'Mẫu câu 2'},
           {'groups': [{'id': 'n1',
                        'instr': 'Nghe 1. Bấm 🔊 (nghe lại được nhiều lần) và chọn từ em nghe được.',
                        'items': [{'id': 'n1.1',
                                   'o': ['friend', 'that', 'yes'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'friend',
                                   't': 'mcq'},
                                  {'id': 'n1.2',
                                   'o': ['that', 'yes', 'teacher'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'teacher',
                                   't': 'mcq'},
                                  {'id': 'n1.3',
                                   'o': ['teacher', 'this', 'yes'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'this',
                                   't': 'mcq'},
                                  {'id': 'n1.4',
                                   'o': ['friend', 'this', 'that'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'that',
                                   't': 'mcq'},
                                  {'id': 'n1.5',
                                   'o': ['friend', 'that', 'yes'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'yes',
                                   't': 'mcq'}]},
                       {'id': 'n2',
                        'instr': 'Nghe 2. Nghe câu và chọn câu trả lời phù hợp.',
                        'items': [{'id': 'n2.1',
                                   'o': ['Hi, Mary.', "No, it isn't. It's Minh.", 'Yes, it is.'],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'Is this Bill?',
                                   't': 'mcq'},
                                  {'id': 'n2.2',
                                   'o': ['Yes, it is.', 'Hello, Mr Long.', "No, it isn't. It's Minh."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'Is that Nam?',
                                   't': 'mcq'},
                                  {'id': 'n2.3',
                                   'o': ['Hello, Mr Long.', 'Yes, it is.', 'Hi, Mary.'],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'This is Mary.',
                                   't': 'mcq'},
                                  {'id': 'n2.4',
                                   'o': ['Hi, Mary.', "No, it isn't. It's Minh.", 'Hello, Mr Long.'],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': "That's Mr Long.",
                                   't': 'mcq'},
                                  {'id': 'n2.5',
                                   'o': ['Hi, Mary.', "No, it isn't. It's Minh.", "I'm fine, thank you."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'How are you?',
                                   't': 'mcq'}]},
                       {'id': 'n3',
                        'instr': 'Nghe 3. Nghe và viết lại từ.',
                        'items': [{'id': 'n3.1', 'q': '{_}', 'say': 'friend', 't': 'fill'},
                                  {'id': 'n3.2', 'q': '{_}', 'say': 'teacher', 't': 'fill'},
                                  {'id': 'n3.3', 'q': '{_}', 'say': 'this', 't': 'fill'},
                                  {'id': 'n3.4', 'q': '{_}', 'say': 'that', 't': 'fill'},
                                  {'id': 'n3.5', 'q': '{_}', 'say': 'yes', 't': 'fill'}]},
                       {'id': 'n4',
                        'instr': 'Nghe 4. Nghe và viết lại cả câu.',
                        'items': [{'id': 'n4.1', 'q': '{_}', 'say': 'This is my friend Linh.', 't': 'fill'},
                                  {'id': 'n4.2', 'q': '{_}', 'say': "That's my teacher, Ms Hoa.", 't': 'fill'},
                                  {'id': 'n4.3', 'q': '{_}', 'say': 'Is this Bill?', 't': 'fill'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Nghe'},
           {'groups': [{'id': 'c1',
                        'instr': 'Điền chữ cái còn thiếu.',
                        'items': [{'id': 'c1.1', 'q': 'fri{_}nd', 't': 'fill'},
                                  {'id': 'c1.2', 'q': 'tea{_}her', 't': 'fill'},
                                  {'id': 'c1.3', 'q': 'th{_}s', 't': 'fill'},
                                  {'id': 'c1.4', 'q': 'th{_}t', 't': 'fill'},
                                  {'id': 'c1.5', 'q': 'y{_}s', 't': 'fill'}]},
                       {'id': 'c2',
                        'instr': 'Sắp xếp lại chữ cái thành từ đúng.',
                        'items': [{'id': 'c2.1', 'q': 'enirfd → {_}', 't': 'fill'},
                                  {'id': 'c2.2', 'q': 'etecarh → {_}', 't': 'fill'},
                                  {'id': 'c2.3', 'q': 'isth → {_}', 't': 'fill'},
                                  {'id': 'c2.4', 'q': 'ahtt → {_}', 't': 'fill'},
                                  {'id': 'c2.5', 'q': 'sey → {_}', 't': 'fill'}]}],
            'id': 'chinh-ta',
            'mode': 'practice',
            'title': 'Chính tả'},
           {'groups': [{'id': 'r1',
                        'instr': 'Sắp xếp hội thoại: chọn số thứ tự (câu đầu tiên là số 0: "Nam: Hello, I\'m Nam.").',
                        'items': [{'id': 'r1.1',
                                   'left': ["Quan: Hi, Nam. I'm Quan.",
                                            'Nam: Is that Ms Hoa, Quan?',
                                            "Quan: Yes, it's Ms Hoa, my English teacher.",
                                            'Nam: Ms Hoa is my English teacher, too.'],
                                   'o': ['1', '2', '3', '4'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'r2',
                        'instr': 'Đọc và chọn True (Đúng) hoặc False (Sai).',
                        'items': [{'id': 'r2.1', 'q': "Linh is Nam's friend.", 't': 'tf'},
                                  {'id': 'r2.2', 'q': "Ms Hoa is Nam's friend.", 't': 'tf'},
                                  {'id': 'r2.3', 'q': 'Nam is a teacher.', 't': 'tf'}],
                        'passage': "<p>Hello. I'm Nam. This is my friend, Linh. That is my teacher, Ms Hoa.</p>"},
                       {'id': 'r3',
                        'instr': 'Đọc và chọn True (Đúng) hoặc False (Sai).',
                        'items': [{'id': 'r3.1', 'q': 'This is Tom.', 't': 'tf'},
                                  {'id': 'r3.2', 'q': 'This is Bill.', 't': 'tf'},
                                  {'id': 'r3.3', 'q': 'That is Mr Long.', 't': 'tf'},
                                  {'id': 'r3.4', 'q': 'Nam says "No" to the second question.', 't': 'tf'}],
                        'passage': "<p><b>Mary:</b> Is this Bill?<br><b>Nam:</b> No, it isn't. It's Tom.<br><b>Mary:</b> Is that Mr "
                                   'Long?<br><b>Nam:</b> Yes, it is.</p>'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'}],
 'theory': '<h3>Từ vựng</h3><table class="th"><tr><th>English</th><th>Tiếng Việt</th></tr><tr><td>friend '
           '👫</td><td>bạn</td></tr><tr><td>teacher 👩\u200d🏫</td><td>giáo viên</td></tr><tr><td>Mr 👨</td><td>ông, thầy</td></tr><tr><td>Ms '
           '👩</td><td>cô</td></tr><tr><td>this 👇</td><td>đây, cái này (ở gần)</td></tr><tr><td>that 👉</td><td>kia, cái kia (ở '
           'xa)</td></tr><tr><td>yes ✅</td><td>vâng, đúng</td></tr><tr><td>no '
           '❌</td><td>không</td></tr><tr><td>it</td><td>nó</td></tr></table><h3>Mẫu câu</h3><ul><li><b>This is Mary.</b> – Đây là Mary. '
           "&rarr; <b>Hi, Mary.</b></li><li><b>That's Mr Long.</b> – Kia là thầy Long. &rarr; <b>Hello, Mr Long.</b></li><li><b>Is this "
           "Bill?</b> – Đây có phải Bill không? &rarr; <b>Yes, it is.</b> / <b>No, it isn't.</b></li><li><b>Is that Nam?</b> &rarr; <b>No, "
           "it isn't. It's Minh.</b></li><li>It's = It is &nbsp; | &nbsp; It isn't = It is not</li></ul>",
 'title': 'Unit 3 – Our friends: Luyện tập',
 'unit': 3}
