# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'t1.1': 'mouth',
 't1.10': "I'm fine, thanks.",
 't1.11': ['eye'],
 't1.12': ['hand'],
 't1.13': ['face'],
 't1.14': ['Touch'],
 't1.15': ['eye'],
 't1.16': ["What's that?"],
 't1.17': ['Touch your nose.'],
 't1.18': ["It's a nose."],
 't1.19': ["It's an eye."],
 't1.2': 'mouth',
 't1.20': {'blanks': [["I'm fine, thanks."], ["My name's Mai."], ['Yes, it is.'], ["It's a nose."]]},
 't1.3': 'nose',
 't1.4': 'hair',
 't1.5': 'hand',
 't1.6': 'mouth',
 't1.7': 'open',
 't1.8': 'bàn tay',
 't1.9': 'miệng'}

EXPLANATIONS = {'t1.1': 'mouth = miệng.',
 't1.10': "How are you? → I'm fine, thanks.",
 't1.11': 'eye = mắt',
 't1.12': 'hand = bàn tay',
 't1.13': 'face = khuôn mặt',
 't1.14': 'Touch your hair!',
 't1.15': 'eye',
 't1.16': "What's that?",
 't1.17': 'Touch your nose.',
 't1.18': "It's a nose.",
 't1.19': "It's an eye.",
 't1.2': 'Ta há miệng (mouth).',
 't1.20': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 't1.3': 'nose = mũi.',
 't1.4': 'hair = tóc.',
 't1.5': 'hand = bàn tay (✋)',
 't1.6': 'mouth = miệng (👄)',
 't1.7': 'face, hand là bộ phận cơ thể.',
 't1.8': 'hand = bàn tay',
 't1.9': 'mouth = miệng'}

GHI_CHU_RA_SOAT = []
