# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u1-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 21 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['hello', 'goodbye', 'fine'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'goodbye',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ["I'm fine, thanks.", 'Bye.', "I'm Tony."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe câu hỏi rồi chọn câu trả lời.',
                                   'say': 'How are you?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["Hello, Mai. I'm Nam.", 'Fine, thanks.', 'Goodbye.'],
                                   'plain': True,
                                   'q': "— Hi, I'm Mai. — ___",
                                   't': 'mcq'},
                                  {'id': 't1.4', 'o': ['bye', 'goodbye', 'hi'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.5', 'o': ['you', 'fine', 'bye'], 'plain': True, 'q': 'Nice to meet ___.', 't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Good{_}! (chào buổi sáng)', 't': 'fill'},
                                  {'id': 't1.7', 'q': "I'm fine, thank {_}.", 't': 'fill'},
                                  {'id': 't1.8', 'q': 'See you {_}.', 't': 'fill'},
                                  {'id': 't1.9', 'q': '{_} are you?', 't': 'fill'},
                                  {'id': 't1.10', 'q': 'kthna uoy → {_}', 't': 'fill'},
                                  {'id': 't1.11', 'q': '', 't': 'order', 'words': ['Lan?', 'How', 'you,', 'are']},
                                  {'id': 't1.12', 'q': '', 't': 'order', 'words': ['Quan.', 'Hello,']},
                                  {'id': 't1.13', 'q': '', 't': 'order', 'words': ['Phong.', "I'm"]},
                                  {'id': 't1.14',
                                   'left': ['Hello!', 'Goodbye!', 'How are you?', 'Nice to meet you!'],
                                   'o': ['Fine, thanks.', 'Nice to meet you, too!', 'Hi!', 'Bye.'],
                                   'q': 'Nối:',
                                   't': 'match'},
                                  {'id': 't1.15', 'q': '', 't': 'order', 'words': ['Miss', 'Hoa.', 'Goodbye,']},
                                  {'id': 't1.16',
                                   'o': ['hi', 'thanks', 'fine'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "chào" (thân mật):',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['night', 'fine', 'how'],
                                   'plain': True,
                                   'q': '— Good___! (chúc ngủ ngon)',
                                   't': 'mcq'},
                                  {'id': 't1.18', 'o': ['fine', 'bye', 'hello'], 'plain': True, 'q': "I'm ___, thank you.", 't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['Nice', 'Fine', 'Bye'],
                                   'plain': True,
                                   'q': "Hello, I'm Nam. ___ to meet you.",
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'lehol → {_}', 't': 'fill'},
                                  {'id': 't1.21', 'q': 'G{_}odbye', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 1 – Hello: Kiểm tra 3',
 'unit': 1}
