# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u1-luyentap',
 'pages': [{'groups': [{'id': 'm1',
                        'instr': 'Nối từ tiếng Anh với nghĩa tiếng Việt. (Chọn nghĩa ở ô bên phải.)',
                        'items': [{'id': 'm1.1',
                                   'left': ['hello', 'goodbye', 'thank you', 'fine', 'name', 'school'],
                                   'o': ['tạm biệt', 'cảm ơn', 'trường học', 'xin chào', 'khỏe', 'tên'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'a',
                        'instr': 'Task 1. Nhìn hình và chọn từ đúng.',
                        'items': [{'id': 'a.1',
                                   'img': 'image6.png',
                                   'o': ['How are you?', 'hello', "I'm Nam"],
                                   'plain': True,
                                   'q': '',
                                   't': 'mcq'},
                                  {'id': 'a.2', 'img': 'image7.png', 'o': ['goodbye', 'name', 'how'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.3', 'img': 'image8.png', 'o': ['I', 'thank you', 'you'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.4', 'img': 'image9.png', 'o': ['nice', 'are', 'hi'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.5',
                                   'img': 'image10.png',
                                   'o': ['fine', 'bye', 'thank you'],
                                   'plain': True,
                                   'q': '',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Task 2. Chọn từ khác loại.',
                        'items': [{'id': 'b.1', 'o': ['hi', 'hello', 'bye'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['how', 'Peter', 'Tony'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['pink', 'yellow', 'ten'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['bye', 'goodbye', 'hello'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'b.5', 'o': ['thanks', 'bye', 'thank you'], 'plain': True, 'q': '', 't': 'mcq'}]},
                       {'id': 'c',
                        'instr': 'Task 3. Nhìn hình, sắp xếp lại chữ cái và viết từ đúng.',
                        'items': [{'id': 'c.1', 'img': 'image12.png', 'q': 'hlole → {_}', 't': 'fill'},
                                  {'id': 'c.2', 'img': 'image13.png', 'q': 'ih → {_}', 't': 'fill'},
                                  {'id': 'c.3', 'img': 'image14.png', 'q': 'hankts → {_}', 't': 'fill'},
                                  {'id': 'c.4', 'img': 'image15.png', 'q': 'eyb → {_}', 't': 'fill'},
                                  {'id': 'c.5', 'img': 'image16.jpeg', 'q': 'ouy → {_}', 't': 'fill'}]}],
            'id': 'tu-vung',
            'mode': 'practice',
            'title': 'Từ vựng'},
           {'groups': [{'id': 'd',
                        'instr': 'Task 4. Nối câu hỏi / lời nói (cột A) với câu trả lời (cột B).',
                        'items': [{'id': 'd.1',
                                   'left': ['How are you?', "Hi! I'm Mai.", 'Goodbye!', 'Hello. I am Thuy.', 'Nice to meet you!'],
                                   'o': ['Hi!', 'Bye. See you later.', 'Hello!', 'Nice to meet you, too!', 'Fine, thanks.'],
                                   'q': '',
                                   't': 'match'}]},
                       {'bank': ['Hello', 'How', 'fine', 'you', 'thanks'],
                        'id': 'e',
                        'instr': 'Task 5. Hoàn thành đoạn hội thoại bằng các từ: Hello – How – fine – you – thanks.',
                        'items': [{'id': 'e.1', 'q': 'Quan: Hi, Tony.<br>Tony: {_}, Quan and Phong.', 't': 'fill'},
                                  {'id': 'e.2', 'q': 'Quan: {_} are you?', 't': 'fill'},
                                  {'id': 'e.3', 'q': "Tony: I'm {_}, thanks. And you?", 't': 'fill'},
                                  {'id': 'e.4', 'q': "Quan: I'm fine. Thank {_}.", 't': 'fill'},
                                  {'id': 'e.5', 'q': 'Tony: And how are you, Phong?<br>Phong: Fine, {_}.', 't': 'fill'}]},
                       {'id': 'f',
                        'instr': 'Task 6. Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'f.1', 'q': '', 't': 'order', 'words': ['Phong.', 'Hello,', "I'm", 'Quan.']},
                                  {'id': 'f.2', 'q': '', 't': 'order', 'words': ['thanks.', 'fine,', "I'm"]},
                                  {'id': 'f.3', 'q': '', 't': 'order', 'words': ['are', 'you?', 'How']},
                                  {'id': 'f.4', 'q': '', 't': 'order', 'words': ['too.', 'Nice', 'you,', 'to', 'meet']},
                                  {'id': 'f.5', 'q': '', 't': 'order', 'words': ['Hoa.', 'Miss', 'Goodbye,']}]}],
            'id': 'mau-cau',
            'mode': 'practice',
            'title': 'Mẫu câu'},
           {'groups': [{'id': 'n1',
                        'instr': 'Nghe 1. Bấm 🔊 (có thể nghe lại nhiều lần) và chọn từ em nghe được.',
                        'items': [{'id': 'n1.1',
                                   'o': ['hello', 'hi', 'bye'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'hello',
                                   't': 'mcq'},
                                  {'id': 'n1.2',
                                   'o': ['goodbye', 'hello', 'hi'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'goodbye',
                                   't': 'mcq'},
                                  {'id': 'n1.3',
                                   'o': ['hello', 'fine', 'hi'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'fine',
                                   't': 'mcq'},
                                  {'id': 'n1.4',
                                   'o': ['hello', 'hi', 'thank you'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'thank you',
                                   't': 'mcq'},
                                  {'id': 'n1.5',
                                   'o': ['hello', 'hi', 'bye'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'hi',
                                   't': 'mcq'},
                                  {'id': 'n1.6',
                                   'o': ['hello', 'hi', 'bye'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn từ em nghe được.',
                                   'say': 'bye',
                                   't': 'mcq'}]},
                       {'id': 'n2',
                        'instr': 'Nghe 2. Nghe câu và chọn câu trả lời phù hợp.',
                        'items': [{'id': 'n2.1',
                                   'o': ["I'm fine, thank you.", 'Goodbye.', "I'm Nam."],
                                   'plain': True,
                                   'q': 'Em nghe: câu hỏi',
                                   'say': 'How are you?',
                                   't': 'mcq'},
                                  {'id': 'n2.2',
                                   'o': ['Bye, Mai.', 'Hello.', 'Fine, thanks.'],
                                   'plain': True,
                                   'q': 'Em nghe: lời tạm biệt',
                                   'say': 'Goodbye, Nam.',
                                   't': 'mcq'},
                                  {'id': 'n2.3',
                                   'o': ['Nice to meet you, too.', 'Goodbye.', 'How are you?'],
                                   'plain': True,
                                   'q': 'Em nghe: lời làm quen',
                                   'say': 'Nice to meet you.',
                                   't': 'mcq'},
                                  {'id': 'n2.4',
                                   'o': ["Hi, Tony. I'm Linda.", "I'm fine.", 'Bye.'],
                                   'plain': True,
                                   'q': 'Em nghe: lời chào',
                                   'say': "Hello, I'm Tony.",
                                   't': 'mcq'},
                                  {'id': 'n2.5',
                                   'o': ['Fine, thanks.', 'Hello.', 'Bye.'],
                                   'plain': True,
                                   'q': 'Em nghe: lời cảm ơn',
                                   'say': "I'm fine, thank you.",
                                   't': 'mcq'}]},
                       {'id': 'n3',
                        'instr': 'Nghe 3. Nghe và viết lại từ.',
                        'items': [{'id': 'n3.1', 'q': '{_}', 'say': 'hello', 't': 'fill'},
                                  {'id': 'n3.2', 'q': '{_}', 'say': 'goodbye', 't': 'fill'},
                                  {'id': 'n3.3', 'q': '{_}', 'say': 'thanks', 't': 'fill'},
                                  {'id': 'n3.4', 'q': '{_}', 'say': 'fine', 't': 'fill'},
                                  {'id': 'n3.5', 'q': '{_}', 'say': 'bye', 't': 'fill'}]},
                       {'id': 'n4',
                        'instr': 'Nghe 4. Nghe và viết lại cả câu.',
                        'items': [{'id': 'n4.1', 'q': '{_}', 'say': 'How are you?', 't': 'fill'},
                                  {'id': 'n4.2', 'q': '{_}', 'say': "I'm fine, thanks.", 't': 'fill'},
                                  {'id': 'n4.3', 'q': '{_}', 'say': 'Goodbye, Mai.', 't': 'fill'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Nghe'},
           {'groups': [{'id': 'c1',
                        'instr': 'Điền chữ cái còn thiếu.',
                        'items': [{'id': 'c1.1', 'q': 'th{_}nk you', 't': 'fill'},
                                  {'id': 'c1.2', 'q': 'ho{_}', 't': 'fill'},
                                  {'id': 'c1.3', 'q': 'y{_}u', 't': 'fill'},
                                  {'id': 'c1.4', 'q': 'h{_}', 't': 'fill'},
                                  {'id': 'c1.5', 'q': 'goo{_}bye', 't': 'fill'},
                                  {'id': 'c1.6', 'q': 'h{_}llo', 't': 'fill'},
                                  {'id': 'c1.7', 'q': 'f{_}ne', 't': 'fill'}]},
                       {'id': 'c2',
                        'instr': 'Sắp xếp lại chữ cái thành từ đúng.',
                        'items': [{'id': 'c2.1', 'q': 'oyu → {_}', 't': 'fill'},
                                  {'id': 'c2.2', 'q': 'lehol → {_}', 't': 'fill'},
                                  {'id': 'c2.3', 'q': 'doog bey → {_}', 't': 'fill'},
                                  {'id': 'c2.4', 'q': 'nefi → {_}', 't': 'fill'},
                                  {'id': 'c2.5', 'q': 'ohw → {_}', 't': 'fill'},
                                  {'id': 'c2.6', 'q': 'kthna uoy → {_}', 't': 'fill'}]}],
            'id': 'chinh-ta',
            'mode': 'practice',
            'title': 'Chính tả'},
           {'groups': [{'id': 'e2',
                        'instr': 'Điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'e2.1', 'q': "Hi, I'm Ben.<br>Hello, Ben. {_} Mai.", 't': 'fill'},
                                  {'id': 'e2.2', 'q': "How are you? – I'm fine, {_}.", 't': 'fill'},
                                  {'id': 'e2.3', 'q': '{_}, Miss Nga.<br>Goodbye, Nam.', 't': 'fill'},
                                  {'id': 'e2.4', 'q': "{_}, I'm Lucy.<br>Hi, Lucy. I'm Minh.", 't': 'fill'},
                                  {'id': 'e2.5', 'q': "How are {_}, Ben? – I'm fine, thank you.", 't': 'fill'},
                                  {'id': 'e2.6', 'q': "{_}, Nam. I'm Lan.", 't': 'fill'},
                                  {'id': 'e2.7', 'q': "I'm fine, {_} you.", 't': 'fill'},
                                  {'id': 'e2.8', 'q': 'Hi, Mai. {_} are you? – Fine, thanks.', 't': 'fill'}]},
                       {'id': 'f2',
                        'instr': 'Chọn từ đúng để hoàn thành đoạn hội thoại.',
                        'items': [{'id': 'f2.1',
                                   'o': ['you', 'I', 'fine'],
                                   'plain': True,
                                   'q': 'Nga: Hello, Hoa. How are ___?',
                                   't': 'mcq'},
                                  {'id': 'f2.2',
                                   'o': ['fine', 'hello', 'bye'],
                                   'plain': True,
                                   'q': "Hoa: Hi, Nga. I'm ___, thanks. And you?",
                                   't': 'mcq'},
                                  {'id': 'f2.3',
                                   'o': ["I'm", 'How', 'Hi'],
                                   'plain': True,
                                   'q': 'Nga: ___ fine, thank you. Goodbye, Hoa.',
                                   't': 'mcq'},
                                  {'id': 'f2.4', 'o': ['Bye', 'How', 'Fine'], 'plain': True, 'q': 'Hoa: ___, Nga.', 't': 'mcq'}]},
                       {'id': 'g2',
                        'instr': 'Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'g2.1', 'q': '', 't': 'order', 'words': ['Mai.', "I'm", 'Minh.', 'Hi,']},
                                  {'id': 'g2.2', 'q': '', 't': 'order', 'words': ['Minh.', 'Goodbye,']},
                                  {'id': 'g2.3', 'q': '', 't': 'order', 'words': ['Lan?', 'How', 'you,', 'are']},
                                  {'id': 'g2.4', 'q': '', 't': 'order', 'words': ['thanks.', 'fine,', "I'm"]},
                                  {'id': 'g2.5', 'q': '', 't': 'order', 'words': ['you', 'Bye.', 'later.', 'See']},
                                  {'id': 'g2.6', 'q': '', 't': 'order', 'words': ['you', 'Bill.', 'See', 'next', 'Goodbye.', 'week,']}]}],
            'id': 'mau-cau-2',
            'mode': 'practice',
            'title': 'Mẫu câu 2'},
           {'groups': [{'id': 'r1',
                        'instr': 'Sắp xếp hội thoại: chọn số thứ tự (câu đầu tiên là số 0: "Nam: Hello, I\'m Nam.").',
                        'items': [{'id': 'r1.1',
                                   'left': ["Quan: Hi, Nam. I'm Quan.",
                                            'Nam: How are you, Quan?',
                                            "Quan: I'm fine, thanks. And you?",
                                            "Nam: I'm fine, too. Thank you."],
                                   'o': ['1', '2', '3', '4'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'r2',
                        'instr': 'Đọc và chọn True (Đúng) hoặc False (Sai).',
                        'items': [{'id': 'r2.1', 'q': 'Her name is Mai.', 't': 'tf'},
                                  {'id': 'r2.2', 'q': 'She says goodbye.', 't': 'tf'},
                                  {'id': 'r2.3', 'q': 'Mai is fine.', 't': 'tf'}],
                        'passage': "<p>Hello. I'm Mai. I'm fine, thank you.</p>"},
                       {'id': 'r3',
                        'instr': 'Đọc hội thoại và chọn True hoặc False.',
                        'items': [{'id': 'r3.1', 'q': 'Nam asks "How are you?"', 't': 'tf'},
                                  {'id': 'r3.2', 'q': 'Lan is not fine.', 't': 'tf'},
                                  {'id': 'r3.3', 'q': 'They say goodbye.', 't': 'tf'},
                                  {'id': 'r3.4', 'q': 'Lan says "Hello" at the end.', 't': 'tf'}],
                        'passage': "<p><b>Nam:</b> Hi, Lan. How are you?<br><b>Lan:</b> I'm fine, thanks. And you?<br><b>Nam:</b> I'm "
                                   'fine, too. Goodbye, Lan.<br><b>Lan:</b> Bye, Nam.</p>'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'}],
 'theory': '<h3>Từ vựng</h3><table class="th"><tr><th>English</th><th>Tiếng Việt</th></tr><tr><td>hi / hello</td><td>xin '
           'chào</td></tr><tr><td>goodbye / bye</td><td>tạm biệt</td></tr><tr><td>fine</td><td>khỏe</td></tr><tr><td>thank you / '
           'thanks</td><td>cảm ơn</td></tr><tr><td>nice to meet you</td><td>rất vui được gặp '
           'bạn</td></tr><tr><td>name</td><td>tên</td></tr><tr><td>school</td><td>trường học</td></tr><tr><td>class</td><td>lớp '
           'học</td></tr></table><h3>Mẫu câu</h3><ul><li><b>Hello. / Hi.</b> – Xin chào. (<i>Hi</i> thân mật hơn, dùng với bạn '
           "bè.)</li><li><b>I'm + tên.</b> – Mình là … &nbsp; <i>I'm Mai.</i></li><li><b>How are you?</b> – Bạn có khỏe không? &rarr; "
           "<b>I'm fine, thank you. / Fine, thanks.</b> – Mình khỏe, cảm ơn.</li><li><b>Nice to meet you.</b> – Rất vui được gặp bạn. "
           '&rarr; <b>Nice to meet you, too.</b></li><li><b>Goodbye. / Bye.</b> – Tạm biệt. &rarr; <b>Bye. See you later.</b> – Hẹn gặp '
           'lại.</li></ul>',
 'title': 'Unit 1 – Hello: Luyện tập',
 'unit': 1}
