# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u4-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'o': ['mouth', 'nose', 'face'], 'plain': True, 'q': 'Chọn từ nghĩa "miệng":', 't': 'mcq'},
                                  {'id': 't1.2', 'o': ['mouth', 'hair', 'hand'], 'plain': True, 'q': 'Open your ___. (há ra)', 't': 'mcq'},
                                  {'id': 't1.3', 'o': ['nose', 'mouth', 'face'], 'plain': True, 'q': 'Chọn từ nghĩa "mũi":', 't': 'mcq'},
                                  {'id': 't1.4', 'o': ['hair', 'hand', 'ear'], 'plain': True, 'q': 'Chọn từ nghĩa "tóc":', 't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['face', 'mouth', 'hand'],
                                   'plain': True,
                                   'q': '<span class="emo">✋</span>',
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'o': ['ear', 'nose', 'mouth'],
                                   'plain': True,
                                   'q': '<span class="emo">👄</span>',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['face', 'hand', 'open'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.8', 'o': ['tóc', 'tai', 'bàn tay'], 'plain': True, 'q': 'Nghĩa của "hand" là:', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['khuôn mặt', 'sờ, chạm', 'miệng'],
                                   'plain': True,
                                   'q': 'Nghĩa của "mouth" là:',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ["My name's Mai.", 'Yes, it is.', "I'm fine, thanks."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'How are you?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': "👁️ It's an {_}.", 't': 'fill'},
                                  {'id': 't1.12', 'q': "✋ It's a {_}.", 't': 'fill'},
                                  {'id': 't1.13', 'q': "🙂 It's a {_}.", 't': 'fill'},
                                  {'id': 't1.14', 'q': '{_} your hair!', 't': 'fill'},
                                  {'id': 't1.15', 'q': 'eey → {_}', 't': 'fill'},
                                  {'id': 't1.16', 'q': '', 't': 'order', 'words': ['that?', "What's"]},
                                  {'id': 't1.17', 'q': '', 't': 'order', 'words': ['nose.', 'your', 'Touch']},
                                  {'id': 't1.18', 'q': '', 't': 'order', 'words': ['nose.', 'a', "It's"]},
                                  {'id': 't1.19', 'q': '', 't': 'order', 'words': ['an', 'eye.', "It's"]},
                                  {'id': 't1.20',
                                   'left': ['How are you?', "What's your name?", 'Is this Bill?', "What's this?"],
                                   'o': ["It's a nose.", "I'm fine, thanks.", 'Yes, it is.', "My name's Mai."],
                                   'q': 'Nối:',
                                   't': 'match'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 4 – Our bodies: Kiểm tra 3',
 'unit': 4}
