# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u2-luyentap',
 'pages': [{'groups': [{'id': 'm1',
                        'instr': 'Nối từ tiếng Anh với nghĩa tiếng Việt.',
                        'items': [{'id': 'm1.1',
                                   'left': ['what', 'your', 'my', 'name', 'spell', 'how'],
                                   'o': ['tên', 'như thế nào', 'cái gì', 'đánh vần', 'của tôi', 'của bạn'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'a',
                        'instr': 'Task 1. Chọn từ khác loại.',
                        'items': [{'id': 'a.1', 'o': ['Hi', 'bye', 'hello'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.2', 'o': ['how', 'Peter', 'Linda'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.3', 'o': ['Bye', 'goodbye', 'name'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.4', 'o': ['what', 'how', 'hi'], 'plain': True, 'q': '', 't': 'mcq'},
                                  {'id': 'a.5', 'o': ['Tony', 'Peter', 'fine'], 'plain': True, 'q': '', 't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Task 2. Nhìn hình, sắp xếp chữ cái và viết từ đúng.',
                        'items': [{'id': 'b.1', 'img': 'image7.jpeg', 'q': 'trePe → {_}', 't': 'fill'},
                                  {'id': 'b.2', 'img': 'image8.jpeg', 'q': 'Lnadi → {_}', 't': 'fill'},
                                  {'id': 'b.3', 'img': 'image9.jpeg', 'q': 'begodyo → {_}', 't': 'fill'},
                                  {'id': 'b.4', 'img': 'image10.jpeg', 'q': 'neam → {_}', 't': 'fill'},
                                  {'id': 'b.5', 'img': 'image11.jpeg', 'q': 'plsel → {_}', 't': 'fill'}]}],
            'id': 'tu-vung',
            'mode': 'practice',
            'title': 'Từ vựng'},
           {'groups': [{'id': 'c',
                        'instr': 'Task 3. Nối câu (cột A) với câu đáp (cột B).',
                        'items': [{'id': 'c.1',
                                   'left': ["Hello. I'm Mary.",
                                            "What's your name?",
                                            'How do you spell your name?',
                                            'How are you?',
                                            "My name's Nam. Nice to meet you."],
                                   'o': ["I'm fine, thank you.",
                                         'N-A-M.',
                                         "My name's Tony.",
                                         "Hi, Mary. I'm Phuong.",
                                         "My name's Ha. Nice to meet you, too."],
                                   'q': '',
                                   't': 'match'}]},
                       {'bank': ['hi', "What's", 'Linda', 'name', 'nice', 'How'],
                        'id': 'd',
                        'instr': "Task 4. Hoàn thành đoạn hội thoại bằng các từ: names – how – nice – hi – What's – Linda.",
                        'items': [{'id': 'd.1', 'q': "Linda: Hi, I'm Linda. {_} your name?", 't': 'fill'},
                                  {'id': 'd.2', 'q': 'Mai: Hello, my {_} Mai.', 't': 'fill'},
                                  {'id': 'd.3', 'q': 'Mai: Nice to meet you, {_}.', 't': 'fill'},
                                  {'id': 'd.4', 'q': 'Linda: {_} to meet you, too.', 't': 'fill'},
                                  {'id': 'd.5', 'q': 'Mai: {_} do you spell your name?', 't': 'fill'}]},
                       {'id': 'e',
                        'instr': 'Task 5. Chọn từ đúng điền vào chỗ trống.',
                        'items': [{'id': 'e.1', 'q': '{_} your name?', 't': 'fill'},
                                  {'id': 'e.2', 'q': "{_} name's Tim.", 't': 'fill'},
                                  {'id': 'e.3', 'q': '{_} do you spell your name?', 't': 'fill'},
                                  {'id': 'e.4', 'q': 'My {_} is Mary.', 't': 'fill'},
                                  {'id': 'e.5', 'q': 'How {_} you?', 't': 'fill'},
                                  {'id': 'e.6', 'q': 'Nice {_} meet you.', 't': 'fill'}]},
                       {'id': 'f',
                        'instr': 'Task 6. Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'f.1', 'q': '', 't': 'order', 'words': ['is', 'your', 'name?', 'What']},
                                  {'id': 'f.2', 'q': '', 't': 'order', 'words': ['Mary.', 'My', 'is', 'name']},
                                  {'id': 'f.3', 'q': '', 't': 'order', 'words': ['am', 'Linda.', 'I']},
                                  {'id': 'f.4', 'q': '', 't': 'order', 'words': ['do', 'How', 'spell', 'name?', 'you', 'your']},
                                  {'id': 'f.5', 'q': '', 't': 'order', 'words': ['is', 'Her', 'Mai.', 'name']}]}],
            'id': 'mau-cau',
            'mode': 'practice',
            'title': 'Mẫu câu'},
           {'groups': [{'id': 'g',
                        'instr': 'Task 7. Nhìn hình và viết: What is his / her name? – He / She is …',
                        'items': [{'id': 'g.1', 'img': 'image26.png', 'q': 'What is his name? – He is {_}.', 't': 'fill'},
                                  {'id': 'g.2', 'img': 'image28.png', 'q': 'What is her name? – She is {_}.', 't': 'fill'},
                                  {'id': 'g.3', 'img': 'image30.png', 'q': 'What is her name? – She is {_}.', 't': 'fill'},
                                  {'id': 'g.4', 'img': 'image31.png', 'q': 'What is her name? – She is {_}.', 't': 'fill'}]},
                       {'id': 'h',
                        'instr': 'Task 8. Chọn đáp án đúng.',
                        'items': [{'id': 'h.1', 'o': ['am', 'is', 'are', 'it'], 'plain': True, 'q': 'How ___ you, Mai?', 't': 'mcq'},
                                  {'id': 'h.2',
                                   'o': ['How', 'See', 'Nice', 'are'],
                                   'plain': True,
                                   'q': 'Goodbye. ___ you later.',
                                   't': 'mcq'},
                                  {'id': 'h.3',
                                   'o': ['Hello', 'Good-bye', 'Bye', 'See you'],
                                   'plain': True,
                                   'q': '___, I am Linda.',
                                   't': 'mcq'},
                                  {'id': 'h.4', 'o': ['soon', 'late', 'do', 'am'], 'plain': True, 'q': 'Goodbye. See you ___.', 't': 'mcq'},
                                  {'id': 'h.5',
                                   'o': ['Hello', 'Goodbye', 'What', "What's"],
                                   'plain': True,
                                   'q': '___ her name?',
                                   't': 'mcq'}]}],
            'id': 'doc-viet',
            'mode': 'practice',
            'title': 'Đọc – Viết'},
           {'groups': [{'id': 's1',
                        'instr': 'Nối số với chữ (số 1–5).',
                        'items': [{'id': 's1.1',
                                   'left': ['1', '2', '3', '4', '5'],
                                   'o': ['three', 'five', 'one', 'four', 'two'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 's2',
                        'instr': 'Nối số với chữ (số 6–10).',
                        'items': [{'id': 's2.1',
                                   'left': ['6', '7', '8', '9', '10'],
                                   'o': ['nine', 'ten', 'six', 'eight', 'seven'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 's3',
                        'instr': 'Viết số bằng chữ.',
                        'items': [{'id': 's3.1', 'q': '1 = {_}', 't': 'fill'},
                                  {'id': 's3.3', 'q': '3 = {_}', 't': 'fill'},
                                  {'id': 's3.5', 'q': '5 = {_}', 't': 'fill'},
                                  {'id': 's3.7', 'q': '7 = {_}', 't': 'fill'},
                                  {'id': 's3.9', 'q': '9 = {_}', 't': 'fill'}]},
                       {'id': 's4',
                        'instr': 'Sắp xếp lại chữ cái thành số.',
                        'items': [{'id': 's4.1', 'q': 'net → {_}', 't': 'fill'},
                                  {'id': 's4.2', 'q': 'vense → {_}', 't': 'fill'},
                                  {'id': 's4.3', 'q': 'veif → {_}', 't': 'fill'},
                                  {'id': 's4.4', 'q': 'neni → {_}', 't': 'fill'},
                                  {'id': 's4.5', 'q': 'rofu → {_}', 't': 'fill'},
                                  {'id': 's4.6', 'q': 'theig → {_}', 't': 'fill'},
                                  {'id': 's4.7', 'q': 'xis → {_}', 't': 'fill'}]}],
            'id': 'so-dem',
            'mode': 'practice',
            'title': 'Số đếm 1–10'},
           {'groups': [{'id': 'n1',
                        'instr': 'Nghe 1. Bấm 🔊 và chọn số em nghe được.',
                        'items': [{'id': 'n1.1', 'o': ['2', '3', '8'], 'plain': True, 'q': 'Em nghe số mấy?', 'say': 'three', 't': 'mcq'},
                                  {'id': 'n1.2', 'o': ['6', '7', '9'], 'plain': True, 'q': 'Em nghe số mấy?', 'say': 'seven', 't': 'mcq'},
                                  {'id': 'n1.3', 'o': ['1', '10', '5'], 'plain': True, 'q': 'Em nghe số mấy?', 'say': 'ten', 't': 'mcq'},
                                  {'id': 'n1.4', 'o': ['4', '8', '9'], 'plain': True, 'q': 'Em nghe số mấy?', 'say': 'eight', 't': 'mcq'},
                                  {'id': 'n1.5', 'o': ['5', '6', '4'], 'plain': True, 'q': 'Em nghe số mấy?', 'say': 'five', 't': 'mcq'}]},
                       {'id': 'n2',
                        'instr': 'Nghe 2. Nghe câu hỏi và chọn câu trả lời.',
                        'items': [{'id': 'n2.1',
                                   'o': ["My name's Nam.", "I'm eight years old.", "I'm fine."],
                                   'plain': True,
                                   'q': 'Em nghe câu hỏi:',
                                   'say': "What's your name?",
                                   't': 'mcq'},
                                  {'id': 'n2.2',
                                   'o': ["I'm eight years old.", "My name's Mai.", 'Goodbye.'],
                                   'plain': True,
                                   'q': 'Em nghe câu hỏi:',
                                   'say': 'How old are you?',
                                   't': 'mcq'},
                                  {'id': 'n2.3',
                                   'o': ["I'm fine, thanks.", "My name's Ben.", "I'm nine years old."],
                                   'plain': True,
                                   'q': 'Em nghe câu hỏi:',
                                   'say': 'How are you?',
                                   't': 'mcq'},
                                  {'id': 'n2.4',
                                   'o': ["Hi, Linda. I'm Tom.", "I'm ten years old.", 'Bye.'],
                                   'plain': True,
                                   'q': 'Em nghe câu:',
                                   'say': "Hello, I'm Linda.",
                                   't': 'mcq'}]},
                       {'id': 'n3',
                        'instr': 'Nghe 3. Nghe và viết số bằng chữ.',
                        'items': [{'id': 'n3.1', 'q': '{_}', 'say': 'two', 't': 'fill'},
                                  {'id': 'n3.2', 'q': '{_}', 'say': 'six', 't': 'fill'},
                                  {'id': 'n3.3', 'q': '{_}', 'say': 'nine', 't': 'fill'},
                                  {'id': 'n3.4', 'q': '{_}', 'say': 'four', 't': 'fill'},
                                  {'id': 'n3.5', 'q': '{_}', 'say': 'ten', 't': 'fill'}]},
                       {'id': 'n4',
                        'instr': 'Nghe 4. Nghe và viết lại câu.',
                        'items': [{'id': 'n4.1', 'q': '{_}', 'say': "What's your name?", 't': 'fill'},
                                  {'id': 'n4.2', 'q': '{_}', 'say': 'How old are you?', 't': 'fill'},
                                  {'id': 'n4.3', 'q': '{_}', 'say': "I'm eight years old.", 't': 'fill'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Nghe'},
           {'groups': [{'id': 'c1',
                        'instr': 'Điền chữ cái còn thiếu.',
                        'items': [{'id': 'c1.1', 'q': 'o{_}r', 't': 'fill'},
                                  {'id': 'c1.2', 'q': 'm{_}', 't': 'fill'},
                                  {'id': 'c1.3', 'q': 'ho{_} old', 't': 'fill'},
                                  {'id': 'c1.4', 'q': 'wh{_}t', 't': 'fill'},
                                  {'id': 'c1.5', 'q': 'y{_}ur', 't': 'fill'},
                                  {'id': 'c1.6', 'q': 'na{_}e', 't': 'fill'}]},
                       {'id': 'c2',
                        'instr': 'Sắp xếp lại chữ cái thành từ đúng.',
                        'items': [{'id': 'c2.1', 'q': 'ym → {_}', 't': 'fill'},
                                  {'id': 'c2.2', 'q': 'wath → {_}', 't': 'fill'},
                                  {'id': 'c2.3', 'q': 'ruyo → {_}', 't': 'fill'},
                                  {'id': 'c2.4', 'q': 'mena → {_}', 't': 'fill'},
                                  {'id': 'c2.5', 'q': 'ruo → {_}', 't': 'fill'},
                                  {'id': 'c2.6', 'q': 'woh lod → {_}', 't': 'fill'}]}],
            'id': 'chinh-ta',
            'mode': 'practice',
            'title': 'Chính tả'},
           {'groups': [{'id': 'e2',
                        'instr': 'Điền từ thích hợp.',
                        'items': [{'id': 'e2.1', 'q': "What's {_} name? – My name's Nam.", 't': 'fill'},
                                  {'id': 'e2.2', 'q': "How {_} are you? – I'm nine years old.", 't': 'fill'},
                                  {'id': 'e2.3', 'q': "My name's Lan. I'm five {_} old.", 't': 'fill'},
                                  {'id': 'e2.4', 'q': "What's your {_}? – My name's Mary.", 't': 'fill'},
                                  {'id': 'e2.5', 'q': "How old {_} you? – I'm ten.", 't': 'fill'}]},
                       {'id': 'f2',
                        'instr': 'Chọn đáp án đúng cho đoạn hội thoại.',
                        'items': [{'id': 'f2.1',
                                   'o': ['our', 'your', 'you'],
                                   'plain': True,
                                   'q': "Bill: Hi. I'm Bill. What's ___ name?",
                                   't': 'mcq'},
                                  {'id': 'f2.2',
                                   'o': ["name's", 'name', 'names'],
                                   'plain': True,
                                   'q': 'Nam: Hello, Bill. My ___ Nam.',
                                   't': 'mcq'},
                                  {'id': 'f2.3', 'o': ['much', 'old', 'many'], 'plain': True, 'q': 'Bill: How ___ are you?', 't': 'mcq'},
                                  {'id': 'f2.4',
                                   'o': ['nice', 'fine', 'nine'],
                                   'plain': True,
                                   'q': "Nam: I'm ___ years old.",
                                   't': 'mcq'}]},
                       {'id': 'g2',
                        'instr': 'Bấm các từ để xếp thành câu đúng.',
                        'items': [{'id': 'g2.1', 'q': '', 't': 'order', 'words': ['your', 'name?', "What's"]},
                                  {'id': 'g2.2', 'q': '', 't': 'order', 'words': ['name', 'is', 'Mary.', 'My']},
                                  {'id': 'g2.3', 'q': '', 't': 'order', 'words': ['are', 'How', 'you?', 'old']},
                                  {'id': 'g2.4', 'q': '', 't': 'order', 'words': ["I'm", 'ten', 'old.', 'years']},
                                  {'id': 'g2.5', 'q': '', 't': 'order', 'words': ['seven', 'years', 'old.', 'Bill', 'is']},
                                  {'id': 'g2.6', 'q': '', 't': 'order', 'words': ['is', 'name', 'my', 'Hello,', 'Nam.']},
                                  {'id': 'g2.7', 'q': '', 't': 'order', 'words': ['Keith.', 'name', 'His', 'is']},
                                  {'id': 'g2.8', 'q': '', 't': 'order', 'words': ['eight', 'years', 'old.', "She's"]}]}],
            'id': 'mau-cau-2',
            'mode': 'practice',
            'title': 'Mẫu câu 2 (hỏi tuổi)'},
           {'groups': [{'id': 'r1',
                        'instr': 'Sắp xếp hội thoại: chọn số thứ tự (câu đầu tiên là số 0: "Linh: Hello, I\'m Linh.").',
                        'items': [{'id': 'r1.1',
                                   'left': ["Mary: Hello, Linh. I'm Mary.",
                                            'Mary: How old are you?',
                                            "Linh: I'm eight years old. How about you?",
                                            "Mary: I'm eight years old, too."],
                                   'o': ['1', '2', '3', '4'],
                                   'q': '',
                                   't': 'match'}]},
                       {'id': 'r2',
                        'instr': 'Đọc và chọn True hoặc False.',
                        'items': [{'id': 'r2.1', 'q': 'Her name is Linda.', 't': 'tf'},
                                  {'id': 'r2.2', 'q': 'She is ten years old.', 't': 'tf'},
                                  {'id': 'r2.3', 'q': 'Linda says hello.', 't': 'tf'}],
                        'passage': "<p>Hello. My name's Linda. I'm nine years old.</p>"},
                       {'id': 'r3',
                        'instr': 'Đọc hội thoại và chọn True hoặc False.',
                        'items': [{'id': 'r3.1', 'q': "Bill asks about Nam's name.", 't': 'tf'},
                                  {'id': 'r3.2', 'q': 'Nam is nine years old.', 't': 'tf'},
                                  {'id': 'r3.3', 'q': 'Bill asks "How old are you?"', 't': 'tf'},
                                  {'id': 'r3.4', 'q': "Nam's name is Bill.", 't': 'tf'}],
                        'passage': "<p><b>Bill:</b> Hi. I'm Bill. What's your name?<br><b>Nam:</b> Hello, Bill. My name's "
                                   "Nam.<br><b>Bill:</b> How old are you?<br><b>Nam:</b> I'm eight years old.</p>"}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'}],
 'theory': '<h3>Từ vựng</h3><table class="th"><tr><th>English</th><th>Tiếng Việt</th></tr><tr><td>what</td><td>cái '
           "gì</td></tr><tr><td>what's (= what is)</td><td>là cái gì</td></tr><tr><td>your</td><td>của bạn</td></tr><tr><td>my</td><td>của "
           'tôi / của mình</td></tr><tr><td>name</td><td>tên</td></tr><tr><td>how</td><td>như thế nào</td></tr><tr><td>spell</td><td>đánh '
           "vần</td></tr></table><h3>Mẫu câu</h3><ul><li><b>What's your name?</b> – Tên bạn là gì? &rarr; <b>My name's Quynh.</b> / <b>I'm "
           "Quynh.</b></li><li><b>What's his / her name?</b> – Tên bạn ấy là gì? &rarr; <b>His / Her name's Mai.</b></li><li><b>How do you "
           'spell your name?</b> – Bạn đánh vần tên thế nào? &rarr; <b>L-I-N-D-A.</b></li></ul>',
 'title': "Unit 2 – What's your name?: Luyện tập",
 'unit': 2}
