# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u2-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['3', '8', '10'],
                                   'plain': True,
                                   'q': 'Bấm 🔊 và chọn số em nghe được.',
                                   'say': 'eight',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ["My name's Mai.", "I'm nine.", 'Bye.'],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe câu hỏi rồi chọn câu trả lời.',
                                   'say': "What's your name?",
                                   't': 'mcq'},
                                  {'id': 't1.3', 'o': ['old', 'name', 'what'], 'plain': True, 'q': 'How ___ are you?', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['you', 'fine', 'bye'],
                                   'plain': True,
                                   'q': "Hello. My name's Linda. Nice to meet ___.",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ['Peter', 'Linda', 'how'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.6', 'q': '{_} your name?', 't': 'fill'},
                                  {'id': 't1.7', 'q': 'My {_} is Mary.', 't': 'fill'},
                                  {'id': 't1.8', 'q': 'How old are {_}?', 't': 'fill'},
                                  {'id': 't1.9', 'q': 'Số 9 viết là: {_}', 't': 'fill'},
                                  {'id': 't1.10', 'q': 'ruo → {_}', 't': 'fill'},
                                  {'id': 't1.11', 'q': '', 't': 'order', 'words': ['old.', "I'm", 'years', 'eight']},
                                  {'id': 't1.12', 'q': '', 't': 'order', 'words': ['Mai.', 'Her', 'is', 'name']},
                                  {'id': 't1.13', 'q': '', 't': 'order', 'words': ['you?', 'How', 'are', 'old']},
                                  {'id': 't1.14',
                                   'left': ['2', '4', '6', '9'],
                                   'o': ['six', 'nine', 'two', 'four'],
                                   'q': 'Nối số với chữ:',
                                   't': 'match'},
                                  {'id': 't1.15', 'q': '', 't': 'order', 'words': ['Keith.', 'His', 'is', 'name']},
                                  {'id': 't1.16',
                                   'o': ["I'm eight years old.", "I'm Mai.", 'Goodbye.'],
                                   'plain': True,
                                   'q': '— How old are you? — ___',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['how old', 'what', 'name'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "bao nhiêu tuổi":',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['What', 'How', 'Fine'],
                                   'plain': True,
                                   'q': '___ is your name? (hỏi tên)',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'q': 'mena → {_}', 't': 'fill'},
                                  {'id': 't1.20', 'q': 'Hello, my {_} is Mai.', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': "Unit 2 – What's your name?: Kiểm tra 3",
 'unit': 2}
