# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'a.1': 'face',
 'a.2': 'nose',
 'a.3': 'eye',
 'a.4': 'ear',
 'a.5': 'hand',
 'a.6': 'mouth',
 'a.7': 'hair',
 'b.1': 'open',
 'b.2': 'touch',
 'b.3': 'open',
 'b.4': 'ear',
 'c1.1': ['c'],
 'c1.2': ['s'],
 'c1.3': ['y'],
 'c1.4': ['a'],
 'c1.5': ['n'],
 'c1.6': ['u'],
 'c1.7': ['i'],
 'c1.8': ['u'],
 'c1.9': ['e'],
 'c2.1': ['face'],
 'c2.2': ['nose'],
 'c2.3': ['eye'],
 'c2.4': ['ear'],
 'c2.5': ['hand'],
 'c2.6': ['mouth'],
 'c2.7': ['hair'],
 'c2.8': ['touch'],
 'c2.9': ['open'],
 'd.1': {'blanks': [["It's a nose."], ["It's an eye."], ["I'm fine, thanks."], ["My name's Mai."], ['Yes, it is.']]},
 'e.1': ['this'],
 'e.2': ['that'],
 'e.3': ['an'],
 'e.4': ['a'],
 'e.5': ['an'],
 'e.6': ['nose'],
 'e.7': ['ear'],
 'e.8': ['mouth'],
 'e2.1': 'an',
 'e2.10': 'mouth',
 'e2.11': 'nose',
 'e2.12': 'hair',
 'e2.2': 'a',
 'e2.3': "It's a hand.",
 'e2.4': 'Open',
 'e2.5': 'Touch',
 'e2.6': 'an',
 'e2.7': 'a',
 'e2.8': 'ear',
 'e2.9': 'mouth',
 'f.1': ["It's a nose."],
 'f.2': ["It's an eye."],
 'f.3': ["It's a face."],
 'f.4': ['Open your mouth.'],
 'f.5': ['Touch your ears.'],
 'f.6': ['Open your eyes.'],
 'f2.1': ['eye'],
 'f2.2': ['hand'],
 'f2.3': ['face'],
 'f2.4': ['Touch'],
 'f2.5': ['Open'],
 'f2.6': ['hair'],
 'g2.1': ['Touch your hair.'],
 'g2.2': ["What's this?"],
 'g2.3': ["What's that?"],
 'g2.4': ['Touch your nose.'],
 'm1.1': {'blanks': [['khuôn mặt'], ['mũi'], ['mắt'], ['tai'], ['bàn tay'], ['miệng']]},
 'm1.2': {'blanks': [['tóc'], ['sờ, chạm'], ['mở, há']]},
 'n1.1': 'face',
 'n1.2': 'nose',
 'n1.3': 'eye',
 'n1.4': 'ear',
 'n1.5': 'hand',
 'n1.6': 'mouth',
 'n2.1': "It's a nose.",
 'n2.2': "It's an eye.",
 'n2.3': "I'm fine, thanks.",
 'n2.4': "My name's Mai.",
 'n2.5': 'Yes, it is.',
 'n3.1': ['face'],
 'n3.2': ['nose'],
 'n3.3': ['eye'],
 'n3.4': ['ear'],
 'n3.5': ['hand'],
 'n4.1': ["It's a nose."],
 'n4.2': ["It's an eye."],
 'n4.3': ["It's a face."],
 'r1.1': {'blanks': [['1'], ['2'], ['3'], ['4']]},
 'r2.1': 'T',
 'r2.2': 'F',
 'r2.3': 'T',
 'r2.4': 'T',
 'r3.1': 'T',
 'r3.2': 'F',
 'r3.3': 'T'}

EXPLANATIONS = {'a.1': 'face = khuôn mặt (🙂)',
 'a.2': 'nose = mũi (👃)',
 'a.3': 'eye = mắt (👁️)',
 'a.4': 'ear = tai (👂)',
 'a.5': 'hand = bàn tay (✋)',
 'a.6': 'mouth = miệng (👄)',
 'a.7': 'hair = tóc (💇)',
 'b.1': 'eye, ear là bộ phận cơ thể; open là "mở".',
 'b.2': 'nose, mouth là bộ phận cơ thể; touch là "sờ".',
 'b.3': 'face, hand là bộ phận cơ thể.',
 'b.4': 'touch, open là động từ; ear là danh từ.',
 'c1.1': 'face',
 'c1.2': 'nose',
 'c1.3': 'eye',
 'c1.4': 'ear',
 'c1.5': 'hand',
 'c1.6': 'mouth',
 'c1.7': 'hair',
 'c1.8': 'touch',
 'c1.9': 'open',
 'c2.1': 'face',
 'c2.2': 'nose',
 'c2.3': 'eye',
 'c2.4': 'ear',
 'c2.5': 'hand',
 'c2.6': 'mouth',
 'c2.7': 'hair',
 'c2.8': 'touch',
 'c2.9': 'open',
 'd.1': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 'e.1': "What's this? (vật ở gần)",
 'e.2': "What's that?",
 'e.3': 'eye bắt đầu bằng nguyên âm → an.',
 'e.4': 'nose bắt đầu bằng phụ âm → a.',
 'e.5': 'ear bắt đầu bằng nguyên âm → an.',
 'e.6': 'nose = mũi',
 'e.7': 'ear = tai',
 'e.8': 'mouth = miệng',
 'e2.1': 'ear bắt đầu bằng nguyên âm → an.',
 'e2.10': 'Ta há miệng (mouth).',
 'e2.11': 'nose = mũi.',
 'e2.12': 'hair = tóc.',
 'e2.2': 'nose → a.',
 'e2.3': 'Hỏi "đây là gì" → It\'s a …',
 'e2.4': 'Open = mở / há.',
 'e2.5': 'Touch = sờ.',
 'e2.6': 'an eye.',
 'e2.7': 'a face.',
 'e2.8': 'ear = tai.',
 'e2.9': 'mouth = miệng.',
 'f.1': "It's a nose.",
 'f.2': "It's an eye.",
 'f.3': "It's a face.",
 'f.4': 'Open your mouth.',
 'f.5': 'Touch your ears.',
 'f.6': 'Open your eyes.',
 'f2.1': 'eye = mắt',
 'f2.2': 'hand = bàn tay',
 'f2.3': 'face = khuôn mặt',
 'f2.4': 'Touch your hair!',
 'f2.5': 'Open your mouth!',
 'f2.6': 'hair = tóc',
 'g2.1': 'Touch your hair.',
 'g2.2': "What's this?",
 'g2.3': "What's that?",
 'g2.4': 'Touch your nose.',
 'm1.1': 'face = khuôn mặt; nose = mũi; eye = mắt; ear = tai; hand = bàn tay; mouth = miệng',
 'm1.2': 'hair = tóc; touch = sờ, chạm; open = mở, há',
 'n1.1': 'Từ được đọc là: face.',
 'n1.2': 'Từ được đọc là: nose.',
 'n1.3': 'Từ được đọc là: eye.',
 'n1.4': 'Từ được đọc là: ear.',
 'n1.5': 'Từ được đọc là: hand.',
 'n1.6': 'Từ được đọc là: mouth.',
 'n2.1': "What's this? → It's a nose.",
 'n2.2': "What's that? → It's an eye.",
 'n2.3': "How are you? → I'm fine, thanks.",
 'n2.4': "What's your name? → My name's Mai.",
 'n2.5': 'Is this Bill? → Yes, it is.',
 'n3.1': 'face',
 'n3.2': 'nose',
 'n3.3': 'eye',
 'n3.4': 'ear',
 'n3.5': 'hand',
 'n4.1': "It's a nose.",
 'n4.2': "It's an eye.",
 'n4.3': "It's a face.",
 'r1.1': "Thứ tự đúng: A: What's this? → B: It's a hand. → A: What's that? → B: It's a nose. → A: Thank you.",
 'r2.1': 'two eyes = 2 mắt.',
 'r2.2': 'one nose = 1 mũi.',
 'r2.3': 'one mouth.',
 'r2.4': 'two ears, too.',
 'r3.1': 'Touch your nose.',
 'r3.2': 'Cô nói Open your mouth.',
 'r3.3': 'Touch your ears.'}

GHI_CHU_RA_SOAT = []
