# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'t1.1': 'Hello',
 't1.10': ['bye'],
 't1.11': ['Hello, Miss Hoa.'],
 't1.12': ["I'm fine, thanks."],
 't1.13': ['How are you?'],
 't1.14': {'blanks': [['Fine, thanks.'], ['Bye. See you later.'], ['Nice to meet you, too!'], ['Hello!']]},
 't1.15': ['Goodbye, Miss Hoa.'],
 't1.16': 'thank you',
 't1.17': 'hi',
 't1.18': 'How',
 't1.19': ['you'],
 't1.2': "I'm fine, thank you.",
 't1.20': ['hello'],
 't1.3': 'Bye, Mai.',
 't1.4': 'Nice to meet you, too.',
 't1.5': 'hello',
 't1.6': ['you'],
 't1.7': ['are'],
 't1.8': ['fine'],
 't1.9': ['later']}

EXPLANATIONS = {'t1.1': 'Giới thiệu bắt đầu bằng lời chào.',
 't1.10': 'bye',
 't1.11': 'Hello, Miss Hoa.',
 't1.12': "I'm fine, thanks.",
 't1.13': 'How are you?',
 't1.14': 'Mỗi câu nói có một câu đáp.',
 't1.15': 'Goodbye, Miss Hoa.',
 't1.16': 'thank you = cảm ơn.',
 't1.17': 'hi = xin chào.',
 't1.18': 'How are you?',
 't1.19': 'Thank you.',
 't1.2': 'Hỏi thăm → trả lời khỏe.',
 't1.20': 'hello',
 't1.3': 'Tạm biệt thì đáp Bye.',
 't1.4': 'Đáp lại làm quen.',
 't1.5': 'bye, goodbye = tạm biệt; hello = chào.',
 't1.6': 'Nice to meet you.',
 't1.7': 'How are you?',
 't1.8': "I'm fine, thanks.",
 't1.9': 'See you later.'}

GHI_CHU_RA_SOAT = []
