# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u5-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['swimming', 'running', 'walking'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "bơi":',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['drawing', 'painting', 'cooking'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "vẽ":',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['cooking', 'singing', 'dancing'],
                                   'plain': True,
                                   'q': 'Chọn từ nghĩa "nấu ăn":',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['hobby', 'like', 'friend'],
                                   'plain': True,
                                   'q': "What's your ___? – It's singing.",
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['drawing', 'cooking', 'running'],
                                   'plain': True,
                                   'q': '<span class="emo">✏️</span>',
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'o': ['swimming', 'painting', 'singing'],
                                   'plain': True,
                                   'q': '<span class="emo">🏊</span>',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['running', 'walking', 'like'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['vẽ', 'chạy', 'nhảy, múa'],
                                   'plain': True,
                                   'q': 'Nghĩa của "drawing" là:',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['nhảy, múa', 'chạy', 'bơi'],
                                   'plain': True,
                                   'q': 'Nghĩa của "swimming" là:',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ["It's singing.", "It's drawing.", "My name's Nam."],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': "What's your hobby, Mary?",
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': "🎤 It's {_}.", 't': 'fill'},
                                  {'id': 't1.12', 'q': "💃 It's {_}.", 't': 'fill'},
                                  {'id': 't1.13', 'q': "🏊 It's {_}.", 't': 'fill'},
                                  {'id': 't1.14', 'q': "🍳 It's {_}.", 't': 'fill'},
                                  {'id': 't1.15', 'q': 'ngnidca → {_}', 't': 'fill'},
                                  {'id': 't1.16', 'q': '', 't': 'order', 'words': ['painting.', 'is', 'My', 'hobby']},
                                  {'id': 't1.17', 'q': '', 't': 'order', 'words': ['dancing.', 'likes', 'and', 'She', 'singing']},
                                  {'id': 't1.18', 'q': '', 't': 'order', 'words': ['and', 'are', 'Our', 'hobbies', 'swimming', 'cooking.']},
                                  {'id': 't1.19', 'q': '', 't': 'order', 'words': ['cooking.', "It's"]},
                                  {'id': 't1.20',
                                   'left': ["What's your hobby, Mary?", 'I like dancing.', 'How are you?', "What's your name?"],
                                   'o': ["My name's Nam.", "It's drawing.", 'Me too.', "I'm fine, thanks."],
                                   'q': 'Nối:',
                                   't': 'match'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 5 – My hobbies: Kiểm tra 2',
 'unit': 5}
