# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'a.1': 'friend',
 'a.2': 'teacher',
 'a.3': 'Mr',
 'a.4': 'Ms',
 'a.5': 'this',
 'a.6': 'that',
 'a.7': 'yes',
 'a.8': 'no',
 'b.1': 'yes',
 'b.2': 'this',
 'b.3': 'Mr',
 'b.4': 'no',
 'c1.1': ['e'],
 'c1.2': ['c'],
 'c1.3': ['i'],
 'c1.4': ['a'],
 'c1.5': ['e'],
 'c2.1': ['friend'],
 'c2.2': ['teacher'],
 'c2.3': ['this'],
 'c2.4': ['that'],
 'c2.5': ['yes'],
 'd.1': {'blanks': [['Yes, it is.'], ["No, it isn't. It's Minh."], ['Hi, Mary.'], ['Hello, Mr Long.'], ["I'm fine, thank you."]]},
 'e.1': ['thank you', 'thanks'],
 'e.2': ['Is'],
 'e.3': ['that'],
 'e.4': ['Mr'],
 'e.5': ['friend'],
 'e.6': ['Ms', 'Miss'],
 'e.7': ['Yes'],
 'e.8': ['No'],
 'e2.1': 'Yes, it is.',
 'e2.10': "It's",
 'e2.11': 'friend',
 'e2.12': 'Thank',
 'e2.2': 'is',
 'e2.3': "isn't",
 'e2.4': 'This',
 'e2.5': "That's",
 'e2.6': 'Hi, Nam.',
 'e2.7': 'Hello, Ms Hoa.',
 'e2.8': 'Yes, it is.',
 'e2.9': 'teacher',
 'f.1': ['This is my friend Linh.'],
 'f.2': ["That's my teacher, Ms Hoa."],
 'f.3': ['Is this Bill?'],
 'f.4': ['Yes, it is.'],
 'f.5': ["No, it isn't."],
 'f.6': ['Is that Mai?'],
 'f2.1': ['Hello', 'Hi'],
 'f2.2': ['is'],
 'f2.3': ['Hello', 'Hi'],
 'f2.4': ['This'],
 'f2.5': ['That'],
 'f2.6': ['is'],
 'g2.1': ['Thank you, Ben.'],
 'g2.2': ["That's Mr Long."],
 'g2.3': ['Hello, Mr Long.'],
 'g2.4': ['This is Mary.'],
 'm1.1': {'blanks': [['bạn'], ['giáo viên'], ['ông, thầy'], ['cô'], ['đây, cái này (ở gần)'], ['kia, cái kia (ở xa)']]},
 'm1.2': {'blanks': [['vâng, đúng'], ['không'], ['nó']]},
 'n1.1': 'friend',
 'n1.2': 'teacher',
 'n1.3': 'this',
 'n1.4': 'that',
 'n1.5': 'yes',
 'n2.1': 'Yes, it is.',
 'n2.2': "No, it isn't. It's Minh.",
 'n2.3': 'Hi, Mary.',
 'n2.4': 'Hello, Mr Long.',
 'n2.5': "I'm fine, thank you.",
 'n3.1': ['friend'],
 'n3.2': ['teacher'],
 'n3.3': ['this'],
 'n3.4': ['that'],
 'n3.5': ['yes'],
 'n4.1': ['This is my friend Linh.'],
 'n4.2': ["That's my teacher, Ms Hoa."],
 'n4.3': ['Is this Bill?'],
 'r1.1': {'blanks': [['1'], ['2'], ['3'], ['4']]},
 'r2.1': 'T',
 'r2.2': 'F',
 'r2.3': 'F',
 'r3.1': 'T',
 'r3.2': 'F',
 'r3.3': 'T',
 'r3.4': 'F'}

EXPLANATIONS = {'a.1': 'friend = bạn (👫)',
 'a.2': 'teacher = giáo viên (👩\u200d🏫)',
 'a.3': 'Mr = ông, thầy (👨)',
 'a.4': 'Ms = cô (👩)',
 'a.5': 'this = đây, cái này (ở gần) (👇)',
 'a.6': 'that = kia, cái kia (ở xa) (👉)',
 'a.7': 'yes = vâng, đúng (✅)',
 'a.8': 'no = không (❌)',
 'b.1': 'Mr, Ms dùng trước tên người; yes là "vâng".',
 'b.2': 'friend, teacher là người; this là "đây".',
 'b.3': 'yes, no là trả lời; Mr là "ông/thầy".',
 'b.4': 'this, that chỉ người/vật; no là "không".',
 'c1.1': 'friend',
 'c1.2': 'teacher',
 'c1.3': 'this',
 'c1.4': 'that',
 'c1.5': 'yes',
 'c2.1': 'friend',
 'c2.2': 'teacher',
 'c2.3': 'this',
 'c2.4': 'that',
 'c2.5': 'yes',
 'd.1': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 'e.1': "I'm fine, thank you.",
 'e.2': 'Câu hỏi bắt đầu bằng Is: Is this Lan?',
 'e.3': 'Is that Mai? (người ở xa)',
 'e.4': 'Mr Long = thầy/ông Long.',
 'e.5': 'my friend Nam = bạn Nam của tôi.',
 'e.6': 'Ms/Miss Hoa = cô Hoa.',
 'e.7': 'Yes, it is.',
 'e.8': "No, it isn't.",
 'e2.1': 'Is this …? → Yes, it is.',
 'e2.10': "It's Lucy.",
 'e2.11': 'friend = bạn.',
 'e2.12': 'Thank you.',
 'e2.2': 'This is …',
 'e2.3': "No, it isn't.",
 'e2.4': 'This = ở gần.',
 'e2.5': "That's = kia là.",
 'e2.6': 'Được giới thiệu thì chào lại.',
 'e2.7': 'Chào cô Hoa.',
 'e2.8': 'Trả lời Yes/No.',
 'e2.9': 'teacher = giáo viên.',
 'f.1': 'This is my friend Linh.',
 'f.2': "That's my teacher, Ms Hoa.",
 'f.3': 'Is this Bill?',
 'f.4': 'Yes, it is.',
 'f.5': "No, it isn't.",
 'f.6': 'Is that Mai?',
 'f2.1': 'Chào lại: Hello / Hi.',
 'f2.2': 'This is Nam.',
 'f2.3': 'Chào thầy: Hello, Mr Long.',
 'f2.4': 'This is Mary.',
 'f2.5': "That's Mr Long.",
 'f2.6': 'Yes, it is.',
 'g2.1': 'Thank you, Ben.',
 'g2.2': "That's Mr Long.",
 'g2.3': 'Hello, Mr Long.',
 'g2.4': 'This is Mary.',
 'm1.1': 'friend = bạn; teacher = giáo viên; Mr = ông, thầy; Ms = cô; this = đây, cái này (ở gần); that = kia, cái kia (ở xa)',
 'm1.2': 'yes = vâng, đúng; no = không; it = nó',
 'n1.1': 'Từ được đọc là: friend.',
 'n1.2': 'Từ được đọc là: teacher.',
 'n1.3': 'Từ được đọc là: this.',
 'n1.4': 'Từ được đọc là: that.',
 'n1.5': 'Từ được đọc là: yes.',
 'n2.1': 'Is this Bill? → Yes, it is.',
 'n2.2': "Is that Nam? → No, it isn't. It's Minh.",
 'n2.3': 'This is Mary. → Hi, Mary.',
 'n2.4': "That's Mr Long. → Hello, Mr Long.",
 'n2.5': "How are you? → I'm fine, thank you.",
 'n3.1': 'friend',
 'n3.2': 'teacher',
 'n3.3': 'this',
 'n3.4': 'that',
 'n3.5': 'yes',
 'n4.1': 'This is my friend Linh.',
 'n4.2': "That's my teacher, Ms Hoa.",
 'n4.3': 'Is this Bill?',
 'r1.1': "Thứ tự đúng: Nam: Hello, I'm Nam. → Quan: Hi, Nam. I'm Quan. → Nam: Is that Ms Hoa, Quan? → Quan: Yes, it's Ms Hoa, my English "
         'teacher. → Nam: Ms Hoa is my English teacher, too.',
 'r2.1': 'This is my friend, Linh.',
 'r2.2': 'Ms Hoa là cô giáo (teacher).',
 'r2.3': 'Nam giới thiệu bạn và cô giáo; Nam không phải giáo viên.',
 'r3.1': "No, it isn't. It's Tom.",
 'r3.2': "No, it isn't Bill.",
 'r3.3': 'Yes, it is.',
 'r3.4': 'Câu hỏi thứ hai Nam trả lời Yes.'}

GHI_CHU_RA_SOAT = []
