# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'a.1': 'hello',
 'a.2': 'goodbye',
 'a.3': 'thank you',
 'a.4': 'hi',
 'a.5': 'fine',
 'b.1': 'bye',
 'b.2': 'how',
 'b.3': 'ten',
 'b.4': 'hello',
 'b.5': 'bye',
 'c.1': ['hello'],
 'c.2': ['hi'],
 'c.3': ['thanks'],
 'c.4': ['bye'],
 'c.5': ['you'],
 'c1.1': ['a'],
 'c1.2': ['w'],
 'c1.3': ['o'],
 'c1.4': ['i'],
 'c1.5': ['d'],
 'c1.6': ['e'],
 'c1.7': ['i'],
 'c2.1': ['you'],
 'c2.2': ['hello'],
 'c2.3': ['good bye', 'goodbye'],
 'c2.4': ['fine'],
 'c2.5': ['how'],
 'c2.6': ['thank you'],
 'd.1': {'blanks': [['Fine, thanks.'], ['Hello!'], ['Bye. See you later.'], ['Hi!'], ['Nice to meet you, too!']]},
 'e.1': ['Hello'],
 'e.2': ['How'],
 'e.3': ['fine'],
 'e.4': ['you'],
 'e.5': ['thanks'],
 'e2.1': ["I'm"],
 'e2.2': ['thank you', 'thanks'],
 'e2.3': ['Goodbye', 'Bye'],
 'e2.4': ['Hello', 'Hi'],
 'e2.5': ['you'],
 'e2.6': ['Hi', 'Hello'],
 'e2.7': ['thank'],
 'e2.8': ['How'],
 'f.1': ["Hello, Quan. I'm Phong."],
 'f.2': ["I'm fine, thanks."],
 'f.3': ['How are you?'],
 'f.4': ['Nice to meet you, too.'],
 'f.5': ['Goodbye, Miss Hoa.'],
 'f2.1': 'you',
 'f2.2': 'fine',
 'f2.3': "I'm",
 'f2.4': 'Bye',
 'g2.1': ["Hi, Mai. I'm Minh."],
 'g2.2': ['Goodbye, Minh.'],
 'g2.3': ['How are you, Lan?'],
 'g2.4': ["I'm fine, thanks."],
 'g2.5': ['Bye. See you later.'],
 'g2.6': ['Goodbye. See you next week, Bill.'],
 'm1.1': {'blanks': [['xin chào'], ['tạm biệt'], ['cảm ơn'], ['khỏe'], ['tên'], ['trường học']]},
 'n1.1': 'hello',
 'n1.2': 'goodbye',
 'n1.3': 'fine',
 'n1.4': 'thank you',
 'n1.5': 'hi',
 'n1.6': 'bye',
 'n2.1': "I'm fine, thank you.",
 'n2.2': 'Bye, Mai.',
 'n2.3': 'Nice to meet you, too.',
 'n2.4': "Hi, Tony. I'm Linda.",
 'n2.5': 'Fine, thanks.',
 'n3.1': ['hello'],
 'n3.2': ['goodbye'],
 'n3.3': ['thanks'],
 'n3.4': ['fine'],
 'n3.5': ['bye'],
 'n4.1': ['How are you?'],
 'n4.2': ["I'm fine, thanks.", "I'm fine, thank you."],
 'n4.3': ['Goodbye, Mai.'],
 'r1.1': {'blanks': [['1'], ['2'], ['3'], ['4']]},
 'r2.1': 'T',
 'r2.2': 'F',
 'r2.3': 'T',
 'r3.1': 'T',
 'r3.2': 'F',
 'r3.3': 'T',
 'r3.4': 'F'}

EXPLANATIONS = {'a.1': 'Các bạn đang vẫy tay chào nhau → hello.',
 'a.2': 'Mẹ và bé vẫy tay chia tay → goodbye.',
 'a.3': 'Bạn nhỏ đưa quà / nói cảm ơn → thank you.',
 'a.4': 'Chú chim cánh cụt vẫy chào → hi.',
 'a.5': 'Ngón tay OK nghĩa là khỏe → fine.',
 'b.1': 'hi, hello là lời chào; bye là lời tạm biệt.',
 'b.2': 'Peter, Tony là tên người; how là từ để hỏi.',
 'b.3': 'pink, yellow là màu sắc; ten là số.',
 'b.4': 'bye, goodbye là tạm biệt; hello là chào.',
 'b.5': 'thanks, thank you đều là cảm ơn; bye là tạm biệt.',
 'c.1': 'h-e-l-l-o = hello.',
 'c.2': 'h-i = hi.',
 'c.3': 't-h-a-n-k-s = thanks.',
 'c.4': 'b-y-e = bye.',
 'c.5': 'y-o-u = you.',
 'c1.1': 'thank you',
 'c1.2': 'how',
 'c1.3': 'you',
 'c1.4': 'hi',
 'c1.5': 'goodbye',
 'c1.6': 'hello',
 'c1.7': 'fine',
 'c2.1': 'you',
 'c2.2': 'hello',
 'c2.3': 'good bye = goodbye',
 'c2.4': 'fine',
 'c2.5': 'how',
 'c2.6': 'thank you',
 'd.1': "How are you? – Fine, thanks. | Hi! I'm Mai. – Hello! | Goodbye! – Bye. See you later. | Hello. – Hi! | Nice to meet you! – Nice "
        'to meet you, too!',
 'e.1': 'Chào lại: Hello.',
 'e.2': 'How are you? = Bạn khỏe không?',
 'e.3': "I'm fine, thanks. = Mình khỏe, cảm ơn.",
 'e.4': 'Thank you = cảm ơn bạn.',
 'e.5': 'Fine, thanks. = Khỏe, cảm ơn.',
 'e2.1': "I'm Mai. = Mình là Mai.",
 'e2.2': "I'm fine, thank you.",
 'e2.3': 'Goodbye / Bye = tạm biệt.',
 'e2.4': 'Mở đầu bằng lời chào.',
 'e2.5': 'How are you?',
 'e2.6': 'Chào rồi giới thiệu.',
 'e2.7': 'thank you',
 'e2.8': 'How are you?',
 'f.1': "Chào Quan rồi giới thiệu: Hello, Quan. I'm Phong.",
 'f.2': "I'm fine, thanks. = Mình khỏe, cảm ơn.",
 'f.3': 'Câu hỏi thăm sức khoẻ: How are you?',
 'f.4': 'Đáp lại: Nice to meet you, too.',
 'f.5': 'Goodbye, Miss Hoa. = Tạm biệt cô Hoa.',
 'f2.1': 'How are you?',
 'f2.2': "I'm fine, thanks.",
 'f2.3': "I'm fine.",
 'f2.4': 'Đáp lại lời tạm biệt.',
 'g2.1': "Hi, Mai. I'm Minh. = Chào Mai. Mình là Minh.",
 'g2.2': 'Goodbye, Minh.',
 'g2.3': 'How are you, Lan?',
 'g2.4': "I'm fine, thanks.",
 'g2.5': 'Bye. See you later. = Tạm biệt. Hẹn gặp lại.',
 'g2.6': 'See you next week = Hẹn gặp lại tuần sau.',
 'm1.1': 'hello = xin chào, goodbye = tạm biệt, thank you = cảm ơn, fine = khỏe, name = tên, school = trường học.',
 'n1.1': 'Từ được đọc là: hello.',
 'n1.2': 'Từ được đọc là: goodbye.',
 'n1.3': 'Từ được đọc là: fine.',
 'n1.4': 'Từ được đọc là: thank you.',
 'n1.5': 'Từ được đọc là: hi.',
 'n1.6': 'Từ được đọc là: bye.',
 'n2.1': 'Câu hỏi là "How are you?" → trả lời I\'m fine, thank you.',
 'n2.2': 'Nghe "Goodbye, Nam." → đáp lại Bye.',
 'n2.3': 'Nghe "Nice to meet you." → đáp Nice to meet you, too.',
 'n2.4': 'Được chào Hello thì chào lại.',
 'n2.5': 'Nghe "I\'m fine, thank you." → bạn ấy đang trả lời "How are you?".',
 'n3.1': 'hello',
 'n3.2': 'goodbye',
 'n3.3': 'thanks = cảm ơn',
 'n3.4': 'fine',
 'n3.5': 'bye',
 'n4.1': 'How are you?',
 'n4.2': "I'm fine, thanks.",
 'n4.3': 'Goodbye, Mai.',
 'r1.1': "Thứ tự: 0 Nam: Hello, I'm Nam. → 1 Quan: Hi, Nam. I'm Quan. → 2 Nam: How are you, Quan? → 3 Quan: I'm fine... → 4 Nam: I'm fine, "
         'too.',
 'r2.1': "I'm Mai → tên bạn ấy là Mai.",
 'r2.2': 'Bạn ấy chào (Hello), chưa tạm biệt.',
 'r2.3': "I'm fine → Mai khỏe.",
 'r3.1': 'Nam hỏi Lan: How are you?',
 'r3.2': "Lan nói I'm fine.",
 'r3.3': 'Cả hai đều tạm biệt.',
 'r3.4': 'Cuối hội thoại Lan nói Bye.'}

GHI_CHU_RA_SOAT = []
