# -*- coding: utf-8 -*-
"""Đáp án + giải thích (Lớp 3)."""

ANS = {'t1.1': 'an',
 't1.10': "It's a nose.",
 't1.11': ['this'],
 't1.12': ['that'],
 't1.13': ['an'],
 't1.14': ['a'],
 't1.15': ['face'],
 't1.16': ["It's a nose."],
 't1.17': ["It's an eye."],
 't1.18': ["It's a face."],
 't1.19': ['Open your mouth.'],
 't1.2': 'a',
 't1.20': {'blanks': [["It's a nose."], ["It's an eye."], ["I'm fine, thanks."], ["My name's Mai."]]},
 't1.3': "It's a hand.",
 't1.4': 'Open',
 't1.5': 'face',
 't1.6': 'nose',
 't1.7': 'open',
 't1.8': 'khuôn mặt',
 't1.9': 'mũi'}

EXPLANATIONS = {'t1.1': 'ear bắt đầu bằng nguyên âm → an.',
 't1.10': "What's this? → It's a nose.",
 't1.11': "What's this? (vật ở gần)",
 't1.12': "What's that?",
 't1.13': 'eye bắt đầu bằng nguyên âm → an.',
 't1.14': 'nose bắt đầu bằng phụ âm → a.',
 't1.15': 'face',
 't1.16': "It's a nose.",
 't1.17': "It's an eye.",
 't1.18': "It's a face.",
 't1.19': 'Open your mouth.',
 't1.2': 'nose → a.',
 't1.20': 'Mỗi câu hỏi có một câu đáp tương ứng.',
 't1.3': 'Hỏi "đây là gì" → It\'s a …',
 't1.4': 'Open = mở / há.',
 't1.5': 'face = khuôn mặt (🙂)',
 't1.6': 'nose = mũi (👃)',
 't1.7': 'eye, ear là bộ phận cơ thể; open là "mở".',
 't1.8': 'face = khuôn mặt',
 't1.9': 'nose = mũi'}

GHI_CHU_RA_SOAT = []
