# -*- coding: utf-8 -*-
"""Lớp 3 – Global Success. Sinh bởi tools/gen_lop3.py; nguồn: Bài tập chuyên sâu Tiếng Anh 3."""

SET = {'grade': 3,
 'id': 'lop3-u3-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["That's", "This's", 'Are'],
                                   'plain': True,
                                   'q': '___ Mr Long. (người ở xa)',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['Hi, Nam.', 'Goodbye.', 'Yes, it is.'],
                                   'plain': True,
                                   'q': 'Hi, Mary. This is my friend Nam. – ___',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['Hello, Ms Hoa.', "It's Nam.", "I'm fine."],
                                   'plain': True,
                                   'q': "That's Ms Hoa. – ___",
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Yes, it is.', "I'm Long.", 'Goodbye.'],
                                   'plain': True,
                                   'q': 'Is that Mr Long? – ___',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ['no', 'Mr', 'Ms'], 'plain': True, 'q': '<span class="emo">👨</span>', 't': 'mcq'},
                                  {'id': 't1.6', 'o': ['yes', 'that', 'Ms'], 'plain': True, 'q': '<span class="emo">👩</span>', 't': 'mcq'},
                                  {'id': 't1.7', 'o': ['friend', 'teacher', 'this'], 'plain': True, 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['kia, cái kia (ở xa)', 'giáo viên', 'ông, thầy'],
                                   'plain': True,
                                   'q': 'Nghĩa của "Mr" là:',
                                   't': 'mcq'},
                                  {'id': 't1.9', 'o': ['nó', 'bạn', 'cô'], 'plain': True, 'q': 'Nghĩa của "Ms" là:', 't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ["I'm fine, thank you.", "No, it isn't. It's Minh.", 'Hi, Mary.'],
                                   'plain': True,
                                   'q': 'Bấm 🔊, nghe và chọn câu trả lời phù hợp.',
                                   'say': 'Is that Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'This is my {_} Nam. – Hi, Nam.', 't': 'fill'},
                                  {'id': 't1.12', 'q': "That's my teacher, {_} Hoa.", 't': 'fill'},
                                  {'id': 't1.13', 'q': 'Is that Mr Long? – {_}, it is.', 't': 'fill'},
                                  {'id': 't1.14', 'q': "Is this Lan? – {_}, it isn't. It's Mary.", 't': 'fill'},
                                  {'id': 't1.15', 'q': 'arehtce → {_}', 't': 'fill'},
                                  {'id': 't1.16', 'q': '', 't': 'order', 'words': ['it', "isn't.", 'No,']},
                                  {'id': 't1.17', 'q': '', 't': 'order', 'words': ['Mai?', 'Is', 'that']},
                                  {'id': 't1.18', 'q': '', 't': 'order', 'words': ['Ben.', 'you,', 'Thank']},
                                  {'id': 't1.19', 'q': '', 't': 'order', 'words': ['Long.', "That's", 'Mr']},
                                  {'id': 't1.20',
                                   'left': ['Is that Nam?', 'This is Mary.', "That's Mr Long.", 'How are you?'],
                                   'o': ["No, it isn't. It's Minh.", 'Hello, Mr Long.', 'Hi, Mary.', "I'm fine, thank you."],
                                   'q': 'Nối:',
                                   't': 'match'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 3 – Our friends: Kiểm tra 2',
 'unit': 3}
