# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['My father teaches at a primary school.'],
 't1.10': 'My sister is a teacher.',
 't1.11': 'on a farm',
 't1.12': ['He studies at a university.'],
 't1.13': 'How many people are there in her family?',
 't1.14': 'at a nursing home',
 't1.15': ['My grandfather works on a farm.'],
 't1.16': 'How many people are there in your family?',
 't1.17': 'does',
 't1.18': 'I live in Nguyen Kiem Street.',
 't1.19': 'have',
 't1.2': 'Mẹ tôi là nông dân.',
 't1.20': ['How many people are there in your family?'],
 't1.3': 'in an office',
 't1.4': 'Where',
 't1.5': ['There are five people in my family.'],
 't1.6': 'My mother works at a school.',
 't1.7': 'at a primary school',
 't1.8': 'factory',
 't1.9': ['My brother is a student.']}

EXPLANATIONS = {'t1.1': 'Câu đúng: My father teaches at a primary school.',
 't1.10': 'Đáp án: My sister is a teacher.',
 't1.11': 'Đáp án: on a farm',
 't1.12': 'Câu đúng: He studies at a university.',
 't1.13': 'Đáp án: How many people are there in her family?',
 't1.14': 'Đáp án: at a nursing home',
 't1.15': 'Câu đúng: My grandfather works on a farm.',
 't1.16': 'Đáp án: How many people are there in your family?',
 't1.17': 'Đáp án: does',
 't1.18': 'Đáp án: I live in Nguyen Kiem Street.',
 't1.19': 'Đáp án: have',
 't1.2': 'Đáp án: Mẹ tôi là nông dân.',
 't1.20': 'Câu đúng: How many people are there in your family?',
 't1.3': 'Đáp án: in an office',
 't1.4': 'Đáp án: Where',
 't1.5': 'Câu đúng: There are five people in my family.',
 't1.6': 'Đáp án: My mother works at a school.',
 't1.7': 'Đáp án: at a primary school',
 't1.8': 'Đáp án: factory',
 't1.9': 'Câu đúng: My brother is a student.'}
