# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': {'blanks': [['D'], ['A'], ['E'], ['C']]},
 'l2.2': 'F',
 'l2.3': 'F',
 'l2.4': 'T',
 'l2.5': 'T',
 'l3.6': ['factory'],
 'l3.7': ['small face'],
 'l3.8': ['swimming pool'],
 'l3.9': ['tug of war'],
 'r1.10': 'C',
 'r1.11': 'C',
 'r1.12': 'B',
 'r1.13': 'D',
 'r2.14': ['library'],
 'r2.15': ['straight'],
 'r2.16': ['left'],
 'r3.17': 'A',
 'r3.18': 'C',
 'r3.19': 'B',
 'w1.20': ['between'],
 'w1.21': ['playing tug of war'],
 'w1.22': ['ninety thousand dong', 'ninety thousand'],
 'w1.23': ['dance beautifully'],
 'w2.24': ['What do you do in the morning?'],
 'w2.25': ['I live at 12 Tran Hung Dao Street.', 'I live at 12 Tran Dung Dao Street.'],
 'w2.26': ['Do you want to go to the supermarket?'],
 'w3.27': ['I wash the clothes in the afternoon.'],
 'w3.28': ['He plays tennis on Saturdays.', 'My father plays tennis on Saturdays.'],
 'w3.29': ['They are building a campfire.']}

EXPLANATIONS = {'l1.1': 'Theo đáp án của đề: 1–D, 2–A, 3–E, 4–C (B là ví dụ số 0).',
 'l2.2': 'Đáp án: False (theo đáp án của đề).',
 'l2.3': 'Đáp án: False (theo đáp án của đề).',
 'l2.4': 'Đáp án: True (theo đáp án của đề).',
 'l2.5': 'Đáp án: True (theo đáp án của đề).',
 'l3.6': 'factory = nhà máy.',
 'l3.7': 'small face = khuôn mặt nhỏ.',
 'l3.8': 'swimming pool = bể bơi.',
 'l3.9': 'tug of war = kéo co.',
 'r1.10': 'eyes là danh từ; còn lại là tính từ.',
 'r1.11': 'weather là danh từ chung; còn lại là các kiểu thời tiết.',
 'r1.12': 'T-shirt là quần áo; còn lại là cửa hàng.',
 'r1.13': 'dance là động từ; còn lại là con vật.',
 'r2.14': 'Thư viện (library).',
 'r2.15': 'go straight = đi thẳng.',
 'r2.16': 'on the left = bên trái.',
 'r3.17': 'Đáp án: A. Yes, it is.',
 'r3.18': 'Đáp án: C. She is in the shopping centre with her mother.',
 'r3.19': 'Đáp án: B. Because her mother wants to buy clothes.',
 'w1.20': 'between … and … = ở giữa … và …',
 'w1.21': 'playing tug of war = chơi kéo co.',
 'w1.22': '90,000 đồng = ninety thousand dong.',
 'w1.23': 'Công múa đẹp: dance beautifully.',
 'w2.24': 'Câu đúng: What do you do in the morning?',
 'w2.25': 'Câu đúng: I live at 12 Tran Hung Dao Street.',
 'w2.26': 'Câu đúng: Do you want to go to the supermarket?',
 'w3.27': 'Câu đúng: I wash the clothes in the afternoon.',
 'w3.28': 'Câu đúng: He plays tennis on Saturdays.',
 'w3.29': 'Câu đúng: They are building a campfire.'}
