# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_dc2.py"""

SET = {'grade': 4,
 'id': 'lop4-dc2-c',
 'pages': [{'groups': [{'id': 'u11mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u11mcq.1', 'o': ['on', 'at', 'in'], 'q': 'I live ______ Tran Hung Dao Street.', 't': 'mcq'},
                                  {'id': 'u11mcq.2',
                                   'o': ['quiet', 'noisy', 'live'],
                                   'q': 'This is a very ______ road. Many cars and motorbikes go fast.',
                                   't': 'mcq'},
                                  {'id': 'u11mcq.3', 'o': ['in', 'live', 'street'], 'q': 'We ______ in a small house on Le Loi Street.', 't': 'mcq'},
                                  {'id': 'u11mcq.4',
                                   'o': ['quiet', 'noisy', 'busy'],
                                   'q': 'The street is ______ today. There is not much noise.',
                                   't': 'mcq'}]},
                       {'bank': ['busy', 'quiet', 'road', 'live', 'at'],
                        'id': 'u11fill',
                        'instr': 'Bài 4. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u11fill.5', 'q': 'I {_} in a small town.', 't': 'fill'},
                                  {'id': 'u11fill.6', 'q': 'My house is {_} 45 Le Loi Street.', 't': 'fill'},
                                  {'id': 'u11fill.7', 'q': 'We walk on the {_} to school.', 't': 'fill'},
                                  {'id': 'u11fill.8', 'q': 'The street is very {_} in the morning.', 't': 'fill'},
                                  {'id': 'u11fill.9', 'q': 'I like living in a {_} place.', 't': 'fill'}]},
                       {'id': 'u11order',
                        'instr': 'Bài 3. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u11order.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Street.', 'Trung', 'I', 'Ba', 'Hai', 'at', 'live']},
                                  {'id': 'u11order.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['a', 'This', 'street.', 'noisy', 'is']},
                                  {'id': 'u11order.12', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['big', 'is', 'a', 'There', 'school.']},
                                  {'id': 'u11order.13',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Road.', 'Hoang', 'Van', 'He', 'lives', 'Thu', 'on']},
                                  {'id': 'u11order.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['quiet.', 'very', 'street', 'The', 'is']}]},
                       {'bank': ['road', 'street', 'live', 'quiet', 'busy', 'noisy', 'big'],
                        'id': 'u11b5',
                        'instr': 'Bài 5. Read and Complete – điền từ trong khung vào chỗ trống (có 1 từ thừa): road, street, live, quiet, busy, noisy, big.',
                        'items': [{'id': 'u11b5.15', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'u11b5.16', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'u11b5.17', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'u11b5.18', 'q': 'Chỗ trống (4): {_}', 't': 'fill'},
                                  {'id': 'u11b5.19', 'q': 'Chỗ trống (5): {_}', 't': 'fill'}],
                        'passage': '<p>I <b>(1) ______</b> in a house on Hoa Binh Street. It’s a long and <b>(2) ______</b> street with many trees and shops. '
                                   'Sometimes the street is very <b>(3) ______</b> in the morning because there are many motorbikes and cars. But in the '
                                   'afternoon, it becomes <b>(4) ______</b> and peaceful. Near my house, there is a small <b>(5) ______</b> that leads to the '
                                   'park.</p>'}],
            'id': 'unit-11',
            'mode': 'practice',
            'title': 'Unit 11: My home'},
           {'groups': [{'id': 'u12mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u12mcq.20', 'o': ['nurse', 'farmer', 'actor'], 'q': 'My dad is a ______. He works on a farm.', 't': 'mcq'},
                                  {'id': 'u12mcq.21', 'o': ['factory', 'farm', 'hospital'], 'q': 'My uncle works in a ______. He makes cars.', 't': 'mcq'},
                                  {'id': 'u12mcq.22',
                                   'o': ['office worker', 'actor', 'nurse'],
                                   'q': 'A ______ takes care of sick people in a hospital.',
                                   't': 'mcq'},
                                  {'id': 'u12mcq.23',
                                   'o': ['farmer', 'nurse', 'policeman'],
                                   'q': 'My aunt is a ______. She helps old people in a nursing home.',
                                   't': 'mcq'},
                                  {'id': 'u12mcq.24', 'o': ['policeman', 'farmer', 'actor'], 'q': 'He is a ______. He catches thieves.', 't': 'mcq'}]},
                       {'id': 'u12match',
                        'instr': 'Bài 2. Match – nối từ/cụm từ với nghĩa hoặc nơi phù hợp.',
                        'items': [{'id': 'u12match.25',
                                   'left': [{'t': 'Actor'}, {'t': 'Farmer'}, {'t': 'Nurse'}, {'t': 'Office worker'}, {'t': 'Nurse (for elderly)'}],
                                   'o': ['Hospital', 'Nursing home', 'Theatre', 'Office', 'Farm'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'bank': ['hospital', 'actor', 'farmer', 'policeman', 'factory'],
                        'id': 'u12fill',
                        'instr': 'Bài 3. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u12fill.26', 'q': 'My grandfather was a {_}. He grew rice and vegetables.', 't': 'fill'},
                                  {'id': 'u12fill.27', 'q': 'I want to be an {_} and act in movies.', 't': 'fill'},
                                  {'id': 'u12fill.28', 'q': 'A {_} works to keep us safe.', 't': 'fill'},
                                  {'id': 'u12fill.29', 'q': 'My mother works in a {_}. She takes care of patients.', 't': 'fill'},
                                  {'id': 'u12fill.30', 'q': 'There are many workers in the {_} near my house.', 't': 'fill'}]},
                       {'id': 'u12order',
                        'instr': 'Bài 4. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u12order.31', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['nurse.', 'is', 'a', 'She']},
                                  {'id': 'u12order.32',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['factory.', 'in', 'brother', 'a', 'My', 'works']},
                                  {'id': 'u12order.33', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['dad', 'a', 'policeman.', 'is', 'My']}]},
                       {'id': 'u12b5',
                        'instr': 'Bài 5. Read & Choose – đọc đoạn văn và chọn đáp án đúng.',
                        'items': [{'id': 'u12b5.34', 'o': ['In a hospital', 'On a farm', 'In a factory'], 'q': 'Where does the dad work?', 't': 'mcq'},
                                  {'id': 'u12b5.35', 'o': ['Policeman', 'Office worker', 'Nurse'], 'q': 'Who helps sick people?', 't': 'mcq'},
                                  {'id': 'u12b5.36', 'o': ['Office worker', 'Actor', 'Farmer'], 'q': 'What does the uncle do?', 't': 'mcq'},
                                  {'id': 'u12b5.37', 'o': ['The cousin', 'The sister', 'The aunt'], 'q': 'Who wants to act in films?', 't': 'mcq'},
                                  {'id': 'u12b5.38', 'o': ['Make movies', 'Grow food', 'Keep the town safe'], 'q': 'What is the policeman’s job?', 't': 'mcq'}],
                        'passage': '<p>My family has many different jobs. My dad is a farmer. He works on a farm. He grows rice and vegetables. My aunt is a '
                                   'nurse. She works in a big hospital. She helps sick people every day. My uncle is an office worker. He works in a tall '
                                   'building and uses a computer. My cousin is a policeman. He works to keep the town safe. My sister wants to be an actor. '
                                   'She loves to act in plays and films. Everyone in my family has an interesting job!</p>'}],
            'id': 'unit-12',
            'mode': 'practice',
            'title': 'Unit 12: Jobs'},
           {'groups': [{'id': 'u13mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u13mcq.39',
                                   'o': ['short', 'tall', 'slim'],
                                   'q': 'My sister is very ______. She can reach the top shelf.',
                                   't': 'mcq'},
                                  {'id': 'u13mcq.40', 'o': ['short', 'big', 'long'], 'q': 'She has ______ hair. It goes down to her back.', 't': 'mcq'},
                                  {'id': 'u13mcq.41', 'o': ['slim', 'tall', 'round'], 'q': 'That boy is ______. He’s not fat at all.', 't': 'mcq'},
                                  {'id': 'u13mcq.42', 'o': ['eyes', 'face', 'hair'], 'q': 'His ______ is friendly and happy.', 't': 'mcq'}]},
                       {'id': 'u13match',
                        'instr': 'Bài 2. Match – nối từ/cụm từ với nghĩa hoặc nơi phù hợp.',
                        'items': [{'id': 'u13match.43',
                                   'left': [{'t': 'Slim'}, {'t': 'Eyes'}, {'t': 'Hair'}, {'t': 'Round'}, {'t': 'Face'}],
                                   'o': ['A head with two eyes and a nose',
                                         'Not fat, small body',
                                         'You see with them',
                                         'Not square, like a circle',
                                         'On your head, can be long/short'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'bank': ['short', 'big', 'hair', 'tall', 'round'],
                        'id': 'u13fill',
                        'instr': 'Bài 3. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u13fill.44', 'q': 'My brother is very {_}. I am much smaller.', 't': 'fill'},
                                  {'id': 'u13fill.45', 'q': 'She has {_} eyes. They are very beautiful.', 't': 'fill'},
                                  {'id': 'u13fill.46', 'q': 'He has black {_}.', 't': 'fill'},
                                  {'id': 'u13fill.47', 'q': 'My little cousin is very {_}. He’s just five years old!', 't': 'fill'},
                                  {'id': 'u13fill.48', 'q': 'Her face is {_} like a ball.', 't': 'fill'}]},
                       {'id': 'u13order',
                        'instr': 'Bài 4. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u13order.49', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['round', 'She', 'a', 'face.', 'has']},
                                  {'id': 'u13order.50', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['has', 'hair.', 'long', 'He']},
                                  {'id': 'u13order.51', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Her', 'eyes', 'big.', 'are']},
                                  {'id': 'u13order.52', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'very', 'She', 'slim.']},
                                  {'id': 'u13order.53', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['brother', 'My', 'is', 'short.']}]},
                       {'id': 'u13b5',
                        'instr': 'Bài 5. Read & Choose – đọc đoạn văn và chọn đáp án đúng.',
                        'items': [{'id': 'u13b5.54', 'o': ['Nine', 'Ten', 'Eleven'], 'q': 'How old is Linh?', 't': 'mcq'},
                                  {'id': 'u13b5.55', 'o': ['Short and fat', 'Tall and slim', 'Big and round'], 'q': 'What does she look like?', 't': 'mcq'},
                                  {'id': 'u13b5.56', 'o': ['Black', 'Brown', 'Yellow'], 'q': 'What color is her hair?', 't': 'mcq'},
                                  {'id': 'u13b5.57',
                                   'o': ['Reads books', 'Draws pictures', 'Helps her mom'],
                                   'q': 'What does she do in the morning?',
                                   't': 'mcq'},
                                  {'id': 'u13b5.58',
                                   'o': ['Helps her mom', 'Watches TV', 'Reads books or draws'],
                                   'q': 'What does she do in the evening?',
                                   't': 'mcq'}],
                        'passage': '<p>This is my sister. Her name is Linh. She is ten years old. Linh is tall and slim. She has long black hair and a round '
                                   'face. Her eyes are big and brown, and she has a small nose. Linh is very kind and friendly. Every morning, she helps my '
                                   'mom clean the floor and wash the dishes. In the evening, she reads books or draws pictures. She is my best friend at '
                                   'home.</p>'}],
            'id': 'unit-13',
            'mode': 'practice',
            'title': 'Unit 13: Appearance'},
           {'groups': [{'id': 'u14mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u14mcq.59', 'o': ['evening', 'morning', 'noon'], 'q': 'I go to school in the ______.', 't': 'mcq'},
                                  {'id': 'u14mcq.60', 'o': ['afternoon', 'noon', 'evening'], 'q': 'My mom makes dinner in the ______.', 't': 'mcq'},
                                  {'id': 'u14mcq.61', 'o': ['morning', 'afternoon', 'noon'], 'q': 'We have lunch at ______.', 't': 'mcq'},
                                  {'id': 'u14mcq.62', 'o': ['wash the dishes', 'morning', 'evening'], 'q': 'I ______ every Sunday to help my mom.', 't': 'mcq'},
                                  {'id': 'u14mcq.63', 'o': ['clean', 'help', 'wash'], 'q': 'My sister and I ______ the floor at home.', 't': 'mcq'}]},
                       {'id': 'u14match',
                        'instr': 'Bài 2. Match – nối từ/cụm từ với nghĩa hoặc nơi phù hợp.',
                        'items': [{'id': 'u14match.64',
                                   'left': [{'t': 'Morning'}, {'t': 'Afternoon'}, {'t': 'Clean the floor'}, {'t': 'Help with the cooking'}, {'t': 'Evening'}],
                                   'o': ['Time after lunch but before dinner',
                                         'You do this to make the floor tidy',
                                         'Time when the sun rises',
                                         'Time when it gets dark, dinner time',
                                         'You do this with your mom in the kitchen'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'bank': ['morning', 'noon', 'help with the cooking', 'wash', 'clean'],
                        'id': 'u14fill',
                        'instr': 'Bài 3. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u14fill.65', 'q': 'I always wake up early in the {_}.', 't': 'fill'},
                                  {'id': 'u14fill.66', 'q': 'We eat lunch at {_}.', 't': 'fill'},
                                  {'id': 'u14fill.67', 'q': 'I often {_} the dishes after dinner.', 't': 'fill'},
                                  {'id': 'u14fill.68', 'q': 'My brother and I {_} with the cooking on Sunday.', 't': 'fill'},
                                  {'id': 'u14fill.69', 'q': 'Don’t forget to {_} the floor, it’s dirty!', 't': 'fill'}]},
                       {'id': 'u14order',
                        'instr': 'Bài 4. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u14order.70',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['early', 'get', 'morning.', 'up', 'I', 'in', 'the']},
                                  {'id': 'u14order.71', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['dad', 'the', 'with', 'help', 'cooking.', 'I']},
                                  {'id': 'u14order.72', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['She', 'always', 'the', 'dishes.', 'washes']},
                                  {'id': 'u14order.73', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['floor.', 'the', 'clean', 'They']},
                                  {'id': 'u14order.74',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['afternoon.', 'in', 'go', 'shopping', 'I', 'the']}]},
                       {'bank': ['morning', 'noon', 'evening', 'clean the floor', 'wash the clothes', 'wash the dishes', 'help with the cooking'],
                        'id': 'u14b5',
                        'instr': 'Bài 5. Fill in the Blanks – hoàn thành hội thoại bằng các cụm trong khung.',
                        'items': [{'id': 'u14b5.75', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'u14b5.76', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'u14b5.77', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'u14b5.78', 'q': 'Chỗ trống (4): {_}', 't': 'fill'},
                                  {'id': 'u14b5.79', 'q': 'Chỗ trống (5): {_}', 't': 'fill'},
                                  {'id': 'u14b5.80', 'q': 'Chỗ trống (6): {_}', 't': 'fill'},
                                  {'id': 'u14b5.81', 'q': 'Chỗ trống (7): {_}', 't': 'fill'}],
                        'passage': '<p>Nam: What do you usually do in the <b>(1) ______</b> ?<br>Mai: I often <b>(2) ______</b> with my mom.<br>Nam: Nice! '
                                   'What about at <b>(3) ______</b> ?<br>Mai: I <b>(4) ______</b> . After lunch, I take a nap.<br>Nam: And in the <b>(5) '
                                   '______</b> ?<br>Mai: I <b>(6) ______</b> before dinner.<br>Nam: Do you do anything at night?<br>Mai: Yes, I <b>(7) '
                                   '______</b> after dinner. Then I watch TV!</p>'}],
            'id': 'unit-14',
            'mode': 'practice',
            'title': 'Unit 14: Daily activities'},
           {'groups': [{'id': 'u15mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u15mcq.82',
                                   'o': ['shopping centre', 'sports centre', 'cinema'],
                                   'q': 'We go to the ______ to watch movies.',
                                   't': 'mcq'},
                                  {'id': 'u15mcq.83',
                                   'o': ['do yoga', 'cook meals', 'play tennis'],
                                   'q': 'She loves to ______. She makes rice and vegetables.',
                                   't': 'mcq'},
                                  {'id': 'u15mcq.84',
                                   'o': ['watch films', 'do yoga', 'swim'],
                                   'q': 'My brother and I ______ at the weekend. We love action movies!',
                                   't': 'mcq'},
                                  {'id': 'u15mcq.85',
                                   'o': ['cinema', 'sports centre', 'swimming pool'],
                                   'q': 'You can play basketball or badminton at the ______.',
                                   't': 'mcq'},
                                  {'id': 'u15mcq.86',
                                   'o': ['shopping centre', 'sports centre', 'swimming pool'],
                                   'q': 'My mom goes to the ______ to buy clothes.',
                                   't': 'mcq'}]},
                       {'id': 'u15match',
                        'instr': 'Bài 2. Match – nối từ/cụm từ với nghĩa hoặc nơi phù hợp.',
                        'items': [{'id': 'u15match.87',
                                   'left': [{'t': 'Watch films'}, {'t': 'Play tennis'}, {'t': 'Cook meals'}, {'t': 'Go swimming'}],
                                   'o': ['Swimming pool', 'Sports centre', 'Shopping centre', 'Kitchen', 'Cinema'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'bank': ['do yoga', 'shopping centre', 'cook meals', 'cinema', 'play tennis'],
                        'id': 'u15fill',
                        'instr': 'Bài 3. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u15fill.88', 'q': 'My family goes to the {_} every Saturday to buy food.', 't': 'fill'},
                                  {'id': 'u15fill.89', 'q': 'I like to {_} with my dad. We hit the ball over the net!', 't': 'fill'},
                                  {'id': 'u15fill.90', 'q': 'My aunt can {_} very well. She makes yummy food.', 't': 'fill'},
                                  {'id': 'u15fill.91', 'q': 'Every Sunday, my sister and I {_} with Mom at home.', 't': 'fill'},
                                  {'id': 'u15fill.92', 'q': 'I watch cartoons at the {_}.', 't': 'fill'}]},
                       {'id': 'u15order',
                        'instr': 'Bài 4. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u15order.93', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'I', 'cinema.', 'often', 'the', 'go']},
                                  {'id': 'u15order.94', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'They', 'yoga', 'morning.', 'the', 'do']},
                                  {'id': 'u15order.95',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['dinner.', 'always', 'for', 'We', 'cook', 'meals']},
                                  {'id': 'u15order.96',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['play', 'at', 'I', 'tennis', 'sports', 'the', 'centre.']},
                                  {'id': 'u15order.97',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['to', 'go', 'pool.', 'the', 'We', 'swimming']}]}],
            'id': 'unit-15',
            'mode': 'practice',
            'title': "Unit 15: My family's weekends"},
           {'groups': [{'id': 'u16mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u16mcq.98', 'o': ['windy', 'sunny', 'cloudy'], 'q': 'Today is ______. Let’s wear sunglasses!', 't': 'mcq'},
                                  {'id': 'u16mcq.99', 'o': ['bookshop', 'bakery', 'weather'], 'q': 'When the ______ is bad, we stay at home.', 't': 'mcq'},
                                  {'id': 'u16mcq.100', 'o': ['bakery', 'food stall', 'supermarket'], 'q': 'I buy fresh bread at the ______.', 't': 'mcq'},
                                  {'id': 'u16mcq.101', 'o': ['sunny', 'rainy', 'windy'], 'q': 'It’s ______. Let’s bring an umbrella!', 't': 'mcq'},
                                  {'id': 'u16mcq.102', 'o': ['water park', 'bookshop', 'bakery'], 'q': 'I go to the ______ to buy books.', 't': 'mcq'}]},
                       {'id': 'u16match',
                        'instr': 'Bài 2. Match – nối từ/cụm từ với nghĩa hoặc nơi phù hợp.',
                        'items': [{'id': 'u16match.103',
                                   'left': [{'t': 'Rainy'}, {'t': 'Supermarket'}, {'t': 'Bookshop'}, {'t': 'Water park'}, {'t': 'Windy'}],
                                   'o': ['A place with many books to buy',
                                         'Weather with lots of rain',
                                         'A place to buy many kinds of food',
                                         'A fun place to swim and play in water',
                                         'Weather with strong air moving'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'bank': ['windy', 'supermarket', 'food stall', 'cloudy', 'water park'],
                        'id': 'u16fill',
                        'instr': 'Bài 3. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u16fill.104', 'q': 'It’s very {_} today. My hat is flying away!', 't': 'fill'},
                                  {'id': 'u16fill.105', 'q': 'My mom buys milk and eggs at the {_}.', 't': 'fill'},
                                  {'id': 'u16fill.106', 'q': 'We eat noodles at the {_} near school.', 't': 'fill'},
                                  {'id': 'u16fill.107', 'q': 'It’s {_}, I can’t see the sun.', 't': 'fill'},
                                  {'id': 'u16fill.108', 'q': 'Let’s go to the {_} and play in the slides!', 't': 'fill'}]},
                       {'id': 'u16order',
                        'instr': 'Bài 4. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u16order.109',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['bakery', 'to', 'every', 'the', 'I', 'go', 'morning.']},
                                  {'id': 'u16order.110', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['weather', 'is', 'today.', 'sunny', 'The']},
                                  {'id': 'u16order.111',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['buy', 'the', 'books', 'I', 'bookshop.', 'at']},
                                  {'id': 'u16order.112', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['today.', 'very', 'It', 'is', 'windy']},
                                  {'id': 'u16order.113',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['We', 'the', 'food', 'at', 'stall.', 'noodles', 'eat']}]},
                       {'bank': ['cloudy', 'bookshop', 'supermarket', 'food stall', 'windy'],
                        'id': 'u16b5',
                        'instr': 'Bài 5. Spot the Mistake – tìm từ sai trong câu và viết từ đúng (gợi ý: cloudy, bookshop, supermarket, food stall, windy).',
                        'items': [{'id': 'u16b5.114', 'q': 'Tìm từ sai và sửa lại: <i>Today is cloud, so I need an umbrella.</i><br>Từ đúng: {_}', 't': 'fill'},
                                  {'id': 'u16b5.115',
                                   'q': 'Tìm từ sai và sửa lại: <i>I want to read a new book, so I go to the bakery.</i><br>Từ đúng: {_}',
                                   't': 'fill'},
                                  {'id': 'u16b5.116',
                                   'q': 'Tìm từ sai và sửa lại: <i>My mom buys food at the water park every morning.</i><br>Từ đúng: {_}',
                                   't': 'fill'},
                                  {'id': 'u16b5.117',
                                   'q': 'Tìm từ sai và sửa lại: <i>We’re hungry, so we go to the bookshop to eat noodles.</i><br>Từ đúng: {_}',
                                   't': 'fill'}]}],
            'id': 'unit-16',
            'mode': 'practice',
            'title': 'Unit 16: Weather'},
           {'groups': [{'id': 'u17mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u17mcq.118', 'o': ['straight', 'round', 'stop'], 'q': 'Go ______, then turn left.', 't': 'mcq'},
                                  {'id': 'u17mcq.119', 'o': ['turn', 'stop', 'go'], 'q': 'Don’t ______ at the red light!', 't': 'mcq'},
                                  {'id': 'u17mcq.120', 'o': ['get to', 'turn', 'left'], 'q': 'I want to ______ the zoo. How do I go?', 't': 'mcq'},
                                  {'id': 'u17mcq.121', 'o': ['stop', 'right', 'go'], 'q': 'The shop is on your ______.', 't': 'mcq'}]},
                       {'id': 'u17match',
                        'instr': 'Bài 2. Match – nối từ/cụm từ với nghĩa hoặc nơi phù hợp.',
                        'items': [{'id': 'u17match.122',
                                   'left': [{'t': 'Turn right'}, {'t': 'Go straight'}, {'t': 'Stop'}, {'t': 'Turn round'}, {'t': 'Turn left'}],
                                   'o': ['Walk without turning',
                                         'Move in the opposite direction',
                                         'Turn to your right side',
                                         'Don’t move anymore',
                                         'Turn to your left side'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'bank': ['turn', 'get', 'stop', 'right', 'go straight'],
                        'id': 'u17fill',
                        'instr': 'Bài 3. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u17fill.123', 'q': '{_} at the traffic lights, then you’ll see the cinema.', 't': 'fill'},
                                  {'id': 'u17fill.124', 'q': 'You can {_} to the park in five minutes.', 't': 'fill'},
                                  {'id': 'u17fill.125', 'q': '{_} and then turn left at the bakery.', 't': 'fill'},
                                  {'id': 'u17fill.126', 'q': 'Please {_}! There’s a red light.', 't': 'fill'},
                                  {'id': 'u17fill.127', 'q': 'Don’t turn left! Turn {_}!', 't': 'fill'}]},
                       {'id': 'u17order',
                        'instr': 'Bài 4. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u17order.128', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Go', 'turn', 'straight', 'left.', 'and']},
                                  {'id': 'u17order.129', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'bookstore.', 'Turn', 'at', 'right']},
                                  {'id': 'u17order.130', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['light.', 'Stop', 'the', 'red', 'at']},
                                  {'id': 'u17order.131',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'to', 'get', 'want', 'I', 'to', 'zoo.']},
                                  {'id': 'u17order.132', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['round.', 'can', 'You', 'turn']}]},
                       {'id': 'u17b5',
                        'instr': 'Bài 5. Secret Code – giải mã chỉ dẫn (GS = go straight, TL = turn left, TR = turn right, ST = stop, TT = turn round, GT = '
                                 'get to). Tự viết, xem đáp án mẫu.',
                        'items': [{'id': 'u17b5.133', 'q': 'GS → GS → TR → ST → GT the zoo.', 't': 'open'},
                                  {'id': 'u17b5.134', 'q': 'GS → TL → GS → TT → GT the bakery.', 't': 'open'},
                                  {'id': 'u17b5.135', 'q': 'GS → GS → TR → TL → ST.', 't': 'open'},
                                  {'id': 'u17b5.136', 'q': 'GS → TL → GS → TR → GT the hospital.', 't': 'open'},
                                  {'id': 'u17b5.137', 'q': 'TR → GS → ST → TT → GT the supermarket.', 't': 'open'}]}],
            'id': 'unit-17',
            'mode': 'practice',
            'title': 'Unit 17: In the city'},
           {'groups': [{'id': 'u18mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u18mcq.138',
                                   'o': ['behind', 'between', 'opposite'],
                                   'q': 'The bakery is ______ the school and the post office.',
                                   't': 'mcq'},
                                  {'id': 'u18mcq.139',
                                   'o': ['near', 'opposite', 'behind'],
                                   'q': 'The gift shop is ______ the museum. It’s across the street.',
                                   't': 'mcq'},
                                  {'id': 'u18mcq.140', 'o': ['skirt', 'dong', 'thousand'], 'q': 'That red ______ is beautiful.', 't': 'mcq'},
                                  {'id': 'u18mcq.141', 'o': ['dollar', 'dong', 'yen'], 'q': 'How much is this T-shirt? – It’s 100,000 ______.', 't': 'mcq'},
                                  {'id': 'u18mcq.142',
                                   'o': ['behind', 'opposite', 'near'],
                                   'q': 'The park is ______ the supermarket. They are close together.',
                                   't': 'mcq'}]},
                       {'id': 'u18match',
                        'instr': 'Bài 2. Match – nối từ/cụm từ với nghĩa hoặc nơi phù hợp.',
                        'items': [{'id': 'u18match.143',
                                   'left': [{'t': 'Behind'}, {'t': 'Gift shop'}, {'t': 'Skirt'}, {'t': 'Thousand'}, {'t': 'Opposite'}],
                                   'o': ['A place to buy small presents',
                                         'At the back of something',
                                         'A piece of clothing worn by girls',
                                         '1,000',
                                         'Across from, facing something'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'bank': ['skirt', 'opposite', 'thousand', 'gift shop', 'behind'],
                        'id': 'u18fill',
                        'instr': 'Bài 3. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u18fill.144', 'q': 'There’s a {_} next to the bookstore. I want to buy a postcard.', 't': 'fill'},
                                  {'id': 'u18fill.145', 'q': 'The toy shop is {_} the post office.', 't': 'fill'},
                                  {'id': 'u18fill.146', 'q': 'I want to buy that pink {_} for my sister.', 't': 'fill'},
                                  {'id': 'u18fill.147', 'q': 'The supermarket is {_} the hospital.', 't': 'fill'},
                                  {'id': 'u18fill.148', 'q': 'This dress is two hundred {_} dong.', 't': 'fill'}]},
                       {'id': 'u18order',
                        'instr': 'Bài 4. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u18order.149', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'much', 'skirt?', 'How', 'the']},
                                  {'id': 'u18order.150', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['T-shirt.', 'that', 'I', 'want', 'to', 'buy']},
                                  {'id': 'u18order.151',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['The', 'school.', 'near', 'shop', 'the', 'gift', 'is']},
                                  {'id': 'u18order.152', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['thousand', 'one', 'dong.', 'costs', 'It']}]},
                       {'id': 'u18b5',
                        'instr': 'Bài 5. Read and Complete – đọc đoạn văn rồi điền từ vào chỗ trống (khung từ: T-shirt, skirt, thousand).',
                        'items': [{'id': 'u18b5.153', 'q': 'The price is 100 {_} dong.', 't': 'fill'},
                                  {'id': 'u18b5.154', 'q': 'The girl is standing {_} the gift shop.', 't': 'fill'},
                                  {'id': 'u18b5.155', 'q': 'The food stall is {_} the gift shop and the bookshop.', 't': 'fill'}],
                        'passage': '<p>This is a picture of a busy street. There is a gift shop on the left. A girl is standing opposite the shop. She is '
                                   'wearing a pink …… …… and a white …… …… . There is a price tag on her clothes. It says &quot;100 …… …… dong.&quot; Behind '
                                   'the girl, there is a bookshop. Between the shops, there is a small food stall.</p>'}],
            'id': 'unit-18',
            'mode': 'practice',
            'title': 'Unit 18: At the shopping centre'},
           {'groups': [{'id': 'u19mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u19mcq.156', 'o': ['sing', 'roar', 'dance'], 'q': 'The lion can ______ very loudly.', 't': 'mcq'},
                                  {'id': 'u19mcq.157', 'o': ['roar', 'tail', 'neck'], 'q': 'The giraffe has a long ______.', 't': 'mcq'},
                                  {'id': 'u19mcq.158', 'o': ['loudly', 'quickly', 'merrily'], 'q': 'The hippo is running ______ to the water.', 't': 'mcq'},
                                  {'id': 'u19mcq.159',
                                   'o': ['quickly', 'beautifully', 'merrily'],
                                   'q': 'Crocodiles live in the river and swim very ______.',
                                   't': 'mcq'},
                                  {'id': 'u19mcq.160', 'o': ['roar', 'loudly', 'merrily'], 'q': 'The children are dancing ______ on stage.', 't': 'mcq'}]},
                       {'id': 'u19match',
                        'instr': 'Bài 2. Match – nối từ/cụm từ với nghĩa hoặc nơi phù hợp.',
                        'items': [{'id': 'u19match.161',
                                   'left': [{'t': 'Loudly'}, {'t': 'Giraffe'}, {'t': 'Hippo'}, {'t': 'Crocodile'}, {'t': 'Merrily'}],
                                   'o': ['A big animal with a huge mouth in rivers',
                                         'Making a lot of noise',
                                         'Animal with a long neck',
                                         'A big reptile with strong jaws',
                                         'In a happy and cheerful way'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'bank': ['loudly', 'roar', 'giraffe', 'beautifully', 'crocodile'],
                        'id': 'u19fill',
                        'instr': 'Bài 3. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u19fill.162', 'q': 'The lion can {_} when it’s angry.', 't': 'fill'},
                                  {'id': 'u19fill.163', 'q': 'My sister sings very {_} in the school show.', 't': 'fill'},
                                  {'id': 'u19fill.164', 'q': 'That tall animal is a {_}.', 't': 'fill'},
                                  {'id': 'u19fill.165', 'q': 'The {_} swims in the river.', 't': 'fill'},
                                  {'id': 'u19fill.166', 'q': 'The children are singing {_} in the zoo event.', 't': 'fill'}]},
                       {'id': 'u19order',
                        'instr': 'Bài 4. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u19order.167', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['The', 'loudly.', 'roared', 'lion']},
                                  {'id': 'u19order.168', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['run', 'can', 'quickly.', 'Hippos']},
                                  {'id': 'u19order.169', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sang', 'The', 'beautifully.', 'bird']},
                                  {'id': 'u19order.170',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['merrily.', 'children', 'The', 'are', 'dancing']},
                                  {'id': 'u19order.171', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['We', 'crocodile.', 'the', 'saw']}]}],
            'id': 'unit-19',
            'mode': 'practice',
            'title': 'Unit 19: The animal world'},
           {'groups': [{'id': 'u20mcq',
                        'instr': 'Bài 1. Multiple Choice – chọn đáp án đúng A, B hoặc C.',
                        'items': [{'id': 'u20mcq.172',
                                   'o': ['put up a tent', 'built a campfire', 'took a photo'],
                                   'q': 'We ______ under the stars and stayed warm.',
                                   't': 'mcq'},
                                  {'id': 'u20mcq.173',
                                   'o': ['play card games', 'sing songs', 'tell a story'],
                                   'q': 'I love to ______ with my friends. Uno is my favorite!',
                                   't': 'mcq'},
                                  {'id': 'u20mcq.174',
                                   'o': ['build a campfire', 'put up a tent', 'take a photo'],
                                   'q': 'Dad helped me ______ next to the tree.',
                                   't': 'mcq'},
                                  {'id': 'u20mcq.175',
                                   'o': ['play card games', 'sing songs', 'build a campfire'],
                                   'q': 'Let’s ______ around the fire tonight.',
                                   't': 'mcq'},
                                  {'id': 'u20mcq.176',
                                   'o': ['sang songs', 'told a story', 'took a photo'],
                                   'q': 'We ______ of the mountains. It was beautiful!',
                                   't': 'mcq'}]},
                       {'id': 'u20match',
                        'instr': 'Bài 2. Match – nối từ/cụm từ với nghĩa hoặc nơi phù hợp.',
                        'items': [{'id': 'u20match.177',
                                   'left': [{'t': 'Build a campfire'},
                                            {'t': 'Take a photo'},
                                            {'t': 'Put up a tent'},
                                            {'t': 'Tell a story'},
                                            {'t': 'Play card games'}],
                                   'o': ['Tell a fun tale, maybe with a flashlight',
                                         'Set up something to sleep in outdoors',
                                         'Use wood to make fire',
                                         'Use a camera to capture a moment',
                                         'Use cards to play with friends'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'bank': ['sing songs', 'play card games', 'tell a story', 'build a campfire', 'put up a tent'],
                        'id': 'u20fill',
                        'instr': 'Bài 3. Fill in the blanks – điền từ thích hợp vào chỗ trống.',
                        'items': [{'id': 'u20fill.178', 'q': 'At night, we sat in a circle to {_}.', 't': 'fill'},
                                  {'id': 'u20fill.179', 'q': 'Let’s {_} and roast marshmallows!', 't': 'fill'},
                                  {'id': 'u20fill.180', 'q': 'My brother and I {_} before going to bed.', 't': 'fill'},
                                  {'id': 'u20fill.181', 'q': 'We all helped Dad {_} behind the tree.', 't': 'fill'},
                                  {'id': 'u20fill.182', 'q': 'Grandma loves to {_} when we go camping.', 't': 'fill'}]},
                       {'id': 'u20order',
                        'instr': 'Bài 4. Reorder the words – sắp xếp các từ thành câu đúng.',
                        'items': [{'id': 'u20order.183', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['put', 'They', 'a', 'tent.', 'up']},
                                  {'id': 'u20order.184', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['games.', 'We', 'played', 'card']},
                                  {'id': 'u20order.185',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['of', 'mountain.', 'the', 'a', 'I', 'photo', 'took']},
                                  {'id': 'u20order.186',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['They', 'sang', 'songs', 'the', 'around', 'campfire.']},
                                  {'id': 'u20order.187', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['story.', 'He', 'a', 'funny', 'told']}]},
                       {'id': 'u20b5',
                        'instr': 'Bài 5. Find the Mistake – tìm lỗi sai và viết lại cả câu cho đúng.',
                        'items': [{'id': 'u20b5.188', 'q': 'Sửa lỗi sai: <i>We build a photo of the mountains.</i><br>{_}', 't': 'fill'},
                                  {'id': 'u20b5.189', 'q': 'Sửa lỗi sai: <i>My brother play card game by himself.</i><br>{_}', 't': 'fill'},
                                  {'id': 'u20b5.190', 'q': 'Sửa lỗi sai: <i>They puts up a tent next to the river.</i><br>{_}', 't': 'fill'},
                                  {'id': 'u20b5.191', 'q': 'Sửa lỗi sai: <i>We sat by the fire and tell a stories.</i><br>{_}', 't': 'fill'},
                                  {'id': 'u20b5.192', 'q': 'Sửa lỗi sai: <i>Every night, we sing song around the campfire.</i><br>{_}', 't': 'fill'}]}],
            'id': 'unit-20',
            'mode': 'practice',
            'title': 'Unit 20: At summer camp'}],
 'theory': '<h3>Đề cương ôn tập HK2 năm học 2025–2026 – Tiếng Anh 4</h3><p>Tài liệu chỉ gồm bài tập theo từng Unit. Bảng dưới là từ vựng/cụm từ cùng nghĩa '
           'hoặc mô tả lấy từ Bài 2 (Match) của mỗi Unit.</p><h3>Unit 11: My home</h3><p>Từ cần nhớ: road, street, big, busy, quiet, noisy, live, at, '
           'in.</p><h3>Unit 12: Jobs</h3><table '
           'class="tb"><tr><td><b>Actor</b></td><td>Theatre</td></tr><tr><td><b>Farmer</b></td><td>Farm</td></tr><tr><td><b>Nurse</b></td><td>Hospital</td></tr><tr><td><b>Office '
           'worker</b></td><td>Office</td></tr><tr><td><b>Nurse (for elderly)</b></td><td>Nursing home</td></tr></table><h3>Unit 13: Appearance</h3><table '
           'class="tb"><tr><td><b>Slim</b></td><td>Not fat, small body</td></tr><tr><td><b>Eyes</b></td><td>You see with '
           'them</td></tr><tr><td><b>Hair</b></td><td>On your head, can be long/short</td></tr><tr><td><b>Round</b></td><td>Not square, like a '
           'circle</td></tr><tr><td><b>Face</b></td><td>A head with two eyes and a nose</td></tr></table><h3>Unit 14: Daily activities</h3><table '
           'class="tb"><tr><td><b>Morning</b></td><td>Time when the sun rises</td></tr><tr><td><b>Afternoon</b></td><td>Time after lunch but before '
           'dinner</td></tr><tr><td><b>Clean the floor</b></td><td>You do this to make the floor tidy</td></tr><tr><td><b>Help with the '
           'cooking</b></td><td>You do this with your mom in the kitchen</td></tr><tr><td><b>Evening</b></td><td>Time when it gets dark, dinner '
           'time</td></tr></table><h3>Unit 15: My family\'s weekends</h3><table class="tb"><tr><td><b>Watch films</b></td><td>Cinema</td></tr><tr><td><b>Play '
           'tennis</b></td><td>Sports centre</td></tr><tr><td><b>Cook meals</b></td><td>Kitchen</td></tr><tr><td><b>Go swimming</b></td><td>Swimming '
           'pool</td></tr></table><h3>Unit 16: Weather</h3><table class="tb"><tr><td><b>Rainy</b></td><td>Weather with lots of '
           'rain</td></tr><tr><td><b>Supermarket</b></td><td>A place to buy many kinds of food</td></tr><tr><td><b>Bookshop</b></td><td>A place with many '
           'books to buy</td></tr><tr><td><b>Water park</b></td><td>A fun place to swim and play in water</td></tr><tr><td><b>Windy</b></td><td>Weather with '
           'strong air moving</td></tr></table><h3>Unit 17: In the city</h3><table class="tb"><tr><td><b>Turn right</b></td><td>Turn to your right '
           'side</td></tr><tr><td><b>Go straight</b></td><td>Walk without turning</td></tr><tr><td><b>Stop</b></td><td>Don’t move '
           'anymore</td></tr><tr><td><b>Turn round</b></td><td>Move in the opposite direction</td></tr><tr><td><b>Turn left</b></td><td>Turn to your left '
           'side</td></tr></table><h3>Unit 18: At the shopping centre</h3><table class="tb"><tr><td><b>Behind</b></td><td>At the back of '
           'something</td></tr><tr><td><b>Gift shop</b></td><td>A place to buy small presents</td></tr><tr><td><b>Skirt</b></td><td>A piece of clothing worn '
           'by girls</td></tr><tr><td><b>Thousand</b></td><td>1,000</td></tr><tr><td><b>Opposite</b></td><td>Across from, facing '
           'something</td></tr></table><h3>Unit 19: The animal world</h3><table class="tb"><tr><td><b>Loudly</b></td><td>Making a lot of '
           'noise</td></tr><tr><td><b>Giraffe</b></td><td>Animal with a long neck</td></tr><tr><td><b>Hippo</b></td><td>A big animal with a huge mouth in '
           'rivers</td></tr><tr><td><b>Crocodile</b></td><td>A big reptile with strong jaws</td></tr><tr><td><b>Merrily</b></td><td>In a happy and cheerful '
           'way</td></tr></table><h3>Unit 20: At summer camp</h3><table class="tb"><tr><td><b>Build a campfire</b></td><td>Use wood to make '
           'fire</td></tr><tr><td><b>Take a photo</b></td><td>Use a camera to capture a moment</td></tr><tr><td><b>Put up a tent</b></td><td>Set up something '
           'to sleep in outdoors</td></tr><tr><td><b>Tell a story</b></td><td>Tell a fun tale, maybe with a flashlight</td></tr><tr><td><b>Play card '
           'games</b></td><td>Use cards to play with friends</td></tr></table>',
 'title': 'Đề cương HK2 (25-26) C – Bài tập theo Unit 11–20',
 'unit': 'DeCuongHK2'}
