# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u20-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['Where are you, Minh?', 'What does it say?', 'What is he doing?', 'What are they doing?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi một người nào đó đang làm gì?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['Where are Nam and Minh?', 'Is Nam there?', "Where's Nam?", 'What is Nam doing?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi một người nào đó đang ở đâu?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['What are you doing, Minh?', 'What are they doing?', 'Where are they, Minh?', 'Are Nam and Minh there?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi một nhóm người nào đó đang làm gì?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ["Where's Mai?", 'What are they doing?', "What's Mai doing?", "What's he doing?"],
                                   'plain': True,
                                   'q': 'Câu: “She\'s singing." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['Where are Mai and Lan?', 'Are Mai and Lan at the campsite?', 'What are Mai and Lan doing?', "What's Nam doing?"],
                                   'plain': True,
                                   'q': 'Câu “They are playing tug of war" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ["She's dancing.", "He's playing guitar.", "They're at the campsite.", "They're singing songs."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What are they doing?”',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ["She's dancing.", 'Yes, she is.', "She's at the campsite.", "She's taking a photo."],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “Where's Lan?”",
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ["She's putting up a tent.", "He's buiding a campfire.", "They're telling a story.", "They're putting up a tent."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Họ đang dựng lều.”',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['They are at the campsite.',
                                         'They are building a campfire.',
                                         'They are putting up a tent.',
                                         'They are playing card games.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Họ đang đốt lửa trại.”',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Họ đang nhảy múa ở khu cắm trại.', 'Họ đang đốt lửa trại.', 'Họ đang dựng lều.', 'Họ đang nhảy múa quanh lửa trại.'],
                                   'plain': True,
                                   'q': 'Câu: “They are dancing around the campfire.” có nghĩa là:',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['is', "isn't", 'do', 'does'], 'plain': True, 'q': 'A: Hi, Lan. Is Minh there?', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['Where', 'What', 'When', 'How'], 'plain': True, 'q': 'A: ____________ is he doing?', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: What ___________ Nam and Minh doing?', 't': 'mcq'},
                                  {'id': 'b.4',
                                   'o': ['she is', 'she does', 'they are', 'they do'],
                                   'plain': True,
                                   'q': 'A: Are Mai and Lan at the campsite?',
                                   't': 'mcq'},
                                  {'id': 'b.5', 'o': ['play', 'plays', 'to play', 'playing'], 'plain': True, 'q': 'A: What are they doing?', 't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['playing', 'building', 'putting up', 'doing'],
                                   'plain': True,
                                   'q': "A: What's Nga doing at the campsite?",
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['is', "isn't", 'does', "doesn't"],
                                   'plain': True,
                                   'q': 'A: Is Mary singing a song at the campsite?',
                                   't': 'mcq'},
                                  {'id': 'b.8', 'o': ['doing', 'playing', 'building', 'telling'], 'plain': True, 'q': 'A: Where are Bill and Ben?', 't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['take', 'takes', 'to take', 'taking'],
                                   'plain': True,
                                   'q': 'Phong is ______________ a photo.',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['building', 'putting up', 'telling', 'doing'],
                                   'plain': True,
                                   'q': "A: What's Nam doing?",
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['Where are Lucy and Sarah?',
                                            'What are they doing?',
                                            "Where's Lucas, Mai?",
                                            "What's she doing?",
                                            'Is she taking a photo?'],
                                   'o': ['She is studing English.',
                                         'They are at the campsite.',
                                         'Yes, she is.',
                                         'They are playing tug of war.',
                                         "He's at school."],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['Is', 'Are', 'Do', 'Does'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['he', 'she', 'we', 'they'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['do', 'does', 'is', 'are'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['play', 'plays', 'playing', 'to play'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['do', "don't", 'does', 'doing'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': 'Mary: <b>(1)&nbsp;______</b> Bill and Ben at the campsite, Lucy?<br>Lucy: Yes, <b>(2)&nbsp;______</b> are.<br>Mary: What '
                                   '<b>(3)&nbsp;______</b> they doing?<br>Lucy: They are <b>(4)&nbsp;______</b> tug of war.<br>Mary: What are you '
                                   "<b>(5)&nbsp;______</b>, Lucy?<br>Lucy: I'm playing card games."}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': 'Hoa and her friends are at the campsite.', 't': 'tf'},
                                  {'id': 'e.2', 'q': 'Mai and Lan are playing badminton.', 't': 'tf'},
                                  {'id': 'e.3', 'q': 'Nam and Minh are playing chess.', 't': 'tf'},
                                  {'id': 'e.4', 'q': 'Hanh is drawing a picture.', 't': 'tf'},
                                  {'id': 'e.5', 'q': 'Some other friends are playing football.', 't': 'tf'},
                                  {'id': 'e.6', 'q': 'Hoa is taking photos.', 't': 'tf'}],
                        'passage': 'Hoa and some friends in her class are in the park. Lan and Mai are playing badminton. Nam and Minh are playing chess. Hanh '
                                   'is flying a kite. Some other friends are playing tug of war, Hoa is taking photos. They are having a lot of fun.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['friends?', 'Where', 'are', 'and', 'his', 'Bill']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['doing,', 'Lan?', 'What', 'Nam', 'are', 'and', 'Minh']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['putting', 'a', 'up', 'tent.', 'They', 'are']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['doing,', 'What', 'Mark', 'is', 'Mai?']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['He', 'a', 'kite.', 'is', 'flying']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['watching', 'TV.', 'is', 'Son']},
                                  {'id': 'f.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['are', 'of', 'playing', 'tug', 'war.', 'and', 'his', 'friends', 'Nam']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['and', 'Are', 'Lan', 'songs?', 'singing', 'Mai']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['doing?', 'boys', 'are', 'the', 'What']},
                                  {'id': 'f.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'building', 'a', 'campfire.', 'They']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi một người nào đó đang làm gì và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           "lời</td></tr><tr><td>What are you doing?<br>Bạn đang làm gì?</td><td>I'm + V-ing...<br>Tôi đang...</td></tr><tr><td>What is she/he/(proper name) "
           'doing?<br>Cô ấy/Cậu ấy/(tên riêng) đang làm gì?</td><td>She/He is V-ing...<br>Cô ấy/Cậu ấy đang...</td></tr><tr><td>Ví dụ:<br>A: What are you '
           "doing? Bạn đang làm gì?<br>B: I'm watching TV. Mình đang xem TV.<br>A: What is Nam doing? Nam đang làm gì?<br>B: He is studying English. Cậu ấy "
           'đang học tiếng Anh.</td></tr></table><p>2. Cách hỏi một nhóm người nào đó đang làm gì và cách trả lời:</p><table class="tb"><tr><td>Cách '
           'hỏi</td><td>Cách trả lời</td></tr><tr><td>What are they/(names) doing?<br>Họ/(các tên) đang làm gì?</td><td>They are V-ing...<br>Họ '
           'đang...</td></tr><tr><td>Ví dụ:<br>A: What are they doing? Họ đang làm gì?<br>They are putting up a tent. Họ đang dựng lều.<br>A: What are Bill '
           'and Ben doing? Bill và Ben đang làm gì?<br>B: They are playing badminton. Họ đang chơi cầu lông.</td></tr></table>',
 'title': 'Unit 20 – At summer camp: Luyện tập',
 'unit': 20}
