# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u10-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Were you at the zoo last weekend?',
                                         "When's your sports day?",
                                         'Where were you last weekend?',
                                         'Is your sports day in April?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi có phải ai đó đã ở đâu đó trong thời gian vừa qua không?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['Are', 'Do', 'Was', 'Were'],
                                   'plain': True,
                                   'q': 'A: ______________you at the campsite yesterday?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['I play football.', 'Yes, it is.', 'I was at the zoo yesterday.', 'Yes, I was.', 'Yes, it was.'],
                                   'plain': True,
                                   'q': 'Where were you yesterday?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ you in the countryside last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['on', 'weekend?', 'the', 'beach', 'you', 'Were', 'last']},
                                  {'id': 't1.6',
                                   'o': ["It's in September.", 'Yes, I was.', 'I was in London.', 'Because I like it.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: When’s your sports day?',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['am', 'do', 'was', 'were'], 'plain': True, 'q': 'A: Where were you last summer?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['I play football.', 'Yes, it is.', 'I was at the zoo yesterday.', 'Yes, I was.', 'Yes, it was.'],
                                   'plain': True,
                                   'q': 'Were you on the beach last Sunday?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ were you?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['at', 'the', 'zoo.', 'was', 'No,', 'I', "wasn't.", 'I']},
                                  {'id': 't1.11',
                                   'o': ['Cuối tuần vừa rồi bạn đã ở đâu?',
                                         'Hôm qua bạn đã ở đâu?',
                                         'Có phải hôm qua bạn ở sở thú không?',
                                         'Có phải cuối tuần vừa rồi bạn ở khu cắm trại không?'],
                                   'plain': True,
                                   'q': 'Câu “Where were you yesterday?” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['What', 'Where', 'How', 'When'],
                                   'plain': True,
                                   'q': 'A: _____________ were you yesterday?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['I play football.', 'Yes, it is.', 'I was at the zoo yesterday.', 'Yes, I was.', 'Yes, it was.'],
                                   'plain': True,
                                   'q': 'What did you do last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ did you do there?',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['summer?', 'you', 'Where', 'last', 'were']},
                                  {'id': 't1.16',
                                   'o': ["Yes, I wasn't.", "No, I wasn't. I was at the campsite.", 'I was in the mountains.', 'No, I was.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Were you on the beach last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ['in', 'at', 'on', 'to'], 'plain': True, 'q': 'Were you _____________ the beach yesterday?', 't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['I play football.', 'Yes, it is.', 'I was at the zoo yesterday.', 'Yes, I was.', 'Yes, it was.'],
                                   'plain': True,
                                   'q': 'Was the food good?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: I _____ volleyball with my friends. How about you? Where were you last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['summer.', 'Bangkok', 'last', 'was', 'I', 'in']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 10 – Our summer holidays: Kiểm tra 1',
 'unit': 10}
