# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_dc2.py"""

SET = {'grade': 4,
 'id': 'lop4-dc2-d',
 'pages': [{'groups': [{'id': 'ev11',
                        'instr': 'Unit 11 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev11.1',
                                   'o': ['tại (số nhà)', 'con đường', 'một con đường nhộn nhịp', 'sống'],
                                   'q': '<b>live</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev11.2',
                                   'o': ['một ngôi làng yên tĩnh', 'một con đường nhộn nhịp', 'đường phố', 'một con đường ồn ào'],
                                   'q': '<b>a busy street</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev11.3',
                                   'o': ['trong, ở', 'đường phố', 'một ngôi làng yên tĩnh', 'một con đường nhộn nhịp'],
                                   'q': '<b>street</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev11.4',
                                   'o': ['một thành phố lớn', 'một con đường nhộn nhịp', 'một ngôi làng yên tĩnh', 'tại (số nhà)'],
                                   'q': '<b>a quiet village</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev11.5',
                                   'o': ['đường phố', 'con đường', 'sống', 'một con đường nhộn nhịp'],
                                   'q': '<b>road</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev11.6',
                                   'o': ['sống', 'một thành phố lớn', 'con đường', 'một con đường ồn ào'],
                                   'q': '<b>a noisy road</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev11.7', 'o': ['đường phố', 'trong, ở', 'tại (số nhà)', 'sống'], 'q': '<b>in</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev11.8',
                                   'o': ['một thành phố lớn', 'trong, ở', 'đường phố', 'tại (số nhà)'],
                                   'q': '<b>a big city</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev11.9', 'o': ['đường phố', 'tại (số nhà)', 'con đường', 'sống'], 'q': '<b>at</b> nghĩa là gì?', 't': 'mcq'}]},
                       {'id': 'ev12',
                        'instr': 'Unit 12 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev12.10',
                                   'o': ['cảnh sát (nam)', 'nông dân', 'nhà máy', 'nhân viên văn phòng'],
                                   'q': '<b>farmer</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev12.11',
                                   'o': ['nông trại', 'viện điều dưỡng', 'bệnh viện', 'cảnh sát (nam)'],
                                   'q': '<b>a nursing home</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev12.12',
                                   'o': ['viện điều dưỡng', 'diễn viên (nam)', 'cảnh sát (nam)', 'nhân viên văn phòng'],
                                   'q': '<b>policeman</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev12.13', 'o': ['viện điều dưỡng', 'y tá', 'nhà máy', 'nông trại'], 'q': '<b>a factory</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev12.14',
                                   'o': ['diễn viên (nam)', 'bệnh viện', 'nhân viên văn phòng', 'viện điều dưỡng'],
                                   'q': '<b>office worker</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev12.15',
                                   'o': ['nhà máy', 'trường học', 'nông dân', 'nhân viên văn phòng'],
                                   'q': '<b>a school</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev12.16', 'o': ['bệnh viện', 'diễn viên (nam)', 'nông trại', 'y tá'], 'q': '<b>actor</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev12.17',
                                   'o': ['diễn viên (nam)', 'nhà máy', 'nông trại', 'nhân viên văn phòng'],
                                   'q': '<b>a farm</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev12.18', 'o': ['diễn viên (nam)', 'bệnh viện', 'y tá', 'nông dân'], 'q': '<b>nurse</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev12.19',
                                   'o': ['trường học', 'diễn viên (nam)', 'bệnh viện', 'nhân viên văn phòng'],
                                   'q': '<b>a hospital</b> nghĩa là gì?',
                                   't': 'mcq'}]},
                       {'id': 'ev13',
                        'instr': 'Unit 13 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev13.20',
                                   'o': ['mắt to', 'khuôn mặt tròn', 'tóc dài', 'trông như thế nào'],
                                   'q': '<b>look like</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev13.21', 'o': ['thấp', 'mắt to', 'tóc ngắn', 'tóc dài'], 'q': '<b>short hair</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev13.22', 'o': ['tóc dài', 'cao', 'mảnh khảnh', 'mắt to'], 'q': '<b>tall</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev13.23', 'o': ['tóc ngắn', 'cao', 'tóc dài', 'trông như thế nào'], 'q': '<b>long hair</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev13.24', 'o': ['trông như thế nào', 'thấp', 'mắt to', 'tóc dài'], 'q': '<b>short</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev13.25', 'o': ['tóc ngắn', 'cao', 'khuôn mặt tròn', 'thấp'], 'q': '<b>round face</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev13.26', 'o': ['trông như thế nào', 'thấp', 'mắt to', 'mảnh khảnh'], 'q': '<b>slim</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev13.27', 'o': ['mắt to', 'mảnh khảnh', 'khuôn mặt tròn', 'thấp'], 'q': '<b>big eyes</b> nghĩa là gì?', 't': 'mcq'}]},
                       {'id': 'ev14',
                        'instr': 'Unit 14 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev14.28',
                                   'o': ['vào buổi sáng', 'xem ti vi', 'giặt áo quần', 'lau nhà'],
                                   'q': '<b>in the morning</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev14.29',
                                   'o': ['xem ti vi', 'làm việc nhà', 'vào buổi tối', 'rửa chén, bát'],
                                   'q': '<b>watch TV</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev14.30',
                                   'o': ['làm việc nhà', 'giặt áo quần', 'giúp đỡ việc nấu ăn', 'vào buổi chiều'],
                                   'q': '<b>in the afternoon</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev14.31',
                                   'o': ['giặt áo quần', 'làm việc nhà', 'lau nhà', 'giúp đỡ việc nấu ăn'],
                                   'q': '<b>wash the clothes</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev14.32',
                                   'o': ['vào buổi trưa', 'vào buổi tối', 'xem ti vi', 'rửa chén, bát'],
                                   'q': '<b>at noon</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev14.33',
                                   'o': ['vào buổi chiều', 'vào buổi sáng', 'rửa chén, bát', 'lau nhà'],
                                   'q': '<b>clean the floor</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev14.34',
                                   'o': ['làm việc nhà', 'vào buổi sáng', 'vào buổi tối', 'giặt áo quần'],
                                   'q': '<b>in the evening</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev14.35',
                                   'o': ['vào buổi sáng', 'rửa chén, bát', 'giúp đỡ việc nấu ăn', 'lau nhà'],
                                   'q': '<b>help with the cooking</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev14.36',
                                   'o': ['làm việc nhà', 'lau nhà', 'vào buổi chiều', 'giúp đỡ việc nấu ăn'],
                                   'q': '<b>do housework</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev14.37',
                                   'o': ['làm việc nhà', 'lau nhà', 'vào buổi chiều', 'rửa chén, bát'],
                                   'q': '<b>wash the dishes</b> nghĩa là gì?',
                                   't': 'mcq'}]}],
            'id': 'ev1',
            'mode': 'practice',
            'title': 'Từ vựng Anh → Việt (Unit 11–14)'},
           {'groups': [{'id': 'ev15',
                        'instr': 'Unit 15 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev15.38',
                                   'o': ['trung tâm mua sắm', 'cùng nhau', 'rạp chiếu phim', 'phòng tập gym'],
                                   'q': '<b>gym</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev15.39',
                                   'o': ['hồ bơi', 'nấu ăn', 'xem phim', 'trung tâm mua sắm'],
                                   'q': '<b>cook meals</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev15.40',
                                   'o': ['phòng tập gym', 'cùng nhau', 'hồ bơi', 'trung tâm mua sắm'],
                                   'q': '<b>shopping centre</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev15.41',
                                   'o': ['ở nhà', 'rạp chiếu phim', 'hồ bơi', 'chơi quần vợt'],
                                   'q': '<b>play tennis</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev15.42',
                                   'o': ['nấu ăn', 'nhiều', 'trung tâm thể thao', 'ở nhà'],
                                   'q': '<b>sports centre</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev15.43', 'o': ['xem phim', 'hồ bơi', 'nhiều', 'nấu ăn'], 'q': '<b>watch films</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev15.44',
                                   'o': ['xem phim', 'trung tâm thể thao', 'hồ bơi', 'ở nhà'],
                                   'q': '<b>swimming pool</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev15.45', 'o': ['nhiều', 'trung tâm mua sắm', 'tập yo-ga', 'nấu ăn'], 'q': '<b>do yoga</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev15.46', 'o': ['rạp chiếu phim', 'ở nhà', 'xem phim', 'nấu ăn'], 'q': '<b>cinema</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev15.47',
                                   'o': ['ở nhà', 'nhiều', 'trung tâm thể thao', 'chơi quần vợt'],
                                   'q': '<b>stay at home</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev15.48', 'o': ['nấu ăn', 'cùng nhau', 'phòng tập gym', 'nhiều'], 'q': '<b>a lot of</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev15.49',
                                   'o': ['tập yo-ga', 'phòng tập gym', 'hồ bơi', 'cùng nhau'],
                                   'q': '<b>together</b> nghĩa là gì?',
                                   't': 'mcq'}]},
                       {'id': 'ev16',
                        'instr': 'Unit 16 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev16.50',
                                   'o': ['tuyệt vời', 'có gió', 'thời tiết', 'vui vẻ, đáng yêu'],
                                   'q': '<b>weather</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.51',
                                   'o': ['cuối tuần vừa qua', 'siêu thị', 'quầy hàng thực phẩm', 'hiệu sách'],
                                   'q': '<b>food stall</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.52',
                                   'o': ['cuối tuần vừa qua', 'có mây', 'hiệu bánh', 'công viên nước'],
                                   'q': '<b>last weekend</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.53',
                                   'o': ['thời tiết', 'có mây', 'cuối tuần vừa qua', 'hiệu sách'],
                                   'q': '<b>bookshop</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.54', 'o': ['có gió', 'hiệu sách', 'ngày hôm qua', 'có mây'], 'q': '<b>yesterday</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev16.55',
                                   'o': ['ngày hôm qua', 'vui vẻ, đáng yêu', 'siêu thị', 'hiệu bánh'],
                                   'q': '<b>supermarket</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.56',
                                   'o': ['ngày hôm qua', 'vui vẻ, đáng yêu', 'hiệu sách', 'có nắng'],
                                   'q': '<b>sunny</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.57',
                                   'o': ['hiệu bánh', 'có mưa', 'ngày hôm qua', 'quầy hàng thực phẩm'],
                                   'q': '<b>bakery</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.58', 'o': ['ngày hôm qua', 'hiệu bánh', 'có mưa', 'tuyệt vời'], 'q': '<b>rainy</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev16.59',
                                   'o': ['hiệu bánh', 'có mây', 'công viên nước', 'quầy hàng thực phẩm'],
                                   'q': '<b>water park</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.60', 'o': ['cuối tuần vừa qua', 'có gió', 'hiệu sách', 'có mưa'], 'q': '<b>windy</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev16.61',
                                   'o': ['có mây', 'vui vẻ, đáng yêu', 'tuyệt vời', 'hiệu sách'],
                                   'q': '<b>lovely</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.62',
                                   'o': ['hiệu bánh', 'cuối tuần vừa qua', 'có mây', 'quầy hàng thực phẩm'],
                                   'q': '<b>cloudy</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev16.63',
                                   'o': ['công viên nước', 'có gió', 'hiệu sách', 'tuyệt vời'],
                                   'q': '<b>great</b> nghĩa là gì?',
                                   't': 'mcq'}]},
                       {'id': 'ev17',
                        'instr': 'Unit 17 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev17.64', 'o': ['rẽ trái', 'quay ngược lại', 'bên phải', 'dừng lại'], 'q': '<b>stop</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev17.65',
                                   'o': ['rẽ trái', 'quay ngược lại', 'đi thẳng', 'rẽ phải'],
                                   'q': '<b>go straight</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev17.66', 'o': ['rẽ trái', 'đến (địa điểm)', 'mua', 'đi'], 'q': '<b>go</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev17.67',
                                   'o': ['đi thẳng', 'rẽ phải', 'rẽ trái', 'quay ngược lại'],
                                   'q': '<b>turn round</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev17.68',
                                   'o': ['rẽ trái', 'quay ngược lại', 'rẽ phải', 'đến (địa điểm)'],
                                   'q': '<b>turn right</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev17.69',
                                   'o': ['đi thẳng', 'đến (địa điểm)', 'quay ngược lại', 'mua'],
                                   'q': '<b>get (to)</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev17.70',
                                   'o': ['bên phải', 'rẽ phải', 'đến (địa điểm)', 'rẽ trái'],
                                   'q': '<b>turn left</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev17.71',
                                   'o': ['rẽ phải', 'dừng lại', 'quay ngược lại', 'bên trái'],
                                   'q': '<b>on the left</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev17.72', 'o': ['dừng lại', 'đi', 'mua', 'quay ngược lại'], 'q': '<b>buy</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev17.73', 'o': ['bên phải', 'mua', 'dừng lại', 'rẽ phải'], 'q': '<b>on the right</b> nghĩa là gì?', 't': 'mcq'}]}],
            'id': 'ev2',
            'mode': 'practice',
            'title': 'Từ vựng Anh → Việt (Unit 15–17)'},
           {'groups': [{'id': 'ev18',
                        'instr': 'Unit 18 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev18.74', 'o': ['kem', 'ở giữa', 'hiệu giày', 'gần'], 'q': '<b>near</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev18.75', 'o': ['áo thun', 'cửa hàng quà tặng', 'nghìn', 'chân váy'], 'q': '<b>skirt</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev18.76', 'o': ['kem', 'đối diện', 'ở giữa', 'phía sau'], 'q': '<b>opposite</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev18.77',
                                   'o': ['đối diện', 'cửa hàng đồ chơi', 'hiệu giày', 'áo thun'],
                                   'q': '<b>T-shirt</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev18.78', 'o': ['chân váy', 'phía sau', 'gần', 'áo thun'], 'q': '<b>behind</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev18.79',
                                   'o': ['phía sau', 'cửa hàng quà tặng', 'chân váy', 'đối diện'],
                                   'q': '<b>gift shop</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev18.80',
                                   'o': ['xin lỗi (để hỏi thăm)', 'ở giữa', 'chân váy', 'cửa hàng đồ chơi'],
                                   'q': '<b>between</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev18.81',
                                   'o': ['hiệu giày', 'nghìn', 'xin lỗi (để hỏi thăm)', 'đối diện'],
                                   'q': '<b>thousand</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev18.82',
                                   'o': ['hiệu giày', 'chân váy', 'xin lỗi (để hỏi thăm)', 'nghìn'],
                                   'q': '<b>excuse me</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev18.83',
                                   'o': ['áo thun', 'chân váy', 'cửa hàng đồ chơi', 'hiệu giày'],
                                   'q': '<b>shoe shop</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev18.84',
                                   'o': ['áo thun', 'ở giữa', 'cửa hàng đồ chơi', 'xin lỗi (để hỏi thăm)'],
                                   'q': '<b>toy shop</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev18.85',
                                   'o': ['chân váy', 'kem', 'cửa hàng đồ chơi', 'hiệu giày'],
                                   'q': '<b>ice-cream</b> nghĩa là gì?',
                                   't': 'mcq'}]},
                       {'id': 'ev19',
                        'instr': 'Unit 19 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev19.86',
                                   'o': ['sư tử', 'hươu cao cổ', 'con cá sấu', 'nhảy/ múa đẹp'],
                                   'q': '<b>giraffes</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev19.87',
                                   'o': ['nhảy/ múa đẹp', 'hát hay', 'chạy nhanh', 'gầm to'],
                                   'q': '<b>dance beautifully</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev19.88', 'o': ['chạy nhanh', 'gầm to', 'cái cổ', 'sư tử'], 'q': '<b>lions</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev19.89',
                                   'o': ['cái cổ', 'con cá sấu', 'nhảy/ múa đẹp', 'chạy nhanh'],
                                   'q': '<b>run quickly</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev19.90',
                                   'o': ['hát hay', 'con hà mã', 'con cá sấu', 'hươu cao cổ'],
                                   'q': '<b>crocodiles</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev19.91', 'o': ['gầm to', 'hươu cao cổ', 'con hà mã', 'hát hay'], 'q': '<b>roar loudly</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev19.92', 'o': ['hươu cao cổ', 'con công', 'cái cổ', 'con hà mã'], 'q': '<b>hippos</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev19.93', 'o': ['hát hay', 'hươu cao cổ', 'gầm to', 'con công'], 'q': '<b>sing merrily</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev19.94', 'o': ['chạy nhanh', 'hát hay', 'con công', 'sư tử'], 'q': '<b>peacocks</b> nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'ev19.95', 'o': ['sư tử', 'chạy nhanh', 'con cá sấu', 'cái cổ'], 'q': '<b>neck</b> nghĩa là gì?', 't': 'mcq'}]},
                       {'id': 'ev20',
                        'instr': 'Unit 20 – chọn nghĩa tiếng Việt đúng',
                        'items': [{'id': 'ev20.96',
                                   'o': ['dựng lều trại', 'chụp ảnh', 'nhảy múa xung quanh lửa trại', 'đốt lửa trại'],
                                   'q': '<b>building a campfire</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev20.97',
                                   'o': ['chơi kéo co', 'nhảy múa xung quanh lửa trại', 'chơi bài', 'đốt lửa trại'],
                                   'q': '<b>playing card games</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev20.98',
                                   'o': ['đốt lửa trại', 'chơi bài', 'kể chuyện', 'dựng lều trại'],
                                   'q': '<b>putting up a tent</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev20.99',
                                   'o': ['chơi bài', 'hát', 'chơi kéo co', 'nhảy múa xung quanh lửa trại'],
                                   'q': '<b>playing tug of war</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev20.100',
                                   'o': ['chơi kéo co', 'chơi bài', 'dựng lều trại', 'kể chuyện'],
                                   'q': '<b>telling a story</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev20.101',
                                   'o': ['chơi bài', 'chơi kéo co', 'kể chuyện', 'hát'],
                                   'q': '<b>singing songs</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev20.102',
                                   'o': ['nhảy múa xung quanh lửa trại', 'kể chuyện', 'chơi kéo co', 'chụp ảnh'],
                                   'q': '<b>taking a photo</b> nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'ev20.103',
                                   'o': ['nhảy múa xung quanh lửa trại', 'chơi kéo co', 'kể chuyện', 'đốt lửa trại'],
                                   'q': '<b>dancing around the campfire</b> nghĩa là gì?',
                                   't': 'mcq'}]}],
            'id': 'ev3',
            'mode': 'practice',
            'title': 'Từ vựng Anh → Việt (Unit 18–20)'},
           {'groups': [{'id': 've11',
                        'instr': 'Unit 11 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've11.104', 'o': ['live', 'road', 'a noisy road', 'at'], 'q': 'Từ/cụm từ nào có nghĩa là: <b>sống</b>?', 't': 'mcq'},
                                  {'id': 've11.105',
                                   'o': ['a busy street', 'live', 'a big city', 'in'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>một con đường nhộn nhịp</b>?',
                                   't': 'mcq'},
                                  {'id': 've11.106',
                                   'o': ['a noisy road', 'at', 'a big city', 'street'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>đường phố</b>?',
                                   't': 'mcq'},
                                  {'id': 've11.107',
                                   'o': ['a quiet village', 'street', 'in', 'at'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>một ngôi làng yên tĩnh</b>?',
                                   't': 'mcq'},
                                  {'id': 've11.108',
                                   'o': ['a quiet village', 'a big city', 'live', 'road'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>con đường</b>?',
                                   't': 'mcq'},
                                  {'id': 've11.109',
                                   'o': ['road', 'a noisy road', 'a big city', 'live'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>một con đường ồn ào</b>?',
                                   't': 'mcq'},
                                  {'id': 've11.110',
                                   'o': ['a quiet village', 'in', 'street', 'road'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>trong, ở</b>?',
                                   't': 'mcq'},
                                  {'id': 've11.111',
                                   'o': ['at', 'a big city', 'street', 'road'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>một thành phố lớn</b>?',
                                   't': 'mcq'},
                                  {'id': 've11.112',
                                   'o': ['at', 'in', 'live', 'a noisy road'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>tại (số nhà)</b>?',
                                   't': 'mcq'}]},
                       {'id': 've12',
                        'instr': 'Unit 12 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've12.113',
                                   'o': ['a hospital', 'a nursing home', 'farmer', 'a farm'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>nông dân</b>?',
                                   't': 'mcq'},
                                  {'id': 've12.114',
                                   'o': ['nurse', 'a school', 'a nursing home', 'farmer'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>viện điều dưỡng</b>?',
                                   't': 'mcq'},
                                  {'id': 've12.115',
                                   'o': ['office worker', 'a nursing home', 'farmer', 'policeman'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>cảnh sát (nam)</b>?',
                                   't': 'mcq'},
                                  {'id': 've12.116',
                                   'o': ['a factory', 'policeman', 'nurse', 'a nursing home'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>nhà máy</b>?',
                                   't': 'mcq'},
                                  {'id': 've12.117',
                                   'o': ['office worker', 'a school', 'a farm', 'farmer'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>nhân viên văn phòng</b>?',
                                   't': 'mcq'},
                                  {'id': 've12.118',
                                   'o': ['office worker', 'a school', 'a farm', 'a factory'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>trường học</b>?',
                                   't': 'mcq'},
                                  {'id': 've12.119',
                                   'o': ['actor', 'nurse', 'a nursing home', 'farmer'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>diễn viên (nam)</b>?',
                                   't': 'mcq'},
                                  {'id': 've12.120',
                                   'o': ['a hospital', 'a school', 'office worker', 'a farm'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>nông trại</b>?',
                                   't': 'mcq'},
                                  {'id': 've12.121',
                                   'o': ['nurse', 'a school', 'farmer', 'policeman'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>y tá</b>?',
                                   't': 'mcq'},
                                  {'id': 've12.122',
                                   'o': ['a factory', 'a hospital', 'a farm', 'office worker'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>bệnh viện</b>?',
                                   't': 'mcq'}]},
                       {'id': 've13',
                        'instr': 'Unit 13 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've13.123',
                                   'o': ['short hair', 'look like', 'tall', 'big eyes'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>trông như thế nào</b>?',
                                   't': 'mcq'},
                                  {'id': 've13.124',
                                   'o': ['short hair', 'short', 'tall', 'big eyes'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>tóc ngắn</b>?',
                                   't': 'mcq'},
                                  {'id': 've13.125',
                                   'o': ['big eyes', 'round face', 'tall', 'look like'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>cao</b>?',
                                   't': 'mcq'},
                                  {'id': 've13.126',
                                   'o': ['short', 'look like', 'big eyes', 'long hair'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>tóc dài</b>?',
                                   't': 'mcq'},
                                  {'id': 've13.127',
                                   'o': ['short', 'round face', 'look like', 'big eyes'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>thấp</b>?',
                                   't': 'mcq'},
                                  {'id': 've13.128',
                                   'o': ['round face', 'short', 'slim', 'short hair'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>khuôn mặt tròn</b>?',
                                   't': 'mcq'},
                                  {'id': 've13.129',
                                   'o': ['big eyes', 'slim', 'short hair', 'tall'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>mảnh khảnh</b>?',
                                   't': 'mcq'},
                                  {'id': 've13.130',
                                   'o': ['big eyes', 'slim', 'long hair', 'look like'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>mắt to</b>?',
                                   't': 'mcq'}]},
                       {'id': 've14',
                        'instr': 'Unit 14 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've14.131',
                                   'o': ['wash the dishes', 'at noon', 'in the morning', 'wash the clothes'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>vào buổi sáng</b>?',
                                   't': 'mcq'},
                                  {'id': 've14.132',
                                   'o': ['watch TV', 'clean the floor', 'in the afternoon', 'do housework'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>xem ti vi</b>?',
                                   't': 'mcq'},
                                  {'id': 've14.133',
                                   'o': ['do housework', 'clean the floor', 'watch TV', 'in the afternoon'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>vào buổi chiều</b>?',
                                   't': 'mcq'},
                                  {'id': 've14.134',
                                   'o': ['watch TV', 'help with the cooking', 'wash the clothes', 'do housework'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>giặt áo quần</b>?',
                                   't': 'mcq'},
                                  {'id': 've14.135',
                                   'o': ['watch TV', 'at noon', 'do housework', 'in the afternoon'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>vào buổi trưa</b>?',
                                   't': 'mcq'},
                                  {'id': 've14.136',
                                   'o': ['clean the floor', 'at noon', 'help with the cooking', 'do housework'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>lau nhà</b>?',
                                   't': 'mcq'},
                                  {'id': 've14.137',
                                   'o': ['do housework', 'in the evening', 'at noon', 'in the afternoon'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>vào buổi tối</b>?',
                                   't': 'mcq'},
                                  {'id': 've14.138',
                                   'o': ['in the afternoon', 'watch TV', 'help with the cooking', 'at noon'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>giúp đỡ việc nấu ăn</b>?',
                                   't': 'mcq'},
                                  {'id': 've14.139',
                                   'o': ['wash the clothes', 'at noon', 'wash the dishes', 'do housework'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>làm việc nhà</b>?',
                                   't': 'mcq'},
                                  {'id': 've14.140',
                                   'o': ['wash the dishes', 'in the morning', 'at noon', 'watch TV'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>rửa chén, bát</b>?',
                                   't': 'mcq'}]}],
            'id': 've1',
            'mode': 'practice',
            'title': 'Từ vựng Việt → Anh (Unit 11–14)'},
           {'groups': [{'id': 've15',
                        'instr': 'Unit 15 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've15.141',
                                   'o': ['a lot of', 'cinema', 'together', 'gym'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>phòng tập gym</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.142',
                                   'o': ['shopping centre', 'watch films', 'cook meals', 'gym'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>nấu ăn</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.143',
                                   'o': ['play tennis', 'stay at home', 'swimming pool', 'shopping centre'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>trung tâm mua sắm</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.144',
                                   'o': ['stay at home', 'play tennis', 'a lot of', 'cinema'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>chơi quần vợt</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.145',
                                   'o': ['cook meals', 'sports centre', 'a lot of', 'stay at home'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>trung tâm thể thao</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.146',
                                   'o': ['cinema', 'watch films', 'together', 'sports centre'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>xem phim</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.147',
                                   'o': ['gym', 'watch films', 'swimming pool', 'a lot of'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>hồ bơi</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.148',
                                   'o': ['together', 'a lot of', 'stay at home', 'do yoga'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>tập yo-ga</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.149',
                                   'o': ['sports centre', 'cook meals', 'swimming pool', 'cinema'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>rạp chiếu phim</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.150',
                                   'o': ['together', 'stay at home', 'gym', 'watch films'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>ở nhà</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.151',
                                   'o': ['shopping centre', 'together', 'gym', 'a lot of'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>nhiều</b>?',
                                   't': 'mcq'},
                                  {'id': 've15.152',
                                   'o': ['cook meals', 'together', 'swimming pool', 'a lot of'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>cùng nhau</b>?',
                                   't': 'mcq'}]},
                       {'id': 've16',
                        'instr': 'Unit 16 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've16.153',
                                   'o': ['weather', 'supermarket', 'last weekend', 'rainy'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>thời tiết</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.154',
                                   'o': ['cloudy', 'water park', 'food stall', 'bakery'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>quầy hàng thực phẩm</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.155',
                                   'o': ['water park', 'bookshop', 'supermarket', 'last weekend'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>cuối tuần vừa qua</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.156',
                                   'o': ['rainy', 'last weekend', 'weather', 'bookshop'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>hiệu sách</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.157',
                                   'o': ['yesterday', 'food stall', 'last weekend', 'great'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>ngày hôm qua</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.158',
                                   'o': ['lovely', 'food stall', 'yesterday', 'supermarket'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>siêu thị</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.159',
                                   'o': ['rainy', 'sunny', 'bookshop', 'weather'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>có nắng</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.160',
                                   'o': ['bakery', 'cloudy', 'yesterday', 'great'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>hiệu bánh</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.161',
                                   'o': ['supermarket', 'rainy', 'bookshop', 'yesterday'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>có mưa</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.162',
                                   'o': ['last weekend', 'cloudy', 'supermarket', 'water park'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>công viên nước</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.163',
                                   'o': ['sunny', 'water park', 'windy', 'great'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>có gió</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.164',
                                   'o': ['windy', 'sunny', 'lovely', 'water park'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>vui vẻ, đáng yêu</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.165',
                                   'o': ['yesterday', 'bookshop', 'food stall', 'cloudy'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>có mây</b>?',
                                   't': 'mcq'},
                                  {'id': 've16.166',
                                   'o': ['cloudy', 'great', 'windy', 'last weekend'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>tuyệt vời</b>?',
                                   't': 'mcq'}]},
                       {'id': 've17',
                        'instr': 'Unit 17 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've17.167',
                                   'o': ['turn left', 'go straight', 'go', 'stop'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>dừng lại</b>?',
                                   't': 'mcq'},
                                  {'id': 've17.168',
                                   'o': ['go straight', 'get (to)', 'turn round', 'on the left'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>đi thẳng</b>?',
                                   't': 'mcq'},
                                  {'id': 've17.169', 'o': ['turn round', 'buy', 'go', 'on the left'], 'q': 'Từ/cụm từ nào có nghĩa là: <b>đi</b>?', 't': 'mcq'},
                                  {'id': 've17.170',
                                   'o': ['stop', 'go straight', 'turn round', 'go'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>quay ngược lại</b>?',
                                   't': 'mcq'},
                                  {'id': 've17.171',
                                   'o': ['turn right', 'get (to)', 'turn round', 'on the left'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>rẽ phải</b>?',
                                   't': 'mcq'},
                                  {'id': 've17.172',
                                   'o': ['go straight', 'turn round', 'get (to)', 'turn right'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>đến (địa điểm)</b>?',
                                   't': 'mcq'},
                                  {'id': 've17.173',
                                   'o': ['go', 'go straight', 'turn left', 'stop'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>rẽ trái</b>?',
                                   't': 'mcq'},
                                  {'id': 've17.174',
                                   'o': ['get (to)', 'buy', 'turn left', 'on the left'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>bên trái</b>?',
                                   't': 'mcq'},
                                  {'id': 've17.175', 'o': ['turn left', 'stop', 'go', 'buy'], 'q': 'Từ/cụm từ nào có nghĩa là: <b>mua</b>?', 't': 'mcq'},
                                  {'id': 've17.176',
                                   'o': ['go straight', 'on the right', 'on the left', 'stop'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>bên phải</b>?',
                                   't': 'mcq'}]}],
            'id': 've2',
            'mode': 'practice',
            'title': 'Từ vựng Việt → Anh (Unit 15–17)'},
           {'groups': [{'id': 've18',
                        'instr': 'Unit 18 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've18.177',
                                   'o': ['opposite', 'between', 'gift shop', 'near'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>gần</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.178',
                                   'o': ['behind', 'ice-cream', 'skirt', 'gift shop'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>chân váy</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.179',
                                   'o': ['opposite', 'thousand', 'excuse me', 'ice-cream'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>đối diện</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.180',
                                   'o': ['toy shop', 'T-shirt', 'opposite', 'ice-cream'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>áo thun</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.181',
                                   'o': ['shoe shop', 'ice-cream', 'between', 'behind'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>phía sau</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.182',
                                   'o': ['between', 'excuse me', 'opposite', 'gift shop'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>cửa hàng quà tặng</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.183',
                                   'o': ['between', 'ice-cream', 'shoe shop', 'gift shop'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>ở giữa</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.184',
                                   'o': ['thousand', 'near', 'excuse me', 'ice-cream'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>nghìn</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.185',
                                   'o': ['gift shop', 'excuse me', 'shoe shop', 'opposite'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>xin lỗi (để hỏi thăm)</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.186',
                                   'o': ['opposite', 'behind', 'excuse me', 'shoe shop'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>hiệu giày</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.187',
                                   'o': ['toy shop', 'behind', 'shoe shop', 'near'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>cửa hàng đồ chơi</b>?',
                                   't': 'mcq'},
                                  {'id': 've18.188',
                                   'o': ['opposite', 'ice-cream', 'behind', 'T-shirt'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>kem</b>?',
                                   't': 'mcq'}]},
                       {'id': 've19',
                        'instr': 'Unit 19 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've19.189',
                                   'o': ['peacocks', 'run quickly', 'giraffes', 'crocodiles'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>hươu cao cổ</b>?',
                                   't': 'mcq'},
                                  {'id': 've19.190',
                                   'o': ['lions', 'dance beautifully', 'roar loudly', 'sing merrily'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>nhảy/ múa đẹp</b>?',
                                   't': 'mcq'},
                                  {'id': 've19.191',
                                   'o': ['sing merrily', 'giraffes', 'crocodiles', 'lions'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>sư tử</b>?',
                                   't': 'mcq'},
                                  {'id': 've19.192',
                                   'o': ['dance beautifully', 'peacocks', 'run quickly', 'giraffes'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>chạy nhanh</b>?',
                                   't': 'mcq'},
                                  {'id': 've19.193',
                                   'o': ['sing merrily', 'crocodiles', 'giraffes', 'peacocks'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>con cá sấu</b>?',
                                   't': 'mcq'},
                                  {'id': 've19.194',
                                   'o': ['roar loudly', 'peacocks', 'hippos', 'giraffes'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>gầm to</b>?',
                                   't': 'mcq'},
                                  {'id': 've19.195',
                                   'o': ['giraffes', 'hippos', 'crocodiles', 'dance beautifully'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>con hà mã</b>?',
                                   't': 'mcq'},
                                  {'id': 've19.196',
                                   'o': ['peacocks', 'giraffes', 'sing merrily', 'dance beautifully'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>hát hay</b>?',
                                   't': 'mcq'},
                                  {'id': 've19.197',
                                   'o': ['hippos', 'crocodiles', 'neck', 'peacocks'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>con công</b>?',
                                   't': 'mcq'},
                                  {'id': 've19.198',
                                   'o': ['roar loudly', 'hippos', 'giraffes', 'neck'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>cái cổ</b>?',
                                   't': 'mcq'}]},
                       {'id': 've20',
                        'instr': 'Unit 20 – chọn từ/cụm từ tiếng Anh đúng',
                        'items': [{'id': 've20.199',
                                   'o': ['building a campfire', 'putting up a tent', 'singing songs', 'telling a story'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>đốt lửa trại</b>?',
                                   't': 'mcq'},
                                  {'id': 've20.200',
                                   'o': ['building a campfire', 'telling a story', 'playing card games', 'putting up a tent'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>chơi bài</b>?',
                                   't': 'mcq'},
                                  {'id': 've20.201',
                                   'o': ['putting up a tent', 'singing songs', 'telling a story', 'taking a photo'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>dựng lều trại</b>?',
                                   't': 'mcq'},
                                  {'id': 've20.202',
                                   'o': ['singing songs', 'playing tug of war', 'playing card games', 'putting up a tent'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>chơi kéo co</b>?',
                                   't': 'mcq'},
                                  {'id': 've20.203',
                                   'o': ['playing card games', 'taking a photo', 'putting up a tent', 'telling a story'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>kể chuyện</b>?',
                                   't': 'mcq'},
                                  {'id': 've20.204',
                                   'o': ['singing songs', 'building a campfire', 'playing tug of war', 'dancing around the campfire'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>hát</b>?',
                                   't': 'mcq'},
                                  {'id': 've20.205',
                                   'o': ['dancing around the campfire', 'playing tug of war', 'building a campfire', 'taking a photo'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>chụp ảnh</b>?',
                                   't': 'mcq'},
                                  {'id': 've20.206',
                                   'o': ['taking a photo', 'dancing around the campfire', 'playing tug of war', 'putting up a tent'],
                                   'q': 'Từ/cụm từ nào có nghĩa là: <b>nhảy múa xung quanh lửa trại</b>?',
                                   't': 'mcq'}]}],
            'id': 've3',
            'mode': 'practice',
            'title': 'Từ vựng Việt → Anh (Unit 18–20)'},
           {'groups': [{'id': 'gq11',
                        'instr': 'Unit 11 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq11.207',
                                   'o': ['They’re building a campfire.',
                                         'He’s/She’s a farmer.',
                                         'I live in Le Loi Street./I live at 25 Le Loi Street.',
                                         'It’s a busy street.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>Where do you live?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq11.208',
                                   'o': ['He/She works at a nursing home.',
                                         'It was sunny.',
                                         'It’s a busy street.',
                                         'I live in Le Loi Street./I live at 25 Le Loi Street.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What’s the street like?</b>',
                                   't': 'mcq'}]},
                       {'id': 'gq12',
                        'instr': 'Unit 12 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq12.209',
                                   'o': ['He/She works at a nursing home.', 'He’s/She’s a farmer.', 'They’re building a campfire.', 'He/She goes to the gym.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What does he/she do?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq12.210',
                                   'o': ['It was sunny.', 'It’s a busy street.', 'He/She works at a nursing home.', 'He’s/She’s a farmer.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>Where does he/she work?</b>',
                                   't': 'mcq'}]},
                       {'id': 'gq13',
                        'instr': 'Unit 13 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq13.211',
                                   'o': ['He’s/She’s a farmer.',
                                         'Great! Let’s go (đồng ý)/Sorry, I can’t (từ chối)',
                                         'They’re building a campfire.',
                                         'He’s/She’s tall.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What does he/she look like?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq13.212',
                                   'o': ['He/She has short hair.', 'I wash the clothes/clean the floor.', 'He/She goes to the gym.', 'He/she cooks meals.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What does he/she look like?</b>',
                                   't': 'mcq'}]},
                       {'id': 'gq14',
                        'instr': 'Unit 14 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq14.213',
                                   'o': ['I wash the clothes/clean the floor.',
                                         'Go straight and turn right.',
                                         'He/She goes to the gym.',
                                         'I watch TV in the morning/at noon'],
                                   'q': 'Câu trả lời phù hợp cho: <b>When do you watch TV?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq14.214',
                                   'o': ['It’s a busy street.',
                                         'It’s near the bakery.',
                                         'I wash the clothes/clean the floor.',
                                         'I watch TV in the morning/at noon'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What do you do in the morning?</b>',
                                   't': 'mcq'}]},
                       {'id': 'gq15',
                        'instr': 'Unit 15 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq15.215',
                                   'o': ['He/She has short hair.', 'He/She goes to the gym.', 'He/she cooks meals.', 'It’s twenty thousand dong.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>Where does he/she go on Saturdays?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq15.216',
                                   'o': ['He/she cooks meals.', 'I watch TV in the morning/at noon', 'He’s/she’s taking a photo.', 'He/She goes to the gym.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What does he/she do on Sundays?</b>',
                                   't': 'mcq'}]},
                       {'id': 'gq16',
                        'instr': 'Unit 16 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq16.217',
                                   'o': ['Great! Let’s go (đồng ý)/Sorry, I can’t (từ chối)',
                                         'He’s/she’s taking a photo.',
                                         'I wash the clothes/clean the floor.',
                                         'It was sunny.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What was the weather like last weekend?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq16.218',
                                   'o': ['I watch TV in the morning/at noon',
                                         'It was sunny.',
                                         'Go straight and turn right.',
                                         'Great! Let’s go (đồng ý)/Sorry, I can’t (từ chối)'],
                                   'q': 'Câu trả lời phù hợp cho: <b>Do you want to go to the food stall?</b>',
                                   't': 'mcq'}]},
                       {'id': 'gq17',
                        'instr': 'Unit 17 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq17.219',
                                   'o': ['He’s/She’s a farmer.', 'It says ‘go’.', 'Go straight and turn right.', 'It’s twenty thousand dong.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What does it say?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq17.220',
                                   'o': ['It’s a busy street.', 'It says ‘go’.', 'Go straight and turn right.', 'Because they dance beautifully.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>How can I get to the bookshop?</b>',
                                   't': 'mcq'}]},
                       {'id': 'gq18',
                        'instr': 'Unit 18 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq18.221',
                                   'o': ['It’s near the bakery.', 'I watch TV in the morning/at noon', 'It’s twenty thousand dong.', 'He’s/She’s tall.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>Where’s the bookshop?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq18.222',
                                   'o': ['He/she cooks meals.', 'It’s near the bakery.', 'I wash the clothes/clean the floor.', 'It’s twenty thousand dong.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>How much is the T-shirt?</b>',
                                   't': 'mcq'}]},
                       {'id': 'gq19',
                        'instr': 'Unit 19 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq19.223',
                                   'o': ['They’re giraffes.', 'Go straight and turn right.', 'Because they dance beautifully.', 'It’s near the bakery.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What are these animals?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq19.224',
                                   'o': ['He/She has short hair.', 'I watch TV in the morning/at noon', 'Because they dance beautifully.', 'They’re giraffes.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>Why do you like peacocks?</b>',
                                   't': 'mcq'}]},
                       {'id': 'gq20',
                        'instr': 'Unit 20 – chọn câu trả lời phù hợp',
                        'items': [{'id': 'gq20.225',
                                   'o': ['They’re building a campfire.', 'They’re giraffes.', 'It was sunny.', 'He’s/she’s taking a photo.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What’s he/she doing?</b>',
                                   't': 'mcq'},
                                  {'id': 'gq20.226',
                                   'o': ['He/She has short hair.',
                                         'They’re building a campfire.',
                                         'I wash the clothes/clean the floor.',
                                         'He’s/she’s taking a photo.'],
                                   'q': 'Câu trả lời phù hợp cho: <b>What are they doing?</b>',
                                   't': 'mcq'}]}],
            'id': 'mau-cau-tra-loi',
            'mode': 'practice',
            'title': 'Mẫu câu: chọn câu trả lời'},
           {'groups': [{'id': 'gh11',
                        'instr': 'Unit 11 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh11.227',
                                   'o': ['Where do you live?', 'What’s the street like?', 'How can I get to the bookshop?', 'What does he/she look like?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>I live in Le Loi Street./I live at 25 Le Loi Street.</b>',
                                   't': 'mcq'},
                                  {'id': 'gh11.228',
                                   'o': ['How can I get to the bookshop?', 'Where do you live?', 'Where’s the bookshop?', 'What’s the street like?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>It’s a busy street.</b>',
                                   't': 'mcq'}]},
                       {'id': 'gh12',
                        'instr': 'Unit 12 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh12.229',
                                   'o': ['What does he/she do?', 'Where does he/she work?', 'What’s the street like?', 'How much is the T-shirt?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>He’s/She’s a farmer.</b>',
                                   't': 'mcq'},
                                  {'id': 'gh12.230',
                                   'o': ['What does he/she do?',
                                         'Where does he/she work?',
                                         'What do you do in the morning?',
                                         'What does he/she do on Sundays?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>He/She works at a nursing home.</b>',
                                   't': 'mcq'}]},
                       {'id': 'gh13',
                        'instr': 'Unit 13 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh13.231',
                                   'o': ['What does he/she look like?',
                                         'Where does he/she work?',
                                         'What do you do in the morning?',
                                         'How much is the T-shirt?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>He’s/She’s tall.</b>',
                                   't': 'mcq'},
                                  {'id': 'gh13.232',
                                   'o': ['What are they doing?',
                                         'What was the weather like last weekend?',
                                         'What does he/she look like?',
                                         'Where does he/she work?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>He/She has short hair.</b>',
                                   't': 'mcq'}]},
                       {'id': 'gh14',
                        'instr': 'Unit 14 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh14.233',
                                   'o': ['What was the weather like last weekend?',
                                         'What do you do in the morning?',
                                         'What does he/she look like?',
                                         'When do you watch TV?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>I watch TV in the morning/at noon</b>',
                                   't': 'mcq'},
                                  {'id': 'gh14.234',
                                   'o': ['What do you do in the morning?',
                                         'Do you want to go to the food stall?',
                                         'When do you watch TV?',
                                         'Where’s the bookshop?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>I wash the clothes/clean the floor.</b>',
                                   't': 'mcq'}]},
                       {'id': 'gh15',
                        'instr': 'Unit 15 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh15.235',
                                   'o': ['How much is the T-shirt?',
                                         'Where does he/she go on Saturdays?',
                                         'What does he/she look like?',
                                         'What does he/she do on Sundays?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>He/She goes to the gym.</b>',
                                   't': 'mcq'},
                                  {'id': 'gh15.236',
                                   'o': ['What does he/she look like?',
                                         'What does he/she do on Sundays?',
                                         'Why do you like peacocks?',
                                         'Where does he/she go on Saturdays?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>He/she cooks meals.</b>',
                                   't': 'mcq'}]},
                       {'id': 'gh16',
                        'instr': 'Unit 16 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh16.237',
                                   'o': ['What was the weather like last weekend?',
                                         'Do you want to go to the food stall?',
                                         'Where does he/she go on Saturdays?',
                                         'What does he/she do?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>It was sunny.</b>',
                                   't': 'mcq'},
                                  {'id': 'gh16.238',
                                   'o': ['Why do you like peacocks?',
                                         'What’s the street like?',
                                         'What was the weather like last weekend?',
                                         'Do you want to go to the food stall?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>Great! Let’s go (đồng ý)/Sorry, I can’t (từ chối)</b>',
                                   't': 'mcq'}]},
                       {'id': 'gh17',
                        'instr': 'Unit 17 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh17.239',
                                   'o': ['What was the weather like last weekend?',
                                         'How can I get to the bookshop?',
                                         'What do you do in the morning?',
                                         'What does it say?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>It says ‘go’.</b>',
                                   't': 'mcq'},
                                  {'id': 'gh17.240',
                                   'o': ['What does it say?', 'Why do you like peacocks?', 'What does he/she do?', 'How can I get to the bookshop?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>Go straight and turn right.</b>',
                                   't': 'mcq'}]},
                       {'id': 'gh18',
                        'instr': 'Unit 18 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh18.241',
                                   'o': ['Where’s the bookshop?',
                                         'How can I get to the bookshop?',
                                         'How much is the T-shirt?',
                                         'Where does he/she go on Saturdays?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>It’s near the bakery.</b>',
                                   't': 'mcq'},
                                  {'id': 'gh18.242',
                                   'o': ['When do you watch TV?', 'Where’s the bookshop?', 'How much is the T-shirt?', 'Do you want to go to the food stall?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>It’s twenty thousand dong.</b>',
                                   't': 'mcq'}]},
                       {'id': 'gh19',
                        'instr': 'Unit 19 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh19.243',
                                   'o': ['Where do you live?', 'What are they doing?', 'Why do you like peacocks?', 'What are these animals?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>They’re giraffes.</b>',
                                   't': 'mcq'},
                                  {'id': 'gh19.244',
                                   'o': ['Why do you like peacocks?',
                                         'When do you watch TV?',
                                         'Do you want to go to the food stall?',
                                         'What are these animals?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>Because they dance beautifully.</b>',
                                   't': 'mcq'}]},
                       {'id': 'gh20',
                        'instr': 'Unit 20 – chọn câu hỏi phù hợp',
                        'items': [{'id': 'gh20.245',
                                   'o': ['What does he/she do on Sundays?',
                                         'Do you want to go to the food stall?',
                                         'What’s he/she doing?',
                                         'What are they doing?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>He’s/she’s taking a photo.</b>',
                                   't': 'mcq'},
                                  {'id': 'gh20.246',
                                   'o': ['Where do you live?', 'How can I get to the bookshop?', 'What’s he/she doing?', 'What are they doing?'],
                                   'q': 'Câu hỏi phù hợp cho câu trả lời: <b>They’re building a campfire.</b>',
                                   't': 'mcq'}]}],
            'id': 'mau-cau-hoi',
            'mode': 'practice',
            'title': 'Mẫu câu: chọn câu hỏi'}],
 'theory': '<h3>Đề cương ôn tập Tiếng Anh khối 4 – Kì 2 (Global Success) – Năm học 2024–2025</h3><h3>Unit 11: My home</h3><table class="tb"><tr><td><b>Từ '
           'vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>live</td><td>sống</td></tr><tr><td>a busy street</td><td>một con đường nhộn '
           'nhịp</td></tr><tr><td>street</td><td>đường phố</td></tr><tr><td>a quiet village</td><td>một ngôi làng yên tĩnh</td></tr><tr><td>road</td><td>con '
           'đường</td></tr><tr><td>a noisy road</td><td>một con đường ồn ào</td></tr><tr><td>in</td><td>trong, ở</td></tr><tr><td>a big city</td><td>một thành '
           'phố lớn</td></tr><tr><td>at</td><td>tại (số nhà)</td></tr></table><p><b>Mẫu câu</b></p><p>Hỏi và trả lời ai đó sống ở đâu?</p><ul><li>Where do you '
           'live?</li><li>I live in Le Loi Street./I live at 25 Le Loi Street.</li></ul><p>Hỏi và trả lời nơi nào đó là như thế nào?</p><ul><li>What’s the '
           'street like?</li><li>It’s a busy street.</li></ul><h3>Unit 12: Jobs</h3><table class="tb"><tr><td><b>Từ '
           'vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>farmer</td><td>nông dân</td></tr><tr><td>a nursing home</td><td>viện điều '
           'dưỡng</td></tr><tr><td>policeman</td><td>cảnh sát (nam)</td></tr><tr><td>a factory</td><td>nhà máy</td></tr><tr><td>office worker</td><td>nhân '
           'viên văn phòng</td></tr><tr><td>a school</td><td>trường học</td></tr><tr><td>actor</td><td>diễn viên (nam)</td></tr><tr><td>a farm</td><td>nông '
           'trại</td></tr><tr><td>nurse</td><td>y tá</td></tr><tr><td>a hospital</td><td>bệnh viện</td></tr></table><p><b>Mẫu câu</b></p><p>Hỏi và trả lời anh '
           'ấy / cô ấy làm gì?</p><ul><li>What does he/she do?</li><li>He’s/She’s a farmer.</li></ul><p>Hỏi và trả lời về nơi làm việc của anh ấy/ cô '
           'ấy?</p><ul><li>Where does he/she work?</li><li>He/She works at a nursing home.</li></ul><h3>Unit 13: Appearance</h3><table '
           'class="tb"><tr><td><b>Từ vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>look like</td><td>trông như thế nào</td></tr><tr><td>short '
           'hair</td><td>tóc ngắn</td></tr><tr><td>tall</td><td>cao</td></tr><tr><td>long hair</td><td>tóc '
           'dài</td></tr><tr><td>short</td><td>thấp</td></tr><tr><td>round face</td><td>khuôn mặt tròn</td></tr><tr><td>slim</td><td>mảnh '
           'khảnh</td></tr><tr><td>big eyes</td><td>mắt to</td></tr></table><p><b>Mẫu câu</b></p><p>Hỏi và trả lời anh ấy /cô ấy trông như thế '
           'nào?</p><ul><li>What does he/she look like?</li><li>He’s/She’s tall.</li><li>What does he/she look like?</li><li>He/She has short '
           'hair.</li></ul><h3>Unit 14: Daily activities</h3><table class="tb"><tr><td><b>Từ vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>in the '
           'morning</td><td>vào buổi sáng</td></tr><tr><td>watch TV</td><td>xem ti vi</td></tr><tr><td>in the afternoon</td><td>vào buổi '
           'chiều</td></tr><tr><td>wash the clothes</td><td>giặt áo quần</td></tr><tr><td>at noon</td><td>vào buổi trưa</td></tr><tr><td>clean the '
           'floor</td><td>lau nhà</td></tr><tr><td>in the evening</td><td>vào buổi tối</td></tr><tr><td>help with the cooking</td><td>giúp đỡ việc nấu '
           'ăn</td></tr><tr><td>do housework</td><td>làm việc nhà</td></tr><tr><td>wash the dishes</td><td>rửa chén, bát</td></tr></table><p><b>Mẫu '
           'câu</b></p><p>Hỏi và trả lời về ai đó xem ti vi khi nào?</p><ul><li>When do you watch TV?</li><li>I watch TV in the morning/at '
           'noon</li></ul><p>Hỏi và trả lời về ai đó làm gì vào buổi sáng?</p><ul><li>What do you do in the morning?</li><li>I wash the clothes/clean the '
           'floor.</li></ul><h3>Unit 15: My family&#x27;s weekends</h3><table class="tb"><tr><td><b>Từ '
           'vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>gym</td><td>phòng tập gym</td></tr><tr><td>cook meals</td><td>nấu ăn</td></tr><tr><td>shopping '
           'centre</td><td>trung tâm mua sắm</td></tr><tr><td>play tennis</td><td>chơi quần vợt</td></tr><tr><td>sports centre</td><td>trung tâm thể '
           'thao</td></tr><tr><td>watch films</td><td>xem phim</td></tr><tr><td>swimming pool</td><td>hồ bơi</td></tr><tr><td>do yoga</td><td>tập '
           'yo-ga</td></tr><tr><td>cinema</td><td>rạp chiếu phim</td></tr><tr><td>stay at home</td><td>ở nhà</td></tr><tr><td>a lot '
           'of</td><td>nhiều</td></tr><tr><td>together</td><td>cùng nhau</td></tr></table><p><b>Mẫu câu</b></p><p>Hỏi và trả lời anh ấy / cô ấy đi đâu vào '
           'ngày thứ bảy?</p><ul><li>Where does he/she go on Saturdays?</li><li>He/She goes to the gym.</li></ul><p>Hỏi và trả lời anh ấy / cô ấy làm gì vào '
           'ngày chủ nhật?</p><ul><li>What does he/she do on Sundays?</li><li>He/she cooks meals.</li></ul><h3>Unit 16: Weather</h3><table '
           'class="tb"><tr><td><b>Từ vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>weather</td><td>thời tiết</td></tr><tr><td>food stall</td><td>quầy hàng '
           'thực phẩm</td></tr><tr><td>last weekend</td><td>cuối tuần vừa qua</td></tr><tr><td>bookshop</td><td>hiệu '
           'sách</td></tr><tr><td>yesterday</td><td>ngày hôm qua</td></tr><tr><td>supermarket</td><td>siêu thị</td></tr><tr><td>sunny</td><td>có '
           'nắng</td></tr><tr><td>bakery</td><td>hiệu bánh</td></tr><tr><td>rainy</td><td>có mưa</td></tr><tr><td>water park</td><td>công viên '
           'nước</td></tr><tr><td>windy</td><td>có gió</td></tr><tr><td>lovely</td><td>vui vẻ, đáng yêu</td></tr><tr><td>cloudy</td><td>có '
           'mây</td></tr><tr><td>great</td><td>tuyệt vời</td></tr></table><p><b>Mẫu câu</b></p><p>Hỏi và trả lời thời tiết cuối tuần vừa qua là như thế '
           'nào?</p><ul><li>What was the weather like last weekend?</li><li>It was sunny.</li></ul><p>Hỏi và trả lời ai đó muốn đi đến nơi nào đó '
           'không?</p><ul><li>Do you want to go to the food stall?</li><li>Great! Let’s go (đồng ý)/Sorry, I can’t (từ chối)</li></ul><h3>Unit 17: In the '
           'city</h3><table class="tb"><tr><td><b>Từ vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>stop</td><td>dừng lại</td></tr><tr><td>go '
           'straight</td><td>đi thẳng</td></tr><tr><td>go</td><td>đi</td></tr><tr><td>turn round</td><td>quay ngược lại</td></tr><tr><td>turn right</td><td>rẽ '
           'phải</td></tr><tr><td>get (to)</td><td>đến (địa điểm)</td></tr><tr><td>turn left</td><td>rẽ trái</td></tr><tr><td>on the left</td><td>bên '
           'trái</td></tr><tr><td>buy</td><td>mua</td></tr><tr><td>on the right</td><td>bên phải</td></tr></table><p><b>Mẫu câu</b></p><p>Hỏi và trả lời về '
           'biển báo nói gì?</p><ul><li>What does it say?</li><li>It says ‘go’.</li></ul><p>Hỏi và trả lời ai đó có thể đi đến nơi nào đó bằng cách '
           'nào?</p><ul><li>How can I get to the bookshop?</li><li>Go straight and turn right.</li></ul><h3>Unit 18: At the shopping centre</h3><table '
           'class="tb"><tr><td><b>Từ vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>near</td><td>gần</td></tr><tr><td>skirt</td><td>chân '
           'váy</td></tr><tr><td>opposite</td><td>đối diện</td></tr><tr><td>T-shirt</td><td>áo thun</td></tr><tr><td>behind</td><td>phía '
           'sau</td></tr><tr><td>gift shop</td><td>cửa hàng quà tặng</td></tr><tr><td>between</td><td>ở '
           'giữa</td></tr><tr><td>thousand</td><td>nghìn</td></tr><tr><td>excuse me</td><td>xin lỗi (để hỏi thăm)</td></tr><tr><td>shoe shop</td><td>hiệu '
           'giày</td></tr><tr><td>toy shop</td><td>cửa hàng đồ chơi</td></tr><tr><td>ice-cream</td><td>kem</td></tr></table><p><b>Mẫu câu</b></p><p>Hỏi và trả '
           'lời hiệu sách thì ở đâu?</p><ul><li>Where’s the bookshop?</li><li>It’s near the bakery.</li></ul><p>Hỏi và trả lời về giá tiền của quần áo/ đồ '
           'dùng?</p><ul><li>How much is the T-shirt?</li><li>It’s twenty thousand dong.</li></ul><h3>Unit 19: The animal world</h3><table '
           'class="tb"><tr><td><b>Từ vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>giraffes</td><td>hươu cao cổ</td></tr><tr><td>dance '
           'beautifully</td><td>nhảy/ múa đẹp</td></tr><tr><td>lions</td><td>sư tử</td></tr><tr><td>run quickly</td><td>chạy '
           'nhanh</td></tr><tr><td>crocodiles</td><td>con cá sấu</td></tr><tr><td>roar loudly</td><td>gầm to</td></tr><tr><td>hippos</td><td>con hà '
           'mã</td></tr><tr><td>sing merrily</td><td>hát hay</td></tr><tr><td>peacocks</td><td>con công</td></tr><tr><td>neck</td><td>cái '
           'cổ</td></tr></table><p><b>Mẫu câu</b></p><p>Hỏi và trả lời những động vật này là con gì?</p><ul><li>What are these animals?</li><li>They’re '
           'giraffes.</li></ul><p>Hỏi và trả lời về ai đó tại sao thích con vật nào đó?</p><ul><li>Why do you like peacocks?</li><li>Because they dance '
           'beautifully.</li></ul><h3>Unit 20: At summer camp</h3><table class="tb"><tr><td><b>Từ vựng</b></td><td><b>Nghĩa</b></td></tr><tr><td>building a '
           'campfire</td><td>đốt lửa trại</td></tr><tr><td>playing card games</td><td>chơi bài</td></tr><tr><td>putting up a tent</td><td>dựng lều '
           'trại</td></tr><tr><td>playing tug of war</td><td>chơi kéo co</td></tr><tr><td>telling a story</td><td>kể chuyện</td></tr><tr><td>singing '
           'songs</td><td>hát</td></tr><tr><td>taking a photo</td><td>chụp ảnh</td></tr><tr><td>dancing around the campfire</td><td>nhảy múa xung quanh lửa '
           'trại</td></tr></table><p><b>Mẫu câu</b></p><p>Hỏi và trả lời anh ấy / cô ấy đang làm gì?</p><ul><li>What’s he/she doing?</li><li>He’s/she’s taking '
           'a photo.</li></ul><p>Hỏi và trả lời họ đang làm cái gì?</p><ul><li>What are they doing?</li><li>They’re building a campfire.</li></ul>',
 'title': 'Đề cương HK2 (24-25) D – Cuối kì 2: từ vựng & mẫu câu',
 'unit': 'DeCuongHK2'}
