# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['Those giraffes are running quickly.'],
 't1.10': 'like',
 't1.11': ['The giraffes have long necks and legs.'],
 't1.12': 'Những con công này múa đẹp.',
 't1.13': 'scary',
 't1.14': 'hippos',
 't1.15': ['She likes birds because they sing merrily.'],
 't1.16': "They're giraffes.",
 't1.17': 'hippos',
 't1.18': 'strong',
 't1.19': ['Why do you like peacocks?'],
 't1.2': 'Because they dance beautifully.',
 't1.20': "They're peacocks.",
 't1.3': 'because they',
 't1.4': 'I want to see giraffes.',
 't1.5': 'Why',
 't1.6': ['Those lions are roaring loudly.'],
 't1.7': 'Những con hươu cao cổ này chạy nhanh.',
 't1.8': 'they',
 't1.9': 'He wants to see hippos.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: Those giraffes are running quickly.',
 't1.10': 'Đáp án: like',
 't1.11': 'Câu đúng: The giraffes have long necks and legs.',
 't1.12': 'Đáp án: Những con công này múa đẹp.',
 't1.13': 'Đáp án: scary',
 't1.14': 'Đáp án: hippos',
 't1.15': 'Câu đúng: She likes birds because they sing merrily.',
 't1.16': "Đáp án: They're giraffes.",
 't1.17': 'Đáp án: hippos',
 't1.18': 'Đáp án: strong',
 't1.19': 'Câu đúng: Why do you like peacocks?',
 't1.2': 'Đáp án: Because they dance beautifully.',
 't1.20': "Đáp án: They're peacocks.",
 't1.3': 'Đáp án: because they',
 't1.4': 'Đáp án: I want to see giraffes.',
 't1.5': 'Đáp án: Why',
 't1.6': 'Câu đúng: Those lions are roaring loudly.',
 't1.7': 'Đáp án: Những con hươu cao cổ này chạy nhanh.',
 't1.8': 'Đáp án: they',
 't1.9': 'Đáp án: He wants to see hippos.'}
