# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a.1': 'B',
 'a.2': 'B',
 'a.3': 'B',
 'a.4': 'D',
 'a.5': 'D',
 'b.10': 'A',
 'b.6': 'B',
 'b.7': 'A',
 'b.8': 'D',
 'b.9': 'B',
 'c.11': 'C',
 'c.12': 'A',
 'c.13': 'A',
 'c.14': 'B',
 'c.15': 'A',
 'c.16': 'A',
 'c.17': 'C',
 'c.18': 'B',
 'c.19': 'C',
 'c.20': 'A',
 'd.21': {'blanks': [['play']]},
 'd.22': {'blanks': [['reads']]},
 'd.23': {'blanks': [['go']]},
 'd.24': {'blanks': [['isn’t reading']]},
 'd.25': {'blanks': [['aren’t swimming']]},
 'd.26': {'blanks': [['didn’t play']]},
 'd.27': {'blanks': [['didn’t read']]},
 'd.28': {'blanks': [['Did'], ['listen']]},
 'd.29': {'blanks': [['Did'], ['play']]},
 'd.30': {'blanks': [['went']]},
 'e.31': {'blanks': [['My favorite subject is science.'],
                     ['I went to Florida with my family. We visited Disney World and had a lot of fun!'],
                     ['My birthday is on July 15th.'],
                     ['No, I don’t.'],
                     ['Yes, I am.']]},
 'f.37': ['upon'],
 'f.38': ['named'],
 'f.39': ['Children'],
 'f.40': ['taught'],
 'f.41': ['kingdom'],
 'g.42': ['The Declaration of Independence declared freedom.'],
 'g.43': ['Music evokes emotions in us.'],
 'g.44': ['Earthquakes shake the ground.'],
 'g.45': ['Cells are tiny living things.'],
 'g.46': ['The Earth goes around the Sun.'],
 'wrfix.32': ['The sun is shining brightly.'],
 'wrfix.33': ['Birds chirp in the morning.'],
 'wrfix.34': ['I love playing with my toys.'],
 'wrfix.35': ['My dog likes to chase its tail.'],
 'wrfix.36': ['We go to school to learn.']}

EXPLANATIONS = {'a.1': 'Đáp án: B. nice',
 'a.2': 'Đáp án: B. happy',
 'a.3': 'Đáp án: B. apple',
 'a.4': 'Đáp án: D. were',
 'a.5': 'Đáp án: D. cooker',
 'b.10': 'Đáp án: A. h<u>a</u>te',
 'b.6': 'Đáp án: B. pl<u>ea</u>se',
 'b.7': 'Đáp án: A. n<u>o</u>tebook',
 'b.8': 'Đáp án: D. bl<u>ow</u>',
 'b.9': 'Đáp án: B. w<u>ea</u>r',
 'c.11': 'Đáp án: C. cooked',
 'c.12': 'Đáp án: A. enjoys',
 'c.13': 'Đáp án: A. is drinking',
 'c.14': 'Đáp án: B. walk',
 'c.15': 'Đáp án: A. chirp',
 'c.16': 'Đáp án: A. sets',
 'c.17': 'Đáp án: C. visited',
 'c.18': 'Đáp án: B. have',
 'c.19': 'Đáp án: C. went',
 'c.20': 'Đáp án: A. studying',
 'd.21': 'Đáp án: play',
 'd.22': 'Đáp án: reads',
 'd.23': 'Đáp án: go',
 'd.24': 'Đáp án: isn’t reading',
 'd.25': 'Đáp án: aren’t swimming',
 'd.26': 'Đáp án: didn’t play',
 'd.27': 'Đáp án: didn’t read',
 'd.28': 'Đáp án: Did / listen',
 'd.29': 'Đáp án: Did / play',
 'd.30': 'Đáp án: went',
 'e.31': '1–B; 2–D; 3–A; 4–E; 5–C (theo đáp án của đề).',
 'f.37': 'Đáp án: upon',
 'f.38': 'Đáp án: named',
 'f.39': 'Đáp án: Children',
 'f.40': 'Đáp án: taught',
 'f.41': 'Đáp án: kingdom',
 'g.42': 'Câu đúng: The Declaration of Independence declared freedom.',
 'g.43': 'Câu đúng: Music evokes emotions in us.',
 'g.44': 'Câu đúng: Earthquakes shake the ground.',
 'g.45': 'Câu đúng: Cells are tiny living things.',
 'g.46': 'Câu đúng: The Earth goes around the Sun.',
 'h.47': 'Đáp án mẫu (theo đáp án của đề): <b>My sister goes to the supermarket on foot.</b>',
 'h.48': 'Đáp án mẫu (theo đáp án của đề): <b>Our garden has many flowers.</b>',
 'h.49': 'Đáp án mẫu (theo đáp án của đề): <b>Does your father get to work by bike?</b>',
 'h.50': 'Đáp án mẫu (theo đáp án của đề): <b>Nam’s classroom is in front of the garden.</b>',
 'h.51': 'Đáp án mẫu (theo đáp án của đề): <b>Tom travels to work by car every morning.</b>',
 'wrfix.32': 'Sửa lỗi: are → is. Câu đúng: The sun is shining brightly.',
 'wrfix.33': 'Sửa lỗi: chirps → chirp. Câu đúng: Birds chirp in the morning.',
 'wrfix.34': 'Sửa lỗi: play → playing. Câu đúng: I love playing with my toys.',
 'wrfix.35': 'Sửa lỗi: like → likes. Câu đúng: My dog likes to chase its tail.',
 'wrfix.36': 'Sửa lỗi: goes → go. Câu đúng: We go to school to learn.'}
