# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de13',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and number (nghe và đánh số). (Ví dụ: câu 0 – tranh d.)',
                        'items': [{'id': 'l1.1', 'o': ['a', 'b', 'c', 'd', 'e'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['a', 'b', 'c', 'd', 'e'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['a', 'b', 'c', 'd', 'e'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['a', 'b', 'c', 'd', 'e'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de13/l1.png" alt="Tranh">'},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and circle the correct pictures (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 1 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 2 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 3 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 4 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen and write the missing words (nghe và điền từ). Ví dụ: What does it say? – It says “Stop”.',
                        'items': [{'id': 'l3.9', 'q': 'A: Where does he work?<br>B: He works {_}.', 't': 'fill'},
                                  {'id': 'l3.10', 'q': 'A: How much is the pen?<br>B: It’s twenty {_} dong.', 't': 'fill'},
                                  {'id': 'l3.11', 'q': 'A: Do you want to go to the {_}?<br>B: Great! Let’s go.', 't': 'fill'},
                                  {'id': 'l3.12', 'q': 'A: Where do you live?<br>B: I live at {_} Tran Hung Dao Street.', 't': 'fill'}]},
                       {'id': 'r1',
                        'instr': 'Question 4. Look, read and put a tick or cross (nhìn tranh, đọc: đúng ✓ = True, sai ✗ = False). Ví dụ: She has round face ✓; '
                                 'She is big ✗.',
                        'items': [{'id': 'r1.13',
                                   'img': 'r1_1.png',
                                   'q': 'What do you do in the morning?<br>– I wash the clothes.<br>(Câu trả lời có đúng với tranh không?)',
                                   't': 'tf'},
                                  {'id': 'r1.14',
                                   'img': 'r1_2.png',
                                   'q': 'What was the weather like last weekend?<br>– It was windy.<br>(Câu trả lời có đúng với tranh không?)',
                                   't': 'tf'},
                                  {'id': 'r1.15',
                                   'img': 'r1_3.png',
                                   'q': 'Why do you like peacocks?<br>– Because they dance beautifully.<br>(Câu trả lời có đúng với tranh không?)',
                                   't': 'tf'},
                                  {'id': 'r1.16',
                                   'img': 'r1_4.png',
                                   'q': 'Where does your brother work?<br>– He works at a bank.<br>(Câu trả lời có đúng với tranh không?)',
                                   't': 'tf'},
                                  {'id': 'r1.17',
                                   'img': 'r1_5.png',
                                   'q': 'How much is the pen?<br>– It’s fifteen thousand dong.<br>(Câu trả lời có đúng với tranh không?)',
                                   't': 'tf'}]},
                       {'id': 'r2',
                        'instr': 'Question 5. Read and choose the correct answer (chọn đáp án đúng). Ví dụ: Do you want to go to the food stall? (A. to go)',
                        'items': [{'id': 'r2.18', 'o': ['How', 'Why', 'Who', 'What'], 'q': '………… is the road like? – It’s a noisy road.', 't': 'mcq'},
                                  {'id': 'r2.19',
                                   'o': ['But', 'Because', 'And', 'So'],
                                   'q': 'Why does she like giraffes? – ………… they run quickly.',
                                   't': 'mcq'},
                                  {'id': 'r2.20',
                                   'o': ['I went to the Sports shop last weekend', 'I like the Sports shop.', 'It’s near the pets shop.', 'It’s quiet.'],
                                   'q': 'Where’s the Sports shop? – ………………',
                                   't': 'mcq'},
                                  {'id': 'r2.21', 'o': ['say', 'saying', 'to say', 'says'], 'q': 'What does it say? – It ……… “stop”.', 't': 'mcq'},
                                  {'id': 'r2.22', 'o': ['in', 'at', 'on', 'for'], 'q': 'When do you watch TV? – I watch TV ……… the evening.', 't': 'mcq'}]},
                       {'id': 'r3',
                        'instr': 'Question 6. Look and write (nhìn tranh, viết từ/cụm từ đúng). Ví dụ: (tranh con phố yên tĩnh) → quiet.',
                        'items': [{'id': 'r3.23', 'img': 'r3_1.png', 'q': 'Tranh người làm việc văn phòng (gợi ý: 6 + 6 chữ cái): {_}', 't': 'fill'},
                                  {'id': 'r3.24', 'img': 'r3_2.png', 'q': 'Tranh người tập yoga (gợi ý: 6 chữ cái): {_}', 't': 'fill'},
                                  {'id': 'r3.25', 'img': 'r3_3.png', 'q': 'Tranh mặt trời (gợi ý: 5 chữ cái): {_}', 't': 'fill'},
                                  {'id': 'r3.26', 'img': 'r3_4.png', 'q': 'Biển báo (gợi ý: 9 chữ cái): {_}', 't': 'fill'},
                                  {'id': 'r3.27',
                                   'img': 'r3_5.png',
                                   'q': 'Tranh các cửa hàng, mũi tên chỉ cửa hàng giữa (gợi ý: 8 chữ cái): {_}',
                                   't': 'fill'}]},
                       {'id': 'w1',
                        'instr': 'Question 7. Rearrange the words to make complete sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w1.28', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ["What's", 'the', 'like?', 'street']},
                                  {'id': 'w1.29',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'floor', 'in', 'the', 'afternoon.', 'I', 'clean']},
                                  {'id': 'w1.30',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['weather', 'yesterday?', 'like', 'What', 'the', 'Hue', 'in', 'was']},
                                  {'id': 'w1.31',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['left', 'turn', 'go', 'the', 'I', 'to', 'bakery.', 'get', 'can', 'to', 'and', 'straight']},
                                  {'id': 'w1.32',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['because', 'merrily.', 'Her', 'birds', 'friends', 'they', 'like', 'sing']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 13',
 'unit': 'OnHK2'}
