# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a1.1': 'B',
 'a1.2': 'A',
 'a1.3': 'A',
 'a1.4': 'B',
 'a2.5': 'B',
 'a2.6': 'C',
 'a2.7': 'D',
 'a2.8': 'A',
 'a3.10': 'T',
 'a3.9': 'F',
 'a4.11': ['teacher'],
 'a4.12': ['buildings'],
 'b1.13': {'blanks': [['e'], ['a'], ['b'], ['f'], ['d']]},
 'b2.14': 'T',
 'b2.15': 'F',
 'b2.16': 'F',
 'b2.17': 'T',
 'b2.18': 'T',
 'c1.19': ['listen to music'],
 'c1.20': ['village'],
 'c1.21': ['Science'],
 'c1.22': ['ride a bike'],
 'c1.23': ['eat dinner', 'have dinner'],
 'c2.24': ['There are three buildings at my school.'],
 'c2.25': ['It is Sunday today.'],
 'c2.26': ['I eat breakfast at 6.15.'],
 'c2.27': ['I can’t play badminton.'],
 'c2.28': ['I was in Da Nang last weekend.']}

EXPLANATIONS = {'a1.1': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.2': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.3': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.4': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a2.5': 'Câu 1 ứng với tranh B (theo đáp án của đề).',
 'a2.6': 'Câu 2 ứng với tranh C (theo đáp án của đề).',
 'a2.7': 'Câu 3 ứng với tranh D (theo đáp án của đề).',
 'a2.8': 'Câu 4 ứng với tranh A (theo đáp án của đề).',
 'a3.10': 'Đáp án: True (theo đáp án của đề: ✓).',
 'a3.9': 'Đáp án: False (theo đáp án của đề: ✗).',
 'a4.11': 'Đáp án: teacher',
 'a4.12': 'Đáp án: buildings',
 'b1.13': 'Đáp án: 1–e, 2–a, 3–b, 4–f, 5–d',
 'b2.14': 'Đáp án: True (theo đáp án của đề).',
 'b2.15': 'Đáp án: False (theo đáp án của đề).',
 'b2.16': 'Đáp án: False (theo đáp án của đề).',
 'b2.17': 'Đáp án: True (theo đáp án của đề).',
 'b2.18': 'Đáp án: True (theo đáp án của đề).',
 'c1.19': 'Đáp án: listen to music',
 'c1.20': 'Đáp án: village',
 'c1.21': 'Đáp án: Science',
 'c1.22': 'Đáp án: ride a bike',
 'c1.23': 'Đáp án: eat dinner',
 'c2.24': 'Câu đúng: There are three buildings at my school.',
 'c2.25': 'Câu đúng: It is Sunday today.',
 'c2.26': 'Câu đúng: I eat breakfast at 6.15.',
 'c2.27': 'Câu đúng: I can’t play badminton.',
 'c2.28': 'Câu đúng: I was in Da Nang last weekend.'}
