# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u13-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What does your brother do?', 'Where does your brother work?', 'What does your brother look like?', "Who's that?"],
                                   'plain': True,
                                   'q': 'Câu: “He has a round face.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['is', 'be', 'look', 'have'], 'plain': True, 'q': 'A: What does she ____________ like?', 't': 'mcq'},
                                  {'id': 't1.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['long', 'big', 'She', 'hair.', 'and', 'eyes', 'has']},
                                  {'id': 't1.4',
                                   'o': ["He's thin and tall.", "She's a nurse.", "She's slim.", "He's a worker."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does your sister look like?”',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['your sister', 'they', 'we', 'you'],
                                   'plain': True,
                                   'q': 'What does ____________ look like?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['very', 'father', 'is', 'tall.', 'My']},
                                  {'id': 't1.7',
                                   'o': ['Chị tôi có gương mặt tròn và đôi mắt nhỏ.',
                                         'Chị tôi có gương mặt tròn và đôi mắt to.',
                                         'Chị tôi cao và có đôi mắt to.',
                                         'Chị tôi mảnh mai và có đôi mắt to.'],
                                   'plain': True,
                                   'q': 'Câu: “My sister has a round face and big eyes.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['Are', 'Is', 'Do', 'Does'], 'plain': True, 'q': '___________ you have a brother, Mai?', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['four', 'people', 'in', 'my', 'are', 'family.', 'There']},
                                  {'id': 't1.10',
                                   'o': ['What does your mother do?',
                                         'What does your mother look like?',
                                         'Where does your mother work?',
                                         'Is your mother slim?'],
                                   'plain': True,
                                   'q': 'Câu: “She has long hair" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'o': ['is', 'has', 'have', 'does'], 'plain': True, 'q': 'My sister _____________ long hair.', 't': 'mcq'},
                                  {'id': 't1.12',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['My', 'long', 'slim', 'has', 'and', 'mother', 'is', 'hair.']},
                                  {'id': 't1.13',
                                   'o': ['What does your brother look like?', 'Do you have a brother?', 'Is he your brother?', 'Where does he live?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn có anh trai không?.”',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'o': ['do', 'does', 'is', 'are'], 'plain': True, 'q': 'What ____________ she look like?', 't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['Yes, I do.', 'He is big and short.', "It's my brother.", "He's a student.", 'She is tall and slim.'],
                                   'plain': True,
                                   'q': "Who's that?",
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['How much', 'How many', 'How old', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ people are there in your family?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Mai?', 'or', 'Do', 'brother', 'sister,', 'have', 'a', 'a', 'you']},
                                  {'id': 't1.18',
                                   'o': ['What does she do?', 'Where does she live?', 'Where does she work?', 'What does she look like?'],
                                   'plain': True,
                                   'q': 'Câu “She is slim." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['old', 'high', 'much', 'many'],
                                   'plain': True,
                                   'q': 'How ____________ is your mother, Lan?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['Yes, I do.', 'He is big and short.', "It's my brother.", "He's a student.", 'She is tall and slim.'],
                                   'plain': True,
                                   'q': 'What does he do?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 13 – Appearance: Kiểm tra 3',
 'unit': 13}
