# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck1-de3',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'gi',
                        'instr': 'I. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'gi.1', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.2', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.3', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.4', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de3/gi.png" alt="Tranh a–d">'},
                       {'id': 'gii',
                        'instr': 'II. Listen and draw lines (nghe và nối nhân vật với tranh).',
                        'items': [{'id': 'gii.5',
                                   'left': [{'img': 'gii_l1.png', 't': 'Mai'},
                                            {'img': 'gii_l2.png', 't': 'Huy'},
                                            {'img': 'gii_l3.png', 't': 'Phong'},
                                            {'img': 'gii_l4.png', 't': 'Lan'}],
                                   'o': ['a', 'b', 'c', 'd'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de3/gii.png" alt="Tranh a–d">'},
                       {'id': 'giii',
                        'instr': 'III. Listen and complete (nghe và điền từ).',
                        'items': [{'id': 'giii.6', 'q': '– Is your sports day in {_}?<br>– Yes, it is.', 't': 'fill'},
                                  {'id': 'giii.7', 'q': '– How many {_} are there at your school?<br>– There is one.', 't': 'fill'},
                                  {'id': 'giii.8', 'q': '– Why do you like {_}?<br>– Because I want to be a singer.', 't': 'fill'},
                                  {'id': 'giii.9', 'q': '– Where were you last summer?<br>– I was in {_}.', 't': 'fill'}]},
                       {'id': 'giv',
                        'instr': 'IV. Read and choose A, B or C (nhìn tranh, chọn đáp án đúng).',
                        'items': [{'id': 'giv.10',
                                   'img': 'giv_1.png',
                                   'o': ['It’s in September.', 'I have it on Tuesdays.', 'I like art.'],
                                   'q': 'When do you have art?',
                                   't': 'mcq'},
                                  {'id': 'giv.11',
                                   'img': 'giv_2.png',
                                   'o': ['It’s in the village.', 'I was at the beach.', 'I study at school.'],
                                   'q': 'Where’s your school?',
                                   't': 'mcq'},
                                  {'id': 'giv.12',
                                   'img': 'giv_3.png',
                                   'o': ['I have it on Mondays.', 'My favourite subject is maths.', 'Because I want to be a maths teacher.'],
                                   'q': 'Why do you like maths?',
                                   't': 'mcq'},
                                  {'id': 'giv.13',
                                   'img': 'giv_4.png',
                                   'o': ['No, I was.', 'Yes, I was.', 'Yes, I were.'],
                                   'q': 'Were you in the countryside last month?',
                                   't': 'mcq'}]},
                       {'id': 'gv',
                        'instr': 'V. Read and write T (True) or F (False) (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'gv.14', 'q': 'Mark went camping with her friend.', 't': 'tf'},
                                  {'id': 'gv.15', 'q': 'She went camping in Green Park.', 't': 'tf'},
                                  {'id': 'gv.16', 'q': 'They went fishing, hiking and swimming every day.', 't': 'tf'}],
                        'passage': '<p>My name is Mark. I had a great summer. I went camping with my sister Susan in Green Park. We went camping because it '
                                   'was my sister’s birthday and she liked outdoor activities. We stayed there for five days. We went fishing, hiking and '
                                   'swimming every day. It was a wonderful summer.</p>'},
                       {'id': 'gvi',
                        'instr': 'VI. Write suitable questions for the answers given (nhìn tranh, viết câu hỏi phù hợp).',
                        'items': [{'id': 'gvi.17', 'img': 'gvi_1.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>I like English.</i><br>{_}', 't': 'fill'},
                                  {'id': 'gvi.18',
                                   'img': 'gvi_2.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>I was at the beach yesterday.</i><br>{_}',
                                   't': 'fill'},
                                  {'id': 'gvi.19', 'img': 'gvi_3.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>There are three.</i><br>{_}', 't': 'fill'}]},
                       {'bank': ['lemonade', 'sandcastle', 'ball', 'swim'],
                        'id': 'gvii',
                        'instr': 'VII. Fill in the blanks (điền từ vào chỗ trống, chọn từ trong khung).',
                        'items': [{'id': 'gvii.20', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'gvii.21', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'gvii.22', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'gvii.23', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Hello, my name is Sam. I like to go to the beach in summer. I <b>(1) ______</b> in the sea and build a <b>(2) '
                                   '______</b> I look for shells and throw a <b>(3) ______</b> at the beach. I drink <b>(4) ______</b> and eat an ice cream. I '
                                   'like my summer holidays!</p>'},
                       {'id': 'gviii',
                        'instr': 'VIII. Reorder the words to make correct sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'gviii.24', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sports', 'My', 'is', 'day', 'March.', 'in']},
                                  {'id': 'gviii.25',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['many', 'at', 'school?', 'buildings', 'How', 'your', 'there', 'are']},
                                  {'id': 'gviii.26', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['on', 'have', 'I', 'music', 'Tuesdays.']},
                                  {'id': 'gviii.27', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'were', 'Where', 'summer?', 'last']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 1 – Đề 3',
 'unit': 'CuoiKy1'}
