# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck1-de20',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'a1',
                        'instr': 'I. Listen and tick (nghe và chọn tranh đúng).',
                        'items': [{'id': 'a1.1', 'img': 'a1_1.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.2', 'img': 'a1_2.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.3', 'img': 'a1_3.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.4',
                                   'img': 'a1_4.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'a2',
                        'instr': 'II. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'a2.5', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.6', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.7', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.8', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de20/a2.png" alt="Tranh A-D">'},
                       {'id': 'a3',
                        'instr': 'III. Listen and tick or cross (nghe, nội dung nghe có khớp với tranh không?).',
                        'items': [{'id': 'a3.9', 'img': 'a3_1.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'},
                                  {'id': 'a3.10', 'img': 'a3_2.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'}]},
                       {'id': 'a4',
                        'instr': 'IV. Listen and write (nghe và điền từ).',
                        'items': [{'id': 'a4.11', 'q': 'A: What do you do on Thursday?<br>B: I {_}.', 't': 'fill'},
                                  {'id': 'a4.12', 'q': 'A: Where’s your school, Bill?<br>B: It’s in the {_}.', 't': 'fill'}]},
                       {'id': 'b1',
                        'instr': 'I. Look, read and circle a or b (nhìn tranh, chọn câu đúng).',
                        'items': [{'id': 'b1.13',
                                   'img': 'b1_1.png',
                                   'o': ['I like maths because I want to be a math teacher.', 'I like art because I want to be an art teacher.'],
                                   'q': 'Chọn câu đúng với tranh.',
                                   't': 'mcq'},
                                  {'id': 'b1.14',
                                   'img': 'b1_2.png',
                                   'o': ['I have breakfast at six thirty.', 'I have breakfast at six fifty.'],
                                   'q': 'Chọn câu đúng với tranh.',
                                   't': 'mcq'},
                                  {'id': 'b1.15',
                                   'img': 'b1_3.png',
                                   'o': ['I want some chips.', 'I want some grapes.'],
                                   'q': 'What do you want to eat?',
                                   't': 'mcq'},
                                  {'id': 'b1.16',
                                   'img': 'b1_4.png',
                                   'o': ['I listen to music.', 'I do housework.'],
                                   'q': 'What do you do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 'b1.17', 'img': 'b1_5.png', 'o': ['It’s in August.', 'It’s in March.'], 'q': 'When’s your birthday?', 't': 'mcq'}]},
                       {'id': 'b2',
                        'instr': 'II. Read and complete the sentences (đọc đoạn văn và điền từ).',
                        'items': [{'id': 'b2.18', 'q': 'He is {_} years old.', 't': 'fill'},
                                  {'id': 'b2.19', 'q': 'His school is in the {_}.', 't': 'fill'},
                                  {'id': 'b2.20', 'q': 'There are three {_} at his school.', 't': 'fill'},
                                  {'id': 'b2.21', 'q': 'There are many trees and flowers in the {_}.', 't': 'fill'},
                                  {'id': 'b2.22', 'q': 'The students can play football and skip in the {_}.', 't': 'fill'}],
                        'passage': '<p>Hello, everyone. My name is Gia Bao. I’m nine years old. I live in Nam Dinh province with my family. My school is not '
                                   'very big. It’s in the town. There are three buildings, a garden and a yard at my school. The garden has many trees and '
                                   'flowers. The playground is very big. The students can play football, badminton and skip there. I love my school because it '
                                   'is very beautiful.</p>'},
                       {'id': 'c1',
                        'instr': 'I. Look and complete (nhìn tranh, điền từ).',
                        'items': [{'id': 'c1.23', 'img': 'c1_1.png', 'q': 'Can she {_}? – Yes, she can.', 't': 'fill'},
                                  {'id': 'c1.24', 'img': 'c1_2.png', 'q': 'My favourite subject is {_}.', 't': 'fill'},
                                  {'id': 'c1.25', 'img': 'c1_3.png', 'q': '– Were you at the {_} yesterday? – Yes, I was.', 't': 'fill'},
                                  {'id': 'c1.26', 'img': 'c1_4.png', 'q': 'A: What do you do on Tuesday?<br>B: I {_}.', 't': 'fill'},
                                  {'id': 'c1.27', 'img': 'c1_5.png', 'q': 'A: What do you want to drink?<br>B: I want some {_}.', 't': 'fill'}]},
                       {'id': 'c2',
                        'instr': 'Reorder the words (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'c2.28', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['eat?', 'do', 'What', 'to', 'want', 'you']},
                                  {'id': 'c2.29', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['today.', 'It', 'Saturday', 'is']},
                                  {'id': 'c2.30', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['school', 'at', 'go', 'I', 'to', '6.45.']},
                                  {'id': 'c2.31', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['can', 'piano.', 'play', 'She', 'the']},
                                  {'id': 'c2.32',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['in', 'last', 'Da', 'Nang', 'was', 'I', 'summer.']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 1 – Đề 20 (25-26)',
 'unit': 'CuoiKy1'}
