# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ["What's the street like?"],
 't1.10': 'house',
 't1.11': ['I live in a small flat with my parents.'],
 't1.12': 'I live in a small house with my parents.',
 't1.13': 'in',
 't1.14': ['The flat is small and beautiful.'],
 't1.15': "It's a small village.",
 't1.16': 'with',
 't1.17': ['She lives at 15 Le Lai Street.'],
 't1.18': 'She lives in Nguyen Van Troi Street.',
 't1.19': 'Who',
 't1.2': "What's the street like?",
 't1.20': ['They live in a big house with their grandparents.'],
 't1.3': "What's",
 't1.4': "It's a quiet village.",
 't1.5': 'with',
 't1.6': ['The street is small and quiet.'],
 't1.7': "It's a big city.",
 't1.8': 'at',
 't1.9': 'She lives in Nguyen Van Nghi Street.'}

EXPLANATIONS = {'t1.1': "Câu đúng: What's the street like?",
 't1.10': 'Đáp án: house',
 't1.11': 'Câu đúng: I live in a small flat with my parents.',
 't1.12': 'Đáp án: I live in a small house with my parents.',
 't1.13': 'Đáp án: in',
 't1.14': 'Câu đúng: The flat is small and beautiful.',
 't1.15': "Đáp án: It's a small village.",
 't1.16': 'Đáp án: with',
 't1.17': 'Câu đúng: She lives at 15 Le Lai Street.',
 't1.18': 'Đáp án: She lives in Nguyen Van Troi Street.',
 't1.19': 'Đáp án: Who',
 't1.2': "Đáp án: What's the street like?",
 't1.20': 'Câu đúng: They live in a big house with their grandparents.',
 't1.3': "Đáp án: What's",
 't1.4': "Đáp án: It's a quiet village.",
 't1.5': 'Đáp án: with',
 't1.6': 'Câu đúng: The street is small and quiet.',
 't1.7': "Đáp án: It's a big city.",
 't1.8': 'Đáp án: at',
 't1.9': 'Đáp án: She lives in Nguyen Van Nghi Street.'}
