# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Môn học yêu thích của cô ấy là môn Toán.',
 't1.10': 'Thứ Bảy tuần vừa rồi bạn đã ở đâu?',
 't1.11': 'in',
 't1.12': ['I painted a picture of my hometown.'],
 't1.13': 'How many gardens are there at your school?',
 't1.14': 'gardens',
 't1.15': 'There is a garden at his school.',
 't1.16': 'Saturday',
 't1.17': ['How many buildings are there at your school?'],
 't1.18': 'Có một khu vườn ở trường của tôi.',
 't1.19': 'How many',
 't1.2': 'Is',
 't1.20': 'I have it on Wednesday.',
 't1.3': ['Is your sports day in May?'],
 't1.4': 'Why do you like English?',
 't1.5': 'July',
 't1.6': ['The sports day is in December.'],
 't1.7': "No, I wasn't. I was in Sydney.",
 't1.8': 'Where',
 't1.9': ['I was in Bangkok last summer.']}

EXPLANATIONS = {'t1.1': 'Đáp án: Môn học yêu thích của cô ấy là môn Toán.',
 't1.10': 'Đáp án: Thứ Bảy tuần vừa rồi bạn đã ở đâu?',
 't1.11': 'Đáp án: in',
 't1.12': 'Câu đúng: I painted a picture of my hometown.',
 't1.13': 'Đáp án: How many gardens are there at your school?',
 't1.14': 'Đáp án: gardens',
 't1.15': 'Đáp án: There is a garden at his school.',
 't1.16': 'Đáp án: Saturday',
 't1.17': 'Câu đúng: How many buildings are there at your school?',
 't1.18': 'Đáp án: Có một khu vườn ở trường của tôi.',
 't1.19': 'Đáp án: How many',
 't1.2': 'Đáp án: Is',
 't1.20': 'Đáp án: I have it on Wednesday.',
 't1.3': 'Câu đúng: Is your sports day in May?',
 't1.4': 'Đáp án: Why do you like English?',
 't1.5': 'Đáp án: July',
 't1.6': 'Câu đúng: The sports day is in December.',
 't1.7': "Đáp án: No, I wasn't. I was in Sydney.",
 't1.8': 'Đáp án: Where',
 't1.9': 'Câu đúng: I was in Bangkok last summer.'}
