# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u18-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What does it say?', 'How can I get to the sports centre?', "Where's the bookshop?", 'How much is the T-shirt?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về địa điểm?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['What', 'How', 'How much', 'When'], 'plain': True, 'q': 'A: ___________ is that skirt?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["It's near the gift shop.",
                                         'Go straight and turn left at the corner.',
                                         "It's ninety thousand dong.",
                                         "Great! Let's go.",
                                         "They're one hundred and ninety thousand dong."],
                                   'plain': True,
                                   'q': 'How much is the skirt?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['between', 'those', 'over there', 'it', 'get', 'near'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. A: Excuse me, is there a shopping centre _____ here?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['pet', 'shop?', 'the', 'is', 'Where']},
                                  {'id': 't1.6',
                                   'o': ['How much is the skirt?', 'How many skirts are there?', "Where's the gift shop?", 'How can I get to the gift shop?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về giá cả?',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['It', "It's", 'They', "They're"], 'plain': True, 'q': 'A: How much are these pants?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ["It's near the gift shop.",
                                         'Go straight and turn left at the corner.',
                                         "It's ninety thousand dong.",
                                         "Great! Let's go.",
                                         "They're one hundred and ninety thousand dong."],
                                   'plain': True,
                                   'q': 'Where is the pet shop?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['between', 'those', 'over there', 'it', 'get', 'near'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 2. A: How can I _____ there?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', "It's", 'bookshop.', 'behind']},
                                  {'id': 't1.11',
                                   'o': ['Where are you?', "Where's the food shop?", 'How much is the T-shirt?', 'What does it say?'],
                                   'plain': True,
                                   'q': 'Câu "It\'s between the sports shop and the bookshop." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['How', 'How much', 'What', 'Where'],
                                   'plain': True,
                                   'q': 'A: ___________ is the gift shop?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ["It's near the gift shop.",
                                         'Go straight and turn left at the corner.',
                                         "It's ninety thousand dong.",
                                         "Great! Let's go.",
                                         "They're one hundred and ninety thousand dong."],
                                   'plain': True,
                                   'q': 'How much are those trousers?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['between', 'those', 'over there', 'it', 'get', 'near'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____. It's near the bookshop.",
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['shop', 'bookshop.', 'the', 'opposite', 'The', 'is', 'pet']},
                                  {'id': 't1.16',
                                   'o': ["It's ninety thousand dong.", "It's over there.", "It's opposite the gift shop.", 'It says "Stop".'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “How much is the school bag?”',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ['this', 'that', 'these', 'they'], 'plain': True, 'q': 'How much are ___________ trousers?', 't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ["It's near the gift shop.",
                                         'Go straight and turn left at the corner.',
                                         "It's ninety thousand dong.",
                                         "Great! Let's go.",
                                         "They're one hundred and ninety thousand dong."],
                                   'plain': True,
                                   'q': 'How can I get to the bookshop?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['between', 'those', 'over there', 'it', 'get', 'near'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____ the bookshop and the bakery.",
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['museum.', 'opposite', 'the', 'bakery', 'The', 'is']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 18 – At the shopping centre: Kiểm tra 1',
 'unit': 18}
