# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-hsg-b3',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'I. Circle the odd one out. (Chọn từ khác loại.)',
                        'items': [{'id': 'a.1', 'o': ['art', 'maths', 'subject', 'science'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.2', 'o': ['when', 'why', 'watch', 'how'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.3', 'o': ['June', 'August', 'weather', 'December'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.4', 'o': ['book', 'pen', 'rubber', 'house'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.5', 'o': ['teacher', 'daughter', 'sister', 'aunt'], 'q': 'Chọn từ khác loại.', 't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'II. Circle the word which has the underlined part pronounced differently from the others. (Chọn từ có phần gạch chân phát âm '
                                 'khác.)',
                        'items': [{'id': 'b.6',
                                   'o': ['h<u>ar</u>d', 'c<u>ar</u>ry', 'c<u>ar</u>d', 'y<u>ar</u>d'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['w<u>e</u>ll', 'g<u>e</u>t', 's<u>e</u>nd', 'pr<u>e</u>tty'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['w<u>ea</u>ther', 'r<u>ea</u>dy', 'm<u>ea</u>n', 'h<u>ea</u>d'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['br<u>ea</u>k', 'm<u>ea</u>n', 'pl<u>ea</u>se', 'm<u>ea</u>t'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'}]},
                       {'id': 'c',
                        'instr': 'III. Circle the word or phrase that best completes the sentence. (Chọn từ/cụm từ đúng.)',
                        'items': [{'id': 'c.10',
                                   'o': ['practice', 'practices', 'is practicing', 'practiced'],
                                   'q': 'She _________ yoga regularly.',
                                   't': 'mcq'},
                                  {'id': 'c.11',
                                   'o': ['teaches', 'teach', 'is teaching', 'teached'],
                                   'q': 'She _________ English at the local school.',
                                   't': 'mcq'},
                                  {'id': 'c.12', 'o': ['rise', 'is rising', 'rises', 'rised'], 'q': 'The sun _________ early in the morning.', 't': 'mcq'},
                                  {'id': 'c.13', 'o': ['plan', 'plans', 'are planning', 'planned'], 'q': 'They _________ a vacation next month.', 't': 'mcq'},
                                  {'id': 'c.14',
                                   'o': ['attend', 'attends', 'are attending', 'attended'],
                                   'q': 'They _________ a concert last Friday.',
                                   't': 'mcq'},
                                  {'id': 'c.15', 'o': ['enjoy', 'enjoys', 'are enjoying', 'enjoyed'], 'q': 'We _________ hiking in the mountains.', 't': 'mcq'},
                                  {'id': 'c.16', 'o': ['ate', 'are eating', 'eats', 'eat'], 'q': 'We _________ dinner at 7 p.m.', 't': 'mcq'},
                                  {'id': 'c.17', 'o': ['are taking', 'take', 'takes', 'taked'], 'q': 'We usually _________ a walk after dinner.', 't': 'mcq'},
                                  {'id': 'c.18',
                                   'o': ['watch', 'watches', 'are watching', 'watched'],
                                   'q': 'We _________ a movie at home last night.',
                                   't': 'mcq'},
                                  {'id': 'c.19',
                                   'o': ['go to', 'goes to', 'are going to', 'went to'],
                                   'q': 'We _________ the theater tomorrow night.',
                                   't': 'mcq'}]},
                       {'id': 'd',
                        'instr': 'IV. Put the verbs in brackets into the correct form. (Chia động từ trong ngoặc.)',
                        'items': [{'id': 'd.20', 'q': '{_} she {_} (read) a book right now?', 't': 'fill'},
                                  {'id': 'd.21', 'q': '{_} we {_} (swim) at the pool today?', 't': 'fill'},
                                  {'id': 'd.22', 'q': '{_} they {_} (watch) movies on Fridays?', 't': 'fill'},
                                  {'id': 'd.23', 'q': '{_} the Sun {_} (rise) in the east?', 't': 'fill'},
                                  {'id': 'd.24', 'q': 'We {_} (not visit) grandma next week.', 't': 'fill'},
                                  {'id': 'd.25', 'q': 'He {_} (walk) to school last morning.', 't': 'fill'},
                                  {'id': 'd.26', 'q': 'We {_} (not go) to the park tomorrow.', 't': 'fill'},
                                  {'id': 'd.27', 'q': '{_} they {_} (play) video games together last weekend?', 't': 'fill'}]},
                       {'id': 'e',
                        'instr': 'V. Match the questions with the answers. (Nối câu hỏi với câu trả lời.)',
                        'items': [{'id': 'e.28',
                                   'left': [{'t': 'How old is your brother?'},
                                            {'t': 'Where is Hakim from?'},
                                            {'t': 'What are they doing?'},
                                            {'t': 'Nice to meet you, Son.'},
                                            {'t': 'Are they your friends?'}],
                                   'o': ['They’re doing their homework.',
                                         'It’s nice to meet you, too, Ha.',
                                         "He's six.",
                                         'Yes, they’re.',
                                         'He’s from Malaysia.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'wrfix',
                        'instr': 'VI. Find and correct the mistakes in each sentence. (Tìm lỗi sai và viết lại câu đúng.)',
                        'items': [{'id': 'wrfix.29', 'q': 'Câu sai: <i>He walk to school in the morning.</i><br>Viết lại câu đúng: {_}', 't': 'fill'},
                                  {'id': 'wrfix.30', 'q': 'Câu sai: <i>They watched movies on Fridays.</i><br>Viết lại câu đúng: {_}', 't': 'fill'},
                                  {'id': 'wrfix.31', 'q': 'Câu sai: <i>He walks to school this morning.</i><br>Viết lại câu đúng: {_}', 't': 'fill'},
                                  {'id': 'wrfix.32', 'q': 'Câu sai: <i>They watch a movie tonight.</i><br>Viết lại câu đúng: {_}', 't': 'fill'},
                                  {'id': 'wrfix.33', 'q': 'Câu sai: <i>The Sun shines brightly yesterday.</i><br>Viết lại câu đúng: {_}', 't': 'fill'}]},
                       {'id': 'f',
                        'instr': 'VII. Read the passage and answer the questions. (Đọc đoạn văn và trả lời câu hỏi – đối chiếu đáp án mẫu sau khi nộp.)',
                        'items': [{'id': 'f.34', 'q': 'Who goes to Hogwarts School?', 't': 'open'},
                                  {'id': 'f.35', 'q': 'How do students get to school on their first day?', 't': 'open'},
                                  {'id': 'f.36', 'q': 'What do the students wear for their uniforms?', 't': 'open'},
                                  {'id': 'f.37', 'q': 'What do owls do for the students?', 't': 'open'},
                                  {'id': 'f.38', 'q': 'What do players use to hit the ball in a quidditch?', 't': 'open'}],
                        'passage': '<p>Hogwarts is a very special school: it is a school for young witches and wizards. It is located near a lake in Scotland, '
                                   'but its students come from Scotland, England, Ireland and Wales. School begins on September 1, and students all get on a '
                                   'special train in London to go to school together. Hogwarts is a boarding school, so students have classes and live at the '
                                   'school. They have to wear robes as their uniform. Each student has an owl for a pet. The owls also carry letters from '
                                   'families. All students play a sport called “quidditch”, a kind of flying soccer. Players try to hit the ball with a stick '
                                   'while mounting their flying brooms.</p>'},
                       {'id': 'g',
                        'instr': 'VIII. Reorder the words to make correct sentences. (Sắp xếp từ thành câu đúng.)',
                        'items': [{'id': 'g.39', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['We', "don't", 'go', 'swimming', 'on', 'Saturdays.']},
                                  {'id': 'g.40',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['He', "doesn't", 'walk', 'to', 'school', 'in', 'the', 'morning.']},
                                  {'id': 'g.41', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Am', 'I', 'playing', 'soccer', 'after', 'school?']},
                                  {'id': 'g.42', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Is', 'she', 'reading', 'a', 'book', 'right', 'now?']},
                                  {'id': 'g.43',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['They', "didn't", 'watch', 'a', 'movie', 'last', 'Friday.']}]},
                       {'id': 'h',
                        'instr': 'IX. Rewrite the following sentences in such another way which has the same meaning as the first one. (Viết lại câu – đối '
                                 'chiếu đáp án mẫu sau khi nộp.)',
                        'items': [{'id': 'h.44',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>My room is smaller than your room.</i><br><b>Your room …</b>',
                                   't': 'open'},
                                  {'id': 'h.45',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>No house in the street is older than this house.</i><br><b>This house '
                                        '…</b>',
                                   't': 'open'},
                                  {'id': 'h.46',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>Quang is 1.75 meters tall. Vinh is 1.65 meters tall.</i><br><b>Vinh is '
                                        '…</b>',
                                   't': 'open'},
                                  {'id': 'h.47',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>Hang is the fattest girl in my class.</i><br><b>No girl …</b>',
                                   't': 'open'},
                                  {'id': 'h.48',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>The Red River is 1,200 kilometers long. The Nile River is 6,437 '
                                        'kilometers long.</i><br><b>The Nile River is much …</b>',
                                   't': 'open'}]}],
            'id': 'kiem-tra',
            'minutes': 40,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'HSG – Bộ đề ôn thi – Đề 3',
 'unit': 'HSG'}
