# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'gi.1': 'd',
 'gi.2': 'c',
 'gi.3': 'b',
 'gi.4': 'a',
 'gii.5': {'blanks': [['c'], ['a'], ['d'], ['b']]},
 'giii.6': ['water park'],
 'giii.7': ['skirt'],
 'giii.8': ['crocodiles'],
 'giii.9': ['rainy'],
 'giv.10': 'B',
 'giv.11': 'A',
 'giv.12': 'C',
 'giv.13': 'B',
 'gv.14': ['Where’s the water park?'],
 'gv.15': ['What are these animals?'],
 'gv.16': ['Do you want to go to the farm?'],
 'gvi.17': 'F',
 'gvi.18': 'T',
 'gvi.19': 'F',
 'gvii.20': ['sunny'],
 'gvii.21': ['tent'],
 'gvii.22': ['campfire'],
 'gvii.23': ['dancing'],
 'gviii.24': ['They’re singing songs.'],
 'gviii.25': ['It says ‘turn round’.'],
 'gviii.26': ['Sorry, I can’t.'],
 'gviii.27': ['Because they dance beautifully.']}

EXPLANATIONS = {'gi.1': 'Câu 1 ứng với tranh d (theo đáp án của đề).',
 'gi.2': 'Câu 2 ứng với tranh c (theo đáp án của đề).',
 'gi.3': 'Câu 3 ứng với tranh b (theo đáp án của đề).',
 'gi.4': 'Câu 4 ứng với tranh a (theo đáp án của đề).',
 'gii.5': 'Đáp án theo đáp án của đề: 1–c, 2–a, 3–d, 4–b',
 'giii.6': 'Đáp án: water park',
 'giii.7': 'Đáp án: skirt',
 'giii.8': 'Đáp án: crocodiles',
 'giii.9': 'Đáp án: rainy',
 'giv.10': 'Đáp án: B. Because they roar loudly.',
 'giv.11': 'Đáp án: A. It’s next to the gift shop.',
 'giv.12': 'Đáp án: C. She’s playing tug of war.',
 'giv.13': 'Đáp án: B. How much is the skirt?',
 'gv.14': 'Câu hỏi đúng: Where’s the water park?',
 'gv.15': 'Câu hỏi đúng: What are these animals?',
 'gv.16': 'Câu hỏi đúng: Do you want to go to the farm?',
 'gvi.17': 'Đáp án: False (theo đáp án của đề).',
 'gvi.18': 'Đáp án: True (theo đáp án của đề).',
 'gvi.19': 'Đáp án: False (theo đáp án của đề).',
 'gvii.20': 'Đáp án: sunny',
 'gvii.21': 'Đáp án: tent',
 'gvii.22': 'Đáp án: campfire',
 'gvii.23': 'Đáp án: dancing',
 'gviii.24': 'Câu trả lời đúng: They’re singing songs.',
 'gviii.25': 'Câu trả lời đúng: It says ‘turn round’.',
 'gviii.26': 'Câu trả lời đúng: Sorry, I can’t.',
 'gviii.27': 'Câu trả lời đúng: Because they dance beautifully.'}
