# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u6-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Where is your school?',
                                         'Where are you?',
                                         'How many buildings are there at your school?',
                                         "What's the name of your school?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về tên trường?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['How', 'When', 'Where', 'What'], 'plain': True, 'q': 'A: ____________ is your school, Nam?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['There is a garden at her school.',
                                         "It's in the town.",
                                         'There are two computer rooms at his school.',
                                         'Nguyen Du Primary School.',
                                         'There is a playground at my school.'],
                                   'plain': True,
                                   'q': "Where's her school?",
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: Hi. I'm Minh. _____ is your school, Bill?",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'school?', 'name', 'of', 'is', 'What', 'your']},
                                  {'id': 't1.6',
                                   'o': ['Where are you from?', 'Where are you?', 'Where is your school?', 'How many playgrounds are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi “Trường bạn ở đâu?”',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There ____________ a big playground at my school.',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['There is a garden at her school.',
                                         "It's in the town.",
                                         'There are two computer rooms at his school.',
                                         'Nguyen Du Primary School.',
                                         'There is a playground at my school.'],
                                   'plain': True,
                                   'q': "What's the name of your school?",
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: 2. A: I'm _____ Thailand. And you?",
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'Where', 'school?', 'is']},
                                  {'id': 't1.11',
                                   'o': ['Có một khu vườn ở trường của tôi.',
                                         'Có một sân chơi ở trường của tôi.',
                                         'Có một toà nhà ở trường của tôi.',
                                         'Có một thị trấn không xa trường của tôi.'],
                                   'plain': True,
                                   'q': 'Câu “There\'s one playground at my school." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['room', 'garden', 'playgrounds', 'building'],
                                   'plain': True,
                                   'q': 'How many ____________ are there at your school?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['There is a garden at her school.',
                                         "It's in the town.",
                                         'There are two computer rooms at his school.',
                                         'Nguyen Du Primary School.',
                                         'There is a playground at my school.'],
                                   'plain': True,
                                   'q': 'How many playgrounds are there at your school?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: A: Where's your _____?",
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['village.', 'is', 'a', 'My', 'in', 'school']},
                                  {'id': 't1.16',
                                   'o': ['There are two playrounds at my school.',
                                         "It's in the village.",
                                         'There is a big garden.',
                                         'We can play sports in the playground.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where’s your school?”?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There ____________ two computer rooms at my school.',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['There is a garden at her school.',
                                         "It's in the town.",
                                         'There are two computer rooms at his school.',
                                         'Nguyen Du Primary School.',
                                         'There is a playground at my school.'],
                                   'plain': True,
                                   'q': 'How many gardens are there at her school?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____ the mountains.",
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['There', 'at', 'garden', 'a', 'school.', 'two', 'big', 'my', 'playgrounds', 'are', 'and']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 6 – Our school facilities: Kiểm tra 1',
 'unit': 6}
