# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on1-de6',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Listening – Part 1. Listen and tick (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l1.1',
                                   'img': 'l1_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.2',
                                   'img': 'l1_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.3',
                                   'img': 'l1_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.4',
                                   'img': 'l1_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'l2',
                        'instr': 'Listening – Part 2. Listen and number (nghe và đánh số; tranh B là ví dụ).',
                        'items': [{'id': 'l2.5', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh A là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.6', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh C là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.7', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh D là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.8', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh E là câu số mấy trong bài nghe?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de6/l2.png" alt="Tranh">'},
                       {'id': 'l3',
                        'instr': 'Listening – Part 3. Listen and draw line (nghe và nối số thứ tự với tranh; câu 0 – tranh B là ví dụ).',
                        'items': [{'id': 'l3.9',
                                   'left': [{'t': 'Câu 1'}, {'t': 'Câu 2'}, {'t': 'Câu 3'}, {'t': 'Câu 4'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de6/l3.png" alt="Tranh">'},
                       {'id': 'l4',
                        'instr': 'Listening – Part 4. Listen and write (nghe và điền từ).',
                        'items': [{'id': 'l4.10', 'q': 'I’m from {_}.', 't': 'fill'},
                                  {'id': 'l4.11', 'q': 'I want to be a {_} teacher.', 't': 'fill'},
                                  {'id': 'l4.12', 'q': 'He likes {_}.', 't': 'fill'},
                                  {'id': 'l4.13', 'q': 'When’s your birthday? – It’s in {_}.', 't': 'fill'}]},
                       {'id': 'r1',
                        'instr': 'Reading – Part 1. Read and match the words with pictures (nối từ với tranh; tranh B là ví dụ).',
                        'items': [{'id': 'r1.14',
                                   'left': [{'t': 'grapes'}, {'t': 'English teacher'}, {'t': 'Britain'}, {'t': 'listen to music'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de6/r1.png" alt="Tranh">'},
                       {'id': 'r2',
                        'instr': 'Reading – Part 2. Read and choose A, B or C to complete the text (đọc, chọn từ điền vào chỗ trống).',
                        'items': [{'id': 'r2.15', 'o': ['do', 'can', 'is'], 'q': 'Chọn từ điền vào chỗ trống (1).', 't': 'mcq'},
                                  {'id': 'r2.16', 'o': ['play', 'does', 'do'], 'q': 'Chọn từ điền vào chỗ trống (2).', 't': 'mcq'},
                                  {'id': 'r2.17', 'o': ['on', 'to', 'and'], 'q': 'Chọn từ điền vào chỗ trống (3).', 't': 'mcq'}],
                        'passage': '<p>There are four people in my family. My father <b>(1) ______</b> swim very well. My mother can cook but she can’t <b>(2) '
                                   '______</b> the piano. My brother can play football and play the guitar but he can’t dance. I like music, I can sing <b>(3) '
                                   '______</b> dance but I can’t cook.</p>'},
                       {'id': 'r3',
                        'instr': 'Reading – Part 3. Read and tick True or False (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'r3.18', 'q': 'Mary and Lucy go to school from Mondays to Fridays.', 't': 'tf'},
                                  {'id': 'r3.19', 'q': 'At the weekend, they don’t stay at home.', 't': 'tf'},
                                  {'id': 'r3.20', 'q': 'On Saturdays, they do homework.', 't': 'tf'}],
                        'passage': '<p>Hello. My name is Lucy. It is Wednesday today. It is a school day. My friend Mary and I go to school on Mondays, '
                                   'Tuesdays, Wednesdays, Thursdays and Fridays. At the weekend, we stay at home. We do housework on Saturdays. We listen to '
                                   'music and watch TV on Sundays.</p>'},
                       {'id': 'w1',
                        'instr': 'Writing – Part 1. Look at the pictures and the letters. Write the words (nhìn tranh, sắp xếp chữ cái thành từ).',
                        'items': [{'id': 'w1.21', 'img': 'w1_1.png', 'q': 'Sắp xếp các chữ cái: <b>shicp</b> → {_}', 't': 'fill'},
                                  {'id': 'w1.22', 'img': 'w1_2.png', 'q': 'Sắp xếp các chữ cái: <b>misw</b> → {_}', 't': 'fill'},
                                  {'id': 'w1.23', 'img': 'w1_3.png', 'q': 'Sắp xếp các chữ cái: <b>cecisen</b> → {_}', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Writing – Part 2. Rearrange the words to make the sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w2.24', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['six', 'I', 'at', 'breakfast', 'have', 'fifteen.']},
                                  {'id': 'w2.25', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['want', 'do', 'What', 'to', 'you', 'eat?']},
                                  {'id': 'w2.26', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['school', 'has', 'My', 'playground.', 'a']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK1 – Đề 6',
 'unit': 'OnHK1'}
