# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a1.1': 'A',
 'a1.2': 'B',
 'a1.3': 'B',
 'a1.4': 'A',
 'a2.5': 'B',
 'a2.6': 'C',
 'a2.7': 'D',
 'a2.8': 'A',
 'a3.10': 'F',
 'a3.9': 'T',
 'a4.11': ['Malaysia'],
 'a4.12': ['Science'],
 'b1.13': 'T',
 'b1.14': 'F',
 'b1.15': 'F',
 'b1.16': 'T',
 'b1.17': 'F',
 'b2.18': ['village'],
 'b2.19': ['6 o’clock', 'six o’clock', '6', 'six'],
 'b2.20': ['English'],
 'b2.21': ['English teacher'],
 'b2.22': ['singer'],
 'c1.23': ['go to bed'],
 'c1.24': ['at the zoo'],
 'c1.25': ['buildings'],
 'c1.26': ['painter'],
 'c1.27': ['lemonade'],
 'c2.28': ['Where were you yesterday?'],
 'c2.29': ['I listen to music on Sundays.'],
 'c2.30': ['I have music on Thursdays.'],
 'c2.31': ['I have breakfast at six forty-five.'],
 'c2.32': ['My favourite subject is maths.']}

EXPLANATIONS = {'a1.1': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.2': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.3': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.4': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a2.5': 'Câu 1 ứng với tranh B (theo đáp án của đề).',
 'a2.6': 'Câu 2 ứng với tranh C (theo đáp án của đề).',
 'a2.7': 'Câu 3 ứng với tranh D (theo đáp án của đề).',
 'a2.8': 'Câu 4 ứng với tranh A (theo đáp án của đề).',
 'a3.10': 'Đáp án: False (theo đáp án của đề: ✗).',
 'a3.9': 'Đáp án: True (theo đáp án của đề: ✓).',
 'a4.11': 'Đáp án: Malaysia',
 'a4.12': 'Đáp án: Science',
 'b1.13': 'Đáp án: True (theo đáp án của đề).',
 'b1.14': 'Đáp án: False (theo đáp án của đề).',
 'b1.15': 'Đáp án: False (theo đáp án của đề).',
 'b1.16': 'Đáp án: True (theo đáp án của đề).',
 'b1.17': 'Đáp án: False (theo đáp án của đề).',
 'b2.18': 'Đáp án: village',
 'b2.19': 'Đáp án: 6 o’clock',
 'b2.20': 'Đáp án: English',
 'b2.21': 'Đáp án: English teacher',
 'b2.22': 'Đáp án: singer',
 'c1.23': 'Đáp án: go to bed',
 'c1.24': 'Đáp án: at the zoo',
 'c1.25': 'Đáp án: buildings',
 'c1.26': 'Đáp án: painter',
 'c1.27': 'Đáp án: lemonade',
 'c2.28': 'Câu đúng: Where were you yesterday?',
 'c2.29': 'Câu đúng: I listen to music on Sundays.',
 'c2.30': 'Câu đúng: I have music on Thursdays.',
 'c2.31': 'Câu đúng: I have breakfast at six forty-five.',
 'c2.32': 'Câu đúng: My favourite subject is maths.'}
