# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a.1': 'C',
 'a.2': 'C',
 'a.3': 'C',
 'a.4': 'D',
 'a.5': 'A',
 'b.6': 'B',
 'b.7': 'D',
 'b.8': 'C',
 'b.9': 'A',
 'c.10': 'B',
 'c.11': 'A',
 'c.12': 'C',
 'c.13': 'C',
 'c.14': 'D',
 'c.15': 'A',
 'c.16': 'D',
 'c.17': 'B',
 'c.18': 'D',
 'c.19': 'C',
 'd.20': {'blanks': [['Is'], ['reading']]},
 'd.21': {'blanks': [['Are'], ['swimming']]},
 'd.22': {'blanks': [['Do'], ['watch']]},
 'd.23': {'blanks': [['Does'], ['rise']]},
 'd.24': {'blanks': [['aren’t visiting']]},
 'd.25': {'blanks': [['walked']]},
 'd.26': {'blanks': [['aren’t going']]},
 'd.27': {'blanks': [['Did'], ['play']]},
 'e.28': {'blanks': [["He's six."], ['He’s from Malaysia.'], ['They’re doing their homework.'], ['It’s nice to meet you, too, Ha.'], ['Yes, they’re.']]},
 'g.39': ["We don't go swimming on Saturdays."],
 'g.40': ["He doesn't walk to school in the morning."],
 'g.41': ['Am I playing soccer after school?'],
 'g.42': ['Is she reading a book right now?'],
 'g.43': ["They didn't watch a movie last Friday."],
 'wrfix.29': ['He walks to school in the morning.'],
 'wrfix.30': ['They watch movies on Fridays.'],
 'wrfix.31': ['He is walking to school this morning.'],
 'wrfix.32': ['They are watching a movie tonight.'],
 'wrfix.33': ['The Sun shone brightly yesterday.']}

EXPLANATIONS = {'a.1': 'Đáp án: C. subject',
 'a.2': 'Đáp án: C. watch',
 'a.3': 'Đáp án: C. weather',
 'a.4': 'Đáp án: D. house',
 'a.5': 'Đáp án: A. teacher',
 'b.6': 'Đáp án: B. c<u>ar</u>ry',
 'b.7': 'Đáp án: D. pr<u>e</u>tty',
 'b.8': 'Đáp án: C. m<u>ea</u>n',
 'b.9': 'Đáp án: A. br<u>ea</u>k',
 'c.10': 'Đáp án: B. practices',
 'c.11': 'Đáp án: A. teaches',
 'c.12': 'Đáp án: C. rises',
 'c.13': 'Đáp án: C. are planning',
 'c.14': 'Đáp án: D. attended',
 'c.15': 'Đáp án: A. enjoy',
 'c.16': 'Đáp án: D. eat',
 'c.17': 'Đáp án: B. take',
 'c.18': 'Đáp án: D. watched',
 'c.19': 'Đáp án: C. are going to',
 'd.20': 'Đáp án: Is / reading',
 'd.21': 'Đáp án: Are / swimming',
 'd.22': 'Đáp án: Do / watch',
 'd.23': 'Đáp án: Does / rise',
 'd.24': 'Đáp án: aren’t visiting',
 'd.25': 'Đáp án: walked',
 'd.26': 'Đáp án: aren’t going',
 'd.27': 'Đáp án: Did / play',
 'e.28': '1–C; 2–E; 3–A; 4–B; 5–D (theo đáp án của đề).',
 'f.34': 'Đáp án mẫu (theo đáp án của đề): <b>Young witches and wizards</b>',
 'f.35': 'Đáp án mẫu (theo đáp án của đề): <b>By train</b>',
 'f.36': 'Đáp án mẫu (theo đáp án của đề): <b>Robes</b>',
 'f.37': 'Đáp án mẫu (theo đáp án của đề): <b>Carry letters from families</b>',
 'f.38': 'Đáp án mẫu (theo đáp án của đề): <b>A stick</b>',
 'g.39': "Câu đúng: We don't go swimming on Saturdays.",
 'g.40': "Câu đúng: He doesn't walk to school in the morning.",
 'g.41': 'Câu đúng: Am I playing soccer after school?',
 'g.42': 'Câu đúng: Is she reading a book right now?',
 'g.43': "Câu đúng: They didn't watch a movie last Friday.",
 'h.44': 'Đáp án mẫu (theo đáp án của đề): <b>Your room is bigger than my room.</b>',
 'h.45': 'Đáp án mẫu (theo đáp án của đề): <b>This house is the oldest in the street.</b>',
 'h.46': 'Đáp án mẫu (theo đáp án của đề): <b>Vinh is shorter than Quang.</b>',
 'h.47': 'Đáp án mẫu (theo đáp án của đề): <b>No girl in my class is fatter than Hang.</b>',
 'h.48': 'Đáp án mẫu (theo đáp án của đề): <b>The Nile River is much longer than the Red River.</b>',
 'wrfix.29': 'Sửa lỗi: walk → walks. Câu đúng: He walks to school in the morning.',
 'wrfix.30': 'Sửa lỗi: watched → watch. Câu đúng: They watch movies on Fridays.',
 'wrfix.31': 'Sửa lỗi: walks → is walking. Câu đúng: He is walking to school this morning.',
 'wrfix.32': 'Sửa lỗi: watch → are watching. Câu đúng: They are watching a movie tonight.',
 'wrfix.33': 'Sửa lỗi: shines → shone. Câu đúng: The Sun shone brightly yesterday.'}
