# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r4-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['What was the weather like yesterday?',
                                         'What does your brother loook like?',
                                         'Where do you go on Sundays?',
                                         'Do you want to go to the supermarket?'],
                                   'plain': True,
                                   'q': 'Câu “It was rainy.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['What was the weather like in Da Lat?',
                                         'What was the weather like in Da Lat last weekend?',
                                         'Do you want to go to Da Lat?',
                                         'It was sunny in Da Lat.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Cuối tuần trước thời tiết ở Đà Lạt như thế nào?”',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Go straight and turn left.',
                                         'There is a bookshop in Nguyen Thi Minh Khai Street.',
                                         'Thank you very much for your help.',
                                         'The zoo is on the right.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: How can I get to the zoo?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['Is there a post office near here?',
                                         'How can I get the the post office?',
                                         'What do you want to buy at the post office?',
                                         'Do you want to go to the post office with me?'],
                                   'plain': True,
                                   'q': 'Câu: “Go straight and turn right" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['Where are you?', "Where's the stadium?", 'How much is the skirt?', 'What does it say?'],
                                   'plain': True,
                                   'q': 'Câu “It\'s near the park." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['What do you do on Sunday mornings?', 'What does it say?', 'How much is that shirt?', 'How many T-shirts are there?'],
                                   'plain': True,
                                   'q': "Câu “It's one hundred and fifty thousand dong.” trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['What are those animals?',
                                         'Why do you like those animals?',
                                         'What animals dance beautifully?',
                                         'What animals do you want to see?'],
                                   'plain': True,
                                   'q': 'Câu: “They are hippos" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ["They're giraffes.", 'Because they run quickly.', 'Because they roar loudly.', 'Because they look strong.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like giraffes?”',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['This is Lan.', "She's at the campsite.", 'Yes, she is.', "She's telling a story."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What is Lan doing?”?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ["She's building a campfire.", "He's taking photos.", 'They are at the campsite.', 'They are playing badminton.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What is Mike doing?”?',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1',
                                   'o': ['What', 'Where', 'How', 'When'],
                                   'plain': True,
                                   'q': 'A: (1) ______________ was the weather like yesterday?',
                                   't': 'mcq'},
                                  {'id': 'b.2',
                                   'o': ['bakery', 'food stall', 'bookshop', 'pet shop'],
                                   'plain': True,
                                   'q': 'A: Do you want to go to the ______________ with me?',
                                   't': 'mcq'},
                                  {'id': 'b.3',
                                   'o': ['cinema', 'bakery', 'food stall', 'post office'],
                                   'plain': True,
                                   'q': 'I want to buy some stamps. Is there a _____________ near here?',
                                   't': 'mcq'},
                                  {'id': 'b.4',
                                   'o': ['bakery', 'bookshop', 'sports centre', 'swimming pool'],
                                   'plain': True,
                                   'q': 'I want to buy some bread. How can I get to the _____________?',
                                   't': 'mcq'},
                                  {'id': 'b.5', 'o': ['How', 'How much', 'What', 'Where'], 'plain': True, 'q': 'A: ___________ is the pet shop?', 't': 'mcq'},
                                  {'id': 'b.6', 'o': ['behind', 'between', 'opposite', 'next'], 'plain': True, 'q': 'A: Where is the sports shop?', 't': 'mcq'},
                                  {'id': 'b.7', 'o': ['What', 'Where', 'When', 'Why'], 'plain': True, 'q': 'A: ____________ do you like peacocks?', 't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['because', 'because it', 'because they', 'because that'],
                                   'plain': True,
                                   'q': "She doesn't like lions ____________ roar loudly.",
                                   't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['he is', 'he does', 'they are', 'they do'],
                                   'plain': True,
                                   'q': 'A: Are Bill and Ben at the campsite?',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['doing', 'singing', 'building', 'telling'],
                                   'plain': True,
                                   'q': 'A: Where are Mary and Lucy?',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['What was the weather like last Saturday, Lan?',
                                            'How can I get to the zoo?',
                                            'How much is the skirt?',
                                            'Why do you like monkeys?',
                                            'What are Mai and Lan doing?'],
                                   'o': ["It's two hundred thousand dong.",
                                         'It was rainy.',
                                         'They are building a campfire.',
                                         'Because they are funny.',
                                         'Turn right and go straight.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['like', 'judo', 'Where', 'Are', 'between'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['like', 'judo', 'Where', 'Are', 'between'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['like', 'judo', 'Where', 'Are', 'between'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['like', 'judo', 'Where', 'Are', 'between'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['like', 'judo', 'Where', 'Are', 'between'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': '1. A: Hi, Ben. <b>(1)&nbsp;______</b> were you last weekend?<br>B: I was in Da Lat.<br>A: Great! I like Da Lat.<br>2. B: '
                                   "What was the weather <b>(2)&nbsp;______</b> in Da Lat?<br>A: It was rainy.<br>3. A: Where's the food shop?<br>B: It's "
                                   "<b>(3)&nbsp;______</b> the gift shop and the pet shop.<br>4. A: What's Nam doing at the sports centre?<br>B: He's doing a "
                                   '<b>(4)&nbsp;______</b>.<br>5. A: Hello, Ben. <b>(5)&nbsp;______</b> Mai and her sister at home?<br>B: Yes, they are.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and choose the correct answers. (Đọc và chọn đáp án đúng.)',
                        'items': [{'id': 'e.1',
                                   'o': ['at the shopping centre', 'at the zoo', 'in the bakery', 'in the bookshop'],
                                   'plain': True,
                                   'q': 'Where are Bill and Ben?',
                                   't': 'mcq'},
                                  {'id': 'e.2', 'o': ['sunny', 'rainy', 'windy', 'cloudy'], 'plain': True, 'q': "What's the weather like today?", 't': 'mcq'},
                                  {'id': 'e.3',
                                   'o': ['monkeys', 'crocodiles', 'elephants', 'tigers'],
                                   'plain': True,
                                   'q': 'What animals does Bill like?',
                                   't': 'mcq'},
                                  {'id': 'e.4',
                                   'o': ['monkeys', 'crocodiles', 'elephants', 'tigers'],
                                   'plain': True,
                                   'q': "What animals doesn't Bill like?",
                                   't': 'mcq'},
                                  {'id': 'e.5', 'o': ['monkeys', 'bears', 'elephants', 'bears'], 'plain': True, 'q': 'What animals does Ben like?', 't': 'mcq'},
                                  {'id': 'e.6',
                                   'o': ['are funny', 'are scary', 'are big', 'can climb'],
                                   'plain': True,
                                   'q': "Why doesn't Bill like crocodiles?",
                                   't': 'mcq'},
                                  {'id': 'e.7',
                                   'o': ['are funny', 'are scary', 'are big', 'can climp'],
                                   'plain': True,
                                   'q': "Why doesn't Ben like elephants?",
                                   't': 'mcq'}],
                        'passage': 'Bill and Ben usually go out on Sundays, but last Sunday they stayed home because it was rainy. It is Sunday today and it '
                                   'is sunny. They are at the zoo. There are many different animals at the zoo such as monkeys, elephants, bears, crocodiles, '
                                   "tigers, peacocks, etc. Bill likes monkeys because they look funny. He doesn't like crocodiles because they are scary. Ben "
                                   "wants to see bears because they can climb. He doesn't like elephants because they are big."}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Linh?', 'Where', 'were', 'last', 'weekend,', 'you']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sunny', 'was', 'It', 'and', 'hot.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['get', 'to', 'the', 'I', 'bookshop?', 'How', 'can']},
                                  {'id': 'f.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Dao', 'There', 'Hung', 'Tran', 'is', 'in', 'a', 'Street.', 'bookshop']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['How', 'these', 'hats?', 'much', 'are']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'three', 'thousand', 'dong.', 'hundred', 'It']},
                                  {'id': 'f.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['hippos', 'strong.', 'because', 'likes', 'Minh', 'look', 'they']},
                                  {'id': 'f.8',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['sing', 'Lucy', 'birds', 'because', 'merrily.', 'they', 'likes']},
                                  {'id': 'f.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['are', 'Ben', 'Mary?', 'doing,', 'and', 'Bill', 'What']},
                                  {'id': 'f.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['playing', 'are', 'tug', 'of', 'war.', 'They']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '',
 'title': 'Review 4: Luyện tập',
 'unit': 'Review4'}
