# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['My brother is tall and has a round face.'],
 't1.10': 'slim',
 't1.11': ['What does your sister look like?'],
 't1.12': 'What does he look like?',
 't1.13': 'is',
 't1.14': ['My sister is beautiful and slim.'],
 't1.15': 'What does your brother look like?',
 't1.16': 'look',
 't1.17': ['She has big eyes and long hair.'],
 't1.18': "She's slim.",
 't1.19': 'your sister',
 't1.2': 'What does she look like?',
 't1.20': ['My father is very tall.'],
 't1.3': 'What',
 't1.4': 'She is tall and slim.',
 't1.5': 'does',
 't1.6': ['My father has short hair.'],
 't1.7': 'Cô ấy có đôi mắt to.',
 't1.8': 'big',
 't1.9': 'He is big and short.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: My brother is tall and has a round face.',
 't1.10': 'Đáp án: slim',
 't1.11': 'Câu đúng: What does your sister look like?',
 't1.12': 'Đáp án: What does he look like?',
 't1.13': 'Đáp án: is',
 't1.14': 'Câu đúng: My sister is beautiful and slim.',
 't1.15': 'Đáp án: What does your brother look like?',
 't1.16': 'Đáp án: look',
 't1.17': 'Câu đúng: She has big eyes and long hair.',
 't1.18': "Đáp án: She's slim.",
 't1.19': 'Đáp án: your sister',
 't1.2': 'Đáp án: What does she look like?',
 't1.20': 'Câu đúng: My father is very tall.',
 't1.3': 'Đáp án: What',
 't1.4': 'Đáp án: She is tall and slim.',
 't1.5': 'Đáp án: does',
 't1.6': 'Câu đúng: My father has short hair.',
 't1.7': 'Đáp án: Cô ấy có đôi mắt to.',
 't1.8': 'Đáp án: big',
 't1.9': 'Đáp án: He is big and short.'}
