# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-hsg-b5',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'I. Circle the odd one out. (Chọn từ khác loại.)',
                        'items': [{'id': 'a.1', 'o': ['kite', 'cook', 'sing', 'listen'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.2', 'o': ['read', 'happy', 'young', 'beautiful'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.3', 'o': ['egg', 'apple', 'pen', 'books'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.4', 'o': ['window', 'wall', 'door', 'bus'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.5', 'o': ['May', 'July', 'Monday', 'January'], 'q': 'Chọn từ khác loại.', 't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'II. Circle the word which has the underlined part pronounced differently from the others. (Chọn từ có phần gạch chân phát âm '
                                 'khác.)',
                        'items': [{'id': 'b.6',
                                   'o': ['r<u>ou</u>gh', 's<u>u</u>m', '<u>u</u>tter', '<u>u</u>nion'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['n<u>oo</u>n', 't<u>oo</u>l', 'bl<u>oo</u>d', 'sp<u>oo</u>n'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['<u>ch</u>emist', '<u>ch</u>icken', '<u>ch</u>urch', 'cen<u>t</u>ury'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['th<u>ou</u>ght', 't<u>ou</u>gh', 't<u>au</u>ght', 'b<u>ou</u>ght'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['pl<u>ea</u>sure', 'h<u>ea</u>t', 'm<u>ea</u>t', 'f<u>ee</u>d'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'}]},
                       {'id': 'c',
                        'instr': 'III. Circle the word or phrase that best completes the sentence. (Chọn từ/cụm từ đúng.)',
                        'items': [{'id': 'c.11', 'o': ['is watching', 'watch', 'watches', 'watched'], 'q': 'He _________ television right now.', 't': 'mcq'},
                                  {'id': 'c.12',
                                   'o': ['play', 'plays', 'is playing', 'played'],
                                   'q': 'He _________ basketball with his friends yesterday.',
                                   't': 'mcq'},
                                  {'id': 'c.13',
                                   'o': ['read', 'reads', 'is reading', 'have read'],
                                   'q': 'He _________ the newspaper every morning.',
                                   't': 'mcq'},
                                  {'id': 'c.14', 'o': ['is visiting', 'visit', 'visited', 'visits'], 'q': 'He _________ his parents last weekend.', 't': 'mcq'},
                                  {'id': 'c.15', 'o': ['What', 'When', 'Why', 'Who'], 'q': "_________ do you like monkeys? Because they're funny.", 't': 'mcq'},
                                  {'id': 'c.16', 'o': ['like', 'liking', 'to like', 'liked'], 'q': 'Would you _________ some milk? Yes, please.', 't': 'mcq'},
                                  {'id': 'c.17',
                                   'o': ['What', 'What’s', 'When', 'How'],
                                   'q': "_________ your favorite drink, Mai? – It's orange juice.",
                                   't': 'mcq'},
                                  {'id': 'c.18', 'o': ['What', 'What’s', 'Why', 'How'], 'q': "_________ do they look like? They're tall and slim.", 't': 'mcq'},
                                  {'id': 'c.19', 'o': ['Why', 'When', 'Who', 'What'], 'q': '_________ is stronger? Kevin is stronger.', 't': 'mcq'},
                                  {'id': 'c.20', 'o': ['Why', 'Who', 'Where', 'What'], 'q': '_________ are you doing, Linda?', 't': 'mcq'}]},
                       {'id': 'd',
                        'instr': 'IV. Put the verbs in brackets into the correct form. (Chia động từ trong ngoặc.)',
                        'items': [{'id': 'd.21', 'q': 'She {_} (brush) her teeth before bed last night.', 't': 'fill'},
                                  {'id': 'd.22', 'q': 'He {_} (listen) to music in his room yesterday.', 't': 'fill'},
                                  {'id': 'd.23', 'q': 'She {_} (not dance) ballet in the gym next week.', 't': 'fill'},
                                  {'id': 'd.24', 'q': 'He {_} (not swim) in the pool right now.', 't': 'fill'},
                                  {'id': 'd.25', 'q': 'My mom {_} (not cook) breakfast in the evening.', 't': 'fill'},
                                  {'id': 'd.26', 'q': 'We {_} (not visit) the park at night.', 't': 'fill'},
                                  {'id': 'd.27', 'q': '{_} they {_} (watch) a movie tonight?', 't': 'fill'},
                                  {'id': 'd.28', 'q': 'They {_} (not play) video games together last weekend.', 't': 'fill'},
                                  {'id': 'd.29', 'q': 'We {_} (go) swimming on Saturdays.', 't': 'fill'},
                                  {'id': 'd.30', 'q': 'He {_} (walk) to school in the morning.', 't': 'fill'}]},
                       {'id': 'e',
                        'instr': 'V. Match the questions with the answers. (Nối câu hỏi với câu trả lời.)',
                        'items': [{'id': 'e.31',
                                   'left': [{'t': 'What do you do at the weekend?'},
                                            {'t': 'What does Alex do on Sunday mornings?'},
                                            {'t': 'What is the date today?'},
                                            {'t': 'What is Hakim’s nationality?'},
                                            {'t': 'How many months are there in a year?'}],
                                   'o': ['He goes to school on Sunday mornings.',
                                         'Today is Thursday.',
                                         'I go shopping with my mother.',
                                         'There are twelve months.',
                                         'He is Malaysian.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'wrfix',
                        'instr': 'VI. Find and correct the mistakes in each sentence. (Tìm lỗi sai và viết lại câu đúng.)',
                        'items': [{'id': 'wrfix.32', 'q': "Câu sai: <i>The Sun isn't rise in the west.</i><br>Viết lại câu đúng: {_}", 't': 'fill'},
                                  {'id': 'wrfix.33', 'q': 'Câu sai: <i>Birds aren’t sing in the winter.</i><br>Viết lại câu đúng: {_}', 't': 'fill'},
                                  {'id': 'wrfix.34', 'q': 'Câu sai: <i>We visit grandma this weekend.</i><br>Viết lại câu đúng: {_}', 't': 'fill'},
                                  {'id': 'wrfix.35',
                                   'q': 'Câu sai: <i>Does he listen to music in his room yesterday?</i><br>Viết lại câu đúng: {_}',
                                   't': 'fill'},
                                  {'id': 'wrfix.36',
                                   'q': 'Câu sai: <i>Do they play basketball after school yesterday?</i><br>Viết lại câu đúng: {_}',
                                   't': 'fill'}]},
                       {'id': 'f',
                        'instr': 'VII. Read the passage and answer the questions. (Đọc đoạn văn và trả lời câu hỏi – đối chiếu đáp án mẫu sau khi nộp.)',
                        'items': [{'id': 'f.37', 'q': 'Who is in the first picture from Camp Wannabe?', 't': 'open'},
                                  {'id': 'f.38', 'q': 'What can you say about Ian and Anne?', 't': 'open'},
                                  {'id': 'f.39', 'q': 'Who is in the second picture and where is he from?', 't': 'open'},
                                  {'id': 'f.40', 'q': 'What do we know about Tomas?', 't': 'open'},
                                  {'id': 'f.41', 'q': 'Who is the girl in the third picture and where is she from?', 't': 'open'}],
                        'passage': '<p>These are my friends from Camp Wannabe. In the first picture, you can see Ian and Anne. They are from Ireland. I like '
                                   'them a lot. They’re really nice, and I had a lot of fun with them at the camp. In the second picture, you can see a boy '
                                   'from Poland. His name is Tomas. He’s a very honest boy, and he’s learning English, just like me! He likes playing ice '
                                   'hockey a lot. The girl in the third picture is Kim. She lives in Australia with her family, but her aunt lives in England. '
                                   'I don’t see her because she lives far away, but we chat on the Internet.</p>'},
                       {'id': 'g',
                        'instr': 'VIII. Reorder the words to make correct sentences. (Sắp xếp từ thành câu đúng.)',
                        'items': [{'id': 'g.42', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Do', 'go', 'we', 'on', 'swimming', 'Saturdays?']},
                                  {'id': 'g.43',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['walk', 'Does', 'in', 'he', 'the', 'school', 'to', 'morning?']},
                                  {'id': 'g.44',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['in', 'He', 'right', 'is', 'the', 'pool', 'swimming', 'now.']},
                                  {'id': 'g.45',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['a', 'They', 'watch', 'last', "didn't", 'movie', 'Friday.']},
                                  {'id': 'g.46',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ["didn't", 'The', 'brightly', 'shine', 'Sun', 'yesterday.']}]},
                       {'id': 'h',
                        'instr': 'IX. Rewrite the following sentences in such another way which has the same meaning as the first one. (Viết lại câu – đối '
                                 'chiếu đáp án mẫu sau khi nộp.)',
                        'items': [{'id': 'h.47',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>Mr. Ba rides his motorbike to work every day.</i><br><b>Mr. Ba gets …</b>',
                                   't': 'open'},
                                  {'id': 'h.48',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>My school has six hundred students.</i><br><b>There …</b>',
                                   't': 'open'},
                                  {'id': 'h.49', 'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>Julia is Jack’s sister.</i><br><b>Jack …</b>', 't': 'open'},
                                  {'id': 'h.50',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>The supermarket is behind the bank.</i><br><b>The bank …</b>',
                                   't': 'open'},
                                  {'id': 'h.51',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>The children are walking to school now.</i><br><b>The children are going '
                                        'to …</b>',
                                   't': 'open'}]}],
            'id': 'kiem-tra',
            'minutes': 40,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'HSG – Bộ đề ôn thi – Đề 5',
 'unit': 'HSG'}
