# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk1-de4',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'I. Listen and circle the correct words (nghe và chọn từ đúng).',
                        'items': [{'id': 'l1.1', 'o': ['bed', 'get', 'head'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['jam', 'grapes', 'water'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['Japan', 'juice', 'January'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['yes', 'jet', 'get'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'}]},
                       {'id': 'l2',
                        'instr': 'II. Listen and number the pictures (nghe và đánh số tranh; tranh a là ví dụ = 1).',
                        'items': [{'id': 'l2.5', 'o': ['2', '3', '4', '5'], 'plain': True, 'q': 'Tranh b là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.6', 'o': ['2', '3', '4', '5'], 'plain': True, 'q': 'Tranh c là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.7', 'o': ['2', '3', '4', '5'], 'plain': True, 'q': 'Tranh d là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.8', 'o': ['2', '3', '4', '5'], 'plain': True, 'q': 'Tranh e là câu số mấy trong bài nghe?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_de4/l2.png" alt="Tranh">'},
                       {'id': 'r1',
                        'instr': 'III. Read and tick the correct sentences (nhìn tranh, chọn câu đúng).',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['I go to bed at nine fifteen.', 'I go to bed at nine o’clock.'],
                                   'q': 'What time do you go to bed?',
                                   't': 'mcq'},
                                  {'id': 'r1.10', 'img': 'r1_2.png', 'o': ['I do homework.', 'I do housework.'], 'q': 'What do you do on Fridays?', 't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['I want some grapes.', 'I want some jam.'],
                                   'q': 'What do you want to eat?',
                                   't': 'mcq'},
                                  {'id': 'r1.12', 'img': 'r1_4.png', 'o': ['No, she can.', 'No, she can’t.'], 'q': 'Can she swim?', 't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'IV. Fill in the blanks (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'r2.13', 'img': 'r2_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.14', 'img': 'r2_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'img': 'r2_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'img': 'r2_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>My name is Alice. Every day, I <b>(1) ______</b> at seven o’clock. I brush my teeth and take a shower. At eight '
                                   'o’clock, I <b>(2) ______</b> I eat some bread and some <b>(3) ______</b> and drink a glass of <b>(4) ______</b> Then I go '
                                   'to school by bus. I study at school in the morning. In the afternoon, I go to a football club. I play football with my '
                                   'friends.</p>'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 1 – Đề 4',
 'unit': 'GiuaKy1'}
