# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u8-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['like', 'do', 'you', 'Why', 'Art?']},
                                  {'id': 't1.2',
                                   'o': ['What day is it today?',
                                         'Why do you like Music?',
                                         'How many playgrounds are there at your school?',
                                         'When do you have English?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi lý do ai đó thích môn gì?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['PE', 'IT', 'Science', 'Art'],
                                   'plain': True,
                                   'q': 'I like running. My favourite subject is __________.',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ["It's music.", "It's Thursday.", 'Because I want to be a maths teacher.', 'I have it on Friday.', 'Yes, I do.'],
                                   'plain': True,
                                   'q': 'When do you have Science?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['PE', 'IT', 'English', 'Art'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: My favourite subject is _____.',
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['I', 'become', 'want', 'to', 'painter.', 'Because', 'a']},
                                  {'id': 't1.7',
                                   'o': ['I have maths on Mondays and Thursdays.',
                                         'I have maths and Vietnamese.',
                                         'Because I want to be a Maths teacher.',
                                         'Because I want to be an English teacher.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like Maths?"',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['Where', 'Why', 'What', 'How'], 'plain': True, 'q': 'A: __________ do you like Music?', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ["It's music.", "It's Thursday.", 'Because I want to be a maths teacher.', 'I have it on Friday.', 'Yes, I do.'],
                                   'plain': True,
                                   'q': 'Why do you like it Maths?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['What', 'How', 'Because', 'With'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ I want to be a painter.',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'today?', 'you', 'subjects', 'have', 'What']},
                                  {'id': 't1.12',
                                   'o': ['Because I want to be a painter.',
                                         'Because I want to be a singer.',
                                         'My favourite subject is music.',
                                         'I like music.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like music?"',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['IT', 'Art', 'Music', 'Science'],
                                   'plain': True,
                                   'q': 'My favourite subject is __________. I want to be a painter.',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Vietnamese,', 'and', 'Maths.', 'English', 'I', 'have']},
                                  {'id': 't1.15',
                                   'o': ['How many building are there at your school?',
                                         'What subjects do you have today?',
                                         'Why do you like Art?',
                                         'Why do you like Maths?'],
                                   'plain': True,
                                   'q': 'Câu “Because I want to be a painter." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['English', 'Art', 'Music', 'IT'],
                                   'plain': True,
                                   'q': 'I like __________ because I want to be a singer.',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Fridays.', 'Music', 'have', 'on', 'I']},
                                  {'id': 't1.18',
                                   'o': ['Why do you like English?', 'Why do you like Music?', 'Why do you like Maths?', "What's your favourtie subject?"],
                                   'plain': True,
                                   'q': 'Câu “Because I want to be an English teacher.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['subject', 'day', 'school', 'name'],
                                   'plain': True,
                                   'q': "I like PE. It's my favourite __________.",
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'like', 'English?', 'Why', 'you']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 8 – My favourite subjects: Kiểm tra 2',
 'unit': 8}
