# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de7',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and tick (✓ = True) or cross (✗ = False) (nghe, tranh đúng thì chọn True, sai thì chọn False; tranh A là '
                                 'ví dụ).',
                        'items': [{'id': 'l1.1',
                                   'img': 'l1_1.png',
                                   'q': 'Nghe và quyết định: nội dung nghe có đúng với tranh không? (✓ = True, ✗ = False)',
                                   't': 'tf'},
                                  {'id': 'l1.2',
                                   'img': 'l1_2.png',
                                   'q': 'Nghe và quyết định: nội dung nghe có đúng với tranh không? (✓ = True, ✗ = False)',
                                   't': 'tf'},
                                  {'id': 'l1.3',
                                   'img': 'l1_3.png',
                                   'q': 'Nghe và quyết định: nội dung nghe có đúng với tranh không? (✓ = True, ✗ = False)',
                                   't': 'tf'},
                                  {'id': 'l1.4',
                                   'img': 'l1_4.png',
                                   'q': 'Nghe và quyết định: nội dung nghe có đúng với tranh không? (✓ = True, ✗ = False)',
                                   't': 'tf'}]},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and write Yes or No (nghe, chọn Yes hoặc No cho mỗi tranh).',
                        'items': [{'id': 'l2.5', 'img': 'l2_1.png', 'o': ['Yes', 'No'], 'q': 'Nghe và chọn Yes hoặc No cho tranh này.', 't': 'mcq'},
                                  {'id': 'l2.6', 'img': 'l2_2.png', 'o': ['Yes', 'No'], 'q': 'Nghe và chọn Yes hoặc No cho tranh này.', 't': 'mcq'},
                                  {'id': 'l2.7', 'img': 'l2_3.png', 'o': ['Yes', 'No'], 'q': 'Nghe và chọn Yes hoặc No cho tranh này.', 't': 'mcq'},
                                  {'id': 'l2.8', 'img': 'l2_4.png', 'o': ['Yes', 'No'], 'q': 'Nghe và chọn Yes hoặc No cho tranh này.', 't': 'mcq'}]},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen to the dialogue and complete (nghe đoạn hội thoại và điền từ).',
                        'items': [{'id': 'l3.9', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'l3.10', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'l3.11', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'l3.12', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p><b>Boy:</b> Hi, can I ask you some questions for my assignment?<br><b>Girl:</b> (0) <b>Yes</b>, please go '
                                   'ahead.<br><b>Boy:</b> What do you do <b>(1) ______</b>?<br><b>Girl:</b> I do my homework.<br><b>Boy:</b> What about your '
                                   'sister? What does she do at noon?<br><b>Girl:</b> She <b>(2) ______</b>.<br><b>Boy:</b> OK, I already take note. Now, I '
                                   'want to go to the <b>(3) ______</b>. Where’s it?<br><b>Girl:</b> It’s in Green Street.<br><b>Boy:</b> How can I get '
                                   'there?<br><b>Girl:</b> You can <b>(4) ______</b> and turn left.</p>'},
                       {'id': 'r1',
                        'instr': 'Question 4. Read and choose A, B or C (đọc và chọn tranh đúng).',
                        'items': [{'id': 'r1.13',
                                   'img': 'r1_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'The gift shop is between the bookshop and the bakery.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r1.14',
                                   'img': 'r1_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'What do your parents look like? – My father is big and tall, and my mother is slim and short.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r1.15',
                                   'img': 'r1_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'What was the weather like last weekend? – It was windy and rainy.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r1.16',
                                   'img': 'r1_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'How can I get to the water park? – Go straight, turn left, then turn right. The water park is on the left.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'r2',
                        'instr': 'Question 5. Read and match (nối câu hỏi với câu trả lời; câu 0 “How much is the skirt?” – C là ví dụ).',
                        'items': [{'id': 'r2.17',
                                   'left': [{'t': 'Why do you like giraffes?'}, {'t': 'What’s Huong doing?'}, {'t': 'What does your sister do on Sundays?'}],
                                   'o': ['Because they run quickly.',
                                         'She helps my mother with the housework.',
                                         'It’s eighty thousand dong.',
                                         'She’s taking a photo.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'r3',
                        'instr': 'Question 6. Read and tick True or False (đọc đoạn văn, chọn True hoặc False).',
                        'items': [{'id': 'r3.18', 'q': 'Thuy Duong likes flying a kite with her father on Saturdays.', 't': 'tf'},
                                  {'id': 'r3.19', 'q': 'On Sundays, her family do housework and cook meals together.', 't': 'tf'},
                                  {'id': 'r3.20', 'q': 'Her family love watching television or listening to music on Saturday evening.', 't': 'tf'}],
                        'passage': '<p>Thuy Duong loves the weekends so much. On Saturdays, her mother brings her to the supermarket to buy groceries and milk '
                                   'in the morning. On Saturday afternoon, Thuy Duong’s favorite hobby is flying a kite with her father. Or they cycle around '
                                   'the village. On Sundays, the family clean the house and cook meals together. They love watching television or listening to '
                                   'music on Sunday evening. They are a happy family.</p><img src="../../../../assets/lop4_on2_de7/p6.png" alt="Hình" '
                                   'style="max-width:200px;height:auto">'},
                       {'id': 'w1',
                        'instr': 'Question 7. Fill in the blanks to make complete words (nhìn tranh, điền từ hoàn chỉnh; gợi ý một số chữ cái).',
                        'items': [{'id': 'w1.21', 'img': 'w1_1.png', 'q': 'F _ _ _ _ _ Y → {_}', 't': 'fill'},
                                  {'id': 'w1.22', 'img': 'w1_2.png', 'q': '_ I _ _ _ → {_}', 't': 'fill'},
                                  {'id': 'w1.23', 'img': 'w1_3.png', 'q': 'T _ _ _ R _ U _ _ → {_} (2 từ, gõ cách nhau)', 't': 'fill'},
                                  {'id': 'w1.24', 'img': 'w1_4.png', 'q': '_ I _ _ M _ R _ _ _ _ → {_} (2 từ, gõ cách nhau)', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Question 8. Reorder the words to make complete sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w2.25',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['campfire.', 'The', 'girls', 'around', 'are', 'the', 'dancing']},
                                  {'id': 'w2.26',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['in', 'water', 'The', 'park', 'Street.', 'is', 'Lac', 'Long', 'Quan']},
                                  {'id': 'w2.27',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'My', 'clothes', 'washes', 'in', 'the', 'mother', 'evening.']}]},
                       {'id': 'w3',
                        'instr': 'Question 9. Look at the pictures and answer the questions (nhìn tranh, trả lời câu hỏi).',
                        'items': [{'id': 'w3.28', 'img': 'w3_1.png', 'q': 'Where does your sister go on Saturdays?<br>→ {_}', 't': 'fill'},
                                  {'id': 'w3.29', 'img': 'w3_2.png', 'q': 'What’s the weather like today?<br>→ {_}', 't': 'fill'},
                                  {'id': 'w3.30', 'img': 'w3_3.png', 'q': 'What does she do in the morning?<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 7',
 'unit': 'OnHK2'}
