# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u12-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['worker.', 'an', 'office', "She's"]},
                                  {'id': 't1.2',
                                   'o': ["She's an office worker.", 'She works on a farm.', 'She lives in Le Lai Street.', "She's a nurse."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where does she work?”?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['When', 'What', 'How', 'Where'],
                                   'plain': True,
                                   'q': '_____________ does your brother work?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ["I'm a worker.", 'I live in Nguyen Kiem Street.', "She's a nurse.", 'I live with my parents.', 'I work at a factory.'],
                                   'plain': True,
                                   'q': 'Where do you work?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['work', 'do', 'in', 'is'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: Where does she _____?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['she', 'does', 'work?', 'Where']},
                                  {'id': 't1.7',
                                   'o': ['What do you do?', 'Where does he work?', 'What does your father do?', 'What does your mother do?'],
                                   'plain': True,
                                   'q': 'Câu: “My father\'s a farmer." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['What', 'Where', 'When', 'How'], 'plain': True, 'q': '_____________ does your brother do?', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ["I'm a worker.", 'I live in Nguyen Kiem Street.', "She's a nurse.", 'I live with my parents.', 'I work at a factory.'],
                                   'plain': True,
                                   'q': 'What does she do?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['farm', 'school', 'hospital', 'factory'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: She works at a _____ in Nguyen Kiem Street.',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['at', 'factory.', 'a', 'works', 'She']},
                                  {'id': 't1.12',
                                   'o': ['Cô ấy làm việc ở nông trại.', 'Cô ấy là nhân viên văn phòng.', 'Cô ấy làm việc ở viện dưỡng lão.', 'Cô ấy là y tá.'],
                                   'plain': True,
                                   'q': 'Câu: “She works at a nursing home.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['farmer', 'gardener', 'teacher', 'nurse'],
                                   'plain': True,
                                   'q': "My mother works at a nursing home. She's a _____________.",
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['brother', 'sister', 'mother', 'grandmother'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What does your _____ do?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['teaches', 'school.', 'primary', 'a', 'My', 'at', 'father']},
                                  {'id': 't1.16',
                                   'o': ['Mẹ tôi làm việc ở nông trại.', 'Mẹ tôi là nông dân.', 'Mẹ tôi là công nhân.', 'Mẹ tôi là y tá.'],
                                   'plain': True,
                                   'q': 'Câu “My mother is a farmer" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['in an office', 'at a factory', 'on a farm', 'at a primary school'],
                                   'plain': True,
                                   'q': 'My friend is an office worker. She works _____________.',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['When', 'Where', 'What', 'How'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ does he work?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['are', 'five', 'people', 'my', 'in', 'family.', 'There']},
                                  {'id': 't1.20',
                                   'o': ['My brother works at a factory.',
                                         'My father works on a farm.',
                                         'My brother is a student.',
                                         'My mother works at a school.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where does your mother work?”?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 12 – Jobs: Kiểm tra 2',
 'unit': 12}
