# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u9-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sports', 'play', 'different', 'We', 'and', 'games.']},
                                  {'id': 't1.2',
                                   'o': ['Ngày hội thể thao của họ diễn ra trong tháng Mười.',
                                         'Ngày hội thể thao của bạn diễn ra trong tháng Mười một.',
                                         'Ngày hội thể thao của chúng tôi diễn ra trong tháng Mười một.',
                                         'Ngày hội thể thao của bạn diễn ra trong tháng Mười hai.'],
                                   'plain': True,
                                   'q': 'Câu “Our sports day is in November" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There __________ many boys and girls in the school playground.',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'pupils', 'are', 'playground.', 'There', 'in', 'many']},
                                  {'id': 't1.5',
                                   'o': ["Who's that?", "When's your sports day?", 'Is your sports day in Apirl?', 'Why do you like it?'],
                                   'plain': True,
                                   'q': "Câu: “No, it isn’t. It's in March.” trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'o': ['play', 'plays', 'is play', 'are play'],
                                   'plain': True,
                                   'q': 'They ____________ different sports and games.',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Some', 'play', 'in', 'my', 'boys', 'class', 'football.']},
                                  {'id': 't1.8',
                                   'o': ["When's your sports day?", 'Why do you like it?', 'Is your sportsday in June?', 'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu “Our sports day is in May.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.9', 'o': ['at', 'on', 'in', 'do'], 'plain': True, 'q': "A: When's your sports day?", 't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['play', 'Some', 'volleyball.', 'girls']},
                                  {'id': 't1.11',
                                   'o': ['Ngày hội thể thao của bạn diễn ra trong tháng Chín phải không?',
                                         'Ngày hội thể thao của bạn diễn ra trong tháng Mười phải không?',
                                         'Môn thể thao yêu thích của bạn là gì?',
                                         'Khi nào ngày hội thể thao của bạn diễn ra?'],
                                   'plain': True,
                                   'q': 'Câu “Is your sports day in September?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ["He's", "She's", "They're", "It's"], 'plain': True, 'q': "A: What's that?", 't': 'mcq'},
                                  {'id': 't1.13',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['lot', 'a', 'We', 'GHI', 'fun.', 'have', 'NHỚ', 'of']},
                                  {'id': 't1.14',
                                   'o': ["What's your favourite subject?", 'When do you have English?', 'Is your sports day in June?', "What's that?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về ngày hội thể thao?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['do', 'make', 'play', 'take'],
                                   'plain': True,
                                   'q': 'We ____________ many sports and games.',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ["It's in December.",
                                         "It's PE.",
                                         "It's a picture of our sports day.",
                                         'Yes, it is.',
                                         'Because I want to be a football player.'],
                                   'plain': True,
                                   'q': "What's that?",
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____.",
                                   't': 'mcq'},
                                  {'id': 't1.18', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'Our', 'June.', 'is', 'sports', 'day']},
                                  {'id': 't1.19',
                                   'o': ["It's a picture of our sports day.", "It's in June.", 'Yes, it is.', 'My birthday is in May.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Is your sports day in May?”',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'o': ['Is', 'Are', 'Do', 'Does'], 'plain': True, 'q': '____________ your sports day in June?', 't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 9 – Our sports day: Kiểm tra 3',
 'unit': 9}
