# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'What subjects do you have today?',
 'a.10': 'When do you have Art?',
 'a.2': 'What subjects do you have today?',
 'a.3': 'When do you have English?',
 'a.4': 'What subjects do you have today?',
 'a.5': 'Do you have music today?',
 'a.6': 'Hôm nay bạn có môn Khoa học không?',
 'a.7': 'I have it on Tuesday and Tuesdays.',
 'a.8': 'Hôm nay bạn có những môn gì?',
 'a.9': 'Khi nào bạn có môn tiếng Việt?',
 'b.1': "What's",
 'b.10': 'on',
 'b.2': 'it',
 'b.3': 'have',
 'b.4': 'do',
 'b.5': 'subjects',
 'b.6': 'today',
 'b.7': 'Wednesdays',
 'b.8': "don't",
 'b.9': 'Do',
 'c.1': {'blanks': [['I have Maths, Vietnamese and Science.'],
                    ['Yes, I do.'],
                    ["It's Wednesday."],
                    ['I have it on Monday and Thursdays.'],
                    ['Yes, she does.']]},
 'd.1': 'it',
 'd.2': "don't",
 'd.3': 'When',
 'd.4': 'on',
 'd.5': 'do',
 'e.1': 'T',
 'e.2': 'T',
 'e.3': 'F',
 'e.4': 'F',
 'e.5': 'T',
 'f.1': ['What subjects do you have today?'],
 'f.10': ['I like Art very much. GHI NHỚ'],
 'f.2': ['I have English on Wednesdays and Fridays.'],
 'f.3': ['Do you have Science on Mondays?'],
 'f.4': ['When do you have music?'],
 'f.5': ['I have music on Saturdays.'],
 'f.6': ['I have Vietnamese every day.'],
 'f.7': ['When do you have Art?'],
 'f.8': ['We have Vietnamese and Maths today.'],
 'f.9': ['I go to school from Mondays to Fridays.'],
 'n.1': 'I have English and Maths.',
 'n.10': 'FALSE',
 'n.2': ['Science'],
 'n.3': ['Vietnamese'],
 'n.4': ['Maths'],
 'n.5': 'T',
 'n.6': 'I have it on Wednesdays.',
 'n.7': 'Mondays, Tuesdays, Thursdays and Fridays',
 'n.8': ['Mondays'],
 'n.9': 'TRUE'}

EXPLANATIONS = {'a.1': 'Đáp án: What subjects do you have today?',
 'a.10': 'Đáp án: When do you have Art?',
 'a.2': 'Đáp án: What subjects do you have today?',
 'a.3': 'Đáp án: When do you have English?',
 'a.4': 'Đáp án: What subjects do you have today?',
 'a.5': 'Đáp án: Do you have music today?',
 'a.6': 'Đáp án: Hôm nay bạn có môn Khoa học không?',
 'a.7': 'Đáp án: I have it on Tuesday and Tuesdays.',
 'a.8': 'Đáp án: Hôm nay bạn có những môn gì?',
 'a.9': 'Đáp án: Khi nào bạn có môn tiếng Việt?',
 'b.1': "Đáp án: What's",
 'b.10': 'Đáp án: on',
 'b.2': 'Đáp án: it',
 'b.3': 'Đáp án: have',
 'b.4': 'Đáp án: do',
 'b.5': 'Đáp án: subjects',
 'b.6': 'Đáp án: today',
 'b.7': 'Đáp án: Wednesdays',
 'b.8': "Đáp án: don't",
 'b.9': 'Đáp án: Do',
 'c.1': "What subjects do you have today? → I have Maths, Vietnamese and Science.; Do you have Art today? → Yes, I do.; What day is it today? → It's "
        'Wednesday.; When do you have English? → I have it on Monday and Thursdays.; Does she have English today? → Yes, she does.',
 'd.1': 'Đáp án: it',
 'd.2': "Đáp án: don't",
 'd.3': 'Đáp án: When',
 'd.4': 'Đáp án: on',
 'd.5': 'Đáp án: do',
 'e.1': 'Đáp án: True (Đúng)',
 'e.2': 'Đáp án: True (Đúng)',
 'e.3': 'Đáp án: False (Sai)',
 'e.4': 'Đáp án: False (Sai)',
 'e.5': 'Đáp án: True (Đúng)',
 'f.1': 'Câu đúng: What subjects do you have today?',
 'f.10': 'Câu đúng: I like Art very much. GHI NHỚ',
 'f.2': 'Câu đúng: I have English on Wednesdays and Fridays.',
 'f.3': 'Câu đúng: Do you have Science on Mondays?',
 'f.4': 'Câu đúng: When do you have music?',
 'f.5': 'Câu đúng: I have music on Saturdays.',
 'f.6': 'Câu đúng: I have Vietnamese every day.',
 'f.7': 'Câu đúng: When do you have Art?',
 'f.8': 'Câu đúng: We have Vietnamese and Maths today.',
 'f.9': 'Câu đúng: I go to school from Mondays to Fridays.',
 'n.1': 'Đáp án: I have English and Maths.',
 'n.10': 'Đáp án: FALSE',
 'n.2': 'Đáp án: Science',
 'n.3': 'Đáp án: Vietnamese',
 'n.4': 'Đáp án: Maths',
 'n.5': 'Đáp án: True (Đúng)',
 'n.6': 'Đáp án: I have it on Wednesdays.',
 'n.7': 'Đáp án: Mondays, Tuesdays, Thursdays and Fridays',
 'n.8': 'Đáp án: Mondays',
 'n.9': 'Đáp án: TRUE'}
