# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'Good morning.',
 'a.10': "What's he doing?",
 'a.2': 'How are you?',
 'a.3': 'This is Mai.',
 'a.4': 'Open your books, please!',
 'a.5': 'Fly it in the sky.',
 'a.6': 'Nice to see you!',
 'a.7': 'Tạm biệt!',
 'a.8': 'See you later.',
 'a.9': 'How are you?',
 'b.1': 'are',
 'b.10': 'tomorrow',
 'b.2': 'again',
 'b.3': 'down',
 'b.4': 'up',
 'b.5': 'aloud',
 'b.6': 'are',
 'b.7': 'up',
 'b.8': 'is',
 'b.9': 'is cycling',
 'c.1': {'blanks': [["I'm fine, thank you."], ['Good morning, class.'], ["He's flying a kite."], ["They're painting."], ["She's skipping."]]},
 'f.1': ['Nice to see you.'],
 'f.2': ['Close your book, please.'],
 'f.3': ['This is Mary.'],
 'f.4': ['They are playing badminton.']}

EXPLANATIONS = {'a.1': 'Đáp án: Good morning.',
 'a.10': "Đáp án: What's he doing?",
 'a.2': 'Đáp án: How are you?',
 'a.3': 'Đáp án: This is Mai.',
 'a.4': 'Đáp án: Open your books, please!',
 'a.5': 'Đáp án: Fly it in the sky.',
 'a.6': 'Đáp án: Nice to see you!',
 'a.7': 'Đáp án: Tạm biệt!',
 'a.8': 'Đáp án: See you later.',
 'a.9': 'Đáp án: How are you?',
 'b.1': 'Đáp án: are',
 'b.10': 'Đáp án: tomorrow',
 'b.2': 'Đáp án: again',
 'b.3': 'Đáp án: down',
 'b.4': 'Đáp án: up',
 'b.5': 'Đáp án: aloud',
 'b.6': 'Đáp án: are',
 'b.7': 'Đáp án: up',
 'b.8': 'Đáp án: is',
 'b.9': 'Đáp án: is cycling',
 'c.1': "How are you? → I'm fine, thank you.; Good morning, Mr Long. → Good morning, class.; What's he doing? → He's flying a kite.; What are they doing? → "
        "They're painting.; What's she doing? → She's skipping.",
 'f.1': 'Câu đúng: Nice to see you.',
 'f.2': 'Câu đúng: Close your book, please.',
 'f.3': 'Câu đúng: This is Mary.',
 'f.4': 'Câu đúng: They are playing badminton.'}
