# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk2-de2',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'I. Listen to the sounds and circle the correct words (nghe âm, chọn từ có âm đó).',
                        'items': [{'id': 'l1.1', 'o': ['nurse', 'hair', 'floor'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['clean', 'clothes', 'wash'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['street', 'big', 'quiet'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['slim', 'television', 'centre'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'}]},
                       {'id': 'l2',
                        'instr': 'II. Listen and circle the correct pictures (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'r1',
                        'instr': 'III. Circle the correct answers (nhìn tranh, chọn câu đúng).',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['He’s an office worker.', 'He works in an office.', 'She’s an office worker.'],
                                   'q': 'What does your father do?',
                                   't': 'mcq'},
                                  {'id': 'r1.10',
                                   'img': 'r1_2.png',
                                   'o': ['She has short hair.', 'She has dark hair.', 'She has long hair.'],
                                   'q': 'What does she look like?',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['He goes to the swimming pool.', 'He goes to the shopping centre.', 'He goes to the sports centre.'],
                                   'q': 'Where does he go on Fridays?',
                                   't': 'mcq'},
                                  {'id': 'r1.12',
                                   'img': 'r1_4.png',
                                   'o': ['I help my mum with the cooking.', 'I wash the dishes with my mum.', 'I clean the floor with my mum.'],
                                   'q': 'What do you do in the morning?',
                                   't': 'mcq'}]},
                       {'bank': ['long', 'big', 'tall', 'hair', 'slim'],
                        'id': 'r2',
                        'instr': 'IV. Fill in the blanks. There is ONE extra word (chọn từ trong khung, thừa 1 từ).',
                        'items': [{'id': 'r2.13', 'img': 'r2_1.png', 'q': 'Susan: What does your dad look like? John: He has short, black {_}.', 't': 'fill'},
                                  {'id': 'r2.14', 'img': 'r2_2.png', 'q': 'Susan: Is he {_}? John: Yes, he is. And he is thin.', 't': 'fill'},
                                  {'id': 'r2.15', 'img': 'r2_3.png', 'q': 'Susan: Can you describe your mum? John: She has {_}, brown hair.', 't': 'fill'},
                                  {'id': 'r2.16', 'img': 'r2_4.png', 'q': 'Susan: Is she big? John: No, she isn’t. She’s {_}.', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 2 – Đề 2',
 'unit': 'GiuaKy2'}
