# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'Where do you go?',
 'a.10': 'What do you do on Saturday evenings?',
 'a.2': 'Where does she go on Sundays?',
 'a.3': 'She goes to the cinema on Sundays.',
 'a.4': 'What does she do on Sundays?',
 'a.5': 'Where does he go on Saturdays?',
 'a.6': 'What does she do on Sundays?',
 'a.7': 'Ba tôi đi đến bể bơi vào các ngày Chủ nhật.',
 'a.8': 'Mẹ bạn làm gì vào các ngày Chủ nhật?',
 'a.9': 'What does she do on Sunday mornings?',
 'b.1': 'does',
 'b.10': 'plays',
 'b.2': 'goes',
 'b.3': 'does',
 'b.4': 'does',
 'b.5': 'cooks',
 'b.6': 'washes',
 'b.7': 'plays',
 'b.8': 'go',
 'b.9': 'do',
 'c.1': {'blanks': [['She does yoga on Sundays.'],
                    ['He plays tennis on Sundays.'],
                    ['She cooks meals on Saturdays.'],
                    ['He goes to the sport centre.'],
                    ['I go to the swimming pool.']]},
 'e.1': 'T',
 'e.2': 'T',
 'e.3': 'F',
 'e.4': 'F',
 'e.5': 'T',
 'f.1': ['Where do you go on Sundays?'],
 'f.10': ['She goes to the cinema on Saturdays.'],
 'f.2': ['I go to the sports centre on Sundays.'],
 'f.3': ['What do you do on Sundays?'],
 'f.4': ['I play football with my friends.'],
 'f.5': ['Where does your father go on Saturdays?'],
 'f.6': ['He goes to the swimming pool on Saturdays.'],
 'f.7': ['Where does your mother go on Sundays?'],
 'f.8': ['My mother goes to the shopping centre.'],
 'f.9': ['What does she do on Saturdays?']}

EXPLANATIONS = {'a.1': 'Đáp án: Where do you go?',
 'a.10': 'Đáp án: What do you do on Saturday evenings?',
 'a.2': 'Đáp án: Where does she go on Sundays?',
 'a.3': 'Đáp án: She goes to the cinema on Sundays.',
 'a.4': 'Đáp án: What does she do on Sundays?',
 'a.5': 'Đáp án: Where does he go on Saturdays?',
 'a.6': 'Đáp án: What does she do on Sundays?',
 'a.7': 'Đáp án: Ba tôi đi đến bể bơi vào các ngày Chủ nhật.',
 'a.8': 'Đáp án: Mẹ bạn làm gì vào các ngày Chủ nhật?',
 'a.9': 'Đáp án: What does she do on Sunday mornings?',
 'b.1': 'Đáp án: does',
 'b.10': 'Đáp án: plays',
 'b.2': 'Đáp án: goes',
 'b.3': 'Đáp án: does',
 'b.4': 'Đáp án: does',
 'b.5': 'Đáp án: cooks',
 'b.6': 'Đáp án: washes',
 'b.7': 'Đáp án: plays',
 'b.8': 'Đáp án: go',
 'b.9': 'Đáp án: do',
 'c.1': 'What does your mother do on Sundays? → She does yoga on Sundays.; What does your father do on Sundays? → He plays tennis on Sundays.; What does your '
        'sister do on Saturdays? → She cooks meals on Saturdays.; Where does your brother go on Sundays? → He goes to the sport centre.; Where do you go on '
        'Sundays? → I go to the swimming pool.',
 'e.1': 'Đáp án: True (Đúng)',
 'e.2': 'Đáp án: True (Đúng)',
 'e.3': 'Đáp án: False (Sai)',
 'e.4': 'Đáp án: False (Sai)',
 'e.5': 'Đáp án: True (Đúng)',
 'f.1': 'Câu đúng: Where do you go on Sundays?',
 'f.10': 'Câu đúng: She goes to the cinema on Saturdays.',
 'f.2': 'Câu đúng: I go to the sports centre on Sundays.',
 'f.3': 'Câu đúng: What do you do on Sundays?',
 'f.4': 'Câu đúng: I play football with my friends.',
 'f.5': 'Câu đúng: Where does your father go on Saturdays?',
 'f.6': 'Câu đúng: He goes to the swimming pool on Saturdays.',
 'f.7': 'Câu đúng: Where does your mother go on Sundays?',
 'f.8': 'Câu đúng: My mother goes to the shopping centre.',
 'f.9': 'Câu đúng: What does she do on Saturdays?'}
