# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on1-de15',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Listening – Part 1. Listen and tick (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l1.1',
                                   'img': 'l1_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.2',
                                   'img': 'l1_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.3',
                                   'img': 'l1_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.4',
                                   'img': 'l1_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'l2',
                        'instr': 'Listening – Part 2. Listen and number (nghe và đánh số tranh; tranh B là ví dụ = 0).',
                        'items': [{'id': 'l2.5', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh A là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.6', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh C là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.7', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh D là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.8', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh E là câu số mấy trong bài nghe?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de15/l2.png" alt="Tranh">'},
                       {'id': 'l3',
                        'instr': 'Listening – Part 3. Listen and draw line (nghe và nối tranh với số; tranh B là ví dụ = 0).',
                        'items': [{'id': 'l3.9', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh A là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l3.10', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh C là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l3.11', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh D là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l3.12', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh E là câu số mấy trong bài nghe?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de15/l3.png" alt="Tranh">'},
                       {'id': 'l4',
                        'instr': 'Listening – Part 4. Listen and write (nghe và điền từ).',
                        'items': [{'id': 'l4.13', 'q': 'I want to be a {_}.', 't': 'fill'},
                                  {'id': 'l4.14', 'q': 'She’s from {_}.', 't': 'fill'},
                                  {'id': 'l4.15', 'q': 'He goes to {_} at six fifteen.', 't': 'fill'},
                                  {'id': 'l4.16', 'q': 'What do you do on {_}? – I listen to music.', 't': 'fill'}]},
                       {'id': 'r1',
                        'instr': 'Reading – Part 1. Read and match the words with pictures (nối từ với tranh).',
                        'items': [{'id': 'r1.17',
                                   'left': [{'t': 'birthday party'}, {'t': 'buildings'}, {'t': 'study at school'}, {'t': 'play the guitar'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de15/r1_pics.png" alt="Tranh A–E">'},
                       {'id': 'r2',
                        'instr': 'Reading – Part 2. Read and choose A, B or C to complete the text (đọc và chọn từ điền vào chỗ trống).',
                        'items': [{'id': 'r2.18', 'o': ['from', 'singing', 'cooking'], 'q': 'Chọn từ điền vào chỗ trống (1).', 't': 'mcq'},
                                  {'id': 'r2.19', 'o': ['nineteen', 'nine', 'September'], 'q': 'Chọn từ điền vào chỗ trống (2).', 't': 'mcq'},
                                  {'id': 'r2.20', 'o': ['When', 'When’s', 'Where'], 'q': 'Chọn từ điền vào chỗ trống (3).', 't': 'mcq'}],
                        'passage': '<p>Dear penfriend,</p><p>Hi! My <b>name</b> is Mary. I’m <b>(1) ______</b> America. My birthday is in <b>(2) ______</b>. I '
                                   'have many presents from my family. My parents give me a new blue bike and I receive a new pink doll from my sister. I’m '
                                   'very happy. What about you? <b>(3) ______</b> your birthday?</p>'},
                       {'id': 'r3',
                        'instr': 'Reading – Part 3. Read and tick True or False (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'r3.21', 'q': 'Mary can play the piano, but she can’t play the guitar.', 't': 'tf'},
                                  {'id': 'r3.22', 'q': 'Ben can ride a horse and draw.', 't': 'tf'},
                                  {'id': 'r3.23', 'q': 'Lan, Mary, Lucy, Ben and Minh can sing and dance.', 't': 'tf'}],
                        'passage': '<p>Hello, my name is Lan. I have four friends: Mary, Lucy, Ben, Minh. Mary can play the piano, but she can’t play the '
                                   'guitar. Lucy can cook, but she can’t ride a bike. Ben can ride a horse, but he can’t draw. Minh can play football, but he '
                                   'can’t roller skate. I can cook, but I can’t swim. We all can sing and dance.</p>'},
                       {'id': 'w1',
                        'instr': 'Writing – Part 1. Look at the pictures and the letters. Write the words (nhìn tranh, sắp xếp chữ cái thành từ).',
                        'items': [{'id': 'w1.24', 'img': 'w1_1.png', 'q': 'Sắp xếp chữ cái: <b>nuringn</b> → {_}', 't': 'fill'},
                                  {'id': 'w1.25', 'img': 'w1_2.png', 'q': 'Sắp xếp chữ cái: <b>sepgar</b> → {_}', 't': 'fill'},
                                  {'id': 'w1.26', 'img': 'w1_3.png', 'q': 'Sắp xếp chữ cái: <b>saninomut</b> → {_}', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Writing – Part 2. Rearrange the words to make sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w2.27', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['she', 'Where', 'from?', 'is']},
                                  {'id': 'w2.28', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'My', 'February.', 'is', 'birthday']},
                                  {'id': 'w2.29', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['up', 'I', 'five', 'at', 'get', 'forty-five.']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK1 – Đề 15',
 'unit': 'OnHK1'}
