# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'What are those animals?',
 't1.10': "He's taking photos.",
 't1.11': 'singing',
 't1.12': ['They are playing tug of war.'],
 't1.13': 'What was the weather like yesterday?',
 't1.14': 'What',
 't1.15': 'It was rainy.',
 't1.16': 'Where',
 't1.17': ['Where were you last weekend, Linh?'],
 't1.18': 'What was the weather like in Da Lat last weekend?',
 't1.19': 'bookshop',
 't1.2': 'Why',
 't1.20': 'Turn right and go straight.',
 't1.3': ['Minh likes hippos because they look strong.'],
 't1.4': 'Because they run quickly.',
 't1.5': 'because they',
 't1.6': ['Lucy likes birds because they sing merrily.'],
 't1.7': "She's telling a story.",
 't1.8': 'they are',
 't1.9': ['What are Bill and Ben doing, Mary?']}

EXPLANATIONS = {'t1.1': 'Đáp án: What are those animals?',
 't1.10': "Đáp án: He's taking photos.",
 't1.11': 'Đáp án: singing',
 't1.12': 'Câu đúng: They are playing tug of war.',
 't1.13': 'Đáp án: What was the weather like yesterday?',
 't1.14': 'Đáp án: What',
 't1.15': 'Đáp án: It was rainy.',
 't1.16': 'Đáp án: Where',
 't1.17': 'Câu đúng: Where were you last weekend, Linh?',
 't1.18': 'Đáp án: What was the weather like in Da Lat last weekend?',
 't1.19': 'Đáp án: bookshop',
 't1.2': 'Đáp án: Why',
 't1.20': 'Đáp án: Turn right and go straight.',
 't1.3': 'Câu đúng: Minh likes hippos because they look strong.',
 't1.4': 'Đáp án: Because they run quickly.',
 't1.5': 'Đáp án: because they',
 't1.6': 'Câu đúng: Lucy likes birds because they sing merrily.',
 't1.7': "Đáp án: She's telling a story.",
 't1.8': 'Đáp án: they are',
 't1.9': 'Câu đúng: What are Bill and Ben doing, Mary?'}
