# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u16-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['in', 'yesterday?', 'An', 'weather', 'the', 'like', 'was', 'Long', 'What']},
                                  {'id': 't1.2',
                                   'o': ["She's beautiful.", 'He has a round face.', 'It was rainy.', "Let's go to the food stall."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What was the weather like yesterday?”',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['day', 'weather', 'homework', 'weekend'],
                                   'plain': True,
                                   'q': "A: What's the __________ like yesterday?",
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['It was sunny.', 'It is cloudy.', 'I was in Da Nang.', 'I want to buy some books.', "Great! Let's go."],
                                   'plain': True,
                                   'q': 'What do you want to buy?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['is', 'are', 'was', 'were'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: It _____ rainy.',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['and', 'was', 'rainy', 'cold', 'It', 'yesterday.']},
                                  {'id': 't1.7',
                                   'o': ['What was the weather lile last weekend?',
                                         'What does he look like?',
                                         'Do you want to go to the bakery?',
                                         'Where do you go on Sundays?'],
                                   'plain': True,
                                   'q': 'Câu “Great! Let\'s go." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['bakery', 'bookshop', 'wate park', 'swimming pool'],
                                   'plain': True,
                                   'q': "Let's go to the ___________. I want to buy some bread.",
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['It was sunny.', 'It is cloudy.', 'I was in Da Nang.', 'I want to buy some books.', "Great! Let's go."],
                                   'plain': True,
                                   'q': 'What is the weather like today?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['am', 'do', "can't", 'am not'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: Sorry, I _____. I'm doing my housework.",
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Nang', 'like', 'today?', 'Da', 'is', 'in', 'the', 'weather', 'What']},
                                  {'id': 't1.12',
                                   'o': ["Sorry, I can't. I'm doing my homework.", 'It was cloudy.', "I don't like rainy weather.", "It's sunny today."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi “Do you want to go to the bookshop with me?"',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['bakery', 'bookshop', 'food stall', 'water park'],
                                   'plain': True,
                                   'q': 'Do you want to go to the ___________ with me? I want to buy some books.',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sunny', 'today.', 'It', 'is']},
                                  {'id': 't1.15',
                                   'o': ['She is tall and slim.', 'It was sunny.', "Let's go to the bakery.", "Sorry, I can't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What was the weather like in Da Nang yesterday?"',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['sunny', 'rainy', 'cloudy', 'windy.'],
                                   'plain': True,
                                   'q': "It's _________________. Let's go to the beach.",
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['some', 'to', 'want', 'buy', 'We', 'food.']},
                                  {'id': 't1.18',
                                   'o': ['What was the weather like in Sa Pa?',
                                         'What was the weather like in Sa Pa last weekend?',
                                         'Do you want to go to Sa Pa?',
                                         'It was sunny in Sa Pa.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Cuối tuần rồi thời tiết ở Sa Pa như thế nào?',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'o': ['is', 'are', 'was', 'were'], 'plain': True, 'q': 'Where ____________ you yesterday?', 't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['books.', 'buy', 'some', 'wants', 'Mai', 'to']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 16 – Weather: Kiểm tra 2',
 'unit': 16}
