# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "Let's go to the water park.",
 't1.10': ['I was in Hue last weekend.'],
 't1.11': 'Do you want to go to the shopping centre?',
 't1.12': 'Do',
 't1.13': "Great! Let's go.",
 't1.14': 'bookshop',
 't1.15': ['What was the weather like in Long An yesterday?'],
 't1.16': 'It was rainy.',
 't1.17': 'weather',
 't1.18': 'I want to buy some books.',
 't1.19': 'was',
 't1.2': 'was',
 't1.20': ['It was rainy and cold yesterday.'],
 't1.3': 'I was in Da Nang.',
 't1.4': 'Where',
 't1.5': ['Where were you last weekend?'],
 't1.6': 'What was the weather like last Sunday?',
 't1.7': 'was',
 't1.8': 'It was sunny.',
 't1.9': 'food stall'}

EXPLANATIONS = {'t1.1': "Đáp án: Let's go to the water park.",
 't1.10': 'Câu đúng: I was in Hue last weekend.',
 't1.11': 'Đáp án: Do you want to go to the shopping centre?',
 't1.12': 'Đáp án: Do',
 't1.13': "Đáp án: Great! Let's go.",
 't1.14': 'Đáp án: bookshop',
 't1.15': 'Câu đúng: What was the weather like in Long An yesterday?',
 't1.16': 'Đáp án: It was rainy.',
 't1.17': 'Đáp án: weather',
 't1.18': 'Đáp án: I want to buy some books.',
 't1.19': 'Đáp án: was',
 't1.2': 'Đáp án: was',
 't1.20': 'Câu đúng: It was rainy and cold yesterday.',
 't1.3': 'Đáp án: I was in Da Nang.',
 't1.4': 'Đáp án: Where',
 't1.5': 'Câu đúng: Where were you last weekend?',
 't1.6': 'Đáp án: What was the weather like last Sunday?',
 't1.7': 'Đáp án: was',
 't1.8': 'Đáp án: It was sunny.',
 't1.9': 'Đáp án: food stall'}
