# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u18-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['What does it say?', 'How can I get to the sports centre?', "Where's the bookshop?", 'How much is the T-shirt?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về địa điểm?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['How much is the skirt?', 'How many skirts are there?', "Where's the gift shop?", 'How can I get to the gift shop?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về giá cả?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Where are you?', "Where's the food shop?", 'How much is the T-shirt?', 'What does it say?'],
                                   'plain': True,
                                   'q': 'Câu "It\'s between the sports shop and the bookshop." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ["It's ninety thousand dong.", "It's over there.", "It's opposite the gift shop.", 'It says "Stop".'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “How much is the school bag?”',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['What do you do on Sundays?', 'What does it say?', 'How much is the T-shirt?', 'How many T-shirts are there?'],
                                   'plain': True,
                                   'q': "Câu “It's fifty thousand dong.” trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ["It's five thousand dong.", "It's on the desk.", "It's near the bookshop.", 'I want to buy a pen.'],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi “Where's the gift shop?”?",
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['Tiệm bánh mì đối diện hiệu sách và cửa hàng thú cưng.',
                                         'Tiệm bánh mì ở gần hiệu sách và cửa hàng thú cưng.',
                                         'Tiệm bánh mì ở giữa hiệu sách và cửa hàng thú cứng.',
                                         'Tiệm bánh mì ở đằng sau hiệu sách và cửa hàng thú cứng.'],
                                   'plain': True,
                                   'q': 'Câu “The bakery is between the bookshop and the pet shop” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['Trung tâm thể thao ở gần trung tâm mua sắm.',
                                         'Trung tâm thể thao ở đằng sau trung tâm mua sắm.',
                                         'Trung tâm thể thao đối diện trung tâm mua sắm.',
                                         'Trung tâm thể thao ở giữa trung tâm mua sắm.'],
                                   'plain': True,
                                   'q': 'Câu “The sports centre is opposite the shopping centre." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['How much is the skirt?', 'How much is the T-shirt?', 'How much is the shirt?', 'How much are the pants?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi giá tiền của áo sơ mi?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ["It's thirty thousand dong.",
                                         'They are two hundred thousand dong.',
                                         'They are over there.',
                                         "It's opposite the gift shop."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “How much are the hats?”',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['What', 'How', 'How much', 'When'], 'plain': True, 'q': 'A: ___________ is that skirt?', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['It', "It's", 'They', "They're"], 'plain': True, 'q': 'A: How much are these pants?', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['How', 'How much', 'What', 'Where'], 'plain': True, 'q': 'A: ___________ is the gift shop?', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['this', 'that', 'these', 'they'], 'plain': True, 'q': 'How much are ___________ trousers?', 't': 'mcq'},
                                  {'id': 'b.5', 'o': ['behind', 'opposite', 'between', 'next'], 'plain': True, 'q': 'A: Where is the pet shop?', 't': 'mcq'},
                                  {'id': 'b.6', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'How much ___________ that pen?', 't': 'mcq'},
                                  {'id': 'b.7', 'o': ['next', 'between', 'in front', 'opposite'], 'plain': True, 'q': 'A: Where is the gift shop?', 't': 'mcq'},
                                  {'id': 'b.8', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: How much _________ those dolls?', 't': 'mcq'},
                                  {'id': 'b.9', 'o': ['on', 'in', 'over', 'at'], 'plain': True, 'q': 'A: Where is the bookshop?', 't': 'mcq'},
                                  {'id': 'b.10', 'o': ['next', 'near', 'between', 'in'], 'plain': True, 'q': "A: Where's the bakery?", 't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['How much is the skirt?',
                                            'Where is the pet shop?',
                                            'How much are those trousers?',
                                            'How can I get to the bookshop?',
                                            'Do you want to go to the shopping center with me?'],
                                   'o': ["It's near the gift shop.",
                                         'Go straight and turn left at the corner.',
                                         "It's ninety thousand dong.",
                                         "Great! Let's go.",
                                         "They're one hundred and ninety thousand dong."],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['between', 'those', 'over there', 'it', 'get', 'near'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['between', 'those', 'over there', 'it', 'get', 'near'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['between', 'those', 'over there', 'it', 'get', 'near'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['between', 'those', 'over there', 'it', 'get', 'near'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['between', 'those', 'over there', 'it', 'get', 'near'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'},
                                  {'id': 'd.6',
                                   'o': ['between', 'those', 'over there', 'it', 'get', 'near'],
                                   'plain': True,
                                   'q': 'Chỗ trống (6):',
                                   't': 'mcq'}],
                        'passage': '1. A: Excuse me, is there a shopping centre <b>(1)&nbsp;______</b> here?<br>B: There is a shopping centre in Phan Van Tri '
                                   'Street.<br>2. A: How can I <b>(2)&nbsp;______</b> there?<br>B: Turn left at the first corner.<br>A: Thank you for your '
                                   "help.<br>3. A: Excuse me, where's the toy shop?<br>B: It's <b>(3)&nbsp;______</b>. It's near the bookshop.<br>4. A: "
                                   "Where's the sports shop?<br>B: It's <b>(4)&nbsp;______</b> the bookshop and the bakery.<br>5. A: Your hat is so "
                                   "nice.<br>B: Thank you. I like it very much.<br>A: How much is <b>(5)&nbsp;______</b>?<br>B: It's sixty thousand "
                                   'dong.<br>6. A: How much are <b>(6)&nbsp;______</b> shoes?<br>B: They are four hundred thousand dong.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': 'Nam and Minh are at the shopping centre.', 't': 'tf'},
                                  {'id': 'e.2', 'q': 'The bookshop is near the gift shop.', 't': 'tf'},
                                  {'id': 'e.3', 'q': 'The bakery is behind the sports shop.', 't': 'tf'},
                                  {'id': 'e.4', 'q': 'The clothing shop is between the food shop and the bakery.', 't': 'tf'},
                                  {'id': 'e.5', 'q': 'The gift is 300,000 dong.', 't': 'tf'},
                                  {'id': 'e.6', 'q': 'The book is 80,000 dong.', 't': 'tf'}],
                        'passage': 'Nam and Minh are at the shopping centre. There are many shops there. The bookshop is near the gift shop. The sports shop '
                                   'is in front of the bakery. The clothing shop is between the food shop and the pet shop.<br>Nam wants to buy a gift for his '
                                   "mother. It's four hundred thousand dong. Minh wants to buy a book. It is seventy thousand dong."}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['shop?', 'Where', 'is', 'pet', 'the']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'behind', "It's", 'bookshop.']},
                                  {'id': 'f.3',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['is', 'opposite', 'the', 'shop', 'bookshop.', 'The', 'pet']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'The', 'opposite', 'museum.', 'bakery', 'the']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['How', 'these', 'pants?', 'much', 'are']},
                                  {'id': 'f.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['dong.', 'two', 'thousand', 'forty', 'They', 'and', 'hundred', 'are']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['much', 'that', 'is', 'How', 'shirt?']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['five', 'It', 'hundred', 'dong.', 'thousand', 'is']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['school', 'bag?', 'much', 'that', 'is', 'How']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['eighty', 'is', 'thousand', 'dong.', 'GHI', 'It', 'NHỚ']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi và chỉ đường đến một địa điểm nào đó:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           "lời</td></tr><tr><td>Where's the...?<br>… ở đâu?</td><td>It's...<br>Nó ở... (vị trí của địa điểm).</td></tr><tr><td>Ví dụ:<br>A: Where's the "
           "bookshop? Hiệu sách ở đâu?<br>B: It's behind the bakery. Nó ở đằng sau tiệm bánh mì.</td></tr></table><p>2. Cách hỏi giá tiền của một món đồ nào "
           'đó ở dạng số ít và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>How much is the/this/that...? ¦... '
           "này/đó giá bao nhiêu?</td><td>It's...<br>Nó có giá... (số tiền).</td></tr><tr><td>Ví dụ:<br>A: How much is the pen? Cây bút giá bao nhiêu "
           'vậy?<br>B: It’s five thousand dong. Nó có giá năm ngàn đồng.</td></tr></table><p>3. Cách hỏi giá tiền của một món đồ nào đó ở dạng số nhiều và '
           'cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>How much are the/these/those...?<br>… này/đó giá bao '
           'nhiêu?</td><td>They are...<br>Chúng có giá … (số tiền).</td></tr><tr><td>Ví dụ:<br>A: How much are those shoes? Đôi giày đó giá bao nhiêu '
           'vậy?<br>B: They are three hundred thousand dong. Chúng có giá ba trăm ngàn đồng.</td></tr></table>',
 'title': 'Unit 18 – At the shopping centre: Luyện tập',
 'unit': 18}
