# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk2-de6',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'A. Listening. Listen and choose the correct answers to complete sentences (nghe, chọn đáp án hoàn thành câu).',
                        'items': [{'id': 'l1.1', 'o': ['have breakfast', 'take a shower', 'do morning exercise'], 'q': '1. I ____ in the morning.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['have dinner', 'take a bath', 'watch TV'], 'q': '2. You ____ in the evening.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['half past three', 'six o’clock', 'three o’clock'], 'q': '3. She goes home at ____.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['take a bath', 'takes a shower', 'takes a bath'], 'q': '4. Tom ____ at 5 p.m.', 't': 'mcq'},
                                  {'id': 'l1.5', 'o': ['go to school', 'go home', 'get dressed'], 'q': '5. You ____ in the afternoon.', 't': 'mcq'}]},
                       {'id': 'v1',
                        'instr': 'B. Vocabulary & Grammar. I. Odd one out (chọn từ khác loại).',
                        'items': [{'id': 'v1.6', 'o': ['hotel', 'accountant', 'fireman', 'engineer'], 'q': '1. Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 'v1.7', 'o': ['chicken', 'bread', 'lemonade', 'fish'], 'q': '2. Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 'v1.8', 'o': ['strong', 'slim', 'young', 'live'], 'q': '3. Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 'v1.9', 'o': ['come', 'smart', 'join', 'hear'], 'q': '4. Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 'v1.10', 'o': ['get up', 'have breakfast', 'go home', 'routine'], 'q': '5. Chọn từ khác loại:', 't': 'mcq'}]},
                       {'id': 'v2',
                        'instr': 'II. Match (nhìn tranh, chọn từ đúng).',
                        'items': [{'id': 'v2.11',
                                   'left': [{'img': 'm1.png'}, {'img': 'm2.png'}, {'img': 'm3.png'}, {'img': 'm4.png'}, {'img': 'm5.png'}],
                                   'o': ['interview', 'party', 'vegetables', 'farmer', 'Christmas'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'v3',
                        'instr': 'III. Choose the correct answer (chọn đáp án đúng).',
                        'items': [{'id': 'v3.12', 'o': ['What', 'When', 'Where'], 'q': '1. ____ does he work? – He works in a hospital.', 't': 'mcq'},
                                  {'id': 'v3.13', 'o': ['drink', 'milk', 'food'], 'q': '2. I like beef. It’s my favourite ____.', 't': 'mcq'},
                                  {'id': 'v3.14', 'o': ['do', 'are', 'does'], 'q': '3. What ____ they look like?', 't': 'mcq'},
                                  {'id': 'v3.15', 'o': ['much', 'many', 'lot of'], 'q': '4. How ____ is this bag?', 't': 'mcq'},
                                  {'id': 'v3.16', 'o': ['many', 'some', 'for'], 'q': '5. Would you like ____ water?', 't': 'mcq'}]},
                       {'id': 'v4',
                        'instr': 'IV. Read the passage and complete the sentences (đọc đoạn văn, hoàn thành câu).',
                        'items': [{'id': 'v4.17', 'q': 'Dat studies at {_}.', 't': 'fill'},
                                  {'id': 'v4.18', 'q': 'He {_} at six o’clock in the morning.', 't': 'fill'},
                                  {'id': 'v4.19', 'q': 'His class starts at {_}.', 't': 'fill'},
                                  {'id': 'v4.20', 'q': 'He has lunch in {_}.', 't': 'fill'},
                                  {'id': 'v4.21', 'q': 'He {_} at 11 p.m.', 't': 'fill'}],
                        'passage': '<p>My brother’s name is Dat. He is 10 and he studies at Cambridge Primary School. He often gets up at six o’clock in the '
                                   'morning. He usually has breakfast at six thirty. Then, he goes to school by bus. He has got Maths and Science in the '
                                   'morning and his class starts at seven o’clock. He studies to eleven o’clock. He and his friends have lunch in the canteen. '
                                   'He learns English and History in the afternoon. His class finishes at five p.m. He is at home at five thirty and helps mom '
                                   'to clear the table and cook the dinner. He watches TV, then goes to bed at 11 p.m.</p>'},
                       {'id': 'v5',
                        'instr': 'V. Read and choose the correct words (chọn từ đúng).',
                        'items': [{'id': 'v5.22', 'o': ['a', 'an'], 'q': '1. This is my uncle. He is ____ worker.', 't': 'mcq'},
                                  {'id': 'v5.23', 'o': ['Do', 'Would'], 'q': '2. ____ you like some orange juice? – No, thanks.', 't': 'mcq'},
                                  {'id': 'v5.24', 'o': ['What', 'Where'], 'q': '3. ____ does he do at Tet? – He cleans the house.', 't': 'mcq'},
                                  {'id': 'v5.25', 'o': ['What', 'How'], 'q': '4. ____ is your favourite food? – Pork.', 't': 'mcq'},
                                  {'id': 'v5.26', 'o': ['he', 'his'], 'q': '5. What does ____ mother look like?', 't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Giữa kỳ 2 – Đề 6',
 'unit': 'GiuaKy2'}
