# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'It was sunny.',
 't1.10': 'Đó là một ngày mưa.',
 't1.11': 'was',
 't1.12': ['Do you want to go to the water park with me?'],
 't1.13': "Let's go to the water park.",
 't1.14': 'was',
 't1.15': 'I was in Da Nang.',
 't1.16': 'Where',
 't1.17': ['Where were you last weekend?'],
 't1.18': 'What was the weather like last Sunday?',
 't1.19': 'was',
 't1.2': 'sunny',
 't1.20': 'It was sunny.',
 't1.3': ['We want to buy some food.'],
 't1.4': 'What was the weather like in Sa Pa last weekend?',
 't1.5': 'were',
 't1.6': ['Mai wants to buy some books.'],
 't1.7': 'Chúng ta hãy đi đến trung tâm mua sắm nhé.',
 't1.8': 'was',
 't1.9': ['Nam is at the shopping centre.']}

EXPLANATIONS = {'t1.1': 'Đáp án: It was sunny.',
 't1.10': 'Đáp án: Đó là một ngày mưa.',
 't1.11': 'Đáp án: was',
 't1.12': 'Câu đúng: Do you want to go to the water park with me?',
 't1.13': "Đáp án: Let's go to the water park.",
 't1.14': 'Đáp án: was',
 't1.15': 'Đáp án: I was in Da Nang.',
 't1.16': 'Đáp án: Where',
 't1.17': 'Câu đúng: Where were you last weekend?',
 't1.18': 'Đáp án: What was the weather like last Sunday?',
 't1.19': 'Đáp án: was',
 't1.2': 'Đáp án: sunny',
 't1.20': 'Đáp án: It was sunny.',
 't1.3': 'Câu đúng: We want to buy some food.',
 't1.4': 'Đáp án: What was the weather like in Sa Pa last weekend?',
 't1.5': 'Đáp án: were',
 't1.6': 'Câu đúng: Mai wants to buy some books.',
 't1.7': 'Đáp án: Chúng ta hãy đi đến trung tâm mua sắm nhé.',
 't1.8': 'Đáp án: was',
 't1.9': 'Câu đúng: Nam is at the shopping centre.'}
