# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'What time is it?',
 't1.10': ['It is seven thirty.'],
 't1.11': 'What time is it?',
 't1.12': 'time',
 't1.13': 'She has dinner at seven thirty.',
 't1.14': 'at',
 't1.15': ['What time do you get up?'],
 't1.16': 'What time do you get up?',
 't1.17': 'does',
 't1.18': "They go to school at seven o'clock.",
 't1.19': 'lunch',
 't1.2': 'at',
 't1.20': ["I get up at six o'clock."],
 't1.3': "It's ten o'clock.",
 't1.4': 'What',
 't1.5': ['What time is it, Mai?'],
 't1.6': "It's three fifteen.",
 't1.7': 'does',
 't1.8': 'I get up at six fifteen.',
 't1.9': 'have'}

EXPLANATIONS = {'t1.1': 'Đáp án: What time is it?',
 't1.10': 'Câu đúng: It is seven thirty.',
 't1.11': 'Đáp án: What time is it?',
 't1.12': 'Đáp án: time',
 't1.13': 'Đáp án: She has dinner at seven thirty.',
 't1.14': 'Đáp án: at',
 't1.15': 'Câu đúng: What time do you get up?',
 't1.16': 'Đáp án: What time do you get up?',
 't1.17': 'Đáp án: does',
 't1.18': "Đáp án: They go to school at seven o'clock.",
 't1.19': 'Đáp án: lunch',
 't1.2': 'Đáp án: at',
 't1.20': "Câu đúng: I get up at six o'clock.",
 't1.3': "Đáp án: It's ten o'clock.",
 't1.4': 'Đáp án: What',
 't1.5': 'Câu đúng: What time is it, Mai?',
 't1.6': "Đáp án: It's three fifteen.",
 't1.7': 'Đáp án: does',
 't1.8': 'Đáp án: I get up at six fifteen.',
 't1.9': 'Đáp án: have'}
