# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u5-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['a', 'she', 'fly', 'Can', 'kite?']},
                                  {'id': 't1.2',
                                   'o': ['Can she cook?', 'Can he swim?', 'Can he play badminton?', 'Can you draw?'],
                                   'plain': True,
                                   'q': 'Câu: “Yes, I can." có thể trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'o': ['is', 'does', 'can', "can't"], 'plain': True, 'q': 'A: Can he dance?', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ["No, she can't dance, but she can sing.",
                                         "No, she can't, but she can run.",
                                         'Yes, I can.',
                                         "No, I can't ride a horse, but I can ride a bike.",
                                         'Yes, he can.'],
                                   'plain': True,
                                   'q': 'Can he roller skate?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: No, she _____ ride a horse, (5) ____________ she can ride a bike.',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', "can't", 'play', 'guitar.', 'I']},
                                  {'id': 't1.7',
                                   'o': ['Mary can sing.', 'Can she sing?', 'Minh cannot draw', 'Can he play badminton?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói ai đó có thể làm được điều gì?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['football', 'the piano', 'the guitar', 'badminton'],
                                   'plain': True,
                                   'q': 'A: Can you play ____________?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ["No, she can't dance, but she can sing.",
                                         "No, she can't, but she can run.",
                                         'Yes, I can.',
                                         "No, I can't ride a horse, but I can ride a bike.",
                                         'Yes, he can.'],
                                   'plain': True,
                                   'q': 'Can Lan play badminton?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: No, she (4) ____________ ride a horse, _____ she can ride a bike.',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['can', 'do?', 'you', 'What']},
                                  {'id': 't1.12',
                                   'o': ['Quan cannot ride a horse.', 'Lucy can play the piano.', 'Can she swim?', 'Can he draw?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói ai đó không thể làm được điều gì?',
                                   't': 'mcq'},
                                  {'id': 't1.13', 'o': ['Can', 'Is', 'Does', 'Do'], 'plain': True, 'q': 'A: ____________ he roller skate?', 't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: Yes, I _____.',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sing,', 'dance.', 'can', 'I', 'I', 'but', "can't"]},
                                  {'id': 't1.16',
                                   'o': ['Can she cook?', 'Can he play the guitar?', 'Can you dance?', 'Can they roller skate?'],
                                   'plain': True,
                                   'q': "Câu: “No, he can't” có thể trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ['is', 'does', "can't", 'can'], 'plain': True, 'q': 'A: Can Lan ride a bike?', 't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: _____, I can't, but I can swim.",
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['play', 'badminton,', 'she', "can't", 'can', 'but', 'run.', 'She']},
                                  {'id': 't1.20',
                                   'o': ['Cậu ấy có thể chơi đàn ghi-ta không?',
                                         'Cô ấy có thể chơi đàn piano không?',
                                         'Cậu ấy có thể chơi đàn piano không?',
                                         'Cậu ấy có thể chơi cầu lông không?'],
                                   'plain': True,
                                   'q': 'Câu “Can he play the guitar?" có nghĩa là:',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 5 – Things we can do: Kiểm tra 2',
 'unit': 5}
