# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck2-de1',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'gi',
                        'instr': 'I. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'gi.1', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.2', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.3', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.4', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck2_de1/gi.png" alt="Tranh a–d">'},
                       {'id': 'gii',
                        'instr': 'II. Listen and draw lines (nghe và nối nhân vật với tranh).',
                        'items': [{'id': 'gii.5',
                                   'left': [{'img': 'gii_l1.png', 't': ''},
                                            {'img': 'gii_l2.png', 't': ''},
                                            {'img': 'gii_l3.png', 't': ''},
                                            {'img': 'gii_l4.png', 't': ''}],
                                   'o': ['a', 'b', 'c', 'd'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck2_de1/gii.png" alt="Tranh a–d">'},
                       {'id': 'giii',
                        'instr': 'III. Listen and complete (nghe và điền từ).',
                        'items': [{'id': 'giii.6', 'q': 'How can I get to the supermarket? – Go straight. Then {_}.', 't': 'fill'},
                                  {'id': 'giii.7', 'q': 'Why do you like {_}? – Because they roar loudly.', 't': 'fill'},
                                  {'id': 'giii.8', 'q': 'What are they doing? – They’re {_}.', 't': 'fill'},
                                  {'id': 'giii.9', 'q': 'How much is the {_}? – It’s 150,000 dong.', 't': 'fill'}]},
                       {'id': 'giv',
                        'instr': 'IV. Read and choose A, B or C (nhìn tranh, chọn đáp án đúng).',
                        'items': [{'id': 'giv.10',
                                   'img': 'giv_1.png',
                                   'o': ['Great! Let’s go.', 'Sorry. Let’s go.', 'Great! I can’t.'],
                                   'q': 'Do you want to go to the bookshop?',
                                   't': 'mcq'},
                                  {'id': 'giv.11',
                                   'img': 'giv_2.png',
                                   'o': ['Because they roar loudly.', 'Because they dance beautifully.', 'Because they sing merrily.'],
                                   'q': 'Why do you like birds?',
                                   't': 'mcq'},
                                  {'id': 'giv.12',
                                   'img': 'giv_3.png',
                                   'o': ['He builds a campfire.', 'He’s building a campfire.', 'She’s building a campfire.'],
                                   'q': 'What is he doing?',
                                   't': 'mcq'},
                                  {'id': 'giv.13',
                                   'img': 'giv_4.png',
                                   'o': ['It says ‘turn right’.', 'It says ‘turn left’.', 'It says ‘turn round’.'],
                                   'q': 'What does it say?',
                                   't': 'mcq'}]},
                       {'id': 'gv',
                        'instr': 'V. Write suitable questions for the answers given (nhìn tranh, viết câu hỏi phù hợp).',
                        'items': [{'id': 'gv.14', 'img': 'gv_1.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>They’re giraffes.</i><br>{_}', 't': 'fill'},
                                  {'id': 'gv.15',
                                   'img': 'gv_2.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>They’re putting up a tent.</i><br>{_}',
                                   't': 'fill'},
                                  {'id': 'gv.16', 'img': 'gv_3.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>It says ‘go straight’.</i><br>{_}', 't': 'fill'}]},
                       {'id': 'gvi',
                        'instr': 'VI. Read and write T (True) or F (False) (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'gvi.17', 'q': 'There were some sandwiches and a hamburger for her parents.', 't': 'tf'},
                                  {'id': 'gvi.18', 'q': 'There were some monkeys in the photos.', 't': 'tf'},
                                  {'id': 'gvi.19', 'q': 'The monkeys were very funny.', 't': 'tf'}],
                        'passage': '<p>Lizzy was at the zoo with her parents. For lunch, there were some sandwiches for her mum and a hamburger for her dad. '
                                   'There were some giraffes in their photos. Next, they were able to see the monkeys. The monkeys were able to swing from the '
                                   'trees and they were so funny. That was their great day at the zoo.</p>'},
                       {'id': 'gvii',
                        'instr': 'VII. Fill in the blanks (điền từ vào chỗ trống, nhìn tranh).',
                        'items': [{'id': 'gvii.20', 'img': 'gvii_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'gvii.21', 'img': 'gvii_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'gvii.22', 'img': 'gvii_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'gvii.23', 'img': 'gvii_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Today, I go to a campsite with my family. The weather is <b>(1) ______</b> We get to the campsite by car. When we '
                                   'arrive, we put up a big <b>(2) ______</b> My dad builds a <b>(3) ______</b> We cook and sing songs around it, too. My '
                                   'sister brings some cards and we play <b>(4) ______</b> together.</p>'},
                       {'bank': ['crocodiles', 'rainy', 'telling a story', 'go straight'],
                        'id': 'gviii',
                        'instr': 'VIII. Write suitable answers to the questions using given words (dùng từ cho sẵn để trả lời).',
                        'items': [{'id': 'gviii.24', 'q': 'What does it say?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.25', 'q': 'What are these animals?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.26', 'q': 'What was the weather like last weekend?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.27', 'q': 'What is Lan doing?<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 2 – Đề 1',
 'unit': 'CuoiKy2'}
