# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u17-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What does it say?',
                                         'How can she get to the shopping centre?',
                                         'Is there a cinema near here?',
                                         'What do you want to buy at the shopping centre?'],
                                   'plain': True,
                                   'q': 'Câu: "Go straight and turn right." trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['food stall', 'bookshop', 'sports centre', 'campsite'],
                                   'plain': True,
                                   'q': 'I want to buy some meat. How can I get to the ______________?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['bakery', 'Street.', 'There', 'is', 'in', 'Thai', 'Nguyen', 'Son', 'a']},
                                  {'id': 't1.4',
                                   'o': ['Is there a bookshop near here?',
                                         'What do you want to buy at the food stall?',
                                         'How can he get to the bookshop?',
                                         'What does he want to buy at the bookshop?'],
                                   'plain': True,
                                   'q': 'Câu "He wants to buy some books” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['sports centre', 'shopping centre', 'cinema', 'bakery'],
                                   'plain': True,
                                   'q': 'A: How can I get to the ____________?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['can', 'to', 'we', 'get', 'campsite?', 'How', 'the']},
                                  {'id': 't1.7',
                                   'o': ['Rẽ phải.', 'Rẽ trái.', 'Quay vòng lại.', 'Đi thẳng.'],
                                   'plain': True,
                                   'q': 'Câu: “Turn round" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['bakery', 'bookshop', 'food stall', 'campsite'],
                                   'plain': True,
                                   'q': 'A: What do you want to buy at the ________________?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['on', 'the', 'will', 'the', 'campsite', 'see', 'and', 'left.', 'you', 'Go', 'straight']},
                                  {'id': 't1.10',
                                   'o': ['Có một trung tâm mua sắm ở đường Nguyễn Trãi.',
                                         'Có một tiệm bánh mì ở đường Nguyễn Trãi.',
                                         'Có một trung tâm mua sắm ở đường Nguyễn Trãi.',
                                         'Có một trung tâm thể thao ở đường Nguyễn Trãi.'],
                                   'plain': True,
                                   'q': 'Câu: “There is a sports centre in Nguyen Trai Street" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'o': ['Go', 'Turn', 'Be', 'Is'], 'plain': True, 'q': 'A: How can I get to the Ben Thanh Market?', 't': 'mcq'},
                                  {'id': 't1.12',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Thank', 'your', 'help.', 'for', 'you', 'very', 'much']},
                                  {'id': 't1.13',
                                   'o': ['How can I get to the cinema?',
                                         'What does it say?',
                                         'Do you want to go to the cinema with me?',
                                         "What's the weather like today?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Biển báo nói gì?”:',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['cinema', 'bakery', 'food stall', 'bookshop'],
                                   'plain': True,
                                   'q': 'I want to buy some books. Is there a __________ near here?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['I want to buy some clothes.',
                                         "I'm at the shopping centre.",
                                         "Great! Let's go.",
                                         'It says "stop".',
                                         'Go straight and turn right.'],
                                   'plain': True,
                                   'q': 'Where are you now?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: _____ left at the food stall.',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['How', 'to', 'centre?', 'I', 'sports', 'get', 'the', 'can']},
                                  {'id': 't1.18',
                                   'o': ['How can I get to the bookshop?',
                                         'What does it say?',
                                         'What do you want to buy at the shopping centre?',
                                         'Is there a bakery near here?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi cách để đến nơi nào đó?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['What', 'How', 'Where', 'When'],
                                   'plain': True,
                                   'q': 'A: _____________ can I get to the cinema?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['I want to buy some clothes.',
                                         "I'm at the shopping centre.",
                                         "Great! Let's go.",
                                         'It says "stop".',
                                         'Go straight and turn right.'],
                                   'plain': True,
                                   'q': 'How can I get to the campsite?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 17 – In the city: Kiểm tra 3',
 'unit': 17}
