# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on1-de11',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'q1',
                        'instr': 'Listen and circle (nghe và khoanh)',
                        'items': [{'id': 'q1.1', 'o': ['July', 'February', 'January'], 'q': 'Is your sports day in _____?', 't': 'mcq'},
                                  {'id': 'q1.2', 'o': ['July', 'January', 'cycling'], 'q': 'I like ______.', 't': 'mcq'}]},
                       {'id': 'q2',
                        'instr': 'Listen and tick or cross (nghe và chọn tick/cross)',
                        'items': [{'id': 'q2.3', 'o': ['Tick (✓)', 'Cross (✗)'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q2.4', 'o': ['Tick (✓)', 'Cross (✗)'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q2.5', 'o': ['Tick (✓)', 'Cross (✗)'], 'q': 'Nghe câu số 3.', 't': 'mcq'},
                                  {'id': 'q2.6', 'o': ['Tick (✓)', 'Cross (✗)'], 'q': 'Nghe câu số 4.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de11/p2.png" alt="Hình">'},
                       {'id': 'q3',
                        'instr': 'Listen and tick (nghe và chọn tranh)',
                        'items': [{'id': 'q3.7', 'o': ['Tranh a', 'Tranh b'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q3.8', 'o': ['Tranh a', 'Tranh b'], 'q': 'Nghe câu số 2.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de11/p3.png" alt="Hình">'},
                       {'id': 'q4',
                        'instr': 'Choose the best option (chọn đáp án đúng)',
                        'items': [{'id': 'q4.9',
                                   'o': ['I can swim.', 'On Mondays.', "It's 7 o'clock in the morning.", 'At the weekend.'],
                                   'q': 'What time do you go to school?',
                                   't': 'mcq'},
                                  {'id': 'q4.10', 'o': ["No, she can't.", 'Yes, he can.', 'No, he can.', 'Yes, she can.'], 'q': 'Can he draw?', 't': 'mcq'},
                                  {'id': 'q4.11',
                                   'o': ['I have English on Tuesdays.',
                                         'I like maths.',
                                         "I don't go to school on Sundays.",
                                         'I have it on Mondays and Thursdays.'],
                                   'q': 'When do you have maths?',
                                   't': 'mcq'},
                                  {'id': 'q4.12',
                                   'o': ['Do you like English?', 'When do you have English?', 'What subjects do you have today?', "What's favorite subject?"],
                                   'q': 'I have it on Mondays and Fridays.',
                                   't': 'mcq'},
                                  {'id': 'q4.13',
                                   'o': ["It's in Mondays.", 'It’s in October.', 'It was at the weekend.', 'It was on the beach.'],
                                   'q': 'When’s your sports day?',
                                   't': 'mcq'},
                                  {'id': 'q4.14',
                                   'o': ['I am in England.', 'I am in Tokyo.', 'She was in Malaysia.', 'I was in Tokyo.'],
                                   'q': 'Where were you last summer?',
                                   't': 'mcq'}]},
                       {'id': 'q5',
                        'instr': 'Reorder words to make right sentences (sắp xếp từ thành câu)',
                        'items': [{'id': 'q5.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['summer?', 'Were', 'on', 'last', 'the', 'beach', 'you']},
                                  {'id': 'q5.16', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['were', 'weekend?', 'last', 'Where', 'you']},
                                  {'id': 'q5.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'is', 'day', 'sports', 'February.', 'Our']},
                                  {'id': 'q5.18', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'birthday', 'July.', 'is', 'My']},
                                  {'id': 'q5.19', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['My', 'favorite', 'is', 'English.', 'subject']},
                                  {'id': 'q5.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['have', 'science', 'today.', 'We']},
                                  {'id': 'q5.21', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['mountains.', 'the', 'school', 'is', 'in', 'My']},
                                  {'id': 'q5.22',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['near', 'my', 'are', 'school.', 'villages', 'There', 'three']},
                                  {'id': 'q5.23', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['some', 'I', 'water.', 'want']}]},
                       {'id': 'q6',
                        'instr': 'Read and chose True or False (đúng hay sai)',
                        'items': [{'id': 'q6.24', 'q': "Bill's from Britain.", 't': 'tf'},
                                  {'id': 'q6.25', 'q': 'His birthday’s in January.', 't': 'tf'},
                                  {'id': 'q6.26', 'q': 'He wants some chips and some lemonade.', 't': 'tf'},
                                  {'id': 'q6.27', 'q': "He's ten years old.", 't': 'tf'}],
                        'passage': '<p>Dear pen friend, My name’s Bill. I’m from Britain. I’m nine years old. My birthday’s in March. It’s coming soon. I want '
                                   'some chips and some lemonade at my party. What about you? When’s your birthday? What do you want to eat and drink at your '
                                   'party? Write to me soon. Bill</p>'},
                       {'id': 'q7',
                        'instr': 'Read and choose A, B or C (đọc và chọn đáp án đúng)',
                        'items': [{'id': 'q7.28', 'o': ['in', 'of', 'from', 'on'], 'q': 'He goes to school __________ Mondays to Fridays', 't': 'mcq'},
                                  {'id': 'q7.29', 'o': ['every', 'at', 'each', 'all'], 'q': 'He has Vietnamese and maths _________ school day.', 't': 'mcq'},
                                  {'id': 'q7.30', 'o': ['like', 'love', 'likes', 'enjoy'], 'q': 'He ________ music very much.', 't': 'mcq'}],
                        'passage': '<p>My name is Minh. I go to school from Mondays to Fridays. I have Vietnamese and maths every school day. I have English '
                                   'on Mondays, Thursdays and Fridays. I have science on Wednesdays and Thursdays. I have music on Tuesdays. I like music very '
                                   'much.</p>'}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK1 – Đề 11',
 'unit': 'OnHK1'}
