# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u17-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['a', 'there', 'here?', 'water', 'Is', 'park', 'near']},
                                  {'id': 't1.2',
                                   'o': ['Go straight.', 'Turn right.', 'Turn left.', 'Turn round.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói: “Rẽ trái.”',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['sports centre', 'shopping centre', 'bookshop', 'cinema'],
                                   'plain': True,
                                   'q': 'I want to see a movie. How can I get to the _____________.',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['I want to buy some clothes.',
                                         "I'm at the shopping centre.",
                                         "Great! Let's go.",
                                         'It says "stop".',
                                         'Go straight and turn right.'],
                                   'plain': True,
                                   'q': 'What do you want to buy at the shopping centre?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 4. A: Do you want to go to the _____ with me?',
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['food', 'Pham', 'a', 'Dong', 'is', 'stall', 'in', 'Van', 'Street.', 'There']},
                                  {'id': 't1.7',
                                   'o': ['Is there a bookshop near here?',
                                         'How can I get to the bookshop?',
                                         'What do you want to buy at the bookshop?',
                                         'Do you want to go to the bookshop with me?'],
                                   'plain': True,
                                   'q': 'Câu: “Go straight" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['stop', 'go', 'run', 'go straight'],
                                   'plain': True,
                                   'q': 'We _____________ when the light is red.',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['I want to buy some clothes.',
                                         "I'm at the shopping centre.",
                                         "Great! Let's go.",
                                         'It says "stop".',
                                         'Go straight and turn right.'],
                                   'plain': True,
                                   'q': 'Do you want to go to the swimming pool with me?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 5. A: How can I _____to the campsite?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['does', 'say?', 'it', 'What']},
                                  {'id': 't1.12',
                                   'o': ['Có một hiệu sách trên đường Nguyễn Thái Sơn.',
                                         'Có một sạp bán thực phẩm trên đường Nguyễn Thái Sơn.',
                                         'Có một hiệu bánh mì trên đường Nguyễn Thái Sơn.',
                                         'Có một rạp chiếu phim trên đường Nguyễn Thái Sơn.'],
                                   'plain': True,
                                   'q': 'Câu: “There’s a food stall in Nguyen Thai Son Street.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['yellow', 'green', 'red', 'off'],
                                   'plain': True,
                                   'q': 'We go when the light is _______________.',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'bookshop.', 'the', 'to', 'go', 'We', 'want']},
                                  {'id': 't1.15',
                                   'o': ['What does it say?',
                                         'How can she get to the shopping centre?',
                                         'Is there a cinema near here?',
                                         'What do you want to buy at the shopping centre?'],
                                   'plain': True,
                                   'q': 'Câu: "Go straight and turn right." trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['food stall', 'bookshop', 'sports centre', 'campsite'],
                                   'plain': True,
                                   'q': 'I want to buy some meat. How can I get to the ______________?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Street.', 'Nguyen', 'There', 'in', 'Son', 'a', 'bakery', 'Thai', 'is']},
                                  {'id': 't1.18',
                                   'o': ['Is there a bookshop near here?',
                                         'What do you want to buy at the food stall?',
                                         'How can he get to the bookshop?',
                                         'What does he want to buy at the bookshop?'],
                                   'plain': True,
                                   'q': 'Câu "He wants to buy some books” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['sports centre', 'shopping centre', 'cinema', 'bakery'],
                                   'plain': True,
                                   'q': 'A: How can I get to the ____________?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['get', 'campsite?', 'to', 'the', 'can', 'How', 'we']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 17 – In the city: Kiểm tra 2',
 'unit': 17}
