# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r1-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["I'm fine, thank you.", "I'm Mike.", "I'm from Australia.", "He's from Australia."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where\'s Mike from?"',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['What', 'Where', 'When', 'How'], 'plain': True, 'q': 'A: _____________ is Laura from?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['I go to school.', "I'm from England.", "No, I can't.", "She goes to school at seven o'clock.", 'I want some water.'],
                                   'plain': True,
                                   'q': 'Where are you from, Mary?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['night', 'morning', 'bye'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Mary: Good _____. I'm Mary.",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'from?', 'Nam', 'Where']},
                                  {'id': 't1.6',
                                   'o': ["Where's she from?", "Where's he from?", 'Where are you from?', "Where're they from?"],
                                   'plain': True,
                                   'q': 'Câu “I’m from Malaysia” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['is', 'am', 'are', 'does'], 'plain': True, 'q': 'Mary _____________ from England.', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['I go to school.', "I'm from England.", "No, I can't.", "She goes to school at seven o'clock.", 'I want some water.'],
                                   'plain': True,
                                   'q': 'What time does Lan go to school?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['from', 'in', 'at'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Lan: Hi, Mary. I'm Lan. Are you _____ Australia?",
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['old.', 'years', 'Mai', 'eight', 'is']},
                                  {'id': 't1.11',
                                   'o': ["Where's he from?", 'What time do you get up?', 'What day is it today?', 'What time is it?'],
                                   'plain': True,
                                   'q': 'Câu: “It\'s eight thirty" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['What', 'When', 'Where', 'Why'],
                                   'plain': True,
                                   'q': '_____________ day is it today, Linh?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['I go to school.', "I'm from England.", "No, I can't.", "She goes to school at seven o'clock.", 'I want some water.'],
                                   'plain': True,
                                   'q': 'What do you do on Tuesdays, Lan?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['Australian', 'Korean', 'England'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Mary: No, I'm not. I'm from _____.",
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['breakfast?', 'does', 'have', 'What', 'she', 'time']},
                                  {'id': 't1.16',
                                   'o': ["I get up at six o'clock.",
                                         'She gets up at five thirty.',
                                         "Let's have breakfast.",
                                         "I have breakfast at seven o'clock."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What time do you have breakfast?"',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ["It's Sunday today.", 'I do housework.', "She's from Thailand.", 'I go to school on Mondays.'],
                                   'plain': True,
                                   'q': 'A: What do you do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['I go to school.', "I'm from England.", "No, I can't.", "She goes to school at seven o'clock.", 'I want some water.'],
                                   'plain': True,
                                   'q': 'What do you want to drink, Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['Japan', 'English', 'Korea'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Lan: Wow. So you're _____.",
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['at', 'lunch', 'school.', 'at', 'have', "o'clock", 'They', 'eleven']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Review 1: Kiểm tra 1',
 'unit': 'Review1'}
