# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': {'blanks': [['A'], ['E'], ['B'], ['D']]},
 'l2.2': 'T',
 'l2.3': 'F',
 'l2.4': 'T',
 'l2.5': 'F',
 'l3a.6': 'B',
 'l3a.7': 'A',
 'l3b.8': 'A',
 'l3b.9': 'C',
 'r1.10': ['five o’clock', 'five'],
 'r1.11': ['with the cooking'],
 'r1.12': ['wash the dishes'],
 'r2.13': 'C',
 'r2.14': 'B',
 'r2.15': 'C',
 'r2.16': 'A',
 'r3.17': 'F',
 'r3.18': 'T',
 'r3.19': 'F',
 'w1.20': ['bakery'],
 'w1.21': ['opposite'],
 'w1.22': ['clean the floor'],
 'w1.23': ['turn left'],
 'w2.24': ['She is short and big.', 'She’s short and big.', 'She is short and big'],
 'w2.25': ['She cleans the house on Sundays.', 'She cleans the house.'],
 'w2.26': ['It’s forty-five thousand dong.', 'It is forty-five thousand dong.'],
 'w3.27': ['Why do you like elephants?'],
 'w3.28': ['The kids are dancing around the campfire.', 'Kids are dancing around the campfire.'],
 'w3.29': ['I like peacocks because they dance beautifully.']}

EXPLANATIONS = {'l1.1': 'Theo đáp án của đề: 1–A, 2–E, 3–B, 4–D (C là ví dụ số 0).',
 'l2.2': 'Đáp án: True (theo đáp án của đề).',
 'l2.3': 'Đáp án: False (theo đáp án của đề).',
 'l2.4': 'Đáp án: True (theo đáp án của đề).',
 'l2.5': 'Đáp án: False (theo đáp án của đề).',
 'l3a.6': 'Đáp án: B. worker / factory',
 'l3a.7': 'Đáp án: A. yoga / gym',
 'l3b.8': 'Đáp án: A. sunny',
 'l3b.9': 'Đáp án: C. thirty thousand',
 'r1.10': 'I go home at five o’clock.',
 'r1.11': 'help my mom with the cooking = giúp mẹ nấu ăn.',
 'r1.12': 'After dinner, I wash the dishes.',
 'r2.13': 'on Sundays = vào các ngày Chủ nhật.',
 'r2.14': 'go to the cinema = đi xem phim.',
 'r2.15': 'dancing around the campfire = nhảy quanh đống lửa trại.',
 'r2.16': 'at the shopping centre = ở trung tâm mua sắm.',
 'r3.17': 'Sai: giraffes … running very quickly.',
 'r3.18': 'Đúng: I like them because they roar loudly.',
 'r3.19': 'Sai: Linda thích công vì chúng múa đẹp (dance beautifully); “sing merrily” là lý do thích chim.',
 'w1.20': 'bakery = tiệm bánh.',
 'w1.21': 'opposite = đối diện.',
 'w1.22': 'clean the floor = lau/dọn sàn nhà.',
 'w1.23': 'Biển báo: đi thẳng rồi rẽ trái (turn left).',
 'w2.24': 'Câu đúng: She is short and big.',
 'w2.25': 'Câu đúng: She cleans the house on Sundays.',
 'w2.26': 'Câu đúng: It’s forty-five thousand dong.',
 'w3.27': 'Câu đúng: Why do you like elephants?',
 'w3.28': 'Câu đúng: The kids are dancing around the campfire.',
 'w3.29': 'Câu đúng: I like peacocks because they dance beautifully.'}
