# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'B',
 'l1.2': 'C',
 'l1.3': 'A',
 'l1.4': 'B',
 'l2.5': '1',
 'l2.6': '4',
 'l2.7': '2',
 'l2.8': '3',
 'l3.10': '4',
 'l3.11': '1',
 'l3.12': '2',
 'l3.9': '3',
 'l4.13': ['want'],
 'l4.14': ['campsite'],
 'l4.15': ['six'],
 'l4.16': ['Japan'],
 'r1.17': {'blanks': [['D'], ['A'], ['E'], ['C']]},
 'r2.18': 'B',
 'r2.19': 'A',
 'r2.20': 'C',
 'r3.21': 'F',
 'r3.22': 'F',
 'r3.23': 'T',
 'w1.24': ['water'],
 'w1.25': ['garden'],
 'w1.26': ['English'],
 'w2.27': ['What’s your favourite subject?'],
 'w2.28': ['There are two buildings at my school.'],
 'w2.29': ['What do you do on Tuesdays?']}

EXPLANATIONS = {'l1.1': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.2': 'Đáp án C (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.3': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.4': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l2.5': 'Tranh A ứng với câu 1 (theo đáp án của đề).',
 'l2.6': 'Tranh C ứng với câu 4 (theo đáp án của đề).',
 'l2.7': 'Tranh D ứng với câu 2 (theo đáp án của đề).',
 'l2.8': 'Tranh E ứng với câu 3 (theo đáp án của đề).',
 'l3.10': 'Tranh C ứng với câu 4 (theo đáp án của đề).',
 'l3.11': 'Tranh D ứng với câu 1 (theo đáp án của đề).',
 'l3.12': 'Tranh E ứng với câu 2 (theo đáp án của đề).',
 'l3.9': 'Tranh A ứng với câu 3 (theo đáp án của đề).',
 'l4.13': 'Đáp án: want',
 'l4.14': 'Đáp án: campsite',
 'l4.15': 'Đáp án: six',
 'l4.16': 'Đáp án: Japan',
 'r1.17': 'Đáp án theo đáp án của đề: Maths teacher–D, ride a bike–A, on the beach–E, computer room–C',
 'r2.18': 'Đáp án: B. There',
 'r2.19': 'Đáp án: A. are',
 'r2.20': 'Đáp án: C. play',
 'r3.21': 'Đáp án: False (theo đáp án của đề).',
 'r3.22': 'Đáp án: False (theo đáp án của đề).',
 'r3.23': 'Đáp án: True (theo đáp án của đề).',
 'w1.24': 'Từ đúng: water',
 'w1.25': 'Từ đúng: garden',
 'w1.26': 'Từ đúng: English',
 'w2.27': 'Câu đúng: What’s your favourite subject?',
 'w2.28': 'Câu đúng: There are two buildings at my school.',
 'w2.29': 'Câu đúng: What do you do on Tuesdays?'}
