# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u4-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['What do you want to eat?', 'What day is it today?', "When's your birthday?", 'What do you want to drink?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Sinh nhật của bạn là khi nào?”?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['What day is it today?', 'What do you do on Saturdays?', 'What do you want to eat?', "When's your birthday?"],
                                   'plain': True,
                                   'q': 'Câu “It\'s in July" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Bạn muốn ăn gì?', 'Bạn muốn uống gì?', 'Hôm nay là thứ mấy?', 'Sinh nhật của bạn là khi nào?'],
                                   'plain': True,
                                   'q': 'Câu “When’s your birthday?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['What do you want to drink?', 'What do you want to eat?', 'What does he want to drink?', 'What does she want to eat?'],
                                   'plain': True,
                                   'q': 'Câu: “I want some chips.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['What day is it today?', "When's your birthday, Quan?", 'What do you want to drink?', 'What do you want to eat?'],
                                   'plain': True,
                                   'q': 'Câu “I want some lemonade." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['"When\'s your birthday, Mai?"', 'Where are you from, Mai?', 'What day is it today, Mai?', 'What time is it, Mai?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là "Sinh nhật của bạn là khi nào vậy Mai?".',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['Sinh nhật của tôi là vào tháng Năm.',
                                         'Sinh nhật của tôi là vào tháng Ba.',
                                         'Hôm nay là sinh nhật của tôi.',
                                         'Sinh nhật của tôi là vào tháng Bảy.'],
                                   'plain': True,
                                   'q': 'Câu “My birthday is in March.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['What do you do on Sundays, Mai?',
                                         'What do you want to drink, Mai?',
                                         'What do you want to eat, Mai?',
                                         'Where are you from, Mai?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn muốn uống gì vậy, Mai?”',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['What do you do on Mondays, Nam?',
                                         'What do you want to eat, Nam?',
                                         'What do you want to drink, Nam?',
                                         'What time is it, Nam?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn muốn ăn gì vậy Nam?”',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Tôi muốn uống sữa.', 'Tôi muốn uống nước ép.', 'Tôi muốn ăn khoai tây chiên.', 'Tôi muốn ăn nhỏ.'],
                                   'plain': True,
                                   'q': 'Câu: “I want some grapes." có nghĩa là.',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['What', 'How', 'When', 'Where'], 'plain': True, 'q': 'A: _____________is your birthday?', 't': 'mcq'},
                                  {'id': 'b.2',
                                   'o': ['play', 'do', 'drink', 'eat'],
                                   'plain': True,
                                   'q': 'A: What do you want to _____________, Quan?',
                                   't': 'mcq'},
                                  {'id': 'b.3', 'o': ['When', 'Where', 'How', 'What'], 'plain': True, 'q': '_____________ do you want to drink?', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['grapes', 'lemonade d. juice d. water'], 'plain': True, 'q': 'A: What do you want to eat?', 't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['Thailand', 'Saturday', 'December', "seven o'clock."],
                                   'plain': True,
                                   'q': "A: When's your birthday?",
                                   't': 'mcq'},
                                  {'id': 'b.6', 'o': ['What', 'When', 'Where', 'How'], 'plain': True, 'q': 'A: ____________ are you doing, Mai?', 't': 'mcq'},
                                  {'id': 'b.7', 'o': ['at', 'on', 'in', 'to'], 'plain': True, 'q': 'My birthday is _____________ November.', 't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['play', 'do', 'eat', 'drink'],
                                   'plain': True,
                                   'q': 'A: What do you want to _____________, Quan?',
                                   't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['When', 'What', 'Where', 'How'],
                                   'plain': True,
                                   'q': "A: _____________'s your brother's birthday?",
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['milk', 'meat', 'chicken', 'jam'],
                                   'plain': True,
                                   'q': 'A: What do you want to drink, Lan?',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['What day is it today?',
                                            "When's your birthday?",
                                            'What do you want to eat?',
                                            'What do you want to drink?',
                                            'What are you doing?'],
                                   'o': ['I want some meat.',
                                         "It's Tuesday.",
                                         'I want some lemonade.',
                                         "I'm making a cake for my birthday party.",
                                         "It's in November."],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['cake', 'When', 'eat', 'drink', 'November'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['cake', 'When', 'eat', 'drink', 'November'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['cake', 'When', 'eat', 'drink', 'November'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['cake', 'When', 'eat', 'drink', 'November'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['cake', 'When', 'eat', 'drink', 'November'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': "1. A: <b>(1)&nbsp;______</b> is your birthday, Tony?<br>B: It's in July. What about you?<br>A: It's in "
                                   "<b>(2)&nbsp;______</b>.<br>2. A: What are you doing, Mary?<br>B: I'm making a <b>(3)&nbsp;______</b> for my sister's "
                                   "birthday.<br>A: When's her birthday?<br>B: It's in May.<br>3. A: What do you want to <b>(4)&nbsp;______</b>, Lucy?<br>B: I "
                                   'want some water.<br>4. A: Happy birthday, Lan!<br>B: Thank you. What do you want to <b>(5)&nbsp;______</b>?<br>A: I want '
                                   'some chicken.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and choose the correct answers. (Đọc và chọn đáp án đúng.)',
                        'items': [{'id': 'e.1',
                                   'o': ["She's from Thailand.", "She's from Vietnam.", "She's from Malaysia.", "She's from England."],
                                   'plain': True,
                                   'q': "Where's Kim from?",
                                   't': 'mcq'},
                                  {'id': 'e.2',
                                   'o': ["She's seven years old.", "She's eight years old.", "She's nine years old.", "She's ten years old."],
                                   'plain': True,
                                   'q': 'How old is she?',
                                   't': 'mcq'},
                                  {'id': 'e.3',
                                   'o': ["It's in July.", "It's on the nineth of May.", 'Her birthday is in June.', "It's on the eighth of May."],
                                   'plain': True,
                                   'q': "When's Kim's birthday?",
                                   't': 'mcq'},
                                  {'id': 'e.4',
                                   'o': ['She wants a big cake and some chips.',
                                         'She wants a big cake and some grapes.',
                                         'She wants some jam and some milk.',
                                         'She wants some chicken and some juice.'],
                                   'plain': True,
                                   'q': 'What does she want to eat at her party?',
                                   't': 'mcq'},
                                  {'id': 'e.5',
                                   'o': ['She wants some lemonade.', 'She wants some milk.', 'She wants some juice.', 'She wants some grapes.'],
                                   'plain': True,
                                   'q': 'What does she want to drink?',
                                   't': 'mcq'}],
                        'passage': "My name's Kim. I'm from Kuala Lumpur. It's a big city in Malaysia. I'm eight years old. Today is the eighth of May. "
                                   "Tomorrow is my birthday. I want a big cake, some grapes and some lemonade at my party. What about you? When's your "
                                   'birthday? What do you want to eat and drink at your party?'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Lucy?', 'What', 'are', 'doing,', 'you']},
                                  {'id': 'f.2',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['birthday', 'for', 'cake', 'my', "I'm", 'a', 'doing', 'party.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['birthday?', 'your', 'When', 'is']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'My', 'is', 'birthday', 'October.']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['When', "brother's", 'birthday?', 'is', 'your']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'September.', 'is', 'It']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['she', 'eat?', 'want', 'does', 'What', 'to']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'She', 'eat', 'bread.', 'some', 'wants']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'drink?', 'does', 'want', 'she', 'What']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['some', 'wants', 'chips', 'and', 'some', 'She', 'milk.']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'},
           {'audio': True,
            'groups': [{'id': 'n',
                        'instr': 'Nghe file âm thanh và làm các câu theo số thứ tự trong bài nghe.',
                        'items': [{'id': 'n.1', 'q': "Câu 1. When's your birthday? -It's in {_}", 't': 'fill'},
                                  {'id': 'n.2', 'q': "Câu 2. When's your birthday? -It's in {_}", 't': 'fill'},
                                  {'id': 'n.3', 'q': "Câu 3. When's your birthday? -It's in {_}", 't': 'fill'},
                                  {'id': 'n.4', 'q': "Câu 4. When's your birthday? -It's in {_}", 't': 'fill'},
                                  {'id': 'n.5',
                                   'o': ['grapes', 'chips', 'chicken'],
                                   'plain': True,
                                   'q': 'Câu 5. What do you want to eat?- I want some_____________',
                                   't': 'mcq'},
                                  {'id': 'n.6',
                                   'o': ['milk', 'lemonade', 'water'],
                                   'plain': True,
                                   'q': 'Câu 6. What do you want to drink?- I want some_____________',
                                   't': 'mcq'},
                                  {'id': 'n.7',
                                   'o': ['water', 'lemonade', 'milk'],
                                   'plain': True,
                                   'q': 'Câu 7. What do you want to drink?- I want some_____________',
                                   't': 'mcq'},
                                  {'id': 'n.8',
                                   'o': ['grapes', 'chips', 'jam'],
                                   'plain': True,
                                   'q': 'Câu 8. What do you want to eat?- I want some_____________',
                                   't': 'mcq'},
                                  {'id': 'n.9', 'q': 'Câu 9. I want some {_}', 't': 'fill'},
                                  {'id': 'n.10', 'q': 'Câu 10. Here you are. {_}', 't': 'fill'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Luyện nghe'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi ngày sinh nhật của ai đó và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           "lời</td></tr><tr><td>When's your/her/his birthday?<br>Sinh nhật của bạn/cô ấy/cậu ấy khi nào?</td><td>It’s in... (tháng).<br>Đó là vào "
           "tháng....<br>My/Her/His birthday's in....<br>Sinh nhật của tôi/của cô ấy/của cậu ấy là vào... (tháng).</td></tr><tr><td>Ví dụ:<br>A: When's your "
           "birthday?<br>Sinh nhật của bạn là khi nào?<br>B: It's in December.<br>Đó là vào tháng Mười hai.</td><td>A: When's her birthday?<br>Sinh nhật của "
           'cô ấy là khi nào?<br>B: Her birthday is in October.<br>Sinh nhật của cô ấy là vào tháng Mười.</td></tr></table><p>2. Cách hỏi ai đó muốn ăn gì '
           'hoặc uống gì và cách trả lời:</p><p>+ Đối với chủ ngữ là you hoặc they:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           'lời</td></tr><tr><td>- What do you/they want to eat/drink?<br>Bạn/Họ muốn ăn/uống gì?</td><td>I/They want...<br>Tôi/Họ muốn...</td></tr><tr><td>Ví '
           'dụ:<br>A: What do you want to eat? Bạn muốn ăn gì?<br>B: I want some fish. Tôi muốn ăn cá.<br>A: What do they want to drink? Họ muốn uống '
           'gì?<br>B: They want some lemonade. Họ muốn uống nước chanh.</td></tr></table><p>+ Đối với chủ ngữ là she hoặc he:</p><table '
           'class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>What does she/he want to eat/drink?<br>Cô ấy/Cậu ấy muốn ăn/uống gì?</td><td>- '
           'She/He wants...<br>Cô ấy/Cậu ấy muốn...</td></tr><tr><td>Ví dụ:<br>A: What does she want to eat? Cô ấy muốn ăn gì?<br>B: She wants some bread. Cô '
           'ấy muốn ăn bánh mì.<br>A: What does she want to drink? Cô ấy muốn uống gì?<br>B: She wants some milk. Cô ấy muốn uống sữa..</td></tr></table>',
 'title': 'Unit 4 – My birthday party: Luyện tập',
 'unit': 4}
