# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de8',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and tick A, B or C (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l1.1',
                                   'img': 'l1_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.2',
                                   'img': 'l1_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.3',
                                   'img': 'l1_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.4',
                                   'img': 'l1_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and order the dialogue (nghe và đánh số thứ tự các hội thoại).',
                        'items': [{'id': 'l2.5',
                                   'left': [{'t': 'A: What does she look like? – B: She is fat and tall.'},
                                            {'t': 'A: Sorry, I want to go to the bakery. It is in Oxford Street. – B: You can turn round.'},
                                            {'t': 'A: What does he do? – B: He is a policeman.'},
                                            {'t': 'A: What was the weather like last weekend? – B: It was cloudy.'}],
                                   'o': ['1', '2', '3', '4'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<p>Ví dụ (0): <i>Where do you live? – I live in Quang Trung Street.</i> (hội thoại số 0). Nghe và điền số thứ tự 1–4 cho '
                                   'các hội thoại còn lại.</p>'},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen to the passage and complete (nghe đoạn văn và điền từ).',
                        'items': [{'id': 'l3.6', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'l3.7', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'l3.8', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'l3.9', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>It is a nice day today. The weather is (0) <b>windy</b> and cloudy. In the morning, my family will go to the zoo to see '
                                   'some animals. We all like <b>(1) ______</b> because they have a long neck and legs. After the zoo, we will go to the '
                                   '<b>(2) ______</b> in the afternoon. Some of my friends are already there. They’re playing <b>(3) ______</b>. I promise to '
                                   'help my mom with <b>(4) ______</b> in the evening.</p>'},
                       {'id': 'r1',
                        'instr': 'Question 4. Read and answer the question by choosing A, B or C (chọn câu trả lời đúng).',
                        'items': [{'id': 'r1.10',
                                   'o': ['It’s so hot.', 'Turn left and go straight.', 'It’s in the busy city.'],
                                   'q': 'How can I get to the water park?',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'o': ['Because they run slowly.', 'Because they roar loudly.', 'Because they dance beautifully.'],
                                   'q': 'Why do you like peacocks?',
                                   't': 'mcq'},
                                  {'id': 'r1.12',
                                   'o': ['She goes to the cinema with her friends.', 'She likes running.', 'She hates cooking.'],
                                   'q': 'What does your sister do on Sundays?',
                                   't': 'mcq'}]},
                       {'bank': ['thousand', 'bookshop', 'ninety', 'shopping'],
                        'id': 'r2',
                        'instr': 'Question 5. Fill in each blank with one given word (chọn từ trong khung điền vào chỗ trống).',
                        'items': [{'id': 'r2.13', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.14', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'q': 'Chỗ trống (3): {_}', 't': 'fill'}],
                        'passage': '<p>Ginny and her mother are at a (0) <b>shopping</b> centre. Ginny wants to buy some stationery. They go to the <b>(1) '
                                   '______</b>. The pen is ten thousand dong. The notebook is fifteen <b>(2) ______</b> dong. And the school bag is <b>(3) '
                                   '______</b> thousand dong. Ginny buys two pens, a notebook, and a school bag. She is very happy with her new school '
                                   'things.</p><img src="../../../../assets/lop4_on2_de8/p5.png" alt="Hình" style="max-width:240px;height:auto">'},
                       {'id': 'r3',
                        'instr': 'Question 6. Reorder the sentences to make a complete conversation (sắp xếp thành hội thoại: chọn vị trí 2–5 của từng câu; '
                                 'câu “Hello Ben, look at this road sign. What does it say?” đã đứng đầu, là vị trí 1).',
                        'items': [{'id': 'r3.16',
                                   'left': [{'t': 'Oh, ok. How can I get to the food stall, Ben?'},
                                            {'t': 'Go straight, turn left, and turn right. The food stall is on the right.'},
                                            {'t': 'Thank you, Ben. Have a good day!'},
                                            {'t': 'It says “Go straight”, Lucy.'}],
                                   'o': ['2', '3', '4', '5'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<p><b>1.</b> Hello Ben, look at this road sign. What does it say?</p>'},
                       {'id': 'w1',
                        'instr': 'Question 7. Fill in the blanks with suitable words (nhìn tranh, điền từ phù hợp).',
                        'items': [{'id': 'w1.17', 'img': 'w1_1.png', 'q': 'I help my mom with the housework {_}.', 't': 'fill'},
                                  {'id': 'w1.18', 'img': 'w1_2.png', 'q': 'My brother {_} on Saturdays.', 't': 'fill'},
                                  {'id': 'w1.19', 'img': 'w1_3.png', 'q': 'It’s {_} today.', 't': 'fill'},
                                  {'id': 'w1.20', 'img': 'w1_4.png', 'q': 'They are playing {_}.', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Question 8. Reorder the words to make complete sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w2.21', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['dishes?', 'do', 'wash', 'you', 'When', 'the']},
                                  {'id': 'w2.22',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['sports', 'goes', 'to', 'the', 'Saturdays.', 'father', 'centre', 'My', 'on']},
                                  {'id': 'w2.23',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['they', 'because', 'I', 'horses', 'like', 'quickly.', 'run']}]},
                       {'id': 'w3',
                        'instr': 'Question 9. Use the given words to make sentences (dùng từ gợi ý viết thành câu hoàn chỉnh).',
                        'items': [{'id': 'w3.24', 'q': 'I/ live/ 84 Tran Hung Dao Street<br>→ {_}', 't': 'fill'},
                                  {'id': 'w3.25', 'q': 'turn left/ turn right/ hospital.<br>→ {_}', 't': 'fill'},
                                  {'id': 'w3.26', 'q': 'bookshop/ near/ gift shop.<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 8',
 'unit': 'OnHK2'}
