# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u13-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['has', 'face.', 'round', 'tall', 'is', 'and', 'brother', 'a', 'My']},
                                  {'id': 't1.2',
                                   'o': ['What does she do?', 'What does she look like?', 'Where does she work?', 'Where does she live?'],
                                   'plain': True,
                                   'q': 'Câu: "She has a long hair" trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['What', 'Where', 'How', 'When'],
                                   'plain': True,
                                   'q': '____________ does your teacher look like?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Yes, I do.', 'He is big and short.', "It's my brother.", "He's a student.", 'She is tall and slim.'],
                                   'plain': True,
                                   'q': 'What does she look like?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['is', 'does', 'do', 'are'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What _____ she look like?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['short', 'father', 'has', 'hair.', 'My']},
                                  {'id': 't1.7',
                                   'o': ['Cô ấy có gương mặt tròn.', 'Cô ấy có mái tóc dài.', 'Cô ấy có đôi mắt to.', 'Cô ấy có đôi mắt nhỏ.'],
                                   'plain': True,
                                   'q': 'Câu: “She has big eyes" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['tall', 'big', 'high', 'long'],
                                   'plain': True,
                                   'q': 'My grandfather is ____________ and short.',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['Yes, I do.', 'He is big and short.', "It's my brother.", "He's a student.", 'She is tall and slim.'],
                                   'plain': True,
                                   'q': 'What does your father look like?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['short', 'high', 'old', 'slim'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: She's tall and _____.",
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'like?', 'sister', 'does', 'look', 'What']},
                                  {'id': 't1.12',
                                   'o': ['What does he do?', 'Where does he work?', 'Who does he live with?', 'What does he look like?'],
                                   'plain': True,
                                   'q': "Câu: “He's big.” trả lời cho câu hỏi nào sau đây:",
                                   't': 'mcq'},
                                  {'id': 't1.13', 'o': ['does', 'are', 'is', 'has'], 'plain': True, 'q': 'A: What does your brother look like?', 't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'and', 'slim.', 'beautiful', 'My', 'sister']},
                                  {'id': 't1.15',
                                   'o': ['What does your brother do?', 'Where does your brother work?', 'What does your brother look like?', "Who's that?"],
                                   'plain': True,
                                   'q': 'Câu: “He has a round face.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.16', 'o': ['is', 'be', 'look', 'have'], 'plain': True, 'q': 'A: What does she ____________ like?', 't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['and', 'big', 'has', 'eyes', 'She', 'hair.', 'long']},
                                  {'id': 't1.18',
                                   'o': ["He's thin and tall.", "She's a nurse.", "She's slim.", "He's a worker."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does your sister look like?”',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['your sister', 'they', 'we', 'you'],
                                   'plain': True,
                                   'q': 'What does ____________ look like?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['father', 'very', 'tall.', 'My', 'is']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 13 – Appearance: Kiểm tra 2',
 'unit': 13}
