# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on1-de12',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'q1',
                        'instr': 'Listen and number (nghe và đánh số)',
                        'items': [{'id': 'q1.1', 'o': ['Tranh d', 'Tranh a', 'Tranh c', 'Tranh b'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q1.2', 'o': ['Tranh d', 'Tranh b', 'Tranh a', 'Tranh c'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q1.3', 'o': ['Tranh d', 'Tranh a', 'Tranh c', 'Tranh b'], 'q': 'Nghe câu số 3.', 't': 'mcq'},
                                  {'id': 'q1.4', 'o': ['Tranh a', 'Tranh d', 'Tranh c', 'Tranh b'], 'q': 'Nghe câu số 4.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de12/p1.png" alt="Hình">'},
                       {'id': 'q2',
                        'instr': 'Listen and tick or cross (nghe và chọn tick/cross)',
                        'items': [{'id': 'q2.5', 'o': ['Tick (✓)', 'Cross (✗)'], 'q': 'Nghe và xét tranh a.', 't': 'mcq'},
                                  {'id': 'q2.6', 'o': ['Tick (✓)', 'Cross (✗)'], 'q': 'Nghe và xét tranh b.', 't': 'mcq'},
                                  {'id': 'q2.7', 'o': ['Tick (✓)', 'Cross (✗)'], 'q': 'Nghe và xét tranh c.', 't': 'mcq'},
                                  {'id': 'q2.8', 'o': ['Tick (✓)', 'Cross (✗)'], 'q': 'Nghe và xét tranh d.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de12/p2.png" alt="Hình">'},
                       {'id': 'q3',
                        'instr': 'Listen and write True or False (nghe và chọn đúng/sai)',
                        'items': [{'id': 'q3.9', 'q': 'Nghe và xét tranh a.', 't': 'tf'},
                                  {'id': 'q3.10', 'q': 'Nghe và xét tranh b.', 't': 'tf'},
                                  {'id': 'q3.11', 'q': 'Nghe và xét tranh c.', 't': 'tf'},
                                  {'id': 'q3.12', 'q': 'Nghe và xét tranh d.', 't': 'tf'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de12/p3.png" alt="Hình">'},
                       {'id': 'q4',
                        'instr': 'Read and choose A,B or C (đọc và chọn đáp án đúng)',
                        'items': [{'id': 'q4.13',
                                   'o': ['Wednesday', 'Fridays', 'Sundays', 'Friday'],
                                   'q': 'I go to school from Mondays to _______.',
                                   't': 'mcq'},
                                  {'id': 'q4.14', 'o': ['on', 'in', 'at', 'of'], 'q': 'I have English ____ Mondays.', 't': 'mcq'},
                                  {'id': 'q4.15', 'o': ['likes', 'loves', 'loving', 'like'], 'q': 'I _______ music very much.', 't': 'mcq'}],
                        'passage': '<p>My name is Minh. I go to school from Mondays to Fridays. I have Vietnamese and maths today. I have English on Mondays, '
                                   'Thursdays and Fridays. I have science on Wednesdays and Thursdays. I have music on Tuesdays. I like music very much.</p>'},
                       {'id': 'q5',
                        'instr': 'Reorder words (sắp xếp từ thành câu)',
                        'items': [{'id': 'q5.16', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['subjects?', 'favourite', 'your', "What's"]},
                                  {'id': 'q5.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['There', 'buildings.', 'are', 'three']},
                                  {'id': 'q5.18', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['one', 'is', 'garden.', 'There']},
                                  {'id': 'q5.19', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['draw?', 'Can', 'he']},
                                  {'id': 'q5.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['summer?', 'were', 'Where', 'last', 'you']},
                                  {'id': 'q5.21', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['I', 'in', 'Sydney.', 'was']},
                                  {'id': 'q5.22',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'at', 'campsite', 'Were', 'last', 'you', 'weekend?']},
                                  {'id': 'q5.23', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'December?', 'sports', 'in', 'day', 'Is']},
                                  {'id': 'q5.24', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['maths?', 'Why', 'you', 'do', 'like']},
                                  {'id': 'q5.25',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['a', 'to', 'want', 'be', 'I', 'teacher.', 'Because', 'maths']}]},
                       {'id': 'q6',
                        'instr': 'Read and choose Yes/ No (đọc và chọn Yes/No)',
                        'items': [{'id': 'q6.26', 'o': ['Yes', 'No'], 'q': 'Our sports day is in January.', 't': 'mcq'},
                                  {'id': 'q6.27', 'o': ['Yes', 'No'], 'q': 'It is in the school classroom.', 't': 'mcq'},
                                  {'id': 'q6.28', 'o': ['Yes', 'No'], 'q': 'There are many pupils and teachers.', 't': 'mcq'},
                                  {'id': 'q6.29', 'o': ['Yes', 'No'], 'q': 'We play different sports and games.', 't': 'mcq'},
                                  {'id': 'q6.30', 'o': ['Yes', 'No'], 'q': 'The boys play badminton.', 't': 'mcq'}],
                        'passage': '<p>Our sports day is in November. It is in the school playground. There are many pupils and teachers. We play different '
                                   'sports and games. The boys play badminton. The girls play football. The teachers play basketball. It is a lot of '
                                   'fun.</p>'}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK1 – Đề 12',
 'unit': 'OnHK1'}
