# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'What is he doing?',
 'a.10': 'Họ đang nhảy múa quanh lửa trại.',
 'a.2': "Where's Nam?",
 'a.3': 'What are they doing?',
 'a.4': "What's Mai doing?",
 'a.5': 'What are Mai and Lan doing?',
 'a.6': "They're singing songs.",
 'a.7': "She's at the campsite.",
 'a.8': "They're putting up a tent.",
 'a.9': 'They are building a campfire.',
 'b.1': 'is',
 'b.10': 'telling',
 'b.2': 'What',
 'b.3': 'are',
 'b.4': 'they are',
 'b.5': 'playing',
 'b.6': 'building',
 'b.7': "isn't",
 'b.8': 'playing',
 'b.9': 'taking',
 'c.1': {'blanks': [['They are at the campsite.'], ['They are playing tug of war.'], ["He's at school."], ['She is studing English.'], ['Yes, she is.']]},
 'd.1': 'Are',
 'd.2': 'they',
 'd.3': 'are',
 'd.4': 'playing',
 'd.5': 'doing',
 'e.1': 'F',
 'e.2': 'T',
 'e.3': 'T',
 'e.4': 'F',
 'e.5': 'F',
 'e.6': 'T',
 'f.1': ['Where are Bill and his friends?'],
 'f.10': ['They are building a campfire.'],
 'f.2': ['What are Nam and Minh doing, Lan?'],
 'f.3': ['They are putting up a tent.'],
 'f.4': ['What is Mark doing, Mai?'],
 'f.5': ['He is flying a kite.'],
 'f.6': ['Son is watching TV.'],
 'f.7': ['Nam and his friends are playing tug of war.'],
 'f.8': ['Are Mai and Lan singing songs?'],
 'f.9': ['What are the boys doing?']}

EXPLANATIONS = {'a.1': 'Đáp án: What is he doing?',
 'a.10': 'Đáp án: Họ đang nhảy múa quanh lửa trại.',
 'a.2': "Đáp án: Where's Nam?",
 'a.3': 'Đáp án: What are they doing?',
 'a.4': "Đáp án: What's Mai doing?",
 'a.5': 'Đáp án: What are Mai and Lan doing?',
 'a.6': "Đáp án: They're singing songs.",
 'a.7': "Đáp án: She's at the campsite.",
 'a.8': "Đáp án: They're putting up a tent.",
 'a.9': 'Đáp án: They are building a campfire.',
 'b.1': 'Đáp án: is',
 'b.10': 'Đáp án: telling',
 'b.2': 'Đáp án: What',
 'b.3': 'Đáp án: are',
 'b.4': 'Đáp án: they are',
 'b.5': 'Đáp án: playing',
 'b.6': 'Đáp án: building',
 'b.7': "Đáp án: isn't",
 'b.8': 'Đáp án: playing',
 'b.9': 'Đáp án: taking',
 'c.1': "Where are Lucy and Sarah? → They are at the campsite.; What are they doing? → They are playing tug of war.; Where's Lucas, Mai? → He's at school.; "
        "What's she doing? → She is studing English.; Is she taking a photo? → Yes, she is.",
 'd.1': 'Đáp án: Are',
 'd.2': 'Đáp án: they',
 'd.3': 'Đáp án: are',
 'd.4': 'Đáp án: playing',
 'd.5': 'Đáp án: doing',
 'e.1': 'Đáp án: False (Sai)',
 'e.2': 'Đáp án: True (Đúng)',
 'e.3': 'Đáp án: True (Đúng)',
 'e.4': 'Đáp án: False (Sai)',
 'e.5': 'Đáp án: False (Sai)',
 'e.6': 'Đáp án: True (Đúng)',
 'f.1': 'Câu đúng: Where are Bill and his friends?',
 'f.10': 'Câu đúng: They are building a campfire.',
 'f.2': 'Câu đúng: What are Nam and Minh doing, Lan?',
 'f.3': 'Câu đúng: They are putting up a tent.',
 'f.4': 'Câu đúng: What is Mark doing, Mai?',
 'f.5': 'Câu đúng: He is flying a kite.',
 'f.6': 'Câu đúng: Son is watching TV.',
 'f.7': 'Câu đúng: Nam and his friends are playing tug of war.',
 'f.8': 'Câu đúng: Are Mai and Lan singing songs?',
 'f.9': 'Câu đúng: What are the boys doing?'}
