# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['The pet shop is opposite the bookshop.'],
 't1.10': 'it',
 't1.11': ['How much are these pants?'],
 't1.12': "It's near the bookshop.",
 't1.13': 'is',
 't1.14': 'those',
 't1.15': ['They are two hundred and forty thousand dong.'],
 't1.16': 'Tiệm bánh mì ở giữa hiệu sách và cửa hàng thú cứng.',
 't1.17': 'opposite',
 't1.18': ['How much is that shirt?'],
 't1.19': 'Trung tâm thể thao đối diện trung tâm mua sắm.',
 't1.2': "It's ninety thousand dong.",
 't1.20': 'are',
 't1.3': 'these',
 't1.4': 'Go straight and turn left at the corner.',
 't1.5': 'between',
 't1.6': ['The bakery is opposite the museum.'],
 't1.7': 'How much is the T-shirt?',
 't1.8': 'between',
 't1.9': "Great! Let's go."}

EXPLANATIONS = {'t1.1': 'Câu đúng: The pet shop is opposite the bookshop.',
 't1.10': 'Đáp án: it',
 't1.11': 'Câu đúng: How much are these pants?',
 't1.12': "Đáp án: It's near the bookshop.",
 't1.13': 'Đáp án: is',
 't1.14': 'Đáp án: those',
 't1.15': 'Câu đúng: They are two hundred and forty thousand dong.',
 't1.16': 'Đáp án: Tiệm bánh mì ở giữa hiệu sách và cửa hàng thú cứng.',
 't1.17': 'Đáp án: opposite',
 't1.18': 'Câu đúng: How much is that shirt?',
 't1.19': 'Đáp án: Trung tâm thể thao đối diện trung tâm mua sắm.',
 't1.2': "Đáp án: It's ninety thousand dong.",
 't1.20': 'Đáp án: are',
 't1.3': 'Đáp án: these',
 't1.4': 'Đáp án: Go straight and turn left at the corner.',
 't1.5': 'Đáp án: between',
 't1.6': 'Câu đúng: The bakery is opposite the museum.',
 't1.7': 'Đáp án: How much is the T-shirt?',
 't1.8': 'Đáp án: between',
 't1.9': "Đáp án: Great! Let's go."}
