# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['My mother goes to the shopping centre.'],
 't1.10': 'She does yoga on Sundays.',
 't1.11': ['Where do you go on Sundays?'],
 't1.12': 'Where does she go on Sundays?',
 't1.13': 'goes',
 't1.14': 'He plays tennis on Sundays.',
 't1.15': ['I go to the sports centre on Sundays.'],
 't1.16': 'She goes to the cinema on Sundays.',
 't1.17': 'does',
 't1.18': 'She cooks meals on Saturdays.',
 't1.19': ['What do you do on Sundays?'],
 't1.2': 'What does she do on Sunday mornings?',
 't1.20': 'What does she do on Sundays?',
 't1.3': 'do',
 't1.4': ['What does she do on Saturdays?'],
 't1.5': 'What do you do on Saturday evenings?',
 't1.6': 'plays',
 't1.7': ['She goes to the cinema on Saturdays.'],
 't1.8': 'Where do you go?',
 't1.9': 'does'}

EXPLANATIONS = {'t1.1': 'Câu đúng: My mother goes to the shopping centre.',
 't1.10': 'Đáp án: She does yoga on Sundays.',
 't1.11': 'Câu đúng: Where do you go on Sundays?',
 't1.12': 'Đáp án: Where does she go on Sundays?',
 't1.13': 'Đáp án: goes',
 't1.14': 'Đáp án: He plays tennis on Sundays.',
 't1.15': 'Câu đúng: I go to the sports centre on Sundays.',
 't1.16': 'Đáp án: She goes to the cinema on Sundays.',
 't1.17': 'Đáp án: does',
 't1.18': 'Đáp án: She cooks meals on Saturdays.',
 't1.19': 'Câu đúng: What do you do on Sundays?',
 't1.2': 'Đáp án: What does she do on Sunday mornings?',
 't1.20': 'Đáp án: What does she do on Sundays?',
 't1.3': 'Đáp án: do',
 't1.4': 'Câu đúng: What does she do on Saturdays?',
 't1.5': 'Đáp án: What do you do on Saturday evenings?',
 't1.6': 'Đáp án: plays',
 't1.7': 'Câu đúng: She goes to the cinema on Saturdays.',
 't1.8': 'Đáp án: Where do you go?',
 't1.9': 'Đáp án: does'}
