# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u1-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['England.', 'is', 'from', 'Peter']},
                                  {'id': 't1.2',
                                   'o': ['Bạn đến từ Singapore.', 'Cô ấy đến từ Singapore.', 'Anh ấy đến từ Singapore.', 'Tôi đến từ Singapore.'],
                                   'plain': True,
                                   'q': 'Câu “He\'s from Singapore." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'o': ['is', 'am', 'are', 'do'], 'plain': True, 'q': 'Where __________ Helena from?', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ["They're from Australia.", "I'm fine, thank you.", "He's from Vietnam.", "She's from America.", "It's my new friend."],
                                   'plain': True,
                                   'q': 'Where are Ben and Bill from?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['too', 'friend', 'Bill', 'from', 'Australia'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Bill: It's my _____, Lucy. She's from England.",
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['she', 'is', 'from?', 'Where']},
                                  {'id': 't1.7',
                                   'o': ['Bạn đến từ đâu?', 'Cô ấy đến từ đâu?', 'Anh ấy đến từ đầu?', 'Họ đến từ đâu?'],
                                   'plain': True,
                                   'q': 'Câu “Where\'s he from?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['are', 'is', 'am', 'does'], 'plain': True, 'q': 'Where __________ they from?', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ["They're from Australia.", "I'm fine, thank you.", "He's from Vietnam.", "She's from America.", "It's my new friend."],
                                   'plain': True,
                                   'q': "Where's Minh from?",
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['too', 'friend', 'Bill', 'from', 'Australia'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Lucy: Nice to see you, _____.',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'America.', 'from', 'Lisa']},
                                  {'id': 't1.12',
                                   'o': ["I'm from Japan.", "He's from Japan.", "They're from Japan.", "She's from Japan."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi “Where\'s he from?"',
                                   't': 'mcq'},
                                  {'id': 't1.13', 'o': ['are', 'is', 'am', 'does'], 'plain': True, 'q': 'She __________ from Spain.', 't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['friend,', 'my', 'Mary.', 'This', 'is']},
                                  {'id': 't1.15',
                                   'o': ["Where's she from?", "Where's he from?", 'Where are you from?', 'Where are they from?'],
                                   'plain': True,
                                   'q': 'Câu "I\'m from Australia" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.16', 'o': ['are', 'is', 'am', 'does'], 'plain': True, 'q': 'I __________ from Japan.', 't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['from?', 'is', 'he', 'Where']},
                                  {'id': 't1.18',
                                   'o': ["I'm fine, thank you.", "I'm from Australia.", "It's my new friend.", "She's from Japan."],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi “Who's that”?",
                                   't': 'mcq'},
                                  {'id': 't1.19', 'o': ['is', 'am', 'do', 'are'], 'plain': True, 'q': 'They __________ from the USA.', 't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'Thailand.', 'Malee', 'from']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 1 – My friends: Kiểm tra 2',
 'unit': 1}
