# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['What time does she have breakfast?'],
 't1.10': 'Where',
 't1.11': ['What does Lan do on Sundays?'],
 't1.12': 'She does housework on Saturdays.',
 't1.13': "It's in November.",
 't1.14': ['What does Mary do on Sundays?'],
 't1.15': "It's in May.",
 't1.16': 'on',
 't1.17': ['What are you doing, Ben?'],
 't1.18': 'She wants some milk.',
 't1.19': 'afternoon',
 't1.2': "I have breakfast at seven o'clock.",
 't1.20': ["When's your brother's birthday?"],
 't1.3': 'I do housework.',
 't1.4': 'I want some water.',
 't1.5': 'English',
 't1.6': ["They have lunch at eleven o'clock at school."],
 't1.7': 'What day is it today?',
 't1.8': 'She wants some chips.',
 't1.9': "No, I can't."}

EXPLANATIONS = {'t1.1': 'Câu đúng: What time does she have breakfast?',
 't1.10': 'Đáp án: Where',
 't1.11': 'Câu đúng: What does Lan do on Sundays?',
 't1.12': 'Đáp án: She does housework on Saturdays.',
 't1.13': "Đáp án: It's in November.",
 't1.14': 'Câu đúng: What does Mary do on Sundays?',
 't1.15': "Đáp án: It's in May.",
 't1.16': 'Đáp án: on',
 't1.17': 'Câu đúng: What are you doing, Ben?',
 't1.18': 'Đáp án: She wants some milk.',
 't1.19': 'Đáp án: afternoon',
 't1.2': "Đáp án: I have breakfast at seven o'clock.",
 't1.20': "Câu đúng: When's your brother's birthday?",
 't1.3': 'Đáp án: I do housework.',
 't1.4': 'Đáp án: I want some water.',
 't1.5': 'Đáp án: English',
 't1.6': "Câu đúng: They have lunch at eleven o'clock at school.",
 't1.7': 'Đáp án: What day is it today?',
 't1.8': 'Đáp án: She wants some chips.',
 't1.9': "Đáp án: No, I can't."}
