# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r2-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['music', 'you', 'have', 'Do', 'on', 'Fridays?']},
                                  {'id': 't1.2',
                                   'o': ['Khi nào bạn có môn Khoa học?',
                                         'Hôm nay bạn có môn Mỹ thuật không?',
                                         'Hôm nay bạn có môn học gì?',
                                         'Hôm nay bạn có môn Tiếng Việt không?'],
                                   'plain': True,
                                   'q': 'Câu "Do you have Art today?" có nghĩa là?',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'o': ['am not', "don't", 'are', "aren't"], 'plain': True, 'q': 'A: Do you have Art today?', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['I have it on Wednesday.', 'Yes, it is.', 'There is a garden at his school.', "It's Art.", 'I was at the zoo.'],
                                   'plain': True,
                                   'q': 'Where were you last Sunday?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['Music', 'Science', 'Art', 'Maths'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: I don't have _____ today.",
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['have', 'do', 'you', 'Music?', 'When']},
                                  {'id': 't1.7',
                                   'o': ['Có phải hôm nay bạn có môn Tiếng Việt không?',
                                         'Khi nào bạn có môn Âm nhạc?',
                                         'Hôm nay bạn có những môn gì?',
                                         'Khi nào bạn có môn Tiếng Việt?'],
                                   'plain': True,
                                   'q': 'Câu “When do you have music?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['Where', 'Why', 'What', 'How'], 'plain': True, 'q': 'A: ____________ do you like Art?', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['I have it on Wednesday.', 'Yes, it is.', 'There is a garden at his school.', "It's Art.", 'I was at the zoo.'],
                                   'plain': True,
                                   'q': "What's your favourite subject?",
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['Why', 'What', 'Where', 'When'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ do you have it?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['does', 'today?', 'she', 'subjects', 'have', 'What']},
                                  {'id': 't1.12',
                                   'o': ['What subjects do you have today?',
                                         'Is your sports day in September?',
                                         'Why do you like it?',
                                         "When's your sports day?"],
                                   'plain': True,
                                   'q': "Câu “It's in May.” trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 't1.13', 'o': ['has', 'have', 'sing', 'play'], 'plain': True, 'q': 'A: What subjects do you have today?', 't': 'mcq'},
                                  {'id': 't1.14',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['and', 'have', 'Mondays.', 'on', 'Maths', 'English', 'I', 'Art,']},
                                  {'id': 't1.15',
                                   'o': ['Tôi thích môn Tiếng Anh.',
                                         'Môn học yêu thích của cô ấy là môn Toán.',
                                         'Môn học yêu thích của anh ấy là môn Âm nhạc.',
                                         'Môn học yêu thích của tôi là môn Tiếng Việt.'],
                                   'plain': True,
                                   'q': 'Câu “Her favorite subject is Maths” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['Is', 'Are', 'Do', 'Does'],
                                   'plain': True,
                                   'q': '____________ your sports day in November?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'sports', 'your', 'day', 'Is', 'May?']},
                                  {'id': 't1.18',
                                   'o': ['How many building are there at your school?',
                                         'What subjects do you have today?',
                                         'Why do you like English?',
                                         'Why do you like Maths?'],
                                   'plain': True,
                                   'q': 'Câu “Because I want to be an English teacher” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['Monday', 'July', 'Friday', 'Wednesday'],
                                   'plain': True,
                                   'q': 'Is your sports day in ____________?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['December.', 'is', 'in', 'sports', 'The', 'day']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Review 2: Kiểm tra 2',
 'unit': 'Review2'}
