# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'How many gardens are there at your school?',
 'a.10': 'Thứ Bảy tuần vừa rồi bạn đã ở đâu?',
 'a.2': 'Có một khu vườn ở trường của tôi.',
 'a.3': 'What subjects do you have today?',
 'a.4': 'Hôm nay bạn có môn Mỹ thuật không?',
 'a.5': 'Khi nào bạn có môn Âm nhạc?',
 'a.6': "When's your sports day?",
 'a.7': 'Môn học yêu thích của cô ấy là môn Toán.',
 'a.8': 'Why do you like English?',
 'a.9': "No, I wasn't. I was in Sydney.",
 'b.1': 'gardens',
 'b.10': 'in',
 'b.2': 'How many',
 'b.3': 'do',
 'b.4': "don't",
 'b.5': 'Why',
 'b.6': 'have',
 'b.7': 'Is',
 'b.8': 'July',
 'b.9': 'Where',
 'c.1': {'blanks': [['There is a garden at his school.'], ['I have it on Wednesday.'], ['Yes, it is.'], ['I was at the zoo.'], ["It's Art."]]},
 'd.1': 'Saturday',
 'd.2': 'subjects',
 'd.3': 'have',
 'd.4': 'Art',
 'd.5': 'When',
 'e.1': 'Nguyen Du Primary School',
 'e.2': 'in the town',
 'e.3': 'two buildings and a playground',
 'e.4': 'garden',
 'e.5': 'the playground',
 'f.1': ['How many buildings are there at your school?'],
 'f.10': ['I painted a picture of my hometown.'],
 'f.2': ['There are two buildings at our school.'],
 'f.3': ['Do you have music on Fridays?'],
 'f.4': ['When do you have Music?'],
 'f.5': ['What subjects does she have today?'],
 'f.6': ['I have Art, English and Maths on Mondays.'],
 'f.7': ['Is your sports day in May?'],
 'f.8': ['The sports day is in December.'],
 'f.9': ['I was in Bangkok last summer.']}

EXPLANATIONS = {'a.1': 'Đáp án: How many gardens are there at your school?',
 'a.10': 'Đáp án: Thứ Bảy tuần vừa rồi bạn đã ở đâu?',
 'a.2': 'Đáp án: Có một khu vườn ở trường của tôi.',
 'a.3': 'Đáp án: What subjects do you have today?',
 'a.4': 'Đáp án: Hôm nay bạn có môn Mỹ thuật không?',
 'a.5': 'Đáp án: Khi nào bạn có môn Âm nhạc?',
 'a.6': "Đáp án: When's your sports day?",
 'a.7': 'Đáp án: Môn học yêu thích của cô ấy là môn Toán.',
 'a.8': 'Đáp án: Why do you like English?',
 'a.9': "Đáp án: No, I wasn't. I was in Sydney.",
 'b.1': 'Đáp án: gardens',
 'b.10': 'Đáp án: in',
 'b.2': 'Đáp án: How many',
 'b.3': 'Đáp án: do',
 'b.4': "Đáp án: don't",
 'b.5': 'Đáp án: Why',
 'b.6': 'Đáp án: have',
 'b.7': 'Đáp án: Is',
 'b.8': 'Đáp án: July',
 'b.9': 'Đáp án: Where',
 'c.1': 'How many gardens are there at his school? → There is a garden at his school.; When do you have English? → I have it on Wednesday.; Is your sports day '
        "in May? → Yes, it is.; Where were you last Sunday? → I was at the zoo.; What's your favourite subject? → It's Art.",
 'd.1': 'Đáp án: Saturday',
 'd.2': 'Đáp án: subjects',
 'd.3': 'Đáp án: have',
 'd.4': 'Đáp án: Art',
 'd.5': 'Đáp án: When',
 'e.1': 'Đáp án: Nguyen Du Primary School',
 'e.2': 'Đáp án: in the town',
 'e.3': 'Đáp án: two buildings and a playground',
 'e.4': 'Đáp án: garden',
 'e.5': 'Đáp án: the playground',
 'f.1': 'Câu đúng: How many buildings are there at your school?',
 'f.10': 'Câu đúng: I painted a picture of my hometown.',
 'f.2': 'Câu đúng: There are two buildings at our school.',
 'f.3': 'Câu đúng: Do you have music on Fridays?',
 'f.4': 'Câu đúng: When do you have Music?',
 'f.5': 'Câu đúng: What subjects does she have today?',
 'f.6': 'Câu đúng: I have Art, English and Maths on Mondays.',
 'f.7': 'Câu đúng: Is your sports day in May?',
 'f.8': 'Câu đúng: The sports day is in December.',
 'f.9': 'Câu đúng: I was in Bangkok last summer.'}
