# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u17-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['How can I get to the cinema?',
                                         'What does it say?',
                                         'Do you want to go to the cinema with me?',
                                         "What's the weather like today?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Biển báo nói gì?”:',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['How can I get to the bookshop?',
                                         'What does it say?',
                                         'What do you want to buy at the shopping centre?',
                                         'Is there a bakery near here?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi cách để đến nơi nào đó?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Go straight and turn left.',
                                         'There is a cinema in Hong Bang Street',
                                         'Thank you very much for your help.',
                                         'The bookshop is on the right.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: How can I get there?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['Go straight.', 'Turn right.', 'Turn left.', 'Turn round.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói: “Rẽ trái.”',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['Is there a bookshop near here?',
                                         'How can I get to the bookshop?',
                                         'What do you want to buy at the bookshop?',
                                         'Do you want to go to the bookshop with me?'],
                                   'plain': True,
                                   'q': 'Câu: “Go straight" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['Có một hiệu sách trên đường Nguyễn Thái Sơn.',
                                         'Có một sạp bán thực phẩm trên đường Nguyễn Thái Sơn.',
                                         'Có một hiệu bánh mì trên đường Nguyễn Thái Sơn.',
                                         'Có một rạp chiếu phim trên đường Nguyễn Thái Sơn.'],
                                   'plain': True,
                                   'q': 'Câu: “There’s a food stall in Nguyen Thai Son Street.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['What does it say?',
                                         'How can she get to the shopping centre?',
                                         'Is there a cinema near here?',
                                         'What do you want to buy at the shopping centre?'],
                                   'plain': True,
                                   'q': 'Câu: "Go straight and turn right." trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['Is there a bookshop near here?',
                                         'What do you want to buy at the food stall?',
                                         'How can he get to the bookshop?',
                                         'What does he want to buy at the bookshop?'],
                                   'plain': True,
                                   'q': 'Câu "He wants to buy some books” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['Rẽ phải.', 'Rẽ trái.', 'Quay vòng lại.', 'Đi thẳng.'],
                                   'plain': True,
                                   'q': 'Câu: “Turn round" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Có một trung tâm mua sắm ở đường Nguyễn Trãi.',
                                         'Có một tiệm bánh mì ở đường Nguyễn Trãi.',
                                         'Có một trung tâm mua sắm ở đường Nguyễn Trãi.',
                                         'Có một trung tâm thể thao ở đường Nguyễn Trãi.'],
                                   'plain': True,
                                   'q': 'Câu: “There is a sports centre in Nguyen Trai Street" có nghĩa là:',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1',
                                   'o': ['cinema', 'bakery', 'food stall', 'bookshop'],
                                   'plain': True,
                                   'q': 'I want to buy some books. Is there a __________ near here?',
                                   't': 'mcq'},
                                  {'id': 'b.2',
                                   'o': ['What', 'How', 'Where', 'When'],
                                   'plain': True,
                                   'q': 'A: _____________ can I get to the cinema?',
                                   't': 'mcq'},
                                  {'id': 'b.3', 'o': ['it', 'that', 'there', 'this'], 'plain': True, 'q': 'Is _____________ a bakery near here?', 't': 'mcq'},
                                  {'id': 'b.4',
                                   'o': ['sports centre', 'shopping centre', 'bookshop', 'cinema'],
                                   'plain': True,
                                   'q': 'I want to see a movie. How can I get to the _____________.',
                                   't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['stop', 'go', 'run', 'go straight'],
                                   'plain': True,
                                   'q': 'We _____________ when the light is red.',
                                   't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['yellow', 'green', 'red', 'off'],
                                   'plain': True,
                                   'q': 'We go when the light is _______________.',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['food stall', 'bookshop', 'sports centre', 'campsite'],
                                   'plain': True,
                                   'q': 'I want to buy some meat. How can I get to the ______________?',
                                   't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['sports centre', 'shopping centre', 'cinema', 'bakery'],
                                   'plain': True,
                                   'q': 'A: How can I get to the ____________?',
                                   't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['bakery', 'bookshop', 'food stall', 'campsite'],
                                   'plain': True,
                                   'q': 'A: What do you want to buy at the ________________?',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['Go', 'Turn', 'Be', 'Is'],
                                   'plain': True,
                                   'q': 'A: How can I get to the Ben Thanh Market?',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['Where are you now?',
                                            'How can I get to the campsite?',
                                            'What does it say?',
                                            'What do you want to buy at the shopping centre?',
                                            'Do you want to go to the swimming pool with me?'],
                                   'o': ['I want to buy some clothes.',
                                         "I'm at the shopping centre.",
                                         "Great! Let's go.",
                                         'It says "stop".',
                                         'Go straight and turn right.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': '1. A: Excuse me. How can I get to the sports centre?<br>B: <b>(1)&nbsp;______</b> left at the food stall.<br>2. A: Is '
                                   'there a bakery near here?<br>B: There is a <b>(2)&nbsp;______</b> in Pham Hung Street.<br>3. A: <b>(3)&nbsp;______</b> can '
                                   'I get there?<br>B: Go straight and turn right at the traffic lights.<br>4. A: Do you want to go to the '
                                   "<b>(4)&nbsp;______</b> with me?<br>B: Great! Let's go. I also want to buy some books.<br>5. A: How can I "
                                   '<b>(5)&nbsp;______</b>to the campsite?<br>B: Go straight and turn left at the bookshop.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': "It's Sunday today", 't': 'tf'},
                                  {'id': 'e.2', 'q': 'Nam and Minh want to buy some things.', 't': 'tf'},
                                  {'id': 'e.3', 'q': 'The shopping centre is in Phan Van Tri Street.', 't': 'tf'},
                                  {'id': 'e.4', 'q': 'Nam and Minh go straight and turn left to right to the shopping centre.', 't': 'tf'},
                                  {'id': 'e.5', 'q': 'The shopping centre is on the left.', 't': 'tf'}],
                        'passage': "Nam and Minh usually go out together on Sundays. It's Sunday today. They want to buy some things. The shopping centre is "
                                   'in Phan Van Tri Street. How can they get there? They go straight and turn left at the cinema. The shopping centre is on '
                                   'the left.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'get', 'How', 'can', 'centre?', 'I', 'to', 'sports']},
                                  {'id': 'f.2',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'left', 'turn', 'at', 'Go', 'and', 'straight', 'cinema.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['water', 'park', 'near', 'a', 'here?', 'Is', 'there']},
                                  {'id': 'f.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Van', 'There', 'Pham', 'in', 'is', 'stall', 'a', 'Dong', 'food', 'Street.']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['say?', 'does', 'What', 'it']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['want', 'to', 'the', 'bookshop.', 'to', 'go', 'We']},
                                  {'id': 'f.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['in', 'Son', 'Nguyen', 'Thai', 'Street.', 'is', 'a', 'bakery', 'There']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'How', 'we', 'get', 'campsite?', 'to', 'can']},
                                  {'id': 'f.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Go', 'on', 'and', 'you', 'see', 'left.', 'the', 'the', 'campsite', 'will', 'straight']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['very', 'you', 'much', 'for', 'your', 'Thank', 'help.']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi ý nghĩa của một biển báo và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           'lời</td></tr><tr><td>What does it say?<br>Biển báo nói gì?</td><td>It says ‘…’<br>Nó nói...</td></tr><tr><td>Ví dụ:<br>A: What does it say? Biển '
           'báo nói gì?<br>B: It says “Turn left”. Nó nói “Rẽ trái”.</td></tr></table><p>2. Cách hỏi và chỉ đường:</p><table class="tb"><tr><td>Cách '
           'hỏi</td><td>Cách trả lời</td></tr><tr><td>How can I get to the...?<br>Làm thế nào để tôi có thể đến...?</td><td>… (Go straight/Turn left/Turn '
           'right/...) ¦... (Đi thẳng/Rẽ trái/Rẽ phải...)</td></tr><tr><td>Ví dụ:<br>A: How can I get to the zoo?<br>Làm thế nào để tôi có thể đến được sở '
           'thú?<br>B: Go straight this street and turn left at the bakery.<br>Hãy đi thẳng đường này và rẽ trái tại tiệm bánh mì.</td></tr></table>',
 'title': 'Unit 17 – In the city: Luyện tập',
 'unit': 17}
