# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'gi.1': 'd',
 'gi.2': 'a',
 'gi.3': 'c',
 'gi.4': 'b',
 'gii.5': {'blanks': [['b'], ['d'], ['a'], ['c']]},
 'giii.6': ['ride a horse'],
 'giii.7': ['playgrounds'],
 'giii.8': ['science'],
 'giii.9': ['countryside'],
 'giv.10': 'C',
 'giv.11': 'B',
 'giv.12': 'A',
 'giv.13': 'A',
 'gv.14': 'T',
 'gv.15': 'F',
 'gv.16': 'F',
 'gvi.17': ['Where were you last summer?'],
 'gvi.18': ['When do you have maths?'],
 'gvi.19': ['What do you want to eat?'],
 'gvii.20': ['play football'],
 'gvii.21': ['park'],
 'gvii.22': ['roller skate'],
 'gvii.23': ['lemonade'],
 'gviii.24': ['There are three buildings (in my school).', 'There are three buildings.', 'There are three buildings in my school.'],
 'gviii.25': ['I was at the beach.'],
 'gviii.26': ['It’s in October.'],
 'gviii.27': ['I have it on Mondays.']}

EXPLANATIONS = {'gi.1': 'Câu 1 ứng với tranh d (theo đáp án của đề).',
 'gi.2': 'Câu 2 ứng với tranh a (theo đáp án của đề).',
 'gi.3': 'Câu 3 ứng với tranh c (theo đáp án của đề).',
 'gi.4': 'Câu 4 ứng với tranh b (theo đáp án của đề).',
 'gii.5': 'Đáp án theo đáp án của đề: 1–b, 2–d, 3–a, 4–c',
 'giii.6': 'Đáp án: ride a horse',
 'giii.7': 'Đáp án: playgrounds',
 'giii.8': 'Đáp án: science',
 'giii.9': 'Đáp án: countryside',
 'giv.10': 'Đáp án: C. I ride a bike.',
 'giv.11': 'Đáp án: B. It’s in the village.',
 'giv.12': 'Đáp án: A. I have English.',
 'giv.13': 'Đáp án: A. No, it isn’t.',
 'gv.14': 'Đáp án: True (theo đáp án của đề).',
 'gv.15': 'Đáp án: False (theo đáp án của đề).',
 'gv.16': 'Đáp án: False (theo đáp án của đề).',
 'gvi.17': 'Câu hỏi đúng: Where were you last summer?',
 'gvi.18': 'Câu hỏi đúng: When do you have maths?',
 'gvi.19': 'Câu hỏi đúng: What do you want to eat?',
 'gvii.20': 'Đáp án: play football',
 'gvii.21': 'Đáp án: park',
 'gvii.22': 'Đáp án: roller skate',
 'gvii.23': 'Đáp án: lemonade',
 'gviii.24': 'Câu trả lời đúng: There are three buildings (in my school).',
 'gviii.25': 'Câu trả lời đúng: I was at the beach.',
 'gviii.26': 'Câu trả lời đúng: It’s in October.',
 'gviii.27': 'Câu trả lời đúng: I have it on Mondays.'}
