# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u8-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What subjects do you have today?',
                                         'When do you have English?',
                                         "What's your favourite subject?",
                                         'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi môn học yêu thích của ai đó là gì?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ["Why's", "What's", "How's", "Where's"],
                                   'plain': True,
                                   'q': '__________ your favourite subject?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["It's music.", "It's Thursday.", 'Because I want to be a maths teacher.', 'I have it on Friday.', 'Yes, I do.'],
                                   'plain': True,
                                   'q': 'What day is it today?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Thursday', 'English', 'Vietnamese', 'science'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____.",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'subject?', 'favourite', "What's"]},
                                  {'id': 't1.6',
                                   'o': ['Tôi thích môn tiếng Anh.',
                                         'Môn học yêu thích của tôi là môn Tiếng Anh.',
                                         'Môn học yêu thích của tôi là môn Toán.',
                                         'Môn học yêu thích của tôi là môn Tiếng Việt.'],
                                   'plain': True,
                                   'q': 'Câu “My favorite subject is English” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['English', 'Music', 'Science', 'Art'],
                                   'plain': True,
                                   'q': 'I like drawing. My favourite subject is __________.',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ["It's music.", "It's Thursday.", 'Because I want to be a maths teacher.', 'I have it on Friday.', 'Yes, I do.'],
                                   'plain': True,
                                   'q': 'Do you have English today?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['Are', 'Is', 'Do', 'Does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ you have music today?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Music.', 'is', 'My', 'subject', 'favourite']},
                                  {'id': 't1.11',
                                   'o': ['Because I want to be a teacher.',
                                         'I have English on Mondays and Fridays.',
                                         'I have English, Vietnamese and Maths.',
                                         "It's music."],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “What's your favourite subject?”",
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['book', 'day', 'subject', 'school'],
                                   'plain': True,
                                   'q': "A: What's your favourite __________?",
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ["It's music.", "It's Thursday.", 'Because I want to be a maths teacher.', 'I have it on Friday.', 'Yes, I do.'],
                                   'plain': True,
                                   'q': "What's your favourite subject?",
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['Why', 'How', 'What', 'Where'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's music. _____ about you?",
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Art?', 'you', 'Why', 'like', 'do']},
                                  {'id': 't1.16',
                                   'o': ['What day is it today?',
                                         'Why do you like Music?',
                                         'How many playgrounds are there at your school?',
                                         'When do you have English?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi lý do ai đó thích môn gì?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['PE', 'IT', 'Science', 'Art'],
                                   'plain': True,
                                   'q': 'I like running. My favourite subject is __________.',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ["It's music.", "It's Thursday.", 'Because I want to be a maths teacher.', 'I have it on Friday.', 'Yes, I do.'],
                                   'plain': True,
                                   'q': 'When do you have Science?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['PE', 'IT', 'English', 'Art'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: My favourite subject is _____.',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['to', 'painter.', 'become', 'a', 'I', 'Because', 'want']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 8 – My favourite subjects: Kiểm tra 1',
 'unit': 8}
