# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de6',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and match (nghe và nối từng câu số 1–4 với tranh; tranh B là ví dụ).',
                        'items': [{'id': 'l1.1',
                                   'left': [{'t': 'Câu 1'}, {'t': 'Câu 2'}, {'t': 'Câu 3'}, {'t': 'Câu 4'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de6/m1.png" alt="Tranh A–E">'},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and tick Right (✓ = True) or Wrong (✗ = False) (nghe, câu đúng chọn True, sai chọn False).',
                        'items': [{'id': 'l2.2', 'q': 'I live in a small house in a village.', 't': 'tf'},
                                  {'id': 'l2.3', 'q': 'She doesn’t have long hair and big eyes.', 't': 'tf'},
                                  {'id': 'l2.4', 'q': 'They are crocodiles.', 't': 'tf'},
                                  {'id': 'l2.5', 'q': 'The gift shop is between the bakery and the bookshop.', 't': 'tf'}]},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen and complete (nghe và điền từ vào chỗ trống).',
                        'items': [{'id': 'l3.6', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'l3.7', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'l3.8', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'l3.9', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>My name is Lisa. I am tall and (0) <b>slim</b>. This is my father, Tony. He works in a <b>(1) ______</b>. This is my '
                                   'mother, Daisy. She has a <b>(2) ______</b>. She works in a school as a Maths teacher. My mother often goes to the <b>(3) '
                                   '______</b> on Mondays. Today, my parents will take me to the campsite in the mountain. My class is playing <b>(4) '
                                   '______</b> at the campsite. I am very happy.</p>'},
                       {'id': 'r1',
                        'instr': 'Question 4. Circle the odd one out (chọn từ khác loại).',
                        'items': [{'id': 'r1.10', 'o': ['big', 'tall', 'eyes', 'slim'], 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 'r1.11', 'o': ['rainy', 'sunny', 'weather', 'cloudy'], 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 'r1.12', 'o': ['bakery', 'T-shirt', 'bookshop', 'supermarket'], 'q': 'Chọn từ khác loại:', 't': 'mcq'},
                                  {'id': 'r1.13', 'o': ['crocodiles', 'giraffes', 'lions', 'dance'], 'q': 'Chọn từ khác loại:', 't': 'mcq'}]},
                       {'bank': ['straight', 'left', 'library', 'books'],
                        'id': 'r2',
                        'instr': 'Question 5. Fill in each blank with one given word (chọn từ trong khung điền vào chỗ trống).',
                        'items': [{'id': 'r2.14', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'q': 'Chỗ trống (3): {_}', 't': 'fill'}],
                        'passage': '<p>Today is Sunday. It is sunny and warm. Thuy Duong likes reading (0) <b>books</b>. She wants to go to the <b>(1) '
                                   '______</b>. It is in Chu Van An Street. How can she get there? She can go <b>(2) ______</b> and turn right. The library is '
                                   'on the <b>(3) ______</b>.</p><img src="../../../../assets/lop4_on2_de6/p5.png" alt="Hình" '
                                   'style="max-width:220px;height:auto">'},
                       {'id': 'r3',
                        'instr': 'Question 6. Read and choose A, B or C (đọc và chọn đáp án đúng).',
                        'items': [{'id': 'r3.17',
                                   'o': ['Yes, it is.', 'No, it isn’t.', 'No information is given.'],
                                   'q': 'Is swimming Thang’s hobby?',
                                   't': 'mcq'},
                                  {'id': 'r3.18',
                                   'o': ['She is in the water park with her family.',
                                         'She is in the bakery.',
                                         'She is in the shopping centre with her mother.'],
                                   'q': 'Where is Dao?',
                                   't': 'mcq'},
                                  {'id': 'r3.19',
                                   'o': ['Because she wants some cakes.', 'Because her mother wants to buy clothes.', 'Because they want to go to the bakery.'],
                                   'q': 'Why do Dao and her mother go to the shopping centre?',
                                   't': 'mcq'}],
                        'passage': '<p><b>Thang:</b> Hello, I am Thang. Today is Saturday. It is sunny and hot. Because I like swimming, my family goes to the '
                                   'water park. I can swim and play there.</p><img src="../../../../assets/lop4_on2_de6/p6a.png" alt="Hình" '
                                   'style="max-width:220px;height:auto"><p><b>Dao:</b> Hi there! I’m Dao. It is windy outside. My mother and I go to the '
                                   'shopping centre because my mother wants to buy clothes for winter. There is a bakery in the shopping centre. We can go '
                                   'there to have some cakes as well.</p><img src="../../../../assets/lop4_on2_de6/p6b.png" alt="Hình" '
                                   'style="max-width:160px;height:auto">'},
                       {'id': 'w1',
                        'instr': 'Question 7. Fill in the blanks (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'w1.20', 'img': 'w1_1.png', 'q': 'Where’s the gift shop?<br>It is {_} the bookshop and the food stall.', 't': 'fill'},
                                  {'id': 'w1.21', 'img': 'w1_2.png', 'q': 'What are they doing?<br>They are {_}.', 't': 'fill'},
                                  {'id': 'w1.22', 'img': 'w1_3.png', 'q': 'How much is this skirt?<br>It is {_}.', 't': 'fill'},
                                  {'id': 'w1.23', 'img': 'w1_4.png', 'q': 'Why do you like peacocks?<br>Because they {_}.', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Question 8. Use the given words to make sentences (dùng từ gợi ý viết thành câu hoàn chỉnh).',
                        'items': [{'id': 'w2.24', 'q': 'What/ you/ do/ morning?<br>→ {_}', 't': 'fill'},
                                  {'id': 'w2.25', 'q': 'I/ live/ 12 Tran Hung Dao Street<br>→ {_}', 't': 'fill'},
                                  {'id': 'w2.26', 'q': 'Do/ you/ want/ go/ supermarket?<br>→ {_}', 't': 'fill'}]},
                       {'id': 'w3',
                        'instr': 'Question 9. Answer the questions with the given words (dùng từ gợi ý để trả lời).',
                        'items': [{'id': 'w3.27', 'q': 'When do you wash the clothes? (afternoon)<br>→ {_}', 't': 'fill'},
                                  {'id': 'w3.28', 'q': 'What does your father do on Saturdays? (play tennis)<br>→ {_}', 't': 'fill'},
                                  {'id': 'w3.29', 'q': 'What are Huong and Son doing? (build/ campfire)<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 6',
 'unit': 'OnHK2'}
