# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u2-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ["What's your name?", 'Where are you from?', 'What time is it?', 'How old are you?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi giờ?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ["Let's a break.", "It's three fifteen.", "I get up at six o'clock.", 'I go to school at 1:15 pm.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What time is it?"',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['What time do you get up?', "Who's that?", 'What time is it?', 'What time do you have breakfast?'],
                                   'plain': True,
                                   'q': 'Câu “It\'s one fifteen." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['How old are you?', 'What time is it?', 'What time do you get up?', 'Where is she from?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về thói quen hằng ngày?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['Tôi đi ngủ lúc sáu giờ mười lăm phút.',
                                         'Tôi thức dậy lúc sáu giờ.',
                                         'Tôi thức dậy lúc sáu giờ mười lăm phút.',
                                         'Tôi đi học lúc sáu giờ mười lăm phút.'],
                                   'plain': True,
                                   'q': 'Câu: "I get up at six fifteen.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['What time is it?',
                                         'What time does she get up?',
                                         'What time does she have breakfast?',
                                         'What time do you have breakfast?'],
                                   'plain': True,
                                   'q': 'Câu: “I have breakfast at six thirty.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['What time does she go to school?',
                                         'What time does she have breakfast?',
                                         'What time does she go to bed?',
                                         'What time does he have breakfast?'],
                                   'plain': True,
                                   'q': 'Câu: "She has breakfast at six fifteen.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['I get up at ten fifteen.',
                                         'I go to bed at ten fifteen.',
                                         'I go to school at ten fifteen.',
                                         'I chat with my friends at ten fifteen.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Tôi đi ngủ lúc mười giờ mười lăm phút.”',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['What time is it?',
                                         'What time does she have breakfast?',
                                         'What time do you get up?',
                                         'What time do you have breakfast?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Bạn ăn sáng lúc mấy giờ”?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Cô ấy đi học lúc mấy giờ?', 'Cô ấy đi ngủ lúc mấy giờ', 'Cô ấy ăn sáng lúc mấy giờ?', 'Anh ấy đi học lúc mấy giờ?'],
                                   'plain': True,
                                   'q': 'Câu: “What time does she go to school? có nghĩa là:',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['in', 'on', 'at', 'to'], 'plain': True, 'q': 'A: What time do you get up?', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'What time ___________ she have breakfast?', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['time', 'old', 'name', 'from'], 'plain': True, 'q': 'A: What ___________ is it?', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'What time ___________ he go to bed?', 't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['are', 'is', 'go', 'goes'],
                                   'plain': True,
                                   'q': "Mai ___________ to school at seven o'clock.",
                                   't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['are', 'is', 'does', 'do'],
                                   'plain': True,
                                   'q': 'What time ___________ you chat with your friends?',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['watch', 'watches', 'to watch', 'are watching'],
                                   'plain': True,
                                   'q': 'They ___________ TV at seven fifteen.',
                                   't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['go', 'goes', 'to go', 'going'],
                                   'plain': True,
                                   'q': "Minh and Nam ___________ to school at seven o'clock.",
                                   't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['have', 'has', 'to have', 'having'],
                                   'plain': True,
                                   'q': 'I ___________ dinner at home at seven thirty.',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['have', 'has', 'to have', 'having'],
                                   'plain': True,
                                   'q': 'She ___________ breakfast at six thirty.',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['What time is it?',
                                            'What time do you get up?',
                                            'What time does she have dinner?',
                                            'What time do Bill and Ben go to school?',
                                            'What time does he do his homework?'],
                                   'o': ['She has dinner at seven thirty.',
                                         'He does his homework at seven forty-five.',
                                         "It's ten o'clock.",
                                         'I get up at six fifteen.',
                                         "They go to school at seven o'clock."],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['lunch', 'homework', 'What', 'at', 'have'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['lunch', 'homework', 'What', 'at', 'have'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['lunch', 'homework', 'What', 'at', 'have'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['lunch', 'homework', 'What', 'at', 'have'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['lunch', 'homework', 'What', 'at', 'have'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': "1. Mai: <b>(1)&nbsp;______</b> time do you get up, Lan?<br>Lan: I get up at six o'clock.<br>2. Mary: What time do you "
                                   '<b>(2)&nbsp;______</b> breakfast?<br>Lucy: I have breakfast at six thirty.<br>3. Minh: What time do you go to '
                                   'school?<br>Nam: I go to school <b>(3)&nbsp;______</b> seven thirty.<br>4. Minh: What time does Mai have lunch?<br>Nam: She '
                                   'has <b>(4)&nbsp;______</b> at eleven thirty.<br>5. Phong: What time do you do your homework?<br>Quan: I do my '
                                   '<b>(5)&nbsp;______</b> at seven forty-five.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': 'Minh gets up at 6:45 a.m.', 't': 'tf'},
                                  {'id': 'e.2', 'q': 'He has breakfast at 6:15 a.m.', 't': 'tf'},
                                  {'id': 'e.3', 'q': 'He goes to school at 6:45 a.m.', 't': 'tf'},
                                  {'id': 'e.4', 'q': 'He has dinner at 7 p.m.', 't': 'tf'},
                                  {'id': 'e.5', 'q': 'He goes to bed at 9 p.m.', 't': 'tf'}],
                        'passage': 'My name is Minh. In the morning, I get up at five forty-five. I wash my face and clean my teeth. Then I do exercise about '
                                   'fifteen minutes. I have breakfast at six fifteen. I go to school at six forty-five. At noon, I have lunch at school. In '
                                   "the evening, I have dinner at home at seven twenty. I do my homework and go to bed at ten o'clock."}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Mai?', 'What', 'time', 'it,', 'is']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['seven', 'is', 'It', 'thirty.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'get', 'you', 'up?', 'What', 'time']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['up', 'I', 'at', "o'clock.", 'get', 'six']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['have', 'breakfast?', 'What', 'she', 'time', 'does']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['has', 'breakfast', 'seven', 'fifteen.', 'at', 'She']},
                                  {'id': 'f.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['and', 'to', 'Quan', 'go', 'school?', 'time', 'do', 'Phong', 'What']},
                                  {'id': 'f.8',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ["o'clock.", 'at', 'twelve', 'They', 'at', 'have', 'school', 'lunch']},
                                  {'id': 'f.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['time', 'do', 'homework?', 'your', 'you', 'do', 'What']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['bed', 'my', 'to', 'homework', 'go', 'and', 'at', 'ten.', 'I', 'do']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'},
           {'audio': True,
            'groups': [{'id': 'n',
                        'instr': 'Nghe file âm thanh và làm các câu theo số thứ tự trong bài nghe.',
                        'items': [{'id': 'n.1',
                                   'o': ['get up', 'read a book', 'chat with my friends'],
                                   'plain': True,
                                   'q': 'Câu 1. I ________________at six thirty.',
                                   't': 'mcq'},
                                  {'id': 'n.2',
                                   'o': ['go out', 'watch TV', 'go to bed'],
                                   'plain': True,
                                   'q': 'Câu 2. I ___________________ at five forty-five.',
                                   't': 'mcq'},
                                  {'id': 'n.3', 'q': 'Câu 3. What time do you have breakfast? - At six {_}', 't': 'fill'},
                                  {'id': 'n.4', 'q': "Câu 4. What time do you get up?- I get up at {_} o'clock.", 't': 'fill'},
                                  {'id': 'n.5', 'q': "Câu 5. I {_} at nine o'clock.", 't': 'fill'},
                                  {'id': 'n.6',
                                   'o': ['I get up at five thirty.', "I get up at five o'clock.", "I get up at six o'clock."],
                                   'plain': True,
                                   'q': 'Câu 6. What time do you get up?',
                                   't': 'mcq'},
                                  {'id': 'n.7',
                                   'o': ['At five fifteen.', 'At six thirty.', 'At six fifteen.'],
                                   'plain': True,
                                   'q': 'Câu 7. What time do you have breakfast?',
                                   't': 'mcq'},
                                  {'id': 'n.8',
                                   'o': ["It's six o'clock.", "It's seven o'clock.", "It's six thirty."],
                                   'plain': True,
                                   'q': 'Câu 8. What time is it?',
                                   't': 'mcq'},
                                  {'id': 'n.9',
                                   'o': ["It's six thirty.", "It's six fifteen", "It's six o'clock."],
                                   'plain': True,
                                   'q': 'Câu 9. What time is it?',
                                   't': 'mcq'},
                                  {'id': 'n.10',
                                   'o': ["It's six fifteen.", "It's six thirty.", "It's six forty-five."],
                                   'plain': True,
                                   'q': 'Câu 10. What time is it?',
                                   't': 'mcq'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Luyện nghe'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi giờ và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>What time is '
           "it?<br>Mấy giờ rồi?</td><td>It is/It's...<br>… giờ... (phút).</td></tr><tr><td>Ví dụ:<br>1. A: What time is it? Mấy giờ rồi?<br>B: It’s ten "
           "o'clock. Mười giờ.<br>2. A: What time is it? Mấy giờ rồi?<br>B: It's six fifteen. Sáu giờ mười lăm phút.</td></tr></table><p>2. Cách hỏi về thói "
           'quen hằng ngày của ai đó và cách trả lời:</p><p>a. Đối với chủ ngữ you hoặc they:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           'lời</td></tr><tr><td>What time do you/they + V +...?<br>Bạn/Họ … lúc mấy giờ?</td><td>I/They … at....<br>Tôi/Họ... giờ.... '
           "(phút).</td></tr><tr><td>Ví dụ:<br>A: What time do you have breakfast? Bạn ăn sáng lúc mấy giờ<br>B: I have breakfast at seven o'clock. Tôi ăn "
           'sáng lúc bảy giờ.</td></tr></table><p>b. Đối với chủ ngữ she hoặc he:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           'lời</td></tr><tr><td>What time does she/he + V+...?<br>Cô ấy/Cậu ấy.. lúc mấy giờ?</td><td>She/He... at...<br>Cô ấy/Cậu ấy... lúc..... giờ … '
           '(phút)</td></tr><tr><td>Ví dụ:<br>A: What time does she get up?<br>Cô ấy thức dậy lúc mấy giờ?<br>B: She gets up at five forty-five.<br>Cô ấy thức '
           'dậy lúc năm giờ bốn mươi lăm phút.<br>A: What time does he go to school?<br>Cậu ấy đi học lúc mấy giờ?<br>B: He goes to school at seven '
           'thirty.<br>Cậu ấy đi học lúc bây giờ ba mươi phút.</td></tr></table>',
 'title': 'Unit 2 – Time and daily routines: Luyện tập',
 'unit': 2}
