# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk2-de4',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'I. Listen to the sounds and circle the correct words. (nghe âm, chọn từ có âm đó).',
                        'items': [{'id': 'l1.1', 'o': ['long', 'round', 'farm'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['slim', 'television', 'centre'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['farmer', 'factory', 'nurse'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['street', 'big', 'quiet'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'}]},
                       {'id': 'l2',
                        'instr': 'II. Listen and tick the correct pictures. (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'r1',
                        'instr': 'III. Circle the correct answers. (nhìn tranh, chọn câu đúng).',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['I wash the clothes.', 'I wash the dishes.', 'I clean the floor.'],
                                   'q': 'What do you do at noon?',
                                   't': 'mcq'},
                                  {'id': 'r1.10',
                                   'img': 'r1_2.png',
                                   'o': ['She’s a farmer.', 'She’s a nurse.', 'She’s a doctor.'],
                                   'q': 'What does Lan do?',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['He goes to the shopping centre.', 'He goes to the swimming pool.', 'He goes to the cinema.'],
                                   'q': 'Where does Ben go on Wednesdays?',
                                   't': 'mcq'},
                                  {'id': 'r1.12',
                                   'img': 'r1_4.png',
                                   'o': ['We go to school in the morning.', 'They go to school in the morning.', 'We go to school in the evening.'],
                                   'q': 'When do you go to school?',
                                   't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'IV. Fill in the blanks. (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'r2.13', 'img': 'r2_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.14', 'img': 'r2_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'img': 'r2_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'img': 'r2_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>My name is Emily. I am 25 years old. I have long <b>(1) ______</b> and big eyes. I am an <b>(2) ______</b> In the '
                                   'morning, I often <b>(3) ______</b> because it’s good for my health. Then I go to work. I work from 8 a.m to 5 p.m. On '
                                   'weekdays, I go back home and cook dinner. At the weekends, I go to the <b>(4) ______</b> with my friends.</p>'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 2 – Đề 4',
 'unit': 'GiuaKy2'}
