# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u12-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What does he do?', 'Where does he work?', 'How many people are there in your family?', 'Where do you live?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về số lượng người trong gia đình?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: What _____________ he do?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["I'm a worker.", 'I live in Nguyen Kiem Street.', "She's a nurse.", 'I live with my parents.', 'I work at a factory.'],
                                   'plain': True,
                                   'q': 'Where do you live?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['do', 'have', 'is', 'are'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: Do you _____ a sister or a brother, Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['there', 'people', 'family?', 'are', 'your', 'many', 'in', 'How']},
                                  {'id': 't1.6',
                                   'o': ['Where do you live?', 'What do you do?', 'Where do you work?', 'Where does your brother work?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về nghề nghiệp của ai đó?',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['teacher', 'farmer', 'worker', 'policeman'],
                                   'plain': True,
                                   'q': "My father works on a farm. He's a _____________.",
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ["I'm a worker.", 'I live in Nguyen Kiem Street.', "She's a nurse.", 'I live with my parents.', 'I work at a factory.'],
                                   'plain': True,
                                   'q': 'Who do you live with?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['am', 'have', 'do', 'does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: Yes, I _____. I have a sister and a brother.',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do?', 'mother', 'What', 'your', 'does']},
                                  {'id': 't1.11',
                                   'o': ['What do you do?', 'How many people are there in your family?', 'Where do you live?', 'Where does she work?'],
                                   'plain': True,
                                   'q': 'Câu: “There are four people" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['farmer', 'nurse', 'worker', 'student'],
                                   'plain': True,
                                   'q': "My sister works at a factory. She's a _____________.",
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ["I'm a worker.", 'I live in Nguyen Kiem Street.', "She's a nurse.", 'I live with my parents.', 'I work at a factory.'],
                                   'plain': True,
                                   'q': 'What do you do?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['brother', 'sister', 'father', 'grandfather'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What does your _____ do?',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['office', "She's", 'worker.', 'an']},
                                  {'id': 't1.16',
                                   'o': ["She's an office worker.", 'She works on a farm.', 'She lives in Le Lai Street.', "She's a nurse."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where does she work?”?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['When', 'What', 'How', 'Where'],
                                   'plain': True,
                                   'q': '_____________ does your brother work?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ["I'm a worker.", 'I live in Nguyen Kiem Street.', "She's a nurse.", 'I live with my parents.', 'I work at a factory.'],
                                   'plain': True,
                                   'q': 'Where do you work?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['work', 'do', 'in', 'is'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: Where does she _____?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['does', 'work?', 'Where', 'she']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 12 – Jobs: Kiểm tra 1',
 'unit': 12}
