# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': "Where's the bookshop?",
 'a.10': 'They are two hundred thousand dong.',
 'a.2': 'How much is the skirt?',
 'a.3': "Where's the food shop?",
 'a.4': "It's ninety thousand dong.",
 'a.5': 'How much is the T-shirt?',
 'a.6': "It's near the bookshop.",
 'a.7': 'Tiệm bánh mì ở giữa hiệu sách và cửa hàng thú cứng.',
 'a.8': 'Trung tâm thể thao đối diện trung tâm mua sắm.',
 'a.9': 'How much is the shirt?',
 'b.1': 'How much',
 'b.10': 'near',
 'b.2': "They're",
 'b.3': 'Where',
 'b.4': 'these',
 'b.5': 'between',
 'b.6': 'is',
 'b.7': 'opposite',
 'b.8': 'are',
 'b.9': 'over',
 'c.1': {'blanks': [["It's ninety thousand dong."],
                    ["It's near the gift shop."],
                    ["They're one hundred and ninety thousand dong."],
                    ['Go straight and turn left at the corner.'],
                    ["Great! Let's go."]]},
 'd.1': 'near',
 'd.2': 'get',
 'd.3': 'over there',
 'd.4': 'between',
 'd.5': 'it',
 'd.6': 'those',
 'e.1': 'T',
 'e.2': 'T',
 'e.3': 'T',
 'e.4': 'F',
 'e.5': 'F',
 'e.6': 'F',
 'f.1': ['Where is the pet shop?'],
 'f.10': ['It is eighty thousand dong. GHI NHỚ'],
 'f.2': ["It's behind the bookshop."],
 'f.3': ['The pet shop is opposite the bookshop.'],
 'f.4': ['The bakery is opposite the museum.'],
 'f.5': ['How much are these pants?'],
 'f.6': ['They are two hundred and forty thousand dong.'],
 'f.7': ['How much is that shirt?'],
 'f.8': ['It is five hundred thousand dong.'],
 'f.9': ['How much is that school bag?']}

EXPLANATIONS = {'a.1': "Đáp án: Where's the bookshop?",
 'a.10': 'Đáp án: They are two hundred thousand dong.',
 'a.2': 'Đáp án: How much is the skirt?',
 'a.3': "Đáp án: Where's the food shop?",
 'a.4': "Đáp án: It's ninety thousand dong.",
 'a.5': 'Đáp án: How much is the T-shirt?',
 'a.6': "Đáp án: It's near the bookshop.",
 'a.7': 'Đáp án: Tiệm bánh mì ở giữa hiệu sách và cửa hàng thú cứng.',
 'a.8': 'Đáp án: Trung tâm thể thao đối diện trung tâm mua sắm.',
 'a.9': 'Đáp án: How much is the shirt?',
 'b.1': 'Đáp án: How much',
 'b.10': 'Đáp án: near',
 'b.2': "Đáp án: They're",
 'b.3': 'Đáp án: Where',
 'b.4': 'Đáp án: these',
 'b.5': 'Đáp án: between',
 'b.6': 'Đáp án: is',
 'b.7': 'Đáp án: opposite',
 'b.8': 'Đáp án: are',
 'b.9': 'Đáp án: over',
 'c.1': "How much is the skirt? → It's ninety thousand dong.; Where is the pet shop? → It's near the gift shop.; How much are those trousers? → They're one "
        'hundred and ninety thousand dong.; How can I get to the bookshop? → Go straight and turn left at the corner.; Do you want to go to the shopping '
        "center with me? → Great! Let's go.",
 'd.1': 'Đáp án: near',
 'd.2': 'Đáp án: get',
 'd.3': 'Đáp án: over there',
 'd.4': 'Đáp án: between',
 'd.5': 'Đáp án: it',
 'd.6': 'Đáp án: those',
 'e.1': 'Đáp án: True (Đúng)',
 'e.2': 'Đáp án: True (Đúng)',
 'e.3': 'Đáp án: True (Đúng)',
 'e.4': 'Đáp án: False (Sai)',
 'e.5': 'Đáp án: False (Sai)',
 'e.6': 'Đáp án: False (Sai)',
 'f.1': 'Câu đúng: Where is the pet shop?',
 'f.10': 'Câu đúng: It is eighty thousand dong. GHI NHỚ',
 'f.2': "Câu đúng: It's behind the bookshop.",
 'f.3': 'Câu đúng: The pet shop is opposite the bookshop.',
 'f.4': 'Câu đúng: The bakery is opposite the museum.',
 'f.5': 'Câu đúng: How much are these pants?',
 'f.6': 'Câu đúng: They are two hundred and forty thousand dong.',
 'f.7': 'Câu đúng: How much is that shirt?',
 'f.8': 'Câu đúng: It is five hundred thousand dong.',
 'f.9': 'Câu đúng: How much is that school bag?'}
