# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_hsg.py"""

ANS = {'r1.1': 'C',
 'r1.2': 'B',
 'r1.3': 'B',
 'r1.4': 'A',
 'r1.5': 'F',
 'r1.6': 'F',
 'r1.7': 'F',
 'r1.8': 'F',
 'r10.1': 'C',
 'r10.10': 'T',
 'r10.2': 'A',
 'r10.3': 'C',
 'r10.4': 'A',
 'r10.5': 'A',
 'r10.6': 'F',
 'r10.7': 'T',
 'r10.8': 'F',
 'r10.9': 'T',
 'r11.1': 'B',
 'r11.10': 'T',
 'r11.2': 'B',
 'r11.3': 'B',
 'r11.4': 'A',
 'r11.5': 'B',
 'r11.6': 'F',
 'r11.7': 'F',
 'r11.8': 'T',
 'r11.9': 'F',
 'r12.1': 'B',
 'r12.2': 'C',
 'r12.3': 'D',
 'r12.4': 'D',
 'r12.5': 'B',
 'r13.1': 'A',
 'r13.2': 'A',
 'r13.3': 'A',
 'r13.4': 'C',
 'r13.5': 'F',
 'r13.6': 'T',
 'r13.7': 'F',
 'r13.8': 'T',
 'r14.1': 'B',
 'r14.2': 'B',
 'r14.3': 'C',
 'r14.4': 'T',
 'r14.5': 'T',
 'r14.6': 'F',
 'r14.7': 'F',
 'r14.8': 'F',
 'r15.1': 'C',
 'r15.2': 'B',
 'r15.3': 'C',
 'r15.4': 'C',
 'r15.5': 'T',
 'r15.6': 'F',
 'r15.7': 'T',
 'r15.8': 'F',
 'r15.9': 'F',
 'r16.1': 'B',
 'r16.10': 'T',
 'r16.2': 'B',
 'r16.3': 'C',
 'r16.4': 'A',
 'r16.5': 'C',
 'r16.6': 'F',
 'r16.7': 'T',
 'r16.8': 'F',
 'r16.9': 'T',
 'r17.1': 'B',
 'r17.2': 'C',
 'r17.3': 'A',
 'r17.4': 'F',
 'r17.5': 'F',
 'r17.6': 'T',
 'r17.7': 'F',
 'r18.1': 'C',
 'r18.2': 'B',
 'r18.3': 'B',
 'r18.4': 'B',
 'r18.5': 'A',
 'r18.6': 'T',
 'r18.7': 'F',
 'r18.8': 'F',
 'r19.1': 'B',
 'r19.10': 'F',
 'r19.2': 'A',
 'r19.3': 'B',
 'r19.4': 'B',
 'r19.5': 'B',
 'r19.6': 'F',
 'r19.7': 'F',
 'r19.8': 'T',
 'r19.9': 'F',
 'r2.1': 'B',
 'r2.2': 'C',
 'r2.3': 'B',
 'r2.4': 'B',
 'r2.5': 'F',
 'r2.6': 'T',
 'r2.7': 'F',
 'r2.8': 'F',
 'r20.1': 'B',
 'r20.2': 'B',
 'r20.3': 'B',
 'r20.4': 'C',
 'r20.5': 'A',
 'r20.6': 'F',
 'r20.7': 'T',
 'r20.8': 'T',
 'r20.9': 'T',
 'r3.1': 'B',
 'r3.2': 'B',
 'r3.3': 'B',
 'r3.4': 'F',
 'r3.5': 'F',
 'r3.6': 'T',
 'r3.7': 'F',
 'r4.1': 'B',
 'r4.2': 'C',
 'r4.3': 'A',
 'r4.4': 'B',
 'r4.5': 'F',
 'r4.6': 'F',
 'r4.7': 'F',
 'r4.8': 'T',
 'r5.1': 'C',
 'r5.2': 'B',
 'r5.3': 'B',
 'r5.4': 'T',
 'r5.5': 'F',
 'r5.6': 'F',
 'r5.7': 'T',
 'r6.1': 'B',
 'r6.2': 'B',
 'r6.3': 'A',
 'r6.4': 'A',
 'r6.5': 'T',
 'r6.6': 'F',
 'r6.7': 'F',
 'r6.8': 'T',
 'r7.1': 'B',
 'r7.2': 'B',
 'r7.3': 'B',
 'r7.4': 'C',
 'r7.5': 'F',
 'r7.6': 'T',
 'r7.7': 'T',
 'r7.8': 'F',
 'r8.1': 'B',
 'r8.2': 'B',
 'r8.3': 'C',
 'r8.4': 'F',
 'r8.5': 'T',
 'r8.6': 'T',
 'r8.7': 'F',
 'r9.1': 'B',
 'r9.2': 'A',
 'r9.3': 'B',
 'r9.4': 'B',
 'r9.5': 'F',
 'r9.6': 'F',
 'r9.7': 'T',
 'v1.1': 'A',
 'v1.2': 'B',
 'v1.3': 'C',
 'v1.4': 'D',
 'v1.5': 'D',
 'v1.6': 'A',
 'v1.7': 'C',
 'v1.8': 'B',
 'v10.1': 'A',
 'v10.2': 'B',
 'v10.3': 'C',
 'v10.4': 'A',
 'v10.5': 'C',
 'v11.1': 'C',
 'v11.2': 'A',
 'v12.1': 'A',
 'v12.2': 'A',
 'v12.3': 'B',
 'v12.4': 'B',
 'v12.5': 'C',
 'v12.6': 'A',
 'v12.7': 'A',
 'v13.1': 'B',
 'v13.2': 'A',
 'v13.3': 'B',
 'v13.4': 'A',
 'v14.1': 'C',
 'v14.2': 'B',
 'v14.3': 'B',
 'v14.4': 'B',
 'v14.5': 'A',
 'v15.1': 'A',
 'v15.2': 'C',
 'v15.3': 'A',
 'v15.4': 'B',
 'v15.5': 'C',
 'v15.6': 'C',
 'v15.7': 'B',
 'v16.1': 'A',
 'v16.2': 'B',
 'v16.3': 'A',
 'v16.4': 'B',
 'v16.5': 'C',
 'v16.6': 'B',
 'v16.7': 'B',
 'v16.8': 'A',
 'v17.1': 'A',
 'v18.1': 'A',
 'v18.2': 'C',
 'v18.3': 'B',
 'v19.1': 'A',
 'v19.2': 'B',
 'v2.1': 'A',
 'v2.2': 'B',
 'v2.3': 'A',
 'v2.4': 'D',
 'v20.1': 'B',
 'v20.2': 'B',
 'v20.3': 'B',
 'v3.1': 'A',
 'v3.2': 'B',
 'v3.3': 'B',
 'v3.4': 'B',
 'v4.1': 'B',
 'v4.2': 'C',
 'v4.3': 'B',
 'v5.1': 'A',
 'v5.2': 'C',
 'v5.3': 'C',
 'v5.4': 'C',
 'v5.5': 'C',
 'v5.6': 'A',
 'v6.1': 'C',
 'v6.2': 'C',
 'v6.3': 'B',
 'v6.4': 'A',
 'v6.5': 'B',
 'v7.1': 'A',
 'v7.2': 'B',
 'v7.3': 'A',
 'v7.4': 'A',
 'v7.5': 'A',
 'v7.6': 'A',
 'v8.1': 'A',
 'v8.2': 'A',
 'v8.3': 'C',
 'v8.4': 'C',
 'v8.5': 'A',
 'v8.6': 'A',
 'v9.1': 'A',
 'v9.2': 'B',
 'v9.3': 'C',
 'v9.4': 'C',
 'v9.5': 'C'}

EXPLANATIONS = {'r1.1': 'Đáp án: C. Tall buildings and the Statue of Liberty',
 'r1.2': 'Đáp án: B. Japanese',
 'r1.3': 'Đáp án: B. The Merlion',
 'r1.4': 'Đáp án: A. Ao dai',
 'r1.5': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r1.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r1.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r1.8': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r10.1': 'Đáp án: C. Beach',
 'r10.10': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r10.2': 'Đáp án: A. Set up a tent and told stories',
 'r10.3': 'Đáp án: C. Bangkok',
 'r10.4': 'Đáp án: A. Sydney Harbour Bridge',
 'r10.5': 'Đáp án: A. Dancing robots',
 'r10.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r10.7': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r10.8': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r10.9': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r11.1': 'Đáp án: B. At the end of the street',
 'r11.10': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r11.2': 'Đáp án: B. Big and colorful',
 'r11.3': 'Đáp án: B. Birds singing',
 'r11.4': 'Đáp án: A. Ride bikes and draw chalk pictures',
 'r11.5': 'Đáp án: B. Calm and peaceful',
 'r11.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r11.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r11.8': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r11.9': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r12.1': 'Đáp án: B. Sarah',
 'r12.2': 'Đáp án: C. Emily',
 'r12.3': 'Đáp án: D. Keeps everyone safe as a policeman',
 'r12.4': 'Đáp án: D. City office',
 'r12.5': 'Đáp án: B. Fun toys for kids',
 'r13.1': 'Đáp án: A. Big and bright',
 'r13.2': 'Đáp án: A. Long',
 'r13.3': 'Đáp án: A. Her big smile',
 'r13.4': 'Đáp án: C. The new friend was tall.',
 'r13.5': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r13.6': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r13.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r13.8': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r14.1': 'Đáp án: B. Broom and dustpan',
 'r14.2': 'Đáp án: B. Wash the clothes',
 'r14.3': 'Đáp án: C. Evening',
 'r14.4': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r14.5': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r14.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r14.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r14.8': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r15.1': 'Đáp án: C. Shopping centre',
 'r15.2': 'Đáp án: B. Play tennis',
 'r15.3': 'Đáp án: C. Swimming in the pool',
 'r15.4': 'Đáp án: C. Do yoga',
 'r15.5': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r15.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r15.7': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r15.8': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r15.9': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r16.1': 'Đáp án: B. Weather',
 'r16.10': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r16.2': 'Đáp án: B. They wanted to buy fresh bread.',
 'r16.3': 'Đáp án: C. Fruits and vegetables',
 'r16.4': 'Đáp án: A. Water park',
 'r16.5': 'Đáp án: C. Ran to a food stall',
 'r16.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r16.7': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r16.8': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r16.9': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r17.1': 'Đáp án: B. Go straight',
 'r17.2': 'Đáp án: C. Turn right',
 'r17.3': 'Đáp án: A. Turn round',
 'r17.4': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r17.5': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r17.6': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r17.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r18.1': 'Đáp án: C. Opposite the entrance',
 'r18.2': 'Đáp án: B. Between two other skirts',
 'r18.3': 'Đáp án: B. Near the apples',
 'r18.4': 'Đáp án: B. Behind the fish and meat section',
 'r18.5': 'Đáp án: A. Between the shoe shop and the hat shop',
 'r18.6': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r18.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r18.8': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r19.1': 'Đáp án: B. Giraffe',
 'r19.10': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r19.2': 'Đáp án: A. Roar',
 'r19.3': 'Đáp án: B. Near the water',
 'r19.4': 'Đáp án: B. Quickly',
 'r19.5': 'Đáp án: B. Dance',
 'r19.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r19.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r19.8': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r19.9': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r2.1': "Đáp án: B. 7 o'clock",
 'r2.2': "Đáp án: C. 8 o'clock",
 'r2.3': 'Đáp án: B. Cereal with milk and orange juice',
 'r2.4': "Đáp án: B. 8 o'clock",
 'r2.5': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r2.6': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r2.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r2.8': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r20.1': 'Đáp án: B. Put up a tent',
 'r20.2': 'Đáp án: B. Build a campfire',
 'r20.3': 'Đáp án: B. Tell stories',
 'r20.4': 'Đáp án: C. Singing songs',
 'r20.5': 'Đáp án: A. Play card games',
 'r20.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r20.7': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r20.8': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r20.9': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r3.1': 'Đáp án: B. Listen to music',
 'r3.2': 'Đáp án: B. Wednesday',
 'r3.3': 'Đáp án: B. The last day of the school week',
 'r3.4': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r3.5': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r3.6': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r3.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r4.1': 'Đáp án: B. Love and exchanging cards',
 'r4.2': 'Đáp án: C. Enjoy nature as flowers bloom',
 'r4.3': 'Đáp án: A. A special day with cake, balloons, and laughter',
 'r4.4': 'Đáp án: B. Fruits',
 'r4.5': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r4.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r4.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r4.8': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r5.1': 'Đáp án: C. Cook with mom',
 'r5.2': 'Đáp án: B. But',
 'r5.3': 'Đáp án: B. Roller skate',
 'r5.4': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r5.5': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r5.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r5.7': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r6.1': 'Đáp án: B. Big and busy with tall buildings',
 'r6.2': 'Đáp án: B. Friendly neighbors and parks',
 'r6.3': 'Đáp án: A. Smaller than a town, with fewer houses',
 'r6.4': 'Đáp án: A. Learn how to use computers and play educational games',
 'r6.5': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r6.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r6.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r6.8': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r7.1': 'Đáp án: B. Use colors and shapes to make drawings',
 'r7.2': 'Đáp án: B. Read and speak in a different language',
 'r7.3': 'Đáp án: B. Discovering the past and different places',
 'r7.4': 'Đáp án: C. Numbers and counting',
 'r7.5': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r7.6': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r7.7': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r7.8': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r8.1': 'Đáp án: B. How to use computers and technology',
 'r8.2': 'Đáp án: B. Moving and playing games',
 'r8.3': 'Đáp án: C. English teacher',
 'r8.4': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r8.5': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r8.6': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'r8.7': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r9.1': 'Đáp án: B. June',
 'r9.2': 'Đáp án: A. October',
 'r9.3': 'Đáp án: B. November',
 'r9.4': 'Đáp án: B. Sports clothes',
 'r9.5': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r9.6': 'Đáp án: False (Sai) (căn cứ đoạn văn).',
 'r9.7': 'Đáp án: True (Đúng) (căn cứ đoạn văn).',
 'v1.1': 'Đáp án: A. America',
 'v1.2': 'Đáp án: B. Australia',
 'v1.3': 'Đáp án: C. Britain',
 'v1.4': 'Đáp án: D. Japan',
 'v1.5': 'Đáp án: D. Malaysia',
 'v1.6': 'Đáp án: A. Singapore',
 'v1.7': 'Đáp án: C. Vietnam',
 'v1.8': 'Đáp án: B. Australia',
 'v10.1': 'Đáp án: A. beach',
 'v10.2': 'Đáp án: B. Bangkok',
 'v10.3': 'Đáp án: C. countryside',
 'v10.4': 'Đáp án: A. Tokyo',
 'v10.5': 'Đáp án: C. in; yesterday',
 'v11.1': 'Đáp án: C. on; in',
 'v11.2': 'Đáp án: A. busy; noisy',
 'v12.1': 'Đáp án: A. actor',
 'v12.2': 'Đáp án: A. nurse',
 'v12.3': 'Đáp án: B. policeman',
 'v12.4': 'Đáp án: B. farm',
 'v12.5': 'Đáp án: C. nursing home',
 'v12.6': 'Đáp án: A. actor',
 'v12.7': 'Đáp án: A. hospital',
 'v13.1': 'Đáp án: B. tall',
 'v13.2': 'Đáp án: A. eyes; face',
 'v13.3': 'Đáp án: B. long',
 'v13.4': 'Đáp án: A. round',
 'v14.1': 'Đáp án: C. noon',
 'v14.2': 'Đáp án: B. evening',
 'v14.3': 'Đáp án: B. evening',
 'v14.4': 'Đáp án: B. wash the clothes',
 'v14.5': 'Đáp án: A. noon',
 'v15.1': 'Đáp án: A. cinema',
 'v15.2': 'Đáp án: C. swimming pool',
 'v15.3': 'Đáp án: A. shopping centre',
 'v15.4': 'Đáp án: B. sports centre',
 'v15.5': 'Đáp án: C. cook meals',
 'v15.6': 'Đáp án: C. swimming pool',
 'v15.7': 'Đáp án: B. play tennis',
 'v16.1': 'Đáp án: A. cloudy',
 'v16.2': 'Đáp án: B. sunny',
 'v16.3': 'Đáp án: A. bakery',
 'v16.4': 'Đáp án: B. supermarket',
 'v16.5': 'Đáp án: C. sunny',
 'v16.6': 'Đáp án: B. bookshop',
 'v16.7': 'Đáp án: B. food stall',
 'v16.8': 'Đáp án: A. supermarket',
 'v17.1': 'Đáp án: A. turn round',
 'v18.1': 'Đáp án: A. gift shop',
 'v18.2': 'Đáp án: C. between',
 'v18.3': 'Đáp án: B. thousand',
 'v19.1': 'Đáp án: A. roar',
 'v19.2': 'Đáp án: B. roars',
 'v2.1': "Đáp án: A. o'clock",
 'v2.2': 'Đáp án: B. have breakfast',
 'v2.3': "Đáp án: A. o'clock",
 'v2.4': 'Đáp án: D. go to bed',
 'v20.1': 'Đáp án: B. tell a story',
 'v20.2': 'Đáp án: B. take a photo',
 'v20.3': 'Đáp án: B. put up a tent',
 'v3.1': 'Đáp án: A. Tuesday',
 'v3.2': 'Đáp án: B. listen to music',
 'v3.3': 'Đáp án: B. Monday',
 'v3.4': 'Đáp án: B. Friday',
 'v4.1': 'Đáp án: B. January',
 'v4.2': 'Đáp án: C. jam',
 'v4.3': 'Đáp án: B. Jam',
 'v5.1': 'Đáp án: A. can',
 'v5.2': 'Đáp án: C. roller skate',
 'v5.3': 'Đáp án: C. swim',
 'v5.4': 'Đáp án: C. cook',
 'v5.5': 'Đáp án: C. ride',
 'v5.6': 'Đáp án: A. but',
 'v6.1': 'Đáp án: C. village',
 'v6.2': 'Đáp án: C. playground',
 'v6.3': 'Đáp án: B. computer room',
 'v6.4': 'Đáp án: A. village',
 'v6.5': 'Đáp án: B. mountains',
 'v7.1': 'Đáp án: A. art',
 'v7.2': 'Đáp án: B. history and geography',
 'v7.3': 'Đáp án: A. music',
 'v7.4': 'Đáp án: A. maths',
 'v7.5': 'Đáp án: A. science',
 'v7.6': 'Đáp án: A. history and geography',
 'v8.1': 'Đáp án: A. IT (information technology)',
 'v8.2': 'Đáp án: A. maths teacher',
 'v8.3': 'Đáp án: C. playground',
 'v8.4': 'Đáp án: C. English teacher',
 'v8.5': 'Đáp án: A. PE (physical education)',
 'v8.6': 'Đáp án: A. why',
 'v9.1': 'Đáp án: A. sports day',
 'v9.2': 'Đáp án: B. November',
 'v9.3': 'Đáp án: C. December',
 'v9.4': 'Đáp án: C. January',
 'v9.5': 'Đáp án: C. September'}
