# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': ['mother'],
 'l1.2': ['store'],
 'l1.3': ['grapes'],
 'l1.4': ['tomatoes'],
 'l1.5': ['milk'],
 'v1.10': 'C',
 'v1.6': 'C',
 'v1.7': 'A',
 'v1.8': 'B',
 'v1.9': 'D',
 'v2.11': 'C',
 'v2.12': 'A',
 'v2.13': 'B',
 'v2.14': 'B',
 'v2.15': 'C',
 'v3.16': ['letters'],
 'v3.17': ['writes'],
 'v3.18': ['presents'],
 'v3.19': ['brings'],
 'v3.20': ['houses'],
 'v4.21': ['Anna is from the USA.', 'She is from the USA.', 'She’s from the USA.', 'From the USA.', 'The USA.', 'The USA'],
 'v4.22': ['She likes vegetables and fruits.', 'She loves vegetables and fruits.', 'Vegetables and fruits.'],
 'v4.23': ['He likes meat.', 'He loves meat.', 'Meat.'],
 'v4.24': ['There are four people in Anna’s family.', 'There are four people.', 'There are four.', 'Four.'],
 'v4.25': ['She likes pork and chicken.', 'She loves pork and chicken.', 'Pork and chicken.'],
 'v5.26': ['Anna is taller than her sister.'],
 'v5.27': ['She wears new clothes at Tet.'],
 'v5.28': ['What does her mother look like?'],
 'v5.29': ['Where does your brother work?'],
 'v5.30': ['When is the Children’s day?']}

EXPLANATIONS = {'l1.1': 'Đáp án: mother',
 'l1.2': 'Đáp án: store',
 'l1.3': 'Đáp án: grapes',
 'l1.4': 'Đáp án: tomatoes',
 'l1.5': 'Đáp án: milk',
 'v1.10': 'airport là địa điểm; còn lại là nghề nghiệp.',
 'v1.6': 'teacher là nghề nghiệp; còn lại là động vật.',
 'v1.7': 'second là số thứ tự; còn lại là số đếm.',
 'v1.8': 'much không phải tính từ như các từ còn lại.',
 'v1.9': 'near là tính từ; còn lại là địa điểm.',
 'v2.11': 'Hỏi giờ → What time.',
 'v2.12': 'at + giờ.',
 'v2.13': 'her brother → does.',
 'v2.14': 'engineer bắt đầu bằng nguyên âm → an.',
 'v2.15': 'Would you like some + N?',
 'v3.16': 'Đáp án: letters',
 'v3.17': 'Đáp án: writes',
 'v3.18': 'Đáp án: presents',
 'v3.19': 'Đáp án: brings',
 'v3.20': 'Đáp án: houses',
 'v4.21': 'Anna is from the USA.',
 'v4.22': 'She likes vegetables and fruits.',
 'v4.23': 'He likes meat.',
 'v4.24': 'There are four people in Anna’s family.',
 'v4.25': 'She likes pork and chicken.',
 'v5.26': 'Câu đúng: Anna is taller than her sister.',
 'v5.27': 'Câu đúng: She wears new clothes at Tet.',
 'v5.28': 'Câu đúng: What does her mother look like?',
 'v5.29': 'Câu đúng: Where does your brother work?',
 'v5.30': 'Câu đúng: When is the Children’s day?'}
