# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'Where do you live?',
 'a.10': 'Tôi sống ở số 64 đường Nguyễn Huệ.',
 'a.2': "It's a small road.",
 'a.3': 'I live in Le Lai Street.',
 'a.4': "What's the street like?",
 'a.5': "It's a big city.",
 'a.6': 'I live in a small house with my parents.',
 'a.7': "It's a small village.",
 'a.8': 'She lives in Nguyen Van Troi Street.',
 'a.9': 'Cậu ấy sống trong một căn nhà nhỏ cùng với dì của cậu ấy.',
 'b.1': 'do',
 'b.10': 'in',
 'b.2': 'live',
 'b.3': 'does',
 'b.4': "What's",
 'b.5': 'at',
 'b.6': 'in',
 'b.7': 'with',
 'b.8': 'Who',
 'b.9': 'like',
 'c.1': {'blanks': [['I live in Bui Minh Truc Street.'],
                    ["It's a busy street."],
                    ['I live with my parents.'],
                    ["It's a quiet village."],
                    ['She lives in Nguyen Van Nghi Street.']]},
 'd.1': 'in',
 'd.2': 'like',
 'd.3': 'lives',
 'd.4': 'with',
 'd.5': 'house',
 'e.1': 'He lives in a small house.',
 'e.2': 'He live with his parents.',
 'e.3': "It's a small and quiet street.",
 'e.4': "No, there aren't.",
 'e.5': 'Yes, there are.',
 'f.1': ['Where do you live, Minh?'],
 'f.10': ['He lives with his parents and grandparents.'],
 'f.2': ['I live in An Duong Vuong Street.'],
 'f.3': ["What's the street like?"],
 'f.4': ['The street is small and quiet.'],
 'f.5': ['I live in a small flat with my parents.'],
 'f.6': ['The flat is small and beautiful.'],
 'f.7': ['She lives at 15 Le Lai Street.'],
 'f.8': ['They live in a big house with their grandparents.'],
 'f.9': ['Who does he live with?']}

EXPLANATIONS = {'a.1': 'Đáp án: Where do you live?',
 'a.10': 'Đáp án: Tôi sống ở số 64 đường Nguyễn Huệ.',
 'a.2': "Đáp án: It's a small road.",
 'a.3': 'Đáp án: I live in Le Lai Street.',
 'a.4': "Đáp án: What's the street like?",
 'a.5': "Đáp án: It's a big city.",
 'a.6': 'Đáp án: I live in a small house with my parents.',
 'a.7': "Đáp án: It's a small village.",
 'a.8': 'Đáp án: She lives in Nguyen Van Troi Street.',
 'a.9': 'Đáp án: Cậu ấy sống trong một căn nhà nhỏ cùng với dì của cậu ấy.',
 'b.1': 'Đáp án: do',
 'b.10': 'Đáp án: in',
 'b.2': 'Đáp án: live',
 'b.3': 'Đáp án: does',
 'b.4': "Đáp án: What's",
 'b.5': 'Đáp án: at',
 'b.6': 'Đáp án: in',
 'b.7': 'Đáp án: with',
 'b.8': 'Đáp án: Who',
 'b.9': 'Đáp án: like',
 'c.1': "Where do you live? → I live in Bui Minh Truc Street.; What's the street like? → It's a busy street.; Who do you live with? → I live with my parents.; "
        "What's the village like? → It's a quiet village.; Where does she live? → She lives in Nguyen Van Nghi Street.",
 'd.1': 'Đáp án: in',
 'd.2': 'Đáp án: like',
 'd.3': 'Đáp án: lives',
 'd.4': 'Đáp án: with',
 'd.5': 'Đáp án: house',
 'e.1': 'Đáp án: He lives in a small house.',
 'e.2': 'Đáp án: He live with his parents.',
 'e.3': "Đáp án: It's a small and quiet street.",
 'e.4': "Đáp án: No, there aren't.",
 'e.5': 'Đáp án: Yes, there are.',
 'f.1': 'Câu đúng: Where do you live, Minh?',
 'f.10': 'Câu đúng: He lives with his parents and grandparents.',
 'f.2': 'Câu đúng: I live in An Duong Vuong Street.',
 'f.3': "Câu đúng: What's the street like?",
 'f.4': 'Câu đúng: The street is small and quiet.',
 'f.5': 'Câu đúng: I live in a small flat with my parents.',
 'f.6': 'Câu đúng: The flat is small and beautiful.',
 'f.7': 'Câu đúng: She lives at 15 Le Lai Street.',
 'f.8': 'Câu đúng: They live in a big house with their grandparents.',
 'f.9': 'Câu đúng: Who does he live with?'}
