# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'gi.1': 'b',
 'gi.2': 'd',
 'gi.3': 'c',
 'gi.4': 'a',
 'gii.5': {'blanks': [['d'], ['a'], ['c'], ['b']]},
 'giii.6': ['behind'],
 'giii.7': ['farm'],
 'giii.8': ['sunny'],
 'giii.9': ['Turn right'],
 'giv.10': 'A',
 'giv.11': 'B',
 'giv.12': 'C',
 'giv.13': 'B',
 'gv.14': ['Do you want to go to the food stall?'],
 'gv.15': ['Why do you like crocodiles?'],
 'gv.16': ['What was the weather like last Monday?'],
 'gvi.17': 'T',
 'gvi.18': 'F',
 'gvi.19': 'T',
 'gvii.20': ['bookshop'],
 'gvii.21': ['bakery'],
 'gvii.22': ['water park'],
 'gvii.23': ['gift shop'],
 'gviii.24': ['Because they run quickly.'],
 'gviii.25': ['They’re putting up a tent.'],
 'gviii.26': ['It says ‘turn right’.'],
 'gviii.27': ['It was cloudy.']}

EXPLANATIONS = {'gi.1': 'Câu 1 ứng với tranh b (theo đáp án của đề).',
 'gi.2': 'Câu 2 ứng với tranh d (theo đáp án của đề).',
 'gi.3': 'Câu 3 ứng với tranh c (theo đáp án của đề).',
 'gi.4': 'Câu 4 ứng với tranh a (theo đáp án của đề).',
 'gii.5': 'Đáp án theo đáp án của đề: 1–d, 2–a, 3–c, 4–b',
 'giii.6': 'Đáp án: behind',
 'giii.7': 'Đáp án: farm',
 'giii.8': 'Đáp án: sunny',
 'giii.9': 'Đáp án: Turn right',
 'giv.10': 'Đáp án: A. It says ‘go straight’.',
 'giv.11': 'Đáp án: B. They’re hippos.',
 'giv.12': 'Đáp án: C. He’s dancing around the campfire.',
 'giv.13': 'Đáp án: B. Great! Let’s go.',
 'gv.14': 'Câu hỏi đúng: Do you want to go to the food stall?',
 'gv.15': 'Câu hỏi đúng: Why do you like crocodiles?',
 'gv.16': 'Câu hỏi đúng: What was the weather like last Monday?',
 'gvi.17': 'Đáp án: True (theo đáp án của đề).',
 'gvi.18': 'Đáp án: False (theo đáp án của đề).',
 'gvi.19': 'Đáp án: True (theo đáp án của đề).',
 'gvii.20': 'Đáp án: bookshop',
 'gvii.21': 'Đáp án: bakery',
 'gvii.22': 'Đáp án: water park',
 'gvii.23': 'Đáp án: gift shop',
 'gviii.24': 'Câu trả lời đúng: Because they run quickly.',
 'gviii.25': 'Câu trả lời đúng: They’re putting up a tent.',
 'gviii.26': 'Câu trả lời đúng: It says ‘turn right’.',
 'gviii.27': 'Câu trả lời đúng: It was cloudy.'}
