# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'A',
 'l1.2': 'B',
 'l1.3': 'C',
 'l1.4': 'B',
 'l2.5': {'blanks': [['4'], ['3'], ['1'], ['2']]},
 'l3.6': ['giraffes'],
 'l3.7': ['campsite'],
 'l3.8': ['card games'],
 'l3.9': ['cooking'],
 'r1.10': 'B',
 'r1.11': 'C',
 'r1.12': 'A',
 'r2.13': ['bookshop'],
 'r2.14': ['thousand'],
 'r2.15': ['ninety'],
 'r3.16': {'blanks': [['3'], ['4'], ['5'], ['2']]},
 'w1.17': ['in the evening'],
 'w1.18': ['cooks meals', 'cooks meal'],
 'w1.19': ['rainy'],
 'w1.20': ['tug of war'],
 'w2.21': ['When do you wash the dishes?'],
 'w2.22': ['My father goes to the sports centre on Saturdays.'],
 'w2.23': ['I like horses because they run quickly.'],
 'w3.24': ['I live at 84 Tran Hung Dao Street.'],
 'w3.25': ['Turn left and turn right to get to the hospital.'],
 'w3.26': ['The bookshop is near the gift shop.']}

EXPLANATIONS = {'l1.1': 'Đáp án: A (theo đáp án của đề).',
 'l1.2': 'Đáp án: B (theo đáp án của đề).',
 'l1.3': 'Đáp án: C (theo đáp án của đề).',
 'l1.4': 'Đáp án: B (theo đáp án của đề).',
 'l2.5': 'Theo đáp án của đề: she look like = 4; bakery = 3; he do = 1; weather = 2 (hội thoại “Where do you live?” là số 0).',
 'l3.6': 'giraffes = hươu cao cổ.',
 'l3.7': 'campsite = khu cắm trại.',
 'l3.8': 'card games = trò chơi bài.',
 'l3.9': 'help my mom with cooking = giúp mẹ nấu ăn.',
 'r1.10': 'Hỏi đường → Turn left and go straight.',
 'r1.11': 'Công → múa đẹp (dance beautifully).',
 'r1.12': 'Hỏi việc làm vào Chủ nhật → She goes to the cinema with her friends.',
 'r2.13': 'They go to the bookshop (mua đồ dùng học tập).',
 'r2.14': 'fifteen thousand dong.',
 'r2.15': 'ninety thousand dong.',
 'r3.16': 'Thứ tự đúng (theo đề): 2 – 5 – 1 – 3 – 4, tức: Hello Ben… → It says “Go straight” → Oh, ok. How can I get… → Go straight, turn left… → Thank you, '
          'Ben.',
 'w1.17': 'in the evening = vào buổi tối.',
 'w1.18': 'cooks meals = nấu ăn.',
 'w1.19': 'rainy = có mưa.',
 'w1.20': 'tug of war = kéo co.',
 'w2.21': 'Câu đúng: When do you wash the dishes?',
 'w2.22': 'Câu đúng: My father goes to the sports centre on Saturdays.',
 'w2.23': 'Câu đúng: I like horses because they run quickly.',
 'w3.24': 'Câu đúng: I live at 84 Tran Hung Dao Street.',
 'w3.25': 'Câu đúng: Turn left and turn right to get to the hospital.',
 'w3.26': 'Câu đúng: The bookshop is near the gift shop.'}
