# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u6-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['two', 'are', 'school.', 'buildings', 'There', 'at', 'our']},
                                  {'id': 't1.2',
                                   'o': ['How many gardens are there at your school?',
                                         'How many rooms are there at your school?',
                                         'How many playgrounds are there at your school?',
                                         'How many buildings are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Có bao nhiêu sân chơi ở trường của bạn?"',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['park', 'mountains', 'buildings', 'villages'],
                                   'plain': True,
                                   'q': 'My school is near a ____________.',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 4. A: How many gardens _____ at your school?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['big', 'playround', 'a', 'is', 'There', 'there.']},
                                  {'id': 't1.6',
                                   'o': ['Our school is near two cities.',
                                         'Our school is near two towns.',
                                         'Our school is near two mountains.',
                                         'Our school is near two villages.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là “Trường học của chúng tôi ở gần hai ngôi làng.”',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There ____________ a big computer room at our school.',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'sports', 'We', 'can', 'playground.', 'play', 'in']},
                                  {'id': 't1.9',
                                   'o': ['Our school is near two mountains.',
                                         'Our school is in the mountains.',
                                         'There are two mountains not far from my school.',
                                         'Our school is big.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là “Trường học của chúng tôi ở trên núi.”?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There ____________ two supermarkets not far from my school.',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['my', 'not', 'school.', 'from', 'are', 'far', 'two', 'villages', 'There']},
                                  {'id': 't1.12',
                                   'o': ['My school is in the village.',
                                         'There is a big playground at my school.',
                                         "It's Nguyen Du Primary School.",
                                         'I loved my school!'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What\'s the name of your school?"',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['What', 'When', 'Where', 'How'],
                                   'plain': True,
                                   'q': '____________ many gardens are there at your school?',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['my', 'school.', 'I', 'love']},
                                  {'id': 't1.15',
                                   'o': ['Where is your school?',
                                         'Where are you?',
                                         'How many buildings are there at your school?',
                                         "What's the name of your school?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về tên trường?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['How', 'When', 'Where', 'What'],
                                   'plain': True,
                                   'q': 'A: ____________ is your school, Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['There is a garden at her school.',
                                         "It's in the town.",
                                         'There are two computer rooms at his school.',
                                         'Nguyen Du Primary School.',
                                         'There is a playground at my school.'],
                                   'plain': True,
                                   'q': "Where's her school?",
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: Hi. I'm Minh. _____ is your school, Bill?",
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['is', 'the', 'name', 'your', 'of', 'school?', 'What']},
                                  {'id': 't1.20',
                                   'o': ['Where are you from?', 'Where are you?', 'Where is your school?', 'How many playgrounds are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi “Trường bạn ở đâu?”',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 6 – Our school facilities: Kiểm tra 3',
 'unit': 6}
