# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u10-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['Were you at the zoo last weekend?',
                                         "When's your sports day?",
                                         'Where were you last weekend?',
                                         'Is your sports day in April?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi có phải ai đó đã ở đâu đó trong thời gian vừa qua không?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ["It's in September.", 'Yes, I was.', 'I was in London.', 'Because I like it.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: When’s your sports day?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Cuối tuần vừa rồi bạn đã ở đâu?',
                                         'Hôm qua bạn đã ở đâu?',
                                         'Có phải hôm qua bạn ở sở thú không?',
                                         'Có phải cuối tuần vừa rồi bạn ở khu cắm trại không?'],
                                   'plain': True,
                                   'q': 'Câu “Where were you yesterday?” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ["Yes, I wasn't.", "No, I wasn't. I was at the campsite.", 'I was in the mountains.', 'No, I was.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Were you on the beach last weekend?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['Where were you last Sunday?', 'Were you at the zoo last Saturday?', 'Is it a big city?', "When's your sports day?"],
                                   'plain': True,
                                   'q': 'Câu “Yes, I was,” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['Where were you last summer?',
                                         'Were you in the countryside last weekend?',
                                         'Where were you last weekend?',
                                         'Where were you yesterday?'],
                                   'plain': True,
                                   'q': 'Câu “I was on the beach last weekend.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ["No, it isn't.", 'Yes, he was.', "No, I wasn't. I was on the beach last Sunday.", "No, they weren't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Were you at the campsite last Sunday?',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['Cuối tuần rồi bạn đã ở đâu?',
                                         'Hôm qua bạn đã ở đâu?',
                                         'Mùa hè vừa rồi bạn đã ở đâu?',
                                         'Có phải bạn ở miền quê không?'],
                                   'plain': True,
                                   'q': 'Câu “Where were you last summer" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['Were you in Tokyo last summer?',
                                         'Was I in Bangkok last summer?',
                                         'What do you do in Bangkok?',
                                         'Where were you last summer?'],
                                   'plain': True,
                                   'q': 'Câu “I was in Bangkok lat summer." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Cuối tuần rồi bạn đã ở bãi biển phải không?',
                                         'Hôm qua bạn đã ở sở thú phải không?',
                                         'Chủ nhật vừa rồi bạn đã ở bãi biển phải không?',
                                         'Hôm qua bạn ở bãi biển phải không? Bản word phát hành từ Tailieuchuan.vn'],
                                   'plain': True,
                                   'q': 'Câu “Were you on the beach yesterday?” có nghĩa là:',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1',
                                   'o': ['Are', 'Do', 'Was', 'Were'],
                                   'plain': True,
                                   'q': 'A: ______________you at the campsite yesterday?',
                                   't': 'mcq'},
                                  {'id': 'b.2', 'o': ['am', 'do', 'was', 'were'], 'plain': True, 'q': 'A: Where were you last summer?', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['What', 'Where', 'How', 'When'], 'plain': True, 'q': 'A: _____________ were you yesterday?', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['in', 'at', 'on', 'to'], 'plain': True, 'q': 'Were you _____________ the beach yesterday?', 't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['Where', 'What', 'When', 'How'],
                                   'plain': True,
                                   'q': 'A: _____________ were you last weekend?',
                                   't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['at', 'on', 'in', 'to'],
                                   'plain': True,
                                   'q': 'A: Were you _____________ the campsite yesterday?',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['today', 'tomorrow', 'last summer', 'next Sunday'],
                                   'plain': True,
                                   'q': 'A: Were you in the countryside _____________?',
                                   't': 'mcq'},
                                  {'id': 'b.8', 'o': ['am', 'was', 'were', 'are'], 'plain': True, 'q': 'A: Where were you last week, Mai?', 't': 'mcq'},
                                  {'id': 'b.9', 'o': ['are', 'is', 'was', 'were'], 'plain': True, 'q': 'A: Where _____________ Mai yesterday?', 't': 'mcq'},
                                  {'id': 'b.10', 'o': ['was', 'were', 'is', "isn't"], 'plain': True, 'q': 'A: Is Tokyo a big city?', 't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['Where were you yesterday?',
                                            'Were you on the beach last Sunday?',
                                            'What did you do last weekend?',
                                            'Was the food good?',
                                            'Is it a big city?'],
                                   'o': ['I play football.', 'Yes, it is.', 'I was at the zoo yesterday.', 'Yes, I was.', 'Yes, it was.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'},
                                  {'id': 'd.6', 'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'], 'plain': True, 'q': 'Chỗ trống (6):', 't': 'mcq'}],
                        'passage': "A: <b>(1)&nbsp;______</b> you in the countryside last weekend?<br>B: No, I wasn't.<br>A: <b>(2)&nbsp;______</b> were "
                                   'you?<br>B: I was on the beach.<br>A: <b>(3)&nbsp;______</b> did you do there?<br>B: I <b>(4)&nbsp;______</b> volleyball '
                                   'with my friends. How about you? Where were you last weekend?<br>A: I was in the mountains.<br>B: What '
                                   '<b>(5)&nbsp;______</b> you do there?<br>A: I <b>(6)&nbsp;______</b> a picture.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and choose the correct answers. (Đọc và chọn đáp án đúng.)',
                        'items': [{'id': 'e.1',
                                   'o': ['He was at the zoo.', 'He was on the beach.', 'He was in the countryside.', 'He was at the campsite.'],
                                   'plain': True,
                                   'q': 'Where was Minh last weekend?',
                                   't': 'mcq'},
                                  {'id': 'e.2',
                                   'o': ['It was busy.', 'It was cool.', 'It was peaceful.', 'It was beautiful.'],
                                   'plain': True,
                                   'q': 'How was the countryside?',
                                   't': 'mcq'},
                                  {'id': 'e.3',
                                   'o': ['He went fishing with his grandfather.',
                                         'He played football.',
                                         'He flied a kite with his cousin.',
                                         'He painted a picture of the countryside.'],
                                   'plain': True,
                                   'q': 'What did Minh do on Saturday morning?',
                                   't': 'mcq'},
                                  {'id': 'e.4',
                                   'o': ['He flied a kite with his cousin.', 'He played basketball.', 'He played football.', 'He played badminton.'],
                                   'plain': True,
                                   'q': 'What did Minh do on Saturday afternoon?',
                                   't': 'mcq'},
                                  {'id': 'e.5',
                                   'o': ['He went fishing with his cousin.',
                                         'He painted a picture of the countryside.',
                                         'He went fishing with his grandfather.',
                                         'He flied a kite.'],
                                   'plain': True,
                                   'q': 'What did Minh do on Sunday morning?',
                                   't': 'mcq'},
                                  {'id': 'e.6',
                                   'o': ['He painted a picture of a bird.',
                                         'He painted a picture of the countryside.',
                                         'He played badminton.',
                                         'He went fishing with his grandfather.'],
                                   'plain': True,
                                   'q': 'What did Minh do on Sunday evening?',
                                   't': 'mcq'}],
                        'passage': "Hello, everyone, I'm Minh. Last weekend, I was in the countryside. The countryside was peaceful. On Saturday morning, I "
                                   'flied a kite with my cousin. In the afternoon, I played badminton. On Sunday morning, I went fishing with my grandfather. '
                                   'In the evening, I painted a picture of the countryside. It was a happy weekend.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['you', 'Were', 'weekend?', 'on', 'the', 'beach', 'last']},
                                  {'id': 'f.2',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'was', 'I', 'at', 'No,', "wasn't.", 'I', 'zoo.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'summer?', 'last', 'Where', 'were']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'I', 'Bangkok', 'summer.', 'was', 'last']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Was', 'big', 'city?', 'it', 'a']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['did', 'there?', 'you', 'do', 'What']},
                                  {'id': 'f.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['a', 'hometown.', 'picture', 'painted', 'I', 'my', 'of']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['badminton', 'I', 'with', 'cousin.', 'my', 'played']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['yesterday?', 'you', 'were', 'Where']},
                                  {'id': 'f.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['at', 'was', 'the', 'campsite', 'yesterday.', 'I']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'},
           {'audio': True,
            'groups': [{'id': 'n',
                        'instr': 'Nghe file âm thanh và làm các câu theo số thứ tự trong bài nghe.',
                        'items': [{'id': 'n.1',
                                   'o': ['city', 'mountains', 'countryside'],
                                   'plain': True,
                                   'q': 'Câu 1. I was in the _________________ last weekend.',
                                   't': 'mcq'},
                                  {'id': 'n.2',
                                   'o': ['mountains', 'town', 'countryside'],
                                   'plain': True,
                                   'q': 'Câu 2. I was in the ________________.',
                                   't': 'mcq'},
                                  {'id': 'n.3', 'q': 'Câu 3. Where were you last summer?- I was in {_}', 't': 'fill'},
                                  {'id': 'n.4', 'q': 'Câu 4. Where were you last summer?- I was in {_}', 't': 'fill'},
                                  {'id': 'n.5',
                                   'o': ['Tokyo', 'Sydney', 'Bangkok'],
                                   'plain': True,
                                   'q': 'Câu 5. Where were you last summer?- I was in_____________.',
                                   't': 'mcq'},
                                  {'id': 'n.6',
                                   'o': ['Bangkok', 'London', 'Sydney'],
                                   'plain': True,
                                   'q': 'Câu 6. Where were you last summer?- I was in_____________.',
                                   't': 'mcq'},
                                  {'id': 'n.7', 'q': 'Câu 7. Were you at the {_} at weekend?', 't': 'fill'},
                                  {'id': 'n.8', 'q': 'Câu 8. Were you at the {_} at weekend? - Yes, I was.', 't': 'fill'},
                                  {'id': 'n.9',
                                   'o': ['Where were you last summer?', 'Where were you last weekend?'],
                                   'plain': True,
                                   'q': 'Câu 9. Nghe và chọn đáp án đúng.',
                                   't': 'mcq'},
                                  {'id': 'n.10',
                                   'o': ['Were you on the beach last summer?', 'Were you at the campsite last summer?'],
                                   'plain': True,
                                   'q': 'Câu 10. Nghe và chọn đáp án đúng.',
                                   't': 'mcq'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Luyện nghe'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi ai đó đã ở đâu trong quá khứ và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           'lời</td></tr><tr><td>Where were you + (time in the past)?<br>Bạn đã ở đâu + (thời gian trong quá khứ)?</td><td>I was + at/in/on '
           '+...(place).<br>Tôi ở + (địa điểm).</td></tr><tr><td>Where was she/he + (time in the past)?<br>Cô ấy/Cậu ấy đã ở đâu + (thời gian trong quá '
           'khứ)?</td><td>She/He was + at/in/on +... (place).<br>Cô ấy/Cậu ấy đã ở + (địa điểm).</td></tr><tr><td>Ví dụ:<br>A: Where were you yesterday? Hôm '
           'qua bạn đã ở đâu?<br>B: I was at the zoo. Tôi ở sở thú.<br>A: Where was he last summer? Mùa hè vừa rồi cậu ấy đã ở đâu?<br>B: He was in Bangkok. '
           'Cậu ấy ở Bangkok.</td></tr></table><p>2. Cách hỏi xem có phải ai đó đã ở một địa điểm nào đó trong quá khứ hay không và cách trả lời:</p><table '
           'class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>Were you + on/at/in + (place) + (time in the past)?<br>Có phải bạn đã ở... (địa '
           'điểm) + (thời gian trong quá khứ) không?</td><td>Yes, I was. Vâng, đúng vậy.<br>No, I wasn’t. Không, không phải.</td></tr><tr><td>Was she/he + '
           'on/at/in + (place) + (time in the past)?<br>Có phải cô ấy/cậu ấy đã ở … (địa điểm) + (thời gian trong quá khứ) không?</td><td>Yes, she/he was. '
           'Vâng, đúng vậy.<br>No, she/he wasn’t. Không, không phải.</td></tr><tr><td>Ví dụ:<br>A: Were you at the campsite last weekend?<br>Cuối tuần rồi bạn '
           "đã ở khu cắm trại phải không?<br>B: No, I wasn't. Không phải.<br>A: Was she on the beach yesterday?<br>Hôm qua cô ấy ở bãi biển phải không?<br>B: "
           'Yes, she was. Vâng, đúng rồi.</td></tr></table><p>3. Cách hỏi ai đó đã làm gì trong quá khứ và cách trả lời:</p><table class="tb"><tr><td>Cách '
           'hỏi</td><td>Cách trả lời</td></tr><tr><td>What did you/she/he do + (time in the past)?<br>Bạn/Cô ấy/Cậu ấy đã làm gì + (thời gian trong quá '
           'khứ)?</td><td>I + V-ed...<br>Tôi đã …</td></tr><tr><td>Ví dụ:<br>A: What did you do last Sunday? Chủ nhật vừa rồi bạn đã làm gì?<br>B: I played '
           'football. Mình chơi bóng đá.<br>A: What did she do yesterday? Hôm qua cô ấy đã làm gì?<br>B: She painted a picture. Cô ấy đã tô màu bức '
           'tranh.</td></tr></table>',
 'title': 'Unit 10 – Our summer holidays: Luyện tập',
 'unit': 10}
