# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r4-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What are those animals?',
                                         'Why do you like those animals?',
                                         'What animals dance beautifully?',
                                         'What animals do you want to see?'],
                                   'plain': True,
                                   'q': 'Câu: “They are hippos" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['What', 'Where', 'When', 'Why'],
                                   'plain': True,
                                   'q': 'A: ____________ do you like peacocks?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['look', 'hippos', 'Minh', 'strong.', 'they', 'because', 'likes']},
                                  {'id': 't1.4',
                                   'o': ["They're giraffes.", 'Because they run quickly.', 'Because they roar loudly.', 'Because they look strong.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like giraffes?”',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['because', 'because it', 'because they', 'because that'],
                                   'plain': True,
                                   'q': "She doesn't like lions ____________ roar loudly.",
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['likes', 'they', 'birds', 'because', 'merrily.', 'Lucy', 'sing']},
                                  {'id': 't1.7',
                                   'o': ['This is Lan.', "She's at the campsite.", 'Yes, she is.', "She's telling a story."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What is Lan doing?”?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['he is', 'he does', 'they are', 'they do'],
                                   'plain': True,
                                   'q': 'A: Are Bill and Ben at the campsite?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Bill', 'and', 'Ben', 'doing,', 'are', 'Mary?', 'What']},
                                  {'id': 't1.10',
                                   'o': ["She's building a campfire.", "He's taking photos.", 'They are at the campsite.', 'They are playing badminton.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What is Mike doing?”?',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'o': ['doing', 'singing', 'building', 'telling'],
                                   'plain': True,
                                   'q': 'A: Where are Mary and Lucy?',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['war.', 'They', 'of', 'are', 'playing', 'tug']},
                                  {'id': 't1.13',
                                   'o': ['What was the weather like yesterday?',
                                         'What does your brother loook like?',
                                         'Where do you go on Sundays?',
                                         'Do you want to go to the supermarket?'],
                                   'plain': True,
                                   'q': 'Câu “It was rainy.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['What', 'Where', 'How', 'When'],
                                   'plain': True,
                                   'q': 'A: (1) ______________ was the weather like yesterday?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ["It's two hundred thousand dong.",
                                         'It was rainy.',
                                         'They are building a campfire.',
                                         'Because they are funny.',
                                         'Turn right and go straight.'],
                                   'plain': True,
                                   'q': 'What was the weather like last Saturday, Lan?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['like', 'judo', 'Where', 'Are', 'between'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. A: Hi, Ben. _____ were you last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['weekend,', 'you', 'were', 'last', 'Where', 'Linh?']},
                                  {'id': 't1.18',
                                   'o': ['What was the weather like in Da Lat?',
                                         'What was the weather like in Da Lat last weekend?',
                                         'Do you want to go to Da Lat?',
                                         'It was sunny in Da Lat.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Cuối tuần trước thời tiết ở Đà Lạt như thế nào?”',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['bakery', 'food stall', 'bookshop', 'pet shop'],
                                   'plain': True,
                                   'q': 'A: Do you want to go to the ______________ with me?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ["It's two hundred thousand dong.",
                                         'It was rainy.',
                                         'They are building a campfire.',
                                         'Because they are funny.',
                                         'Turn right and go straight.'],
                                   'plain': True,
                                   'q': 'How can I get to the zoo?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Review 4: Kiểm tra 3',
 'unit': 'Review4'}
