# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "She's at the campsite.",
 't1.10': 'Họ đang nhảy múa quanh lửa trại.',
 't1.11': 'telling',
 't1.12': ['They are building a campfire.'],
 't1.13': 'What is he doing?',
 't1.14': 'is',
 't1.15': 'They are at the campsite.',
 't1.16': 'Are',
 't1.17': ['Where are Bill and his friends?'],
 't1.18': "Where's Nam?",
 't1.19': 'What',
 't1.2': "isn't",
 't1.20': 'They are playing tug of war.',
 't1.3': ['Nam and his friends are playing tug of war.'],
 't1.4': "They're putting up a tent.",
 't1.5': 'playing',
 't1.6': ['Are Mai and Lan singing songs?'],
 't1.7': 'They are building a campfire.',
 't1.8': 'taking',
 't1.9': ['What are the boys doing?']}

EXPLANATIONS = {'t1.1': "Đáp án: She's at the campsite.",
 't1.10': 'Đáp án: Họ đang nhảy múa quanh lửa trại.',
 't1.11': 'Đáp án: telling',
 't1.12': 'Câu đúng: They are building a campfire.',
 't1.13': 'Đáp án: What is he doing?',
 't1.14': 'Đáp án: is',
 't1.15': 'Đáp án: They are at the campsite.',
 't1.16': 'Đáp án: Are',
 't1.17': 'Câu đúng: Where are Bill and his friends?',
 't1.18': "Đáp án: Where's Nam?",
 't1.19': 'Đáp án: What',
 't1.2': "Đáp án: isn't",
 't1.20': 'Đáp án: They are playing tug of war.',
 't1.3': 'Câu đúng: Nam and his friends are playing tug of war.',
 't1.4': "Đáp án: They're putting up a tent.",
 't1.5': 'Đáp án: playing',
 't1.6': 'Câu đúng: Are Mai and Lan singing songs?',
 't1.7': 'Đáp án: They are building a campfire.',
 't1.8': 'Đáp án: taking',
 't1.9': 'Câu đúng: What are the boys doing?'}
