# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk1-nghe4',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'q1',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q1.1', 'o': ['jam', 'juice', 'party'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q1.2', 'o': ['jam', 'juice', 'party'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q1.3', 'o': ['jam', 'juice', 'party'], 'q': 'Nghe câu số 3.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_nghe4/p1.png" alt="Hình">'},
                       {'id': 'q2',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q2.4', 'o': ['birthday party', 'May', 'chips'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q2.5', 'o': ['birthday party', 'May', 'chips'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q2.6', 'o': ['birthday party', 'May', 'chips'], 'q': 'Nghe câu số 3.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_nghe4/p2.png" alt="Hình">'},
                       {'id': 'q3',
                        'instr': 'Listen And Write (nghe và điền từ)',
                        'items': [{'id': 'q3.7', 'q': 'He can {_}.', 't': 'fill'},
                                  {'id': 'q3.8', 'q': "But he can't {_}.", 't': 'fill'},
                                  {'id': 'q3.9', 'q': 'I get up at five {_}.', 't': 'fill'},
                                  {'id': 'q3.10', 'q': 'On Fridays, I {_} at school.', 't': 'fill'}]},
                       {'id': 'q4',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q4.11', 'o': ["No, he can't.", 'Yes, he can.'], 'q': 'Can he ride a bike?', 't': 'mcq'},
                                  {'id': 'q4.12',
                                   'o': ['I listen to music.', 'I do housework.', 'I study at school.'],
                                   'q': 'What do you do on Mondays?',
                                   't': 'mcq'}]},
                       {'id': 'q5',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q5.13', 'o': ['picture A', 'picture B', 'picture C'], 'q': 'Nghe và chọn đáp án đúng.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_nghe4/p5.png" alt="Hình">'},
                       {'id': 'q6',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q6.14', 'o': ['picture A', 'picture B', 'picture C'], 'q': 'Nghe và chọn đáp án đúng.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_nghe4/p6.png" alt="Hình">'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 1 – Luyện nghe phần 4',
 'unit': 'GiuaKy1'}
