# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'gi.1': 'a',
 'gi.2': 'd',
 'gi.3': 'b',
 'gi.4': 'c',
 'gii.5': {'blanks': [['b'], ['d'], ['c'], ['a']]},
 'giii.6': ['September'],
 'giii.7': ['gardens'],
 'giii.8': ['music'],
 'giii.9': ['Sydney'],
 'giv.10': 'B',
 'giv.11': 'A',
 'giv.12': 'C',
 'giv.13': 'B',
 'gv.14': 'F',
 'gv.15': 'T',
 'gv.16': 'T',
 'gvi.17': ['What’s your favourite subject?'],
 'gvi.18': ['Where were you yesterday?'],
 'gvi.19': ['How many computer rooms are there (at your school)?', 'How many computer rooms are there?', 'How many computer rooms are there at your school?'],
 'gvii.20': ['swim'],
 'gvii.21': ['sandcastle'],
 'gvii.22': ['ball'],
 'gvii.23': ['lemonade'],
 'gviii.24': ['My sports day is in March.'],
 'gviii.25': ['How many buildings are there at your school?'],
 'gviii.26': ['I have music on Tuesdays.'],
 'gviii.27': ['Where were you last summer?']}

EXPLANATIONS = {'gi.1': 'Câu 1 ứng với tranh a (theo đáp án của đề).',
 'gi.2': 'Câu 2 ứng với tranh d (theo đáp án của đề).',
 'gi.3': 'Câu 3 ứng với tranh b (theo đáp án của đề).',
 'gi.4': 'Câu 4 ứng với tranh c (theo đáp án của đề).',
 'gii.5': 'Đáp án theo đáp án của đề: 1–b, 2–d, 3–c, 4–a',
 'giii.6': 'Đáp án: September',
 'giii.7': 'Đáp án: gardens',
 'giii.8': 'Đáp án: music',
 'giii.9': 'Đáp án: Sydney',
 'giv.10': 'Đáp án: B. I have it on Tuesdays.',
 'giv.11': 'Đáp án: A. It’s in the village.',
 'giv.12': 'Đáp án: C. Because I want to be a maths teacher.',
 'giv.13': 'Đáp án: B. Yes, I was.',
 'gv.14': 'Đáp án: False (theo đáp án của đề).',
 'gv.15': 'Đáp án: True (theo đáp án của đề).',
 'gv.16': 'Đáp án: True (theo đáp án của đề).',
 'gvi.17': 'Câu hỏi đúng: What’s your favourite subject?',
 'gvi.18': 'Câu hỏi đúng: Where were you yesterday?',
 'gvi.19': 'Câu hỏi đúng: How many computer rooms are there (at your school)?',
 'gvii.20': 'Đáp án: swim',
 'gvii.21': 'Đáp án: sandcastle',
 'gvii.22': 'Đáp án: ball',
 'gvii.23': 'Đáp án: lemonade',
 'gviii.24': 'Câu đúng: My sports day is in March.',
 'gviii.25': 'Câu đúng: How many buildings are there at your school?',
 'gviii.26': 'Câu đúng: I have music on Tuesdays.',
 'gviii.27': 'Câu đúng: Where were you last summer?'}
