# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'How can she get to the shopping centre?',
 't1.10': 'Có một trung tâm thể thao ở đường Nguyễn Trãi.',
 't1.11': 'Turn',
 't1.12': ['Thank you very much for your help.'],
 't1.13': 'What does it say?',
 't1.14': 'bookshop',
 't1.15': "I'm at the shopping centre.",
 't1.16': 'Turn',
 't1.17': ['How can I get to the sports centre?'],
 't1.18': 'How can I get to the bookshop?',
 't1.19': 'How',
 't1.2': 'food stall',
 't1.20': 'Go straight and turn right.',
 't1.3': ['There is a bakery in Nguyen Thai Son Street.'],
 't1.4': 'What does he want to buy at the bookshop?',
 't1.5': 'cinema',
 't1.6': ['How can we get to the campsite?'],
 't1.7': 'Quay vòng lại.',
 't1.8': 'food stall',
 't1.9': ['Go straight and you will see the campsite on the left.']}

EXPLANATIONS = {'t1.1': 'Đáp án: How can she get to the shopping centre?',
 't1.10': 'Đáp án: Có một trung tâm thể thao ở đường Nguyễn Trãi.',
 't1.11': 'Đáp án: Turn',
 't1.12': 'Câu đúng: Thank you very much for your help.',
 't1.13': 'Đáp án: What does it say?',
 't1.14': 'Đáp án: bookshop',
 't1.15': "Đáp án: I'm at the shopping centre.",
 't1.16': 'Đáp án: Turn',
 't1.17': 'Câu đúng: How can I get to the sports centre?',
 't1.18': 'Đáp án: How can I get to the bookshop?',
 't1.19': 'Đáp án: How',
 't1.2': 'Đáp án: food stall',
 't1.20': 'Đáp án: Go straight and turn right.',
 't1.3': 'Câu đúng: There is a bakery in Nguyen Thai Son Street.',
 't1.4': 'Đáp án: What does he want to buy at the bookshop?',
 't1.5': 'Đáp án: cinema',
 't1.6': 'Câu đúng: How can we get to the campsite?',
 't1.7': 'Đáp án: Quay vòng lại.',
 't1.8': 'Đáp án: food stall',
 't1.9': 'Câu đúng: Go straight and you will see the campsite on the left.'}
