# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u18-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['two', 'are', 'dong.', 'hundred', 'forty', 'and', 'thousand', 'They']},
                                  {'id': 't1.2',
                                   'o': ['Tiệm bánh mì đối diện hiệu sách và cửa hàng thú cưng.',
                                         'Tiệm bánh mì ở gần hiệu sách và cửa hàng thú cưng.',
                                         'Tiệm bánh mì ở giữa hiệu sách và cửa hàng thú cứng.',
                                         'Tiệm bánh mì ở đằng sau hiệu sách và cửa hàng thú cứng.'],
                                   'plain': True,
                                   'q': 'Câu “The bakery is between the bookshop and the pet shop” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['next', 'between', 'in front', 'opposite'],
                                   'plain': True,
                                   'q': 'A: Where is the gift shop?',
                                   't': 'mcq'},
                                  {'id': 't1.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['that', 'shirt?', 'much', 'How', 'is']},
                                  {'id': 't1.5',
                                   'o': ['Trung tâm thể thao ở gần trung tâm mua sắm.',
                                         'Trung tâm thể thao ở đằng sau trung tâm mua sắm.',
                                         'Trung tâm thể thao đối diện trung tâm mua sắm.',
                                         'Trung tâm thể thao ở giữa trung tâm mua sắm.'],
                                   'plain': True,
                                   'q': 'Câu “The sports centre is opposite the shopping centre." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: How much _________ those dolls?', 't': 'mcq'},
                                  {'id': 't1.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['It', 'dong.', 'five', 'hundred', 'is', 'thousand']},
                                  {'id': 't1.8',
                                   'o': ['How much is the skirt?', 'How much is the T-shirt?', 'How much is the shirt?', 'How much are the pants?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi giá tiền của áo sơ mi?',
                                   't': 'mcq'},
                                  {'id': 't1.9', 'o': ['on', 'in', 'over', 'at'], 'plain': True, 'q': 'A: Where is the bookshop?', 't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['school', 'that', 'How', 'is', 'much', 'bag?']},
                                  {'id': 't1.11',
                                   'o': ["It's thirty thousand dong.",
                                         'They are two hundred thousand dong.',
                                         'They are over there.',
                                         "It's opposite the gift shop."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “How much are the hats?”',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['next', 'near', 'between', 'in'], 'plain': True, 'q': "A: Where's the bakery?", 't': 'mcq'},
                                  {'id': 't1.13',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['thousand', 'It', 'NHỚ', 'GHI', 'is', 'dong.', 'eighty']},
                                  {'id': 't1.14',
                                   'o': ['What does it say?', 'How can I get to the sports centre?', "Where's the bookshop?", 'How much is the T-shirt?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về địa điểm?',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'o': ['What', 'How', 'How much', 'When'], 'plain': True, 'q': 'A: ___________ is that skirt?', 't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ["It's near the gift shop.",
                                         'Go straight and turn left at the corner.',
                                         "It's ninety thousand dong.",
                                         "Great! Let's go.",
                                         "They're one hundred and ninety thousand dong."],
                                   'plain': True,
                                   'q': 'How much is the skirt?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['between', 'those', 'over there', 'it', 'get', 'near'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. A: Excuse me, is there a shopping centre _____ here?',
                                   't': 'mcq'},
                                  {'id': 't1.18', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['shop?', 'Where', 'pet', 'is', 'the']},
                                  {'id': 't1.19',
                                   'o': ['How much is the skirt?', 'How many skirts are there?', "Where's the gift shop?", 'How can I get to the gift shop?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về giá cả?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'o': ['It', "It's", 'They', "They're"], 'plain': True, 'q': 'A: How much are these pants?', 't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 18 – At the shopping centre: Kiểm tra 3',
 'unit': 18}
