# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': "Let's go to the water park.",
 'a.10': 'Đó là một ngày mưa.',
 'a.2': 'What was the weather like last Sunday?',
 'a.3': 'Do you want to go to the shopping centre?',
 'a.4': 'It was rainy.',
 'a.5': 'Do you want to go to the bakery?',
 'a.6': "Sorry, I can't. I'm doing my homework.",
 'a.7': 'It was sunny.',
 'a.8': 'What was the weather like in Sa Pa last weekend?',
 'a.9': 'Chúng ta hãy đi đến trung tâm mua sắm nhé.',
 'b.1': 'was',
 'b.10': 'was',
 'b.2': 'was',
 'b.3': 'Do',
 'b.4': 'weather',
 'b.5': 'bakery',
 'b.6': 'bookshop',
 'b.7': 'sunny',
 'b.8': 'were',
 'b.9': 'was',
 'c.1': {'blanks': [['I was in Da Nang.'], ['It was sunny.'], ["Great! Let's go."], ['I want to buy some books.'], ['It is cloudy.']]},
 'd.1': 'Where',
 'd.2': 'food stall',
 'd.3': 'bookshop',
 'd.4': 'was',
 'd.5': "can't",
 'e.1': 'rainy',
 'e.2': 'sunny',
 'e.3': 'bookshop',
 'e.4': 'bakery',
 'e.5': 'some sausages',
 'e.6': 'some bread',
 'e.7': 'some notebooks',
 'f.1': ['Where were you last weekend?'],
 'f.10': ['Do you want to go to the water park with me?'],
 'f.2': ['I was in Hue last weekend.'],
 'f.3': ['What was the weather like in Long An yesterday?'],
 'f.4': ['It was rainy and cold yesterday.'],
 'f.5': ['What is the weather like in Da Nang today?'],
 'f.6': ['It is sunny today.'],
 'f.7': ['We want to buy some food.'],
 'f.8': ['Mai wants to buy some books.'],
 'f.9': ['Nam is at the shopping centre.']}

EXPLANATIONS = {'a.1': "Đáp án: Let's go to the water park.",
 'a.10': 'Đáp án: Đó là một ngày mưa.',
 'a.2': 'Đáp án: What was the weather like last Sunday?',
 'a.3': 'Đáp án: Do you want to go to the shopping centre?',
 'a.4': 'Đáp án: It was rainy.',
 'a.5': 'Đáp án: Do you want to go to the bakery?',
 'a.6': "Đáp án: Sorry, I can't. I'm doing my homework.",
 'a.7': 'Đáp án: It was sunny.',
 'a.8': 'Đáp án: What was the weather like in Sa Pa last weekend?',
 'a.9': 'Đáp án: Chúng ta hãy đi đến trung tâm mua sắm nhé.',
 'b.1': 'Đáp án: was',
 'b.10': 'Đáp án: was',
 'b.2': 'Đáp án: was',
 'b.3': 'Đáp án: Do',
 'b.4': 'Đáp án: weather',
 'b.5': 'Đáp án: bakery',
 'b.6': 'Đáp án: bookshop',
 'b.7': 'Đáp án: sunny',
 'b.8': 'Đáp án: were',
 'b.9': 'Đáp án: was',
 'c.1': 'Where were you last Saturday? → I was in Da Nang.; What was the weather like last Saturday? → It was sunny.; Do you want to go to the bookshop? → '
        "Great! Let's go.; What do you want to buy? → I want to buy some books.; What is the weather like today? → It is cloudy.",
 'd.1': 'Đáp án: Where',
 'd.2': 'Đáp án: food stall',
 'd.3': 'Đáp án: bookshop',
 'd.4': 'Đáp án: was',
 'd.5': "Đáp án: can't",
 'e.1': 'Đáp án: rainy',
 'e.2': 'Đáp án: sunny',
 'e.3': 'Đáp án: bookshop',
 'e.4': 'Đáp án: bakery',
 'e.5': 'Đáp án: some sausages',
 'e.6': 'Đáp án: some bread',
 'e.7': 'Đáp án: some notebooks',
 'f.1': 'Câu đúng: Where were you last weekend?',
 'f.10': 'Câu đúng: Do you want to go to the water park with me?',
 'f.2': 'Câu đúng: I was in Hue last weekend.',
 'f.3': 'Câu đúng: What was the weather like in Long An yesterday?',
 'f.4': 'Câu đúng: It was rainy and cold yesterday.',
 'f.5': 'Câu đúng: What is the weather like in Da Nang today?',
 'f.6': 'Câu đúng: It is sunny today.',
 'f.7': 'Câu đúng: We want to buy some food.',
 'f.8': 'Câu đúng: Mai wants to buy some books.',
 'f.9': 'Câu đúng: Nam is at the shopping centre.'}
