# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck1-de17',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'a1',
                        'instr': 'I. Listen and tick (nghe và chọn tranh đúng).',
                        'items': [{'id': 'a1.1', 'img': 'a1_1.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.2', 'img': 'a1_2.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.3', 'img': 'a1_3.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.4',
                                   'img': 'a1_4.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'a2',
                        'instr': 'II. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'a2.5', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.6', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.7', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.8', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de17/a2.png" alt="Tranh A-D">'},
                       {'id': 'a3',
                        'instr': 'III. Listen and tick or cross (nghe, nội dung nghe có khớp với tranh không?).',
                        'items': [{'id': 'a3.9', 'img': 'a3_1.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'},
                                  {'id': 'a3.10', 'img': 'a3_2.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'}]},
                       {'id': 'a4',
                        'instr': 'IV. Listen and write (nghe và điền từ).',
                        'items': [{'id': 'a4.11', 'q': 'A: Where’s he from?<br>B: He’s from {_}.', 't': 'fill'},
                                  {'id': 'a4.12', 'q': 'A: What subjects do you have today?<br>B: I have {_}.', 't': 'fill'}]},
                       {'id': 'b1',
                        'instr': 'I. Look, read and write true (T) or false (F).',
                        'items': [{'id': 'b1.13', 'img': 'b1_1.png', 'q': 'A: Where were you last weekend? B: I was on the beach.', 't': 'tf'},
                                  {'id': 'b1.14', 'img': 'b1_2.png', 'q': 'My favourite subject is English. I want to be an English teacher.', 't': 'tf'},
                                  {'id': 'b1.15', 'img': 'b1_3.png', 'q': 'My school is in the city.', 't': 'tf'},
                                  {'id': 'b1.16', 'img': 'b1_4.png', 'q': 'A: What time do you go to school? B: I go to school at six thirty.', 't': 'tf'},
                                  {'id': 'b1.17', 'img': 'b1_5.png', 'q': 'My friend is from America.', 't': 'tf'}]},
                       {'id': 'b2',
                        'instr': 'II. Read and complete the sentences (đọc đoạn văn và điền từ).',
                        'items': [{'id': 'b2.18', 'q': 'Bao’s school is in the {_}.', 't': 'fill'},
                                  {'id': 'b2.19', 'q': 'He gets up at {_}.', 't': 'fill'},
                                  {'id': 'b2.20', 'q': 'Bao’s favourite subject is {_}.', 't': 'fill'},
                                  {'id': 'b2.21', 'q': 'Bao wants to be a(n) {_}.', 't': 'fill'},
                                  {'id': 'b2.22', 'q': 'Mai’s favourite subject is music. She wants to be a(n) {_}.', 't': 'fill'}],
                        'passage': '<p>Hi! My name is Bao. I’m ten years old and I am a student at a primary school. My school is in the village and it is '
                                   'near my house. Everyday, I often get up at six o’clock. After breakfast, I ride my bike to school at six forty – five. I '
                                   'have many subjects at school, but my favourite subject is English. I want to be an English teacher. Mai is my best friend '
                                   'in my class. Her favourite subject is music, because she wants to be a singer.</p>'},
                       {'id': 'c1',
                        'instr': 'I. Look and complete (nhìn tranh, điền từ).',
                        'items': [{'id': 'c1.23', 'img': 'c1_1.png', 'q': 'I {_} at 9.30.', 't': 'fill'},
                                  {'id': 'c1.24', 'img': 'c1_2.png', 'q': 'Last Sunday, I was {_}.', 't': 'fill'},
                                  {'id': 'c1.25', 'img': 'c1_3.png', 'q': 'There are three {_} at my school.', 't': 'fill'},
                                  {'id': 'c1.26', 'img': 'c1_4.png', 'q': 'I like art, because I want to be a {_}.', 't': 'fill'},
                                  {'id': 'c1.27', 'img': 'c1_5.png', 'q': 'A: What do you want to drink?<br>B: I want some {_}.', 't': 'fill'}]},
                       {'id': 'c2',
                        'instr': 'Reorder the words (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'c2.28', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['yesterday?', 'were', 'Where', 'you']},
                                  {'id': 'c2.29', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['on', 'Sundays.', 'I', 'listen', 'music', 'to']},
                                  {'id': 'c2.30', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['music', 'have', 'I', 'on', 'Thursdays.']},
                                  {'id': 'c2.31',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['six', 'forty-five.', 'breakfast', 'at', 'I', 'have']},
                                  {'id': 'c2.32', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['subject', 'is', 'My', 'favourite', 'maths.']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 1 – Đề 17 (25-26)',
 'unit': 'CuoiKy1'}
