# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de15',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and match (nghe và nối số với tranh). Ví dụ: 0 – d.',
                        'items': [{'id': 'l1.1',
                                   'left': [{'t': 'Nghe câu số 1'}, {'t': 'Nghe câu số 2'}, {'t': 'Nghe câu số 3'}, {'t': 'Nghe câu số 4'}],
                                   'o': ['a', 'b', 'c', 'd', 'e'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de15/l1.png" alt="Tranh">'},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and circle the correct answer (nghe và chọn đáp án đúng). Ví dụ: 0. A. It was cloudy.',
                        'items': [{'id': 'l2.2', 'o': ['She goes to the shopping center.', 'She goes to the zoo.'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'l2.3', 'o': ['She has big ears.', 'She has long hair.'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'l2.4',
                                   'o': ['The skirt is sixty thousand dong.', 'The skirt is eighty thousand dong.'],
                                   'q': 'Nghe câu số 3.',
                                   't': 'mcq'},
                                  {'id': 'l2.5', 'o': ['The mother is a nurse.', 'The mother is a farmer.'], 'q': 'Nghe câu số 4.', 't': 'mcq'}]},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen and write the missing words (nghe và điền từ). Ví dụ: I watch TV in the afternoon.',
                        'items': [{'id': 'l3.6', 'q': 'A: How can I get to the cinema?<br>B: {_}.', 't': 'fill'},
                                  {'id': 'l3.7', 'q': 'A: What does he {_}?<br>B: He’s big.', 't': 'fill'},
                                  {'id': 'l3.8', 'q': 'A: Where does he work?<br>B: He works {_}.', 't': 'fill'},
                                  {'id': 'l3.9', 'q': 'A: What are these animals?<br>B: These are {_}.', 't': 'fill'}]},
                       {'id': 'r1',
                        'instr': 'Question 4. Look, read and put a tick in the box (nhìn tranh, đọc và chọn tranh đúng). Ví dụ: What does it say? – It says '
                                 '“Turn right” → c.',
                        'items': [{'id': 'r1.10',
                                   'img': 'r1_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'What was the weather like last weekend? – It’s cloudy.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r1.11',
                                   'img': 'r1_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'What does your sister look like? – She is tall.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r1.12',
                                   'img': 'r1_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Where’s the bookshop? – It’s behind the bakery.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r1.13',
                                   'img': 'r1_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Why do you like peacocks? – Because they dance beautifully.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r1.14',
                                   'img': 'r1_5.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'What does she do on Sundays? – She does yoga.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'bank': ['opposite', 'thousand', 'merrily', 'wants', 'shopping centre', 'sunny'],
                        'id': 'r2',
                        'instr': 'Question 5. Read and complete using words in the box (chọn từ trong khung). Ví dụ: (0) sunny.',
                        'items': [{'id': 'r2.15', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.17', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r2.18', 'q': 'Chỗ trống (4): {_}', 't': 'fill'},
                                  {'id': 'r2.19', 'q': 'Chỗ trống (5): {_}', 't': 'fill'}],
                        'passage': '<p>Today is Sunday. It’s (0) <b>sunny</b>. My mum and I are going to the <b>(1) ______</b>. It is <b>(2) ______</b> the '
                                   'swimming pool. My mum <b>(3) ______</b> to buy some food. I go there to buy some books about wildlife, especially the '
                                   'birds because they sing <b>(4) ______</b>. The books are eighty-eight <b>(5) ______</b> dong. I’m happy to have new '
                                   'books.</p>'},
                       {'id': 'r3',
                        'instr': 'Question 6. Order the letters (sắp xếp chữ cái thành từ, nhìn tranh). Ví dụ: s h t o r → short.',
                        'items': [{'id': 'r3.20', 'img': 'r3_1.png', 'q': 'b a r y k e → {_}', 't': 'fill'},
                                  {'id': 'r3.21', 'img': 'r3_2.png', 'q': 'f m e a r r → {_}', 't': 'fill'},
                                  {'id': 'r3.22', 'img': 'r3_3.png', 'q': 'u r t n e f t l → {_}', 't': 'fill'},
                                  {'id': 'r3.23', 'img': 'r3_4.png', 'q': 'c l e r o d I o c s → {_}', 't': 'fill'},
                                  {'id': 'r3.24', 'img': 'r3_5.png', 'q': 'r n d o u → {_}', 't': 'fill'}]},
                       {'id': 'w1',
                        'instr': 'Question 7. Rearrange the words to make complete sentences (sắp xếp từ thành câu đúng). Ví dụ: She goes to the shopping '
                                 'centre on Saturdays.',
                        'items': [{'id': 'w1.25', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'do', 'When', 'TV?', 'watch']},
                                  {'id': 'w1.26',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['food', 'store?', 'go', 'to', 'to', 'you', 'the', 'want', 'Do']},
                                  {'id': 'w1.27',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['to', 'the', 'can', 'I', 'How', 'supermarket?', 'get']},
                                  {'id': 'w1.28',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['at', 'is', 'She', 'campsite.', 'campfire', 'a', 'the', 'building']},
                                  {'id': 'w1.29',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'shop', 'bookshop', 'is', 'The', 'shop.', 'and', 'sports', 'the', 'gift', 'between']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 15',
 'unit': 'OnHK2'}
