# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u19-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['running', 'giraffes', 'are', 'Those', 'quickly.']},
                                  {'id': 't1.2',
                                   'o': ["They're peacocks.", 'Because they run quickly.', 'Because they roar loudly.', 'Because they dance beautifully.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like peacocks?”',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['because it', 'because they', 'because', 'because that'],
                                   'plain': True,
                                   'q': 'I like peacocks __________ dance beautifully.',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['I want to see giraffes.',
                                         'They are lions.',
                                         'He wants to see hippos.',
                                         'Because they are scary.',
                                         'Because they dance beautifully.'],
                                   'plain': True,
                                   'q': 'What animals do you want to see?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: _____ do you like peacocks?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['roaring', 'lions', 'are', 'loudly.', 'Those']},
                                  {'id': 't1.7',
                                   'o': ['Những con sư tử này chạy nhanh.',
                                         'Những con hươu cao cổ đó chạy nhanh.',
                                         'Những con hươu cao cổ này chạy nhanh.',
                                         'Những con công này múa đẹp.'],
                                   'plain': True,
                                   'q': 'Câu: “These giraffes run quickly” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['it', 'they', 'she', 'he'],
                                   'plain': True,
                                   'q': 'Nam likes lions because _________ look strong.',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['I want to see giraffes.',
                                         'They are lions.',
                                         'He wants to see hippos.',
                                         'Because they are scary.',
                                         'Because they dance beautifully.'],
                                   'plain': True,
                                   'q': 'What animals does Nam want to see?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Minh: Because they dance beautifully. What animals do you _____, Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['and', 'legs.', 'long', 'have', 'giraffes', 'necks', 'The']},
                                  {'id': 't1.12',
                                   'o': ['Những con hổ này đáng sợ.',
                                         'Những con chim này hát hay.',
                                         'Những con ngựa này chạy nhanh.',
                                         'Những con công này múa đẹp.'],
                                   'plain': True,
                                   'q': 'Câu: “These peacocks dance beautifully." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['scary', 'funny', 'friendly', 'beautiful'],
                                   'plain': True,
                                   'q': "Mai doesn't like crocodiles because they are _________.",
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Minh: Why do you like _____?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['birds', 'merrily.', 'sing', 'they', 'She', 'because', 'likes']},
                                  {'id': 't1.16',
                                   'o': ["They're peacocks.", "They're lions.", "They're crocodiles.", "They're giraffes."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What animals have long necks and legs?”:',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['lions', 'giraffes', 'birds', 'hippos'],
                                   'plain': True,
                                   'q': 'A: Those animals swim well. What are they?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: Because they look _____.',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'like', 'you', 'peacocks?', 'Why']},
                                  {'id': 't1.20',
                                   'o': ["They're lions.", "They're monkeys.", "They're peacocks.", "They're hippos."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What animals dance beautifully”?:',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 19 – The animal world: Kiểm tra 2',
 'unit': 19}
