# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_dc1.py"""

SET = {'grade': 4,
 'id': 'lop4-dc1-b',
 'pages': [{'groups': [{'id': 'r1',
                        'instr': 'Read and circle the correct word. (Đọc và chọn từ đúng.)',
                        'items': [{'id': 'r1.1', 'o': ['am', 'is'], 'q': 'Where are you from? – I ____ from Viet Nam.', 't': 'mcq'},
                                  {'id': 'r1.2', 'o': ['have', 'has'], 'q': 'I ____ science on Mondays and Fridays.', 't': 'mcq'},
                                  {'id': 'r1.3', 'o': ['garden', 'gardens'], 'q': 'How many ____ are there at your school?', 't': 'mcq'},
                                  {'id': 'r1.4', 'o': ['eat', 'drink'], 'q': 'What do you want to ____? – I want some grapes.', 't': 'mcq'},
                                  {'id': 'r1.5', 'o': ['Monday', 'September'], 'q': 'My birthday is in ____.', 't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'Look and read. Tick True or False. (Đọc đoạn văn về Ben và chọn Đúng/Sai.)',
                        'items': [{'id': 'r2.6', 'q': 'His name is Ben.', 't': 'tf'},
                                  {'id': 'r2.7', 'q': 'He is from Australia.', 't': 'tf'},
                                  {'id': 'r2.8', 'q': 'He doesn’t go to school on Saturdays and Sundays.', 't': 'tf'},
                                  {'id': 'r2.9', 'q': 'He plays the piano on Wednesdays.', 't': 'tf'},
                                  {'id': 'r2.10', 'q': 'He stays at home and does housework on Tuesdays.', 't': 'tf'}],
                        'passage': '<p>My name is Ben. I am nine years old. I am from Australia. I am a pupil at Rose Primary School. I go to school from '
                                   'Mondays to Fridays. I like sports and music. I play football on Tuesdays. I play the guitar on Wednesdays. At the weekend, '
                                   'I stay at home and do housework with my mother.</p><img class="wide" src="../../../../assets/lop4_dc1_b/ben.png" '
                                   'alt="Ben">'}],
            'id': 'doc-chon',
            'mode': 'practice',
            'title': 'Đọc: chọn từ, Đúng/Sai'},
           {'groups': [{'id': 'r3',
                        'instr': 'Read and match. (Nối câu hỏi với câu trả lời phù hợp.)',
                        'items': [{'id': 'r3.11',
                                   'left': [{'t': 'What time is it?'},
                                            {'t': 'Where’s she from?'},
                                            {'t': 'When’s your birthday?'},
                                            {'t': 'What do you want to drink?'},
                                            {'t': 'What subjects do you have today?'}],
                                   'o': ['It’s six thirty.',
                                         'It’s in October.',
                                         'I want some milk and juice.',
                                         'I have English, maths and Vietnamese.',
                                         'She’s from Singapore.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'r4',
                        'instr': 'Read and match. (Nối câu hỏi với câu trả lời phù hợp.)',
                        'items': [{'id': 'r4.12',
                                   'left': [{'t': 'What time is it?'},
                                            {'t': 'What do you do on sports day?'},
                                            {'t': 'What time do you have music class?'},
                                            {'t': 'Can your brother ride a bike?'},
                                            {'t': 'What do you do on Sundays?'}],
                                   'o': ['It’s six thirty.',
                                         'We play sports and games.',
                                         'No, he can’t.',
                                         'I have music class at eight fifteen.',
                                         'I stay at home.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]}],
            'id': 'doc-noi',
            'mode': 'practice',
            'title': 'Đọc và nối'},
           {'groups': [{'bank': ['Sports day', 'village', 'sing', 'computer rooms', 'Music'],
                        'id': 'r5',
                        'instr': 'Read and complete. (Chọn từ trong khung điền vào chỗ trống; từ ở (0) là ví dụ.)',
                        'items': [{'id': 'r5.13', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r5.14', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r5.15', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r5.16', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>My name is Trung. I study at Nghia Lam Primary School. My school is in the (0) <u>village</u>. There are twenty '
                                   'classrooms, two <b>(1) ______</b> and a beautiful garden. My favourite subject is <b>(2) ______</b>. I can play the piano '
                                   'and <b>(3) ______</b> with my friends. It is our <b>(4) ______</b> today. The activities there are fun. It is very great. '
                                   'How about your school?</p><img class="wide" src="../../../../assets/lop4_dc1_b/bank5.png" alt="Khung từ">'},
                       {'id': 'r6',
                        'instr': 'Read and tick the correct picture. (Đọc câu và chọn tranh đúng.)',
                        'items': [{'id': 'r6.17',
                                   'img': 'p6_1.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': '“He is from Singapore.” – Chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r6.18',
                                   'img': 'p6_2.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': '“I want some chips.” – Chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r6.19',
                                   'img': 'p6_3.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': '“My school is in the town.” – Chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'r6.20',
                                   'img': 'p6_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': '“I like music because I want to be a singer.” – Chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]}],
            'id': 'doc-dien-tranh',
            'mode': 'practice',
            'title': 'Đọc: điền từ, chọn tranh'},
           {'groups': [{'id': 'w1',
                        'instr': 'Look at the picture and complete the sentences. (Nhìn tranh và hoàn thành câu.)',
                        'items': [{'id': 'w1.21', 'img': 'w1_1.png', 'q': 'Lucy is from {_}.', 't': 'fill'},
                                  {'id': 'w1.22', 'img': 'w1_2.png', 'q': 'I want some {_} at the party.', 't': 'fill'},
                                  {'id': 'w1.23', 'img': 'w1_3.png', 'q': 'There is one {_} at my school.', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Reorder the words to make a correct sentence. (Sắp xếp từ thành câu đúng.)',
                        'items': [{'id': 'w2.24',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['is', 'Music', 'subject.', 'not', 'his', 'favourite']},
                                  {'id': 'w2.25',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['They', 'day.', 'play', 'basketball', 'Sports', 'on']},
                                  {'id': 'w2.26',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['to', 'from', 'go', 'to', 'We', 'school', 'Mondays', 'Fridays.']},
                                  {'id': 'w2.27', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'at', 'the', 'We', 'housework', 'weekend.']},
                                  {'id': 'w2.28',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['building', 'is', 'my', 'There', 'one', 'at', 'school.']},
                                  {'id': 'w2.29',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['have', 'English', 'Thursdays.', 'Tuesdays', 'and', 'on', 'They']},
                                  {'id': 'w2.30',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'sing.', 'sister', 'piano', 'but', 'play', 'can’t', 'My', 'she', 'can']},
                                  {'id': 'w2.31',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['because', 'an', 'I', 'to', 'want', 'like', 'I', 'be', 'teacher.', 'English', 'English']},
                                  {'id': 'w2.32',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['my', 'three', 'buildings', 'school.', 'There', 'at', 'are']},
                                  {'id': 'w2.33',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['and', 'Mondays.', 'history', 'have', 'geography', 'on', 'I']}]},
                       {'id': 'w3',
                        'instr': 'Write the missing letters. (Viết các chữ cái còn thiếu.)',
                        'items': [{'id': 'w3.34', 'img': 'w3_1.png', 'q': 'Sat{_}day', 't': 'fill'},
                                  {'id': 'w3.35', 'img': 'w3_2.png', 'q': 'vi{_}ge', 't': 'fill'}]},
                       {'id': 'w4',
                        'instr': 'Look at the picture and complete the sentences. (Nhìn tranh và hoàn thành câu.)',
                        'items': [{'id': 'w4.36', 'img': 'w4_1.png', 'q': 'I have breakfast at six {_}.', 't': 'fill'},
                                  {'id': 'w4.37', 'img': 'w4_2.png', 'q': 'I go to school on {_}.', 't': 'fill'},
                                  {'id': 'w4.38', 'img': 'w4_3.png', 'q': 'My school is in the {_}.', 't': 'fill'}]}],
            'id': 'viet',
            'mode': 'practice',
            'title': 'Viết'}],
 'theory': '<h3>Các mẫu câu của từng Unit</h3><p>Đề cương cuối HK1 gồm 4 phần: Speaking, Listening, Reading, Writing. Dưới đây là các mẫu câu cần nhớ (Unit '
           '1–9).</p><h4>Unit 1: My friends</h4><table class="tb"><tr><th>Câu hỏi</th><th>Câu trả lời</th></tr><tr><td>Where are you from?</td><td>I’m '
           'from……</td></tr><tr><td>Where’s he/ she from?</td><td>He’s / She’s from……</td></tr></table><h4>Unit 2: Time and daily routines</h4><table '
           'class="tb"><tr><th>Câu hỏi</th><th>Câu trả lời</th></tr><tr><td>What time is it?</td><td>It’s ……</td></tr><tr><td>What time do you get up/ go to '
           'bed/ go to school/ have breakfast?</td><td>I…… …… at……</td></tr></table><h4>Unit 3: My week</h4><table class="tb"><tr><th>Câu hỏi</th><th>Câu trả '
           'lời</th></tr><tr><td>What day is it today?</td><td>It’s Monday/ Tuesday/ Wednesday/ Thursday/ Friday/ Saturday/ Sunday.</td></tr><tr><td>What do '
           'you do on……?</td><td>I do housework/ listen to music/ study at school..</td></tr></table><h4>Unit 4: My birthday party</h4><table '
           'class="tb"><tr><th>Câu hỏi</th><th>Câu trả lời</th></tr><tr><td>When’s your birthday?</td><td>It’s in……</td></tr><tr><td>What do you want to eat/ '
           'drink?</td><td>I want some……</td></tr></table><h4>Unit 5: Things we can do</h4><table class="tb"><tr><th>Câu hỏi</th><th>Câu trả '
           'lời</th></tr><tr><td>Can you cook/ draw/ play the piano/ play the guitar/ ride a bike/ ride a horse……?</td><td>Yes, I can/ No, I '
           'can’t</td></tr><tr><td>Can he/ she ……?</td><td>Yes, he/ she can / No, he/ she can’t but he/ she can……</td></tr></table><h4>Unit 6: Our school '
           'facilities</h4><table class="tb"><tr><th>Câu hỏi</th><th>Câu trả lời</th></tr><tr><td>Where’s your school?</td><td>It’s in the city/ mountains/ '
           'village/ town.</td></tr><tr><td>How many buildings/ computer rooms/ gardens/ playgrounds are there at your school?</td><td>There '
           'are……</td></tr></table><h4>Unit 7: Our timetables</h4><table class="tb"><tr><th>Câu hỏi</th><th>Câu trả lời</th></tr><tr><td>What subjects do you '
           'have today?</td><td>I have art/ English/ history and geography/ maths/ music/ science/ Vietnamese.</td></tr><tr><td>When do you have English/ '
           'Maths……?</td><td>I have it on ……</td></tr></table><h4>Unit 8: My favourite subjects</h4><table class="tb"><tr><th>Câu hỏi</th><th>Câu trả '
           'lời</th></tr><tr><td>What’s your favourite subject?</td><td>It’s IT/ PE……</td></tr><tr><td>Why do you like it?</td><td>Because I want to be a/ an '
           'English teacher/ maths teacher/ painter/ singer.</td></tr></table><h4>Unit 9: Our sports day</h4><table class="tb"><tr><th>Câu hỏi</th><th>Câu trả '
           'lời</th></tr><tr><td>Is your Sports Day in December?</td><td>Yes, it is/ No, it isn’t. It’s in……</td></tr><tr><td>When’s your Sports '
           'Day?</td><td>It’s in January/ February/ March/ April/ May/ June/ July/ August/ September/ October/ November/ December.</td></tr></table>',
 'title': 'Đề cương cuối HK1',
 'unit': 'DeCuongHK1'}
