# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'Hôm nay là thứ mấy?',
 'a.10': 'She does housework on Sundays.',
 'a.2': 'Bạn làm gì vào các ngày thứ Bảy?',
 'a.3': 'What day is it today?',
 'a.4': 'What do you do on Mondays?',
 'a.5': 'What do you do at the weekend?',
 'a.6': 'What does she do on Saturdays?',
 'a.7': 'Bạn làm gì vào thứ Năm?',
 'a.8': "It's Friday today.",
 'a.9': 'What do you do on Tuesdays?',
 'b.1': 'Wednesday',
 'b.10': 'on',
 'b.2': 'What',
 'b.3': 'Sundays',
 'b.4': "seven o'clock",
 'b.5': 'I study at school.',
 'b.6': 'does',
 'b.7': 'on',
 'b.8': 'What',
 'b.9': "It's Tuesday.",
 'c.1': {'blanks': [["It's Friday."], ["It's eight o'clock."], ['I do housework.'], ['Yes, she does.'], ['He plays football with his friends.']]},
 'd.1': 'How',
 'd.2': 'fine',
 'd.3': 'What',
 'd.4': 'Saturday',
 'd.5': 'tomorrow',
 'd.6': 'play',
 'd.7': 'help',
 'e.1': 'T',
 'e.2': 'F',
 'e.3': 'T',
 'e.4': 'F',
 'e.5': 'F',
 'f.1': ['What day is it today, Mai?'],
 'f.10': ['He listens to music on Sundays.'],
 'f.2': ['It is Wednesday'],
 'f.3': ['Mai goes to school from Monday to Friday.'],
 'f.4': ['What do you do at the weekend?'],
 'f.5': ['I play badminton with my friends.'],
 'f.6': ['What does she do on Sundays?'],
 'f.7': ['I watch TV on Sundays.'],
 'f.8': ['I do my homework on Saturdays.'],
 'f.9': ['What does he do on Sundays?'],
 'n.1': ['Monday'],
 'n.10': ['Thursday'],
 'n.2': ['Friday'],
 'n.3': ['Wednesday'],
 'n.4': 'I study at school.',
 'n.5': 'I go to school.',
 'n.6': 'I do housework.',
 'n.7': 'I listen to music.',
 'n.8': ['I listen to music'],
 'n.9': ['I study at school']}

EXPLANATIONS = {'a.1': 'Đáp án: Hôm nay là thứ mấy?',
 'a.10': 'Đáp án: She does housework on Sundays.',
 'a.2': 'Đáp án: Bạn làm gì vào các ngày thứ Bảy?',
 'a.3': 'Đáp án: What day is it today?',
 'a.4': 'Đáp án: What do you do on Mondays?',
 'a.5': 'Đáp án: What do you do at the weekend?',
 'a.6': 'Đáp án: What does she do on Saturdays?',
 'a.7': 'Đáp án: Bạn làm gì vào thứ Năm?',
 'a.8': "Đáp án: It's Friday today.",
 'a.9': 'Đáp án: What do you do on Tuesdays?',
 'b.1': 'Đáp án: Wednesday',
 'b.10': 'Đáp án: on',
 'b.2': 'Đáp án: What',
 'b.3': 'Đáp án: Sundays',
 'b.4': "Đáp án: seven o'clock",
 'b.5': 'Đáp án: I study at school.',
 'b.6': 'Đáp án: does',
 'b.7': 'Đáp án: on',
 'b.8': 'Đáp án: What',
 'b.9': "Đáp án: It's Tuesday.",
 'c.1': "What day is it today? → It's Friday.; What time is it? → It's eight o'clock.; What do you do on Sundays? → I do housework.; Does she go to school on "
        'Saturdays? → Yes, she does.; What does he do on Saturdays morning? → He plays football with his friends.',
 'd.1': 'Đáp án: How',
 'd.2': 'Đáp án: fine',
 'd.3': 'Đáp án: What',
 'd.4': 'Đáp án: Saturday',
 'd.5': 'Đáp án: tomorrow',
 'd.6': 'Đáp án: play',
 'd.7': 'Đáp án: help',
 'e.1': 'Đáp án: True (Đúng)',
 'e.2': 'Đáp án: False (Sai)',
 'e.3': 'Đáp án: True (Đúng)',
 'e.4': 'Đáp án: False (Sai)',
 'e.5': 'Đáp án: False (Sai)',
 'f.1': 'Câu đúng: What day is it today, Mai?',
 'f.10': 'Câu đúng: He listens to music on Sundays.',
 'f.2': 'Câu đúng: It is Wednesday',
 'f.3': 'Câu đúng: Mai goes to school from Monday to Friday.',
 'f.4': 'Câu đúng: What do you do at the weekend?',
 'f.5': 'Câu đúng: I play badminton with my friends.',
 'f.6': 'Câu đúng: What does she do on Sundays?',
 'f.7': 'Câu đúng: I watch TV on Sundays.',
 'f.8': 'Câu đúng: I do my homework on Saturdays.',
 'f.9': 'Câu đúng: What does he do on Sundays?',
 'n.1': 'Đáp án: Monday',
 'n.10': 'Đáp án: Thursday',
 'n.2': 'Đáp án: Friday',
 'n.3': 'Đáp án: Wednesday',
 'n.4': 'Đáp án: I study at school.',
 'n.5': 'Đáp án: I go to school.',
 'n.6': 'Đáp án: I do housework.',
 'n.7': 'Đáp án: I listen to music.',
 'n.8': 'Đáp án: I listen to music',
 'n.9': 'Đáp án: I study at school'}
