# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u3-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['Hôm nay bạn khoẻ không?', 'Bạn đến từ đâu?', 'Hôm nay là thứ mấy?', 'Mấy giờ rồi?'],
                                   'plain': True,
                                   'q': 'Câu “What day is it today?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['Hôm nay là thứ Bảy.', 'Tôi nghe nhạc vào thứ Bảy.', 'Bạn làm gì vào các ngày thứ Bảy?', 'Bạn đi đâu vào thứ Bảy?'],
                                   'plain': True,
                                   'q': 'Câu: “What do you do on Saturdays?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['What time is it?', 'How are you today?', 'Where are you from?', 'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu “It\'s Tuesday." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['What day is it today?', 'What do you do on Mondays?', 'Where are you from?', "Where's she from?"],
                                   'plain': True,
                                   'q': 'Câu “I study at school." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['What do you do on Saturdays?',
                                         'What do you do on Sundays?',
                                         'What do you do at the weekend?',
                                         'Do you go to school at the weekend?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn làm gì vào ngày cuối tuần?”',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['What does she do on Saturdays?',
                                         'Do you go to school on Saturdays?',
                                         'What do you do at the weekend?',
                                         'Is it Saturday today?'],
                                   'plain': True,
                                   'q': 'Câu: “She plays badminton in the morning." trả lời cho câu hỏi nào sau dây?',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['Hôm nay là thứ Năm phải không?',
                                         'Bạn làm gì vào thứ Năm?',
                                         'Cô ấy làm gì vào thứ Năm?',
                                         'Anh ấy làm gì vào thứ Năm?'],
                                   'plain': True,
                                   'q': '“What do you do on Thursday?" có nghĩa là?',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['I listen to music.', 'I do housework.', "It's Friday today.", "It's here."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Hôm nay là ngày thứ Sáu?”',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['Is it Tuesday today?', 'What day is it today?', 'What do you do on Tuesdays?', 'What does she do on Tuesdays?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn làm gì vào các ngày thứ Ba?".',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['She goes to school.', 'She does her homework on Sundays.', "It's Sunday.", 'She does housework on Sundays.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Cô ấy làm công việc nhà vào các ngày Chủ nhật.”',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1',
                                   'o': ['Wednesday', 'on Tuesdays', 'Mondays', 'Fridays'],
                                   'plain': True,
                                   'q': 'A: What day is it today, Mary?',
                                   't': 'mcq'},
                                  {'id': 'b.2',
                                   'o': ['What', 'How', 'When', 'Where'],
                                   'plain': True,
                                   'q': 'A: ______________ do you do on Sunday mornings, Nam?',
                                   't': 'mcq'},
                                  {'id': 'b.3',
                                   'o': ['shool', 'Sundays', 'today', 'the afternoon'],
                                   'plain': True,
                                   'q': 'A: What do you do on ______________, Bill?',
                                   't': 'mcq'},
                                  {'id': 'b.4', 'o': ['Monday', "seven o'clock", 'Sundays', 'England'], 'plain': True, 'q': 'A: What time is it?', 't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ["I'm from Singapore.", "It's five thirty.", 'They listen to music.', 'I study at school.'],
                                   'plain': True,
                                   'q': 'A: What do you do on Wednesday?',
                                   't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'A: What ______________ she do on Saturday morning?',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['in', 'at', 'on', 'with'],
                                   'plain': True,
                                   'q': 'A: What does he do _____________ Sunday mornings?',
                                   't': 'mcq'},
                                  {'id': 'b.8', 'o': ['What', 'How', 'Where', 'When'], 'plain': True, 'q': 'A: ______________ time is it?', 't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ["It's five o'clock.", "It's Tuesday.", 'I study at school.', 'I play football on Saturday mornings.'],
                                   'plain': True,
                                   'q': 'A: What day is it today?',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['at', 'in', 'on', 'to'],
                                   'plain': True,
                                   'q': 'A: What do you do _______________Monday mornings, Lucy?',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['What day is it today?',
                                            'What time is it?',
                                            'What do you do on Sundays?',
                                            'Does she go to school on Saturdays?',
                                            'What does he do on Saturdays morning?'],
                                   'o': ['I do housework.', 'He plays football with his friends.', "It's Friday.", 'Yes, she does.', "It's eight o'clock."],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': 'Chỗ trống (1):',
                                   't': 'mcq'},
                                  {'id': 'd.2',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': 'Chỗ trống (2):',
                                   't': 'mcq'},
                                  {'id': 'd.3',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': 'Chỗ trống (3):',
                                   't': 'mcq'},
                                  {'id': 'd.4',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': 'Chỗ trống (4):',
                                   't': 'mcq'},
                                  {'id': 'd.5',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': 'Chỗ trống (5):',
                                   't': 'mcq'},
                                  {'id': 'd.6',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': 'Chỗ trống (6):',
                                   't': 'mcq'},
                                  {'id': 'd.7',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': 'Chỗ trống (7):',
                                   't': 'mcq'}],
                        'passage': "Mai: Hi, Lucy.<br>Lucy: Hi, Mai. <b>(1)&nbsp;______</b> are you today?<br>Mai: I'm <b>(2)&nbsp;______</b>, thank you. And "
                                   "you?<br>Lucy: I'm fine too. <b>(3)&nbsp;______</b> day is it today, Mai?<br>Mai: It is <b>(4)&nbsp;______</b>.<br>Lucy: So "
                                   '<b>(5)&nbsp;______</b> is Sunday. What do you do on Sundays?<br>Mai: I <b>(6)&nbsp;______</b> badminton with my friends in '
                                   'the mornings, and then I <b>(7)&nbsp;______</b> my parents.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': 'Today Minh goes to school.', 't': 'tf'},
                                  {'id': 'e.2', 'q': 'Minh goes to school from Monday to Saturday.', 't': 'tf'},
                                  {'id': 'e.3', 'q': 'Minh does housework on Saturdays.', 't': 'tf'},
                                  {'id': 'e.4', 'q': 'On Sunday mornings, he goes swimming.', 't': 'tf'},
                                  {'id': 'e.5', 'q': 'On Sunday afternoon, he plays football with his friends.', 't': 'tf'}],
                        'passage': "My name's Minh. Today is Friday. It's a school day. I go to school from Monday to Friday. I do housework on Saturdays. On "
                                   'Sunday mornings, I play football with my friends and in the afternoon, I go swimming.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Mai?', 'What', 'day', 'it', 'today,', 'is']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['It', 'Wednesday', 'is']},
                                  {'id': 'f.3',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['from', 'to', 'school', 'Monday', 'Friday.', 'goes', 'Mai', 'to']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'What', 'do', 'the', 'weekend?', 'do', 'at']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['my', 'friends.', 'I', 'with', 'play', 'badminton']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['does', 'she', 'on', 'Sundays?', 'do', 'What']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['watch', 'on', 'TV', 'I', 'Sundays.']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['my', 'I', 'homework', 'Saturdays.', 'on', 'do']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['on', 'Sundays?', 'does', 'do', 'he', 'What']},
                                  {'id': 'f.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'listens', 'music', 'on', 'Sundays.', 'He']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'},
           {'audio': True,
            'groups': [{'id': 'n',
                        'instr': 'Nghe file âm thanh và làm các câu theo số thứ tự trong bài nghe.',
                        'items': [{'id': 'n.1', 'q': "Câu 1. Hi, class. What day is it today?- It's {_}", 't': 'fill'},
                                  {'id': 'n.2', 'q': "Câu 2. What day is it today?- It's {_}", 't': 'fill'},
                                  {'id': 'n.3', 'q': "Câu 3. What day is it today?- It's {_}", 't': 'fill'},
                                  {'id': 'n.4',
                                   'o': ['I study at school.', 'I play football.', 'I go to school.'],
                                   'plain': True,
                                   'q': 'Câu 4. What do you do on Mondays?',
                                   't': 'mcq'},
                                  {'id': 'n.5',
                                   'o': ['I study at school.', 'I go to school.', "I don't go to school."],
                                   'plain': True,
                                   'q': 'Câu 5. What do you do on Wednesdays?',
                                   't': 'mcq'},
                                  {'id': 'n.6',
                                   'o': ['I do homework.', 'I go to school.', 'I do housework.'],
                                   'plain': True,
                                   'q': 'Câu 6. What do you do on Saturdays?',
                                   't': 'mcq'},
                                  {'id': 'n.7',
                                   'o': ['I do housework.', 'I do homework.', 'I listen to music.'],
                                   'plain': True,
                                   'q': 'Câu 7. What do you do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 'n.8', 'q': 'Câu 8. {_}', 't': 'fill'},
                                  {'id': 'n.9', 'q': 'Câu 9. {_}', 't': 'fill'},
                                  {'id': 'n.10', 'q': "Câu 10. What day is it today?- It's {_}", 't': 'fill'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Luyện nghe'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi “Hôm nay là thứ mấy?" và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           "lời</td></tr><tr><td>What day is it today?<br>Hôm nay là thứ mấy?</td><td>It's + (thứ)...<br>Hôm nay là thứ...</td></tr><tr><td>Ví dụ:<br>A: What "
           "day is it today? Hôm nay là thứ mấy vậy?<br>B: It's Friday. Hôm nay là thứ Sáu.</td></tr></table><p>2. Cách hỏi ai đó làm gì vào một ngày cụ thể "
           'trong tuần:</p><p>+ Đối với chủ ngữ là you hoặc they:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>What do you/they '
           'do on... (ngày trong tuần dạng số nhiều)?<br>Bạn/Họ làm gì vào...?</td><td>I/They do …<br>Tôi/Họ...</td></tr><tr><td>Ví dụ:<br>A: What do you do '
           'on Wednesdays?<br>Bạn làm gì vào các ngày thứ Tư?<br>B: I study at school.<br>Tôi học ở trường.</td></tr></table><p>+ Đối với chủ ngữ là '
           'he/she/tên riêng:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>What does she/he do on... (ngày trong tuần dạng số '
           'nhiều)?<br>Cô ấy/Anh ấy làm gì vào...?</td><td>She/ He does...<br>Cô ấy/ Anh ấy...</td></tr><tr><td>Ví dụ:<br>A: What does she do on '
           'Saturdays?<br>Cô ấy làm gì vào các ngày thứ Bảy?<br>B: She watches TV.<br>Cô ấy xem ti vi.</td></tr></table>',
 'title': 'Unit 3 – My week: Luyện tập',
 'unit': 3}
