# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'q1.1': 'A',
 'q1.2': 'B',
 'q2.3': 'A',
 'q2.4': 'B',
 'q2.5': 'A',
 'q2.6': 'B',
 'q3.7': 'A',
 'q3.8': 'A',
 'q4.10': 'B',
 'q4.11': 'D',
 'q4.12': 'B',
 'q4.13': 'B',
 'q4.14': 'D',
 'q4.9': 'C',
 'q5.15': ['Were you on the beach last summer?'],
 'q5.16': ['Where were you last weekend?'],
 'q5.17': ['Our sports day is in February.'],
 'q5.18': ['My birthday is in July.'],
 'q5.19': ['My favorite subject is English.'],
 'q5.20': ['We have science today.'],
 'q5.21': ['My school is in the mountains.'],
 'q5.22': ['There are three villages near my school.'],
 'q5.23': ['I want some water.'],
 'q6.24': 'T',
 'q6.25': 'F',
 'q6.26': 'T',
 'q6.27': 'F',
 'q7.28': 'C',
 'q7.29': 'A',
 'q7.30': 'C'}

EXPLANATIONS = {'q1.1': 'Đáp án: A. July',
 'q1.2': 'Đáp án: B. January',
 'q2.3': 'Đáp án: A. Tick (✓)',
 'q2.4': 'Đáp án: B. Cross (✗)',
 'q2.5': 'Đáp án: A. Tick (✓)',
 'q2.6': 'Đáp án: B. Cross (✗)',
 'q3.7': 'Đáp án: A. Tranh a',
 'q3.8': 'Đáp án: A. Tranh a',
 'q4.10': 'Đáp án: B. Yes, he can.',
 'q4.11': 'Đáp án: D. I have it on Mondays and Thursdays.',
 'q4.12': 'Đáp án: B. When do you have English?',
 'q4.13': 'Đáp án: B. It’s in October.',
 'q4.14': 'Đáp án: D. I was in Tokyo.',
 'q4.9': "Đáp án: C. It's 7 o'clock in the morning.",
 'q5.15': 'Câu đúng: Were you on the beach last summer?',
 'q5.16': 'Câu đúng: Where were you last weekend?',
 'q5.17': 'Câu đúng: Our sports day is in February.',
 'q5.18': 'Câu đúng: My birthday is in July.',
 'q5.19': 'Câu đúng: My favorite subject is English.',
 'q5.20': 'Câu đúng: We have science today.',
 'q5.21': 'Câu đúng: My school is in the mountains.',
 'q5.22': 'Câu đúng: There are three villages near my school.',
 'q5.23': 'Câu đúng: I want some water.',
 'q6.24': 'Đáp án: True (theo đáp án của đề).',
 'q6.25': 'Đáp án: False (theo đáp án của đề).',
 'q6.26': 'Đáp án: True (theo đáp án của đề).',
 'q6.27': 'Đáp án: False (theo đáp án của đề).',
 'q7.28': 'Đáp án: C. from',
 'q7.29': 'Đáp án: A. every',
 'q7.30': 'Đáp án: C. likes'}
