# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': "What's your name?",
 'a.10': "Where's she from?",
 'a.2': 'Where are you from?',
 'a.3': "She's from Thailand.",
 'a.4': 'Anh ấy đến từ Singapore.',
 'a.5': 'Anh ấy đến từ đầu?',
 'a.6': "He's from Japan.",
 'a.7': 'Where are you from?',
 'a.8': "It's my new friend.",
 'a.9': 'Đó là bạn mới của tôi.',
 'b.1': 'are',
 'b.10': 'is',
 'b.2': 'is',
 'b.3': 'are',
 'b.4': 'is',
 'b.5': 'are',
 'b.6': 'is',
 'b.7': 'am',
 'b.8': 'are',
 'b.9': 'is',
 'c.1': {'blanks': [["I'm fine, thank you."], ["She's from America."], ["It's my new friend."], ["They're from Australia."], ["He's from Vietnam."]]},
 'd.1': 'Bill',
 'd.2': 'from',
 'd.3': 'Australia',
 'd.4': 'friend',
 'd.5': 'too',
 'e.1': 'T',
 'e.2': 'F',
 'e.3': 'F',
 'e.4': 'T',
 'e.5': 'F',
 'f.1': ['My name is Minh.'],
 'f.10': ['Where are you from?'],
 'f.2': ["I'm eight years old."],
 'f.3': ['Peter is from England.'],
 'f.4': ['Where is she from?'],
 'f.5': ['Lisa is from America.'],
 'f.6': ['This is my friend, Mary.'],
 'f.7': ['Where is he from?'],
 'f.8': ['Malee is from Thailand.'],
 'f.9': ['They are my good friends.'],
 'n.1': "Hi, I'm from Australia.",
 'n.10': ['America'],
 'n.11': 'America',
 'n.12': 'Australia',
 'n.2': "Hi. I'm from Britain.",
 'n.3': "I'm from America.",
 'n.4': "I'm from Vietnam.",
 'n.5': ['America'],
 'n.6': ['Australia'],
 'n.7': ['Minh'],
 'n.8': ['Vietnam'],
 'n.9': ['Mary']}

EXPLANATIONS = {'a.1': "Đáp án: What's your name?",
 'a.10': "Đáp án: Where's she from?",
 'a.2': 'Đáp án: Where are you from?',
 'a.3': "Đáp án: She's from Thailand.",
 'a.4': 'Đáp án: Anh ấy đến từ Singapore.',
 'a.5': 'Đáp án: Anh ấy đến từ đầu?',
 'a.6': "Đáp án: He's from Japan.",
 'a.7': 'Đáp án: Where are you from?',
 'a.8': "Đáp án: It's my new friend.",
 'a.9': 'Đáp án: Đó là bạn mới của tôi.',
 'b.1': 'Đáp án: are',
 'b.10': 'Đáp án: is',
 'b.2': 'Đáp án: is',
 'b.3': 'Đáp án: are',
 'b.4': 'Đáp án: is',
 'b.5': 'Đáp án: are',
 'b.6': 'Đáp án: is',
 'b.7': 'Đáp án: am',
 'b.8': 'Đáp án: are',
 'b.9': 'Đáp án: is',
 'c.1': "How are you, Mai? → I'm fine, thank you.; Where's Mary from? → She's from America.; Who's that? → It's my new friend.; Where are Ben and Bill from? → "
        "They're from Australia.; Where's Minh from? → He's from Vietnam.",
 'd.1': 'Đáp án: Bill',
 'd.2': 'Đáp án: from',
 'd.3': 'Đáp án: Australia',
 'd.4': 'Đáp án: friend',
 'd.5': 'Đáp án: too',
 'e.1': 'Đáp án: True (Đúng)',
 'e.2': 'Đáp án: False (Sai)',
 'e.3': 'Đáp án: False (Sai)',
 'e.4': 'Đáp án: True (Đúng)',
 'e.5': 'Đáp án: False (Sai)',
 'f.1': 'Câu đúng: My name is Minh.',
 'f.10': 'Câu đúng: Where are you from?',
 'f.2': "Câu đúng: I'm eight years old.",
 'f.3': 'Câu đúng: Peter is from England.',
 'f.4': 'Câu đúng: Where is she from?',
 'f.5': 'Câu đúng: Lisa is from America.',
 'f.6': 'Câu đúng: This is my friend, Mary.',
 'f.7': 'Câu đúng: Where is he from?',
 'f.8': 'Câu đúng: Malee is from Thailand.',
 'f.9': 'Câu đúng: They are my good friends.',
 'n.1': "Đáp án: Hi, I'm from Australia.",
 'n.10': 'Đáp án: America',
 'n.11': 'Đáp án: America',
 'n.12': 'Đáp án: Australia',
 'n.2': "Đáp án: Hi. I'm from Britain.",
 'n.3': "Đáp án: I'm from America.",
 'n.4': "Đáp án: I'm from Vietnam.",
 'n.5': 'Đáp án: America',
 'n.6': 'Đáp án: Australia',
 'n.7': 'Đáp án: Minh',
 'n.8': 'Đáp án: Vietnam',
 'n.9': 'Đáp án: Mary'}
