# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'What time is it?',
 'a.10': 'Cô ấy đi học lúc mấy giờ?',
 'a.2': "It's three fifteen.",
 'a.3': 'What time is it?',
 'a.4': 'What time do you get up?',
 'a.5': 'Tôi thức dậy lúc sáu giờ mười lăm phút.',
 'a.6': 'What time do you have breakfast?',
 'a.7': 'What time does she go to bed?',
 'a.8': 'I go to bed at ten fifteen.',
 'a.9': 'What time do you have breakfast?',
 'b.1': 'at',
 'b.10': 'has',
 'b.2': 'does',
 'b.3': 'time',
 'b.4': 'does',
 'b.5': 'goes',
 'b.6': 'do',
 'b.7': 'watch',
 'b.8': 'go',
 'b.9': 'have',
 'c.1': {'blanks': [["It's ten o'clock."],
                    ['I get up at six fifteen.'],
                    ['She has dinner at seven thirty.'],
                    ["They go to school at seven o'clock."],
                    ['He does his homework at seven forty-five.']]},
 'd.1': 'What',
 'd.2': 'have',
 'd.3': 'at',
 'd.4': 'lunch',
 'd.5': 'homework',
 'e.1': 'F',
 'e.2': 'T',
 'e.3': 'T',
 'e.4': 'F',
 'e.5': 'F',
 'f.1': ['What time is it, Mai?'],
 'f.10': ['I do my homework and go to bed at ten.'],
 'f.2': ['It is seven thirty.'],
 'f.3': ['What time do you get up?'],
 'f.4': ["I get up at six o'clock."],
 'f.5': ['What time does she have breakfast?'],
 'f.6': ['She has breakfast at seven fifteen.'],
 'f.7': ['What time do Phong and Quan go to school?'],
 'f.8': ["They have lunch at school at twelve o'clock."],
 'f.9': ['What time do you do your homework?'],
 'n.1': 'read a book',
 'n.10': "It's six forty-five.",
 'n.2': 'go out',
 'n.3': ['fifteen'],
 'n.4': ['six'],
 'n.5': ['go to bed'],
 'n.6': "I get up at five o'clock.",
 'n.7': 'At six fifteen.',
 'n.8': "It's six o'clock.",
 'n.9': "It's six fifteen"}

EXPLANATIONS = {'a.1': 'Đáp án: What time is it?',
 'a.10': 'Đáp án: Cô ấy đi học lúc mấy giờ?',
 'a.2': "Đáp án: It's three fifteen.",
 'a.3': 'Đáp án: What time is it?',
 'a.4': 'Đáp án: What time do you get up?',
 'a.5': 'Đáp án: Tôi thức dậy lúc sáu giờ mười lăm phút.',
 'a.6': 'Đáp án: What time do you have breakfast?',
 'a.7': 'Đáp án: What time does she go to bed?',
 'a.8': 'Đáp án: I go to bed at ten fifteen.',
 'a.9': 'Đáp án: What time do you have breakfast?',
 'b.1': 'Đáp án: at',
 'b.10': 'Đáp án: has',
 'b.2': 'Đáp án: does',
 'b.3': 'Đáp án: time',
 'b.4': 'Đáp án: does',
 'b.5': 'Đáp án: goes',
 'b.6': 'Đáp án: do',
 'b.7': 'Đáp án: watch',
 'b.8': 'Đáp án: go',
 'b.9': 'Đáp án: have',
 'c.1': "What time is it? → It's ten o'clock.; What time do you get up? → I get up at six fifteen.; What time does she have dinner? → She has dinner at seven "
        "thirty.; What time do Bill and Ben go to school? → They go to school at seven o'clock.; What time does he do his homework? → He does his homework at "
        'seven forty-five.',
 'd.1': 'Đáp án: What',
 'd.2': 'Đáp án: have',
 'd.3': 'Đáp án: at',
 'd.4': 'Đáp án: lunch',
 'd.5': 'Đáp án: homework',
 'e.1': 'Đáp án: False (Sai)',
 'e.2': 'Đáp án: True (Đúng)',
 'e.3': 'Đáp án: True (Đúng)',
 'e.4': 'Đáp án: False (Sai)',
 'e.5': 'Đáp án: False (Sai)',
 'f.1': 'Câu đúng: What time is it, Mai?',
 'f.10': 'Câu đúng: I do my homework and go to bed at ten.',
 'f.2': 'Câu đúng: It is seven thirty.',
 'f.3': 'Câu đúng: What time do you get up?',
 'f.4': "Câu đúng: I get up at six o'clock.",
 'f.5': 'Câu đúng: What time does she have breakfast?',
 'f.6': 'Câu đúng: She has breakfast at seven fifteen.',
 'f.7': 'Câu đúng: What time do Phong and Quan go to school?',
 'f.8': "Câu đúng: They have lunch at school at twelve o'clock.",
 'f.9': 'Câu đúng: What time do you do your homework?',
 'n.1': 'Đáp án: read a book',
 'n.10': "Đáp án: It's six forty-five.",
 'n.2': 'Đáp án: go out',
 'n.3': 'Đáp án: fifteen',
 'n.4': 'Đáp án: six',
 'n.5': 'Đáp án: go to bed',
 'n.6': "Đáp án: I get up at five o'clock.",
 'n.7': 'Đáp án: At six fifteen.',
 'n.8': "Đáp án: It's six o'clock.",
 'n.9': "Đáp án: It's six fifteen"}
