# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['My school is in a village.'],
 't1.10': 'How',
 't1.11': ['How many buildings are there at your school?'],
 't1.12': 'How many gardens are there at your school?',
 't1.13': 'villages',
 't1.14': 'playground',
 't1.15': ['There are two buildings at our school.'],
 't1.16': 'How many playgrounds are there at your school?',
 't1.17': 'park',
 't1.18': 'are there',
 't1.19': ['There is a big playround there.'],
 't1.2': "It's in the village.",
 't1.20': 'Our school is near two villages.',
 't1.3': 'are',
 't1.4': 'There is a garden at her school.',
 't1.5': 'in',
 't1.6': ['There are two playgrounds and a big garden at my school.'],
 't1.7': 'How many buildings are there at your school?',
 't1.8': 'buildings',
 't1.9': 'There are two computer rooms at his school.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: My school is in a village.',
 't1.10': 'Đáp án: How',
 't1.11': 'Câu đúng: How many buildings are there at your school?',
 't1.12': 'Đáp án: How many gardens are there at your school?',
 't1.13': 'Đáp án: villages',
 't1.14': 'Đáp án: playground',
 't1.15': 'Câu đúng: There are two buildings at our school.',
 't1.16': 'Đáp án: How many playgrounds are there at your school?',
 't1.17': 'Đáp án: park',
 't1.18': 'Đáp án: are there',
 't1.19': 'Câu đúng: There is a big playround there.',
 't1.2': "Đáp án: It's in the village.",
 't1.20': 'Đáp án: Our school is near two villages.',
 't1.3': 'Đáp án: are',
 't1.4': 'Đáp án: There is a garden at her school.',
 't1.5': 'Đáp án: in',
 't1.6': 'Câu đúng: There are two playgrounds and a big garden at my school.',
 't1.7': 'Đáp án: How many buildings are there at your school?',
 't1.8': 'Đáp án: buildings',
 't1.9': 'Đáp án: There are two computer rooms at his school.'}
