# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Do you have a brother?',
 't1.10': ['What does your brother look like?'],
 't1.11': "He's tall and thin.",
 't1.12': 'tall',
 't1.13': 'Yes, I do.',
 't1.14': 'How old',
 't1.15': ['My brother is tall and has a round face.'],
 't1.16': 'What does she look like?',
 't1.17': 'What',
 't1.18': 'She is tall and slim.',
 't1.19': 'does',
 't1.2': 'does',
 't1.20': ['My father has short hair.'],
 't1.3': "It's my brother.",
 't1.4': 'How many',
 't1.5': ['Do you have a brother or a sister, Mai?'],
 't1.6': 'What does she look like?',
 't1.7': 'old',
 't1.8': "He's a student.",
 't1.9': 'four'}

EXPLANATIONS = {'t1.1': 'Đáp án: Do you have a brother?',
 't1.10': 'Câu đúng: What does your brother look like?',
 't1.11': "Đáp án: He's tall and thin.",
 't1.12': 'Đáp án: tall',
 't1.13': 'Đáp án: Yes, I do.',
 't1.14': 'Đáp án: How old',
 't1.15': 'Câu đúng: My brother is tall and has a round face.',
 't1.16': 'Đáp án: What does she look like?',
 't1.17': 'Đáp án: What',
 't1.18': 'Đáp án: She is tall and slim.',
 't1.19': 'Đáp án: does',
 't1.2': 'Đáp án: does',
 't1.20': 'Câu đúng: My father has short hair.',
 't1.3': "Đáp án: It's my brother.",
 't1.4': 'Đáp án: How many',
 't1.5': 'Câu đúng: Do you have a brother or a sister, Mai?',
 't1.6': 'Đáp án: What does she look like?',
 't1.7': 'Đáp án: old',
 't1.8': "Đáp án: He's a student.",
 't1.9': 'Đáp án: four'}
