# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck2-de2',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'gi',
                        'instr': 'I. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'gi.1', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.2', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.3', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.4', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck2_de2/gi.png" alt="Tranh a–d">'},
                       {'id': 'gii',
                        'instr': 'II. Listen and draw lines (nghe và nối nhân vật với tranh).',
                        'items': [{'id': 'gii.5',
                                   'left': [{'img': 'gii_l1.png', 't': ''},
                                            {'img': 'gii_l2.png', 't': ''},
                                            {'img': 'gii_l3.png', 't': ''},
                                            {'img': 'gii_l4.png', 't': ''}],
                                   'o': ['a', 'b', 'c', 'd'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck2_de2/gii.png" alt="Tranh a–d">'},
                       {'id': 'giii',
                        'instr': 'III. Listen and complete (nghe và điền từ).',
                        'items': [{'id': 'giii.6', 'q': 'Where’s the bookshop? – It’s {_} the gift shop.', 't': 'fill'},
                                  {'id': 'giii.7', 'q': 'Do you want to go to the {_}? – Great! Let’s go.', 't': 'fill'},
                                  {'id': 'giii.8', 'q': 'What was the weather like last weekend? – It was {_}.', 't': 'fill'},
                                  {'id': 'giii.9', 'q': 'How can I get to the food stall? - {_}.', 't': 'fill'}]},
                       {'id': 'giv',
                        'instr': 'IV. Read and choose A, B or C (nhìn tranh, chọn đáp án đúng).',
                        'items': [{'id': 'giv.10',
                                   'img': 'giv_1.png',
                                   'o': ['It says ‘go straight’.', 'It says ‘stop’.', 'It says ‘turn round’.'],
                                   'q': 'What does it say?',
                                   't': 'mcq'},
                                  {'id': 'giv.11',
                                   'img': 'giv_2.png',
                                   'o': ['They’re hippo.', 'They’re hippos.', 'They are hippoes.'],
                                   'q': 'What are these animals?',
                                   't': 'mcq'},
                                  {'id': 'giv.12',
                                   'img': 'giv_3.png',
                                   'o': ['He dances around the campfire.', 'He’s dancing the campfire.', 'He’s dancing around the campfire.'],
                                   'q': 'What is Minh doing?',
                                   't': 'mcq'},
                                  {'id': 'giv.13',
                                   'img': 'giv_4.png',
                                   'o': ['Great! I can’t.', 'Great! Let’s go.', 'Sorry, let’s go.'],
                                   'q': 'Do you want to go to the water park?',
                                   't': 'mcq'}]},
                       {'id': 'gv',
                        'instr': 'V. Write suitable questions for the answers given (nhìn tranh, viết câu hỏi phù hợp).',
                        'items': [{'id': 'gv.14', 'img': 'gv_1.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>Sorry, I can’t.</i><br>{_}', 't': 'fill'},
                                  {'id': 'gv.15',
                                   'img': 'gv_2.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>Because they dance beautifully.</i><br>{_}',
                                   't': 'fill'},
                                  {'id': 'gv.16',
                                   'img': 'gv_3.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>It was rainy last Monday.</i><br>{_}',
                                   't': 'fill'}]},
                       {'id': 'gvi',
                        'instr': 'VI. Read and write T (True) or F (False) (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'gvi.17', 'q': 'It was rainy on Monday.', 't': 'tf'},
                                  {'id': 'gvi.18', 'q': 'I was at the park on Friday.', 't': 'tf'},
                                  {'id': 'gvi.19', 'q': 'There were lots of photos of the rainbow on Saturday.', 't': 'tf'}],
                        'passage': '<p>| Friday ¦ It was rainy today. So I was at home all day. | Saturday ¦ There was a beautiful rainbow in the sky today. I '
                                   'was able to take lots of photos with my new camera. | | Sunday ¦ Today was very cold but I was still outside. There was a '
                                   'lot of fun at the park. | Monday ¦ The weather was windy but I was not able to fly my kite today. I was outside for a walk '
                                   'and an ice cream. |</p>'},
                       {'id': 'gvii',
                        'instr': 'VII. Fill in the blanks (điền từ vào chỗ trống, nhìn tranh).',
                        'items': [{'id': 'gvii.20', 'img': 'gvii_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'gvii.21', 'img': 'gvii_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'gvii.22', 'img': 'gvii_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'gvii.23', 'img': 'gvii_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>My name is Martin and I live in a small town. In my town, there is a <b>(1) ______</b> and a <b>(2) ______</b> There is '
                                   'a bus stop but there aren’t any airports. There are lots of houses, but there aren’t any tall buildings. My favourite '
                                   'place is the <b>(3) ______</b> It’s near a <b>(4) ______</b> I love playing with my little brother there.</p>'},
                       {'bank': ['turn right', 'run quickly', 'putting up a tent', 'cloudy'],
                        'id': 'gviii',
                        'instr': 'VIII. Write suitable answers to the questions using given words (dùng từ cho sẵn để trả lời).',
                        'items': [{'id': 'gviii.24', 'q': 'Why do you like horses?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.25', 'q': 'What are they doing?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.26', 'q': 'What does it say?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.27', 'q': 'What was the weather like yesterday?<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 2 – Đề 2',
 'unit': 'CuoiKy2'}
