# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de11',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and number (nghe và đánh số). (Ví dụ: câu 0 – tranh a.)',
                        'items': [{'id': 'l1.1', 'o': ['a', 'b', 'c', 'd', 'e'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['a', 'b', 'c', 'd', 'e'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['a', 'b', 'c', 'd', 'e'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['a', 'b', 'c', 'd', 'e'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de11/l1.png" alt="Tranh">'},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and circle the correct answer A, B or C (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 1 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 2 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 3 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 4 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen and write the missing words (nghe và điền từ). Ví dụ: How can I get to the supermarket? – Turn right.',
                        'items': [{'id': 'l3.9', 'q': 'A: Where does she go on Saturdays?<br>B: She goes to the {_}.', 't': 'fill'},
                                  {'id': 'l3.10', 'q': 'A: What does she look like?<br>B: She has {_}.', 't': 'fill'},
                                  {'id': 'l3.11', 'q': 'A: When do you watch TV?<br>B: I watch TV {_}.', 't': 'fill'},
                                  {'id': 'l3.12', 'q': 'A: What is the road like?<br>B: It’s a {_}.', 't': 'fill'}]},
                       {'id': 'r1',
                        'instr': 'Question 4. Read and match (đọc và nối). Ví dụ: Where does your father work? – c. He works at a store.',
                        'items': [{'id': 'r1.13',
                                   'left': [{'t': '1. What does your sister look like?'},
                                            {'t': '2. What does he do on Sundays?'},
                                            {'t': '3. Do you want to go to the cinema?'},
                                            {'t': '4. What does it say?'},
                                            {'t': '5. How much is the T-shirt?'}],
                                   'o': ['a. It’s fifty thousand dong.',
                                         'b. It says “turn left”.',
                                         'd. He cooks meals.',
                                         'e. She is slim.',
                                         'f. Great! Let’s go.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'r2',
                        'instr': 'Question 5. Read and write Yes or No (đọc đoạn văn: Yes = True, No = False). Ví dụ: Tri is a pupil at Le Manh Trinh Primary '
                                 'school. → Yes.',
                        'items': [{'id': 'r2.14', 'q': 'He usually goes to the zoo in the morning.', 't': 'tf'},
                                  {'id': 'r2.15', 'q': 'Dung is very slim with a round face.', 't': 'tf'},
                                  {'id': 'r2.16', 'q': 'The book shop is near Tri’s house.', 't': 'tf'},
                                  {'id': 'r2.17', 'q': 'The English book is 30,000 dong.', 't': 'tf'},
                                  {'id': 'r2.18', 'q': 'They love peacocks because they roar loudly.', 't': 'tf'}],
                        'passage': '<p>I’m Tri. I’m a pupil at Le Manh Trinh Primary school. On Sundays, I usually go to the cinema in the morning and watch '
                                   'films with my sister, Dung. She is very slim with a round face. She also wants to the bookshop near our house to buy an '
                                   'English book. It’s thirty thousand dong. In the afternoon, we go to the zoo. We can see many peacocks and lions. We love '
                                   'lions because they roar loudly. We have a lot of fun on Sundays.</p>'},
                       {'id': 'r3',
                        'instr': 'Question 6. Look and write (nhìn tranh và hoàn thành câu). Ví dụ: What does your mother do? – She is a farmer.',
                        'items': [{'id': 'r3.19', 'img': 'r3_1.png', 'q': 'How much is the T-shirt?<br>It’s {_}.', 't': 'fill'},
                                  {'id': 'r3.20', 'img': 'r3_2.png', 'q': 'What do you do in the morning?<br>I {_}.', 't': 'fill'},
                                  {'id': 'r3.21', 'img': 'r3_3.png', 'q': 'Do you want to go to the bakery?<br>{_}', 't': 'fill'},
                                  {'id': 'r3.22', 'img': 'r3_4.png', 'q': 'Why do you like giraffes?<br>Because they run {_}.', 't': 'fill'}]},
                       {'id': 'w1',
                        'instr': 'Question 7. Rearrange the words to make complete sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w1.23', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['My', 'eyes.', 'grandfather', 'has', 'big']},
                                  {'id': 'w1.24',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'I', 'do', 'in', 'afternoon.', 'the', 'housework']},
                                  {'id': 'w1.25',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['was', 'last', 'rainy', 'It', 'Sapa', 'in', 'Sunday.']},
                                  {'id': 'w1.26',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['and', 'is', 'shop', 'sports', 'food', 'The', 'between', 'the', 'shop', 'the', 'bookshop.']},
                                  {'id': 'w1.27',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['like', 'lions', 'they', 'loudly.', 'They', 'because', 'roar']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 11',
 'unit': 'OnHK2'}
