# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Is your sports day in June?',
 't1.10': ["When's your sports day?"],
 't1.11': "When's your sports day?",
 't1.12': "When's",
 't1.13': 'Yes, it is.',
 't1.14': 'play',
 't1.15': ['The sports day is in December.'],
 't1.16': "It's in December.",
 't1.17': 'is',
 't1.18': 'Because I want to be a football player.',
 't1.19': 'Is',
 't1.2': 'play',
 't1.20': ['Is your sports day in October?'],
 't1.3': "It's a picture of our sports day.",
 't1.4': 'Saturday',
 't1.5': ['Our sports day is in June.'],
 't1.6': 'Yes, it is.',
 't1.7': 'Is',
 't1.8': "It's in December.",
 't1.9': 'do'}

EXPLANATIONS = {'t1.1': 'Đáp án: Is your sports day in June?',
 't1.10': "Câu đúng: When's your sports day?",
 't1.11': "Đáp án: When's your sports day?",
 't1.12': "Đáp án: When's",
 't1.13': 'Đáp án: Yes, it is.',
 't1.14': 'Đáp án: play',
 't1.15': 'Câu đúng: The sports day is in December.',
 't1.16': "Đáp án: It's in December.",
 't1.17': 'Đáp án: is',
 't1.18': 'Đáp án: Because I want to be a football player.',
 't1.19': 'Đáp án: Is',
 't1.2': 'Đáp án: play',
 't1.20': 'Câu đúng: Is your sports day in October?',
 't1.3': "Đáp án: It's a picture of our sports day.",
 't1.4': 'Đáp án: Saturday',
 't1.5': 'Câu đúng: Our sports day is in June.',
 't1.6': 'Đáp án: Yes, it is.',
 't1.7': 'Đáp án: Is',
 't1.8': "Đáp án: It's in December.",
 't1.9': 'Đáp án: do'}
