# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u11-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Where were you yesterday?', 'Where does she live?', 'Where do you live?', "What's the village like?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi “Bạn sống ở đâu?”?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['are', 'is', 'do', 'does'], 'plain': True, 'q': 'Where ____________ you live?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['I live with my parents.',
                                         'She lives in Nguyen Van Nghi Street.',
                                         'I live in Bui Minh Truc Street.',
                                         "It's a busy street.",
                                         "It's a quiet village."],
                                   'plain': True,
                                   'q': 'Where do you live?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['lives', 'with', 'in', 'house', 'like'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: I live _____ Thanh Thai Street.',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['live,', 'Minh?', 'you', 'do', 'Where']},
                                  {'id': 't1.6',
                                   'o': ['I live in a house.', "It's a small road.", 'They live in a city.', 'They live in Le Loi Street.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây miêu tả một địa điểm nào đó?',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['live', 'lives', 'to live', 'living'],
                                   'plain': True,
                                   'q': 'I ____________ in Nguyen Kiem Street.',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['I live with my parents.',
                                         'She lives in Nguyen Van Nghi Street.',
                                         'I live in Bui Minh Truc Street.',
                                         "It's a busy street.",
                                         "It's a quiet village."],
                                   'plain': True,
                                   'q': "What's the street like?",
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['lives', 'with', 'in', 'house', 'like'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: 2. A: What's the road _____?",
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['An', 'Duong', 'I', 'Street.', 'in', 'live', 'Vuong']},
                                  {'id': 't1.11',
                                   'o': ['They live in Nguyen Kiem street.',
                                         'You live in Phan Van Tri Street.',
                                         'I live in Le Lai Street.',
                                         "It's a big house."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Where do you live?',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'Where _______________ she live?', 't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['I live with my parents.',
                                         'She lives in Nguyen Van Nghi Street.',
                                         'I live in Bui Minh Truc Street.',
                                         "It's a busy street.",
                                         "It's a quiet village."],
                                   'plain': True,
                                   'q': 'Who do you live with?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['lives', 'with', 'in', 'house', 'like'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: She _____ in Bach Dang Street.',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['street', "What's", 'like?', 'the']},
                                  {'id': 't1.16',
                                   'o': ['Where do they live?', 'Where do you live?', "What's the street like?", "What's the house like?"],
                                   'plain': True,
                                   'q': 'Câu “It’s a busy street" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ["Where's", "How's", "What's", "When's"],
                                   'plain': True,
                                   'q': 'A: ____________ the city like?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['I live with my parents.',
                                         'She lives in Nguyen Van Nghi Street.',
                                         'I live in Bui Minh Truc Street.',
                                         "It's a busy street.",
                                         "It's a quiet village."],
                                   'plain': True,
                                   'q': "What's the village like?",
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['lives', 'with', 'in', 'house', 'like'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 4. A: Who does she live _____?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['quiet.', 'small', 'and', 'street', 'The', 'is']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 11 – My home: Kiểm tra 1',
 'unit': 11}
