# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Where do you live?',
 't1.10': ['I live in An Duong Vuong Street.'],
 't1.11': 'I live in Le Lai Street.',
 't1.12': 'does',
 't1.13': 'I live with my parents.',
 't1.14': 'lives',
 't1.15': ["What's the street like?"],
 't1.16': "What's the street like?",
 't1.17': "What's",
 't1.18': "It's a quiet village.",
 't1.19': 'with',
 't1.2': 'do',
 't1.20': ['The street is small and quiet.'],
 't1.3': 'I live in Bui Minh Truc Street.',
 't1.4': 'in',
 't1.5': ['Where do you live, Minh?'],
 't1.6': "It's a small road.",
 't1.7': 'live',
 't1.8': "It's a busy street.",
 't1.9': 'like'}

EXPLANATIONS = {'t1.1': 'Đáp án: Where do you live?',
 't1.10': 'Câu đúng: I live in An Duong Vuong Street.',
 't1.11': 'Đáp án: I live in Le Lai Street.',
 't1.12': 'Đáp án: does',
 't1.13': 'Đáp án: I live with my parents.',
 't1.14': 'Đáp án: lives',
 't1.15': "Câu đúng: What's the street like?",
 't1.16': "Đáp án: What's the street like?",
 't1.17': "Đáp án: What's",
 't1.18': "Đáp án: It's a quiet village.",
 't1.19': 'Đáp án: with',
 't1.2': 'Đáp án: do',
 't1.20': 'Câu đúng: The street is small and quiet.',
 't1.3': 'Đáp án: I live in Bui Minh Truc Street.',
 't1.4': 'Đáp án: in',
 't1.5': 'Câu đúng: Where do you live, Minh?',
 't1.6': "Đáp án: It's a small road.",
 't1.7': 'Đáp án: live',
 't1.8': "Đáp án: It's a busy street.",
 't1.9': 'Đáp án: like'}
