# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk2-de3',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'I. Listen to the sounds and circle the correct words. (nghe âm, chọn từ có âm đó).',
                        'items': [{'id': 'l1.1', 'o': ['pool', 'cook', 'go'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['wash', 'watch', 'street'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['big', 'street', 'quiet'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['hair', 'round', 'long'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'}]},
                       {'id': 'l2',
                        'instr': 'II. Listen and circle the correct pictures. (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'o': ['In the afternoon', 'In the morning', 'In the evening'],
                                   'q': 'Nghe: Khi nào bạn rửa bát? (When do you wash the dishes?)',
                                   't': 'mcq'},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'r1',
                        'instr': 'III. Circle the correct answers. (nhìn tranh, chọn câu đúng).',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['She works in a nursing home.', 'She’s a nurse.', 'She is a doctor.'],
                                   'q': 'What does your mother do?',
                                   't': 'mcq'},
                                  {'id': 'r1.10',
                                   'img': 'r1_2.png',
                                   'o': ['I read books in the evening.', 'I read books at noon.', 'I read books in the morning.'],
                                   'q': 'When do you read books?',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['He goes to the swimming pool.', 'He goes to the park.', 'He goes to the bakery.'],
                                   'q': 'Where does Minh go on Sundays?',
                                   't': 'mcq'},
                                  {'id': 'r1.12',
                                   'img': 'r1_4.png',
                                   'o': ['I wash the clothes.', 'I watch TV.', 'I wash the dishes.'],
                                   'q': 'What do you do in the afternoon?',
                                   't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'IV. Fill in the blanks. (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'r2.13', 'img': 'r2_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.14', 'img': 'r2_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'img': 'r2_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'img': 'r2_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>On Saturdays I often visit my friend’s house. She lives in a big <b>(1) ______</b> There is a small <b>(2) ______</b> '
                                   'in the garden. We swim there for hours. Then we go to the <b>(3) ______</b> There is a <b>(4) ______</b> where we often '
                                   'watch films together. Then we go back home and cook dinner.</p>'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 2 – Đề 3',
 'unit': 'GiuaKy2'}
