# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u11-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['like?', 'the', 'street', "What's"]},
                                  {'id': 't1.2',
                                   'o': ['Where do they live?', 'Where do you live?', "What's the street like?", "What's the house like?"],
                                   'plain': True,
                                   'q': 'Câu “It’s a busy street" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["Where's", "How's", "What's", "When's"],
                                   'plain': True,
                                   'q': 'A: ____________ the city like?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['I live with my parents.',
                                         'She lives in Nguyen Van Nghi Street.',
                                         'I live in Bui Minh Truc Street.',
                                         "It's a busy street.",
                                         "It's a quiet village."],
                                   'plain': True,
                                   'q': "What's the village like?",
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['lives', 'with', 'in', 'house', 'like'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 4. A: Who does she live _____?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['small', 'street', 'is', 'and', 'The', 'quiet.']},
                                  {'id': 't1.7',
                                   'o': ['I live in a big city.', "It's a noisy road.", "It's a busy street.", "It's a big city."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What’s the city like?”?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['on', 'at', 'in', 'with'],
                                   'plain': True,
                                   'q': 'I live ____________ 81 Tran Hung Dao Street.',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['I live with my parents.',
                                         'She lives in Nguyen Van Nghi Street.',
                                         'I live in Bui Minh Truc Street.',
                                         "It's a busy street.",
                                         "It's a quiet village."],
                                   'plain': True,
                                   'q': 'Where does she live?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['lives', 'with', 'in', 'house', 'like'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's a big _____.",
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['my', 'small', 'parents.', 'with', 'live', 'flat', 'in', 'a', 'I']},
                                  {'id': 't1.12',
                                   'o': ['I live with my parents.',
                                         'I live in a small house with my parents.',
                                         'I live in Le Lai Street.',
                                         "It's a small house."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: "Tôi sống trong một ngôi nhà nhỏ cùng với bố mẹ tôi”.',
                                   't': 'mcq'},
                                  {'id': 't1.13', 'o': ['at', 'in', 'with', 'to'], 'plain': True, 'q': 'He lives _____________ Ngo Quyen Street.', 't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'and', 'beautiful.', 'small', 'The', 'flat']},
                                  {'id': 't1.15',
                                   'o': ['I live in a small village.',
                                         'I live in a big house in a village.',
                                         "It's a small village.",
                                         'I live in a busy street.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What’s the village like?”',
                                   't': 'mcq'},
                                  {'id': 't1.16', 'o': ['with', 'to', 'on', 'in'], 'plain': True, 'q': 'She lives _____________ his parents.', 't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Le', 'at', 'lives', '15', 'She', 'Street.', 'Lai']},
                                  {'id': 't1.18',
                                   'o': ['He live in Ngo Quyen Street.',
                                         'She lives with her parents.',
                                         'She lives in Nguyen Van Troi Street.',
                                         'I live in a busy street.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where does she live?”',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'o': ['What', 'Who', 'Where', 'When'], 'plain': True, 'q': '____________ does she live with?', 't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['grandparents.', 'with', 'a', 'in', 'They', 'their', 'house', 'live', 'big']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 11 – My home: Kiểm tra 2',
 'unit': 11}
