# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'What was the weather like yesterday?',
 'a.10': "He's taking photos.",
 'a.2': 'What was the weather like in Da Lat last weekend?',
 'a.3': 'Go straight and turn left.',
 'a.4': 'How can I get the the post office?',
 'a.5': "Where's the stadium?",
 'a.6': 'How much is that shirt?',
 'a.7': 'What are those animals?',
 'a.8': 'Because they run quickly.',
 'a.9': "She's telling a story.",
 'b.1': 'What',
 'b.10': 'singing',
 'b.2': 'bookshop',
 'b.3': 'post office',
 'b.4': 'bakery',
 'b.5': 'Where',
 'b.6': 'between',
 'b.7': 'Why',
 'b.8': 'because they',
 'b.9': 'they are',
 'c.1': {'blanks': [['It was rainy.'],
                    ['Turn right and go straight.'],
                    ["It's two hundred thousand dong."],
                    ['Because they are funny.'],
                    ['They are building a campfire.']]},
 'd.1': 'Where',
 'd.2': 'like',
 'd.3': 'between',
 'd.4': 'judo',
 'd.5': 'Are',
 'e.1': 'at the zoo',
 'e.2': 'sunny',
 'e.3': 'monkeys',
 'e.4': 'crocodiles',
 'e.5': 'bears',
 'e.6': 'are scary',
 'e.7': 'are big',
 'f.1': ['Where were you last weekend, Linh?'],
 'f.10': ['They are playing tug of war.'],
 'f.2': ['It was sunny and hot.'],
 'f.3': ['How can I get to the bookshop?'],
 'f.4': ['There is a bookshop in Tran Hung Dao Street.'],
 'f.5': ['How much are these hats?'],
 'f.6': ['It is three hundred thousand dong.'],
 'f.7': ['Minh likes hippos because they look strong.'],
 'f.8': ['Lucy likes birds because they sing merrily.'],
 'f.9': ['What are Bill and Ben doing, Mary?']}

EXPLANATIONS = {'a.1': 'Đáp án: What was the weather like yesterday?',
 'a.10': "Đáp án: He's taking photos.",
 'a.2': 'Đáp án: What was the weather like in Da Lat last weekend?',
 'a.3': 'Đáp án: Go straight and turn left.',
 'a.4': 'Đáp án: How can I get the the post office?',
 'a.5': "Đáp án: Where's the stadium?",
 'a.6': 'Đáp án: How much is that shirt?',
 'a.7': 'Đáp án: What are those animals?',
 'a.8': 'Đáp án: Because they run quickly.',
 'a.9': "Đáp án: She's telling a story.",
 'b.1': 'Đáp án: What',
 'b.10': 'Đáp án: singing',
 'b.2': 'Đáp án: bookshop',
 'b.3': 'Đáp án: post office',
 'b.4': 'Đáp án: bakery',
 'b.5': 'Đáp án: Where',
 'b.6': 'Đáp án: between',
 'b.7': 'Đáp án: Why',
 'b.8': 'Đáp án: because they',
 'b.9': 'Đáp án: they are',
 'c.1': "What was the weather like last Saturday, Lan? → It was rainy.; How can I get to the zoo? → Turn right and go straight.; How much is the skirt? → It's "
        'two hundred thousand dong.; Why do you like monkeys? → Because they are funny.; What are Mai and Lan doing? → They are building a campfire.',
 'd.1': 'Đáp án: Where',
 'd.2': 'Đáp án: like',
 'd.3': 'Đáp án: between',
 'd.4': 'Đáp án: judo',
 'd.5': 'Đáp án: Are',
 'e.1': 'Đáp án: at the zoo',
 'e.2': 'Đáp án: sunny',
 'e.3': 'Đáp án: monkeys',
 'e.4': 'Đáp án: crocodiles',
 'e.5': 'Đáp án: bears',
 'e.6': 'Đáp án: are scary',
 'e.7': 'Đáp án: are big',
 'f.1': 'Câu đúng: Where were you last weekend, Linh?',
 'f.10': 'Câu đúng: They are playing tug of war.',
 'f.2': 'Câu đúng: It was sunny and hot.',
 'f.3': 'Câu đúng: How can I get to the bookshop?',
 'f.4': 'Câu đúng: There is a bookshop in Tran Hung Dao Street.',
 'f.5': 'Câu đúng: How much are these hats?',
 'f.6': 'Câu đúng: It is three hundred thousand dong.',
 'f.7': 'Câu đúng: Minh likes hippos because they look strong.',
 'f.8': 'Câu đúng: Lucy likes birds because they sing merrily.',
 'f.9': 'Câu đúng: What are Bill and Ben doing, Mary?'}
