# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck1-de2',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'gi',
                        'instr': 'I. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'gi.1', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.2', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.3', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.4', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de2/gi.png" alt="Tranh a–d">'},
                       {'id': 'gii',
                        'instr': 'II. Listen and draw lines (nghe và nối nhân vật với tranh).',
                        'items': [{'id': 'gii.5',
                                   'left': [{'img': 'gii_l1.png', 't': 'Nam'},
                                            {'img': 'gii_l2.png', 't': 'Linh'},
                                            {'img': 'gii_l3.png', 't': 'Minh'},
                                            {'img': 'gii_l4.png', 't': 'Hoa'}],
                                   'o': ['a', 'b', 'c', 'd'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de2/gii.png" alt="Tranh a–d">'},
                       {'id': 'giii',
                        'instr': 'III. Listen and complete (nghe và điền từ).',
                        'items': [{'id': 'giii.6', 'q': '– Can he {_}?<br>– Yes, he can.', 't': 'fill'},
                                  {'id': 'giii.7', 'q': '– How many {_} are there at your school?<br>– There are two.', 't': 'fill'},
                                  {'id': 'giii.8', 'q': '– When do you have {_}?<br>– I have it on Mondays.', 't': 'fill'},
                                  {'id': 'giii.9', 'q': '– Where were you last weekend?<br>– I was in the {_}.', 't': 'fill'}]},
                       {'id': 'giv',
                        'instr': 'IV. Read and choose A, B or C (nhìn tranh, chọn đáp án đúng).',
                        'items': [{'id': 'giv.10',
                                   'img': 'giv_1.png',
                                   'o': ['I do housework.', 'I study at school.', 'I ride a bike.'],
                                   'q': 'What do you do on Wednesdays?',
                                   't': 'mcq'},
                                  {'id': 'giv.11',
                                   'img': 'giv_2.png',
                                   'o': ['It’s in the city.', 'It’s in the village.', 'It’s in the mountains.'],
                                   'q': 'Where’s your house?',
                                   't': 'mcq'},
                                  {'id': 'giv.12',
                                   'img': 'giv_3.png',
                                   'o': ['I have English.', 'I have science.', 'I have art.'],
                                   'q': 'What subjects do you have today?',
                                   't': 'mcq'},
                                  {'id': 'giv.13',
                                   'img': 'giv_4.png',
                                   'o': ['No, it isn’t.', 'No, it is.', 'Yes, it is.'],
                                   'q': 'Is your sports day in June?',
                                   't': 'mcq'}]},
                       {'id': 'gv',
                        'instr': 'V. Read and write T (True) or F (False) (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'gv.14', 'q': 'Annie sings English songs on Tuesday.', 't': 'tf'},
                                  {'id': 'gv.15', 'q': 'She can swim.', 't': 'tf'},
                                  {'id': 'gv.16', 'q': 'She does housework with her mum every Thursday.', 't': 'tf'}],
                        'passage': '<p>My name is Annie. I’m nine years old. I live in a big city. I can ride a bike but I can’t swim. Every Monday, I play '
                                   'football with my brother. Every Tuesday, I sing English songs with my friends at school. On Wednesdays, I help my mum do '
                                   'housework. On Thursdays, I roller skate in the park. Every Friday, I ride a bike.</p>'},
                       {'id': 'gvi',
                        'instr': 'VI. Write suitable questions for the answers given (nhìn tranh, viết câu hỏi phù hợp).',
                        'items': [{'id': 'gvi.17',
                                   'img': 'gvi_1.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>I was in Sydney last summer.</i><br>{_}',
                                   't': 'fill'},
                                  {'id': 'gvi.18', 'img': 'gvi_2.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>I have it on Fridays.</i><br>{_}', 't': 'fill'},
                                  {'id': 'gvi.19', 'img': 'gvi_3.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>I want some grapes.</i><br>{_}', 't': 'fill'}]},
                       {'id': 'gvii',
                        'instr': 'VII. Fill in the blanks (điền từ vào chỗ trống, nhìn tranh).',
                        'items': [{'id': 'gvii.20', 'img': 'gvii_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'gvii.21', 'img': 'gvii_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'gvii.22', 'img': 'gvii_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'gvii.23', 'img': 'gvii_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Ken is ten years old. His best friend is Adam. Ken and Adam like to <b>(1) ______</b> They play in the <b>(2) '
                                   '______</b> Sometimes they <b>(3) ______</b> with other kids. They have lots of fun. Before going home, they drink some '
                                   '<b>(4) ______</b></p>'},
                       {'bank': ['October', 'beach', 'Mondays', 'three'],
                        'id': 'gviii',
                        'instr': 'VIII. Write suitable answers to the questions using the given words (dùng từ cho sẵn để trả lời).',
                        'items': [{'id': 'gviii.24', 'q': 'How many buildings are there in your school?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.25', 'q': 'Where were you last weekend?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.26', 'q': 'When’s your sports day?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.27', 'q': 'When do you have maths?<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 1 – Đề 2',
 'unit': 'CuoiKy1'}
