# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['Do you have Science on Mondays?'],
 't1.10': 'do',
 't1.11': ['I have music on Saturdays.'],
 't1.12': 'Hôm nay bạn có môn Khoa học không?',
 't1.13': 'today',
 't1.14': ['I have Vietnamese every day.'],
 't1.15': 'I have it on Tuesday and Tuesdays.',
 't1.16': 'Wednesdays',
 't1.17': ['When do you have Art?'],
 't1.18': 'Hôm nay bạn có những môn gì?',
 't1.19': "don't",
 't1.2': 'What subjects do you have today?',
 't1.20': ['We have Vietnamese and Maths today.'],
 't1.3': 'do',
 't1.4': 'I have it on Monday and Thursdays.',
 't1.5': 'on',
 't1.6': ['When do you have music?'],
 't1.7': 'Do you have music today?',
 't1.8': 'subjects',
 't1.9': 'Yes, she does.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: Do you have Science on Mondays?',
 't1.10': 'Đáp án: do',
 't1.11': 'Câu đúng: I have music on Saturdays.',
 't1.12': 'Đáp án: Hôm nay bạn có môn Khoa học không?',
 't1.13': 'Đáp án: today',
 't1.14': 'Câu đúng: I have Vietnamese every day.',
 't1.15': 'Đáp án: I have it on Tuesday and Tuesdays.',
 't1.16': 'Đáp án: Wednesdays',
 't1.17': 'Câu đúng: When do you have Art?',
 't1.18': 'Đáp án: Hôm nay bạn có những môn gì?',
 't1.19': "Đáp án: don't",
 't1.2': 'Đáp án: What subjects do you have today?',
 't1.20': 'Câu đúng: We have Vietnamese and Maths today.',
 't1.3': 'Đáp án: do',
 't1.4': 'Đáp án: I have it on Monday and Thursdays.',
 't1.5': 'Đáp án: on',
 't1.6': 'Câu đúng: When do you have music?',
 't1.7': 'Đáp án: Do you have music today?',
 't1.8': 'Đáp án: subjects',
 't1.9': 'Đáp án: Yes, she does.'}
