# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a.1': 'A',
 'a.2': 'A',
 'a.3': 'D',
 'a.4': 'D',
 'a.5': 'C',
 'b.10': 'A',
 'b.6': 'D',
 'b.7': 'C',
 'b.8': 'A',
 'b.9': 'B',
 'c.11': 'A',
 'c.12': 'D',
 'c.13': 'B',
 'c.14': 'C',
 'c.15': 'C',
 'c.16': 'A',
 'c.17': 'B',
 'c.18': 'A',
 'c.19': 'C',
 'c.20': 'D',
 'd.21': {'blanks': [['brushed']]},
 'd.22': {'blanks': [['listened']]},
 'd.23': {'blanks': [['isn’t dancing']]},
 'd.24': {'blanks': [['isn’t swimming']]},
 'd.25': {'blanks': [['doesn’t cook']]},
 'd.26': {'blanks': [['don’t visit']]},
 'd.27': {'blanks': [['Are'], ['watching']]},
 'd.28': {'blanks': [['didn’t play']]},
 'd.29': {'blanks': [['go']]},
 'd.30': {'blanks': [['walks']]},
 'e.31': {'blanks': [['I go shopping with my mother.'],
                     ['He goes to school on Sunday mornings.'],
                     ['Today is Thursday.'],
                     ['He is Malaysian.'],
                     ['There are twelve months.']]},
 'g.42': ['Do we go swimming on Saturdays?'],
 'g.43': ['Does he walk to school in the morning?'],
 'g.44': ['He is swimming in the pool right now.'],
 'g.45': ["They didn't watch a movie last Friday."],
 'g.46': ["The Sun didn't shine brightly yesterday."],
 'wrfix.32': ["The Sun doesn't rise in the west."],
 'wrfix.33': ["Birds don't sing in the winter."],
 'wrfix.34': ['We are visiting grandma this weekend.'],
 'wrfix.35': ['Did he listen to music in his room yesterday?'],
 'wrfix.36': ['Did they play basketball after school yesterday?']}

EXPLANATIONS = {'a.1': 'Đáp án: A. kite',
 'a.2': 'Đáp án: A. read',
 'a.3': 'Đáp án: D. books',
 'a.4': 'Đáp án: D. bus',
 'a.5': 'Đáp án: C. Monday',
 'b.10': 'Đáp án: A. pl<u>ea</u>sure',
 'b.6': 'Đáp án: D. <u>u</u>nion',
 'b.7': 'Đáp án: C. bl<u>oo</u>d',
 'b.8': 'Đáp án: A. <u>ch</u>emist',
 'b.9': 'Đáp án: B. t<u>ou</u>gh',
 'c.11': 'Đáp án: A. is watching',
 'c.12': 'Đáp án: D. played',
 'c.13': 'Đáp án: B. reads',
 'c.14': 'Đáp án: C. visited',
 'c.15': 'Đáp án: C. Why',
 'c.16': 'Đáp án: A. like',
 'c.17': 'Đáp án: B. What’s',
 'c.18': 'Đáp án: A. What',
 'c.19': 'Đáp án: C. Who',
 'c.20': 'Đáp án: D. What',
 'd.21': 'Đáp án: brushed',
 'd.22': 'Đáp án: listened',
 'd.23': 'Đáp án: isn’t dancing',
 'd.24': 'Đáp án: isn’t swimming',
 'd.25': 'Đáp án: doesn’t cook',
 'd.26': 'Đáp án: don’t visit',
 'd.27': 'Đáp án: Are / watching',
 'd.28': 'Đáp án: didn’t play',
 'd.29': 'Đáp án: go',
 'd.30': 'Đáp án: walks',
 'e.31': '1–C; 2–A; 3–B; 4–E; 5–D (theo đáp án của đề).',
 'f.37': 'Đáp án mẫu (theo đáp án của đề): <b>Ian and Anne from Ireland.</b>',
 'f.38': 'Đáp án mẫu (theo đáp án của đề): <b>They are really nice, and I had a lot of fun with them at the camp.</b>',
 'f.39': 'Đáp án mẫu (theo đáp án của đề): <b>Tomas from Poland.</b>',
 'f.40': 'Đáp án mẫu (theo đáp án của đề): <b>He is a very honest boy and enjoys playing ice hockey.</b>',
 'f.41': 'Đáp án mẫu (theo đáp án của đề): <b>The girl is Kim, and she lives in Australia with her family.</b>',
 'g.42': 'Câu đúng: Do we go swimming on Saturdays?',
 'g.43': 'Câu đúng: Does he walk to school in the morning?',
 'g.44': 'Câu đúng: He is swimming in the pool right now.',
 'g.45': "Câu đúng: They didn't watch a movie last Friday.",
 'g.46': "Câu đúng: The Sun didn't shine brightly yesterday.",
 'h.47': 'Đáp án mẫu (theo đáp án của đề): <b>Mr. Ba gets to work by motorbike every day.</b>',
 'h.48': 'Đáp án mẫu (theo đáp án của đề): <b>There are six hundred students in my school.</b>',
 'h.49': "Đáp án mẫu (theo đáp án của đề): <b>Jack's sister is Julia.</b>",
 'h.50': 'Đáp án mẫu (theo đáp án của đề): <b>The bank is in front of the supermarket.</b>',
 'h.51': 'Đáp án mẫu (theo đáp án của đề): <b>The children are going to school on foot now.</b>',
 'wrfix.32': "Sửa lỗi: isn’t → doesn’t. Câu đúng: The Sun doesn't rise in the west.",
 'wrfix.33': "Sửa lỗi: aren’t → don’t. Câu đúng: Birds don't sing in the winter.",
 'wrfix.34': 'Sửa lỗi: visit → are visiting. Câu đúng: We are visiting grandma this weekend.',
 'wrfix.35': 'Sửa lỗi: Does → Did. Câu đúng: Did he listen to music in his room yesterday?',
 'wrfix.36': 'Sửa lỗi: Do → Did. Câu đúng: Did they play basketball after school yesterday?'}
