# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_dc1.py"""

ANS = {'r1.1': 'A',
 'r1.2': 'A',
 'r1.3': 'B',
 'r1.4': 'A',
 'r1.5': 'B',
 'r2.10': 'F',
 'r2.6': 'T',
 'r2.7': 'T',
 'r2.8': 'T',
 'r2.9': 'F',
 'r3.11': {'blanks': [['It’s six thirty.'],
                      ['She’s from Singapore.'],
                      ['It’s in October.'],
                      ['I want some milk and juice.'],
                      ['I have English, maths and Vietnamese.']]},
 'r4.12': {'blanks': [['It’s six thirty.'], ['We play sports and games.'], ['I have music class at eight fifteen.'], ['No, he can’t.'], ['I stay at home.']]},
 'r5.13': ['computer rooms'],
 'r5.14': ['Music'],
 'r5.15': ['sing'],
 'r5.16': ['Sports day'],
 'r6.17': 'B',
 'r6.18': 'A',
 'r6.19': 'B',
 'r6.20': 'B',
 'w1.21': ['Britain'],
 'w1.22': ['lemonade'],
 'w1.23': ['building', 'garden'],
 'w2.24': ['Music is not his favourite subject.'],
 'w2.25': ['They play basketball on Sports day.'],
 'w2.26': ['We go to school from Mondays to Fridays.'],
 'w2.27': ['We do housework at the weekend.'],
 'w2.28': ['There is one building at my school.'],
 'w2.29': ['They have English on Tuesdays and Thursdays.'],
 'w2.30': ['My sister can’t play the piano but she can sing.'],
 'w2.31': ['I like English because I want to be an English teacher.'],
 'w2.32': ['There are three buildings at my school.'],
 'w2.33': ['I have history and geography on Mondays.'],
 'w3.34': ['ur'],
 'w3.35': ['lla'],
 'w4.36': ['fifteen'],
 'w4.37': ['Wednesday', 'Wednesdays'],
 'w4.38': ['mountains', 'mountain']}

EXPLANATIONS = {'r1.1': 'Đáp án: A. am',
 'r1.2': 'Đáp án: A. have',
 'r1.3': 'Đáp án: B. gardens',
 'r1.4': 'Đáp án: A. eat',
 'r1.5': 'Đáp án: B. September',
 'r2.10': 'Sai: Ben ở nhà làm việc nhà vào cuối tuần; thứ Ba Ben chơi bóng đá.',
 'r2.6': 'Đúng: “My name is Ben.”',
 'r2.7': 'Đúng: “I am from Australia.”',
 'r2.8': 'Đúng: Ben đi học từ thứ Hai đến thứ Sáu.',
 'r2.9': 'Sai: Ben chơi đàn guitar vào thứ Tư (“I play the guitar on Wednesdays”).',
 'r3.11': 'Đáp án: What time is it? → It’s six thirty.; Where’s she from? → She’s from Singapore.; When’s your birthday? → It’s in October.; What do you want '
          'to drink? → I want some milk and juice.; What subjects do you have today? → I have English, maths and Vietnamese.',
 'r4.12': 'Đáp án: What time is it? → It’s six thirty.; What do you do on sports day? → We play sports and games.; What time do you have music class? → I have '
          'music class at eight fifteen.; Can your brother ride a bike? → No, he can’t.; What do you do on Sundays? → I stay at home.',
 'r5.13': 'Đáp án: computer rooms',
 'r5.14': 'Đáp án: Music',
 'r5.15': 'Đáp án: sing',
 'r5.16': 'Đáp án: Sports day',
 'r6.17': 'Đáp án B: tranh B (Singapore).',
 'r6.18': 'Đáp án A: tranh A (chips).',
 'r6.19': 'Đáp án B: tranh B (town).',
 'r6.20': 'Đáp án B: tranh B (singer).',
 'w1.21': 'Đáp án: Britain',
 'w1.22': 'Đáp án: lemonade',
 'w1.23': 'Đáp án: building',
 'w2.24': 'Câu đúng: Music is not his favourite subject.',
 'w2.25': 'Câu đúng: They play basketball on Sports day.',
 'w2.26': 'Câu đúng: We go to school from Mondays to Fridays.',
 'w2.27': 'Câu đúng: We do housework at the weekend.',
 'w2.28': 'Câu đúng: There is one building at my school.',
 'w2.29': 'Câu đúng: They have English on Tuesdays and Thursdays.',
 'w2.30': 'Câu đúng: My sister can’t play the piano but she can sing.',
 'w2.31': 'Câu đúng: I like English because I want to be an English teacher.',
 'w2.32': 'Câu đúng: There are three buildings at my school.',
 'w2.33': 'Câu đúng: I have history and geography on Mondays.',
 'w3.34': 'Đáp án: ur',
 'w3.35': 'Đáp án: lla',
 'w4.36': 'Đáp án: fifteen',
 'w4.37': 'Đáp án: Wednesday',
 'w4.38': 'Đáp án: mountains'}
