# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u9-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ["What's your favourite subject?", 'When do you have English?', 'Is your sports day in June?', "What's that?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về ngày hội thể thao?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ["It's a picture of our sports day.", "It's in June.", 'Yes, it is.', 'My birthday is in May.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Is your sports day in May?”',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['What subjects do you have today?',
                                         'Is your sports day in September?',
                                         'Why do you like it?',
                                         "When's your sports day?"],
                                   'plain': True,
                                   'q': 'Câu "It\'s in September." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['I like sports.', "No, it isn't.", "It's in December.", 'We plays many sports and games.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “When\'s your sports day?"',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['Ngày hội thể thao của chúng tôi diễn ra trong tháng Sáu.',
                                         'Ngày hội thể thao của chúng tôi diễn ra trong tháng Bảy.',
                                         'Ngày hội thể thao của bạn diễn ra trong tháng Bảy.',
                                         'Ngày hội thể thao của tôi diễn ra trong tháng Tám.'],
                                   'plain': True,
                                   'q': 'Câu “Our sports day is in July" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['Họ chơi nhiều môn thể thao và trò chơi.',
                                         'Họ chơi thể thao nhiều và nhiều trò chơi.',
                                         'Chúng tôi chơi nhiều môn thể thao và trò chơi.',
                                         'Chúng tôi chơi nhiều trò chơi.'],
                                   'plain': True,
                                   'q': 'Câu “We play many sports and games." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['Ngày hội thể thao của họ diễn ra trong tháng Mười.',
                                         'Ngày hội thể thao của bạn diễn ra trong tháng Mười một.',
                                         'Ngày hội thể thao của chúng tôi diễn ra trong tháng Mười một.',
                                         'Ngày hội thể thao của bạn diễn ra trong tháng Mười hai.'],
                                   'plain': True,
                                   'q': 'Câu “Our sports day is in November" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ["Who's that?", "When's your sports day?", 'Is your sports day in Apirl?', 'Why do you like it?'],
                                   'plain': True,
                                   'q': "Câu: “No, it isn’t. It's in March.” trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ["When's your sports day?", 'Why do you like it?', 'Is your sportsday in June?', 'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu “Our sports day is in May.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Ngày hội thể thao của bạn diễn ra trong tháng Chín phải không?',
                                         'Ngày hội thể thao của bạn diễn ra trong tháng Mười phải không?',
                                         'Môn thể thao yêu thích của bạn là gì?',
                                         'Khi nào ngày hội thể thao của bạn diễn ra?'],
                                   'plain': True,
                                   'q': 'Câu “Is your sports day in September?" có nghĩa là:',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['do', 'make', 'play', 'take'], 'plain': True, 'q': 'We ____________ many sports and games.', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['Is', 'Are', 'Do', 'Does'], 'plain': True, 'q': '____________ your sports day in June?', 't': 'mcq'},
                                  {'id': 'b.3',
                                   'o': ["What's", "How's", "When's", "Where's"],
                                   'plain': True,
                                   'q': 'A: ____________ your sports day?',
                                   't': 'mcq'},
                                  {'id': 'b.4', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: Is your sports day in February?', 't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['Do', 'Does', 'Is', 'Are'],
                                   'plain': True,
                                   'q': 'A: Our sports day is in April. ___________ your sports day in May?',
                                   't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['Monday', 'Wednesday', 'Friday', 'May'],
                                   'plain': True,
                                   'q': 'Is your sports day in _____________?',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There __________ many boys and girls in the school playground.',
                                   't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['play', 'plays', 'is play', 'are play'],
                                   'plain': True,
                                   'q': 'They ____________ different sports and games.',
                                   't': 'mcq'},
                                  {'id': 'b.9', 'o': ['at', 'on', 'in', 'do'], 'plain': True, 'q': "A: When's your sports day?", 't': 'mcq'},
                                  {'id': 'b.10', 'o': ["He's", "She's", "They're", "It's"], 'plain': True, 'q': "A: What's that?", 't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ["What's that?",
                                            "When's your sports day?",
                                            'Is your sports day in July?',
                                            'Why do you like it?',
                                            "What's your favourite subject?"],
                                   'o': ["It's in December.",
                                         "It's PE.",
                                         "It's a picture of our sports day.",
                                         'Yes, it is.',
                                         'Because I want to be a football player.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'},
                                  {'id': 'd.6', 'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'], 'plain': True, 'q': 'Chỗ trống (6):', 't': 'mcq'}],
                        'passage': "A: What day is it today?<br>B: It's <b>(1)&nbsp;______</b>.<br>A: What <b>(2)&nbsp;______</b> you do on Saturdays?<br>B: I "
                                   '<b>(3)&nbsp;______</b> football and games with my friends.<br>A: I like football and games. Our sports day is in '
                                   "September. <b>(4)&nbsp;______</b> your sports day in September too?<br>B: No, it isn't.<br>A: <b>(5)&nbsp;______</b>your "
                                   "sports day?<br>B: It's in <b>(6)&nbsp;______</b>."}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': 'The sports day is in December.', 't': 'tf'},
                                  {'id': 'e.2', 'q': 'The sports day is in the park.', 't': 'tf'},
                                  {'id': 'e.3', 'q': "Some boys in Minh's class play basketball.", 't': 'tf'},
                                  {'id': 'e.4', 'q': 'Some girls play badminton.', 't': 'tf'},
                                  {'id': 'e.5', 'q': 'Minh plays volleyball.', 't': 'tf'}],
                        'passage': "Hello, everyone. I'm Minh. Our sports day is in December. It's in the school playground. We play different sports and "
                                   'games. Some boys in my class play football. Some girls play badminton. Other boys and I play volleyball. It is a lot of '
                                   'fun.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['June.', 'Our', 'sports', 'is', 'in', 'day']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sports', 'your', "When's", 'day?']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['day', 'in', 'is', 'December.', 'The', 'sports']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sports', 'Is', 'day', 'October?', 'your', 'in']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'September.', 'The', 'is', 'sports', 'day']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['play', 'different', 'and', 'games.', 'sports', 'We']},
                                  {'id': 'f.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['many', 'playground.', 'pupils', 'are', 'There', 'the', 'in']},
                                  {'id': 'f.8',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['play', 'Some', 'in', 'my', 'football.', 'class', 'boys']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['volleyball.', 'play', 'girls', 'Some']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['NHỚ', 'a', 'of', 'lot', 'fun.', 'GHI', 'We', 'have']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'},
           {'audio': True,
            'groups': [{'id': 'n',
                        'instr': 'Nghe file âm thanh và làm các câu theo số thứ tự trong bài nghe.',
                        'items': [{'id': 'n.1', 'q': "Câu 1. When's your sports day?- It's in {_}", 't': 'fill'},
                                  {'id': 'n.2', 'q': "Câu 2. When's your sports day?- It's in {_}", 't': 'fill'},
                                  {'id': 'n.3', 'q': "Câu 3. When's your sports day?- It's in June.", 't': 'tf'},
                                  {'id': 'n.4', 'q': "Câu 4. When's your sports day?- It's in November.", 't': 'tf'},
                                  {'id': 'n.5', 'q': 'Câu 5. I like {_}', 't': 'fill'},
                                  {'id': 'n.6', 'q': 'Câu 6. Is your sports day in {_}?', 't': 'fill'},
                                  {'id': 'n.7', 'o': ['June', 'April', 'July'], 'plain': True, 'q': 'Câu 7. My birthday is in ____________', 't': 'mcq'},
                                  {'id': 'n.8',
                                   'o': ['January', 'February', 'December'],
                                   'plain': True,
                                   'q': 'Câu 8. Our sports day is in ___________________',
                                   't': 'mcq'},
                                  {'id': 'n.9',
                                   'o': ["No, it isn't. It's in April.", "No, it isn't. It's in August."],
                                   'plain': True,
                                   'q': 'Câu 9. Is your sports day in July, Lucy?',
                                   't': 'mcq'},
                                  {'id': 'n.10', 'q': 'Câu 10. Is your sports day in {_}? Yes, it is.', 't': 'fill'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Luyện nghe'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi ai đó có phải ngày hội thể thao diễn ra trong tháng nào đó hay không và cách trả lời:</p><table '
           'class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>- Is your sports day in + (tháng)?<br>Ngày hội thể thao của bạn diễn ra trong '
           "tháng.... phải không?</td><td>- Yes, it is.<br>Vâng, đúng vậy..<br>- No, it isn't. It's in + (tháng).<br>Không phải. Nó diễn ra … (trong "
           'tháng...)</td></tr><tr><td>Ví dụ:<br>A: Is your sports day in May?<br>Ngày hội thể thao của bạn diễn ra trong tháng Năm phải không?<br>B: Yes, it '
           "is. /No, it isn't. It's in June.<br>Vâng, đúng vậy./Không phải. Nó diễn ra trong tháng Sáu.</td></tr></table><p>2. Cách hỏi về ngày hội thể thao "
           'diễn ra khi nào và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>When\'s your sports day?<br>Ngày hội '
           "thể thao của bạn diễn ra khi nào?</td><td>It's in + (tháng).<br>Nó diễn ra trong tháng …</td></tr><tr><td>Ví dụ:<br>A: When's your sports "
           "day?<br>Ngày hội thể thao của bạn khi nào diễn ra?<br>B: It's in December.<br>Nó diễn ra trong tháng Mười hai.</td></tr></table>",
 'title': 'Unit 9 – Our sports day: Luyện tập',
 'unit': 9}
