# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r1-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["It's in May.", "It's Monday today.", "She gets up at six o'clock.", 'She studies at school.'],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “When's her birthday?”?",
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['in', 'at', 'on', 'with'],
                                   'plain': True,
                                   'q': 'A: What does Mai do _____________ Sunday mornings?',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Ben?', 'What', 'you', 'doing,', 'are']},
                                  {'id': 't1.4',
                                   'o': ['I want some lemonade.', 'He wants some water.', 'They want some grapes.', 'She wants some milk.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does Lan want to drink?”?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['Saturday', 'today', 'December', 'afternoon'],
                                   'plain': True,
                                   'q': 'A: What do you do on Sunday _____________, Ben?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ["brother's", 'your', 'birthday?', "When's"]},
                                  {'id': 't1.7',
                                   'o': ["No, I can't.", 'Yes, I can.', "No, he can't.", "No, she can't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Can she ride a horse?”?',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['am', 'do', 'can', "can't"], 'plain': True, 'q': 'A: Can you ride a bike?', 't': 'mcq'},
                                  {'id': 't1.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Lan', 'play', 'the', 'piano?', 'Can']},
                                  {'id': 't1.10',
                                   'o': ['Can he ride a bike?', 'Can she play the piano?', 'Can you ride a bike?', 'Can Nam ride a horse?'],
                                   'plain': True,
                                   'q': 'Câu: “No, she can’t” trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'o': ['can', "can't", 'is', "isn't"], 'plain': True, 'q': 'A: Can Lan swim _____________?', 't': 'mcq'},
                                  {'id': 't1.12',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['She', "can't", 'dance.', 'she', 'can', 'sing,', 'but']},
                                  {'id': 't1.13',
                                   'o': ["I'm fine, thank you.", "I'm Mike.", "I'm from Australia.", "He's from Australia."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where\'s Mike from?"',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'o': ['What', 'Where', 'When', 'How'], 'plain': True, 'q': 'A: _____________ is Laura from?', 't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['I go to school.', "I'm from England.", "No, I can't.", "She goes to school at seven o'clock.", 'I want some water.'],
                                   'plain': True,
                                   'q': 'Where are you from, Mary?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['night', 'morning', 'bye'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Mary: Good _____. I'm Mary.",
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['from?', 'is', 'Nam', 'Where']},
                                  {'id': 't1.18',
                                   'o': ["Where's she from?", "Where's he from?", 'Where are you from?', "Where're they from?"],
                                   'plain': True,
                                   'q': 'Câu “I’m from Malaysia” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'o': ['is', 'am', 'are', 'does'], 'plain': True, 'q': 'Mary _____________ from England.', 't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['I go to school.', "I'm from England.", "No, I can't.", "She goes to school at seven o'clock.", 'I want some water.'],
                                   'plain': True,
                                   'q': 'What time does Lan go to school?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Review 1: Kiểm tra 3',
 'unit': 'Review1'}
