# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r3-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['mother', 'does', 'your', 'What', 'do?']},
                                  {'id': 't1.2',
                                   'o': ['What do you do?', 'Where does Nam work?', 'Where does your father work?', 'What does Nam do?'],
                                   'plain': True,
                                   'q': 'Câu: “He’s a policeman.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['at a factory', 'on a farm', 'at a primary school', 'in a hospital'],
                                   'plain': True,
                                   'q': 'My aucle is a farmer. He works ____________.',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['He watches TV in the evening.',
                                         'She lives at 10A Oxford Street.',
                                         'She goes to the sports centre.',
                                         'She works on a farm.',
                                         "He's tall and thin."],
                                   'plain': True,
                                   'q': 'What does Ben do in the evening?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['go', 'to go', 'goes', 'going'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: Where does he _____ on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['sister', 'a', 'teaches', 'at', 'school.', 'My', 'primary']},
                                  {'id': 't1.7',
                                   'o': ['What does Mai do?', 'What does Mai look like?', 'Where does Mai work?', 'Where does Mai live?'],
                                   'plain': True,
                                   'q': 'Câu: “She has curly hair" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['What', 'Where', 'How', 'When'],
                                   'plain': True,
                                   'q': '______________ does your cousin look like?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['He watches TV in the evening.',
                                         'She lives at 10A Oxford Street.',
                                         'She goes to the sports centre.',
                                         'She works on a farm.',
                                         "He's tall and thin."],
                                   'plain': True,
                                   'q': 'Where does Hoa go on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['does', 'do', 'to', 'doing'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What does he _____ there?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'like?', 'brother', 'does', 'look', 'What']},
                                  {'id': 't1.12',
                                   'o': ["He's thin and tall.", "She's a nurse.", "She's slim.", "He's a worker."],
                                   'plain': True,
                                   'q': 'Câu nào sau đầy trả lời cho câu hỏi: “What does your aunt look like?”',
                                   't': 'mcq'},
                                  {'id': 't1.13', 'o': ['they', 'your aunt', 'we', 'you'], 'plain': True, 'q': 'What does ___________ look like?', 't': 'mcq'},
                                  {'id': 't1.14',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['and', 'sister', 'hair.', 'long', 'has', 'slim', 'My', 'is']},
                                  {'id': 't1.15',
                                   'o': ['Yes, he does.', 'In the evening.', 'He washes his clothes.', 'He cleans the floor.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: "When does Ben wash his clothes?"',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['clean', 'cleans', 'to clean', 'is clean'],
                                   'plain': True,
                                   'q': 'When does your brother _____________ the floor?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'you', 'do', 'do', 'When', 'housework?']},
                                  {'id': 't1.18',
                                   'o': ['What does Lan do in the evening?',
                                         'When does Lan help mother with the cooking?',
                                         'What does Lan do?',
                                         'What does your mother do in the evening?'],
                                   'plain': True,
                                   'q': 'Câu “She helps her mother with the cooking" trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'What ____________ Lucy do in the morning?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['clothes', 'evening.', 'in', 'the', 'washes', 'Ben', 'his']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Review 3: Kiểm tra 2',
 'unit': 'Review3'}
