# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on1-de5',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Listening – Part 1. Listen and tick (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l1.1',
                                   'img': 'l1_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.2',
                                   'img': 'l1_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.3',
                                   'img': 'l1_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.4',
                                   'img': 'l1_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'l2',
                        'instr': 'Listening – Part 2. Listen and number (nghe và đánh số; tranh B là ví dụ).',
                        'items': [{'id': 'l2.5', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh A là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.6', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh C là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.7', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh D là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.8', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh E là câu số mấy trong bài nghe?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de5/l2.png" alt="Tranh">'},
                       {'id': 'l3',
                        'instr': 'Listening – Part 3. Listen and draw line (nghe và nối số thứ tự với tranh; câu 0 – tranh B là ví dụ).',
                        'items': [{'id': 'l3.9',
                                   'left': [{'t': 'Câu 1'}, {'t': 'Câu 2'}, {'t': 'Câu 3'}, {'t': 'Câu 4'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de5/l3.png" alt="Tranh">'},
                       {'id': 'l4',
                        'instr': 'Listening – Part 4. Listen and write (nghe và điền từ).',
                        'items': [{'id': 'l4.10', 'q': 'There’s some {_} on the table.', 't': 'fill'},
                                  {'id': 'l4.11', 'q': 'He’s from {_}.', 't': 'fill'},
                                  {'id': 'l4.12', 'q': 'What day is it today? – It’s {_}.', 't': 'fill'},
                                  {'id': 'l4.13', 'q': 'My favourite subject is {_}.', 't': 'fill'}]},
                       {'id': 'r1',
                        'instr': 'Reading – Part 1. Read and match the words with pictures (nối từ với tranh; tranh B là ví dụ).',
                        'items': [{'id': 'r1.14',
                                   'left': [{'t': 'go to bed'}, {'t': 'water'}, {'t': 'nine forty-five'}, {'t': 'birthday party'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de5/r1.png" alt="Tranh">'},
                       {'id': 'r2',
                        'instr': 'Reading – Part 2. Read and choose A, B or C to complete the text (đọc, chọn từ điền vào chỗ trống).',
                        'items': [{'id': 'r2.15', 'o': ['swimming', 'singing', 'cooking'], 'q': 'Chọn từ điền vào chỗ trống (1).', 't': 'mcq'},
                                  {'id': 'r2.16', 'o': ['of', 'and', 'on'], 'q': 'Chọn từ điền vào chỗ trống (2).', 't': 'mcq'},
                                  {'id': 'r2.17', 'o': ['mountain', 'hospital', 'cinema'], 'q': 'Chọn từ điền vào chỗ trống (3).', 't': 'mcq'}],
                        'passage': '<p>Hello, my name is Hoa. I’m from Viet Nam. I was on holiday in Nha Trang last summer. The beach was very beautiful. We '
                                   'went <b>(1) ______</b> in the sea and then built sandcastles in the afternoon.</p><p>In the evening, we had seafood at a '
                                   'restaurant, it was excellent. The people were friendly <b>(2) ______</b> helpful. We also watched a film at the <b>(3) '
                                   '______</b>, it was interesting. My holiday was very nice.</p>'},
                       {'id': 'r3',
                        'instr': 'Reading – Part 3. Read and tick True or False (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'r3.18', 'q': 'School starts at seven a.m and finishes at ten thirty a.m.', 't': 'tf'},
                                  {'id': 'r3.19', 'q': 'In the evening, he does his housework or listens to music.', 't': 'tf'}],
                        'passage': '<p>Hung is a pupil at Quang Trung Primary school. Every day he gets up at 6 o’clock. He has breakfast at six twenty and '
                                   'goes to school at six forty-five. School starts at 7:00 a.m and finishes at 10:30 a.m. He goes home at 10:45. He has lunch '
                                   'at 11.15. In the afternoon, he often plays football with his friends at 4:00. In the evening he does his homework or '
                                   'listens to music. Then, he goes to bed at 9:30.</p>'},
                       {'id': 'w1',
                        'instr': 'Writing – Part 1. Look at the pictures and the letters. Write the words (nhìn tranh, sắp xếp chữ cái thành từ).',
                        'items': [{'id': 'w1.20', 'img': 'w1_1.png', 'q': 'Sắp xếp các chữ cái: <b>niraBit</b> → {_}', 't': 'fill'},
                                  {'id': 'w1.21', 'img': 'w1_2.png', 'q': 'Sắp xếp các chữ cái: <b>naledemo</b> → {_}', 't': 'fill'},
                                  {'id': 'w1.22', 'img': 'w1_3.png', 'q': 'Sắp xếp các chữ cái: <b>tar</b> → {_}', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Writing – Part 2. Rearrange the words to make the sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w2.23', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['five', 'I', 'at', 'get', 'thirty.', 'up']},
                                  {'id': 'w2.24', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['subject?', 'your', 'What’s', 'favourite']},
                                  {'id': 'w2.25', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'on', 'I', 'Sunday.', 'housework']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK1 – Đề 5',
 'unit': 'OnHK1'}
