# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a.1': 'B',
 'a.2': 'D',
 'a.3': 'A',
 'a.4': 'B',
 'a.5': 'B',
 'b.10': 'C',
 'b.6': 'A',
 'b.7': 'A',
 'b.8': 'B',
 'b.9': 'A',
 'c.11': 'A',
 'c.12': 'A',
 'c.13': 'A',
 'c.14': 'B',
 'c.15': 'C',
 'c.16': 'A',
 'c.17': 'D',
 'c.18': 'B',
 'c.19': 'D',
 'c.20': 'C',
 'd.21': {'blanks': [['don’t sing']]},
 'd.22': {'blanks': [['don’t sleep']]},
 'd.23': {'blanks': [['is swimming']]},
 'd.24': {'blanks': [['Are'], ['visiting']]},
 'd.25': {'blanks': [['sang']]},
 'd.26': {'blanks': [['slept']]},
 'd.27': {'blanks': [['Did'], ['dance']]},
 'd.28': {'blanks': [['Is'], ['walking']]},
 'd.29': {'blanks': [['isn’t cooking']]},
 'd.30': {'blanks': [['Does'], ['orbit']]},
 'e.31': {'blanks': [['It’s rainy.'], ['She’s Vietnamese.'], ['It’s in north Viet Nam.'], ['Yes, I really like it.'], ['I live in Ha Noi.']]},
 'f.36': 'A',
 'f.37': 'B',
 'f.38': 'A',
 'f.39': 'A',
 'f.40': 'B',
 'g.41': ["She doesn't read books every night."],
 'g.42': ['We are swimming at the pool today.'],
 'g.43': ['He is walking to school this morning.'],
 'g.44': ['She read a book last night.'],
 'g.45': ['We swam at the pool last weekend.'],
 'wrfix.32': ['I play soccer after school.'],
 'wrfix.33': ['She reads books every night.'],
 'wrfix.34': ['She is reading a book right now.'],
 'wrfix.35': ['I played soccer yesterday.']}

EXPLANATIONS = {'a.1': 'Đáp án: B. dancing',
 'a.2': 'Đáp án: D. how',
 'a.3': 'Đáp án: A. Vietnamese',
 'a.4': 'Đáp án: B. your',
 'a.5': 'Đáp án: B. doctor',
 'b.10': 'Đáp án: C. b<u>i</u>rd',
 'b.6': 'Đáp án: A. nerv<u>ou</u>s',
 'b.7': 'Đáp án: A. favor<u>i</u>te',
 'b.8': 'Đáp án: B. t<u>a</u>ste',
 'b.9': 'Đáp án: A. f<u>u</u>ture',
 'c.11': 'Đáp án: A. is watching',
 'c.12': 'Đáp án: A. goes',
 'c.13': 'Đáp án: A. am attending',
 'c.14': 'Đáp án: B. jog',
 'c.15': 'Đáp án: C. sings',
 'c.16': 'Đáp án: A. is reading',
 'c.17': 'Đáp án: D. is studying',
 'c.18': 'Đáp án: B. takes',
 'c.19': 'Đáp án: D. ran',
 'c.20': 'Đáp án: C. is watching',
 'd.21': 'Đáp án: don’t sing',
 'd.22': 'Đáp án: don’t sleep',
 'd.23': 'Đáp án: is swimming',
 'd.24': 'Đáp án: Are / visiting',
 'd.25': 'Đáp án: sang',
 'd.26': 'Đáp án: slept',
 'd.27': 'Đáp án: Did / dance',
 'd.28': 'Đáp án: Is / walking',
 'd.29': 'Đáp án: isn’t cooking',
 'd.30': 'Đáp án: Does / orbit',
 'e.31': '1–D; 2–A; 3–E; 4–B; 5–C (theo đáp án của đề).',
 'f.36': 'Đáp án: A. Lily could communicate with animals.',
 'f.37': 'Đáp án: B. Lily spent her days tending to injured animals.',
 'f.38': 'Đáp án: A. The birds outside her window told Lily tales of their adventures.',
 'f.39': 'Đáp án: A. Lily had an unbreakable bond with the animals of the forest, becoming her closest friends.',
 'f.40': 'Đáp án: B. Lily believed that every creature had a story waiting to be heard and cherished each moment with them.',
 'g.41': "Câu đúng: She doesn't read books every night.",
 'g.42': 'Câu đúng: We are swimming at the pool today.',
 'g.43': 'Câu đúng: He is walking to school this morning.',
 'g.44': 'Câu đúng: She read a book last night.',
 'g.45': 'Câu đúng: We swam at the pool last weekend.',
 'h.46': 'Đáp án mẫu (theo đáp án của đề): <b>Her family has four people.</b>',
 'h.47': 'Đáp án mẫu (theo đáp án của đề): <b>The hotel is in front of my house.</b>',
 'h.48': 'Đáp án mẫu (theo đáp án của đề): <b>Are there twenty-five students in your class?</b>',
 'h.49': 'Đáp án mẫu (theo đáp án của đề): <b>He goes to work at a quarter past seven.</b>',
 'h.50': 'Đáp án mẫu (theo đáp án của đề): <b>The bakery is to the left of the drugstore.</b>',
 'wrfix.32': 'Sửa lỗi: plays → play. Câu đúng: I play soccer after school.',
 'wrfix.33': 'Sửa lỗi: is reading → reads. Câu đúng: She reads books every night.',
 'wrfix.34': 'Sửa lỗi: reads → is reading. Câu đúng: She is reading a book right now.',
 'wrfix.35': 'Sửa lỗi: play → played. Câu đúng: I played soccer yesterday.'}
