# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Good morning.',
 't1.10': 'down',
 't1.11': "He's flying a kite.",
 't1.12': ['This is Mary.'],
 't1.13': 'Open your books, please!',
 't1.14': 'up',
 't1.15': "They're painting.",
 't1.16': ['They are playing badminton.'],
 't1.17': 'Fly it in the sky.',
 't1.18': 'aloud',
 't1.19': "She's skipping.",
 't1.2': 'are',
 't1.20': 'Nice to see you!',
 't1.3': "I'm fine, thank you.",
 't1.4': ['Nice to see you.'],
 't1.5': 'How are you?',
 't1.6': 'again',
 't1.7': 'Good morning, class.',
 't1.8': ['Close your book, please.'],
 't1.9': 'This is Mai.'}

EXPLANATIONS = {'t1.1': 'Đáp án: Good morning.',
 't1.10': 'Đáp án: down',
 't1.11': "Đáp án: He's flying a kite.",
 't1.12': 'Câu đúng: This is Mary.',
 't1.13': 'Đáp án: Open your books, please!',
 't1.14': 'Đáp án: up',
 't1.15': "Đáp án: They're painting.",
 't1.16': 'Câu đúng: They are playing badminton.',
 't1.17': 'Đáp án: Fly it in the sky.',
 't1.18': 'Đáp án: aloud',
 't1.19': "Đáp án: She's skipping.",
 't1.2': 'Đáp án: are',
 't1.20': 'Đáp án: Nice to see you!',
 't1.3': "Đáp án: I'm fine, thank you.",
 't1.4': 'Câu đúng: Nice to see you.',
 't1.5': 'Đáp án: How are you?',
 't1.6': 'Đáp án: again',
 't1.7': 'Đáp án: Good morning, class.',
 't1.8': 'Câu đúng: Close your book, please.',
 't1.9': 'Đáp án: This is Mai.'}
