# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u10-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'did', 'you', 'What', 'there?']},
                                  {'id': 't1.2',
                                   'o': ["No, it isn't.", 'Yes, he was.', "No, I wasn't. I was on the beach last Sunday.", "No, they weren't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Were you at the campsite last Sunday?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['today', 'tomorrow', 'last summer', 'next Sunday'],
                                   'plain': True,
                                   'q': 'A: Were you in the countryside _____________?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['my', 'picture', 'painted', 'hometown.', 'I', 'of', 'a']},
                                  {'id': 't1.5',
                                   'o': ['Cuối tuần rồi bạn đã ở đâu?',
                                         'Hôm qua bạn đã ở đâu?',
                                         'Mùa hè vừa rồi bạn đã ở đâu?',
                                         'Có phải bạn ở miền quê không?'],
                                   'plain': True,
                                   'q': 'Câu “Where were you last summer" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'o': ['am', 'was', 'were', 'are'], 'plain': True, 'q': 'A: Where were you last week, Mai?', 't': 'mcq'},
                                  {'id': 't1.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['I', 'cousin.', 'badminton', 'with', 'played', 'my']},
                                  {'id': 't1.8',
                                   'o': ['Were you in Tokyo last summer?',
                                         'Was I in Bangkok last summer?',
                                         'What do you do in Bangkok?',
                                         'Where were you last summer?'],
                                   'plain': True,
                                   'q': 'Câu “I was in Bangkok lat summer." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.9', 'o': ['are', 'is', 'was', 'were'], 'plain': True, 'q': 'A: Where _____________ Mai yesterday?', 't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'Where', 'yesterday?', 'were']},
                                  {'id': 't1.11',
                                   'o': ['Cuối tuần rồi bạn đã ở bãi biển phải không?',
                                         'Hôm qua bạn đã ở sở thú phải không?',
                                         'Chủ nhật vừa rồi bạn đã ở bãi biển phải không?',
                                         'Hôm qua bạn ở bãi biển phải không? Bản word phát hành từ Tailieuchuan.vn'],
                                   'plain': True,
                                   'q': 'Câu “Were you on the beach yesterday?” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['was', 'were', 'is', "isn't"], 'plain': True, 'q': 'A: Is Tokyo a big city?', 't': 'mcq'},
                                  {'id': 't1.13', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'I', 'yesterday.', 'was', 'campsite', 'at']},
                                  {'id': 't1.14',
                                   'o': ['Were you at the zoo last weekend?',
                                         "When's your sports day?",
                                         'Where were you last weekend?',
                                         'Is your sports day in April?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi có phải ai đó đã ở đâu đó trong thời gian vừa qua không?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['Are', 'Do', 'Was', 'Were'],
                                   'plain': True,
                                   'q': 'A: ______________you at the campsite yesterday?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['I play football.', 'Yes, it is.', 'I was at the zoo yesterday.', 'Yes, I was.', 'Yes, it was.'],
                                   'plain': True,
                                   'q': 'Where were you yesterday?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ you in the countryside last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['beach', 'Were', 'last', 'the', 'you', 'on', 'weekend?']},
                                  {'id': 't1.19',
                                   'o': ["It's in September.", 'Yes, I was.', 'I was in London.', 'Because I like it.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: When’s your sports day?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'o': ['am', 'do', 'was', 'were'], 'plain': True, 'q': 'A: Where were you last summer?', 't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 10 – Our summer holidays: Kiểm tra 3',
 'unit': 10}
