# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'gi.1': 'c',
 'gi.2': 'b',
 'gi.3': 'a',
 'gi.4': 'd',
 'gii.5': {'blanks': [['b'], ['c'], ['a'], ['d']]},
 'giii.6': ['beach'],
 'giii.7': ['art'],
 'giii.8': ['Thursdays'],
 'giii.9': ['town'],
 'giv.10': 'A',
 'giv.11': 'B',
 'giv.12': 'B',
 'giv.13': 'A',
 'gv.14': ['Why do you like English?'],
 'gv.15': ['When do you have science (maths/ English…)?', 'When do you have science?', 'When do you have science maths/ English…?'],
 'gv.16': ['How many playgrounds are there at your school?'],
 'gvi.17': 'F',
 'gvi.18': 'T',
 'gvi.19': 'F',
 'gvii.20': ['Japan'],
 'gvii.21': ['garden'],
 'gvii.22': ['art'],
 'gvii.23': ['computer rooms'],
 'gviii.24': ['It’s in December.'],
 'gviii.25': ['I was in Sydney.'],
 'gviii.26': ['I have music.'],
 'gviii.27': ['It’s in the mountains.']}

EXPLANATIONS = {'gi.1': 'Câu 1 ứng với tranh c (theo đáp án của đề).',
 'gi.2': 'Câu 2 ứng với tranh b (theo đáp án của đề).',
 'gi.3': 'Câu 3 ứng với tranh a (theo đáp án của đề).',
 'gi.4': 'Câu 4 ứng với tranh d (theo đáp án của đề).',
 'gii.5': 'Đáp án theo đáp án của đề: 1–b, 2–c, 3–a, 4–d',
 'giii.6': 'Đáp án: beach',
 'giii.7': 'Đáp án: art',
 'giii.8': 'Đáp án: Thursdays',
 'giii.9': 'Đáp án: town',
 'giv.10': 'Đáp án: A. I listen to music.',
 'giv.11': 'Đáp án: B. It’s in the village.',
 'giv.12': 'Đáp án: B. Yes, it is.',
 'giv.13': 'Đáp án: A. I was at the campsite.',
 'gv.14': 'Câu hỏi đúng: Why do you like English?',
 'gv.15': 'Câu hỏi đúng: When do you have science (maths/ English…)?',
 'gv.16': 'Câu hỏi đúng: How many playgrounds are there at your school?',
 'gvi.17': 'Đáp án: False (theo đáp án của đề).',
 'gvi.18': 'Đáp án: True (theo đáp án của đề).',
 'gvi.19': 'Đáp án: False (theo đáp án của đề).',
 'gvii.20': 'Đáp án: Japan',
 'gvii.21': 'Đáp án: garden',
 'gvii.22': 'Đáp án: art',
 'gvii.23': 'Đáp án: computer rooms',
 'gviii.24': 'Câu trả lời đúng: It’s in December.',
 'gviii.25': 'Câu trả lời đúng: I was in Sydney.',
 'gviii.26': 'Câu trả lời đúng: I have music.',
 'gviii.27': 'Câu trả lời đúng: It’s in the mountains.'}
