# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-start-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Good morning.', "What's your name?", 'This is Mary.', 'See you tomorrow.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây được dùng để chào hỏi?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['is', 'are', 'do', 'am'], 'plain': True, 'q': 'How ____________ you, Mai?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["He's flying a kite.", "I'm fine, thank you.", "She's skipping.", 'Good morning, class.', "They're painting."],
                                   'plain': True,
                                   'q': 'How are you?',
                                   't': 'mcq'},
                                  {'id': 't1.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'Nice', 'you.', 'see']},
                                  {'id': 't1.5',
                                   'o': ['See you later.', 'How are you?', "I'm fine, thank you.", 'Very well, thank you.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây được dùng để hỏi thăm sức khỏe?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'o': ['later', 'well', 'again', 'tomorrow'], 'plain': True, 'q': 'Nice to see you ____________.', 't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ["He's flying a kite.", "I'm fine, thank you.", "She's skipping.", 'Good morning, class.', "They're painting."],
                                   'plain': True,
                                   'q': 'Good morning, Mr Long.',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'Close', 'please.', 'book,']},
                                  {'id': 't1.9',
                                   'o': ['Nice to meet you.', "I'm fine, thank you.", 'This is Mai.', 'Open your book, please!'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây giới thiệu một người bạn?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'o': ['to', 'down', 'in', 'aloud'], 'plain': True, 'q': 'Sit ____________, please.', 't': 'mcq'},
                                  {'id': 't1.11',
                                   'o': ["He's flying a kite.", "I'm fine, thank you.", "She's skipping.", 'Good morning, class.', "They're painting."],
                                   'plain': True,
                                   'q': "What's he doing?",
                                   't': 'mcq'},
                                  {'id': 't1.12', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['This', 'Mary.', 'is']},
                                  {'id': 't1.13',
                                   'o': ["I'm ten years old.", 'Jump up!', "He's skating.", 'Open your books, please!'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói về một hoạt động trong lớp học?',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'o': ['up', 'down', 'aloud', 'to'], 'plain': True, 'q': 'Stand ____________, please.', 't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ["He's flying a kite.", "I'm fine, thank you.", "She's skipping.", 'Good morning, class.', "They're painting."],
                                   'plain': True,
                                   'q': 'What are they doing?',
                                   't': 'mcq'},
                                  {'id': 't1.16', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'badminton.', 'They', 'playing']},
                                  {'id': 't1.17',
                                   'o': ['My hobby is swimming.', 'Fly it in the sky.', 'Say goodbye, please!', 'Stand up, please!'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói về hoạt động ở ngoài trời?',
                                   't': 'mcq'},
                                  {'id': 't1.18', 'o': ['down', 'up', 'aloud', 'in'], 'plain': True, 'q': 'Read ____________, please.', 't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ["He's flying a kite.", "I'm fine, thank you.", "She's skipping.", 'Good morning, class.', "They're painting."],
                                   'plain': True,
                                   'q': "What's she doing?",
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['Nice to see you!', 'Nice to meet you too!', 'See you later.', 'Very well, thank you.'],
                                   'plain': True,
                                   'q': 'Để nói “Rất vui được gặp bạn”, chúng ta nói:',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Bài mở đầu: Kiểm tra 1',
 'unit': 'Start'}
