# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'What was the weather like yesterday?',
 't1.10': ['It was sunny and hot.'],
 't1.11': 'Go straight and turn left.',
 't1.12': 'post office',
 't1.13': "It's two hundred thousand dong.",
 't1.14': 'between',
 't1.15': ['How can I get to the bookshop?'],
 't1.16': 'How can I get the the post office?',
 't1.17': 'bakery',
 't1.18': 'Because they are funny.',
 't1.19': 'judo',
 't1.2': 'What',
 't1.20': ['There is a bookshop in Tran Hung Dao Street.'],
 't1.3': 'It was rainy.',
 't1.4': 'Where',
 't1.5': ['Where were you last weekend, Linh?'],
 't1.6': 'What was the weather like in Da Lat last weekend?',
 't1.7': 'bookshop',
 't1.8': 'Turn right and go straight.',
 't1.9': 'like'}

EXPLANATIONS = {'t1.1': 'Đáp án: What was the weather like yesterday?',
 't1.10': 'Câu đúng: It was sunny and hot.',
 't1.11': 'Đáp án: Go straight and turn left.',
 't1.12': 'Đáp án: post office',
 't1.13': "Đáp án: It's two hundred thousand dong.",
 't1.14': 'Đáp án: between',
 't1.15': 'Câu đúng: How can I get to the bookshop?',
 't1.16': 'Đáp án: How can I get the the post office?',
 't1.17': 'Đáp án: bakery',
 't1.18': 'Đáp án: Because they are funny.',
 't1.19': 'Đáp án: judo',
 't1.2': 'Đáp án: What',
 't1.20': 'Câu đúng: There is a bookshop in Tran Hung Dao Street.',
 't1.3': 'Đáp án: It was rainy.',
 't1.4': 'Đáp án: Where',
 't1.5': 'Câu đúng: Where were you last weekend, Linh?',
 't1.6': 'Đáp án: What was the weather like in Da Lat last weekend?',
 't1.7': 'Đáp án: bookshop',
 't1.8': 'Đáp án: Turn right and go straight.',
 't1.9': 'Đáp án: like'}
