# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk1-de2',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'I. Listen and circle the correct words (nghe và chọn từ đúng).',
                        'items': [{'id': 'l1.1', 'o': ['music', 'Tuesday', 'juice'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['water', 'jam', 'grapes'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['America', 'Australia', 'Malaysia'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['Sunday', 'Monday', 'Thursday'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'}]},
                       {'id': 'l2',
                        'instr': 'II. Listen and tick the correct pictures (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'r1',
                        'instr': 'III. Read and circle the correct sentences (nhìn tranh, chọn câu đúng).',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['I go to school at seven fifteen.', 'I go to school at seven forty-five.', 'I go to school at half past seven.'],
                                   'q': 'What time do you go to school?',
                                   't': 'mcq'},
                                  {'id': 'r1.10',
                                   'img': 'r1_2.png',
                                   'o': ['He’s from Malaysia.', 'He’s from Singapore.', 'He’s from Viet Nam.'],
                                   'q': 'Where’s he from?',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['I want some apples.', 'I want some juice.', 'I want some grapes.'],
                                   'q': 'What do you want to eat?',
                                   't': 'mcq'},
                                  {'id': 'r1.12',
                                   'img': 'r1_4.png',
                                   'o': ['Yes, she can.', 'Yes, he can.', 'Yes, I can.'],
                                   'q': 'Can she ride a bike?',
                                   't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'IV. Fill in the blanks (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'r2.13', 'img': 'r2_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.14', 'img': 'r2_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'img': 'r2_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'img': 'r2_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Hi, I’m Rosie. This is my sister, Sue and my parents. We all can <b>(1) ______</b> but we can’t skateboard. My dad can '
                                   '<b>(2) ______</b> and my sister can <b>(3) ______</b> My sister can <b>(4) ______</b> but I can’t. She often takes me to '
                                   'the park near my house by bike.</p>'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 1 – Đề 2',
 'unit': 'GiuaKy1'}
