# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u20-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["She's dancing.", 'Yes, she is.', "She's at the campsite.", "She's taking a photo."],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “Where's Lan?”",
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['is', "isn't", 'does', "doesn't"],
                                   'plain': True,
                                   'q': 'A: Is Mary singing a song at the campsite?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['friends', 'war.', 'Nam', 'and', 'are', 'tug', 'playing', 'of', 'his']},
                                  {'id': 't1.4',
                                   'o': ["She's putting up a tent.", "He's buiding a campfire.", "They're telling a story.", "They're putting up a tent."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Họ đang dựng lều.”',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['doing', 'playing', 'building', 'telling'],
                                   'plain': True,
                                   'q': 'A: Where are Bill and Ben?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Lan', 'Mai', 'and', 'singing', 'Are', 'songs?']},
                                  {'id': 't1.7',
                                   'o': ['They are at the campsite.',
                                         'They are building a campfire.',
                                         'They are putting up a tent.',
                                         'They are playing card games.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Họ đang đốt lửa trại.”',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['take', 'takes', 'to take', 'taking'],
                                   'plain': True,
                                   'q': 'Phong is ______________ a photo.',
                                   't': 'mcq'},
                                  {'id': 't1.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'the', 'boys', 'doing?', 'What']},
                                  {'id': 't1.10',
                                   'o': ['Họ đang nhảy múa ở khu cắm trại.', 'Họ đang đốt lửa trại.', 'Họ đang dựng lều.', 'Họ đang nhảy múa quanh lửa trại.'],
                                   'plain': True,
                                   'q': 'Câu: “They are dancing around the campfire.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'o': ['building', 'putting up', 'telling', 'doing'], 'plain': True, 'q': "A: What's Nam doing?", 't': 'mcq'},
                                  {'id': 't1.12', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'campfire.', 'They', 'building', 'a']},
                                  {'id': 't1.13',
                                   'o': ['Where are you, Minh?', 'What does it say?', 'What is he doing?', 'What are they doing?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi một người nào đó đang làm gì?',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'o': ['is', "isn't", 'do', 'does'], 'plain': True, 'q': 'A: Hi, Lan. Is Minh there?', 't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['She is studing English.',
                                         'They are at the campsite.',
                                         'Yes, she is.',
                                         'They are playing tug of war.',
                                         "He's at school."],
                                   'plain': True,
                                   'q': 'Where are Lucy and Sarah?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['Is', 'Are', 'Do', 'Does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Mary: _____ Bill and Ben at the campsite, Lucy?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['his', 'Bill', 'are', 'and', 'Where', 'friends?']},
                                  {'id': 't1.18',
                                   'o': ['Where are Nam and Minh?', 'Is Nam there?', "Where's Nam?", 'What is Nam doing?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi một người nào đó đang ở đâu?',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'o': ['Where', 'What', 'When', 'How'], 'plain': True, 'q': 'A: ____________ is he doing?', 't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['She is studing English.',
                                         'They are at the campsite.',
                                         'Yes, she is.',
                                         'They are playing tug of war.',
                                         "He's at school."],
                                   'plain': True,
                                   'q': 'What are they doing?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 20 – At summer camp: Kiểm tra 3',
 'unit': 20}
