# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "What's your favourite subject?",
 't1.10': ['My favourite subject is Music.'],
 't1.11': "It's music.",
 't1.12': 'subject',
 't1.13': "It's music.",
 't1.14': 'How',
 't1.15': ['Why do you like Art?'],
 't1.16': 'Why do you like Music?',
 't1.17': 'PE',
 't1.18': 'I have it on Friday.',
 't1.19': 'Art',
 't1.2': "What's",
 't1.20': ['Because I want to become a painter.'],
 't1.3': "It's Thursday.",
 't1.4': 'Thursday',
 't1.5': ["What's your favourite subject?"],
 't1.6': 'Môn học yêu thích của tôi là môn Tiếng Anh.',
 't1.7': 'Art',
 't1.8': 'Yes, I do.',
 't1.9': 'Do'}

EXPLANATIONS = {'t1.1': "Đáp án: What's your favourite subject?",
 't1.10': 'Câu đúng: My favourite subject is Music.',
 't1.11': "Đáp án: It's music.",
 't1.12': 'Đáp án: subject',
 't1.13': "Đáp án: It's music.",
 't1.14': 'Đáp án: How',
 't1.15': 'Câu đúng: Why do you like Art?',
 't1.16': 'Đáp án: Why do you like Music?',
 't1.17': 'Đáp án: PE',
 't1.18': 'Đáp án: I have it on Friday.',
 't1.19': 'Đáp án: Art',
 't1.2': "Đáp án: What's",
 't1.20': 'Câu đúng: Because I want to become a painter.',
 't1.3': "Đáp án: It's Thursday.",
 't1.4': 'Đáp án: Thursday',
 't1.5': "Câu đúng: What's your favourite subject?",
 't1.6': 'Đáp án: Môn học yêu thích của tôi là môn Tiếng Anh.',
 't1.7': 'Đáp án: Art',
 't1.8': 'Đáp án: Yes, I do.',
 't1.9': 'Đáp án: Do'}
