# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "What's your name?",
 't1.10': ["I'm eight years old."],
 't1.11': "She's from Thailand.",
 't1.12': 'are',
 't1.13': "It's my new friend.",
 't1.14': 'Australia',
 't1.15': ['Peter is from England.'],
 't1.16': 'Anh ấy đến từ Singapore.',
 't1.17': 'is',
 't1.18': "They're from Australia.",
 't1.19': 'friend',
 't1.2': 'are',
 't1.20': ['Where is she from?'],
 't1.3': "I'm fine, thank you.",
 't1.4': 'Bill',
 't1.5': ['My name is Minh.'],
 't1.6': 'Where are you from?',
 't1.7': 'is',
 't1.8': "She's from America.",
 't1.9': 'from'}

EXPLANATIONS = {'t1.1': "Đáp án: What's your name?",
 't1.10': "Câu đúng: I'm eight years old.",
 't1.11': "Đáp án: She's from Thailand.",
 't1.12': 'Đáp án: are',
 't1.13': "Đáp án: It's my new friend.",
 't1.14': 'Đáp án: Australia',
 't1.15': 'Câu đúng: Peter is from England.',
 't1.16': 'Đáp án: Anh ấy đến từ Singapore.',
 't1.17': 'Đáp án: is',
 't1.18': "Đáp án: They're from Australia.",
 't1.19': 'Đáp án: friend',
 't1.2': 'Đáp án: are',
 't1.20': 'Câu đúng: Where is she from?',
 't1.3': "Đáp án: I'm fine, thank you.",
 't1.4': 'Đáp án: Bill',
 't1.5': 'Câu đúng: My name is Minh.',
 't1.6': 'Đáp án: Where are you from?',
 't1.7': 'Đáp án: is',
 't1.8': "Đáp án: She's from America.",
 't1.9': 'Đáp án: from'}
