# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "It's in May.",
 't1.10': 'Can she play the piano?',
 't1.11': "can't",
 't1.12': ["She can sing, but she can't dance."],
 't1.13': "He's from Australia.",
 't1.14': 'Where',
 't1.15': "I'm from England.",
 't1.16': 'morning',
 't1.17': ['Where is Nam from?'],
 't1.18': 'Where are you from?',
 't1.19': 'is',
 't1.2': 'on',
 't1.20': "She goes to school at seven o'clock.",
 't1.3': ['What are you doing, Ben?'],
 't1.4': 'She wants some milk.',
 't1.5': 'afternoon',
 't1.6': ["When's your brother's birthday?"],
 't1.7': "No, she can't.",
 't1.8': 'can',
 't1.9': ['Can Lan play the piano?']}

EXPLANATIONS = {'t1.1': "Đáp án: It's in May.",
 't1.10': 'Đáp án: Can she play the piano?',
 't1.11': "Đáp án: can't",
 't1.12': "Câu đúng: She can sing, but she can't dance.",
 't1.13': "Đáp án: He's from Australia.",
 't1.14': 'Đáp án: Where',
 't1.15': "Đáp án: I'm from England.",
 't1.16': 'Đáp án: morning',
 't1.17': 'Câu đúng: Where is Nam from?',
 't1.18': 'Đáp án: Where are you from?',
 't1.19': 'Đáp án: is',
 't1.2': 'Đáp án: on',
 't1.20': "Đáp án: She goes to school at seven o'clock.",
 't1.3': 'Câu đúng: What are you doing, Ben?',
 't1.4': 'Đáp án: She wants some milk.',
 't1.5': 'Đáp án: afternoon',
 't1.6': "Câu đúng: When's your brother's birthday?",
 't1.7': "Đáp án: No, she can't.",
 't1.8': 'Đáp án: can',
 't1.9': 'Câu đúng: Can Lan play the piano?'}
