# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u6-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'school', 'is', 'My', 'a', 'village.']},
                                  {'id': 't1.2',
                                   'o': ['There are two playrounds at my school.',
                                         "It's in the village.",
                                         'There is a big garden.',
                                         'We can play sports in the playground.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where’s your school?”?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There ____________ two computer rooms at my school.',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['There is a garden at her school.',
                                         "It's in the town.",
                                         'There are two computer rooms at his school.',
                                         'Nguyen Du Primary School.',
                                         'There is a playground at my school.'],
                                   'plain': True,
                                   'q': 'How many gardens are there at her school?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____ the mountains.",
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['playgrounds', 'are', 'a', 'at', 'my', 'and', 'big', 'two', 'garden', 'school.', 'There']},
                                  {'id': 't1.7',
                                   'o': ['How many gardens are there at your school?',
                                         'How many playgrounds are there at your school?',
                                         'How many rooms are there at your school?',
                                         'How many buildings are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu “There are four buildings at my school." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['buildings', 'computer room', 'playground', 'class'],
                                   'plain': True,
                                   'q': 'A: How many ____________ are there at her school?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['There is a garden at her school.',
                                         "It's in the town.",
                                         'There are two computer rooms at his school.',
                                         'Nguyen Du Primary School.',
                                         'There is a playground at my school.'],
                                   'plain': True,
                                   'q': 'How many computer rooms are there at his school?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 3. A: _____ many playgrounds are there at your school?',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['your', 'school?', 'are', 'at', 'buildings', 'many', 'there', 'How']},
                                  {'id': 't1.12',
                                   'o': ["Where's your school?",
                                         'How many gardens are there at your school?',
                                         'How many computers are there at your school?',
                                         'How many playgrounds are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu “There is a garden at my school." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['villages', 'town', 'mountain', 'park'],
                                   'plain': True,
                                   'q': 'There are four ____________ near his school.',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: There is a big _____.',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['two', 'school.', 'our', 'at', 'There', 'buildings', 'are']},
                                  {'id': 't1.16',
                                   'o': ['How many gardens are there at your school?',
                                         'How many rooms are there at your school?',
                                         'How many playgrounds are there at your school?',
                                         'How many buildings are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Có bao nhiêu sân chơi ở trường của bạn?"',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['park', 'mountains', 'buildings', 'villages'],
                                   'plain': True,
                                   'q': 'My school is near a ____________.',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 4. A: How many gardens _____ at your school?',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'a', 'big', 'playround', 'there.', 'There']},
                                  {'id': 't1.20',
                                   'o': ['Our school is near two cities.',
                                         'Our school is near two towns.',
                                         'Our school is near two mountains.',
                                         'Our school is near two villages.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là “Trường học của chúng tôi ở gần hai ngôi làng.”',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 6 – Our school facilities: Kiểm tra 2',
 'unit': 6}
