# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u14-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['wash', 'does', 'he', 'When', 'his', 'clothes?']},
                                  {'id': 't1.2',
                                   'o': ['Tôi rửa chén dĩa.',
                                         'Tôi giúp nấu nướng.',
                                         'Tôi làm việc nhà cùng với bố mẹ tôi.',
                                         'Tôi làm bài tập về nhà với ba mẹ tôi.'],
                                   'plain': True,
                                   'q': 'Câu "I do the housework with my parents.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['help', 'is help', 'helps', 'to help'],
                                   'plain': True,
                                   'q': 'She ______________ her mum with the cooking in the evening.',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'clothes', 'washes', 'morning.', 'He', 'in', 'his']},
                                  {'id': 't1.5',
                                   'o': ['She washes the dishes in the evening.',
                                         'She washes her clothes in the evening.',
                                         'She cleans the floor in the afternoon.',
                                         'She watches TV in the evening.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là “Cô ấy giặt quần áo vào buổi tối.”',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'o': ['are', 'is', 'do', 'does'], 'plain': True, 'q': 'When ______________ you do your homework?', 't': 'mcq'},
                                  {'id': 't1.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['She', 'the', 'her', 'mother', 'helps', 'with', 'cooking.']},
                                  {'id': 't1.8',
                                   'o': ['He watches TV in the evening.',
                                         'He does the housework with his parents.',
                                         'He washes the dishes in the morning.',
                                         'He washes his clothes in the evening.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does he do in the afternoon?”?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['TV', 'books', 'housework', 'floor'],
                                   'plain': True,
                                   'q': 'I read _____________ in the evening.',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['at', 'floor', 'He', 'the', 'cleans', 'noon.']},
                                  {'id': 't1.11',
                                   'o': ['Yes, she does.', 'In the evening.', 'She washes her clothes.', 'She cleans the floor.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “When does she help with the cooking?”',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['make', 'watch', 'do', 'help'],
                                   'plain': True,
                                   'q': 'When do you _____________ the housework?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['housework', 'I', 'morning.', 'the', 'do', 'in', 'the']},
                                  {'id': 't1.14',
                                   'o': ['What do you do?', 'What do you do in the morning?', 'When do you watch TV?', 'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi ai đó làm việc gì đó khi nào?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['When', 'Where', 'What', 'How'],
                                   'plain': True,
                                   'q': 'A: ____________do you do in the evening?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['She cleans the floor.',
                                         'I do the housework in the morning.',
                                         'I read books in the afternoon.',
                                         'She washes her clothes in the evening.',
                                         'I watch TV.'],
                                   'plain': True,
                                   'q': 'When do you do the housework?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: A: Who's _____?",
                                   't': 'mcq'},
                                  {'id': 't1.18', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Minh?', 'your', "What's", 'hobby,']},
                                  {'id': 't1.19',
                                   'o': ['What do you do in the afternoon?',
                                         'What do you do in the morning?',
                                         'What do you do in the evening?',
                                         'When do you wash the clothes?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi bạn làm gì vào buổi sáng?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['wash', 'washes', 'watching', 'to wash'],
                                   'plain': True,
                                   'q': 'She ______________ her clothes in the evening.',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 14 – Daily activities: Kiểm tra 3',
 'unit': 14}
