# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'q1.1': 'A',
 'q1.2': 'B',
 'q1.3': 'B',
 'q1.4': 'A',
 'q2.5': 'B',
 'q2.6': 'A',
 'q3.10': 'C',
 'q3.7': 'D',
 'q3.8': 'B',
 'q3.9': 'D',
 'q4.11': ['Were you in the countryside last weekend?'],
 'q4.12': ['I was in the countryside last weekend.'],
 'q4.13': ['It’s a picture of our sports day.'],
 'q4.14': ['What subjects do you have today?'],
 'q4.15': ['I have English and maths.'],
 'q4.16': ['I have it on Mondays and Fridays.'],
 'q4.17': ['How many buildings are there at your school?'],
 'q4.18': ['Can she roller skate?'],
 'q4.19': ['Can you play the guitar?'],
 'q4.20': ['What do you do on Wednesdays?'],
 'q4.21': ['What do you do on Mondays?'],
 'q4.22': ['What time do you get up?'],
 'q4.23': ['What time do you have breakfast?'],
 'q5.24': 'T',
 'q5.25': 'T',
 'q5.26': 'F',
 'q5.27': 'T',
 'q6.28': 'A',
 'q6.29': 'C',
 'q6.30': 'B'}

EXPLANATIONS = {'q1.1': 'Đáp án: A. Tick (✓)',
 'q1.2': 'Đáp án: B. Cross (✗)',
 'q1.3': 'Đáp án: B. Cross (✗)',
 'q1.4': 'Đáp án: A. Tick (✓)',
 'q2.5': 'Đáp án: B. Tranh b',
 'q2.6': 'Đáp án: A. Tranh a',
 'q3.10': 'Đáp án: C. Tranh d',
 'q3.7': 'Đáp án: D. Tranh c',
 'q3.8': 'Đáp án: B. Tranh b',
 'q3.9': 'Đáp án: D. Tranh a',
 'q4.11': 'Câu đúng: Were you in the countryside last weekend?',
 'q4.12': 'Câu đúng: I was in the countryside last weekend.',
 'q4.13': 'Câu đúng: It’s a picture of our sports day.',
 'q4.14': 'Câu đúng: What subjects do you have today?',
 'q4.15': 'Câu đúng: I have English and maths.',
 'q4.16': 'Câu đúng: I have it on Mondays and Fridays.',
 'q4.17': 'Câu đúng: How many buildings are there at your school?',
 'q4.18': 'Câu đúng: Can she roller skate?',
 'q4.19': 'Câu đúng: Can you play the guitar?',
 'q4.20': 'Câu đúng: What do you do on Wednesdays?',
 'q4.21': 'Câu đúng: What do you do on Mondays?',
 'q4.22': 'Câu đúng: What time do you get up?',
 'q4.23': 'Câu đúng: What time do you have breakfast?',
 'q5.24': 'Đáp án: True (theo đáp án của đề).',
 'q5.25': 'Đáp án: True (theo đáp án của đề).',
 'q5.26': 'Đáp án: False (theo đáp án của đề).',
 'q5.27': 'Đáp án: True (theo đáp án của đề).',
 'q6.28': 'Đáp án: A. He’s from Malaysia.',
 'q6.29': 'Đáp án: C. at 6:30 a.m',
 'q6.30': 'Đáp án: B. I want some juice.'}
