# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de5',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and number (nghe và đánh số 1–4 cho các tranh; tranh B là ví dụ).',
                        'items': [{'id': 'l1.1', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh A là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh C là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh D là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh E là câu số mấy trong bài nghe?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de5/l1.png" alt="Tranh">'},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and tick (✓ = True) or cross (✗ = False) (nghe, tranh đúng thì chọn True, sai thì chọn False).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'q': 'Nghe và quyết định: nội dung nghe có đúng với tranh không? (✓ = True, ✗ = False)',
                                   't': 'tf'},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'q': 'Nghe và quyết định: nội dung nghe có đúng với tranh không? (✓ = True, ✗ = False)',
                                   't': 'tf'},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'q': 'Nghe và quyết định: nội dung nghe có đúng với tranh không? (✓ = True, ✗ = False)',
                                   't': 'tf'},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'q': 'Nghe và quyết định: nội dung nghe có đúng với tranh không? (✓ = True, ✗ = False)',
                                   't': 'tf'}]},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen and choose the answer for the question (nghe câu hỏi trong bong bóng, chọn câu trả lời đúng).',
                        'items': [{'id': 'l3.9',
                                   'img': 'l3_1.png',
                                   'o': ['She has small eyes.', 'He has small eyes.'],
                                   'q': 'Nghe câu hỏi và chọn câu trả lời đúng.',
                                   't': 'mcq'},
                                  {'id': 'l3.10',
                                   'img': 'l3_2.png',
                                   'o': ['Yes, I do.', 'At noon.'],
                                   'q': 'Nghe câu hỏi và chọn câu trả lời đúng.',
                                   't': 'mcq'},
                                  {'id': 'l3.11',
                                   'img': 'l3_3.png',
                                   'o': ['She goes to the sports center.', 'She has a round face.'],
                                   'q': 'Nghe câu hỏi và chọn câu trả lời đúng.',
                                   't': 'mcq'},
                                  {'id': 'l3.12',
                                   'img': 'l3_4.png',
                                   'o': ['It’s windy.', 'They are dancing.'],
                                   'q': 'Nghe câu hỏi và chọn câu trả lời đúng.',
                                   't': 'mcq'}]},
                       {'id': 'r1',
                        'instr': 'Question 4. Read and match (đọc và nối câu với tranh; tranh A đã dùng làm ví dụ).',
                        'items': [{'id': 'r1.13',
                                   'left': [{'t': 'Does she work at a hospital? – No, she doesn’t. She works at a nursing home.'},
                                            {'t': 'What do you do in the evening? – I help my mother with the cooking.'},
                                            {'t': 'What does it say? – It says “GO”.'},
                                            {'t': 'What animals do you like? – I like lions because they roar loudly.'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de5/m4.png" alt="Tranh A–E">'},
                       {'id': 'r2',
                        'instr': 'Question 5. Read and choose A, B or C (đọc và chọn đáp án đúng).',
                        'items': [{'id': 'r2.14', 'o': ['look like', 'like', 'look'], 'q': 'What does your mother ____? – She is tall and slim.', 't': 'mcq'},
                                  {'id': 'r2.15',
                                   'o': ['cinema', 'supermarket', 'swimming pool'],
                                   'q': 'My father wants some grapes and beans. He goes to the ____.',
                                   't': 'mcq'},
                                  {'id': 'r2.16',
                                   'o': ['run quickly', 'roar loudly', 'sing merrily'],
                                   'q': 'Why do you like birds? – Because they ____.',
                                   't': 'mcq'}]},
                       {'id': 'r3',
                        'instr': 'Question 6. Read and tick True or False (đọc đoạn văn, chọn True hoặc False).',
                        'items': [{'id': 'r3.17', 'q': 'Son and Huong are taking a photo.', 't': 'tf'},
                                  {'id': 'r3.18', 'q': 'Kiem is putting a tent.', 't': 'tf'},
                                  {'id': 'r3.19', 'q': 'Hao wants to cook some food.', 't': 'tf'}],
                        'passage': '<p>The weather is sunny today. We are at the campsite. Son is putting up a tent with Kiem. Dao and Huong are taking a '
                                   'photo. Hao is building a campfire to cook some food. Thuy Duong is singing a song. They are having a lot of fun '
                                   'together.</p><img src="../../../../assets/lop4_on2_de5/p6.png" alt="Hình" style="max-width:220px;height:auto">'},
                       {'id': 'w1',
                        'instr': 'Question 7. Reorder the letters to make a word (sắp xếp các chữ cái thành từ đúng, nhìn tranh).',
                        'items': [{'id': 'w1.20', 'img': 'w1_1.png', 'q': 'c o p i e l a n m → {_}', 't': 'fill'},
                                  {'id': 'w1.21', 'img': 'w1_2.png', 'q': 'k o p s o b o h → {_}', 't': 'fill'},
                                  {'id': 'w1.22', 'img': 'w1_3.png', 'q': 'i l c o d e r c o → {_}', 't': 'fill'},
                                  {'id': 'w1.23', 'img': 'w1_4.png', 'q': 'd o u c l y → {_}', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Question 8. Reorder the words to make complete sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w2.24',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'Turn', 'to', 'get', 'stall.', 'to', 'left', 'food']},
                                  {'id': 'w2.25', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['much', 'this', 'is', 'bag?', 'How']},
                                  {'id': 'w2.26', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'Because', 'roar', 'lions', 'loudly.']},
                                  {'id': 'w2.27',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Sundays.', 'My', 'washes', 'clothes', 'the', 'mother', 'on']}]},
                       {'id': 'w3',
                        'instr': 'Question 9. Answer the questions with the given words (dùng từ gợi ý để trả lời).',
                        'items': [{'id': 'w3.28', 'q': 'What’s the weather like today? (sunny and windy)<br>→ {_}', 't': 'fill'},
                                  {'id': 'w3.29', 'q': 'How can I get to the cinema? (go straight, turn right)<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 5',
 'unit': 'OnHK2'}
