# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r1-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ["I'm fine, thank you.", "I'm Mike.", "I'm from Australia.", "He's from Australia."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where\'s Mike from?"',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ["Where's she from?", "Where's he from?", 'Where are you from?', "Where're they from?"],
                                   'plain': True,
                                   'q': 'Câu “I’m from Malaysia” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ["Where's he from?", 'What time do you get up?', 'What day is it today?', 'What time is it?'],
                                   'plain': True,
                                   'q': 'Câu: “It\'s eight thirty" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ["I get up at six o'clock.",
                                         'She gets up at five thirty.',
                                         "Let's have breakfast.",
                                         "I have breakfast at seven o'clock."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What time do you have breakfast?"',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['What time is it?', 'What day is it today?', 'What do you do on Wednesdays?', 'What time does she go to school?'],
                                   'plain': True,
                                   'q': "Câu “It's Saturday” trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['I visit my grandparents on Saturdays.',
                                         'He does his housework.',
                                         'She does housework on Saturdays.',
                                         'She goes to school on Mondays.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does Mai do on Saturdays?"',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ["It's in May.", "It's Monday today.", "She gets up at six o'clock.", 'She studies at school.'],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “When's her birthday?”?",
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['I want some lemonade.', 'He wants some water.', 'They want some grapes.', 'She wants some milk.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does Lan want to drink?”?',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ["No, I can't.", 'Yes, I can.', "No, he can't.", "No, she can't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Can she ride a horse?”?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Can he ride a bike?', 'Can she play the piano?', 'Can you ride a bike?', 'Can Nam ride a horse?'],
                                   'plain': True,
                                   'q': 'Câu: “No, she can’t” trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['What', 'Where', 'When', 'How'], 'plain': True, 'q': 'A: _____________ is Laura from?', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['is', 'am', 'are', 'does'], 'plain': True, 'q': 'Mary _____________ from England.', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['What', 'When', 'Where', 'Why'], 'plain': True, 'q': '_____________ day is it today, Linh?', 't': 'mcq'},
                                  {'id': 'b.4',
                                   'o': ["It's Sunday today.", 'I do housework.', "She's from Thailand.", 'I go to school on Mondays.'],
                                   'plain': True,
                                   'q': 'A: What do you do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['She wants to drink some lemonade.', 'I want some grapes.', "It's in December.", 'She wants some chips.'],
                                   'plain': True,
                                   'q': 'A: What does Mai want to eat?',
                                   't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ["It's in November.", 'I want some juice.', 'Linh wants some water.', 'I study at school.'],
                                   'plain': True,
                                   'q': "A: When's your birthday, Linh?",
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['in', 'at', 'on', 'with'],
                                   'plain': True,
                                   'q': 'A: What does Mai do _____________ Sunday mornings?',
                                   't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['Saturday', 'today', 'December', 'afternoon'],
                                   'plain': True,
                                   'q': 'A: What do you do on Sunday _____________, Ben?',
                                   't': 'mcq'},
                                  {'id': 'b.9', 'o': ['am', 'do', 'can', "can't"], 'plain': True, 'q': 'A: Can you ride a bike?', 't': 'mcq'},
                                  {'id': 'b.10', 'o': ['can', "can't", 'is', "isn't"], 'plain': True, 'q': 'A: Can Lan swim _____________?', 't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['Where are you from, Mary?',
                                            'What time does Lan go to school?',
                                            'What do you do on Tuesdays, Lan?',
                                            'What do you want to drink, Nam?',
                                            'Can you play the guitar, Nam?'],
                                   'o': ['I go to school.', "I'm from England.", "No, I can't.", "She goes to school at seven o'clock.", 'I want some water.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['night', 'morning', 'bye'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['from', 'in', 'at'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['Australian', 'Korean', 'England'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['Japan', 'English', 'Korea'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['When', 'Who', 'Where'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': "Mary: Good <b>(1)&nbsp;______</b>. I'm Mary.<br>Lan: Hi, Mary. I'm Lan. Are you <b>(2)&nbsp;______</b> Australia?<br>Mary: "
                                   "No, I'm not. I'm from <b>(3)&nbsp;______</b>.<br>Lan: Wow. So you're <b>(4)&nbsp;______</b>.<br>Mary: Yes, I am. And you? "
                                   "<b>(5)&nbsp;______</b> are you from?<br>Lan: I'm from Vietnam."}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and choose the correct answers. (Đọc và chọn đáp án đúng.)',
                        'items': [{'id': 'e.1', 'o': ['Australian', 'English', 'Thai'], 'plain': True, 'q': 'Mary is _______________.', 't': 'mcq'},
                                  {'id': 'e.2', 'o': ['five', 'nine', 'eleven'], 'plain': True, 'q': 'Mary is __________ years old.', 't': 'mcq'},
                                  {'id': 'e.3',
                                   'o': ['from Monday to Saturday', 'from Monday to Friday', 'from Tuesday to Sunday'],
                                   'plain': True,
                                   'q': 'Mary goes to school __________.',
                                   't': 'mcq'},
                                  {'id': 'e.4',
                                   'o': ['on Monday, Wednesday and Friday afternoons',
                                         'on Monday, Wednesday and Friday evenings',
                                         'on Monday and Tuesday evenings'],
                                   'plain': True,
                                   'q': 'Mary goes to the English class __________.',
                                   't': 'mcq'},
                                  {'id': 'e.5',
                                   'o': ['does her homework', 'goes to the Martial Arts Club', 'go to the English class'],
                                   'plain': True,
                                   'q': 'On Tuesday, Thursday and Saturday evenings, Mary __________.',
                                   't': 'mcq'},
                                  {'id': 'e.6',
                                   'o': ['cook / helps her parents',
                                         'does housework / goes to the beach with her friends',
                                         'does housework / goes to the park'],
                                   'plain': True,
                                   'q': 'On Sundays, Mary __________ in the morning and ___________ in the afternoon.',
                                   't': 'mcq'}],
                        'passage': "Hi, my name is Mary. I'm from England. I'm English. I'm nine years old. I'm a pupil at Oxford Primary School. I go to "
                                   'school from Monday to Saturday. On Monday, Wednesday and Friday evenings, I go to the English class. On Tuesday, Thursday '
                                   'and Saturday evenings, I do my homework. On Sundays, I do housework in the morning and go to the beach with my friends in '
                                   'the afternoon.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Where', 'is', 'from?', 'Nam']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['eight', 'is', 'Mai', 'years', 'old.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['does', 'have', 'she', 'breakfast?', 'What', 'time']},
                                  {'id': 'f.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['school.', 'at', 'They', "o'clock", 'lunch', 'have', 'eleven', 'at']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['on', 'Sundays?', 'What', 'do', 'does', 'Lan']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['does', 'Mary', 'on', 'Sundays?', 'do', 'What']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'doing,', 'you', 'What', 'Ben?']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['birthday?', "When's", "brother's", 'your']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['piano?', 'the', 'Lan', 'play', 'Can']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['sing,', 'can', 'but', 'she', "can't", 'She', 'dance.']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '',
 'title': 'Review 1: Luyện tập',
 'unit': 'Review1'}
