# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u7-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Science', 'you', 'have', 'Do', 'on', 'Mondays?']},
                                  {'id': 't1.2',
                                   'o': ['When do you have science?',
                                         'What subjects do you have today?',
                                         'Do you have music today?',
                                         'What subjects do you have tomorrow?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Hôm nay bạn có những môn học gì?”?',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: When ____________ you have English?', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Yes, she does.',
                                         'Yes, I do.',
                                         'I have Maths, Vietnamese and Science.',
                                         'I have it on Monday and Thursdays.',
                                         "It's Wednesday."],
                                   'plain': True,
                                   'q': 'When do you have English?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['in', 'on', 'at', 'to'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: I have it _____ Thurdays and Saturdays.',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['have', 'do', 'you', 'music?', 'When']},
                                  {'id': 't1.7',
                                   'o': ['When do you have Vietnamese?',
                                         'What subjects do you have today?',
                                         'Do you have music today?',
                                         'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu “No, I don’t” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['subject', 'subjects', 'maths', 'art'],
                                   'plain': True,
                                   'q': 'What ____________ do you have today?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['Yes, she does.',
                                         'Yes, I do.',
                                         'I have Maths, Vietnamese and Science.',
                                         'I have it on Monday and Thursdays.',
                                         "It's Wednesday."],
                                   'plain': True,
                                   'q': 'Does she have English today?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['do', 'are', "aren't", "don't"],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: When _____ you have Maths?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['music', 'Saturdays.', 'on', 'have', 'I']},
                                  {'id': 't1.12',
                                   'o': ['Khi nào bạn có môn Khoa học?',
                                         'Hôm nay bạn có môn Khoa học không?',
                                         'Hôm nay bạn có môn học gì?',
                                         'Hôm nay bạn có môn Tiếng Việt không?'],
                                   'plain': True,
                                   'q': 'Câu “Do you have Science today?" có nghĩa là?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['today', 'yesterday', 'Friday', 'Monday?'],
                                   'plain': True,
                                   'q': 'Do you have English _________?',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['every', 'Vietnamese', 'day.', 'I', 'have']},
                                  {'id': 't1.15',
                                   'o': ['Yes, I do.', "No, I don't.", 'I have it on Tuesday and Tuesdays.', 'I have Maths and Vietnamese.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “When do you have Maths?”?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['Wednesday', 'Wednesdays', 'Saturday', 'Thursday'],
                                   'plain': True,
                                   'q': 'I have Art on ___________ and Fridays.',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Art?', 'you', 'do', 'have', 'When']},
                                  {'id': 't1.18',
                                   'o': ['Có phải hôm nay bạn có môn toán không?',
                                         'Khi nào bạn có môn Khoa học?',
                                         'Tôi có môn Toán mỗi ngày.',
                                         'Hôm nay bạn có những môn gì?'],
                                   'plain': True,
                                   'q': 'Câu: “What subjects do you have today?” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ["don't", 'am not', 'are', "aren't"],
                                   'plain': True,
                                   'q': 'A: Do you have Vietnamese today?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['today.', 'and', 'Maths', 'have', 'We', 'Vietnamese']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 7 – Our timetable: Kiểm tra 2',
 'unit': 7}
