# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk2-de1',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'I. Listen to the sounds and circle the correct words. (nghe âm, chọn từ có âm đó).',
                        'items': [{'id': 'l1.1', 'o': ['farmer', 'factory', 'nurse'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['long', 'round', 'farm'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['wash', 'clothes', 'watch'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['cinema', 'go', 'cook'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'}]},
                       {'id': 'l2',
                        'instr': 'II. Listen and circle the correct pictures. (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'r1',
                        'instr': 'III. Circle the correct answers. (nhìn tranh, chọn câu đúng).',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['He plays tennis.', 'He does yoga.', 'He goes swimming.'],
                                   'q': 'What does he do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 'r1.10',
                                   'img': 'r1_2.png',
                                   'o': ['I wash the dishes in the evening.', 'I wash the dishes in the morning.', 'I wash the dishes in the afternoon.'],
                                   'q': 'When do you wash the dishes?',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['He works in a factory.', 'He works on a farm.', 'He works in a hospital.'],
                                   'q': 'Where does he work?',
                                   't': 'mcq'},
                                  {'id': 'r1.12',
                                   'img': 'r1_4.png',
                                   'o': ['He goes to the sports centre.', 'He goes to the shopping centre.', 'He goes to the cinema.'],
                                   'q': 'Where does he go on Saturdays?',
                                   't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'IV. Fill in the blanks. (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'r2.13', 'img': 'r2_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.14', 'img': 'r2_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'img': 'r2_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'img': 'r2_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Hello, my name is Emma. I am 9 years old. I am a student. My mother is a <b>(1) ______</b> She works in a <b>(2) '
                                   '______</b> My mother loves to take care of old people. My father is a <b>(3) ______</b> He helps protect the town people. '
                                   'My older sister is an <b>(4) ______</b> She works in an office. They all love their jobs.</p>'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 2 – Đề 1',
 'unit': 'GiuaKy2'}
