# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u18-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['shop', 'pet', 'bookshop.', 'is', 'The', 'opposite', 'the']},
                                  {'id': 't1.2',
                                   'o': ["It's ninety thousand dong.", "It's over there.", "It's opposite the gift shop.", 'It says "Stop".'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “How much is the school bag?”',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'o': ['this', 'that', 'these', 'they'], 'plain': True, 'q': 'How much are ___________ trousers?', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ["It's near the gift shop.",
                                         'Go straight and turn left at the corner.',
                                         "It's ninety thousand dong.",
                                         "Great! Let's go.",
                                         "They're one hundred and ninety thousand dong."],
                                   'plain': True,
                                   'q': 'How can I get to the bookshop?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['between', 'those', 'over there', 'it', 'get', 'near'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____ the bookshop and the bakery.",
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['opposite', 'bakery', 'is', 'the', 'The', 'museum.']},
                                  {'id': 't1.7',
                                   'o': ['What do you do on Sundays?', 'What does it say?', 'How much is the T-shirt?', 'How many T-shirts are there?'],
                                   'plain': True,
                                   'q': "Câu “It's fifty thousand dong.” trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['behind', 'opposite', 'between', 'next'], 'plain': True, 'q': 'A: Where is the pet shop?', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ["It's near the gift shop.",
                                         'Go straight and turn left at the corner.',
                                         "It's ninety thousand dong.",
                                         "Great! Let's go.",
                                         "They're one hundred and ninety thousand dong."],
                                   'plain': True,
                                   'q': 'Do you want to go to the shopping center with me?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['between', 'those', 'over there', 'it', 'get', 'near'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: How much is _____?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'pants?', 'these', 'much', 'How']},
                                  {'id': 't1.12',
                                   'o': ["It's five thousand dong.", "It's on the desk.", "It's near the bookshop.", 'I want to buy a pen.'],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi “Where's the gift shop?”?",
                                   't': 'mcq'},
                                  {'id': 't1.13', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'How much ___________ that pen?', 't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['between', 'those', 'over there', 'it', 'get', 'near'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 6. A: How much are _____ shoes?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['dong.', 'thousand', 'are', 'and', 'forty', 'They', 'hundred', 'two']},
                                  {'id': 't1.16',
                                   'o': ['Tiệm bánh mì đối diện hiệu sách và cửa hàng thú cưng.',
                                         'Tiệm bánh mì ở gần hiệu sách và cửa hàng thú cưng.',
                                         'Tiệm bánh mì ở giữa hiệu sách và cửa hàng thú cứng.',
                                         'Tiệm bánh mì ở đằng sau hiệu sách và cửa hàng thú cứng.'],
                                   'plain': True,
                                   'q': 'Câu “The bakery is between the bookshop and the pet shop” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['next', 'between', 'in front', 'opposite'],
                                   'plain': True,
                                   'q': 'A: Where is the gift shop?',
                                   't': 'mcq'},
                                  {'id': 't1.18', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['shirt?', 'How', 'that', 'much', 'is']},
                                  {'id': 't1.19',
                                   'o': ['Trung tâm thể thao ở gần trung tâm mua sắm.',
                                         'Trung tâm thể thao ở đằng sau trung tâm mua sắm.',
                                         'Trung tâm thể thao đối diện trung tâm mua sắm.',
                                         'Trung tâm thể thao ở giữa trung tâm mua sắm.'],
                                   'plain': True,
                                   'q': 'Câu “The sports centre is opposite the shopping centre." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: How much _________ those dolls?', 't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 18 – At the shopping centre: Kiểm tra 2',
 'unit': 18}
