# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck1-de18',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'a1',
                        'instr': 'I. Listen and tick (nghe và chọn tranh đúng).',
                        'items': [{'id': 'a1.1', 'img': 'a1_1.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.2', 'img': 'a1_2.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.3', 'img': 'a1_3.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.4',
                                   'img': 'a1_4.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'a2',
                        'instr': 'II. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'a2.5', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.6', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.7', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.8', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de18/a2.png" alt="Tranh A-D">'},
                       {'id': 'a3',
                        'instr': 'III. Listen and tick or cross (nghe, nội dung nghe có khớp với tranh không?).',
                        'items': [{'id': 'a3.9', 'img': 'a3_1.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'},
                                  {'id': 'a3.10', 'img': 'a3_2.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'}]},
                       {'id': 'a4',
                        'instr': 'IV. Listen and write (nghe và điền từ).',
                        'items': [{'id': 'a4.11', 'q': 'A: When do you have {_}?<br>B: I have it on Wednesday.', 't': 'fill'},
                                  {'id': 'a4.12', 'q': 'Our sports day is in {_}.', 't': 'fill'}]},
                       {'id': 'b1',
                        'instr': 'I. Look, read and match (đọc câu và chọn tranh a–f).',
                        'items': [{'id': 'b1.13',
                                   'left': [{'t': 'A: How many playgrounds are there at your school? B: There is one.'},
                                            {'t': 'A: What do you do on Sundays? B: I do housework.'},
                                            {'t': 'I was on the beach yesterday.'},
                                            {'t': 'My birthday is in July.'},
                                            {'t': 'A: Why do you like music? B: Because I want to be a singer.'}],
                                   'o': ['a', 'b', 'c', 'd', 'e', 'f'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de18/b1.png" alt="Tranh a-f">'},
                       {'bank': ['draw', 'friends', 'ride', 'badminton', 'can’t', 'piano'],
                        'id': 'b2',
                        'instr': 'II. Read and complete the sentences (chọn từ trong khung).',
                        'items': [{'id': 'b2.14', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'b2.15', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'b2.16', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'b2.17', 'q': 'Chỗ trống (4): {_}', 't': 'fill'},
                                  {'id': 'b2.18', 'q': 'Chỗ trống (5): {_}', 't': 'fill'}],
                        'passage': '<p>Hello, everyone. My name is Uyen. At school, I have many (0) <u>friends</u>. We can do different things. Thu can play '
                                   '(1) ______, but she (2) ______ swim. Nam can roller skate, but he can’t (3) ______ a horse. Linh likes music so much. She '
                                   'can play both the (4) ______ and the guitar well. I can (5) ______, but I can’t play sports. We can all ride a bike. '
                                   'Everyday, we often go to school by bike together.</p>'},
                       {'id': 'c1',
                        'instr': 'I. Look and complete (nhìn tranh, điền từ).',
                        'items': [{'id': 'c1.19', 'img': 'c1_1.png', 'q': 'My friends want some {_}.', 't': 'fill'},
                                  {'id': 'c1.20', 'img': 'c1_2.png', 'q': 'I {_} at 6.45.', 't': 'fill'},
                                  {'id': 'c1.21', 'img': 'c1_3.png', 'q': 'I like art because I want to be a {_}.', 't': 'fill'},
                                  {'id': 'c1.22', 'img': 'c1_4.png', 'q': 'There are two {_} at my school.', 't': 'fill'},
                                  {'id': 'c1.23', 'img': 'c1_5.png', 'q': 'My friend, Hakim is from {_}.', 't': 'fill'}]},
                       {'id': 'c2',
                        'instr': 'Reorder the words (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'c2.24', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['music', 'on', 'have', 'Mondays.', 'I']},
                                  {'id': 'c2.25', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['birthday', 'is', 'My', 'in', 'August.']},
                                  {'id': 'c2.26', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['subject', 'art.', 'My', 'is', 'favourite']},
                                  {'id': 'c2.27', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['get', 'up', 'at', 'five', 'thirty.', 'I']},
                                  {'id': 'c2.28',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['at', 'school?', 'many', 'gardens', 'How', 'are', 'your', 'there']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 1 – Đề 18 (25-26)',
 'unit': 'CuoiKy1'}
