# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'How many people are there in your family?',
 'a.10': 'How many people are there in her family?',
 'a.2': 'What do you do?',
 'a.3': 'How many people are there in your family?',
 'a.4': 'She works on a farm.',
 'a.5': 'What does your father do?',
 'a.6': 'Cô ấy làm việc ở viện dưỡng lão.',
 'a.7': 'Mẹ tôi là nông dân.',
 'a.8': 'My mother works at a school.',
 'a.9': 'My sister is a teacher.',
 'b.1': 'does',
 'b.10': 'at a nursing home',
 'b.2': 'farmer',
 'b.3': 'worker',
 'b.4': 'Where',
 'b.5': 'What',
 'b.6': 'nurse',
 'b.7': 'in an office',
 'b.8': 'at a primary school',
 'b.9': 'on a farm',
 'c.1': {'blanks': [['I live in Nguyen Kiem Street.'], ['I live with my parents.'], ["I'm a worker."], ['I work at a factory.'], ["She's a nurse."]]},
 'd.1': 'have',
 'd.2': 'do',
 'd.3': 'sister',
 'd.4': 'work',
 'd.5': 'hospital',
 'd.6': 'brother',
 'd.7': 'Where',
 'd.8': 'factory',
 'e.1': 'four',
 'e.2': "He's a teacher.",
 'e.3': 'He works at a primary school.',
 'e.4': "She's an office worker.",
 'e.5': 'In an office.',
 'e.6': "He's a student.",
 'e.7': 'He studies at Hong Bang University.',
 'e.8': "He's a pupil.",
 'f.1': ['How many people are there in your family?'],
 'f.10': ['My grandfather works on a farm.'],
 'f.2': ['What does your mother do?'],
 'f.3': ["She's an office worker."],
 'f.4': ['Where does she work?'],
 'f.5': ['She works at a factory.'],
 'f.6': ['My father teaches at a primary school.'],
 'f.7': ['There are five people in my family.'],
 'f.8': ['My brother is a student.'],
 'f.9': ['He studies at a university.']}

EXPLANATIONS = {'a.1': 'Đáp án: How many people are there in your family?',
 'a.10': 'Đáp án: How many people are there in her family?',
 'a.2': 'Đáp án: What do you do?',
 'a.3': 'Đáp án: How many people are there in your family?',
 'a.4': 'Đáp án: She works on a farm.',
 'a.5': 'Đáp án: What does your father do?',
 'a.6': 'Đáp án: Cô ấy làm việc ở viện dưỡng lão.',
 'a.7': 'Đáp án: Mẹ tôi là nông dân.',
 'a.8': 'Đáp án: My mother works at a school.',
 'a.9': 'Đáp án: My sister is a teacher.',
 'b.1': 'Đáp án: does',
 'b.10': 'Đáp án: at a nursing home',
 'b.2': 'Đáp án: farmer',
 'b.3': 'Đáp án: worker',
 'b.4': 'Đáp án: Where',
 'b.5': 'Đáp án: What',
 'b.6': 'Đáp án: nurse',
 'b.7': 'Đáp án: in an office',
 'b.8': 'Đáp án: at a primary school',
 'b.9': 'Đáp án: on a farm',
 'c.1': "Where do you live? → I live in Nguyen Kiem Street.; Who do you live with? → I live with my parents.; What do you do? → I'm a worker.; Where do you "
        "work? → I work at a factory.; What does she do? → She's a nurse.",
 'd.1': 'Đáp án: have',
 'd.2': 'Đáp án: do',
 'd.3': 'Đáp án: sister',
 'd.4': 'Đáp án: work',
 'd.5': 'Đáp án: hospital',
 'd.6': 'Đáp án: brother',
 'd.7': 'Đáp án: Where',
 'd.8': 'Đáp án: factory',
 'e.1': 'Đáp án: four',
 'e.2': "Đáp án: He's a teacher.",
 'e.3': 'Đáp án: He works at a primary school.',
 'e.4': "Đáp án: She's an office worker.",
 'e.5': 'Đáp án: In an office.',
 'e.6': "Đáp án: He's a student.",
 'e.7': 'Đáp án: He studies at Hong Bang University.',
 'e.8': "Đáp án: He's a pupil.",
 'f.1': 'Câu đúng: How many people are there in your family?',
 'f.10': 'Câu đúng: My grandfather works on a farm.',
 'f.2': 'Câu đúng: What does your mother do?',
 'f.3': "Câu đúng: She's an office worker.",
 'f.4': 'Câu đúng: Where does she work?',
 'f.5': 'Câu đúng: She works at a factory.',
 'f.6': 'Câu đúng: My father teaches at a primary school.',
 'f.7': 'Câu đúng: There are five people in my family.',
 'f.8': 'Câu đúng: My brother is a student.',
 'f.9': 'Câu đúng: He studies at a university.'}
