# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['There are two buildings at our school.'],
 't1.10': 'are',
 't1.11': ['There are two villages not far from my school.'],
 't1.12': "It's Nguyen Du Primary School.",
 't1.13': 'How',
 't1.14': ['I love my school.'],
 't1.15': "What's the name of your school?",
 't1.16': 'Where',
 't1.17': "It's in the town.",
 't1.18': 'Where',
 't1.19': ['What is the name of your school?'],
 't1.2': 'How many playgrounds are there at your school?',
 't1.20': 'Where is your school?',
 't1.3': 'park',
 't1.4': 'are there',
 't1.5': ['There is a big playround there.'],
 't1.6': 'Our school is near two villages.',
 't1.7': 'is',
 't1.8': ['We can play sports in the playground.'],
 't1.9': 'Our school is in the mountains.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: There are two buildings at our school.',
 't1.10': 'Đáp án: are',
 't1.11': 'Câu đúng: There are two villages not far from my school.',
 't1.12': "Đáp án: It's Nguyen Du Primary School.",
 't1.13': 'Đáp án: How',
 't1.14': 'Câu đúng: I love my school.',
 't1.15': "Đáp án: What's the name of your school?",
 't1.16': 'Đáp án: Where',
 't1.17': "Đáp án: It's in the town.",
 't1.18': 'Đáp án: Where',
 't1.19': 'Câu đúng: What is the name of your school?',
 't1.2': 'Đáp án: How many playgrounds are there at your school?',
 't1.20': 'Đáp án: Where is your school?',
 't1.3': 'Đáp án: park',
 't1.4': 'Đáp án: are there',
 't1.5': 'Câu đúng: There is a big playround there.',
 't1.6': 'Đáp án: Our school is near two villages.',
 't1.7': 'Đáp án: is',
 't1.8': 'Câu đúng: We can play sports in the playground.',
 't1.9': 'Đáp án: Our school is in the mountains.'}
