# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u7-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['When do you have Maths?',
                                         'What subjects do you have today?',
                                         'How many playgrounds are there at your school?',
                                         "Where's your school?"],
                                   'plain': True,
                                   'q': 'Câu nào hỏi ai đó hôm nay có môn học gì?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ["What's", 'What', 'When', 'Where'],
                                   'plain': True,
                                   'q': 'A: ____________ the name of your school?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['Yes, she does.',
                                         'Yes, I do.',
                                         'I have Maths, Vietnamese and Science.',
                                         'I have it on Monday and Thursdays.',
                                         "It's Wednesday."],
                                   'plain': True,
                                   'q': 'What subjects do you have today?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['this', 'it', 'that', 'she'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What day is _____ today?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'have', 'do', 'subjects', 'What', 'today?']},
                                  {'id': 't1.6',
                                   'o': ['When do you have English?',
                                         "Where's your school?",
                                         'What subjects do you have today?',
                                         'When do you have Maths and English?'],
                                   'plain': True,
                                   'q': 'Câu “I have Maths and English." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['it', 'this', 'that', 'there'], 'plain': True, 'q': 'What day is ____________ today?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['Yes, she does.',
                                         'Yes, I do.',
                                         'I have Maths, Vietnamese and Science.',
                                         'I have it on Monday and Thursdays.',
                                         "It's Wednesday."],
                                   'plain': True,
                                   'q': 'Do you have Art today?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['am', 'am not', 'do', "don't"],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: No, I _____.',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['on', 'Wednesdays', 'I', 'Fridays.', 'English', 'have', 'and']},
                                  {'id': 't1.11',
                                   'o': ["Where's your school?", 'What subjects do you have today?', 'When do you have English?', 'Do you have English today?'],
                                   'plain': True,
                                   'q': 'Câu “I have it on Mondays, Tuesdays and Fridays." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['have', 'has', 'got', 'draw'], 'plain': True, 'q': 'Do you ____________ Art today?', 't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['Yes, she does.',
                                         'Yes, I do.',
                                         'I have Maths, Vietnamese and Science.',
                                         'I have it on Monday and Thursdays.',
                                         "It's Wednesday."],
                                   'plain': True,
                                   'q': 'What day is it today?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['What', 'When', 'How', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ do you have it?',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Mondays?', 'have', 'on', 'Do', 'Science', 'you']},
                                  {'id': 't1.16',
                                   'o': ['When do you have science?',
                                         'What subjects do you have today?',
                                         'Do you have music today?',
                                         'What subjects do you have tomorrow?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Hôm nay bạn có những môn học gì?”?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: When ____________ you have English?', 't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['Yes, she does.',
                                         'Yes, I do.',
                                         'I have Maths, Vietnamese and Science.',
                                         'I have it on Monday and Thursdays.',
                                         "It's Wednesday."],
                                   'plain': True,
                                   'q': 'When do you have English?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['in', 'on', 'at', 'to'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: I have it _____ Thurdays and Saturdays.',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'have', 'music?', 'When', 'you']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 7 – Our timetable: Kiểm tra 1',
 'unit': 7}
