# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['Is there a water park near here?'],
 't1.10': 'get',
 't1.11': ['What does it say?'],
 't1.12': 'Có một sạp bán thực phẩm trên đường Nguyễn Thái Sơn.',
 't1.13': 'green',
 't1.14': ['We want to go to the bookshop.'],
 't1.15': 'How can she get to the shopping centre?',
 't1.16': 'food stall',
 't1.17': ['There is a bakery in Nguyen Thai Son Street.'],
 't1.18': 'What does he want to buy at the bookshop?',
 't1.19': 'cinema',
 't1.2': 'Turn left.',
 't1.20': ['How can we get to the campsite?'],
 't1.3': 'cinema',
 't1.4': 'I want to buy some clothes.',
 't1.5': 'bookshop',
 't1.6': ['There is a food stall in Pham Van Dong Street.'],
 't1.7': 'How can I get to the bookshop?',
 't1.8': 'stop',
 't1.9': "Great! Let's go."}

EXPLANATIONS = {'t1.1': 'Câu đúng: Is there a water park near here?',
 't1.10': 'Đáp án: get',
 't1.11': 'Câu đúng: What does it say?',
 't1.12': 'Đáp án: Có một sạp bán thực phẩm trên đường Nguyễn Thái Sơn.',
 't1.13': 'Đáp án: green',
 't1.14': 'Câu đúng: We want to go to the bookshop.',
 't1.15': 'Đáp án: How can she get to the shopping centre?',
 't1.16': 'Đáp án: food stall',
 't1.17': 'Câu đúng: There is a bakery in Nguyen Thai Son Street.',
 't1.18': 'Đáp án: What does he want to buy at the bookshop?',
 't1.19': 'Đáp án: cinema',
 't1.2': 'Đáp án: Turn left.',
 't1.20': 'Câu đúng: How can we get to the campsite?',
 't1.3': 'Đáp án: cinema',
 't1.4': 'Đáp án: I want to buy some clothes.',
 't1.5': 'Đáp án: bookshop',
 't1.6': 'Câu đúng: There is a food stall in Pham Van Dong Street.',
 't1.7': 'Đáp án: How can I get to the bookshop?',
 't1.8': 'Đáp án: stop',
 't1.9': "Đáp án: Great! Let's go."}
