# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'What time does she go to bed?',
 't1.10': 'Cô ấy đi học lúc mấy giờ?',
 't1.11': 'has',
 't1.12': ['I do my homework and go to bed at ten.'],
 't1.13': 'What time is it?',
 't1.14': 'at',
 't1.15': "It's ten o'clock.",
 't1.16': 'What',
 't1.17': ['What time is it, Mai?'],
 't1.18': "It's three fifteen.",
 't1.19': 'does',
 't1.2': 'watch',
 't1.20': 'I get up at six fifteen.',
 't1.3': ['What time do Phong and Quan go to school?'],
 't1.4': 'I go to bed at ten fifteen.',
 't1.5': 'go',
 't1.6': ["They have lunch at school at twelve o'clock."],
 't1.7': 'What time do you have breakfast?',
 't1.8': 'have',
 't1.9': ['What time do you do your homework?']}

EXPLANATIONS = {'t1.1': 'Đáp án: What time does she go to bed?',
 't1.10': 'Đáp án: Cô ấy đi học lúc mấy giờ?',
 't1.11': 'Đáp án: has',
 't1.12': 'Câu đúng: I do my homework and go to bed at ten.',
 't1.13': 'Đáp án: What time is it?',
 't1.14': 'Đáp án: at',
 't1.15': "Đáp án: It's ten o'clock.",
 't1.16': 'Đáp án: What',
 't1.17': 'Câu đúng: What time is it, Mai?',
 't1.18': "Đáp án: It's three fifteen.",
 't1.19': 'Đáp án: does',
 't1.2': 'Đáp án: watch',
 't1.20': 'Đáp án: I get up at six fifteen.',
 't1.3': 'Câu đúng: What time do Phong and Quan go to school?',
 't1.4': 'Đáp án: I go to bed at ten fifteen.',
 't1.5': 'Đáp án: go',
 't1.6': "Câu đúng: They have lunch at school at twelve o'clock.",
 't1.7': 'Đáp án: What time do you have breakfast?',
 't1.8': 'Đáp án: have',
 't1.9': 'Câu đúng: What time do you do your homework?'}
