# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'c',
 'l1.2': 'e',
 'l1.3': 'b',
 'l1.4': 'd',
 'l2.5': 'A',
 'l2.6': 'C',
 'l2.7': 'B',
 'l2.8': 'C',
 'l3.10': ['short hair'],
 'l3.11': ['in the morning'],
 'l3.12': ['noisy road', 'noisy'],
 'l3.9': ['cinema'],
 'r1.13': {'blanks': [['e. She is slim.'], ['d. He cooks meals.'], ['f. Great! Let’s go.'], ['b. It says “turn left”.'], ['a. It’s fifty thousand dong.']]},
 'r2.14': 'F',
 'r2.15': 'T',
 'r2.16': 'T',
 'r2.17': 'T',
 'r2.18': 'F',
 'r3.19': ['seventy thousand dong', 'seventy thousand', '70,000 dong', '70.000 dong'],
 'r3.20': ['wash the dishes', 'wash dishes', 'wash my dishes', 'do the dishes'],
 'r3.21': ['Sorry, I can’t', 'Sorry, I can not', 'No, I don’t', 'No, thanks'],
 'r3.22': ['quickly'],
 'w1.23': ['My grandfather has big eyes.'],
 'w1.24': ['I do the housework in the afternoon.'],
 'w1.25': ['It was rainy in Sapa last Sunday.'],
 'w1.26': ['The food shop is between the sports shop and the bookshop.', 'The sports shop is between the food shop and the bookshop.'],
 'w1.27': ['They like lions because they roar loudly.']}

EXPLANATIONS = {'l1.1': 'Theo bài nghe: “What do you do in the morning? – I wash my clothes.” → tranh c.',
 'l1.2': 'Theo bài nghe: “What does he do on Sundays? – He watches films.” → tranh e.',
 'l1.3': 'Theo bài nghe: “What does it say? – It says turn left.” → tranh b.',
 'l1.4': 'Theo bài nghe: “Do you want to go to the food stall? – Great! Let’s go!” → tranh d.',
 'l2.5': 'Theo bài nghe: “What does your mother do? – She’s a farmer.” → tranh A.',
 'l2.6': 'Theo bài nghe: “Where does he go on Saturdays? – He goes to the Sports Centre.” → tranh C.',
 'l2.7': 'Theo bài nghe: “What was the weather like last weekend? – It was rainy.” → tranh B.',
 'l2.8': 'Theo bài nghe: “When do you watch TV? – I watch TV at noon.” → tranh C.',
 'l3.10': 'Theo bài nghe: “She has short hair.” → short hair',
 'l3.11': 'Theo bài nghe: “I watch TV in the morning.” → in the morning',
 'l3.12': 'Theo bài nghe: “It’s a noisy road.” → noisy road',
 'l3.9': 'Theo bài nghe: “She goes to the cinema.” → cinema',
 'r1.13': 'Đáp án: 1–e, 2–d, 3–f, 4–b, 5–a (ghép theo nghĩa).',
 'r2.14': 'Đoạn văn: “I usually go to the cinema in the morning” → No (False).',
 'r2.15': 'Đoạn văn: “She is very slim with a round face.” → Yes (True).',
 'r2.16': 'Đoạn văn: “the bookshop near our house” → Yes (True).',
 'r2.17': 'Đoạn văn: “It’s thirty thousand dong.” → Yes (True).',
 'r2.18': 'Đoạn văn: “We love lions because they roar loudly.” (lions, không phải peacocks) → No (False).',
 'r3.19': 'Áo có giá 70.000đ: seventy thousand dong.',
 'r3.20': 'Tranh cô bé rửa bát: wash the dishes.',
 'r3.21': 'Biển “NO” → từ chối: Sorry, I can’t.',
 'r3.22': 'Giraffes chạy nhanh: Because they run quickly.',
 'w1.23': 'Câu đúng: My grandfather has big eyes.',
 'w1.24': 'Câu đúng: I do the housework in the afternoon.',
 'w1.25': 'Câu đúng: It was rainy in Sapa last Sunday.',
 'w1.26': 'Câu đúng: The food shop is between the sports shop and the bookshop.',
 'w1.27': 'Câu đúng: They like lions because they roar loudly.'}
