# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'q1.1': 'C',
 'q1.2': 'C',
 'q1.3': 'A',
 'q1.4': 'D',
 'q2.5': 'A',
 'q2.6': 'A',
 'q2.7': 'A',
 'q2.8': 'B',
 'q3.10': 'F',
 'q3.11': 'T',
 'q3.12': 'T',
 'q3.9': 'T',
 'q4.13': 'B',
 'q4.14': 'A',
 'q4.15': 'D',
 'q5.16': ["What's your favourite subjects?"],
 'q5.17': ['There are three buildings.'],
 'q5.18': ['There is one garden.'],
 'q5.19': ['Can he draw?'],
 'q5.20': ['Where were you last summer?'],
 'q5.21': ['I was in Sydney.'],
 'q5.22': ['Were you at the campsite last weekend?'],
 'q5.23': ['Is your sports day in December?'],
 'q5.24': ['Why do you like maths?'],
 'q5.25': ['Because I want to be a maths teacher.'],
 'q6.26': 'B',
 'q6.27': 'B',
 'q6.28': 'A',
 'q6.29': 'A',
 'q6.30': 'A'}

EXPLANATIONS = {'q1.1': 'Đáp án: C. Tranh c',
 'q1.2': 'Đáp án: C. Tranh a',
 'q1.3': 'Đáp án: A. Tranh d',
 'q1.4': 'Đáp án: D. Tranh b',
 'q2.5': 'Đáp án: A. Tick (✓)',
 'q2.6': 'Đáp án: A. Tick (✓)',
 'q2.7': 'Đáp án: A. Tick (✓)',
 'q2.8': 'Đáp án: B. Cross (✗)',
 'q3.10': 'Đáp án: False (theo đáp án của đề).',
 'q3.11': 'Đáp án: True (theo đáp án của đề).',
 'q3.12': 'Đáp án: True (theo đáp án của đề).',
 'q3.9': 'Đáp án: True (theo đáp án của đề).',
 'q4.13': 'Đáp án: B. Fridays',
 'q4.14': 'Đáp án: A. on',
 'q4.15': 'Đáp án: D. like',
 'q5.16': "Câu đúng: What's your favourite subjects?",
 'q5.17': 'Câu đúng: There are three buildings.',
 'q5.18': 'Câu đúng: There is one garden.',
 'q5.19': 'Câu đúng: Can he draw?',
 'q5.20': 'Câu đúng: Where were you last summer?',
 'q5.21': 'Câu đúng: I was in Sydney.',
 'q5.22': 'Câu đúng: Were you at the campsite last weekend?',
 'q5.23': 'Câu đúng: Is your sports day in December?',
 'q5.24': 'Câu đúng: Why do you like maths?',
 'q5.25': 'Câu đúng: Because I want to be a maths teacher.',
 'q6.26': 'Đáp án: B. No',
 'q6.27': 'Đáp án: B. No',
 'q6.28': 'Đáp án: A. Yes',
 'q6.29': 'Đáp án: A. Yes',
 'q6.30': 'Đáp án: A. Yes'}
