# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck1-de4',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'gi',
                        'instr': 'I. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'gi.1', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.2', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.3', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.4', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de4/gi.png" alt="Tranh a–d">'},
                       {'id': 'gii',
                        'instr': 'II. Listen and draw lines (nghe và nối nhân vật với tranh).',
                        'items': [{'id': 'gii.5',
                                   'left': [{'img': 'gii_l1.png', 't': 'Sue'},
                                            {'img': 'gii_l2.png', 't': 'Anna'},
                                            {'img': 'gii_l3.png', 't': 'Tom'},
                                            {'img': 'gii_l4.png', 't': 'Bill'}],
                                   'o': ['a', 'b', 'c', 'd'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de4/gii.png" alt="Tranh a–d">'},
                       {'id': 'giii',
                        'instr': 'III. Listen and complete (nghe và điền từ).',
                        'items': [{'id': 'giii.6', 'q': '– Were you on the {_} last weekend?<br>– Yes, I was.', 't': 'fill'},
                                  {'id': 'giii.7', 'q': '– What’s your favourite subject?<br>– It’s {_}.', 't': 'fill'},
                                  {'id': 'giii.8', 'q': '– When do you have maths?<br>– I have it on {_}.', 't': 'fill'},
                                  {'id': 'giii.9', 'q': '– Where’s your school?<br>– It’s in the {_}.', 't': 'fill'}]},
                       {'id': 'giv',
                        'instr': 'IV. Read and choose A, B or C (nhìn tranh, chọn đáp án đúng).',
                        'items': [{'id': 'giv.10',
                                   'img': 'giv_1.png',
                                   'o': ['I listen to music.', 'I study at school.', 'I do housework.'],
                                   'q': 'What do you do on Saturdays?',
                                   't': 'mcq'},
                                  {'id': 'giv.11',
                                   'img': 'giv_2.png',
                                   'o': ['It was in Bangkok.', 'It’s in the village.', 'It was at the beach.'],
                                   'q': 'Where’s your school?',
                                   't': 'mcq'},
                                  {'id': 'giv.12',
                                   'img': 'giv_3.png',
                                   'o': ['No, it is.', 'Yes, it is.', 'No, it isn’t.'],
                                   'q': 'Is your sports day in July?',
                                   't': 'mcq'},
                                  {'id': 'giv.13',
                                   'img': 'giv_4.png',
                                   'o': ['I was at the campsite.', 'I was in the countryside.', 'I was in the city.'],
                                   'q': 'Where were you last summer?',
                                   't': 'mcq'}]},
                       {'id': 'gv',
                        'instr': 'V. Write suitable questions for the answers given (nhìn tranh, viết câu hỏi phù hợp).',
                        'items': [{'id': 'gv.14',
                                   'img': 'gv_1.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>Because I want to be an English teacher.</i><br>{_}',
                                   't': 'fill'},
                                  {'id': 'gv.15', 'img': 'gv_2.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>I have it on Mondays.</i><br>{_}', 't': 'fill'},
                                  {'id': 'gv.16',
                                   'img': 'gv_3.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>There are two playgrounds at my school.</i><br>{_}',
                                   't': 'fill'}]},
                       {'id': 'gvi',
                        'instr': 'VI. Read and write T (True) or F (False) (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'gvi.17', 'q': 'She usually goes to school by bike.', 't': 'tf'},
                                  {'id': 'gvi.18', 'q': 'She likes Mondays because she has English.', 't': 'tf'},
                                  {'id': 'gvi.19', 'q': 'When she goes home, she does housework.', 't': 'tf'}],
                        'passage': '<p>Monday is my favourite day! Here is what I usually do. I get up, eat my breakfast and go to school at half past seven. '
                                   'I usually take a bus, but sometimes I ride my bike. I like Mondays because we have English. It’s my favourite subject! I '
                                   'always eat lunch at the school canteen. In the afternoon, I have music and maths. They are interesting! Then I go home and '
                                   'do my homework. Then I watch TV with my dad before having dinner.</p>'},
                       {'id': 'gvii',
                        'instr': 'VII. Fill in the blanks (điền từ vào chỗ trống, nhìn tranh).',
                        'items': [{'id': 'gvii.20', 'img': 'gvii_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'gvii.21', 'img': 'gvii_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'gvii.22', 'img': 'gvii_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'gvii.23', 'img': 'gvii_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Hello, my name is Sarah. I am ten years old. I’m from <b>(1) ______</b> I study in a school in London. There is a big '
                                   '<b>(2) ______</b> at my school. My favourite subject is <b>(3) ______</b> I also like computers a lot! There are two '
                                   '<b>(4) ______</b> where we learn IT every Wednesday. After school, I often go for a walk in the park with my friends.</p>'},
                       {'bank': ['music', 'December', 'Sydney', 'mountains'],
                        'id': 'gviii',
                        'instr': 'VIII. Write suitable answers to the questions using the given words (dùng từ cho sẵn để trả lời).',
                        'items': [{'id': 'gviii.24', 'q': 'When is your sports day?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.25', 'q': 'Where were you last summer?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.26', 'q': 'What subjects do you have today?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.27', 'q': 'Where’s your school?<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 1 – Đề 4',
 'unit': 'CuoiKy1'}
