# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'They are giraffes.',
 'a.10': 'They are lions.',
 'a.2': 'Because they roar loudly.',
 'a.3': 'What are these animals?',
 'a.4': 'Because they dance beautifully.',
 'a.5': 'Những con hươu cao cổ này chạy nhanh.',
 'a.6': 'Những con công này múa đẹp.',
 'a.7': "They're giraffes.",
 'a.8': "They're peacocks.",
 'a.9': 'Why do you like birds?',
 'b.1': 'are',
 'b.10': 'loudly',
 'b.2': 'do',
 'b.3': 'Why',
 'b.4': 'because they',
 'b.5': 'they',
 'b.6': 'scary',
 'b.7': 'hippos',
 'b.8': 'hippos',
 'b.9': 'does',
 'c.1': {'blanks': [['They are lions.'],
                    ['Because they dance beautifully.'],
                    ['Because they are scary.'],
                    ['I want to see giraffes.'],
                    ['He wants to see hippos.']]},
 'd.1': 'giraffes',
 'd.2': 'What',
 'd.3': 'peacocks',
 'd.4': 'Why',
 'd.5': 'like',
 'd.6': 'hippos',
 'd.7': 'strong',
 'e.1': 'peacocks',
 'e.2': 'birds',
 'e.3': 'they look strong',
 'e.4': 'they roar loudly.',
 'e.5': 'crocodiles',
 'f.1': ['What are those animals, Minh?'],
 'f.10': ['She likes hippos because they look strong.'],
 'f.2': ['They are giraffes.'],
 'f.3': ['Those giraffes are running quickly.'],
 'f.4': ['Those lions are roaring loudly.'],
 'f.5': ['The giraffes have long necks and legs.'],
 'f.6': ['She likes birds because they sing merrily.'],
 'f.7': ['Why do you like peacocks?'],
 'f.8': ['I like peacocks because they dance beautifully.'],
 'f.9': ['What animals does she want to see?']}

EXPLANATIONS = {'a.1': 'Đáp án: They are giraffes.',
 'a.10': 'Đáp án: They are lions.',
 'a.2': 'Đáp án: Because they roar loudly.',
 'a.3': 'Đáp án: What are these animals?',
 'a.4': 'Đáp án: Because they dance beautifully.',
 'a.5': 'Đáp án: Những con hươu cao cổ này chạy nhanh.',
 'a.6': 'Đáp án: Những con công này múa đẹp.',
 'a.7': "Đáp án: They're giraffes.",
 'a.8': "Đáp án: They're peacocks.",
 'a.9': 'Đáp án: Why do you like birds?',
 'b.1': 'Đáp án: are',
 'b.10': 'Đáp án: loudly',
 'b.2': 'Đáp án: do',
 'b.3': 'Đáp án: Why',
 'b.4': 'Đáp án: because they',
 'b.5': 'Đáp án: they',
 'b.6': 'Đáp án: scary',
 'b.7': 'Đáp án: hippos',
 'b.8': 'Đáp án: hippos',
 'b.9': 'Đáp án: does',
 'c.1': "What are these animals? → They are lions.; Why do you like peacocks? → Because they dance beautifully.; Why doesn't Lan like crocodiles? → Because "
        'they are scary.; What animals do you want to see? → I want to see giraffes.; What animals does Nam want to see? → He wants to see hippos.',
 'd.1': 'Đáp án: giraffes',
 'd.2': 'Đáp án: What',
 'd.3': 'Đáp án: peacocks',
 'd.4': 'Đáp án: Why',
 'd.5': 'Đáp án: like',
 'd.6': 'Đáp án: hippos',
 'd.7': 'Đáp án: strong',
 'e.1': 'Đáp án: peacocks',
 'e.2': 'Đáp án: birds',
 'e.3': 'Đáp án: they look strong',
 'e.4': 'Đáp án: they roar loudly.',
 'e.5': 'Đáp án: crocodiles',
 'f.1': 'Câu đúng: What are those animals, Minh?',
 'f.10': 'Câu đúng: She likes hippos because they look strong.',
 'f.2': 'Câu đúng: They are giraffes.',
 'f.3': 'Câu đúng: Those giraffes are running quickly.',
 'f.4': 'Câu đúng: Those lions are roaring loudly.',
 'f.5': 'Câu đúng: The giraffes have long necks and legs.',
 'f.6': 'Câu đúng: She likes birds because they sing merrily.',
 'f.7': 'Câu đúng: Why do you like peacocks?',
 'f.8': 'Câu đúng: I like peacocks because they dance beautifully.',
 'f.9': 'Câu đúng: What animals does she want to see?'}
