# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r3-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Yes, he does.', 'In the evening.', 'He washes his clothes.', 'He cleans the floor.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: "When does Ben wash his clothes?"',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['clean', 'cleans', 'to clean', 'is clean'],
                                   'plain': True,
                                   'q': 'When does your brother _____________ the floor?',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'you', 'When', 'housework?', 'do', 'do']},
                                  {'id': 't1.4',
                                   'o': ['What does Lan do in the evening?',
                                         'When does Lan help mother with the cooking?',
                                         'What does Lan do?',
                                         'What does your mother do in the evening?'],
                                   'plain': True,
                                   'q': 'Câu “She helps her mother with the cooking" trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'What ____________ Lucy do in the morning?', 't': 'mcq'},
                                  {'id': 't1.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['washes', 'in', 'his', 'clothes', 'evening.', 'Ben', 'the']},
                                  {'id': 't1.7',
                                   'o': ["She's beautiful.",
                                         'She goes to the swimming pool on Saturdays.',
                                         'She goes to the supermarket on Sundays.',
                                         'She washes the floor on Sundays.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where does Mary go on Sundays?”?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['play', 'plays', 'do', 'does'],
                                   'plain': True,
                                   'q': 'Her mother ____________ yoga on Saturday evenings.',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['pool', 'the', 'to', 'goes', 'on', 'swimming', 'Saturdays.', 'My', 'father']},
                                  {'id': 't1.10',
                                   'o': ['Dì của bạn làm nghề gì?',
                                         'Dì của bạn đi đâu vào các ngày thứ Bảy?',
                                         'Dì của bạn làm gì vào các ngày thứ Bảy?',
                                         'Dì của bạn trông như thế nào?'],
                                   'plain': True,
                                   'q': 'Câu “What does your aunt do on Saturdays?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'o': ['goes', 'go', 'watch', 'play'],
                                   'plain': True,
                                   'q': 'Nam and his father ____________ to the sports centre on Sunday mornings.',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['What', 'on', 'Sundays?', 'do', 'does', 'your', 'brother']},
                                  {'id': 't1.13',
                                   'o': ['They live in Nguyen Kiem street.',
                                         'You live in Phan Van Tri Street.',
                                         'She lives in Le Lai Street.',
                                         "It's a big house."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Where does Mai live?',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: Where Nam live?', 't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['He watches TV in the evening.',
                                         'She lives at 10A Oxford Street.',
                                         'She goes to the sports centre.',
                                         'She works on a farm.',
                                         "He's tall and thin."],
                                   'plain': True,
                                   'q': 'Where does Mary live?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['What', 'Who', 'When', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ is that girl, Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['live?', 'Mary', 'does', 'Where']},
                                  {'id': 't1.18',
                                   'o': ['I live in a small house.',
                                         'He lives in a big house in a village.',
                                         "It's a small house.",
                                         'She lives in a big house.'],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “What's the house like?”",
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['on', 'at', 'in', 'with'],
                                   'plain': True,
                                   'q': 'He lives _______________ 311 Le Loi Street.',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['He watches TV in the evening.',
                                         'She lives at 10A Oxford Street.',
                                         'She goes to the sports centre.',
                                         'She works on a farm.',
                                         "He's tall and thin."],
                                   'plain': True,
                                   'q': 'Where does she work?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Review 3: Kiểm tra 3',
 'unit': 'Review3'}
