# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'He goes to the sport centre.',
 't1.10': 'Ba tôi đi đến bể bơi vào các ngày Chủ nhật.',
 't1.11': 'plays',
 't1.12': ['Where does your mother go on Sundays?'],
 't1.13': 'Mẹ bạn làm gì vào các ngày Chủ nhật?',
 't1.14': 'go',
 't1.15': ['My mother goes to the shopping centre.'],
 't1.16': 'What does she do on Sunday mornings?',
 't1.17': 'do',
 't1.18': ['What does she do on Saturdays?'],
 't1.19': 'What do you do on Saturday evenings?',
 't1.2': ['I play football with my friends.'],
 't1.20': 'plays',
 't1.3': 'Where does he go on Saturdays?',
 't1.4': 'cooks',
 't1.5': 'I go to the swimming pool.',
 't1.6': ['Where does your father go on Saturdays?'],
 't1.7': 'What does she do on Sundays?',
 't1.8': 'washes',
 't1.9': ['He goes to the swimming pool on Saturdays.']}

EXPLANATIONS = {'t1.1': 'Đáp án: He goes to the sport centre.',
 't1.10': 'Đáp án: Ba tôi đi đến bể bơi vào các ngày Chủ nhật.',
 't1.11': 'Đáp án: plays',
 't1.12': 'Câu đúng: Where does your mother go on Sundays?',
 't1.13': 'Đáp án: Mẹ bạn làm gì vào các ngày Chủ nhật?',
 't1.14': 'Đáp án: go',
 't1.15': 'Câu đúng: My mother goes to the shopping centre.',
 't1.16': 'Đáp án: What does she do on Sunday mornings?',
 't1.17': 'Đáp án: do',
 't1.18': 'Câu đúng: What does she do on Saturdays?',
 't1.19': 'Đáp án: What do you do on Saturday evenings?',
 't1.2': 'Câu đúng: I play football with my friends.',
 't1.20': 'Đáp án: plays',
 't1.3': 'Đáp án: Where does he go on Saturdays?',
 't1.4': 'Đáp án: cooks',
 't1.5': 'Đáp án: I go to the swimming pool.',
 't1.6': 'Câu đúng: Where does your father go on Saturdays?',
 't1.7': 'Đáp án: What does she do on Sundays?',
 't1.8': 'Đáp án: washes',
 't1.9': 'Câu đúng: He goes to the swimming pool on Saturdays.'}
