# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'When do you watch TV?',
 'a.10': 'In the evening.',
 'a.2': 'What do you do in the morning?',
 'a.3': 'What do you do in the evening?',
 'a.4': 'I wash the dishes in the evening.',
 'a.5': 'Yes, I do.',
 'a.6': 'What do you do in the evening?',
 'a.7': 'Tôi làm việc nhà cùng với bố mẹ tôi.',
 'a.8': 'She washes her clothes in the evening.',
 'a.9': 'He does the housework with his parents.',
 'b.1': 'What',
 'b.10': 'do',
 'b.2': 'washes',
 'b.3': 'Do',
 'b.4': 'does',
 'b.5': 'watches',
 'b.6': 'clean',
 'b.7': 'helps',
 'b.8': 'do',
 'b.9': 'books',
 'c.1': {'blanks': [['I do the housework in the morning.'],
                    ['I watch TV.'],
                    ['She washes her clothes in the evening.'],
                    ['She cleans the floor.'],
                    ['I read books in the afternoon.']]},
 'd.1': 'that',
 'd.2': 'does',
 'd.3': 'do',
 'd.4': 'studies',
 'd.5': 'cleans',
 'd.6': 'helps',
 'e.1': 'T',
 'e.2': 'T',
 'e.3': 'F',
 'e.4': 'T',
 'e.5': 'F',
 'e.6': 'F',
 'f.1': ["What's your hobby, Minh?"],
 'f.10': ['I do the housework in the morning.'],
 'f.2': ['I like watching TV.'],
 'f.3': ['She watches TV in the evening.'],
 'f.4': ['What does Nam do in the afternoon?'],
 'f.5': ['Minh reads books in the afternoon.'],
 'f.6': ['When does he wash his clothes?'],
 'f.7': ['He washes his clothes in the morning.'],
 'f.8': ['She helps her mother with the cooking.'],
 'f.9': ['He cleans the floor at noon.']}

EXPLANATIONS = {'a.1': 'Đáp án: When do you watch TV?',
 'a.10': 'Đáp án: In the evening.',
 'a.2': 'Đáp án: What do you do in the morning?',
 'a.3': 'Đáp án: What do you do in the evening?',
 'a.4': 'Đáp án: I wash the dishes in the evening.',
 'a.5': 'Đáp án: Yes, I do.',
 'a.6': 'Đáp án: What do you do in the evening?',
 'a.7': 'Đáp án: Tôi làm việc nhà cùng với bố mẹ tôi.',
 'a.8': 'Đáp án: She washes her clothes in the evening.',
 'a.9': 'Đáp án: He does the housework with his parents.',
 'b.1': 'Đáp án: What',
 'b.10': 'Đáp án: do',
 'b.2': 'Đáp án: washes',
 'b.3': 'Đáp án: Do',
 'b.4': 'Đáp án: does',
 'b.5': 'Đáp án: watches',
 'b.6': 'Đáp án: clean',
 'b.7': 'Đáp án: helps',
 'b.8': 'Đáp án: do',
 'b.9': 'Đáp án: books',
 'c.1': 'When do you do the housework? → I do the housework in the morning.; What do you do on Saturdays? → I watch TV.; When does she wash her clothes? → She '
        'washes her clothes in the evening.; What does she do on Sundays? → She cleans the floor.; What do you do in the afternoon? → I read books in the '
        'afternoon.',
 'd.1': 'Đáp án: that',
 'd.2': 'Đáp án: does',
 'd.3': 'Đáp án: do',
 'd.4': 'Đáp án: studies',
 'd.5': 'Đáp án: cleans',
 'd.6': 'Đáp án: helps',
 'e.1': 'Đáp án: True (Đúng)',
 'e.2': 'Đáp án: True (Đúng)',
 'e.3': 'Đáp án: False (Sai)',
 'e.4': 'Đáp án: True (Đúng)',
 'e.5': 'Đáp án: False (Sai)',
 'e.6': 'Đáp án: False (Sai)',
 'f.1': "Câu đúng: What's your hobby, Minh?",
 'f.10': 'Câu đúng: I do the housework in the morning.',
 'f.2': 'Câu đúng: I like watching TV.',
 'f.3': 'Câu đúng: She watches TV in the evening.',
 'f.4': 'Câu đúng: What does Nam do in the afternoon?',
 'f.5': 'Câu đúng: Minh reads books in the afternoon.',
 'f.6': 'Câu đúng: When does he wash his clothes?',
 'f.7': 'Câu đúng: He washes his clothes in the morning.',
 'f.8': 'Câu đúng: She helps her mother with the cooking.',
 'f.9': 'Câu đúng: He cleans the floor at noon.'}
