# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'I have it on Tuesday and Tuesdays.',
 't1.10': 'When do you have Art?',
 't1.11': 'on',
 't1.12': ['I like Art very much. GHI NHỚ'],
 't1.13': 'What subjects do you have today?',
 't1.14': "What's",
 't1.15': 'I have Maths, Vietnamese and Science.',
 't1.16': 'it',
 't1.17': ['What subjects do you have today?'],
 't1.18': 'What subjects do you have today?',
 't1.19': 'it',
 't1.2': 'Wednesdays',
 't1.20': 'Yes, I do.',
 't1.3': ['When do you have Art?'],
 't1.4': 'Hôm nay bạn có những môn gì?',
 't1.5': "don't",
 't1.6': ['We have Vietnamese and Maths today.'],
 't1.7': 'Khi nào bạn có môn tiếng Việt?',
 't1.8': 'Do',
 't1.9': ['I go to school from Mondays to Fridays.']}

EXPLANATIONS = {'t1.1': 'Đáp án: I have it on Tuesday and Tuesdays.',
 't1.10': 'Đáp án: When do you have Art?',
 't1.11': 'Đáp án: on',
 't1.12': 'Câu đúng: I like Art very much. GHI NHỚ',
 't1.13': 'Đáp án: What subjects do you have today?',
 't1.14': "Đáp án: What's",
 't1.15': 'Đáp án: I have Maths, Vietnamese and Science.',
 't1.16': 'Đáp án: it',
 't1.17': 'Câu đúng: What subjects do you have today?',
 't1.18': 'Đáp án: What subjects do you have today?',
 't1.19': 'Đáp án: it',
 't1.2': 'Đáp án: Wednesdays',
 't1.20': 'Đáp án: Yes, I do.',
 't1.3': 'Câu đúng: When do you have Art?',
 't1.4': 'Đáp án: Hôm nay bạn có những môn gì?',
 't1.5': "Đáp án: don't",
 't1.6': 'Câu đúng: We have Vietnamese and Maths today.',
 't1.7': 'Đáp án: Khi nào bạn có môn tiếng Việt?',
 't1.8': 'Đáp án: Do',
 't1.9': 'Câu đúng: I go to school from Mondays to Fridays.'}
