# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['She likes birds because they sing merrily.'],
 't1.10': 'does',
 't1.11': ['What animals does she want to see?'],
 't1.12': 'They are lions.',
 't1.13': 'loudly',
 't1.14': ['She likes hippos because they look strong.'],
 't1.15': 'They are giraffes.',
 't1.16': 'are',
 't1.17': 'They are lions.',
 't1.18': 'giraffes',
 't1.19': ['What are those animals, Minh?'],
 't1.2': "They're giraffes.",
 't1.20': 'Because they roar loudly.',
 't1.3': 'hippos',
 't1.4': 'strong',
 't1.5': ['Why do you like peacocks?'],
 't1.6': "They're peacocks.",
 't1.7': 'hippos',
 't1.8': ['I like peacocks because they dance beautifully.'],
 't1.9': 'Why do you like birds?'}

EXPLANATIONS = {'t1.1': 'Câu đúng: She likes birds because they sing merrily.',
 't1.10': 'Đáp án: does',
 't1.11': 'Câu đúng: What animals does she want to see?',
 't1.12': 'Đáp án: They are lions.',
 't1.13': 'Đáp án: loudly',
 't1.14': 'Câu đúng: She likes hippos because they look strong.',
 't1.15': 'Đáp án: They are giraffes.',
 't1.16': 'Đáp án: are',
 't1.17': 'Đáp án: They are lions.',
 't1.18': 'Đáp án: giraffes',
 't1.19': 'Câu đúng: What are those animals, Minh?',
 't1.2': "Đáp án: They're giraffes.",
 't1.20': 'Đáp án: Because they roar loudly.',
 't1.3': 'Đáp án: hippos',
 't1.4': 'Đáp án: strong',
 't1.5': 'Câu đúng: Why do you like peacocks?',
 't1.6': "Đáp án: They're peacocks.",
 't1.7': 'Đáp án: hippos',
 't1.8': 'Câu đúng: I like peacocks because they dance beautifully.',
 't1.9': 'Đáp án: Why do you like birds?'}
