# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': '3',
 'l1.2': '2',
 'l1.3': '1',
 'l1.4': '4',
 'l2.5': 'T',
 'l2.6': 'F',
 'l2.7': 'T',
 'l2.8': 'T',
 'l3.10': 'B',
 'l3.11': 'A',
 'l3.12': 'B',
 'l3.9': 'B',
 'r1.13': {'blanks': [['C'], ['A'], ['E'], ['D']]},
 'r2.14': 'A',
 'r2.15': 'B',
 'r2.16': 'C',
 'r3.17': 'F',
 'r3.18': 'T',
 'r3.19': 'T',
 'w1.20': ['policeman'],
 'w1.21': ['bookshop'],
 'w1.22': ['crocodile'],
 'w1.23': ['cloudy'],
 'w2.24': ['Turn left to get to the food stall.'],
 'w2.25': ['How much is this bag?'],
 'w2.26': ['Because the lions roar loudly.'],
 'w2.27': ['My mother washes the clothes on Sundays.'],
 'w3.28': ['It’s sunny and windy.', 'It is sunny and windy.'],
 'w3.29': ['Go straight and turn right.', 'Go straight, turn right.', 'Go straight then turn right.']}

EXPLANATIONS = {'l1.1': 'Tranh A ứng với câu 3 (theo đáp án của đề).',
 'l1.2': 'Tranh C ứng với câu 2 (theo đáp án của đề).',
 'l1.3': 'Tranh D ứng với câu 1 (theo đáp án của đề).',
 'l1.4': 'Tranh E ứng với câu 4 (theo đáp án của đề).',
 'l2.5': 'Đáp án: True (theo đáp án của đề: ✓).',
 'l2.6': 'Đáp án: False (theo đáp án của đề: ✗).',
 'l2.7': 'Đáp án: True (theo đáp án của đề: ✓).',
 'l2.8': 'Đáp án: True (theo đáp án của đề: ✓).',
 'l3.10': 'Đáp án: B. At noon.',
 'l3.11': 'Đáp án: A. She goes to the sports center.',
 'l3.12': 'Đáp án: B. They are dancing.',
 'l3.9': 'Đáp án: B. He has small eyes.',
 'r1.13': 'Theo đáp án của đề: 1–C (bệnh viện/nhà dưỡng lão), 2–A (nấu ăn cùng mẹ), 3–E (biển báo GO), 4–D (sư tử). Tranh B (ngôi làng) là ví dụ “Where do you '
          'live?”.',
 'r2.14': 'What does your mother look like? = Mẹ bạn trông thế nào?',
 'r2.15': 'Mua nho và đậu → đi siêu thị (supermarket).',
 'r2.16': 'Chim → hót líu lo (sing merrily).',
 'r3.17': 'Sai: Dao and Huong are taking a photo (không phải Son).',
 'r3.18': 'Đúng: Son is putting up a tent with Kiem.',
 'r3.19': 'Đúng: Hao is building a campfire to cook some food.',
 'w1.20': 'policeman = cảnh sát.',
 'w1.21': 'bookshop = hiệu sách.',
 'w1.22': 'crocodile = cá sấu.',
 'w1.23': 'cloudy = nhiều mây.',
 'w2.24': 'Câu đúng: Turn left to get to the food stall.',
 'w2.25': 'Câu đúng: How much is this bag?',
 'w2.26': 'Câu đúng: Because the lions roar loudly.',
 'w2.27': 'Câu đúng: My mother washes the clothes on Sundays.',
 'w3.28': 'Câu đúng: It’s sunny and windy.',
 'w3.29': 'Câu đúng: Go straight and turn right.'}
