# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'b',
 'l1.2': 'c',
 'l1.3': 'e',
 'l1.4': 'a',
 'l2.5': 'C',
 'l2.6': 'A',
 'l2.7': 'B',
 'l2.8': 'C',
 'l3.10': ['thousand'],
 'l3.11': ['supermarket'],
 'l3.12': ['81', 'eighty-one', 'eighty one'],
 'l3.9': ['at a factory', 'at the factory', 'in a factory'],
 'r1.13': 'T',
 'r1.14': 'F',
 'r1.15': 'T',
 'r1.16': 'F',
 'r1.17': 'F',
 'r2.18': 'D',
 'r2.19': 'B',
 'r2.20': 'C',
 'r2.21': 'D',
 'r2.22': 'A',
 'r3.23': ['office worker'],
 'r3.24': ['do yoga', 'doyoga'],
 'r3.25': ['sunny'],
 'r3.26': ['turn right', 'turnright'],
 'r3.27': ['bookshop', 'book shop'],
 'w1.28': ["What's the street like?"],
 'w1.29': ['I clean the floor in the afternoon.'],
 'w1.30': ['What was the weather like in Hue yesterday?'],
 'w1.31': ['I can go straight and turn left to get to the bakery.'],
 'w1.32': ['Her friends like birds because they sing merrily.']}

EXPLANATIONS = {'l1.1': 'Theo bài nghe: “Where’s the bookshop? – It’s behind the bakery.” → tranh b.',
 'l1.2': 'Theo bài nghe: “When do you watch TV? – I watch TV in the evening.” → tranh c.',
 'l1.3': 'Theo bài nghe: “What does she do on Sundays? – She does yoga.” → tranh e.',
 'l1.4': 'Theo bài nghe: “What does it say? – It says “Go straight!”” → tranh a.',
 'l2.5': 'Theo bài nghe: “What does he do on Sundays? – He plays tennis.” → tranh C.',
 'l2.6': 'Theo bài nghe: “What’s the street like? – It’s a busy street.” → tranh A.',
 'l2.7': 'Theo bài nghe: “What was the weather like last weekend? – It was windy!” → tranh B.',
 'l2.8': 'Theo bài nghe: “Where’s the bookshop? – It’s between the gift shop and the bakery.” → tranh C.',
 'l3.10': 'Theo bài nghe: “It’s 20,000 dong.” → thousand',
 'l3.11': 'Theo bài nghe: “Do you want to go to the supermarket?” → supermarket',
 'l3.12': 'Theo bài nghe: “I live at 81 Tran Hung Dao Street.” → 81',
 'l3.9': 'Theo bài nghe: “He works at a factory.” → at a factory',
 'r1.13': 'Tranh cô bé giặt quần áo → khớp (tick ✓).',
 'r1.14': 'Tranh trời nhiều mây (cloudy), không phải windy → cross ✗.',
 'r1.15': 'Tranh chim công xòe đuôi → khớp (tick ✓).',
 'r1.16': 'Tranh người nông dân (farmer), không phải bank → cross ✗.',
 'r1.17': 'Bút giá 25.000đ, không phải fifteen → cross ✗.',
 'r2.18': 'Đáp án: D. What',
 'r2.19': 'Đáp án: B. Because',
 'r2.20': 'Đáp án: C. It’s near the pets shop.',
 'r2.21': 'Đáp án: D. says',
 'r2.22': 'Đáp án: A. in',
 'r3.23': 'office worker = nhân viên văn phòng.',
 'r3.24': 'do yoga = tập yoga.',
 'r3.25': 'sunny = có nắng.',
 'r3.26': 'Biển rẽ phải: turn right.',
 'r3.27': 'Mũi tên chỉ “BOOKSHOP” (cửa hàng giữa): bookshop.',
 'w1.28': "Câu đúng: What's the street like?",
 'w1.29': 'Câu đúng: I clean the floor in the afternoon.',
 'w1.30': 'Câu đúng: What was the weather like in Hue yesterday?',
 'w1.31': 'Câu đúng: I can go straight and turn left to get to the bakery.',
 'w1.32': 'Câu đúng: Her friends like birds because they sing merrily.'}
