# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "He's from Australia.",
 't1.10': ['Mai is eight years old.'],
 't1.11': 'What time is it?',
 't1.12': 'What',
 't1.13': 'I go to school.',
 't1.14': 'England',
 't1.15': ['What time does she have breakfast?'],
 't1.16': "I have breakfast at seven o'clock.",
 't1.17': 'I do housework.',
 't1.18': 'I want some water.',
 't1.19': 'English',
 't1.2': 'Where',
 't1.20': ["They have lunch at eleven o'clock at school."],
 't1.3': "I'm from England.",
 't1.4': 'morning',
 't1.5': ['Where is Nam from?'],
 't1.6': 'Where are you from?',
 't1.7': 'is',
 't1.8': "She goes to school at seven o'clock.",
 't1.9': 'from'}

EXPLANATIONS = {'t1.1': "Đáp án: He's from Australia.",
 't1.10': 'Câu đúng: Mai is eight years old.',
 't1.11': 'Đáp án: What time is it?',
 't1.12': 'Đáp án: What',
 't1.13': 'Đáp án: I go to school.',
 't1.14': 'Đáp án: England',
 't1.15': 'Câu đúng: What time does she have breakfast?',
 't1.16': "Đáp án: I have breakfast at seven o'clock.",
 't1.17': 'Đáp án: I do housework.',
 't1.18': 'Đáp án: I want some water.',
 't1.19': 'Đáp án: English',
 't1.2': 'Đáp án: Where',
 't1.20': "Câu đúng: They have lunch at eleven o'clock at school.",
 't1.3': "Đáp án: I'm from England.",
 't1.4': 'Đáp án: morning',
 't1.5': 'Câu đúng: Where is Nam from?',
 't1.6': 'Đáp án: Where are you from?',
 't1.7': 'Đáp án: is',
 't1.8': "Đáp án: She goes to school at seven o'clock.",
 't1.9': 'Đáp án: from'}
