# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-hsg-b2',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'I. Circle the odd one out. (Chọn từ khác loại.)',
                        'items': [{'id': 'a.1', 'o': ['morning', 'dancing', 'evening', 'afternoon'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.2', 'o': ['see', 'watch', 'meet', 'how'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.3', 'o': ['Vietnamese', 'Australia', 'America', 'Canada'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.4', 'o': ['he', 'your', 'they', 'we'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'a.5', 'o': ['grandpa', 'doctor', 'mother', 'cousin'], 'q': 'Chọn từ khác loại.', 't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'II. Circle the word which has the underlined part pronounced differently from the others. (Chọn từ có phần gạch chân phát âm '
                                 'khác.)',
                        'items': [{'id': 'b.6',
                                   'o': ['nerv<u>ou</u>s', 'sc<u>ou</u>t', 'h<u>ou</u>sehold', 'm<u>ou</u>se'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['favor<u>i</u>te', 'f<u>i</u>nd', 'outs<u>i</u>de', 'l<u>i</u>brary'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['l<u>a</u>st', 't<u>a</u>ste', 'f<u>a</u>st', 't<u>a</u>sk'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['f<u>u</u>ture', 's<u>u</u>mmer', 'n<u>u</u>mber', 'dr<u>u</u>m'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['t<u>i</u>me', 'k<u>i</u>nd', 'b<u>i</u>rd', 'n<u>i</u>ce'],
                                   'q': 'Chọn từ có phần gạch chân phát âm khác các từ còn lại.',
                                   't': 'mcq'}]},
                       {'id': 'c',
                        'instr': 'III. Circle the word or phrase that best completes the sentence. (Chọn từ/cụm từ đúng.)',
                        'items': [{'id': 'c.11',
                                   'o': ['is watching', 'watch', 'watches', 'watched'],
                                   'q': 'He __________ a documentary about nature.',
                                   't': 'mcq'},
                                  {'id': 'c.12', 'o': ['goes', 'is going', 'went', 'go'], 'q': 'He usually __________ for a run in the evening.', 't': 'mcq'},
                                  {'id': 'c.13',
                                   'o': ['am attending', 'attend', 'attends', 'attended'],
                                   'q': 'I __________ a workshop next month.',
                                   't': 'mcq'},
                                  {'id': 'c.14', 'o': ['am jogging', 'jog', 'jogs', 'jogged'], 'q': 'I __________ in the park every morning.', 't': 'mcq'},
                                  {'id': 'c.15', 'o': ['is singing', 'sing', 'sings', 'sang'], 'q': 'She always __________ in the shower.', 't': 'mcq'},
                                  {'id': 'c.16', 'o': ['is reading', 'read', 'reads', 'have read'], 'q': 'She __________ a novel at the moment.', 't': 'mcq'},
                                  {'id': 'c.17',
                                   'o': ['study', 'studies', 'studied', 'is studying'],
                                   'q': 'She __________ for her exams this week.',
                                   't': 'mcq'},
                                  {'id': 'c.18', 'o': ['taked', 'takes', 'take', 'is taking'], 'q': 'She often __________ long walks in the park.', 't': 'mcq'},
                                  {'id': 'c.19', 'o': ['is running', 'run', 'runs', 'ran'], 'q': 'She __________ a marathon last month.', 't': 'mcq'},
                                  {'id': 'c.20', 'o': ['watch', 'watches', 'is watching', 'watched'], 'q': 'He __________ television right now.', 't': 'mcq'}]},
                       {'id': 'd',
                        'instr': 'IV. Put the verbs in brackets into the correct form. (Chia động từ trong ngoặc.)',
                        'items': [{'id': 'd.21', 'q': 'Birds {_} (not sing) in the winter.', 't': 'fill'},
                                  {'id': 'd.22', 'q': 'Cats {_} (not sleep) in the morning.', 't': 'fill'},
                                  {'id': 'd.23', 'q': 'He {_} (swim) in the pool right now.', 't': 'fill'},
                                  {'id': 'd.24', 'q': '{_} we {_} (visit) grandma this weekend?', 't': 'fill'},
                                  {'id': 'd.25', 'q': 'Birds {_} (sing) in the trees yesterday.', 't': 'fill'},
                                  {'id': 'd.26', 'q': 'Cats {_} (sleep) on the couch last night.', 't': 'fill'},
                                  {'id': 'd.27', 'q': '{_} she {_} (dance) ballet in the studio yesterday?', 't': 'fill'},
                                  {'id': 'd.28', 'q': '{_} he {_} (walk) to school this morning?', 't': 'fill'},
                                  {'id': 'd.29', 'q': 'My mom {_} (not cook) dinner tonight.', 't': 'fill'},
                                  {'id': 'd.30', 'q': '{_} the Earth {_} (orbit) the Sun?', 't': 'fill'}]},
                       {'id': 'e',
                        'instr': 'V. Match the questions with the answers. (Nối câu hỏi với câu trả lời.)',
                        'items': [{'id': 'e.31',
                                   'left': [{'t': 'What’s the weather like today?'},
                                            {'t': 'What nationality is Hoa?'},
                                            {'t': 'Where’s Ha Noi?'},
                                            {'t': 'Do you like English?'},
                                            {'t': 'Where do you live?'}],
                                   'o': ['She’s Vietnamese.', 'Yes, I really like it.', 'I live in Ha Noi.', 'It’s rainy.', 'It’s in north Viet Nam.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'wrfix',
                        'instr': 'VI. Find and correct the mistakes in each sentence. (Tìm lỗi sai và viết lại câu đúng.)',
                        'items': [{'id': 'wrfix.32', 'q': 'Câu sai: <i>I plays soccer after school.</i><br>Viết lại câu đúng: {_}', 't': 'fill'},
                                  {'id': 'wrfix.33', 'q': 'Câu sai: <i>She is reading books every night.</i><br>Viết lại câu đúng: {_}', 't': 'fill'},
                                  {'id': 'wrfix.34', 'q': 'Câu sai: <i>She reads a book right now.</i><br>Viết lại câu đúng: {_}', 't': 'fill'},
                                  {'id': 'wrfix.35', 'q': 'Câu sai: <i>I play soccer yesterday.</i><br>Viết lại câu đúng: {_}', 't': 'fill'}]},
                       {'id': 'f',
                        'instr': 'VII. Read the passage and circle the correct answers. (Đọc đoạn văn và chọn đáp án đúng.)',
                        'items': [{'id': 'f.36',
                                   'o': ['Lily could communicate with animals.', 'Lily could communicate with gifts.'],
                                   'q': 'What was special about Lily in the story?',
                                   't': 'mcq'},
                                  {'id': 'f.37',
                                   'o': ['Lily spent her days buying animals.', 'Lily spent her days tending to injured animals.'],
                                   'q': 'How did Lily spend her days in the village?',
                                   't': 'mcq'},
                                  {'id': 'f.38',
                                   'o': ['The birds outside her window told Lily tales of their adventures.',
                                         'The birds outside her door told Lily tales of their adventures.'],
                                   'q': 'What did the birds do for Lily every morning?',
                                   't': 'mcq'},
                                  {'id': 'f.39',
                                   'o': ['Lily had an unbreakable bond with the animals of the forest, becoming her closest friends.',
                                         'With a heart full of kindness, Lily would spend her days tending to injured animals, nursing them back to health '
                                         'with gentle care.'],
                                   'q': 'Describe Lily’s relationship with the animals of the forest.',
                                   't': 'mcq'},
                                  {'id': 'f.40',
                                   'o': ['Lily had a special gift – she could communicate with animals.',
                                         'Lily believed that every creature had a story waiting to be heard and cherished each moment with them.'],
                                   'q': 'How did Lily view every creature she encountered?',
                                   't': 'mcq'}],
                        'passage': '<p>Once upon a time, a young girl named Lily lived in a small village nestled between rolling hills. Lily had a special '
                                   'gift – she could communicate with animals. Every morning, she would wake up to the cheerful chirping of birds outside her '
                                   'window, and they would tell her tales of their adventures in the forest. With a heart full of kindness, Lily would spend '
                                   'her days tending to injured animals, nursing them back to health with gentle care. Her bond with the creatures of the '
                                   'forest was unbreakable, and they became her closest friends. Together, they roamed the woods, exploring hidden trails and '
                                   'discovering the wonders of nature. In the eyes of Lily, every creature, big or small, held a story waiting to be heard, '
                                   'and she cherished each moment spent in their company.</p>'},
                       {'id': 'g',
                        'instr': 'VIII. Reorder the words to make correct sentences. (Sắp xếp từ thành câu đúng.)',
                        'items': [{'id': 'g.41', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ["doesn't", 'She', 'books', 'every', 'read', 'night.']},
                                  {'id': 'g.42',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['We', 'swimming', 'at', 'are', 'pool', 'the', 'today.']},
                                  {'id': 'g.43',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['He', 'is', 'walking', 'to', 'school', 'this', 'morning.']},
                                  {'id': 'g.44', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['She', 'read', 'a', 'book', 'last', 'night.']},
                                  {'id': 'g.45',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['We', 'swam', 'at', 'the', 'pool', 'last', 'weekend.']}]},
                       {'id': 'h',
                        'instr': 'IX. Rewrite the following sentences in such another way which has the same meaning as the first one. (Viết lại câu – đối '
                                 'chiếu đáp án mẫu sau khi nộp.)',
                        'items': [{'id': 'h.46',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>There are four people in her family.</i><br><b>Her family …</b>',
                                   't': 'open'},
                                  {'id': 'h.47',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>My house is behind the hotel.</i><br><b>The hotel …</b>',
                                   't': 'open'},
                                  {'id': 'h.48',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>Does your class have twenty-five students?</i><br><b>Are …</b>',
                                   't': 'open'},
                                  {'id': 'h.49',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>He goes to work at seven-fifteen.</i><br><b>He goes to work at a …</b>',
                                   't': 'open'},
                                  {'id': 'h.50',
                                   'q': 'Viết lại câu sao cho nghĩa không đổi:<br><i>The drugstore is to the right of the bakery.</i><br><b>The bakery …</b>',
                                   't': 'open'}]}],
            'id': 'kiem-tra',
            'minutes': 40,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'HSG – Bộ đề ôn thi – Đề 2',
 'unit': 'HSG'}
