# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u17-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['How can I get to the cinema?',
                                         'What does it say?',
                                         'Do you want to go to the cinema with me?',
                                         "What's the weather like today?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Biển báo nói gì?”:',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['cinema', 'bakery', 'food stall', 'bookshop'],
                                   'plain': True,
                                   'q': 'I want to buy some books. Is there a __________ near here?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['I want to buy some clothes.',
                                         "I'm at the shopping centre.",
                                         "Great! Let's go.",
                                         'It says "stop".',
                                         'Go straight and turn right.'],
                                   'plain': True,
                                   'q': 'Where are you now?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: _____ left at the food stall.',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['to', 'I', 'centre?', 'get', 'sports', 'can', 'the', 'How']},
                                  {'id': 't1.6',
                                   'o': ['How can I get to the bookshop?',
                                         'What does it say?',
                                         'What do you want to buy at the shopping centre?',
                                         'Is there a bakery near here?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi cách để đến nơi nào đó?',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['What', 'How', 'Where', 'When'],
                                   'plain': True,
                                   'q': 'A: _____________ can I get to the cinema?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['I want to buy some clothes.',
                                         "I'm at the shopping centre.",
                                         "Great! Let's go.",
                                         'It says "stop".',
                                         'Go straight and turn right.'],
                                   'plain': True,
                                   'q': 'How can I get to the campsite?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: There is a _____ in Pham Hung Street.',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['at', 'the', 'cinema.', 'left', 'Go', 'straight', 'and', 'turn']},
                                  {'id': 't1.11',
                                   'o': ['Go straight and turn left.',
                                         'There is a cinema in Hong Bang Street',
                                         'Thank you very much for your help.',
                                         'The bookshop is on the right.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: How can I get there?',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['it', 'that', 'there', 'this'], 'plain': True, 'q': 'Is _____________ a bakery near here?', 't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['I want to buy some clothes.',
                                         "I'm at the shopping centre.",
                                         "Great! Let's go.",
                                         'It says "stop".',
                                         'Go straight and turn right.'],
                                   'plain': True,
                                   'q': 'What does it say?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 3. A: _____ can I get there?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['a', 'here?', 'near', 'park', 'Is', 'water', 'there']},
                                  {'id': 't1.16',
                                   'o': ['Go straight.', 'Turn right.', 'Turn left.', 'Turn round.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói: “Rẽ trái.”',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['sports centre', 'shopping centre', 'bookshop', 'cinema'],
                                   'plain': True,
                                   'q': 'I want to see a movie. How can I get to the _____________.',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['I want to buy some clothes.',
                                         "I'm at the shopping centre.",
                                         "Great! Let's go.",
                                         'It says "stop".',
                                         'Go straight and turn right.'],
                                   'plain': True,
                                   'q': 'What do you want to buy at the shopping centre?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['get', 'Turn', 'bookshop', 'How', 'bakery'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 4. A: Do you want to go to the _____ with me?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Pham', 'Van', 'Dong', 'in', 'Street.', 'a', 'There', 'food', 'is', 'stall']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 17 – In the city: Kiểm tra 1',
 'unit': 17}
