# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r3-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['They live in Nguyen Kiem street.',
                                         'You live in Phan Van Tri Street.',
                                         'She lives in Le Lai Street.',
                                         "It's a big house."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Where does Mai live?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['I live in a small house.',
                                         'He lives in a big house in a village.',
                                         "It's a small house.",
                                         'She lives in a big house.'],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “What's the house like?”",
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Where does she live?', 'What does Mai do?', 'Where does she work?', 'Where does your brother work?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về nghề nghiệp của ai đó?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['What do you do?', 'Where does Nam work?', 'Where does your father work?', 'What does Nam do?'],
                                   'plain': True,
                                   'q': 'Câu: “He’s a policeman.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['What does Mai do?', 'What does Mai look like?', 'Where does Mai work?', 'Where does Mai live?'],
                                   'plain': True,
                                   'q': 'Câu: “She has curly hair" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ["He's thin and tall.", "She's a nurse.", "She's slim.", "He's a worker."],
                                   'plain': True,
                                   'q': 'Câu nào sau đầy trả lời cho câu hỏi: “What does your aunt look like?”',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['Yes, he does.', 'In the evening.', 'He washes his clothes.', 'He cleans the floor.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: "When does Ben wash his clothes?"',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['What does Lan do in the evening?',
                                         'When does Lan help mother with the cooking?',
                                         'What does Lan do?',
                                         'What does your mother do in the evening?'],
                                   'plain': True,
                                   'q': 'Câu “She helps her mother with the cooking" trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ["She's beautiful.",
                                         'She goes to the swimming pool on Saturdays.',
                                         'She goes to the supermarket on Sundays.',
                                         'She washes the floor on Sundays.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where does Mary go on Sundays?”?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Dì của bạn làm nghề gì?',
                                         'Dì của bạn đi đâu vào các ngày thứ Bảy?',
                                         'Dì của bạn làm gì vào các ngày thứ Bảy?',
                                         'Dì của bạn trông như thế nào?'],
                                   'plain': True,
                                   'q': 'Câu “What does your aunt do on Saturdays?" có nghĩa là:',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: Where Nam live?', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['on', 'at', 'in', 'with'], 'plain': True, 'q': 'He lives _______________ 311 Le Loi Street.', 't': 'mcq'},
                                  {'id': 'b.3',
                                   'o': ['farmer', 'nurse', 'worker', 'student'],
                                   'plain': True,
                                   'q': "My father works at a factory. He's a ____________.",
                                   't': 'mcq'},
                                  {'id': 'b.4',
                                   'o': ['at a factory', 'on a farm', 'at a primary school', 'in a hospital'],
                                   'plain': True,
                                   'q': 'My aucle is a farmer. He works ____________.',
                                   't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['What', 'Where', 'How', 'When'],
                                   'plain': True,
                                   'q': '______________ does your cousin look like?',
                                   't': 'mcq'},
                                  {'id': 'b.6', 'o': ['they', 'your aunt', 'we', 'you'], 'plain': True, 'q': 'What does ___________ look like?', 't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['clean', 'cleans', 'to clean', 'is clean'],
                                   'plain': True,
                                   'q': 'When does your brother _____________ the floor?',
                                   't': 'mcq'},
                                  {'id': 'b.8', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'What ____________ Lucy do in the morning?', 't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['play', 'plays', 'do', 'does'],
                                   'plain': True,
                                   'q': 'Her mother ____________ yoga on Saturday evenings.',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['goes', 'go', 'watch', 'play'],
                                   'plain': True,
                                   'q': 'Nam and his father ____________ to the sports centre on Sunday mornings.',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['Where does Mary live?',
                                            'Where does she work?',
                                            'What does your cousin look like?',
                                            'What does Ben do in the evening?',
                                            'Where does Hoa go on Sundays?'],
                                   'o': ['He watches TV in the evening.',
                                         'She lives at 10A Oxford Street.',
                                         'She goes to the sports centre.',
                                         'She works on a farm.',
                                         "He's tall and thin."],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['What', 'Who', 'When', 'Where'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['What', 'Where', 'When', 'How'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['do', 'does', 'is', 'are'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['go', 'to go', 'goes', 'going'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['does', 'do', 'to', 'doing'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': "A: <b>(1)&nbsp;______</b> is that girl, Nam?<br>B: It's my cousin.<br>A: <b>(2)&nbsp;______</b> does he live?<br>B: He "
                                   'lives in Le Loi Street.<br>A: What does he do?<br>B: He <b>(3)&nbsp;______</b> a student.<br>A: Where does he '
                                   '<b>(4)&nbsp;______</b> on Sundays?<br>B: He goes to the sports centre.<br>A: What does he <b>(5)&nbsp;______</b> '
                                   'there?<br>B: He plays tennis.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and choose the correct answers. (Đọc và chọn đáp án đúng.)',
                        'items': [{'id': 'e.1', 'o': ['two', 'three', 'four'], 'plain': True, 'q': "How many people are there in Binh's family?", 't': 'mcq'},
                                  {'id': 'e.2',
                                   'o': ["He's a polceman.", "He's a worker.", "He's a farmer."],
                                   'plain': True,
                                   'q': 'What does his father do?',
                                   't': 'mcq'},
                                  {'id': 'e.3',
                                   'o': ['He works at a factory.', 'He works on a farm.', 'He works in a hopistal.'],
                                   'plain': True,
                                   'q': 'Where does his father work?',
                                   't': 'mcq'},
                                  {'id': 'e.4',
                                   'o': ["She's an office worker.", "She's a nurse.", "She's a teacher."],
                                   'plain': True,
                                   'q': 'What does his mother do?',
                                   't': 'mcq'},
                                  {'id': 'e.5',
                                   'o': ['She works at a factory.', 'She works at a nursing home.', 'She works at a school.'],
                                   'plain': True,
                                   'q': 'Where does his mother work?',
                                   't': 'mcq'},
                                  {'id': 'e.6',
                                   'o': ['He’s a worker.', 'He’s a student.', 'He’s a policeman.'],
                                   'plain': True,
                                   'q': 'What does Binh do?',
                                   't': 'mcq'}],
                        'passage': 'That boy is Binh, my cousin. There are three people in his family: his father, his mother and him. His father is a farmer. '
                                   'He works on a farm. His mother is a teacher. She works at a school. Binh is a student. He studies at Hong Bang '
                                   'University.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Where', 'Mary', 'live?', 'does']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['village', 'the', "What's", 'like?']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'do?', 'mother', 'What', 'does']},
                                  {'id': 'f.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['teaches', 'My', 'at', 'primary', 'school.', 'sister', 'a']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['look', 'like?', 'What', 'brother', 'does', 'your']},
                                  {'id': 'f.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['hair.', 'is', 'long', 'has', 'My', 'and', 'slim', 'sister']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'housework?', 'do', 'do', 'When', 'the']},
                                  {'id': 'f.8',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'Ben', 'his', 'clothes', 'evening.', 'in', 'washes']},
                                  {'id': 'f.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['My', 'swimming', 'pool', 'on', 'Saturdays.', 'goes', 'to', 'the', 'father']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['your', 'does', 'brother', 'do', 'on', 'What', 'Sundays?']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '',
 'title': 'Review 3: Luyện tập',
 'unit': 'Review3'}
