# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "When's your birthday?",
 't1.10': ["I'm doing a cake for my birthday party."],
 't1.11': 'Sinh nhật của bạn là khi nào?',
 't1.12': 'What',
 't1.13': 'I want some meat.',
 't1.14': 'cake',
 't1.15': ['When is your birthday?'],
 't1.16': 'What do you want to eat?',
 't1.17': 'grapes',
 't1.18': 'I want some lemonade.',
 't1.19': 'drink',
 't1.2': 'When',
 't1.20': ['My birthday is in October.'],
 't1.3': "It's Tuesday.",
 't1.4': 'When',
 't1.5': ['What are you doing, Lucy?'],
 't1.6': "When's your birthday?",
 't1.7': 'eat',
 't1.8': "It's in November.",
 't1.9': 'November'}

EXPLANATIONS = {'t1.1': "Đáp án: When's your birthday?",
 't1.10': "Câu đúng: I'm doing a cake for my birthday party.",
 't1.11': 'Đáp án: Sinh nhật của bạn là khi nào?',
 't1.12': 'Đáp án: What',
 't1.13': 'Đáp án: I want some meat.',
 't1.14': 'Đáp án: cake',
 't1.15': 'Câu đúng: When is your birthday?',
 't1.16': 'Đáp án: What do you want to eat?',
 't1.17': 'Đáp án: grapes',
 't1.18': 'Đáp án: I want some lemonade.',
 't1.19': 'Đáp án: drink',
 't1.2': 'Đáp án: When',
 't1.20': 'Câu đúng: My birthday is in October.',
 't1.3': "Đáp án: It's Tuesday.",
 't1.4': 'Đáp án: When',
 't1.5': 'Câu đúng: What are you doing, Lucy?',
 't1.6': "Đáp án: When's your birthday?",
 't1.7': 'Đáp án: eat',
 't1.8': "Đáp án: It's in November.",
 't1.9': 'Đáp án: November'}
