# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u3-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Hôm nay bạn khoẻ không?', 'Bạn đến từ đâu?', 'Hôm nay là thứ mấy?', 'Mấy giờ rồi?'],
                                   'plain': True,
                                   'q': 'Câu “What day is it today?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['Wednesday', 'on Tuesdays', 'Mondays', 'Fridays'],
                                   'plain': True,
                                   'q': 'A: What day is it today, Mary?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['I do housework.', 'He plays football with his friends.', "It's Friday.", 'Yes, she does.', "It's eight o'clock."],
                                   'plain': True,
                                   'q': 'What day is it today?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Lucy: Hi, Mai. _____ are you today?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['it', 'today,', 'is', 'day', 'What', 'Mai?']},
                                  {'id': 't1.6',
                                   'o': ['Hôm nay là thứ Bảy.', 'Tôi nghe nhạc vào thứ Bảy.', 'Bạn làm gì vào các ngày thứ Bảy?', 'Bạn đi đâu vào thứ Bảy?'],
                                   'plain': True,
                                   'q': 'Câu: “What do you do on Saturdays?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['What', 'How', 'When', 'Where'],
                                   'plain': True,
                                   'q': 'A: ______________ do you do on Sunday mornings, Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['I do housework.', 'He plays football with his friends.', "It's Friday.", 'Yes, she does.', "It's eight o'clock."],
                                   'plain': True,
                                   'q': 'What time is it?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Mai: I'm _____, thank you. And you?",
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'It', 'Wednesday']},
                                  {'id': 't1.11',
                                   'o': ['What time is it?', 'How are you today?', 'Where are you from?', 'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu “It\'s Tuesday." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['shool', 'Sundays', 'today', 'the afternoon'],
                                   'plain': True,
                                   'q': 'A: What do you do on ______________, Bill?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['I do housework.', 'He plays football with his friends.', "It's Friday.", 'Yes, she does.', "It's eight o'clock."],
                                   'plain': True,
                                   'q': 'What do you do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Lucy: I'm fine too. _____ day is it today, Mai?",
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Friday.', 'to', 'goes', 'from', 'Monday', 'Mai', 'school', 'to']},
                                  {'id': 't1.16',
                                   'o': ['What day is it today?', 'What do you do on Mondays?', 'Where are you from?', "Where's she from?"],
                                   'plain': True,
                                   'q': 'Câu “I study at school." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['Monday', "seven o'clock", 'Sundays', 'England'],
                                   'plain': True,
                                   'q': 'A: What time is it?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['I do housework.', 'He plays football with his friends.', "It's Friday.", 'Yes, she does.', "It's eight o'clock."],
                                   'plain': True,
                                   'q': 'Does she go to school on Saturdays?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['What', 'Saturday', 'fine', 'tomorrow', 'How', 'help', 'play'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Mai: It is _____.',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['do', 'weekend?', 'at', 'the', 'do', 'What', 'you']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 3 – My week: Kiểm tra 1',
 'unit': 3}
