# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'C',
 'l1.2': 'A',
 'l1.3': 'B',
 'l1.4': 'C',
 'l2.5': '2',
 'l2.6': '4',
 'l2.7': '1',
 'l2.8': '3',
 'l3.9': {'blanks': [['C'], ['E'], ['A'], ['D']]},
 'l4.10': ['painter'],
 'l4.11': ['Thailand'],
 'l4.12': ['school'],
 'l4.13': ['Friday', 'Fridays'],
 'r1.14': {'blanks': [['D'], ['A'], ['E'], ['C']]},
 'r2.15': 'A',
 'r2.16': 'C',
 'r2.17': 'B',
 'r3.18': 'T',
 'r3.19': 'F',
 'r3.20': 'T',
 'w1.21': ['running'],
 'w1.22': ['grapes'],
 'w1.23': ['mountains'],
 'w2.24': ['Where is she from?'],
 'w2.25': ['My birthday is in February.'],
 'w2.26': ['I get up at five forty-five.']}

EXPLANATIONS = {'l1.1': 'Đáp án C: tranh cậu bé cầm cờ Malaysia.',
 'l1.2': 'Đáp án A: tranh cậu bé trượt patin (roller skate).',
 'l1.3': 'Đáp án B: đồng hồ 6:00 AM.',
 'l1.4': 'Đáp án C: tranh cô bé hút bụi (làm việc nhà).',
 'l2.5': 'Tranh A ứng với câu 2 (theo đáp án của đề).',
 'l2.6': 'Tranh C ứng với câu 4 (theo đáp án của đề).',
 'l2.7': 'Tranh D ứng với câu 1 (theo đáp án của đề).',
 'l2.8': 'Tranh E ứng với câu 3 (theo đáp án của đề).',
 'l3.9': 'Đáp án theo đáp án của đề: 1–C, 2–E, 3–A, 4–D',
 'l4.10': 'Đáp án: painter',
 'l4.11': 'Đáp án: Thailand',
 'l4.12': 'Đáp án: school',
 'l4.13': 'Đáp án: Friday',
 'r1.14': 'Đáp án: birthday party – D, buildings – A, study at school – E, play the guitar – C',
 'r2.15': 'Đáp án: A. from',
 'r2.16': 'Đáp án: C. September',
 'r2.17': 'Đáp án: B. When’s',
 'r3.18': 'Đúng: đúng như bài đọc.',
 'r3.19': 'Sai: Ben can ride a horse, but he can’t draw.',
 'r3.20': 'Đúng: We all can sing and dance.',
 'w1.21': 'Đáp án: running',
 'w1.22': 'Đáp án: grapes',
 'w1.23': 'Đáp án: mountains',
 'w2.24': 'Câu đúng: Where is she from?',
 'w2.25': 'Câu đúng: My birthday is in February.',
 'w2.26': 'Câu đúng: I get up at five forty-five.'}
