# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u1-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["Where's she from?", "Where's he from?", 'Where are you from?', 'Where are they from?'],
                                   'plain': True,
                                   'q': 'Câu "I\'m from Australia" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['are', 'is', 'am', 'does'], 'plain': True, 'q': 'I __________ from Japan.', 't': 'mcq'},
                                  {'id': 't1.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['he', 'Where', 'from?', 'is']},
                                  {'id': 't1.4',
                                   'o': ["I'm fine, thank you.", "I'm from Australia.", "It's my new friend.", "She's from Japan."],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi “Who's that”?",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ['is', 'am', 'do', 'are'], 'plain': True, 'q': 'They __________ from the USA.', 't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['from', 'is', 'Thailand.', 'Malee']},
                                  {'id': 't1.7',
                                   'o': ['Bạn tôi đến từ Nhật Bản.', 'Đó là bạn mới của tôi.', 'Cô ấy đến từ đâu?', 'Bạn mới của tôi đến từ Nhật Bản.'],
                                   'plain': True,
                                   'q': 'Câu “It’s my new friend." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['is', 'am', 'are', 'do'], 'plain': True, 'q': 'John __________ from Australia.', 't': 'mcq'},
                                  {'id': 't1.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'my', 'good', 'friends.', 'They']},
                                  {'id': 't1.10',
                                   'o': ["Where's he from?", "Who's that?", 'Where are you from?', "Where's she from?"],
                                   'plain': True,
                                   'q': 'Câu “She’s from Malaysia." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'o': ['is', 'does', 'are', 'am'], 'plain': True, 'q': 'Lucy __________ from Malaysia.', 't': 'mcq'},
                                  {'id': 't1.12', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'Where', 'are', 'from?']},
                                  {'id': 't1.13',
                                   'o': ["What's your name?", "Who's that?", 'How are you?', 'Where are you from?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây dùng để hỏi tên của bạn?',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'o': ['is', 'am', 'are', 'do'], 'plain': True, 'q': 'Where __________ you from?', 't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ["They're from Australia.", "I'm fine, thank you.", "He's from Vietnam.", "She's from America.", "It's my new friend."],
                                   'plain': True,
                                   'q': 'How are you, Mai?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['too', 'friend', 'Bill', 'from', 'Australia'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Bill: Hello, Nam. I'm _____.",
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Minh.', 'name', 'is', 'My']},
                                  {'id': 't1.18',
                                   'o': ['How are you today?', 'Where are you from?', "Where's he from?", "Where's she from?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi bạn đến từ đâu?',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'o': ['are', 'is', 'am', 'does.'], 'plain': True, 'q': 'Where __________ he from?', 't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ["They're from Australia.", "I'm fine, thank you.", "He's from Vietnam.", "She's from America.", "It's my new friend."],
                                   'plain': True,
                                   'q': "Where's Mary from?",
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 1 – My friends: Kiểm tra 3',
 'unit': 1}
