# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['What does she do on Sundays?'],
 't1.10': "It's Tuesday.",
 't1.11': ['What does he do on Sundays?'],
 't1.12': 'She does housework on Sundays.',
 't1.13': 'on',
 't1.14': ['He listens to music on Sundays.'],
 't1.15': 'Hôm nay là thứ mấy?',
 't1.16': 'Wednesday',
 't1.17': "It's Friday.",
 't1.18': 'How',
 't1.19': ['What day is it today, Mai?'],
 't1.2': 'Bạn làm gì vào thứ Năm?',
 't1.20': 'Bạn làm gì vào các ngày thứ Bảy?',
 't1.3': 'on',
 't1.4': 'help',
 't1.5': ['I watch TV on Sundays.'],
 't1.6': "It's Friday today.",
 't1.7': 'What',
 't1.8': ['I do my homework on Saturdays.'],
 't1.9': 'What do you do on Tuesdays?'}

EXPLANATIONS = {'t1.1': 'Câu đúng: What does she do on Sundays?',
 't1.10': "Đáp án: It's Tuesday.",
 't1.11': 'Câu đúng: What does he do on Sundays?',
 't1.12': 'Đáp án: She does housework on Sundays.',
 't1.13': 'Đáp án: on',
 't1.14': 'Câu đúng: He listens to music on Sundays.',
 't1.15': 'Đáp án: Hôm nay là thứ mấy?',
 't1.16': 'Đáp án: Wednesday',
 't1.17': "Đáp án: It's Friday.",
 't1.18': 'Đáp án: How',
 't1.19': 'Câu đúng: What day is it today, Mai?',
 't1.2': 'Đáp án: Bạn làm gì vào thứ Năm?',
 't1.20': 'Đáp án: Bạn làm gì vào các ngày thứ Bảy?',
 't1.3': 'Đáp án: on',
 't1.4': 'Đáp án: help',
 't1.5': 'Câu đúng: I watch TV on Sundays.',
 't1.6': "Đáp án: It's Friday today.",
 't1.7': 'Đáp án: What',
 't1.8': 'Câu đúng: I do my homework on Saturdays.',
 't1.9': 'Đáp án: What do you do on Tuesdays?'}
