# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'What does it say?',
 'a.10': 'Có một trung tâm thể thao ở đường Nguyễn Trãi.',
 'a.2': 'How can I get to the bookshop?',
 'a.3': 'Go straight and turn left.',
 'a.4': 'Turn left.',
 'a.5': 'How can I get to the bookshop?',
 'a.6': 'Có một sạp bán thực phẩm trên đường Nguyễn Thái Sơn.',
 'a.7': 'How can she get to the shopping centre?',
 'a.8': 'What does he want to buy at the bookshop?',
 'a.9': 'Quay vòng lại.',
 'b.1': 'bookshop',
 'b.10': 'Turn',
 'b.2': 'How',
 'b.3': 'there',
 'b.4': 'cinema',
 'b.5': 'stop',
 'b.6': 'green',
 'b.7': 'food stall',
 'b.8': 'cinema',
 'b.9': 'food stall',
 'c.1': {'blanks': [["I'm at the shopping centre."],
                    ['Go straight and turn right.'],
                    ['It says "stop".'],
                    ['I want to buy some clothes.'],
                    ["Great! Let's go."]]},
 'd.1': 'Turn',
 'd.2': 'bakery',
 'd.3': 'How',
 'd.4': 'bookshop',
 'd.5': 'get',
 'e.1': 'T',
 'e.2': 'T',
 'e.3': 'T',
 'e.4': 'F',
 'e.5': 'T',
 'f.1': ['How can I get to the sports centre?'],
 'f.10': ['Thank you very much for your help.'],
 'f.2': ['Go straight and turn left at the cinema.'],
 'f.3': ['Is there a water park near here?'],
 'f.4': ['There is a food stall in Pham Van Dong Street.'],
 'f.5': ['What does it say?'],
 'f.6': ['We want to go to the bookshop.'],
 'f.7': ['There is a bakery in Nguyen Thai Son Street.'],
 'f.8': ['How can we get to the campsite?'],
 'f.9': ['Go straight and you will see the campsite on the left.']}

EXPLANATIONS = {'a.1': 'Đáp án: What does it say?',
 'a.10': 'Đáp án: Có một trung tâm thể thao ở đường Nguyễn Trãi.',
 'a.2': 'Đáp án: How can I get to the bookshop?',
 'a.3': 'Đáp án: Go straight and turn left.',
 'a.4': 'Đáp án: Turn left.',
 'a.5': 'Đáp án: How can I get to the bookshop?',
 'a.6': 'Đáp án: Có một sạp bán thực phẩm trên đường Nguyễn Thái Sơn.',
 'a.7': 'Đáp án: How can she get to the shopping centre?',
 'a.8': 'Đáp án: What does he want to buy at the bookshop?',
 'a.9': 'Đáp án: Quay vòng lại.',
 'b.1': 'Đáp án: bookshop',
 'b.10': 'Đáp án: Turn',
 'b.2': 'Đáp án: How',
 'b.3': 'Đáp án: there',
 'b.4': 'Đáp án: cinema',
 'b.5': 'Đáp án: stop',
 'b.6': 'Đáp án: green',
 'b.7': 'Đáp án: food stall',
 'b.8': 'Đáp án: cinema',
 'b.9': 'Đáp án: food stall',
 'c.1': 'Where are you now? → I\'m at the shopping centre.; How can I get to the campsite? → Go straight and turn right.; What does it say? → It says "stop".; '
        "What do you want to buy at the shopping centre? → I want to buy some clothes.; Do you want to go to the swimming pool with me? → Great! Let's go.",
 'd.1': 'Đáp án: Turn',
 'd.2': 'Đáp án: bakery',
 'd.3': 'Đáp án: How',
 'd.4': 'Đáp án: bookshop',
 'd.5': 'Đáp án: get',
 'e.1': 'Đáp án: True (Đúng)',
 'e.2': 'Đáp án: True (Đúng)',
 'e.3': 'Đáp án: True (Đúng)',
 'e.4': 'Đáp án: False (Sai)',
 'e.5': 'Đáp án: True (Đúng)',
 'f.1': 'Câu đúng: How can I get to the sports centre?',
 'f.10': 'Câu đúng: Thank you very much for your help.',
 'f.2': 'Câu đúng: Go straight and turn left at the cinema.',
 'f.3': 'Câu đúng: Is there a water park near here?',
 'f.4': 'Câu đúng: There is a food stall in Pham Van Dong Street.',
 'f.5': 'Câu đúng: What does it say?',
 'f.6': 'Câu đúng: We want to go to the bookshop.',
 'f.7': 'Câu đúng: There is a bakery in Nguyen Thai Son Street.',
 'f.8': 'Câu đúng: How can we get to the campsite?',
 'f.9': 'Câu đúng: Go straight and you will see the campsite on the left.'}
