# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a1.1': 'B',
 'a1.2': 'A',
 'a1.3': 'A',
 'a1.4': 'B',
 'a2.5': 'C',
 'a2.6': 'D',
 'a2.7': 'B',
 'a2.8': 'A',
 'a3.10': 'F',
 'a3.9': 'T',
 'a4.11': ['music'],
 'a4.12': ['February'],
 'b1.13': {'blanks': [['f'], ['e'], ['a'], ['c'], ['b']]},
 'b2.14': ['badminton'],
 'b2.15': ['can’t'],
 'b2.16': ['ride'],
 'b2.17': ['piano'],
 'b2.18': ['draw'],
 'c1.19': ['grapes'],
 'c1.20': ['go to school'],
 'c1.21': ['painter'],
 'c1.22': ['buildings'],
 'c1.23': ['Malaysia'],
 'c2.24': ['I have music on Mondays.'],
 'c2.25': ['My birthday is in August.'],
 'c2.26': ['My favourite subject is art.'],
 'c2.27': ['I get up at five thirty.'],
 'c2.28': ['How many gardens are there at your school?']}

EXPLANATIONS = {'a1.1': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.2': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.3': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.4': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a2.5': 'Câu 1 ứng với tranh C (theo đáp án của đề).',
 'a2.6': 'Câu 2 ứng với tranh D (theo đáp án của đề).',
 'a2.7': 'Câu 3 ứng với tranh B (theo đáp án của đề).',
 'a2.8': 'Câu 4 ứng với tranh A (theo đáp án của đề).',
 'a3.10': 'Đáp án: False (theo đáp án của đề: ✗).',
 'a3.9': 'Đáp án: True (theo đáp án của đề: ✓).',
 'a4.11': 'Đáp án: music',
 'a4.12': 'Đáp án: February',
 'b1.13': 'Đáp án: 1–f, 2–e, 3–a, 4–c, 5–b',
 'b2.14': 'Đáp án: badminton',
 'b2.15': 'Đáp án: can’t',
 'b2.16': 'Đáp án: ride',
 'b2.17': 'Đáp án: piano',
 'b2.18': 'Đáp án: draw',
 'c1.19': 'Đáp án: grapes',
 'c1.20': 'Đáp án: go to school',
 'c1.21': 'Đáp án: painter',
 'c1.22': 'Đáp án: buildings',
 'c1.23': 'Đáp án: Malaysia',
 'c2.24': 'Câu đúng: I have music on Mondays.',
 'c2.25': 'Câu đúng: My birthday is in August.',
 'c2.26': 'Câu đúng: My favourite subject is art.',
 'c2.27': 'Câu đúng: I get up at five thirty.',
 'c2.28': 'Câu đúng: How many gardens are there at your school?'}
