# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u8-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['What subjects do you have today?',
                                         'When do you have English?',
                                         "What's your favourite subject?",
                                         'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi môn học yêu thích của ai đó là gì?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['Tôi thích môn tiếng Anh.',
                                         'Môn học yêu thích của tôi là môn Tiếng Anh.',
                                         'Môn học yêu thích của tôi là môn Toán.',
                                         'Môn học yêu thích của tôi là môn Tiếng Việt.'],
                                   'plain': True,
                                   'q': 'Câu “My favorite subject is English” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Because I want to be a teacher.',
                                         'I have English on Mondays and Fridays.',
                                         'I have English, Vietnamese and Maths.',
                                         "It's music."],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “What's your favourite subject?”",
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['What day is it today?',
                                         'Why do you like Music?',
                                         'How many playgrounds are there at your school?',
                                         'When do you have English?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi lý do ai đó thích môn gì?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['I have maths on Mondays and Thursdays.',
                                         'I have maths and Vietnamese.',
                                         'Because I want to be a Maths teacher.',
                                         'Because I want to be an English teacher.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like Maths?"',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['Because I want to be a painter.',
                                         'Because I want to be a singer.',
                                         'My favourite subject is music.',
                                         'I like music.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like music?"',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['How many building are there at your school?',
                                         'What subjects do you have today?',
                                         'Why do you like Art?',
                                         'Why do you like Maths?'],
                                   'plain': True,
                                   'q': 'Câu “Because I want to be a painter." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['Why do you like English?', 'Why do you like Music?', 'Why do you like Maths?', "What's your favourtie subject?"],
                                   'plain': True,
                                   'q': 'Câu “Because I want to be an English teacher.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['Tại sao bạn thích môn Âm nhạc?',
                                         'Tại sao bạn thích môn Mỹ thuật?',
                                         'Tại sao bạn thích môn Toán?',
                                         'Tại sao bạn thích môn Khoa học?'],
                                   'plain': True,
                                   'q': 'Câu “Why do you like Art?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Bởi vì mình muốn trở thành một giáo viên Âm nhạc.',
                                         'Bởi vì mình muốn trở thành một giáo viên Mỹ thuật.',
                                         'Bởi vì mình muốn trở thành một giáo viên Khoa học.',
                                         'Bởi vì mình muốn trở thành một giáo viên Tin học.'],
                                   'plain': True,
                                   'q': 'Câu “Because I want to be an IT teacher" có nghĩa là:',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1',
                                   'o': ["Why's", "What's", "How's", "Where's"],
                                   'plain': True,
                                   'q': '__________ your favourite subject?',
                                   't': 'mcq'},
                                  {'id': 'b.2',
                                   'o': ['English', 'Music', 'Science', 'Art'],
                                   'plain': True,
                                   'q': 'I like drawing. My favourite subject is __________.',
                                   't': 'mcq'},
                                  {'id': 'b.3',
                                   'o': ['book', 'day', 'subject', 'school'],
                                   'plain': True,
                                   'q': "A: What's your favourite __________?",
                                   't': 'mcq'},
                                  {'id': 'b.4',
                                   'o': ['PE', 'IT', 'Science', 'Art'],
                                   'plain': True,
                                   'q': 'I like running. My favourite subject is __________.',
                                   't': 'mcq'},
                                  {'id': 'b.5', 'o': ['Where', 'Why', 'What', 'How'], 'plain': True, 'q': 'A: __________ do you like Music?', 't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['IT', 'Art', 'Music', 'Science'],
                                   'plain': True,
                                   'q': 'My favourite subject is __________. I want to be a painter.',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['English', 'Art', 'Music', 'IT'],
                                   'plain': True,
                                   'q': 'I like __________ because I want to be a singer.',
                                   't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['subject', 'day', 'school', 'name'],
                                   'plain': True,
                                   'q': "I like PE. It's my favourite __________.",
                                   't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['Art', 'Science', 'Vietnamese', 'Music'],
                                   'plain': True,
                                   'q': 'I like singing. My favourite subject is __________.',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['like', 'have c.sing d. play'],
                                   'plain': True,
                                   'q': 'A: What subjects do you have today?',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['What day is it today?',
                                            'Do you have English today?',
                                            "What's your favourite subject?",
                                            'When do you have Science?',
                                            'Why do you like it Maths?'],
                                   'o': ["It's music.", "It's Thursday.", 'Because I want to be a maths teacher.', 'I have it on Friday.', 'Yes, I do.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['Thursday', 'English', 'Vietnamese', 'science'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['Are', 'Is', 'Do', 'Does'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['Why', 'How', 'What', 'Where'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['PE', 'IT', 'English', 'Art'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['What', 'How', 'Because', 'With'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': "A: What day is it today?<br>B: It's <b>(1)&nbsp;______</b>.<br>A: <b>(2)&nbsp;______</b> you have music today?<br>B: Yes, "
                                   "I do.<br>A: What's your favourite subject?<br>B: It's music. <b>(3)&nbsp;______</b> about you?<br>A: My favourite subject "
                                   'is <b>(4)&nbsp;______</b>.<br>B: Why do you like Art?<br>A: <b>(5)&nbsp;______</b> I want to be a painter.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': 'His name is Binh.', 't': 'tf'},
                                  {'id': 'e.2', 'q': 'He has three subjects at school today.', 't': 'tf'},
                                  {'id': 'e.3', 'q': 'His favourite subject is Art.', 't': 'tf'},
                                  {'id': 'e.4', 'q': 'Science is also his favourite subject.', 't': 'tf'},
                                  {'id': 'e.5', 'q': "He doesn't like English because he isn't good at it.", 't': 'tf'}],
                        'passage': "My name is Binh. It's Thursday today. I have English, Vietnamese And Art at school. My favourite subject is Art. I like it "
                                   "because I want to be a painter. I also like English because I want to be an English teacher. I don't like Science because "
                                   "I'm not good at it."}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ["What's", 'your', 'subject?', 'favourite']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['subject', 'favourite', 'My', 'is', 'Music.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'Art?', 'like', 'Why', 'do']},
                                  {'id': 'f.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['want', 'Because', 'to', 'a', 'painter.', 'I', 'become']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['have', 'today?', 'What', 'you', 'subjects', 'do']},
                                  {'id': 'f.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['have', 'Vietnamese,', 'and', 'Maths.', 'English', 'I']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['have', 'on', 'Music', 'I', 'Fridays.']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'Why', 'like', 'English?', 'do']},
                                  {'id': 'f.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['be', 'an', 'Because', 'teacher.', 'English', 'to', 'want', 'I']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['teacher.', 'want', 'be', 'to', 'a', 'Maths', 'Because', 'I']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'},
           {'audio': True,
            'groups': [{'id': 'n',
                        'instr': 'Nghe file âm thanh và làm các câu theo số thứ tự trong bài nghe.',
                        'items': [{'id': 'n.1', 'o': ["It's IT", "It's Art."], 'plain': True, 'q': "Câu 1. What's your favourite subject?", 't': 'mcq'},
                                  {'id': 'n.2', 'q': "Câu 2. What's your favourite subject? - It's {_}", 't': 'fill'},
                                  {'id': 'n.3', 'q': 'Câu 3. My favourite subject is Maths.', 't': 'tf'},
                                  {'id': 'n.4', 'q': "Câu 4. What's your favourite subject? - It's IT.", 't': 'tf'},
                                  {'id': 'n.5', 'q': "Câu 5. What's your favourite subject, Nam? - It's {_}", 't': 'fill'},
                                  {'id': 'n.6',
                                   'o': ['Because I want to be an English teacher.', 'Because I want to sing English songs.'],
                                   'plain': True,
                                   'q': 'Câu 6. Why do you like English?',
                                   't': 'mcq'},
                                  {'id': 'n.7', 'q': 'Câu 7. Why do you like {_}?', 't': 'fill'},
                                  {'id': 'n.8', 'q': 'Câu 8. Because I want to be a Maths {_}', 't': 'fill'},
                                  {'id': 'n.9',
                                   'o': ['teacher', 'painter', 'singer'],
                                   'plain': True,
                                   'q': 'Câu 9. Because I want to be a _____________.',
                                   't': 'mcq'},
                                  {'id': 'n.10', 'o': ['Science', 'Music', 'Art'], 'plain': True, 'q': 'Câu 10. I like ________________.', 't': 'mcq'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Luyện nghe'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi môn học yêu thích của ai đó là gì và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           "lời</td></tr><tr><td>- What's your favourite subject?<br>Môn học yêu thích của bạn là gì?<br>- What's her/his favourite subject?<br>Môn học yêu "
           'thích của cô ấy/cậu ấy là gì?</td><td>- My favourite subject is... (tên môn học).<br>Môn học yêu thích của mình là... (tên môn học).<br>- Her/His '
           'favourite subject is... (tên môn học).<br>Môn học yêu thích của cô ấy/cậu ấy là... (tên môn học).<br>hoặc<br>It’s... (tên môn học.)<br>Đó là.. '
           "(tên môn học).</td></tr><tr><td>Ví dụ:<br>A: What's your favourite subject?<br>Môn học yêu thích của bạn là gì?<br>B: My favourite subject is "
           "English.<br>Môn học yêu thích của mình là môn Tiếng Anh.<br>A: What's her favourite subject?<br>Môn học yêu thích của cô ấy là gì?<br>B: Her "
           'favourite subject is Music.<br>Môn học yêu thích của cô ấy là môn Âm nhạc.</td></tr></table><p>2. Cách hỏi lý do ai đó thích môn học nào đó và '
           'cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>- Why do you like + (tên môn học)?<br>Tại sao bạn thích '
           '+ (tên môn học)?<br>- Why does she/he like + (tên môn học)?<br>Tại sao cô ấy/cậu ấy thích + (tên môn học)?</td><td>Because I want to be...<br>Bởi '
           'vì mình muốn trở thành …<br>Because she/he wants to be...<br>Bởi vì cô ấy/cậu ấy muốn trở thành...</td></tr><tr><td>Ví dụ:<br>A: Why do you like '
           'Music?<br>Tại sao bạn thích môn Âm nhạc?<br>B: Because I want to be a singer.<br>Bởi vì mình muốn trở thành ca sĩ.<br>A: Why does she like '
           'English?<br>Tại sao cô ấy thích tiếng Anh?<br>B: Because she wants to be an English teacher.<br>Bởi vì cô ấy muốn trở thành giáo viên tiếng '
           'Anh.</td></tr></table>',
 'title': 'Unit 8 – My favourite subjects: Luyện tập',
 'unit': 8}
