# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u8-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['How many building are there at your school?',
                                         'What subjects do you have today?',
                                         'Why do you like Art?',
                                         'Why do you like Maths?'],
                                   'plain': True,
                                   'q': 'Câu “Because I want to be a painter." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['English', 'Art', 'Music', 'IT'],
                                   'plain': True,
                                   'q': 'I like __________ because I want to be a singer.',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Fridays.', 'I', 'Music', 'on', 'have']},
                                  {'id': 't1.4',
                                   'o': ['Why do you like English?', 'Why do you like Music?', 'Why do you like Maths?', "What's your favourtie subject?"],
                                   'plain': True,
                                   'q': 'Câu “Because I want to be an English teacher.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['subject', 'day', 'school', 'name'],
                                   'plain': True,
                                   'q': "I like PE. It's my favourite __________.",
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['like', 'do', 'you', 'English?', 'Why']},
                                  {'id': 't1.7',
                                   'o': ['Tại sao bạn thích môn Âm nhạc?',
                                         'Tại sao bạn thích môn Mỹ thuật?',
                                         'Tại sao bạn thích môn Toán?',
                                         'Tại sao bạn thích môn Khoa học?'],
                                   'plain': True,
                                   'q': 'Câu “Why do you like Art?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['Art', 'Science', 'Vietnamese', 'Music'],
                                   'plain': True,
                                   'q': 'I like singing. My favourite subject is __________.',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['an', 'be', 'to', 'want', 'English', 'teacher.', 'Because', 'I']},
                                  {'id': 't1.10',
                                   'o': ['Bởi vì mình muốn trở thành một giáo viên Âm nhạc.',
                                         'Bởi vì mình muốn trở thành một giáo viên Mỹ thuật.',
                                         'Bởi vì mình muốn trở thành một giáo viên Khoa học.',
                                         'Bởi vì mình muốn trở thành một giáo viên Tin học.'],
                                   'plain': True,
                                   'q': 'Câu “Because I want to be an IT teacher" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'o': ['like', 'have c.sing d. play'], 'plain': True, 'q': 'A: What subjects do you have today?', 't': 'mcq'},
                                  {'id': 't1.12',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Because', 'Maths', 'to', 'a', 'be', 'I', 'want', 'teacher.']},
                                  {'id': 't1.13',
                                   'o': ['What subjects do you have today?',
                                         'When do you have English?',
                                         "What's your favourite subject?",
                                         'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi môn học yêu thích của ai đó là gì?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ["Why's", "What's", "How's", "Where's"],
                                   'plain': True,
                                   'q': '__________ your favourite subject?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ["It's music.", "It's Thursday.", 'Because I want to be a maths teacher.', 'I have it on Friday.', 'Yes, I do.'],
                                   'plain': True,
                                   'q': 'What day is it today?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['Thursday', 'English', 'Vietnamese', 'science'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____.",
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['subject?', 'your', 'favourite', "What's"]},
                                  {'id': 't1.18',
                                   'o': ['Tôi thích môn tiếng Anh.',
                                         'Môn học yêu thích của tôi là môn Tiếng Anh.',
                                         'Môn học yêu thích của tôi là môn Toán.',
                                         'Môn học yêu thích của tôi là môn Tiếng Việt.'],
                                   'plain': True,
                                   'q': 'Câu “My favorite subject is English” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['English', 'Music', 'Science', 'Art'],
                                   'plain': True,
                                   'q': 'I like drawing. My favourite subject is __________.',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ["It's music.", "It's Thursday.", 'Because I want to be a maths teacher.', 'I have it on Friday.', 'Yes, I do.'],
                                   'plain': True,
                                   'q': 'Do you have English today?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 8 – My favourite subjects: Kiểm tra 3',
 'unit': 8}
