# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de12',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and draw lines (nghe và nối số với tranh). Ví dụ: 0 – c.',
                        'items': [{'id': 'l1.1',
                                   'left': [{'t': 'Nghe câu số 1'}, {'t': 'Nghe câu số 2'}, {'t': 'Nghe câu số 3'}, {'t': 'Nghe câu số 4'}],
                                   'o': ['a', 'b', 'c', 'd', 'e'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de12/l1.png" alt="Tranh">'},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and tick the correct answer (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.2',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 1 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.3',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 2 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.4',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 4 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen and complete each question with ONE word (nghe và điền một từ). Ví dụ: What does she look like? – She is '
                                 'slim.',
                        'items': [{'id': 'l3.5', 'q': 'A: How much is the T-shirt?<br>B: It’s {_} thousand dong.', 't': 'fill'},
                                  {'id': 'l3.6', 'q': 'A: What was the weather like last weekend?<br>B: It was {_}.', 't': 'fill'},
                                  {'id': 'l3.7', 'q': 'A: Where do you live?<br>B: I live at nine Quang Trung {_}.', 't': 'fill'},
                                  {'id': 'l3.8', 'q': 'A: What does she do on {_}?<br>B: She cooks meals.', 't': 'fill'}]},
                       {'id': 'r1',
                        'instr': 'Question 4. Read and tick (nhìn tranh, chọn câu đúng). Ví dụ: (biển rẽ trái) A. It says “turn left”.',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['She has white hair.', 'She has big eyes.'],
                                   'q': 'Chọn câu đúng với tranh:',
                                   't': 'mcq'},
                                  {'id': 'r1.10',
                                   'img': 'r1_2.png',
                                   'o': ['Do you want to go to the book shop? – Great! Let’s go.', 'Do you want to go to the supermarket? – Great! Let’s go.'],
                                   'q': 'Chọn câu đúng với tranh:',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['She goes to the cinema on Saturdays.', 'She goes to the shopping centre on Saturdays.'],
                                   'q': 'Chọn câu đúng với tranh:',
                                   't': 'mcq'},
                                  {'id': 'r1.12',
                                   'img': 'r1_4.png',
                                   'o': ['How can I get to the bakery? – Go straight and turn left.', 'How can I get to the bakery? – Turn round.'],
                                   'q': 'Chọn câu đúng với tranh:',
                                   't': 'mcq'},
                                  {'id': 'r1.13',
                                   'img': 'r1_5.png',
                                   'o': ['The pen is fifty thousand dong.', 'The pen is twenty thousand dong.'],
                                   'q': 'Chọn câu đúng với tranh:',
                                   't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'Question 5. Read and match (đọc và nối). Ví dụ: What does she do? – f. She is an actor.',
                        'items': [{'id': 'r2.14',
                                   'left': [{'t': '1. What does he look like?'},
                                            {'t': '2. How much is the skirt?'},
                                            {'t': '3. Why do you like giraffes?'},
                                            {'t': '4. Where is the sports centre?'},
                                            {'t': '5. What are they doing?'}],
                                   'o': ['a. Because they run quickly.',
                                         'b. They are telling a story.',
                                         'c. He is big.',
                                         'd. It’s behind the gift shop.',
                                         'e. It’s seventy thousand dong.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'r3',
                        'instr': 'Question 6. Read and decide the statements True (T) or False (F) (đọc và chọn đúng/sai). Ví dụ: Last weekend was rainy. → T.',
                        'items': [{'id': 'r3.15', 'q': 'Hoang Hoa Tham Street is a busy street.', 't': 'tf'},
                                  {'id': 'r3.16', 'q': 'The English book is sixty thousand dong.', 't': 'tf'},
                                  {'id': 'r3.17', 'q': 'Her friend wants to go to the cinema to watch films.', 't': 'tf'},
                                  {'id': 'r3.18', 'q': 'The cinema is in Hoang Hoa Tham Street.', 't': 'tf'},
                                  {'id': 'r3.19', 'q': 'The cinema is very big.', 't': 'tf'}],
                        'passage': '<p>Last weekend, it was rainy. Jenny didn’t go out. It’s nice today. Jenny wants to go to the bookshop. The bookshop is in '
                                   'Hoang Hoa Tham Street. It’s a busy street. She wants to buy an English book. It’s fifty thousand dong.</p><p>Her friend, '
                                   'Hoa wants to go to the cinema to watch films. The cinema is in Tran Xuan Soan Street near the swimming pool. She can go '
                                   'straight and turn right. The cinema is on the right. It’s very big.</p>'},
                       {'id': 'w1',
                        'instr': 'Question 7. Rearrange the words to make complete sentences (sắp xếp từ thành câu đúng). Ví dụ: The supermarket is behind the '
                                 'swimming pool.',
                        'items': [{'id': 'w1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['hippos.', 'They', 'are']},
                                  {'id': 'w1.21',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['roar', 'because', 'they', 'I', 'lions', 'like', 'loudly.']},
                                  {'id': 'w1.22', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['How', 'the', 'much', 'school', 'is', 'bag?']},
                                  {'id': 'w1.23',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['like', 'the', 'in', 'weather', 'was', 'What', 'Thanh', 'Hoa', 'last', 'weekend?']},
                                  {'id': 'w1.24',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['sister', 'look', 'your', 'like?', 'What', 'does']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 12',
 'unit': 'OnHK2'}
