# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': {'blanks': [['e'], ['a'], ['b'], ['d']]},
 'l2.2': 'A',
 'l2.3': 'B',
 'l2.4': 'A',
 'l3.5': ['fifty'],
 'l3.6': ['sunny'],
 'l3.7': ['Road'],
 'l3.8': ['Sundays'],
 'r1.10': 'A',
 'r1.11': 'B',
 'r1.12': 'B',
 'r1.13': 'B',
 'r1.9': 'B',
 'r2.14': {'blanks': [['c. He is big.'],
                      ['e. It’s seventy thousand dong.'],
                      ['a. Because they run quickly.'],
                      ['d. It’s behind the gift shop.'],
                      ['b. They are telling a story.']]},
 'r3.15': 'T',
 'r3.16': 'F',
 'r3.17': 'T',
 'r3.18': 'F',
 'r3.19': 'T',
 'w1.20': ['They are hippos.'],
 'w1.21': ['I like lions because they roar loudly.'],
 'w1.22': ['How much is the school bag?'],
 'w1.23': ['What was the weather like in Thanh Hoa last weekend?'],
 'w1.24': ['What does your sister look like?']}

EXPLANATIONS = {'l1.1': 'Theo bài nghe: câu 1 “What are these animals? – The hippos.” → e; câu 2 “When do you watch TV? – I watch TV in the morning.” → a; câu 3 “How can I '
         'get to the bakery? – Turn right/round (còn lại là tranh b).” → b; câu 4 “Where’s the bookshop? – It’s opposite the sports shop.” → d',
 'l2.2': 'Theo bài nghe: “What do you do in the afternoon? – I clean the floor.” → tranh A.',
 'l2.3': 'Theo bài nghe: “Where does she work? – She works at a school.” → tranh B.',
 'l2.4': 'Theo bài nghe: “Where does he go on Saturdays? – He goes to the swimming pool.” → tranh A.',
 'l3.5': 'Theo bài nghe: “It’s 50,000 dong.” → fifty',
 'l3.6': 'Theo bài nghe: “It was sunny.” → sunny',
 'l3.7': 'Theo bài nghe: “I live at 9 Quang Trung Road.” → Road',
 'l3.8': 'Theo bài nghe: “What does she do on Sundays? – She cooks meals.” → Sundays',
 'r1.10': 'Tranh hiệu sách: book shop.',
 'r1.11': 'Tranh trung tâm mua sắm: shopping centre.',
 'r1.12': 'Mũi tên quay đầu (U-turn) quanh tiệm bánh: Turn round.',
 'r1.13': 'Bút giá 20.000đ: twenty thousand dong.',
 'r1.9': 'Cô bé tóc đen, mắt to: She has big eyes.',
 'r2.14': 'Đáp án: 1–c, 2–e, 3–a, 4–d, 5–b (ghép theo nghĩa).',
 'r3.15': 'Đoạn văn: “It’s a busy street.” → True.',
 'r3.16': 'Đoạn văn: “It’s fifty thousand dong.” → False.',
 'r3.17': 'Đoạn văn: “Hoa wants to go to the cinema to watch films.” → True.',
 'r3.18': 'Đoạn văn: rạp ở Tran Xuan Soan Street → False.',
 'r3.19': 'Đoạn văn: “It’s very big.” → True.',
 'w1.20': 'Câu đúng: They are hippos.',
 'w1.21': 'Câu đúng: I like lions because they roar loudly.',
 'w1.22': 'Câu đúng: How much is the school bag?',
 'w1.23': 'Câu đúng: What was the weather like in Thanh Hoa last weekend?',
 'w1.24': 'Câu đúng: What does your sister look like?'}
