# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u5-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['Can you fly a a kite?', 'Can you ride a bike?', 'Can you ride a horse?', 'Can you play a guitar?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn có thể đi xe đạp không?”',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['Bạn có thể chơi đàn ghi-ta không?',
                                         'Bạn có thể cưỡi ngựa không?',
                                         'Bạn có thể chơi đàn piano không?',
                                         'Bạn có thể đi xe đạp không?'],
                                   'plain': True,
                                   'q': 'Câu “Can you play the piano?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Can you play the guitar?', 'How are you?', 'What can you do?', 'How old are you?'],
                                   'plain': True,
                                   'q': 'Để hỏi: “Bạn có thể làm gì?”, em nói:',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['Can she cook?', 'Can he swim?', 'Can he play badminton?', 'Can you draw?'],
                                   'plain': True,
                                   'q': 'Câu: “Yes, I can." có thể trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['Mary can sing.', 'Can she sing?', 'Minh cannot draw', 'Can he play badminton?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói ai đó có thể làm được điều gì?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['Quan cannot ride a horse.', 'Lucy can play the piano.', 'Can she swim?', 'Can he draw?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói ai đó không thể làm được điều gì?',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['Can she cook?', 'Can he play the guitar?', 'Can you dance?', 'Can they roller skate?'],
                                   'plain': True,
                                   'q': "Câu: “No, he can't” có thể trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['Cậu ấy có thể chơi đàn ghi-ta không?',
                                         'Cô ấy có thể chơi đàn piano không?',
                                         'Cậu ấy có thể chơi đàn piano không?',
                                         'Cậu ấy có thể chơi cầu lông không?'],
                                   'plain': True,
                                   'q': 'Câu “Can he play the guitar?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['Can he dance?', 'Can she dance?', 'Can you dance?', 'Can they dance?'],
                                   'plain': True,
                                   'q': 'Câu: “Yes, they can.” có thể trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Yes, he can.', "No, she can't.", 'Yes, I can.', 'Yes, they can.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có thể trả lời cho câu hỏi: “Can they draw?"',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['play', 'do', 'fly', 'ride'], 'plain': True, 'q': 'Can you ____________ a kite?', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['am', 'do', 'can', "can't"], 'plain': True, 'q': 'A: Can you ride a bike?', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['am not', 'can', "can't", "don't"], 'plain': True, 'q': 'Can you play the piano?', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['is', 'does', 'can', "can't"], 'plain': True, 'q': 'A: Can he dance?', 't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['football', 'the piano', 'the guitar', 'badminton'],
                                   'plain': True,
                                   'q': 'A: Can you play ____________?',
                                   't': 'mcq'},
                                  {'id': 'b.6', 'o': ['Can', 'Is', 'Does', 'Do'], 'plain': True, 'q': 'A: ____________ he roller skate?', 't': 'mcq'},
                                  {'id': 'b.7', 'o': ['is', 'does', "can't", 'can'], 'plain': True, 'q': 'A: Can Lan ride a bike?', 't': 'mcq'},
                                  {'id': 'b.8', 'o': ['do', 'can', 'are', 'is'], 'plain': True, 'q': 'She can sing. What ____________ you do?', 't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ["doesn't", "isn't", "aren't", "can't"],
                                   'plain': True,
                                   'q': 'Lan can draw, but she ____________ cook.',
                                   't': 'mcq'},
                                  {'id': 'b.10', 'o': ["can't", 'can', 'is', "isn't"], 'plain': True, 'q': 'A: Can he swim?', 't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['Can you ride a horse?',
                                            'Can you play the guitar?',
                                            'Can she dance?',
                                            'Can he roller skate?',
                                            'Can Lan play badminton?'],
                                   'o': ["No, she can't dance, but she can sing.",
                                         "No, she can't, but she can run.",
                                         'Yes, I can.',
                                         "No, I can't ride a horse, but I can ride a bike.",
                                         'Yes, he can.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'},
                                  {'id': 'd.6', 'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'], 'plain': True, 'q': 'Chỗ trống (6):', 't': 'mcq'},
                                  {'id': 'd.7', 'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'], 'plain': True, 'q': 'Chỗ trống (7):', 't': 'mcq'}],
                        'passage': '1. A: I can sing. What <b>(1)&nbsp;______</b> you do, Hoa?<br>B: I can dance.<br>2. A: Can you <b>(2)&nbsp;______</b> the '
                                   "piano, Minh?<br>B: No, I can't. I can't play the piano, but I can play the guitar.<br>3. A: Can Mai <b>(3)&nbsp;______</b> "
                                   'a horse?<br>B: No, she <b>(4)&nbsp;______</b> ride a horse, <b>(5)&nbsp;______</b> she can ride a bike.<br>4. A: Do you '
                                   "like drawing?<br>B: Yes, I <b>(6)&nbsp;______</b>.<br>A: Can you roller kate?<br>B: <b>(7)&nbsp;______</b>, I can't, but I "
                                   'can swim.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': 'Linh can roler skate but she cannot swim.', 't': 'tf'},
                                  {'id': 'e.2', 'q': "Linh's father can play badminton but he can't play football.", 't': 'tf'},
                                  {'id': 'e.3', 'q': "Linh's mother cannot play the piano but she can sing.", 't': 'tf'},
                                  {'id': 'e.4', 'q': "Linh's sister can draw but she cannot swim.", 't': 'tf'},
                                  {'id': 'e.5', 'q': "Linh's brother cannot play the piano but he can play the guitar.", 't': 'tf'}],
                        'passage': 'Hi, my name is Linh. This is a photo of my family. This is my father. He can play badminton but he cannot play football. '
                                   'The woman on the right is my mother. She can sing but she cannot play the piano. The girl on the left is my sister. She '
                                   'likes drawing very much. She can draw, but she cannot swim. The boy in the middle is my brother. He can play the piano but '
                                   'he cannot play the guitar. And the little girl next to my brother is me. I can swim but I cannot roller skate.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['piano?', 'Can', 'he', 'the', 'play']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['ride', 'can', 'He', 'a', 'bike.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['fly', 'kite?', 'a', 'Can', 'she']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'I', 'play', "can't", 'guitar.']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do?', 'can', 'What', 'you']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ["can't", 'sing,', 'can', 'dance.', 'I', 'but', 'I']},
                                  {'id': 'f.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['but', 'badminton,', 'run.', 'play', "can't", 'can', 'she', 'She']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['badminton.', 'Mai', 'play', 'can']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['piano.', 'the', "can't", 'play', 'Linh']},
                                  {'id': 'f.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'ride', 'a', 'horse?', 'Can']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'},
           {'audio': True,
            'groups': [{'id': 'n',
                        'instr': 'Nghe file âm thanh và làm các câu theo số thứ tự trong bài nghe.',
                        'items': [{'id': 'n.1', 'o': ['can', "can't"], 'plain': True, 'q': 'Câu 1. I ___________ fly a kite.', 't': 'mcq'},
                                  {'id': 'n.2', 'q': 'Câu 2. I can {_}', 't': 'fill'},
                                  {'id': 'n.3', 'q': 'Câu 3. Can you play the {_}?', 't': 'fill'},
                                  {'id': 'n.4', 'q': 'Câu 4. Can you ride a {_}?', 't': 'fill'},
                                  {'id': 'n.5', 'o': ['basketball', 'badminton'], 'plain': True, 'q': 'Câu 5. Can Linh play___________?', 't': 'mcq'},
                                  {'id': 'n.6', 'o': ['swim', 'skip', 'roller skate'], 'plain': True, 'q': 'Câu 6. Can he______________?', 't': 'mcq'},
                                  {'id': 'n.7',
                                   'o': ['ride a horse', 'roller skate', 'ride a bike'],
                                   'plain': True,
                                   'q': 'Câu 7. Can your sister _________________?',
                                   't': 'mcq'},
                                  {'id': 'n.8',
                                   'o': ["No, he can't. But he can play football.", "No, he can't. But he can play chess.", "No, he can't. But he can draw."],
                                   'plain': True,
                                   'q': 'Câu 8. Can your brother play badminton?',
                                   't': 'mcq'},
                                  {'id': 'n.9', 'q': 'Câu 9. My {_} can play the piano very well.', 't': 'fill'},
                                  {'id': 'n.10', 'q': 'Câu 10. Can he {_}?', 't': 'fill'},
                                  {'id': 'n.11', 'q': 'Câu 11. - Yes, he can {_} very well.', 't': 'fill'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Luyện nghe'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi xem ai đó có thể làm được điều gì hay không và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           'lời</td></tr><tr><td>Can + S + V?... có thể... không?</td><td>Yes, S can. Có,... có thể.<br>No, S can’t. Không,... không thể.</td></tr><tr><td>Ví '
           'dụ:<br>A: Can you ride a horse? Bạn có thể cưỡi ngựa không?<br>B: Yes, I can. Có, tôi có thể.<br>A: Can she sing? Cô ấy có thể hát không?<br>B: '
           'No, she can’t. Không, cô ấy không thể.</td></tr></table><p>2. Cách nói về việc ai đó có khả năng làm gì hoặc không có khả năng làm gì:</p><table '
           'class="tb"><tr><td>Có khả năng</td><td>Không có khả năng</td></tr><tr><td>S + can + V<br>… có thể...</td><td>S + can\'t + V ¦...không '
           "thể...</td></tr><tr><td>Ví dụ:<br>He can swim. Anh ấy có thể bơi.<br>She can't ride a horse. Cô ấy không thể cưỡi ngựa.</td></tr></table><p>3. "
           'Cách hỏi về việc ai đó có thể làm được điều gì và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>What + '
           'can + S + do?<br>… có thể làm gì?</td><td>S + can + V.<br>… có thể …</td></tr><tr><td>Ví dụ:<br>A: What can you do? Bạn có thể làm gì?<br>B: I can '
           'draw. Tôi có thể vẽ.</td></tr></table><p>* Lưu ý: S = Subject (Chủ ngữ)</p><p>V = Verb (Động từ)</p>',
 'title': 'Unit 5 – Things we can do: Luyện tập',
 'unit': 5}
