# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck1-de21',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'a1',
                        'instr': 'I. Listen and tick (nghe và chọn tranh đúng).',
                        'items': [{'id': 'a1.1', 'img': 'a1_1.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.2', 'img': 'a1_2.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.3', 'img': 'a1_3.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.4',
                                   'img': 'a1_4.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'a2',
                        'instr': 'II. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'a2.5', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.6', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.7', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.8', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de21/a2.png" alt="Tranh A-D">'},
                       {'id': 'a3',
                        'instr': 'III. Listen and tick or cross (nghe, nội dung nghe có khớp với tranh không?).',
                        'items': [{'id': 'a3.9', 'img': 'a3_1.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'},
                                  {'id': 'a3.10', 'img': 'a3_2.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'}]},
                       {'id': 'a4',
                        'instr': 'IV. Listen and write (nghe và điền từ).',
                        'items': [{'id': 'a4.11', 'q': 'A: Why do you like English?<br>B: Because I want to be an English {_}.', 't': 'fill'},
                                  {'id': 'a4.12', 'q': 'A: How many {_} are there at your school?<br>B: There are three.', 't': 'fill'}]},
                       {'id': 'b1',
                        'instr': 'I. Look, read and match (đọc câu và chọn tranh a–f).',
                        'items': [{'id': 'b1.13',
                                   'left': [{'t': 'My friend is from England.'},
                                            {'t': 'I study at school on Tuesdays.'},
                                            {'t': 'There is one playground at my school.'},
                                            {'t': 'A: Where were you last weekend? B: I was in the countryside.'},
                                            {'t': 'A: What do you want to eat? B: I want some chips.'}],
                                   'o': ['a', 'b', 'c', 'd', 'e', 'f'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de21/b1.png" alt="Tranh a-f">'},
                       {'id': 'b2',
                        'instr': 'II. Read and tick True or False (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'b2.14', 'q': 'Trang, Bao, Uyen and Duong are in the same class.', 't': 'tf'},
                                  {'id': 'b2.15', 'q': 'Uyen likes P.E. because she wants to be a P.E. teacher.', 't': 'tf'},
                                  {'id': 'b2.16', 'q': 'Bao likes English very much.', 't': 'tf'},
                                  {'id': 'b2.17', 'q': 'Duong wants to be a famous artist.', 't': 'tf'},
                                  {'id': 'b2.18', 'q': 'Trang wants to be a singer.', 't': 'tf'}],
                        'passage': '<p>Hello, everyone. My name is Trang. I’m a student in class 4A at a primary school. Uyen, Bao and Duong are my '
                                   'classmates. Uyen likes English, because she wants to be an English teacher. Bao likes P.E., because he wants to be a '
                                   'footballer. Duong likes art, because he wants to be a famous artist. I like music, because I want to be a singer. We are '
                                   'very happy at our school.</p>'},
                       {'id': 'c1',
                        'instr': 'I. Look and complete (nhìn tranh, điền từ).',
                        'items': [{'id': 'c1.19', 'img': 'c1_1.png', 'q': 'I {_} on Sundays.', 't': 'fill'},
                                  {'id': 'c1.20', 'img': 'c1_2.png', 'q': '– Where is your school? – It’s in the {_}.', 't': 'fill'},
                                  {'id': 'c1.21', 'img': 'c1_3.png', 'q': 'I have {_} on Tuesdays and Thursdays.', 't': 'fill'},
                                  {'id': 'c1.22', 'img': 'c1_4.png', 'q': 'She can {_}.', 't': 'fill'},
                                  {'id': 'c1.23', 'img': 'c1_5.png', 'q': 'I {_} at 6.30 in the evening.', 't': 'fill'}]},
                       {'id': 'c2',
                        'instr': 'Reorder the words (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'c2.24',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['buildings', 'three', 'are', 'school.', 'my', 'at', 'There']},
                                  {'id': 'c2.25', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['today.', 'It', 'Sunday', 'is']},
                                  {'id': 'c2.26', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['breakfast', '6.15.', 'eat', 'I', 'at']},
                                  {'id': 'c2.27', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['can’t', 'badminton.', 'I', 'play']},
                                  {'id': 'c2.28',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['in', 'last', 'Da', 'Nang', 'was', 'I', 'weekend.']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 1 – Đề 21 (25-26)',
 'unit': 'CuoiKy1'}
