# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u9-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["What's your favourite subject?", 'When do you have English?', 'Is your sports day in June?', "What's that?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về ngày hội thể thao?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['do', 'make', 'play', 'take'], 'plain': True, 'q': 'We ____________ many sports and games.', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["It's in December.",
                                         "It's PE.",
                                         "It's a picture of our sports day.",
                                         'Yes, it is.',
                                         'Because I want to be a football player.'],
                                   'plain': True,
                                   'q': "What's that?",
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____.",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'in', 'day', 'sports', 'Our', 'June.']},
                                  {'id': 't1.6',
                                   'o': ["It's a picture of our sports day.", "It's in June.", 'Yes, it is.', 'My birthday is in May.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Is your sports day in May?”',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['Is', 'Are', 'Do', 'Does'], 'plain': True, 'q': '____________ your sports day in June?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ["It's in December.",
                                         "It's PE.",
                                         "It's a picture of our sports day.",
                                         'Yes, it is.',
                                         'Because I want to be a football player.'],
                                   'plain': True,
                                   'q': "When's your sports day?",
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What _____ you do on Saturdays?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sports', "When's", 'day?', 'your']},
                                  {'id': 't1.11',
                                   'o': ['What subjects do you have today?',
                                         'Is your sports day in September?',
                                         'Why do you like it?',
                                         "When's your sports day?"],
                                   'plain': True,
                                   'q': 'Câu "It\'s in September." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ["What's", "How's", "When's", "Where's"],
                                   'plain': True,
                                   'q': 'A: ____________ your sports day?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ["It's in December.",
                                         "It's PE.",
                                         "It's a picture of our sports day.",
                                         'Yes, it is.',
                                         'Because I want to be a football player.'],
                                   'plain': True,
                                   'q': 'Is your sports day in July?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: I _____ football and games with my friends.',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['December.', 'day', 'in', 'The', 'is', 'sports']},
                                  {'id': 't1.16',
                                   'o': ['I like sports.', "No, it isn't.", "It's in December.", 'We plays many sports and games.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “When\'s your sports day?"',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: Is your sports day in February?', 't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ["It's in December.",
                                         "It's PE.",
                                         "It's a picture of our sports day.",
                                         'Yes, it is.',
                                         'Because I want to be a football player.'],
                                   'plain': True,
                                   'q': 'Why do you like it?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['play', "When's", 'October', 'do', 'Saturday', 'Is'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: I like football and games. Our sports day is in September. _____ your sports day in '
                                        'September too?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['October?', 'day', 'in', 'your', 'Is', 'sports']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 9 – Our sports day: Kiểm tra 1',
 'unit': 9}
