# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['What did you do there?'],
 't1.10': ['Where were you yesterday?'],
 't1.11': 'Hôm qua bạn ở bãi biển phải không? Bản word phát hành từ Tailieuchuan.vn',
 't1.12': 'is',
 't1.13': ['I was at the campsite yesterday.'],
 't1.14': 'Were you at the zoo last weekend?',
 't1.15': 'Were',
 't1.16': 'I was at the zoo yesterday.',
 't1.17': 'Were',
 't1.18': ['Were you on the beach last weekend?'],
 't1.19': "It's in September.",
 't1.2': "No, I wasn't. I was on the beach last Sunday.",
 't1.20': 'was',
 't1.3': 'last summer',
 't1.4': ['I painted a picture of my hometown.'],
 't1.5': 'Mùa hè vừa rồi bạn đã ở đâu?',
 't1.6': 'was',
 't1.7': ['I played badminton with my cousin.'],
 't1.8': 'Where were you last summer?',
 't1.9': 'was'}

EXPLANATIONS = {'t1.1': 'Câu đúng: What did you do there?',
 't1.10': 'Câu đúng: Where were you yesterday?',
 't1.11': 'Đáp án: Hôm qua bạn ở bãi biển phải không? Bản word phát hành từ Tailieuchuan.vn',
 't1.12': 'Đáp án: is',
 't1.13': 'Câu đúng: I was at the campsite yesterday.',
 't1.14': 'Đáp án: Were you at the zoo last weekend?',
 't1.15': 'Đáp án: Were',
 't1.16': 'Đáp án: I was at the zoo yesterday.',
 't1.17': 'Đáp án: Were',
 't1.18': 'Câu đúng: Were you on the beach last weekend?',
 't1.19': "Đáp án: It's in September.",
 't1.2': "Đáp án: No, I wasn't. I was on the beach last Sunday.",
 't1.20': 'Đáp án: was',
 't1.3': 'Đáp án: last summer',
 't1.4': 'Câu đúng: I painted a picture of my hometown.',
 't1.5': 'Đáp án: Mùa hè vừa rồi bạn đã ở đâu?',
 't1.6': 'Đáp án: was',
 't1.7': 'Câu đúng: I played badminton with my cousin.',
 't1.8': 'Đáp án: Where were you last summer?',
 't1.9': 'Đáp án: was'}
