# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Where do you go?',
 't1.10': 'does',
 't1.11': 'She cooks meals on Saturdays.',
 't1.12': ['What do you do on Sundays?'],
 't1.13': 'What does she do on Sundays?',
 't1.14': 'does',
 't1.15': 'He goes to the sport centre.',
 't1.16': ['I play football with my friends.'],
 't1.17': 'Where does he go on Saturdays?',
 't1.18': 'cooks',
 't1.19': 'I go to the swimming pool.',
 't1.2': 'does',
 't1.20': ['Where does your father go on Saturdays?'],
 't1.3': 'She does yoga on Sundays.',
 't1.4': ['Where do you go on Sundays?'],
 't1.5': 'Where does she go on Sundays?',
 't1.6': 'goes',
 't1.7': 'He plays tennis on Sundays.',
 't1.8': ['I go to the sports centre on Sundays.'],
 't1.9': 'She goes to the cinema on Sundays.'}

EXPLANATIONS = {'t1.1': 'Đáp án: Where do you go?',
 't1.10': 'Đáp án: does',
 't1.11': 'Đáp án: She cooks meals on Saturdays.',
 't1.12': 'Câu đúng: What do you do on Sundays?',
 't1.13': 'Đáp án: What does she do on Sundays?',
 't1.14': 'Đáp án: does',
 't1.15': 'Đáp án: He goes to the sport centre.',
 't1.16': 'Câu đúng: I play football with my friends.',
 't1.17': 'Đáp án: Where does he go on Saturdays?',
 't1.18': 'Đáp án: cooks',
 't1.19': 'Đáp án: I go to the swimming pool.',
 't1.2': 'Đáp án: does',
 't1.20': 'Câu đúng: Where does your father go on Saturdays?',
 't1.3': 'Đáp án: She does yoga on Sundays.',
 't1.4': 'Câu đúng: Where do you go on Sundays?',
 't1.5': 'Đáp án: Where does she go on Sundays?',
 't1.6': 'Đáp án: goes',
 't1.7': 'Đáp án: He plays tennis on Sundays.',
 't1.8': 'Câu đúng: I go to the sports centre on Sundays.',
 't1.9': 'Đáp án: She goes to the cinema on Sundays.'}
