# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': "What's the name of your school?",
 'a.10': "It's Nguyen Du Primary School.",
 'a.2': 'Where is your school?',
 'a.3': 'Có một sân chơi ở trường của tôi.',
 'a.4': "It's in the village.",
 'a.5': 'How many buildings are there at your school?',
 'a.6': 'How many gardens are there at your school?',
 'a.7': 'How many playgrounds are there at your school?',
 'a.8': 'Our school is near two villages.',
 'a.9': 'Our school is in the mountains.',
 'b.1': 'Where',
 'b.10': 'How',
 'b.2': 'is',
 'b.3': 'playgrounds',
 'b.4': 'are',
 'b.5': 'buildings',
 'b.6': 'villages',
 'b.7': 'park',
 'b.8': 'is',
 'b.9': 'are',
 'c.1': {'blanks': [["It's in the town."],
                    ['Nguyen Du Primary School.'],
                    ['There is a playground at my school.'],
                    ['There is a garden at her school.'],
                    ['There are two computer rooms at his school.']]},
 'd.1': 'Where',
 'd.2': 'from',
 'd.3': 'school',
 'd.4': 'in',
 'd.5': 'How',
 'd.6': 'playground',
 'd.7': 'are there',
 'e.1': 'F',
 'e.2': 'T',
 'e.3': 'F',
 'e.4': 'T',
 'e.5': 'T',
 'e.6': 'T',
 'f.1': ['What is the name of your school?'],
 'f.10': ['I love my school.'],
 'f.2': ['Where is your school?'],
 'f.3': ['My school is in a village.'],
 'f.4': ['There are two playgrounds and a big garden at my school.'],
 'f.5': ['How many buildings are there at your school?'],
 'f.6': ['There are two buildings at our school.'],
 'f.7': ['There is a big playround there.'],
 'f.8': ['We can play sports in the playground.'],
 'f.9': ['There are two villages not far from my school.'],
 'n.10': 'F',
 'n.2': ['city'],
 'n.4': "It's in the village.",
 'n.5': ['school'],
 'n.6': 'There is one.',
 'n.7': 'There are three.',
 'n.8': 'There are two.',
 'n.9': ['two']}

EXPLANATIONS = {'a.1': "Đáp án: What's the name of your school?",
 'a.10': "Đáp án: It's Nguyen Du Primary School.",
 'a.2': 'Đáp án: Where is your school?',
 'a.3': 'Đáp án: Có một sân chơi ở trường của tôi.',
 'a.4': "Đáp án: It's in the village.",
 'a.5': 'Đáp án: How many buildings are there at your school?',
 'a.6': 'Đáp án: How many gardens are there at your school?',
 'a.7': 'Đáp án: How many playgrounds are there at your school?',
 'a.8': 'Đáp án: Our school is near two villages.',
 'a.9': 'Đáp án: Our school is in the mountains.',
 'b.1': 'Đáp án: Where',
 'b.10': 'Đáp án: How',
 'b.2': 'Đáp án: is',
 'b.3': 'Đáp án: playgrounds',
 'b.4': 'Đáp án: are',
 'b.5': 'Đáp án: buildings',
 'b.6': 'Đáp án: villages',
 'b.7': 'Đáp án: park',
 'b.8': 'Đáp án: is',
 'b.9': 'Đáp án: are',
 'c.1': "Where's her school? → It's in the town.; What's the name of your school? → Nguyen Du Primary School.; How many playgrounds are there at your school? "
        '→ There is a playground at my school.; How many gardens are there at her school? → There is a garden at her school.; How many computer rooms are '
        'there at his school? → There are two computer rooms at his school.',
 'd.1': 'Đáp án: Where',
 'd.2': 'Đáp án: from',
 'd.3': 'Đáp án: school',
 'd.4': 'Đáp án: in',
 'd.5': 'Đáp án: How',
 'd.6': 'Đáp án: playground',
 'd.7': 'Đáp án: are there',
 'e.1': 'Đáp án: False (Sai)',
 'e.2': 'Đáp án: True (Đúng)',
 'e.3': 'Đáp án: False (Sai)',
 'e.4': 'Đáp án: True (Đúng)',
 'e.5': 'Đáp án: True (Đúng)',
 'e.6': 'Đáp án: True (Đúng)',
 'f.1': 'Câu đúng: What is the name of your school?',
 'f.10': 'Câu đúng: I love my school.',
 'f.2': 'Câu đúng: Where is your school?',
 'f.3': 'Câu đúng: My school is in a village.',
 'f.4': 'Câu đúng: There are two playgrounds and a big garden at my school.',
 'f.5': 'Câu đúng: How many buildings are there at your school?',
 'f.6': 'Câu đúng: There are two buildings at our school.',
 'f.7': 'Câu đúng: There is a big playround there.',
 'f.8': 'Câu đúng: We can play sports in the playground.',
 'f.9': 'Câu đúng: There are two villages not far from my school.',
 'n.10': 'Đáp án: False (Sai)',
 'n.2': 'Đáp án: city',
 'n.4': "Đáp án: It's in the village.",
 'n.5': 'Đáp án: school',
 'n.6': 'Đáp án: There is one.',
 'n.7': 'Đáp án: There are three.',
 'n.8': 'Đáp án: There are two.',
 'n.9': 'Đáp án: two'}
