# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_dc2.py"""

ANS = {'e1.1': {'blanks': [['She lives in Le Lai Street.'],
                     ['Yes, I do.'],
                     ['He was at Green Hotel.'],
                     ['It’s big and busy.'],
                     ['No, it isn’t. It is quiet and beautiful.']]},
 'e10.64': '1',
 'e10.65': '4',
 'e10.66': '6',
 'e10.67': '2',
 'e10.68': '5',
 'e10.69': '3',
 'e11.70': ['What do you do in the morning?'],
 'e11.71': ['I help my mother with the cooking.'],
 'e11.72': ['My family watches TV together in the evening.'],
 'e11.73': ['Do you wash your clothes in the afternoon?'],
 'e11.74': ['I do the housework with my parents.'],
 'e12.75': {'blanks': [['He goes to the gym.'],
                       ['She does yoga.'],
                       ['I go the the cinema on Saturdays.'],
                       ['No. I stay at home.'],
                       ['I cook meals for my family.']]},
 'e13.76': 'B',
 'e13.77': 'B',
 'e13.78': 'B',
 'e13.79': 'A',
 'e13.80': 'A',
 'e13.81': 'C',
 'e13.82': 'B',
 'e13.83': 'C',
 'e13.84': 'C',
 'e13.85': 'D',
 'e14.86': ['Where is your mother on Sunday?'],
 'e14.87': ['What does she do in the morning?'],
 'e14.88': ['We watch television on Sundays.'],
 'e14.89': ['On Sundays, my father goes to sports centre.'],
 'e14.90': ['What does he do there?'],
 'e2.10': 'D',
 'e2.11': 'A',
 'e2.2': 'C',
 'e2.3': 'D',
 'e2.4': 'A',
 'e2.5': 'C',
 'e2.6': 'B',
 'e2.7': 'C',
 'e2.8': 'A',
 'e2.9': 'A',
 'e3.12': ['What is the street like?'],
 'e3.13': ['She lives in Hai Ba Trung Street.'],
 'e3.14': ['It is a beautiful and quiet village.'],
 'e3.15': ['My parents are at Green Hotel.'],
 'e3.16': ['My aunt lives in a big house with a beautiful garden.'],
 'e4.17': {'blanks': [['She is a policeman.'],
                      ['No. She works at a school.'],
                      ['She works at a nursing home.'],
                      ['Yes, they do.'],
                      ['There are four people.']]},
 'e5.18': 'A',
 'e5.19': 'B',
 'e5.20': 'A',
 'e5.21': 'B',
 'e5.22': 'A',
 'e5.23': 'B',
 'e5.24': 'D',
 'e5.25': 'C',
 'e5.26': 'B',
 'e5.27': 'A',
 'e6.28': 'A',
 'e6.29': 'A',
 'e6.30': 'B',
 'e6.31': 'A',
 'e6.32': 'A',
 'e6.33': 'B',
 'e6.34': 'A',
 'e6.35': 'A',
 'e6.36': 'C',
 'e6.37': 'C',
 'e7.38': ['old'],
 'e7.39': ['does'],
 'e7.40': ['do'],
 'e7.41': ['a'],
 'e7.42': ['short'],
 'e7.43': ['are'],
 'e8.44': ['Today is Monday.'],
 'e8.45': ['He has long hair.'],
 'e8.46': ['She has a small face.'],
 'e8.47': ['What does your mother look like?'],
 'e8.48': ['My father has a round face.'],
 'e8.49': ['My little sister has big eyes.'],
 'e8.50': ['My mother has beautiful hands.'],
 'e8.51': ['My grandfather is slim.'],
 'e8.52': ['Do you have a sister?'],
 'e8.53': ["No, I don't. I have a brother."],
 'e9.54': 'C',
 'e9.55': 'C',
 'e9.56': 'A',
 'e9.57': 'A',
 'e9.58': 'B',
 'e9.59': 'A',
 'e9.60': 'B',
 'e9.61': 'A',
 'e9.62': 'D',
 'e9.63': 'A'}

EXPLANATIONS = {'e1.1': '1 – B; 2 – C; 3 – D; 4 – E; 5 – A. Where does she live? → She lives in Le Lai Street. | Do you live at 9 Quang Trung Road? → Yes, I do. | Where was '
         'he last weekend? → He was at Green Hotel. | What’s the city like? → It’s big and busy. | Is the village noisy? → No, it isn’t. It is quiet and '
         'beautiful.',
 'e10.64': 'Thứ tự đúng: A – D – F – B – E – C. Câu A ở vị trí 1.',
 'e10.65': 'Thứ tự đúng: A – D – F – B – E – C. Câu B ở vị trí 4.',
 'e10.66': 'Thứ tự đúng: A – D – F – B – E – C. Câu C ở vị trí 6.',
 'e10.67': 'Thứ tự đúng: A – D – F – B – E – C. Câu D ở vị trí 2.',
 'e10.68': 'Thứ tự đúng: A – D – F – B – E – C. Câu E ở vị trí 5.',
 'e10.69': 'Thứ tự đúng: A – D – F – B – E – C. Câu F ở vị trí 3.',
 'e11.70': 'Câu đúng: What do you do in the morning?',
 'e11.71': 'Câu đúng: I help my mother with the cooking.',
 'e11.72': 'Câu đúng: My family watches TV together in the evening.',
 'e11.73': 'Câu đúng: Do you wash your clothes in the afternoon?',
 'e11.74': 'Câu đúng: I do the housework with my parents.',
 'e12.75': '1 – C; 2 – A; 3 – E; 4 – B; 5 – D. Where does your brother go on Sundays? → He goes to the gym. | What does she do there? → She does yoga. | Where '
           'do you go on Saturdays? → I go the the cinema on Saturdays. | Do you go to the shopping centre? → No. I stay at home. | What do you do at the '
           'weekends? → I cook meals for my family.',
 'e13.76': 'Đáp án: B. does',
 'e13.77': 'Đáp án: B. does',
 'e13.78': 'Đáp án: B. goes',
 'e13.79': 'Đáp án: A. go',
 'e13.80': 'Đáp án: A. he',
 'e13.81': 'Đáp án: C. you',
 'e13.82': 'Đáp án: B. On',
 'e13.83': 'Đáp án: C. at',
 'e13.84': 'Đáp án: C. shopping centre',
 'e13.85': 'Đáp án: D. swimming pool',
 'e14.86': 'Câu đúng: Where is your mother on Sunday?',
 'e14.87': 'Câu đúng: What does she do in the morning?',
 'e14.88': 'Câu đúng: We watch television on Sundays.',
 'e14.89': 'Câu đúng: On Sundays, my father goes to sports centre.',
 'e14.90': 'Câu đúng: What does he do there?',
 'e2.10': 'Đáp án: D. busy',
 'e2.11': 'Đáp án: A. quiet',
 'e2.2': 'Đáp án: C. Where',
 'e2.3': 'Đáp án: D. she',
 'e2.4': 'Đáp án: A. do',
 'e2.5': 'Đáp án: C. at',
 'e2.6': 'Đáp án: B. lives',
 'e2.7': 'Đáp án: C. small',
 'e2.8': 'Đáp án: A. in',
 'e2.9': 'Đáp án: A. is',
 'e3.12': 'Câu đúng: What is the street like?',
 'e3.13': 'Câu đúng: She lives in Hai Ba Trung Street.',
 'e3.14': 'Câu đúng: It is a beautiful and quiet village.',
 'e3.15': 'Câu đúng: My parents are at Green Hotel.',
 'e3.16': 'Câu đúng: My aunt lives in a big house with a beautiful garden.',
 'e4.17': '1 – D; 2 – B; 3 – A; 4 – C; 5 – E. What does your mother do? → She is a policeman. | Does she work on a farm? → No. She works at a school. | Where '
          'does he work? → She works at a nursing home. | Do they work at a factory? → Yes, they do. | How many people are there in your family? → There are '
          'four people.',
 'e5.18': 'Đáp án: A. people',
 'e5.19': 'Đáp án: B. does',
 'e5.20': 'Đáp án: A. do',
 'e5.21': 'Đáp án: B. Where',
 'e5.22': 'Đáp án: A. they',
 'e5.23': 'Đáp án: B. works',
 'e5.24': 'Đáp án: D. are',
 'e5.25': 'Đáp án: C. on',
 'e5.26': 'Đáp án: B. in',
 'e5.27': 'Đáp án: A. students',
 'e6.28': 'Đáp án: A. Do. Đề cương ghi D (Done) nhưng "___ you have a brother?" cần trợ động từ Do.',
 'e6.29': 'Đáp án: A. he',
 'e6.30': 'Đáp án: B. has',
 'e6.31': 'Đáp án: A. a',
 'e6.32': 'Đáp án: A. have',
 'e6.33': 'Đáp án: B. slim. Đề cương ghi A (big) nhưng người nặng 36 kg là "slim" (mảnh khảnh).',
 'e6.34': 'Đáp án: A. tall',
 'e6.35': 'Đáp án: A. big',
 'e6.36': 'Đáp án: C. Her',
 'e6.37': 'Đáp án: C. He',
 'e7.38': 'Đáp án: old',
 'e7.39': 'Đáp án: does',
 'e7.40': 'Đáp án: do',
 'e7.41': 'Đáp án: a',
 'e7.42': 'Đáp án: short',
 'e7.43': 'Đáp án: are (chủ ngữ số nhiều). Đề cương ghi "is".',
 'e8.44': 'Câu đúng: Today is Monday. Bỏ "on": Today is Monday (trước thứ trong tuần ở câu "Today is…" không dùng on).',
 'e8.45': 'Câu đúng: He has long hair. Bỏ "a": hair là danh từ không đếm được.',
 'e8.46': 'Câu đúng: She has a small face. have → has (chủ ngữ she).',
 'e8.47': 'Câu đúng: What does your mother look like? do → does (chủ ngữ your mother).',
 'e8.48': 'Câu đúng: My father has a round face. an → a (round bắt đầu bằng phụ âm).',
 'e8.49': 'Câu đúng: My little sister has big eyes. have → has (chủ ngữ my little sister).',
 'e8.50': 'Câu đúng: My mother has beautiful hands. hand → hands (bộ phận cơ thể có hai cái dùng số nhiều).',
 'e8.51': 'Câu đúng: My grandfather is slim. are → is (chủ ngữ số ít). KEY ghi "are => slim" là sai chính tả của đề cương.',
 'e8.52': 'Câu đúng: Do you have a sister? does → do (chủ ngữ you).',
 'e8.53': "Câu đúng: No, I don't. I have a brother. do → don't (trả lời phủ định).",
 'e9.54': 'Đáp án: C. at',
 'e9.55': 'Đáp án: C. cleans',
 'e9.56': 'Đáp án: A. helps',
 'e9.57': 'Đáp án: A. do. Đề cương ghi B (does) nhưng chủ ngữ "I" đi với do.',
 'e9.58': 'Đáp án: B. reads. Đề cương ghi A (read) nhưng "My family" là chủ ngữ số ít → reads (như câu "My family watches TV").',
 'e9.59': 'Đáp án: A. When',
 'e9.60': 'Đáp án: B. does',
 'e9.61': 'Đáp án: A. do',
 'e9.62': 'Đáp án: D. I',
 'e9.63': 'Đáp án: A. clean'}
