# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Where are you from?',
 't1.10': "Where's she from?",
 't1.11': 'is',
 't1.12': ['Where are you from?'],
 't1.13': "What's your name?",
 't1.14': 'are',
 't1.15': "I'm fine, thank you.",
 't1.16': 'Bill',
 't1.17': ['My name is Minh.'],
 't1.18': 'Where are you from?',
 't1.19': 'is',
 't1.2': 'am',
 't1.20': "She's from America.",
 't1.3': ['Where is he from?'],
 't1.4': "It's my new friend.",
 't1.5': 'are',
 't1.6': ['Malee is from Thailand.'],
 't1.7': 'Đó là bạn mới của tôi.',
 't1.8': 'is',
 't1.9': ['They are my good friends.']}

EXPLANATIONS = {'t1.1': 'Đáp án: Where are you from?',
 't1.10': "Đáp án: Where's she from?",
 't1.11': 'Đáp án: is',
 't1.12': 'Câu đúng: Where are you from?',
 't1.13': "Đáp án: What's your name?",
 't1.14': 'Đáp án: are',
 't1.15': "Đáp án: I'm fine, thank you.",
 't1.16': 'Đáp án: Bill',
 't1.17': 'Câu đúng: My name is Minh.',
 't1.18': 'Đáp án: Where are you from?',
 't1.19': 'Đáp án: is',
 't1.2': 'Đáp án: am',
 't1.20': "Đáp án: She's from America.",
 't1.3': 'Câu đúng: Where is he from?',
 't1.4': "Đáp án: It's my new friend.",
 't1.5': 'Đáp án: are',
 't1.6': 'Câu đúng: Malee is from Thailand.',
 't1.7': 'Đáp án: Đó là bạn mới của tôi.',
 't1.8': 'Đáp án: is',
 't1.9': 'Câu đúng: They are my good friends.'}
