# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['When is your birthday?'],
 't1.10': 'eat',
 't1.11': ["When is your brother's birthday?"],
 't1.12': '"When\'s your birthday, Mai?"',
 't1.13': 'What',
 't1.14': ['It is in September.'],
 't1.15': 'Sinh nhật của tôi là vào tháng Ba.',
 't1.16': 'in',
 't1.17': ['What does she want to eat?'],
 't1.18': 'What do you want to drink, Mai?',
 't1.19': 'drink',
 't1.2': 'What do you want to eat?',
 't1.20': ['She wants to eat some bread.'],
 't1.3': 'grapes',
 't1.4': 'I want some lemonade.',
 't1.5': 'drink',
 't1.6': ['My birthday is in October.'],
 't1.7': 'What do you want to drink?',
 't1.8': 'December',
 't1.9': "I'm making a cake for my birthday party."}

EXPLANATIONS = {'t1.1': 'Câu đúng: When is your birthday?',
 't1.10': 'Đáp án: eat',
 't1.11': "Câu đúng: When is your brother's birthday?",
 't1.12': 'Đáp án: "When\'s your birthday, Mai?"',
 't1.13': 'Đáp án: What',
 't1.14': 'Câu đúng: It is in September.',
 't1.15': 'Đáp án: Sinh nhật của tôi là vào tháng Ba.',
 't1.16': 'Đáp án: in',
 't1.17': 'Câu đúng: What does she want to eat?',
 't1.18': 'Đáp án: What do you want to drink, Mai?',
 't1.19': 'Đáp án: drink',
 't1.2': 'Đáp án: What do you want to eat?',
 't1.20': 'Câu đúng: She wants to eat some bread.',
 't1.3': 'Đáp án: grapes',
 't1.4': 'Đáp án: I want some lemonade.',
 't1.5': 'Đáp án: drink',
 't1.6': 'Câu đúng: My birthday is in October.',
 't1.7': 'Đáp án: What do you want to drink?',
 't1.8': 'Đáp án: December',
 't1.9': "Đáp án: I'm making a cake for my birthday party."}
