# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u20-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Where are you, Minh?', 'What does it say?', 'What is he doing?', 'What are they doing?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi một người nào đó đang làm gì?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['is', "isn't", 'do', 'does'], 'plain': True, 'q': 'A: Hi, Lan. Is Minh there?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['She is studing English.',
                                         'They are at the campsite.',
                                         'Yes, she is.',
                                         'They are playing tug of war.',
                                         "He's at school."],
                                   'plain': True,
                                   'q': 'Where are Lucy and Sarah?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Is', 'Are', 'Do', 'Does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Mary: _____ Bill and Ben at the campsite, Lucy?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['and', 'his', 'Bill', 'are', 'Where', 'friends?']},
                                  {'id': 't1.6',
                                   'o': ['Where are Nam and Minh?', 'Is Nam there?', "Where's Nam?", 'What is Nam doing?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi một người nào đó đang ở đâu?',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['Where', 'What', 'When', 'How'], 'plain': True, 'q': 'A: ____________ is he doing?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['She is studing English.',
                                         'They are at the campsite.',
                                         'Yes, she is.',
                                         'They are playing tug of war.',
                                         "He's at school."],
                                   'plain': True,
                                   'q': 'What are they doing?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['he', 'she', 'we', 'they'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Lucy: Yes, _____ are.',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['and', 'Minh', 'What', 'Lan?', 'Nam', 'are', 'doing,']},
                                  {'id': 't1.11',
                                   'o': ['What are you doing, Minh?', 'What are they doing?', 'Where are they, Minh?', 'Are Nam and Minh there?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi một nhóm người nào đó đang làm gì?',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: What ___________ Nam and Minh doing?', 't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['She is studing English.',
                                         'They are at the campsite.',
                                         'Yes, she is.',
                                         'They are playing tug of war.',
                                         "He's at school."],
                                   'plain': True,
                                   'q': "Where's Lucas, Mai?",
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['do', 'does', 'is', 'are'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Mary: What _____ they doing?',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['tent.', 'putting', 'a', 'They', 'up', 'are']},
                                  {'id': 't1.16',
                                   'o': ["Where's Mai?", 'What are they doing?', "What's Mai doing?", "What's he doing?"],
                                   'plain': True,
                                   'q': 'Câu: “She\'s singing." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['she is', 'she does', 'they are', 'they do'],
                                   'plain': True,
                                   'q': 'A: Are Mai and Lan at the campsite?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['She is studing English.',
                                         'They are at the campsite.',
                                         'Yes, she is.',
                                         'They are playing tug of war.',
                                         "He's at school."],
                                   'plain': True,
                                   'q': "What's she doing?",
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['play', 'plays', 'playing', 'to play'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Lucy: They are _____ tug of war.',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'doing,', 'Mai?', 'What', 'Mark']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 20 – At summer camp: Kiểm tra 1',
 'unit': 20}
