# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u4-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['birthday?', 'is', 'your', 'When']},
                                  {'id': 't1.2',
                                   'o': ['What do you want to drink?', 'What do you want to eat?', 'What does he want to drink?', 'What does she want to eat?'],
                                   'plain': True,
                                   'q': 'Câu: “I want some chips.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'o': ['grapes', 'lemonade d. juice d. water'], 'plain': True, 'q': 'A: What do you want to eat?', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['I want some meat.',
                                         "It's Tuesday.",
                                         'I want some lemonade.',
                                         "I'm making a cake for my birthday party.",
                                         "It's in November."],
                                   'plain': True,
                                   'q': 'What do you want to drink?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['cake', 'When', 'eat', 'drink', 'November'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 3. A: What do you want to _____, Lucy?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'birthday', 'is', 'October.', 'My']},
                                  {'id': 't1.7',
                                   'o': ['What day is it today?', "When's your birthday, Quan?", 'What do you want to drink?', 'What do you want to eat?'],
                                   'plain': True,
                                   'q': 'Câu “I want some lemonade." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['Thailand', 'Saturday', 'December', "seven o'clock."],
                                   'plain': True,
                                   'q': "A: When's your birthday?",
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['I want some meat.',
                                         "It's Tuesday.",
                                         'I want some lemonade.',
                                         "I'm making a cake for my birthday party.",
                                         "It's in November."],
                                   'plain': True,
                                   'q': 'What are you doing?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['cake', 'When', 'eat', 'drink', 'November'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: Thank you. What do you want to _____?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'birthday?', "brother's", 'is', 'When']},
                                  {'id': 't1.12',
                                   'o': ['"When\'s your birthday, Mai?"', 'Where are you from, Mai?', 'What day is it today, Mai?', 'What time is it, Mai?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là "Sinh nhật của bạn là khi nào vậy Mai?".',
                                   't': 'mcq'},
                                  {'id': 't1.13', 'o': ['What', 'When', 'Where', 'How'], 'plain': True, 'q': 'A: ____________ are you doing, Mai?', 't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'September.', 'It', 'is']},
                                  {'id': 't1.15',
                                   'o': ['Sinh nhật của tôi là vào tháng Năm.',
                                         'Sinh nhật của tôi là vào tháng Ba.',
                                         'Hôm nay là sinh nhật của tôi.',
                                         'Sinh nhật của tôi là vào tháng Bảy.'],
                                   'plain': True,
                                   'q': 'Câu “My birthday is in March.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.16', 'o': ['at', 'on', 'in', 'to'], 'plain': True, 'q': 'My birthday is _____________ November.', 't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'she', 'does', 'want', 'What', 'eat?']},
                                  {'id': 't1.18',
                                   'o': ['What do you do on Sundays, Mai?',
                                         'What do you want to drink, Mai?',
                                         'What do you want to eat, Mai?',
                                         'Where are you from, Mai?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn muốn uống gì vậy, Mai?”',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['play', 'do', 'eat', 'drink'],
                                   'plain': True,
                                   'q': 'A: What do you want to _____________, Quan?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['bread.', 'eat', 'some', 'wants', 'She', 'to']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 4 – My birthday party: Kiểm tra 2',
 'unit': 4}
