# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Sinh nhật của tôi là vào tháng Ba.',
 't1.10': 'Tôi muốn ăn nhỏ.',
 't1.11': 'milk',
 't1.12': ['She wants some chips and some milk.'],
 't1.13': "When's your birthday?",
 't1.14': 'When',
 't1.15': "It's Tuesday.",
 't1.16': 'When',
 't1.17': ['What are you doing, Lucy?'],
 't1.18': "When's your birthday?",
 't1.19': 'eat',
 't1.2': 'in',
 't1.20': "It's in November.",
 't1.3': ['What does she want to eat?'],
 't1.4': 'What do you want to drink, Mai?',
 't1.5': 'drink',
 't1.6': ['She wants to eat some bread.'],
 't1.7': 'What do you want to eat, Nam?',
 't1.8': 'When',
 't1.9': ['What does she want to drink?']}

EXPLANATIONS = {'t1.1': 'Đáp án: Sinh nhật của tôi là vào tháng Ba.',
 't1.10': 'Đáp án: Tôi muốn ăn nhỏ.',
 't1.11': 'Đáp án: milk',
 't1.12': 'Câu đúng: She wants some chips and some milk.',
 't1.13': "Đáp án: When's your birthday?",
 't1.14': 'Đáp án: When',
 't1.15': "Đáp án: It's Tuesday.",
 't1.16': 'Đáp án: When',
 't1.17': 'Câu đúng: What are you doing, Lucy?',
 't1.18': "Đáp án: When's your birthday?",
 't1.19': 'Đáp án: eat',
 't1.2': 'Đáp án: in',
 't1.20': "Đáp án: It's in November.",
 't1.3': 'Câu đúng: What does she want to eat?',
 't1.4': 'Đáp án: What do you want to drink, Mai?',
 't1.5': 'Đáp án: drink',
 't1.6': 'Câu đúng: She wants to eat some bread.',
 't1.7': 'Đáp án: What do you want to eat, Nam?',
 't1.8': 'Đáp án: When',
 't1.9': 'Câu đúng: What does she want to drink?'}
