# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_dc1.py"""

ANS = {'c1.123': 'A',
 'c1.124': 'A',
 'c1.125': 'A',
 'c1.126': 'A',
 'c1.127': 'C',
 'c1.128': 'C',
 'c1.129': 'B',
 'c1.130': 'B',
 'c1.131': 'B',
 'c2a.132': ['Australia'],
 'c2a.133': ['go to school'],
 'c2a.134': ['chicken'],
 'c2a.135': ['birthday'],
 'c2b.136': ['sing'],
 'c2b.137': ['unit'],
 'c2b.138': ['sunny'],
 'c2b.139': ['flowers'],
 'c2c.140': ['classrooms'],
 'c2c.141': ['subject'],
 'c2c.142': ['piano'],
 'c2c.143': ['activities'],
 'c2d.144': ['pupil'],
 'c2d.145': ['Fridays'],
 'c2d.146': ['play football'],
 'c2d.147': ['stay at home'],
 'c3a.148': {'blanks': [['b'], ['i'], ['e'], ['a'], ['h'], ['g'], ['c'], ['d'], ['f']]},
 'c3b.149': {'blanks': [['It’s six thirty.'],
                        ['I have music class at eight fifteen.'],
                        ['It’s in October.'],
                        ['I stay at home.'],
                        ['I have maths and Vietnamese.'],
                        ['We play sports and games.'],
                        ['She’s from Singapore.'],
                        ['No, he can’t.'],
                        ['I want some milk and juice.']]},
 'c4.150': ['Our Sports Day is in July.'],
 'c4.151': ['There are three music rooms at my school.'],
 'c4.152': ['I want some grapes at my birthday party.'],
 'c4.153': ['My favourite subject is English.'],
 'c4.154': ['Music is not his favourite subject.'],
 'c4.155': ['They play basketball on Sports day.'],
 'c4.156': ['We do housework at the weekend.'],
 'c4.157': ['There is one building at my school.'],
 'c4.158': ['I like English because I want to be an English teacher.'],
 'c4.159': ['My brother can’t ride a horse but he can roller skate.'],
 'c4.160': ['My sister can’t play the piano but she can sing.'],
 'c4.161': ['My parents have dinner at seven o’clock.'],
 'c4.162': ['We go to school from Mondays to Fridays.'],
 'c5.163': ['lemonade'],
 'c5.164': ['study'],
 'c5.165': ['guitar'],
 'c5.166': ['science'],
 'c5.167': ['mountains', 'mountain'],
 'c5.168': ['Britain'],
 'c5.169': ['fifteen'],
 'c5.170': ['building', 'garden'],
 'c5.171': ['America'],
 'c5.172': ['history and geography', 'geography and history'],
 'c5.173': ['August'],
 'c5.174': ['playground'],
 'c5.175': ['painter'],
 'c5.176': ['breakfast'],
 'c5.177': ['March'],
 'c5.178': ['Saturdays', 'Saturday'],
 'c5.179': ['Wednesdays', 'Wednesday'],
 'c5.180': ['village'],
 'mc.103': 'I’m from Viet Nam.',
 'mc.104': 'He’s/ She’s from Britain.',
 'mc.105': 'It’s six thirty.',
 'mc.106': 'I get up at five forty-five.',
 'mc.107': 'It’s in May.',
 'mc.108': 'I want some jam.',
 'mc.109': 'I want some lemonade.',
 'mc.110': 'Yes, I can/ No, I can’t.',
 'mc.111': 'Yes, he can./ No, he can’t.',
 'mc.112': 'Yes, she can./ No, she can’t.',
 'mc.113': 'It’s in the village.',
 'mc.114': 'There are two./ There is one.',
 'mc.115': 'I have English and maths.',
 'mc.116': 'I have it on Tuesdays and Fridays.',
 'mc.117': 'It’s art.',
 'mc.118': 'Because I want to be a painter.',
 'mc.119': 'Yes, it is./ No, it isn’t.',
 'mc.120': 'It’s in September.',
 'mc.121': 'Yes, I was./ No, I wasn’t.',
 'mc.122': 'I was in London.',
 'v1.1': 'nước Mỹ',
 'v1.10': 'thức dậy',
 'v1.11': 'số 45',
 'v1.12': 'đi ngủ',
 'v1.13': 'giờ đúng',
 'v1.14': 'đi học',
 'v1.15': 'số 30',
 'v1.16': 'ăn sáng',
 'v1.17': 'làm bài tập về nhà',
 'v1.18': 'ăn trưa',
 'v1.19': 'trò chuyện cùng bạn',
 'v1.2': 'nước Ma-lay-xi-a',
 'v1.20': 'ăn tối',
 'v1.21': 'Thứ 2',
 'v1.22': 'nghe nhạc',
 'v1.23': 'Thứ 3',
 'v1.24': 'làm việc nhà',
 'v1.25': 'Thứ 4',
 'v1.26': 'học ở trường',
 'v1.27': 'Thứ 5',
 'v1.28': 'ở nhà',
 'v1.29': 'Thứ 6',
 'v1.3': 'nước Úc',
 'v1.30': 'cuối tuần',
 'v1.31': 'Thứ 7',
 'v1.32': 'xem ti vi',
 'v1.33': 'Chủ nhật',
 'v1.34': 'hôm nay',
 'v1.4': 'nước Xin-ga-po',
 'v1.5': 'nước Anh',
 'v1.6': 'nước Thái Lan',
 'v1.7': 'nước Nhật',
 'v1.8': 'nước Việt Nam',
 'v1.9': 'số 15',
 'v2.35': 'Tháng 1',
 'v2.36': 'Tháng 6',
 'v2.37': 'Tháng 2',
 'v2.38': 'Tháng 7',
 'v2.39': 'Tháng 3',
 'v2.40': 'Tháng 8',
 'v2.41': 'Tháng 4',
 'v2.42': 'Tháng 9',
 'v2.43': 'Tháng 5',
 'v2.44': 'Tháng 10',
 'v2.45': 'ngày sinh',
 'v2.46': 'Tháng 11',
 'v2.47': 'quả nho',
 'v2.48': 'Tháng 12',
 'v2.49': 'mứt',
 'v2.50': 'nước chanh',
 'v2.51': 'nước ép',
 'v2.52': 'buổi tiệc',
 'v2.53': 'Khoai tây chiên',
 'v2.54': 'nước',
 'v2.55': 'có thể, biết (làm gì)',
 'v2.56': 'cưỡi ngựa',
 'v2.57': 'nấu ăn',
 'v2.58': 'trượt pa tin',
 'v2.59': 'chơi đàn piano',
 'v2.60': 'bơi lội',
 'v2.61': 'chơi đàn ghi ta',
 'v2.62': 'nhưng',
 'v2.63': 'đạp xe',
 'v2.64': 'vẽ tranh',
 'v3.100': 'To-ky-o ( thủ đô nước Nhật)',
 'v3.101': 'trước, lần trước',
 'v3.102': 'Luân đôn (thủ đô nước Anh)',
 'v3.65': 'ở thành phố',
 'v3.66': 'khu vườn',
 'v3.67': 'ở vùng núi',
 'v3.68': 'sân chơi',
 'v3.69': 'ở thị trấn',
 'v3.70': 'Tòa nhà',
 'v3.71': 'ở làng quê',
 'v3.72': 'phòng tin học',
 'v3.73': 'môn Mĩ thuật',
 'v3.74': 'môn Âm nhạc',
 'v3.75': 'môn Tiếng Anh',
 'v3.76': 'môn Khoa học',
 'v3.77': 'môn Lịch sử và Địa lí',
 'v3.78': 'môn Tiếng Việt',
 'v3.79': 'môn Toán, toán học',
 'v3.80': 'môn Tin học',
 'v3.81': 'môn học',
 'v3.82': 'môn thể dục',
 'v3.83': 'giáo viên (dạy Tiếng Anh)',
 'v3.84': 'họa sĩ',
 'v3.85': 'giáo viên (dạy Toán)',
 'v3.86': 'ca sĩ',
 'v3.87': 'yêu thích',
 'v3.88': 'bởi vì',
 'v3.89': 'viết truyện',
 'v3.90': 'tại sao',
 'v3.91': 'ngày hội thể thao',
 'v3.92': 'thể thao',
 'v3.93': 'trò chơi',
 'v3.94': 'khác nhau',
 'v3.95': 'bãi biển',
 'v3.96': 'Băng Cốc (thủ đô của nước Thái Lan)',
 'v3.97': 'địa điểm cắm trại',
 'v3.98': 'Xít-ni (thành phố của nước Úc)',
 'v3.99': 'nông thôn, vùng quê'}

EXPLANATIONS = {'c1.123': 'Đáp án: A. Viet Nam',
 'c1.124': 'Đáp án: A. Malaysia',
 'c1.125': 'Đáp án: A. Maths',
 'c1.126': 'Đáp án: A. ride a bike',
 'c1.127': 'Đáp án: C. study at school',
 'c1.128': 'Đáp án: C. six forty-five',
 'c1.129': 'Đáp án: B. singer',
 'c1.130': 'Đáp án: B. buildings',
 'c1.131': 'Đáp án: B. December',
 'c2a.132': 'Đáp án: Australia',
 'c2a.133': 'Đáp án: go to school',
 'c2a.134': 'Đáp án: chicken',
 'c2a.135': 'Đáp án: birthday',
 'c2b.136': 'Đáp án: sing',
 'c2b.137': 'Đáp án: unit',
 'c2b.138': 'Đáp án: sunny',
 'c2b.139': 'Đáp án: flowers',
 'c2c.140': 'Đáp án: classrooms',
 'c2c.141': 'Đáp án: subject',
 'c2c.142': 'Đáp án: piano',
 'c2c.143': 'Đáp án: activities',
 'c2d.144': 'Đáp án: pupil',
 'c2d.145': 'Đáp án: Fridays',
 'c2d.146': 'Đáp án: play football',
 'c2d.147': 'Đáp án: stay at home',
 'c3a.148': 'Đáp án: 1–b, 2–i, 3–e, 4–a, 5–h, 6–g, 7–c, 8–d, 9–f',
 'c3b.149': 'Đáp án: What time is it? → It’s six thirty.; What time do you have music class? → I have music class at eight fifteen.; When’s your birthday? → '
            'It’s in October.; What do you do on Sundays? → I stay at home.; What subjects do you have today? → I have maths and Vietnamese.; What do you do '
            'on sports day? → We play sports and games.; Where’s she from? → She’s from Singapore.; Can your brother ride a bike? → No, he can’t.; What do you '
            'want to drink? → I want some milk and juice.',
 'c4.150': 'Câu đúng: Our Sports Day is in July.',
 'c4.151': 'Câu đúng: There are three music rooms at my school.',
 'c4.152': 'Câu đúng: I want some grapes at my birthday party.',
 'c4.153': 'Câu đúng: My favourite subject is English.',
 'c4.154': 'Câu đúng: Music is not his favourite subject.',
 'c4.155': 'Câu đúng: They play basketball on Sports day.',
 'c4.156': 'Câu đúng: We do housework at the weekend.',
 'c4.157': 'Câu đúng: There is one building at my school.',
 'c4.158': 'Câu đúng: I like English because I want to be an English teacher.',
 'c4.159': 'Câu đúng: My brother can’t ride a horse but he can roller skate.',
 'c4.160': 'Câu đúng: My sister can’t play the piano but she can sing.',
 'c4.161': 'Câu đúng: My parents have dinner at seven o’clock.',
 'c4.162': 'Câu đúng: We go to school from Mondays to Fridays.',
 'c5.163': 'Đáp án: lemonade',
 'c5.164': 'Đáp án: study',
 'c5.165': 'Đáp án: guitar',
 'c5.166': 'Đáp án: science',
 'c5.167': 'Đáp án: mountains',
 'c5.168': 'Đáp án: Britain',
 'c5.169': 'Đáp án: fifteen',
 'c5.170': 'Đáp án: building',
 'c5.171': 'Đáp án: America',
 'c5.172': 'Đáp án: history and geography',
 'c5.173': 'Đáp án: August',
 'c5.174': 'Đáp án: playground',
 'c5.175': 'Đáp án: painter',
 'c5.176': 'Đáp án: breakfast',
 'c5.177': 'Đáp án: March',
 'c5.178': 'Đáp án: Saturdays',
 'c5.179': 'Đáp án: Wednesdays',
 'c5.180': 'Đáp án: village',
 'mc.103': 'Đáp án: I’m from Viet Nam.',
 'mc.104': 'Đáp án: He’s/ She’s from Britain.',
 'mc.105': 'Đáp án: It’s six thirty.',
 'mc.106': 'Đáp án: I get up at five forty-five.',
 'mc.107': 'Đáp án: It’s in May.',
 'mc.108': 'Đáp án: I want some jam.',
 'mc.109': 'Đáp án: I want some lemonade.',
 'mc.110': 'Đáp án: Yes, I can/ No, I can’t.',
 'mc.111': 'Đáp án: Yes, he can./ No, he can’t.',
 'mc.112': 'Đáp án: Yes, she can./ No, she can’t.',
 'mc.113': 'Đáp án: It’s in the village.',
 'mc.114': 'Đáp án: There are two./ There is one.',
 'mc.115': 'Đáp án: I have English and maths.',
 'mc.116': 'Đáp án: I have it on Tuesdays and Fridays.',
 'mc.117': 'Đáp án: It’s art.',
 'mc.118': 'Đáp án: Because I want to be a painter.',
 'mc.119': 'Đáp án: Yes, it is./ No, it isn’t.',
 'mc.120': 'Đáp án: It’s in September.',
 'mc.121': 'Đáp án: Yes, I was./ No, I wasn’t.',
 'mc.122': 'Đáp án: I was in London.',
 'v1.1': 'Đáp án: nước Mỹ',
 'v1.10': 'Đáp án: thức dậy',
 'v1.11': 'Đáp án: số 45',
 'v1.12': 'Đáp án: đi ngủ',
 'v1.13': 'Đáp án: giờ đúng',
 'v1.14': 'Đáp án: đi học',
 'v1.15': 'Đáp án: số 30',
 'v1.16': 'Đáp án: ăn sáng',
 'v1.17': 'Đáp án: làm bài tập về nhà',
 'v1.18': 'Đáp án: ăn trưa',
 'v1.19': 'Đáp án: trò chuyện cùng bạn',
 'v1.2': 'Đáp án: nước Ma-lay-xi-a',
 'v1.20': 'Đáp án: ăn tối',
 'v1.21': 'Đáp án: Thứ 2',
 'v1.22': 'Đáp án: nghe nhạc',
 'v1.23': 'Đáp án: Thứ 3',
 'v1.24': 'Đáp án: làm việc nhà',
 'v1.25': 'Đáp án: Thứ 4',
 'v1.26': 'Đáp án: học ở trường',
 'v1.27': 'Đáp án: Thứ 5',
 'v1.28': 'Đáp án: ở nhà',
 'v1.29': 'Đáp án: Thứ 6',
 'v1.3': 'Đáp án: nước Úc',
 'v1.30': 'Đáp án: cuối tuần',
 'v1.31': 'Đáp án: Thứ 7',
 'v1.32': 'Đáp án: xem ti vi',
 'v1.33': 'Đáp án: Chủ nhật',
 'v1.34': 'Đáp án: hôm nay',
 'v1.4': 'Đáp án: nước Xin-ga-po',
 'v1.5': 'Đáp án: nước Anh',
 'v1.6': 'Đáp án: nước Thái Lan',
 'v1.7': 'Đáp án: nước Nhật',
 'v1.8': 'Đáp án: nước Việt Nam',
 'v1.9': 'Đáp án: số 15',
 'v2.35': 'Đáp án: Tháng 1',
 'v2.36': 'Đáp án: Tháng 6',
 'v2.37': 'Đáp án: Tháng 2',
 'v2.38': 'Đáp án: Tháng 7',
 'v2.39': 'Đáp án: Tháng 3',
 'v2.40': 'Đáp án: Tháng 8',
 'v2.41': 'Đáp án: Tháng 4',
 'v2.42': 'Đáp án: Tháng 9',
 'v2.43': 'Đáp án: Tháng 5',
 'v2.44': 'Đáp án: Tháng 10',
 'v2.45': 'Đáp án: ngày sinh',
 'v2.46': 'Đáp án: Tháng 11',
 'v2.47': 'Đáp án: quả nho',
 'v2.48': 'Đáp án: Tháng 12',
 'v2.49': 'Đáp án: mứt',
 'v2.50': 'Đáp án: nước chanh',
 'v2.51': 'Đáp án: nước ép',
 'v2.52': 'Đáp án: buổi tiệc',
 'v2.53': 'Đáp án: Khoai tây chiên',
 'v2.54': 'Đáp án: nước',
 'v2.55': 'Đáp án: có thể, biết (làm gì)',
 'v2.56': 'Đáp án: cưỡi ngựa',
 'v2.57': 'Đáp án: nấu ăn',
 'v2.58': 'Đáp án: trượt pa tin',
 'v2.59': 'Đáp án: chơi đàn piano',
 'v2.60': 'Đáp án: bơi lội',
 'v2.61': 'Đáp án: chơi đàn ghi ta',
 'v2.62': 'Đáp án: nhưng',
 'v2.63': 'Đáp án: đạp xe',
 'v2.64': 'Đáp án: vẽ tranh',
 'v3.100': 'Đáp án: To-ky-o ( thủ đô nước Nhật)',
 'v3.101': 'Đáp án: trước, lần trước',
 'v3.102': 'Đáp án: Luân đôn (thủ đô nước Anh)',
 'v3.65': 'Đáp án: ở thành phố',
 'v3.66': 'Đáp án: khu vườn',
 'v3.67': 'Đáp án: ở vùng núi',
 'v3.68': 'Đáp án: sân chơi',
 'v3.69': 'Đáp án: ở thị trấn',
 'v3.70': 'Đáp án: Tòa nhà',
 'v3.71': 'Đáp án: ở làng quê',
 'v3.72': 'Đáp án: phòng tin học',
 'v3.73': 'Đáp án: môn Mĩ thuật',
 'v3.74': 'Đáp án: môn Âm nhạc',
 'v3.75': 'Đáp án: môn Tiếng Anh',
 'v3.76': 'Đáp án: môn Khoa học',
 'v3.77': 'Đáp án: môn Lịch sử và Địa lí',
 'v3.78': 'Đáp án: môn Tiếng Việt',
 'v3.79': 'Đáp án: môn Toán, toán học',
 'v3.80': 'Đáp án: môn Tin học',
 'v3.81': 'Đáp án: môn học',
 'v3.82': 'Đáp án: môn thể dục',
 'v3.83': 'Đáp án: giáo viên (dạy Tiếng Anh)',
 'v3.84': 'Đáp án: họa sĩ',
 'v3.85': 'Đáp án: giáo viên (dạy Toán)',
 'v3.86': 'Đáp án: ca sĩ',
 'v3.87': 'Đáp án: yêu thích',
 'v3.88': 'Đáp án: bởi vì',
 'v3.89': 'Đáp án: viết truyện',
 'v3.90': 'Đáp án: tại sao',
 'v3.91': 'Đáp án: ngày hội thể thao',
 'v3.92': 'Đáp án: thể thao',
 'v3.93': 'Đáp án: trò chơi',
 'v3.94': 'Đáp án: khác nhau',
 'v3.95': 'Đáp án: bãi biển',
 'v3.96': 'Đáp án: Băng Cốc (thủ đô của nước Thái Lan)',
 'v3.97': 'Đáp án: địa điểm cắm trại',
 'v3.98': 'Đáp án: Xít-ni (thành phố của nước Úc)',
 'v3.99': 'Đáp án: nông thôn, vùng quê'}
