# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u19-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['birds', 'likes', 'merrily.', 'because', 'She', 'they', 'sing']},
                                  {'id': 't1.2',
                                   'o': ["They're peacocks.", "They're lions.", "They're crocodiles.", "They're giraffes."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What animals have long necks and legs?”:',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['lions', 'giraffes', 'birds', 'hippos'],
                                   'plain': True,
                                   'q': 'A: Those animals swim well. What are they?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: Because they look _____.',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['like', 'peacocks?', 'you', 'do', 'Why']},
                                  {'id': 't1.6',
                                   'o': ["They're lions.", "They're monkeys.", "They're peacocks.", "They're hippos."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What animals dance beautifully”?:',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['monkeys', 'peacocks', 'birds', 'hippos'],
                                   'plain': True,
                                   'q': 'A: Those animals look scary. What are they?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['dance', 'because', 'I', 'like', 'beautifully.', 'peacocks', 'they']},
                                  {'id': 't1.9',
                                   'o': ['What are these animals?', 'Why do you like giraffes?', 'Why do you like birds?', 'What animals do you want to see?'],
                                   'plain': True,
                                   'q': 'Câu: “Because they sing merrily” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'o': ['is', 'are', 'does', 'do'], 'plain': True, 'q': 'Why ____________ Lan like monkeys?', 't': 'mcq'},
                                  {'id': 't1.11',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['to', 'see?', 'she', 'does', 'animals', 'want', 'What']},
                                  {'id': 't1.12',
                                   'o': ['They are birds.', 'They are giraffes.', 'They are hippos.', 'They are lions.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What animals roar loudly?”:',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['loud', 'quick', 'quickly', 'loudly'],
                                   'plain': True,
                                   'q': 'Those lions are roaring ____________.',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['hippos', 'strong.', 'look', 'they', 'because', 'She', 'likes']},
                                  {'id': 't1.15',
                                   'o': ['They look brave.', 'They are giraffes.', 'They look strong.', 'I like them.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What are these animals)”:',
                                   't': 'mcq'},
                                  {'id': 't1.16', 'o': ['do', 'does', 'is', 'are'], 'plain': True, 'q': 'A: What ____________ these animals?', 't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['I want to see giraffes.',
                                         'They are lions.',
                                         'He wants to see hippos.',
                                         'Because they are scary.',
                                         'Because they dance beautifully.'],
                                   'plain': True,
                                   'q': 'What are these animals?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: Wow, those _____ are so beautiful.',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'animals,', 'those', 'Minh?', 'What']},
                                  {'id': 't1.20',
                                   'o': ['They are lions.', 'They look strong.', 'They are giraffes.', 'Because they roar loudly.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like lions?”',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 19 – The animal world: Kiểm tra 3',
 'unit': 19}
