# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck1-de1',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'gi',
                        'instr': 'I. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'gi.1', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.2', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.3', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.4', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de1/gi.png" alt="Tranh a–d">'},
                       {'id': 'gii',
                        'instr': 'II. Listen and draw lines (nghe và nối nhân vật với tranh).',
                        'items': [{'id': 'gii.5',
                                   'left': [{'img': 'gii_l1.png', 't': ''},
                                            {'img': 'gii_l2.png', 't': ''},
                                            {'img': 'gii_l3.png', 't': ''},
                                            {'img': 'gii_l4.png', 't': ''}],
                                   'o': ['a', 'b', 'c', 'd'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de1/gii.png" alt="Tranh a–d">'},
                       {'id': 'giii',
                        'instr': 'III. Listen and complete (nghe và điền từ).',
                        'items': [{'id': 'giii.6', 'q': 'When’s your birthday? – It’s in {_}.', 't': 'fill'},
                                  {'id': 'giii.7', 'q': 'Where’s your school? – It’s in the {_}.', 't': 'fill'},
                                  {'id': 'giii.8', 'q': 'Why do you like {_}? – Because I want to be a painter.', 't': 'fill'},
                                  {'id': 'giii.9', 'q': 'Were you at the {_} last weekend? – Yes, I was.', 't': 'fill'}]},
                       {'id': 'giv',
                        'instr': 'IV. Read and choose A, B or C (nhìn tranh, chọn đáp án đúng).',
                        'items': [{'id': 'giv.10',
                                   'img': 'giv_1.png',
                                   'o': ['I have lunch at twelve fifteen.', 'I have lunch at half past twelve.', 'I have lunch at twelve o’clock.'],
                                   'q': 'What time do you have lunch?',
                                   't': 'mcq'},
                                  {'id': 'giv.11',
                                   'img': 'giv_2.png',
                                   'o': ['I was in Tokyo.', 'I were in Tokyo.', 'I was on Tokyo.'],
                                   'q': 'Where were you last month?',
                                   't': 'mcq'},
                                  {'id': 'giv.12',
                                   'img': 'giv_3.png',
                                   'o': ['I have Vietnamese.', 'I have maths.', 'I have English and science.'],
                                   'q': 'What subjects do you have today?',
                                   't': 'mcq'},
                                  {'id': 'giv.13',
                                   'img': 'giv_4.png',
                                   'o': ['There are one.', 'There is one playgrounds.', 'There is one.'],
                                   'q': 'How many playgrounds are there at your school?',
                                   't': 'mcq'}]},
                       {'id': 'gv',
                        'instr': 'V. Read and write T (True) or F (False) (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'gv.14', 'q': 'Jack is from Thailand.', 't': 'tf'},
                                  {'id': 'gv.15', 'q': 'Jack goes to the beach in the summer.', 't': 'tf'},
                                  {'id': 'gv.16', 'q': 'Jack can swim fast.', 't': 'tf'}],
                        'passage': '<p>This is Jack. He is my best friend. He is from Australia. He has been in Thailand for two years. He has two older '
                                   'brothers. They all live in a big house in Bangkok. Jack and his brothers go to the beach in the summer. They play beach '
                                   'ball or go swimming. Jack is very strong and he can swim fast.</p>'},
                       {'id': 'gvi',
                        'instr': 'VI. Write suitable questions for the answers given (nhìn tranh, viết câu hỏi phù hợp).',
                        'items': [{'id': 'gvi.17',
                                   'img': 'gvi_1.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>Because I want to be an English teacher.</i><br>{_}',
                                   't': 'fill'},
                                  {'id': 'gvi.18', 'img': 'gvi_2.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>It’s in October.</i><br>{_}', 't': 'fill'},
                                  {'id': 'gvi.19', 'img': 'gvi_3.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>I want some chips.</i><br>{_}', 't': 'fill'}]},
                       {'id': 'gvii',
                        'instr': 'VII. Fill in the blanks (điền từ vào chỗ trống, nhìn tranh).',
                        'items': [{'id': 'gvii.20', 'img': 'gvii_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'gvii.21', 'img': 'gvii_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'gvii.22', 'img': 'gvii_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'gvii.23', 'img': 'gvii_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Hi, I’m Sue. I’m 7 years old. This is my school. It’s not big but it’s beautiful. There are twenty <b>(1) ______</b> in '
                                   'my school. There is a small <b>(2) ______</b> We often run and play there at break time. There is also a <b>(3) ______</b> '
                                   'We plant trees and flowers there. We <b>(4) ______</b> at the school canteen.</p>'},
                       {'bank': ['Tuesdays', 'city', 'maths teacher', 'art and science'],
                        'id': 'gviii',
                        'instr': 'VIII. Write suitable answers to the questions using given words (dùng từ cho sẵn để trả lời).',
                        'items': [{'id': 'gviii.24', 'q': 'Where’s your school?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.25', 'q': 'Why do you like maths?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.26', 'q': 'What subjects do you have today?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.27', 'q': 'When do you have science?<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 1 – Đề 1',
 'unit': 'CuoiKy1'}
