# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'What subjects do you have today?',
 't1.10': ['I have English on Wednesdays and Fridays.'],
 't1.11': 'When do you have English?',
 't1.12': 'have',
 't1.13': "It's Wednesday.",
 't1.14': 'When',
 't1.15': ['Do you have Science on Mondays?'],
 't1.16': 'What subjects do you have today?',
 't1.17': 'do',
 't1.18': 'I have it on Monday and Thursdays.',
 't1.19': 'on',
 't1.2': "What's",
 't1.20': ['When do you have music?'],
 't1.3': 'I have Maths, Vietnamese and Science.',
 't1.4': 'it',
 't1.5': ['What subjects do you have today?'],
 't1.6': 'What subjects do you have today?',
 't1.7': 'it',
 't1.8': 'Yes, I do.',
 't1.9': "don't"}

EXPLANATIONS = {'t1.1': 'Đáp án: What subjects do you have today?',
 't1.10': 'Câu đúng: I have English on Wednesdays and Fridays.',
 't1.11': 'Đáp án: When do you have English?',
 't1.12': 'Đáp án: have',
 't1.13': "Đáp án: It's Wednesday.",
 't1.14': 'Đáp án: When',
 't1.15': 'Câu đúng: Do you have Science on Mondays?',
 't1.16': 'Đáp án: What subjects do you have today?',
 't1.17': 'Đáp án: do',
 't1.18': 'Đáp án: I have it on Monday and Thursdays.',
 't1.19': 'Đáp án: on',
 't1.2': "Đáp án: What's",
 't1.20': 'Câu đúng: When do you have music?',
 't1.3': 'Đáp án: I have Maths, Vietnamese and Science.',
 't1.4': 'Đáp án: it',
 't1.5': 'Câu đúng: What subjects do you have today?',
 't1.6': 'Đáp án: What subjects do you have today?',
 't1.7': 'Đáp án: it',
 't1.8': 'Đáp án: Yes, I do.',
 't1.9': "Đáp án: don't"}
