# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u1-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["What's your name?", "Who's that?", 'How are you?', 'Where are you from?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây dùng để hỏi tên của bạn?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['is', 'am', 'are', 'do'], 'plain': True, 'q': 'Where __________ you from?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["They're from Australia.", "I'm fine, thank you.", "He's from Vietnam.", "She's from America.", "It's my new friend."],
                                   'plain': True,
                                   'q': 'How are you, Mai?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['too', 'friend', 'Bill', 'from', 'Australia'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Bill: Hello, Nam. I'm _____.",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['name', 'Minh.', 'is', 'My']},
                                  {'id': 't1.6',
                                   'o': ['How are you today?', 'Where are you from?', "Where's he from?", "Where's she from?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi bạn đến từ đâu?',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['are', 'is', 'am', 'does.'], 'plain': True, 'q': 'Where __________ he from?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ["They're from Australia.", "I'm fine, thank you.", "He's from Vietnam.", "She's from America.", "It's my new friend."],
                                   'plain': True,
                                   'q': "Where's Mary from?",
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['too', 'friend', 'Bill', 'from', 'Australia'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: Where are you _____, Bill?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['years', "I'm", 'old.', 'eight']},
                                  {'id': 't1.11',
                                   'o': ["I'm fine, thank you.", "She's nine.", "I'm from Malaysia.", "She's from Thailand."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where’s she from?"',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['are', 'is', 'am', 'does'], 'plain': True, 'q': 'Where __________ Ben and Mary from?', 't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ["They're from Australia.", "I'm fine, thank you.", "He's from Vietnam.", "She's from America.", "It's my new friend."],
                                   'plain': True,
                                   'q': "Who's that?",
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['too', 'friend', 'Bill', 'from', 'Australia'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Bill: I'm from _____, And you?",
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['from', 'Peter', 'England.', 'is']},
                                  {'id': 't1.16',
                                   'o': ['Bạn đến từ Singapore.', 'Cô ấy đến từ Singapore.', 'Anh ấy đến từ Singapore.', 'Tôi đến từ Singapore.'],
                                   'plain': True,
                                   'q': 'Câu “He\'s from Singapore." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ['is', 'am', 'are', 'do'], 'plain': True, 'q': 'Where __________ Helena from?', 't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ["They're from Australia.", "I'm fine, thank you.", "He's from Vietnam.", "She's from America.", "It's my new friend."],
                                   'plain': True,
                                   'q': 'Where are Ben and Bill from?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['too', 'friend', 'Bill', 'from', 'Australia'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Bill: It's my _____, Lucy. She's from England.",
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'from?', 'Where', 'she']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 1 – My friends: Kiểm tra 1',
 'unit': 1}
