# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'q1.1': 'B',
 'q1.2': 'A',
 'q1.3': 'C',
 'q2.4': 'B',
 'q2.5': 'B',
 'q3.6': 'B',
 'q3.7': 'A',
 'q3.8': 'D',
 'q3.9': 'D',
 'q4.10': ['When’s your sports day?'],
 'q4.11': ['Where were you last summer?'],
 'q4.12': ['What’s your favourite subject?'],
 'q4.13': ['Where’s your school?'],
 'q4.14': ['Can Linh play badminton?'],
 'q4.15': ['What do you do on Thursdays?'],
 'q4.16': ['What time do you get up?'],
 'q4.17': ['Where are you from?'],
 'q4.18': ['What time do you have breakfast?'],
 'q4.19': ['Can he roller skate?'],
 'q5.20': 'C',
 'q5.21': 'A',
 'q5.22': 'D',
 'q5.23': 'A',
 'q5.24': 'B',
 'q5.25': 'D',
 'q5.26': 'B',
 'q6.27': 'F',
 'q6.28': 'F',
 'q6.29': 'T',
 'q6.30': 'T'}

EXPLANATIONS = {'q1.1': 'Đáp án: B. Tranh b',
 'q1.2': 'Đáp án: A. Tranh a',
 'q1.3': 'Đáp án: C. Tranh c',
 'q2.4': 'Đáp án: B. Tranh b',
 'q2.5': 'Đáp án: B. Tranh b',
 'q3.6': 'Đáp án: B. Tranh a',
 'q3.7': 'Đáp án: A. Tranh d',
 'q3.8': 'Đáp án: D. Tranh a',
 'q3.9': 'Đáp án: D. Tranh c',
 'q4.10': 'Câu đúng: When’s your sports day?',
 'q4.11': 'Câu đúng: Where were you last summer?',
 'q4.12': 'Câu đúng: What’s your favourite subject?',
 'q4.13': 'Câu đúng: Where’s your school?',
 'q4.14': 'Câu đúng: Can Linh play badminton?',
 'q4.15': 'Câu đúng: What do you do on Thursdays?',
 'q4.16': 'Câu đúng: What time do you get up?',
 'q4.17': 'Câu đúng: Where are you from?',
 'q4.18': 'Câu đúng: What time do you have breakfast?',
 'q4.19': 'Câu đúng: Can he roller skate?',
 'q5.20': 'Đáp án: C. When’s',
 'q5.21': 'Đáp án: A. last',
 'q5.22': 'Đáp án: D. favourite',
 'q5.23': "Đáp án: A. Yes, She can't.",
 'q5.24': 'Đáp án: B. on',
 'q5.25': 'Đáp án: D. time',
 'q5.26': 'Đáp án: B. have',
 'q6.27': 'Đáp án: False (theo đáp án của đề).',
 'q6.28': 'Đáp án: False (theo đáp án của đề).',
 'q6.29': 'Đáp án: True (theo đáp án của đề).',
 'q6.30': 'Đáp án: True (theo đáp án của đề).'}
