# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u5-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Can you fly a a kite?', 'Can you ride a bike?', 'Can you ride a horse?', 'Can you play a guitar?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn có thể đi xe đạp không?”',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['play', 'do', 'fly', 'ride'], 'plain': True, 'q': 'Can you ____________ a kite?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["No, she can't dance, but she can sing.",
                                         "No, she can't, but she can run.",
                                         'Yes, I can.',
                                         "No, I can't ride a horse, but I can ride a bike.",
                                         'Yes, he can.'],
                                   'plain': True,
                                   'q': 'Can you ride a horse?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. A: I can sing. What _____ you do, Hoa?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'piano?', 'play', 'he', 'Can']},
                                  {'id': 't1.6',
                                   'o': ['Bạn có thể chơi đàn ghi-ta không?',
                                         'Bạn có thể cưỡi ngựa không?',
                                         'Bạn có thể chơi đàn piano không?',
                                         'Bạn có thể đi xe đạp không?'],
                                   'plain': True,
                                   'q': 'Câu “Can you play the piano?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['am', 'do', 'can', "can't"], 'plain': True, 'q': 'A: Can you ride a bike?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ["No, she can't dance, but she can sing.",
                                         "No, she can't, but she can run.",
                                         'Yes, I can.',
                                         "No, I can't ride a horse, but I can ride a bike.",
                                         'Yes, he can.'],
                                   'plain': True,
                                   'q': 'Can you play the guitar?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 2. A: Can you _____ the piano, Minh?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['bike.', 'a', 'He', 'ride', 'can']},
                                  {'id': 't1.11',
                                   'o': ['Can you play the guitar?', 'How are you?', 'What can you do?', 'How old are you?'],
                                   'plain': True,
                                   'q': 'Để hỏi: “Bạn có thể làm gì?”, em nói:',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['am not', 'can', "can't", "don't"], 'plain': True, 'q': 'Can you play the piano?', 't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ["No, she can't dance, but she can sing.",
                                         "No, she can't, but she can run.",
                                         'Yes, I can.',
                                         "No, I can't ride a horse, but I can ride a bike.",
                                         'Yes, he can.'],
                                   'plain': True,
                                   'q': 'Can she dance?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 3. A: Can Mai _____ a horse?',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['kite?', 'fly', 'Can', 'a', 'she']},
                                  {'id': 't1.16',
                                   'o': ['Can she cook?', 'Can he swim?', 'Can he play badminton?', 'Can you draw?'],
                                   'plain': True,
                                   'q': 'Câu: “Yes, I can." có thể trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ['is', 'does', 'can', "can't"], 'plain': True, 'q': 'A: Can he dance?', 't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ["No, she can't dance, but she can sing.",
                                         "No, she can't, but she can run.",
                                         'Yes, I can.',
                                         "No, I can't ride a horse, but I can ride a bike.",
                                         'Yes, he can.'],
                                   'plain': True,
                                   'q': 'Can he roller skate?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['ride', 'can', 'No', "can't", 'do', 'play', 'but'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: No, she _____ ride a horse, (5) ____________ she can ride a bike.',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ["can't", 'the', 'guitar.', 'I', 'play']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 5 – Things we can do: Kiểm tra 1',
 'unit': 5}
