# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk2-de5',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'I. Listen to the sounds and circle the correct words. (nghe âm, chọn từ có âm đó).',
                        'items': [{'id': 'l1.1', 'o': ['farmer', 'actor', 'cinema'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['nurse', 'hair', 'floor'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['big', 'tree', 'bear'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['cinema', 'go', 'cook'], 'q': 'Nghe âm và chọn từ có âm đó.', 't': 'mcq'}]},
                       {'id': 'l2',
                        'instr': 'II. Listen and circle the correct pictures. (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.7',
                                   'o': ['In the morning', 'In the afternoon', 'In the evening'],
                                   'q': 'Nghe: Khi nào cô ấy chơi tennis? (When does she play tennis?)',
                                   't': 'mcq'},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'r1',
                        'instr': 'III. Circle the correct answers. (nhìn tranh, chọn câu đúng).',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['I clean the floor.', 'I wash the clothes.', 'I cook meals.'],
                                   'q': 'What do you do in the morning?',
                                   't': 'mcq'},
                                  {'id': 'r1.10',
                                   'img': 'r1_2.png',
                                   'o': ['She’s a policeman.', 'She’s a farmer.', 'She’s a nurse.'],
                                   'q': 'What does Linh do?',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['It’s a busy street.', 'It’s a quiet street.', 'It’s a noisy street.'],
                                   'q': 'What’s the street like?',
                                   't': 'mcq'},
                                  {'id': 'r1.12',
                                   'img': 'r1_4.png',
                                   'o': ['He goes to the swimming pool.', 'She goes to the sports centre.', 'He goes to the sports centre.'],
                                   'q': 'Where does Mr Long go on Sundays?',
                                   't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'IV. Fill in the blanks. (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'r2.13', 'img': 'r2_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.14', 'img': 'r2_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'img': 'r2_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'img': 'r2_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>This is my brother. His name is Nam. He’s an <b>(1) ______</b> He has short <b>(2) ______</b> On Saturday mornings, he '
                                   'often plays <b>(3) ______</b> Sometimes my brother and I go to the <b>(4) ______</b> We both can swim well. Then we go '
                                   'back home and help our mum with the cooking.</p>'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 2 – Đề 5',
 'unit': 'GiuaKy2'}
