# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['What time do you get up?'],
 't1.10': 'homework',
 't1.11': ['What time does she have breakfast?'],
 't1.12': 'What time do you have breakfast?',
 't1.13': 'do',
 't1.14': ['She has breakfast at seven fifteen.'],
 't1.15': 'What time does she go to bed?',
 't1.16': 'watch',
 't1.17': ['What time do Phong and Quan go to school?'],
 't1.18': 'I go to bed at ten fifteen.',
 't1.19': 'go',
 't1.2': 'What time do you get up?',
 't1.20': ["They have lunch at school at twelve o'clock."],
 't1.3': 'does',
 't1.4': "They go to school at seven o'clock.",
 't1.5': 'lunch',
 't1.6': ["I get up at six o'clock."],
 't1.7': 'Tôi thức dậy lúc sáu giờ mười lăm phút.',
 't1.8': 'goes',
 't1.9': 'He does his homework at seven forty-five.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: What time do you get up?',
 't1.10': 'Đáp án: homework',
 't1.11': 'Câu đúng: What time does she have breakfast?',
 't1.12': 'Đáp án: What time do you have breakfast?',
 't1.13': 'Đáp án: do',
 't1.14': 'Câu đúng: She has breakfast at seven fifteen.',
 't1.15': 'Đáp án: What time does she go to bed?',
 't1.16': 'Đáp án: watch',
 't1.17': 'Câu đúng: What time do Phong and Quan go to school?',
 't1.18': 'Đáp án: I go to bed at ten fifteen.',
 't1.19': 'Đáp án: go',
 't1.2': 'Đáp án: What time do you get up?',
 't1.20': "Câu đúng: They have lunch at school at twelve o'clock.",
 't1.3': 'Đáp án: does',
 't1.4': "Đáp án: They go to school at seven o'clock.",
 't1.5': 'Đáp án: lunch',
 't1.6': "Câu đúng: I get up at six o'clock.",
 't1.7': 'Đáp án: Tôi thức dậy lúc sáu giờ mười lăm phút.',
 't1.8': 'Đáp án: goes',
 't1.9': 'Đáp án: He does his homework at seven forty-five.'}
