# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['Mai goes to school from Monday to Friday.'],
 't1.10': 'tomorrow',
 't1.11': ['I play badminton with my friends.'],
 't1.12': 'What does she do on Saturdays?',
 't1.13': 'does',
 't1.14': 'play',
 't1.15': ['What does she do on Sundays?'],
 't1.16': 'Bạn làm gì vào thứ Năm?',
 't1.17': 'on',
 't1.18': 'help',
 't1.19': ['I watch TV on Sundays.'],
 't1.2': 'What do you do on Mondays?',
 't1.20': "It's Friday today.",
 't1.3': "seven o'clock",
 't1.4': 'Yes, she does.',
 't1.5': 'Saturday',
 't1.6': ['What do you do at the weekend?'],
 't1.7': 'What do you do at the weekend?',
 't1.8': 'I study at school.',
 't1.9': 'He plays football with his friends.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: Mai goes to school from Monday to Friday.',
 't1.10': 'Đáp án: tomorrow',
 't1.11': 'Câu đúng: I play badminton with my friends.',
 't1.12': 'Đáp án: What does she do on Saturdays?',
 't1.13': 'Đáp án: does',
 't1.14': 'Đáp án: play',
 't1.15': 'Câu đúng: What does she do on Sundays?',
 't1.16': 'Đáp án: Bạn làm gì vào thứ Năm?',
 't1.17': 'Đáp án: on',
 't1.18': 'Đáp án: help',
 't1.19': 'Câu đúng: I watch TV on Sundays.',
 't1.2': 'Đáp án: What do you do on Mondays?',
 't1.20': "Đáp án: It's Friday today.",
 't1.3': "Đáp án: seven o'clock",
 't1.4': 'Đáp án: Yes, she does.',
 't1.5': 'Đáp án: Saturday',
 't1.6': 'Câu đúng: What do you do at the weekend?',
 't1.7': 'Đáp án: What do you do at the weekend?',
 't1.8': 'Đáp án: I study at school.',
 't1.9': 'Đáp án: He plays football with his friends.'}
