# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on1-de8',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Listening – Part 1. Listen and tick (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l1.1',
                                   'img': 'l1_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.2',
                                   'img': 'l1_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.3',
                                   'img': 'l1_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l1.4',
                                   'img': 'l1_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'l2',
                        'instr': 'Listening – Part 2. Listen and number (nghe và đánh số; tranh B là ví dụ).',
                        'items': [{'id': 'l2.5', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh A là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.6', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh C là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.7', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh D là câu số mấy trong bài nghe?', 't': 'mcq'},
                                  {'id': 'l2.8', 'o': ['1', '2', '3', '4'], 'plain': True, 'q': 'Tranh E là câu số mấy trong bài nghe?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de8/l2.png" alt="Tranh">'},
                       {'id': 'l3',
                        'instr': 'Listening – Part 3. Listen and draw line (nghe và nối số thứ tự với tranh; câu 0 – tranh B là ví dụ).',
                        'items': [{'id': 'l3.9',
                                   'left': [{'t': 'Câu 1'}, {'t': 'Câu 2'}, {'t': 'Câu 3'}, {'t': 'Câu 4'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de8/l3.png" alt="Tranh">'},
                       {'id': 'l4',
                        'instr': 'Listening – Part 4. Listen and write (nghe và điền từ).',
                        'items': [{'id': 'l4.10', 'q': 'I {_} to be a painter.', 't': 'fill'},
                                  {'id': 'l4.11', 'q': 'Were you at the {_} yesterday?', 't': 'fill'},
                                  {'id': 'l4.12', 'q': 'My family have breakfast at {_} o’clock.', 't': 'fill'},
                                  {'id': 'l4.13', 'q': 'My new friend is from {_}.', 't': 'fill'}]},
                       {'id': 'r1',
                        'instr': 'Reading – Part 1. Read and match the words with pictures (nối từ với tranh; tranh B là ví dụ).',
                        'items': [{'id': 'r1.14',
                                   'left': [{'t': 'Maths teacher'}, {'t': 'ride a bike'}, {'t': 'on the beach'}, {'t': 'computer room'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de8/r1.png" alt="Tranh">'},
                       {'id': 'r2',
                        'instr': 'Reading – Part 2. Read and choose A, B or C to complete the text (đọc, chọn từ điền vào chỗ trống).',
                        'items': [{'id': 'r2.15', 'o': ['The', 'There', 'There’s'], 'q': 'Chọn từ điền vào chỗ trống (1).', 't': 'mcq'},
                                  {'id': 'r2.16', 'o': ['are', 'is', 'am'], 'q': 'Chọn từ điền vào chỗ trống (2).', 't': 'mcq'},
                                  {'id': 'r2.17', 'o': ['playing', 'playes', 'play'], 'q': 'Chọn từ điền vào chỗ trống (3).', 't': 'mcq'}],
                        'passage': '<p>My school is in the village. It has many trees. There is one playground. <b>(1) ______</b> is one computer room with '
                                   'many computers in it. And there <b>(2) ______</b> two gardens. At break time, I and my friends often <b>(3) ______</b> '
                                   'football and game in the playground. I love my school very much.</p>'},
                       {'id': 'r3',
                        'instr': 'Reading – Part 3. Read and tick True or False (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'r3.18', 'q': 'Today is Thursday.', 't': 'tf'},
                                  {'id': 'r3.19', 'q': 'Today, Linh is having Music class now.', 't': 'tf'},
                                  {'id': 'r3.20', 'q': 'Linh’s mother is Mrs Hoa. She’s an English teacher.', 't': 'tf'}],
                        'passage': '<p>Good afternoon! I’m Linh. I’m in Class 4C. This is my classroom. Today is Wednesday. We’re having an English class now. '
                                   'We always have English on Wednesdays and Fridays. Mrs Hoa, my mother, is our English teacher. I like English classes very '
                                   'much. I can speak English and sing many English songs, but I can’t play football.</p>'},
                       {'id': 'w1',
                        'instr': 'Writing – Part 1. Look at the pictures and the letters. Write the words (nhìn tranh, sắp xếp chữ cái thành từ).',
                        'items': [{'id': 'w1.21', 'img': 'w1_1.png', 'q': 'Sắp xếp các chữ cái: <b>retwa</b> → {_}', 't': 'fill'},
                                  {'id': 'w1.22', 'img': 'w1_2.png', 'q': 'Sắp xếp các chữ cái: <b>denrag</b> → {_}', 't': 'fill'},
                                  {'id': 'w1.23', 'img': 'w1_3.png', 'q': 'Sắp xếp các chữ cái: <b>nEshilg</b> → {_}', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Writing – Part 2. Rearrange the words to make the sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w2.24', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['subject?', 'your', 'What’s', 'favourite']},
                                  {'id': 'w2.25',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['school.', 'two', 'are', 'my', 'There', 'buildings', 'at']},
                                  {'id': 'w2.26', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'do', 'What', 'Tuesdays?', 'do', 'on']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK1 – Đề 8',
 'unit': 'OnHK1'}
