# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'C',
 'l1.2': 'A',
 'l1.3': 'C',
 'l1.4': 'A',
 'l2.5': 'C',
 'l2.6': 'A',
 'l2.7': 'B',
 'l2.8': 'C',
 'r1.10': 'C',
 'r1.11': 'C',
 'r1.12': 'A',
 'r1.9': 'A',
 'r2.13': ['roller skate'],
 'r2.14': ['play the guitar'],
 'r2.15': ['play the piano'],
 'r2.16': ['ride a bike']}

EXPLANATIONS = {'l1.1': 'Đáp án: C. juice',
 'l1.2': 'Đáp án: A. water',
 'l1.3': 'Đáp án: C. Malaysia',
 'l1.4': 'Đáp án: A. Sunday',
 'l2.5': 'Đáp án C (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l2.6': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l2.7': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l2.8': 'Đáp án C (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'r1.10': 'Đáp án: C. He’s from Viet Nam.',
 'r1.11': 'Đáp án: C. I want some grapes.',
 'r1.12': 'Đáp án: A. Yes, she can.',
 'r1.9': 'Đáp án: A. I go to school at seven fifteen.',
 'r2.13': 'Đáp án: roller skate',
 'r2.14': 'Đáp án: play the guitar',
 'r2.15': 'Đáp án: play the piano',
 'r2.16': 'Đáp án: ride a bike'}
