# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u2-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What time does she go to school?',
                                         'What time does she have breakfast?',
                                         'What time does she go to bed?',
                                         'What time does he have breakfast?'],
                                   'plain': True,
                                   'q': 'Câu: "She has breakfast at six fifteen.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['watch', 'watches', 'to watch', 'are watching'],
                                   'plain': True,
                                   'q': 'They ___________ TV at seven fifteen.',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Phong', 'school?', 'What', 'time', 'and', 'go', 'Quan', 'to', 'do']},
                                  {'id': 't1.4',
                                   'o': ['I get up at ten fifteen.',
                                         'I go to bed at ten fifteen.',
                                         'I go to school at ten fifteen.',
                                         'I chat with my friends at ten fifteen.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Tôi đi ngủ lúc mười giờ mười lăm phút.”',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['go', 'goes', 'to go', 'going'],
                                   'plain': True,
                                   'q': "Minh and Nam ___________ to school at seven o'clock.",
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['at', 'twelve', 'lunch', 'have', 'at', 'school', "o'clock.", 'They']},
                                  {'id': 't1.7',
                                   'o': ['What time is it?',
                                         'What time does she have breakfast?',
                                         'What time do you get up?',
                                         'What time do you have breakfast?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Bạn ăn sáng lúc mấy giờ”?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['have', 'has', 'to have', 'having'],
                                   'plain': True,
                                   'q': 'I ___________ dinner at home at seven thirty.',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['do', 'you', 'do', 'your', 'time', 'homework?', 'What']},
                                  {'id': 't1.10',
                                   'o': ['Cô ấy đi học lúc mấy giờ?', 'Cô ấy đi ngủ lúc mấy giờ', 'Cô ấy ăn sáng lúc mấy giờ?', 'Anh ấy đi học lúc mấy giờ?'],
                                   'plain': True,
                                   'q': 'Câu: “What time does she go to school? có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'o': ['have', 'has', 'to have', 'having'],
                                   'plain': True,
                                   'q': 'She ___________ breakfast at six thirty.',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['my', 'I', 'go', 'to', 'ten.', 'do', 'at', 'homework', 'and', 'bed']},
                                  {'id': 't1.13',
                                   'o': ["What's your name?", 'Where are you from?', 'What time is it?', 'How old are you?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi giờ?',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'o': ['in', 'on', 'at', 'to'], 'plain': True, 'q': 'A: What time do you get up?', 't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['She has dinner at seven thirty.',
                                         'He does his homework at seven forty-five.',
                                         "It's ten o'clock.",
                                         'I get up at six fifteen.',
                                         "They go to school at seven o'clock."],
                                   'plain': True,
                                   'q': 'What time is it?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['lunch', 'homework', 'What', 'at', 'have'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. Mai: _____ time do you get up, Lan?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Mai?', 'is', 'time', 'it,', 'What']},
                                  {'id': 't1.18',
                                   'o': ["Let's a break.", "It's three fifteen.", "I get up at six o'clock.", 'I go to school at 1:15 pm.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What time is it?"',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'What time ___________ she have breakfast?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['She has dinner at seven thirty.',
                                         'He does his homework at seven forty-five.',
                                         "It's ten o'clock.",
                                         'I get up at six fifteen.',
                                         "They go to school at seven o'clock."],
                                   'plain': True,
                                   'q': 'What time do you get up?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 2 – Time and daily routines: Kiểm tra 3',
 'unit': 2}
