# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u14-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'watches', 'TV', 'She', 'the', 'evening.']},
                                  {'id': 't1.2',
                                   'o': ['I wash the dishes in the evening.', 'I wash my clothes.', 'Yes, I do.', 'I help my mum with the cooking.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “When do you wash the dishes?”?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'What ______________ she do in the morning?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['She cleans the floor.',
                                         'I do the housework in the morning.',
                                         'I read books in the afternoon.',
                                         'She washes her clothes in the evening.',
                                         'I watch TV.'],
                                   'plain': True,
                                   'q': 'What does she do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: She _____ English.',
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['does', 'in', 'Nam', 'do', 'afternoon?', 'What', 'the']},
                                  {'id': 't1.7',
                                   'o': ['I watch TV in the evening.', 'I wash my clothes in the afternoon.', 'Yes, I do.', "No, they don't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Do you wash your clothes?”',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['watch', 'watches', 'to watch', 'watching'],
                                   'plain': True,
                                   'q': 'A: When does your brother watch TV?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['She cleans the floor.',
                                         'I do the housework in the morning.',
                                         'I read books in the afternoon.',
                                         'She washes her clothes in the evening.',
                                         'I watch TV.'],
                                   'plain': True,
                                   'q': 'What do you do in the afternoon?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: She _____ the floor in the morning and washes her clothes in the afternoon.',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['books', 'afternoon.', 'in', 'reads', 'the', 'Minh']},
                                  {'id': 't1.12',
                                   'o': ['What do you do in the evening?',
                                         'When do you help mother with the cooking?',
                                         'What do you do?',
                                         'What does your mother do in the evening?'],
                                   'plain': True,
                                   'q': 'Câu “I help my mother with the cooking" trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['clean', 'cleans', 'to clean', 'are clean'],
                                   'plain': True,
                                   'q': 'When do you ______________ the floor?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: She _____ her mother with the cooking and washes the dishes.',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['clothes?', 'he', 'his', 'When', 'wash', 'does']},
                                  {'id': 't1.16',
                                   'o': ['Tôi rửa chén dĩa.',
                                         'Tôi giúp nấu nướng.',
                                         'Tôi làm việc nhà cùng với bố mẹ tôi.',
                                         'Tôi làm bài tập về nhà với ba mẹ tôi.'],
                                   'plain': True,
                                   'q': 'Câu "I do the housework with my parents.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['help', 'is help', 'helps', 'to help'],
                                   'plain': True,
                                   'q': 'She ______________ her mum with the cooking in the evening.',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['in', 'He', 'the', 'clothes', 'washes', 'his', 'morning.']},
                                  {'id': 't1.19',
                                   'o': ['She washes the dishes in the evening.',
                                         'She washes her clothes in the evening.',
                                         'She cleans the floor in the afternoon.',
                                         'She watches TV in the evening.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là “Cô ấy giặt quần áo vào buổi tối.”',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['are', 'is', 'do', 'does'],
                                   'plain': True,
                                   'q': 'When ______________ you do your homework?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 14 – Daily activities: Kiểm tra 2',
 'unit': 14}
