# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u4-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Sinh nhật của tôi là vào tháng Năm.',
                                         'Sinh nhật của tôi là vào tháng Ba.',
                                         'Hôm nay là sinh nhật của tôi.',
                                         'Sinh nhật của tôi là vào tháng Bảy.'],
                                   'plain': True,
                                   'q': 'Câu “My birthday is in March.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['at', 'on', 'in', 'to'], 'plain': True, 'q': 'My birthday is _____________ November.', 't': 'mcq'},
                                  {'id': 't1.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'she', 'What', 'eat?', 'want', 'does']},
                                  {'id': 't1.4',
                                   'o': ['What do you do on Sundays, Mai?',
                                         'What do you want to drink, Mai?',
                                         'What do you want to eat, Mai?',
                                         'Where are you from, Mai?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn muốn uống gì vậy, Mai?”',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['play', 'do', 'eat', 'drink'],
                                   'plain': True,
                                   'q': 'A: What do you want to _____________, Quan?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['eat', 'wants', 'to', 'some', 'She', 'bread.']},
                                  {'id': 't1.7',
                                   'o': ['What do you do on Mondays, Nam?',
                                         'What do you want to eat, Nam?',
                                         'What do you want to drink, Nam?',
                                         'What time is it, Nam?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn muốn ăn gì vậy Nam?”',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['When', 'What', 'Where', 'How'],
                                   'plain': True,
                                   'q': "A: _____________'s your brother's birthday?",
                                   't': 'mcq'},
                                  {'id': 't1.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['want', 'to', 'she', 'does', 'drink?', 'What']},
                                  {'id': 't1.10',
                                   'o': ['Tôi muốn uống sữa.', 'Tôi muốn uống nước ép.', 'Tôi muốn ăn khoai tây chiên.', 'Tôi muốn ăn nhỏ.'],
                                   'plain': True,
                                   'q': 'Câu: “I want some grapes." có nghĩa là.',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'o': ['milk', 'meat', 'chicken', 'jam'],
                                   'plain': True,
                                   'q': 'A: What do you want to drink, Lan?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['She', 'some', 'milk.', 'and', 'wants', 'some', 'chips']},
                                  {'id': 't1.13',
                                   'o': ['What do you want to eat?', 'What day is it today?', "When's your birthday?", 'What do you want to drink?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Sinh nhật của bạn là khi nào?”?',
                                   't': 'mcq'},
                                  {'id': 't1.14', 'o': ['What', 'How', 'When', 'Where'], 'plain': True, 'q': 'A: _____________is your birthday?', 't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['I want some meat.',
                                         "It's Tuesday.",
                                         'I want some lemonade.',
                                         "I'm making a cake for my birthday party.",
                                         "It's in November."],
                                   'plain': True,
                                   'q': 'What day is it today?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['cake', 'When', 'eat', 'drink', 'November'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. A: _____ is your birthday, Tony?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Lucy?', 'you', 'are', 'doing,', 'What']},
                                  {'id': 't1.18',
                                   'o': ['What day is it today?', 'What do you do on Saturdays?', 'What do you want to eat?', "When's your birthday?"],
                                   'plain': True,
                                   'q': 'Câu “It\'s in July" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['play', 'do', 'drink', 'eat'],
                                   'plain': True,
                                   'q': 'A: What do you want to _____________, Quan?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['I want some meat.',
                                         "It's Tuesday.",
                                         'I want some lemonade.',
                                         "I'm making a cake for my birthday party.",
                                         "It's in November."],
                                   'plain': True,
                                   'q': "When's your birthday?",
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 4 – My birthday party: Kiểm tra 3',
 'unit': 4}
