# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['They are two hundred and forty thousand dong.'],
 't1.10': ['How much is that school bag?'],
 't1.11': 'They are two hundred thousand dong.',
 't1.12': 'near',
 't1.13': ['It is eighty thousand dong. GHI NHỚ'],
 't1.14': "Where's the bookshop?",
 't1.15': 'How much',
 't1.16': "It's ninety thousand dong.",
 't1.17': 'near',
 't1.18': ['Where is the pet shop?'],
 't1.19': 'How much is the skirt?',
 't1.2': 'Tiệm bánh mì ở giữa hiệu sách và cửa hàng thú cứng.',
 't1.20': "They're",
 't1.3': 'opposite',
 't1.4': ['How much is that shirt?'],
 't1.5': 'Trung tâm thể thao đối diện trung tâm mua sắm.',
 't1.6': 'are',
 't1.7': ['It is five hundred thousand dong.'],
 't1.8': 'How much is the shirt?',
 't1.9': 'over'}

EXPLANATIONS = {'t1.1': 'Câu đúng: They are two hundred and forty thousand dong.',
 't1.10': 'Câu đúng: How much is that school bag?',
 't1.11': 'Đáp án: They are two hundred thousand dong.',
 't1.12': 'Đáp án: near',
 't1.13': 'Câu đúng: It is eighty thousand dong. GHI NHỚ',
 't1.14': "Đáp án: Where's the bookshop?",
 't1.15': 'Đáp án: How much',
 't1.16': "Đáp án: It's ninety thousand dong.",
 't1.17': 'Đáp án: near',
 't1.18': 'Câu đúng: Where is the pet shop?',
 't1.19': 'Đáp án: How much is the skirt?',
 't1.2': 'Đáp án: Tiệm bánh mì ở giữa hiệu sách và cửa hàng thú cứng.',
 't1.20': "Đáp án: They're",
 't1.3': 'Đáp án: opposite',
 't1.4': 'Câu đúng: How much is that shirt?',
 't1.5': 'Đáp án: Trung tâm thể thao đối diện trung tâm mua sắm.',
 't1.6': 'Đáp án: are',
 't1.7': 'Câu đúng: It is five hundred thousand dong.',
 't1.8': 'Đáp án: How much is the shirt?',
 't1.9': 'Đáp án: over'}
