# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u2-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["What's your name?", 'Where are you from?', 'What time is it?', 'How old are you?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi giờ?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['in', 'on', 'at', 'to'], 'plain': True, 'q': 'A: What time do you get up?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['She has dinner at seven thirty.',
                                         'He does his homework at seven forty-five.',
                                         "It's ten o'clock.",
                                         'I get up at six fifteen.',
                                         "They go to school at seven o'clock."],
                                   'plain': True,
                                   'q': 'What time is it?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['lunch', 'homework', 'What', 'at', 'have'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. Mai: _____ time do you get up, Lan?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['it,', 'Mai?', 'is', 'time', 'What']},
                                  {'id': 't1.6',
                                   'o': ["Let's a break.", "It's three fifteen.", "I get up at six o'clock.", 'I go to school at 1:15 pm.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What time is it?"',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'What time ___________ she have breakfast?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['She has dinner at seven thirty.',
                                         'He does his homework at seven forty-five.',
                                         "It's ten o'clock.",
                                         'I get up at six fifteen.',
                                         "They go to school at seven o'clock."],
                                   'plain': True,
                                   'q': 'What time do you get up?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['lunch', 'homework', 'What', 'at', 'have'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 2. Mary: What time do you _____ breakfast?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['seven', 'It', 'thirty.', 'is']},
                                  {'id': 't1.11',
                                   'o': ['What time do you get up?', "Who's that?", 'What time is it?', 'What time do you have breakfast?'],
                                   'plain': True,
                                   'q': 'Câu “It\'s one fifteen." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['time', 'old', 'name', 'from'], 'plain': True, 'q': 'A: What ___________ is it?', 't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['She has dinner at seven thirty.',
                                         'He does his homework at seven forty-five.',
                                         "It's ten o'clock.",
                                         'I get up at six fifteen.',
                                         "They go to school at seven o'clock."],
                                   'plain': True,
                                   'q': 'What time does she have dinner?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['lunch', 'homework', 'What', 'at', 'have'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: I go to school _____ seven thirty.',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['up?', 'do', 'get', 'What', 'you', 'time']},
                                  {'id': 't1.16',
                                   'o': ['How old are you?', 'What time is it?', 'What time do you get up?', 'Where is she from?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về thói quen hằng ngày?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'What time ___________ he go to bed?', 't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['She has dinner at seven thirty.',
                                         'He does his homework at seven forty-five.',
                                         "It's ten o'clock.",
                                         'I get up at six fifteen.',
                                         "They go to school at seven o'clock."],
                                   'plain': True,
                                   'q': 'What time do Bill and Ben go to school?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['lunch', 'homework', 'What', 'at', 'have'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: She has _____ at eleven thirty.',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ["o'clock.", 'at', 'six', 'get', 'I', 'up']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 2 – Time and daily routines: Kiểm tra 1',
 'unit': 2}
