# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk1-nghe1',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'q1',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q1.1', 'o': ['swim', 'dance', 'cook'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q1.2', 'o': ['swim', 'dance', 'cook'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q1.3', 'o': ['swim', 'dance', 'cook'], 'q': 'Nghe câu số 3.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_nghe1/p1.png" alt="Hình">'},
                       {'id': 'q2',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q2.4', 'o': ['Friday', 'Thursday', 'Saturday'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q2.5', 'o': ['Friday', 'Thursday', 'Saturday'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q2.6', 'o': ['Friday', 'Thursday', 'Saturday'], 'q': 'Nghe câu số 3.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_nghe1/p2.png" alt="Hình">'},
                       {'id': 'q3',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q3.7', 'o': ['February', 'March', 'January'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q3.8', 'o': ['February', 'March', 'January'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q3.9', 'o': ['February', 'March', 'January'], 'q': 'Nghe câu số 3.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_nghe1/p3.png" alt="Hình">'},
                       {'id': 'q4',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q4.10', 'o': ["It's twelve twenty-five", "It's twelve forty-five"], 'q': 'What time is it?', 't': 'mcq'},
                                  {'id': 'q4.11', 'o': ["It's Saturday.", "It's Sunday."], 'q': 'What day is it today?', 't': 'mcq'},
                                  {'id': 'q4.12', 'o': ["It's Thursday.", "It's Wednesday."], 'q': 'What day is it today?', 't': 'mcq'}]},
                       {'id': 'q5',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q5.13',
                                   'o': ["No, she can't. But she can play the guitar.",
                                         "No, she can't. But she can draw.",
                                         "No, she can't. But she can play the piano."],
                                   'q': 'Can your sister dance?',
                                   't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_nghe1/p5.png" alt="Hình">'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 1 – Luyện nghe phần 1',
 'unit': 'GiuaKy1'}
