# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u16-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['She is tall and slim.', 'It was sunny.', "Let's go to the bakery.", "Sorry, I can't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What was the weather like in Da Nang yesterday?"',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['sunny', 'rainy', 'cloudy', 'windy.'],
                                   'plain': True,
                                   'q': "It's _________________. Let's go to the beach.",
                                   't': 'mcq'},
                                  {'id': 't1.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['some', 'to', 'We', 'food.', 'buy', 'want']},
                                  {'id': 't1.4',
                                   'o': ['What was the weather like in Sa Pa?',
                                         'What was the weather like in Sa Pa last weekend?',
                                         'Do you want to go to Sa Pa?',
                                         'It was sunny in Sa Pa.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Cuối tuần rồi thời tiết ở Sa Pa như thế nào?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ['is', 'are', 'was', 'were'], 'plain': True, 'q': 'Where ____________ you yesterday?', 't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['buy', 'wants', 'to', 'some', 'Mai', 'books.']},
                                  {'id': 't1.7',
                                   'o': ['Chúng ta hãy đi đến tiệm bánh mì nhé.',
                                         'Chúng ta hãy đi đến trung tâm thể thao nhé.',
                                         'Chúng ta hãy đi đến trung tâm mua sắm nhé.',
                                         'Chúng ta hãy đi nhà sách nhé.'],
                                   'plain': True,
                                   'q': 'Câu “Let\'s go to the shopping centre." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['is', 'are', 'was', 'were'], 'plain': True, 'q': 'I. _____________ in Hanoi last Saturday.', 't': 'mcq'},
                                  {'id': 't1.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'shopping', 'at', 'is', 'centre.', 'Nam']},
                                  {'id': 't1.10',
                                   'o': ['Đó là một ngày nắng.', 'Đó là một ngày u ám.', 'Đó là một ngày mưa.', 'Đó là một ngày đẹp.'],
                                   'plain': True,
                                   'q': 'Câu “It was a rainy day." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'o': ['is', 'are', 'was', 'were'],
                                   'plain': True,
                                   'q': 'I was in Hue last weekend. It _____________ rainy.',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['me?', 'Do', 'you', 'to', 'with', 'park', 'the', 'want', 'to', 'go', 'water']},
                                  {'id': 't1.13',
                                   'o': ['I like windy days.', 'It was sunny.', "Let's go to the water park.", "I'm doing my homework."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây đề nghị hoặc rủ ai đó đi đâu cùng với mình?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['is', 'are', 'was', 'were'],
                                   'plain': True,
                                   'q': 'What ____________ the weather like last Sunday?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['It was sunny.', 'It is cloudy.', 'I was in Da Nang.', 'I want to buy some books.', "Great! Let's go."],
                                   'plain': True,
                                   'q': 'Where were you last Saturday?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['Where', 'What', 'When', 'How'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. A: _____ were you last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['weekend?', 'you', 'were', 'last', 'Where']},
                                  {'id': 't1.18',
                                   'o': ['Do you want to go to the bookshop?',
                                         'What was the weather like last Sunday?',
                                         'What does she look like?',
                                         'Where do you go on Sundays?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về thời tiết trong quá khứ?',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'o': ['is', 'are', 'was', 'were'], 'plain': True, 'q': 'It ______________ rainy yesterday.', 't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['It was sunny.', 'It is cloudy.', 'I was in Da Nang.', 'I want to buy some books.', "Great! Let's go."],
                                   'plain': True,
                                   'q': 'What was the weather like last Saturday?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 16 – Weather: Kiểm tra 3',
 'unit': 16}
