# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck2-de4',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'gi',
                        'instr': 'I. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'gi.1', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.2', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.3', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.4', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck2_de4/gi.png" alt="Tranh a–d">'},
                       {'id': 'gii',
                        'instr': 'II. Listen and draw lines (nghe và nối nhân vật với tranh).',
                        'items': [{'id': 'gii.5',
                                   'left': [{'img': 'gii_l1.png', 't': ''},
                                            {'img': 'gii_l2.png', 't': ''},
                                            {'img': 'gii_l3.png', 't': ''},
                                            {'img': 'gii_l4.png', 't': ''}],
                                   'o': ['a', 'b', 'c', 'd'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck2_de4/gii.png" alt="Tranh a–d">'},
                       {'id': 'giii',
                        'instr': 'III. Listen and complete (nghe và điền từ).',
                        'items': [{'id': 'giii.6', 'q': 'What does it say? – It says ‘{_}’.', 't': 'fill'},
                                  {'id': 'giii.7', 'q': 'What is Ben doing? – He’s {_}.', 't': 'fill'},
                                  {'id': 'giii.8', 'q': 'How much is the {_}? – It’s 200,000 dong.', 't': 'fill'},
                                  {'id': 'giii.9', 'q': 'What was the weather like last weekend? – It was {_}.', 't': 'fill'}]},
                       {'id': 'giv',
                        'instr': 'IV. Read and choose A, B or C (nhìn tranh, chọn đáp án đúng).',
                        'items': [{'id': 'giv.10',
                                   'img': 'giv_1.png',
                                   'o': ['Yes, I can’t.', 'Sorry, I can’t.', 'Great, I can’t.'],
                                   'q': 'Do you want to go to the gift shop?',
                                   't': 'mcq'},
                                  {'id': 'giv.11',
                                   'img': 'giv_2.png',
                                   'o': ['They’re building a campfire.', 'They’re dancing around a campfire.', 'They’re putting up a tent.'],
                                   'q': 'What are they doing?',
                                   't': 'mcq'},
                                  {'id': 'giv.12',
                                   'img': 'giv_3.png',
                                   'o': ['They’re crocodiles.', 'They’re birds.', 'It is a crocodile.'],
                                   'q': 'What are these animals?',
                                   't': 'mcq'},
                                  {'id': 'giv.13',
                                   'img': 'giv_4.png',
                                   'o': ['It says sunny.', 'It is sunny.', 'It was sunny.'],
                                   'q': 'What was the weather like last Sunday?',
                                   't': 'mcq'}]},
                       {'id': 'gv',
                        'instr': 'V. Write suitable questions for the answers given (nhìn tranh, viết câu hỏi phù hợp).',
                        'items': [{'id': 'gv.14',
                                   'img': 'gv_1.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>It was cloudy and rainy yesterday.</i><br>{_}',
                                   't': 'fill'},
                                  {'id': 'gv.15', 'img': 'gv_2.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>It’s 70,000 dong.</i><br>{_}', 't': 'fill'},
                                  {'id': 'gv.16',
                                   'img': 'gv_3.png',
                                   'q': 'Viết câu hỏi cho câu trả lời: <i>Because they roar loudly.</i><br>{_}',
                                   't': 'fill'}]},
                       {'id': 'gvi',
                        'instr': 'VI. Read and write T (True) or F (False) (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'gvi.17', 'q': 'Tim and his family are on a camping trip.', 't': 'tf'},
                                  {'id': 'gvi.18', 'q': 'The weather is sunny and cloudy.', 't': 'tf'},
                                  {'id': 'gvi.19', 'q': 'They build a campfire and sing loudly.', 't': 'tf'}],
                        'passage': '<p>Tim and his family are on a camping trip. The weather is sunny and windy. They camp near a lake. They put up a big '
                                   'tent. Tim helps to clean up. There is chicken and corn for lunch. When it gets dark, they start to build a campfire. They '
                                   'tell stories and dance around the campfire.</p>'},
                       {'id': 'gvii',
                        'instr': 'VII. Fill in the blanks (điền từ vào chỗ trống, nhìn tranh).',
                        'items': [{'id': 'gvii.20', 'img': 'gvii_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'gvii.21', 'img': 'gvii_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'gvii.22', 'img': 'gvii_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'gvii.23', 'img': 'gvii_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Today is my sister’s birthday. I go to a <b>(1) ______</b> to buy her a present. It’s next to the <b>(2) ______</b> I '
                                   'choose a pink <b>(3) ______</b> for her. It looks beautiful. Then I go to the <b>(4) ______</b> to buy a birthday cake. '
                                   'When I give her the present, she is very happy. She smiles and says “Thank you!”.</p>'},
                       {'bank': ['taking a photo', 'turn right', 'sunny', 'great'],
                        'id': 'gviii',
                        'instr': 'VIII. Write suitable answers to the questions using given words (dùng từ cho sẵn để trả lời).',
                        'items': [{'id': 'gviii.24', 'q': 'Do you want to go to the water park?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.25', 'q': 'What is Lucy doing?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.26', 'q': 'What does it say?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.27', 'q': 'What was the weather like last Saturday?<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 2 – Đề 4',
 'unit': 'CuoiKy2'}
