# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'B',
 'l1.2': 'C',
 'l1.3': 'A',
 'l1.4': 'B',
 'l2.5': '2',
 'l2.6': '4',
 'l2.7': '3',
 'l2.8': '1',
 'l3.10': '3',
 'l3.11': '2',
 'l3.12': '1',
 'l3.9': '4',
 'l4.13': ['jam'],
 'l4.14': ['Australia'],
 'l4.15': ['Friday'],
 'l4.16': ['Maths', 'Math'],
 'r1.17': {'blanks': [['D'], ['E'], ['A'], ['C']]},
 'r2.18': 'A',
 'r2.19': 'B',
 'r2.20': 'C',
 'r3.21': 'T',
 'r3.22': 'T',
 'r3.23': 'F',
 'w1.24': ['Britain'],
 'w1.25': ['lemonade'],
 'w1.26': ['art'],
 'w2.27': ['I get up at five thirty.'],
 'w2.28': ['What’s your favourite subject?'],
 'w2.29': ['I do housework on Sunday.']}

EXPLANATIONS = {'l1.1': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.2': 'Đáp án C (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.3': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.4': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l2.5': 'Tranh A ứng với câu 2 (theo đáp án của đề).',
 'l2.6': 'Tranh C ứng với câu 4 (theo đáp án của đề).',
 'l2.7': 'Tranh D ứng với câu 3 (theo đáp án của đề).',
 'l2.8': 'Tranh E ứng với câu 1 (theo đáp án của đề).',
 'l3.10': 'Tranh C ứng với câu 3 (theo đáp án của đề).',
 'l3.11': 'Tranh D ứng với câu 2 (theo đáp án của đề).',
 'l3.12': 'Tranh E ứng với câu 1 (theo đáp án của đề).',
 'l3.9': 'Tranh A ứng với câu 4 (theo đáp án của đề).',
 'l4.13': 'Đáp án: jam',
 'l4.14': 'Đáp án: Australia',
 'l4.15': 'Đáp án: Friday',
 'l4.16': 'Đáp án: Maths',
 'r1.17': 'Đáp án theo đáp án của đề: go to bed–D, water–E, nine forty-five–A, birthday party–C',
 'r2.18': 'Đáp án: A. swimming',
 'r2.19': 'Đáp án: B. and',
 'r2.20': 'Đáp án: C. cinema',
 'r3.21': 'Đáp án: True (theo đáp án của đề).',
 'r3.22': 'Đáp án: True (theo đáp án của đề).',
 'r3.23': 'Đáp án: False (theo đáp án của đề).',
 'w1.24': 'Từ đúng: Britain',
 'w1.25': 'Từ đúng: lemonade',
 'w1.26': 'Từ đúng: art',
 'w2.27': 'Câu đúng: I get up at five thirty.',
 'w2.28': 'Câu đúng: What’s your favourite subject?',
 'w2.29': 'Câu đúng: I do housework on Sunday.'}
