# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a1.1': 'B',
 'a1.2': 'A',
 'a1.3': 'A',
 'a1.4': 'B',
 'a2.5': 'C',
 'a2.6': 'D',
 'a2.7': 'B',
 'a2.8': 'A',
 'a3.10': 'F',
 'a3.9': 'T',
 'a4.11': ['study at school'],
 'a4.12': ['town'],
 'b1.13': 'B',
 'b1.14': 'A',
 'b1.15': 'A',
 'b1.16': 'B',
 'b1.17': 'A',
 'b2.18': ['nine', '9'],
 'b2.19': ['town'],
 'b2.20': ['buildings'],
 'b2.21': ['garden'],
 'b2.22': ['playground'],
 'c1.23': ['roller skate'],
 'c1.24': ['music'],
 'c1.25': ['campsite'],
 'c1.26': ['study at school'],
 'c1.27': ['lemonade'],
 'c2.28': ['What do you want to eat?'],
 'c2.29': ['It is Saturday today.'],
 'c2.30': ['I go to school at 6.45.'],
 'c2.31': ['She can play the piano.'],
 'c2.32': ['I was in Da Nang last summer.']}

EXPLANATIONS = {'a1.1': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.2': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.3': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.4': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a2.5': 'Câu 1 ứng với tranh C (theo đáp án của đề).',
 'a2.6': 'Câu 2 ứng với tranh D (theo đáp án của đề).',
 'a2.7': 'Câu 3 ứng với tranh B (theo đáp án của đề).',
 'a2.8': 'Câu 4 ứng với tranh A (theo đáp án của đề).',
 'a3.10': 'Đáp án: False (theo đáp án của đề: ✗).',
 'a3.9': 'Đáp án: True (theo đáp án của đề: ✓).',
 'a4.11': 'Đáp án: study at school',
 'a4.12': 'Đáp án: town',
 'b1.13': 'Đáp án: B. I like art because I want to be an art teacher.',
 'b1.14': 'Đáp án: A. I have breakfast at six thirty.',
 'b1.15': 'Đáp án: A. I want some chips.',
 'b1.16': 'Đáp án: B. I do housework.',
 'b1.17': 'Đáp án: A. It’s in August.',
 'b2.18': 'Đáp án: nine',
 'b2.19': 'Đáp án: town',
 'b2.20': 'Đáp án: buildings',
 'b2.21': 'Đáp án: garden',
 'b2.22': 'Đáp án: playground',
 'c1.23': 'Đáp án: roller skate',
 'c1.24': 'Đáp án: music',
 'c1.25': 'Đáp án: campsite',
 'c1.26': 'Đáp án: study at school',
 'c1.27': 'Đáp án: lemonade',
 'c2.28': 'Câu đúng: What do you want to eat?',
 'c2.29': 'Câu đúng: It is Saturday today.',
 'c2.30': 'Câu đúng: I go to school at 6.45.',
 'c2.31': 'Câu đúng: She can play the piano.',
 'c2.32': 'Câu đúng: I was in Da Nang last summer.'}
