# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'What is he doing?',
 't1.10': ['What are Nam and Minh doing, Lan?'],
 't1.11': 'What are they doing?',
 't1.12': 'are',
 't1.13': "He's at school.",
 't1.14': 'are',
 't1.15': ['They are putting up a tent.'],
 't1.16': "What's Mai doing?",
 't1.17': 'they are',
 't1.18': 'She is studing English.',
 't1.19': 'playing',
 't1.2': 'is',
 't1.20': ['What is Mark doing, Mai?'],
 't1.3': 'They are at the campsite.',
 't1.4': 'Are',
 't1.5': ['Where are Bill and his friends?'],
 't1.6': "Where's Nam?",
 't1.7': 'What',
 't1.8': 'They are playing tug of war.',
 't1.9': 'they'}

EXPLANATIONS = {'t1.1': 'Đáp án: What is he doing?',
 't1.10': 'Câu đúng: What are Nam and Minh doing, Lan?',
 't1.11': 'Đáp án: What are they doing?',
 't1.12': 'Đáp án: are',
 't1.13': "Đáp án: He's at school.",
 't1.14': 'Đáp án: are',
 't1.15': 'Câu đúng: They are putting up a tent.',
 't1.16': "Đáp án: What's Mai doing?",
 't1.17': 'Đáp án: they are',
 't1.18': 'Đáp án: She is studing English.',
 't1.19': 'Đáp án: playing',
 't1.2': 'Đáp án: is',
 't1.20': 'Câu đúng: What is Mark doing, Mai?',
 't1.3': 'Đáp án: They are at the campsite.',
 't1.4': 'Đáp án: Are',
 't1.5': 'Câu đúng: Where are Bill and his friends?',
 't1.6': "Đáp án: Where's Nam?",
 't1.7': 'Đáp án: What',
 't1.8': 'Đáp án: They are playing tug of war.',
 't1.9': 'Đáp án: they'}
