# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u16-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['I like windy days.', 'It was sunny.', "Let's go to the water park.", "I'm doing my homework."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây đề nghị hoặc rủ ai đó đi đâu cùng với mình?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['Do you want to go to the bookshop?',
                                         'What was the weather like last Sunday?',
                                         'What does she look like?',
                                         'Where do you go on Sundays?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về thời tiết trong quá khứ?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Where do you go on Saturdays?',
                                         'Do you want to go to the shopping centre?',
                                         "Let's go.",
                                         'What do you do on Mondays?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi bạn có muốn đi đâu đó không?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ["She's beautiful.", 'He has a round face.', 'It was rainy.', "Let's go to the food stall."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What was the weather like yesterday?”',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['What was the weather lile last weekend?',
                                         'What does he look like?',
                                         'Do you want to go to the bakery?',
                                         'Where do you go on Sundays?'],
                                   'plain': True,
                                   'q': 'Câu “Great! Let\'s go." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ["Sorry, I can't. I'm doing my homework.", 'It was cloudy.', "I don't like rainy weather.", "It's sunny today."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi “Do you want to go to the bookshop with me?"',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['She is tall and slim.', 'It was sunny.', "Let's go to the bakery.", "Sorry, I can't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What was the weather like in Da Nang yesterday?"',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['What was the weather like in Sa Pa?',
                                         'What was the weather like in Sa Pa last weekend?',
                                         'Do you want to go to Sa Pa?',
                                         'It was sunny in Sa Pa.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Cuối tuần rồi thời tiết ở Sa Pa như thế nào?',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['Chúng ta hãy đi đến tiệm bánh mì nhé.',
                                         'Chúng ta hãy đi đến trung tâm thể thao nhé.',
                                         'Chúng ta hãy đi đến trung tâm mua sắm nhé.',
                                         'Chúng ta hãy đi nhà sách nhé.'],
                                   'plain': True,
                                   'q': 'Câu “Let\'s go to the shopping centre." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Đó là một ngày nắng.', 'Đó là một ngày u ám.', 'Đó là một ngày mưa.', 'Đó là một ngày đẹp.'],
                                   'plain': True,
                                   'q': 'Câu “It was a rainy day." có nghĩa là:',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1',
                                   'o': ['is', 'are', 'was', 'were'],
                                   'plain': True,
                                   'q': 'What ____________ the weather like last Sunday?',
                                   't': 'mcq'},
                                  {'id': 'b.2', 'o': ['is', 'are', 'was', 'were'], 'plain': True, 'q': 'It ______________ rainy yesterday.', 't': 'mcq'},
                                  {'id': 'b.3',
                                   'o': ['Was', 'Were', 'Do', 'Does'],
                                   'plain': True,
                                   'q': '_____________ you want to go to the water park with me?',
                                   't': 'mcq'},
                                  {'id': 'b.4',
                                   'o': ['day', 'weather', 'homework', 'weekend'],
                                   'plain': True,
                                   'q': "A: What's the __________ like yesterday?",
                                   't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['bakery', 'bookshop', 'wate park', 'swimming pool'],
                                   'plain': True,
                                   'q': "Let's go to the ___________. I want to buy some bread.",
                                   't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['bakery', 'bookshop', 'food stall', 'water park'],
                                   'plain': True,
                                   'q': 'Do you want to go to the ___________ with me? I want to buy some books.',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['sunny', 'rainy', 'cloudy', 'windy.'],
                                   'plain': True,
                                   'q': "It's _________________. Let's go to the beach.",
                                   't': 'mcq'},
                                  {'id': 'b.8', 'o': ['is', 'are', 'was', 'were'], 'plain': True, 'q': 'Where ____________ you yesterday?', 't': 'mcq'},
                                  {'id': 'b.9', 'o': ['is', 'are', 'was', 'were'], 'plain': True, 'q': 'I. _____________ in Hanoi last Saturday.', 't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['is', 'are', 'was', 'were'],
                                   'plain': True,
                                   'q': 'I was in Hue last weekend. It _____________ rainy.',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['Where were you last Saturday?',
                                            'What was the weather like last Saturday?',
                                            'Do you want to go to the bookshop?',
                                            'What do you want to buy?',
                                            'What is the weather like today?'],
                                   'o': ['It was sunny.', 'It is cloudy.', 'I was in Da Nang.', 'I want to buy some books.', "Great! Let's go."],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['Where', 'What', 'When', 'How'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2',
                                   'o': ['water park', 'bookshop', 'food stall', 'sports centre'],
                                   'plain': True,
                                   'q': 'Chỗ trống (2):',
                                   't': 'mcq'},
                                  {'id': 'd.3', 'o': ['bookshop', 'water park', 'bakery', 'food stall'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['is', 'are', 'was', 'were'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['am', 'do', "can't", 'am not'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': '1. A: <b>(1)&nbsp;______</b> were you last weekend?<br>B: I was in Hue.<br>2. A: Do you want to go to the '
                                   '<b>(2)&nbsp;______</b>?<br>B: Yes, I want to buy some food.<br>3. A: I want to buy some books. Do you want to go to the '
                                   "<b>(3)&nbsp;______</b> with me?<br>B: Great! Let's go.<br>4. A: What was the weather like in Hue yesterday?<br>B: It "
                                   "<b>(4)&nbsp;______</b> rainy.<br>5. A: Do you want to go to the cinema with me?<br>B: Sorry, I <b>(5)&nbsp;______</b>. I'm "
                                   'doing my housework.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and choose the correct answers. (Đọc và chọn đáp án đúng.)',
                        'items': [{'id': 'e.1', 'o': ['cloudy', 'sunny', 'rainy', 'windy'], 'plain': True, 'q': 'It was. last Sunday.', 't': 'mcq'},
                                  {'id': 'e.2', 'o': ['sunny', 'rainy', 'cloudy', 'windy'], 'plain': True, 'q': 'It is _____________ today.', 't': 'mcq'},
                                  {'id': 'e.3',
                                   'o': ['bakery', 'water park', 'food stall', 'bookshop'],
                                   'plain': True,
                                   'q': 'Lan is at the ___________.',
                                   't': 'mcq'},
                                  {'id': 'e.4',
                                   'o': ['bakery', 'water park', 'food stall', 'bookshop'],
                                   'plain': True,
                                   'q': 'Mai is at the __________.',
                                   't': 'mcq'},
                                  {'id': 'e.5',
                                   'o': ['some notebooks', 'some bread', 'some sausages', 'some meat'],
                                   'plain': True,
                                   'q': 'Nam wants to buy ______________.',
                                   't': 'mcq'},
                                  {'id': 'e.6',
                                   'o': ['some notebooks', 'some bread', 'some sausages', 'some meat'],
                                   'plain': True,
                                   'q': 'Mai wants to buy.',
                                   't': 'mcq'},
                                  {'id': 'e.7',
                                   'o': ['some notebooks', 'some bread', 'some popcorn', 'some meat'],
                                   'plain': True,
                                   'q': 'Lan wants to buy _____________.',
                                   't': 'mcq'}],
                        'passage': 'Hi, my name is Lan. I usually go out with my frierds Mai and Nam every Sunday. Last Sunday, it was rainy, so we were at '
                                   'home. It is sunny today. We are at the supermarket. Mai is at the bakery. She wants to buy some bread. Nam is at the food '
                                   "stall. He wants to buy some sausages. I'm at the bookshop. I want to buy some notebooks."}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['weekend?', 'Where', 'were', 'last', 'you']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['in', 'I', 'weekend.', 'was', 'Hue', 'last']},
                                  {'id': 'f.3',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['like', 'What', 'weather', 'in', 'Long', 'yesterday?', 'An', 'was', 'the']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['rainy', 'It', 'and', 'yesterday.', 'was', 'cold']},
                                  {'id': 'f.5',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'in', 'What', 'is', 'Nang', 'Da', 'today?', 'weather', 'like']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sunny', 'today.', 'is', 'It']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'food.', 'buy', 'want', 'We', 'some']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'Mai', 'buy', 'books.', 'some', 'wants']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['shopping', 'centre.', 'is', 'the', 'at', 'Nam']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['to', 'want', 'with', 'water', 'to', 'the', 'go', 'park', 'me?', 'Do', 'you']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi về thời tiết trong quá khứ và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           'lời</td></tr><tr><td>What was the weather like... (place)... (time in the past)?<br>Thời tiết.. như thế nào?</td><td>It '
           'was...<br>Trời...</td></tr><tr><td>Ví dụ:<br>A: What was the weather like in Hue yesterday?<br>Thời tiết ở Huế hôm qua như thế nào?<br>B: It was '
           'rainy.<br>Trời có mưa.</td></tr></table><p>2. Cách đưa ra lời đề nghị hoặc rủ ai đó đi đâu cùng với mình và cách trả lời:</p><table '
           'class="tb"><tr><td>Cách đưa ra lời đề nghị</td><td>Cách trả lời</td></tr><tr><td>Do you want to go to.... with me?<br>Bạn có muốn đi đến... cùng '
           "với tôi không?</td><td>-Great! Let's go.<br>Được! Chúng ta cùng đi nào.<br>- Sorry, I can't.<br>Xin lỗi, mình không thể đi "
           'được.</td></tr><tr><td>Ví dụ:<br>A: Do you want to go to the water park with me?<br>Bạn có muốn đi đến công viên nước cùng với mình không?<br>B: '
           "Great! Let's go.<br>Được! Chúng ta đi nào.</td></tr></table><p>3. Cách hỏi về thời tiết ngày hôm nay và cách trả lời:</p><table "
           'class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>What is the weather like today?<br>Thời tiết hôm nay thế nào?</td><td>It is... '
           '(rainy/windy/sunny/cloudy).<br>Trời... (có mưa/lộng gió/ nắng/nhiều mây)</td></tr><tr><td>Ví dụ:<br>A: What is the weather like today?<br>Thời '
           'tiết hôm nay như thế nào?<br>B: It is sunny.<br>Trời nắng.</td></tr></table>',
 'title': 'Unit 16 – Weather: Luyện tập',
 'unit': 16}
