# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ["She's an office worker."],
 't1.10': 'hospital',
 't1.11': ['She works at a factory.'],
 't1.12': 'Cô ấy làm việc ở viện dưỡng lão.',
 't1.13': 'nurse',
 't1.14': 'brother',
 't1.15': ['My father teaches at a primary school.'],
 't1.16': 'Mẹ tôi là nông dân.',
 't1.17': 'in an office',
 't1.18': 'Where',
 't1.19': ['There are five people in my family.'],
 't1.2': 'She works on a farm.',
 't1.20': 'My mother works at a school.',
 't1.3': 'Where',
 't1.4': 'I work at a factory.',
 't1.5': 'work',
 't1.6': ['Where does she work?'],
 't1.7': 'What does your father do?',
 't1.8': 'What',
 't1.9': "She's a nurse."}

EXPLANATIONS = {'t1.1': "Câu đúng: She's an office worker.",
 't1.10': 'Đáp án: hospital',
 't1.11': 'Câu đúng: She works at a factory.',
 't1.12': 'Đáp án: Cô ấy làm việc ở viện dưỡng lão.',
 't1.13': 'Đáp án: nurse',
 't1.14': 'Đáp án: brother',
 't1.15': 'Câu đúng: My father teaches at a primary school.',
 't1.16': 'Đáp án: Mẹ tôi là nông dân.',
 't1.17': 'Đáp án: in an office',
 't1.18': 'Đáp án: Where',
 't1.19': 'Câu đúng: There are five people in my family.',
 't1.2': 'Đáp án: She works on a farm.',
 't1.20': 'Đáp án: My mother works at a school.',
 't1.3': 'Đáp án: Where',
 't1.4': 'Đáp án: I work at a factory.',
 't1.5': 'Đáp án: work',
 't1.6': 'Câu đúng: Where does she work?',
 't1.7': 'Đáp án: What does your father do?',
 't1.8': 'Đáp án: What',
 't1.9': "Đáp án: She's a nurse."}
