# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u20-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['up', 'are', 'putting', 'They', 'a', 'tent.']},
                                  {'id': 't1.2',
                                   'o': ["Where's Mai?", 'What are they doing?', "What's Mai doing?", "What's he doing?"],
                                   'plain': True,
                                   'q': 'Câu: “She\'s singing." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['she is', 'she does', 'they are', 'they do'],
                                   'plain': True,
                                   'q': 'A: Are Mai and Lan at the campsite?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['She is studing English.',
                                         'They are at the campsite.',
                                         'Yes, she is.',
                                         'They are playing tug of war.',
                                         "He's at school."],
                                   'plain': True,
                                   'q': "What's she doing?",
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['play', 'plays', 'playing', 'to play'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Lucy: They are _____ tug of war.',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['doing,', 'is', 'Mark', 'Mai?', 'What']},
                                  {'id': 't1.7',
                                   'o': ['Where are Mai and Lan?', 'Are Mai and Lan at the campsite?', 'What are Mai and Lan doing?', "What's Nam doing?"],
                                   'plain': True,
                                   'q': 'Câu “They are playing tug of war" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['play', 'plays', 'to play', 'playing'], 'plain': True, 'q': 'A: What are they doing?', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['She is studing English.',
                                         'They are at the campsite.',
                                         'Yes, she is.',
                                         'They are playing tug of war.',
                                         "He's at school."],
                                   'plain': True,
                                   'q': 'Is she taking a photo?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['do', "don't", 'does', 'doing'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Mary: What are you _____, Lucy?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['flying', 'kite.', 'a', 'is', 'He']},
                                  {'id': 't1.12',
                                   'o': ["She's dancing.", "He's playing guitar.", "They're at the campsite.", "They're singing songs."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What are they doing?”',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['playing', 'building', 'putting up', 'doing'],
                                   'plain': True,
                                   'q': "A: What's Nga doing at the campsite?",
                                   't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['watching', 'TV.', 'Son', 'is']},
                                  {'id': 't1.15',
                                   'o': ["She's dancing.", 'Yes, she is.', "She's at the campsite.", "She's taking a photo."],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “Where's Lan?”",
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['is', "isn't", 'does', "doesn't"],
                                   'plain': True,
                                   'q': 'A: Is Mary singing a song at the campsite?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['war.', 'playing', 'Nam', 'are', 'of', 'his', 'friends', 'tug', 'and']},
                                  {'id': 't1.18',
                                   'o': ["She's putting up a tent.", "He's buiding a campfire.", "They're telling a story.", "They're putting up a tent."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Họ đang dựng lều.”',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['doing', 'playing', 'building', 'telling'],
                                   'plain': True,
                                   'q': 'A: Where are Bill and Ben?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['songs?', 'Lan', 'singing', 'Mai', 'Are', 'and']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 20 – At summer camp: Kiểm tra 2',
 'unit': 20}
