# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk1-de1',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'I. Listen to the sounds and circle the correct words (nghe âm, chọn từ đúng).',
                        'items': [{'id': 'l1.1', 'o': ['jam', 'yes', 'grapes'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['party', 'music', 'Sunday'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['Malaysia', 'where', 'here'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['train', 'juice', 'beach'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'}]},
                       {'id': 'l2',
                        'instr': 'II. Listen and tick the correct pictures (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'r1',
                        'instr': 'III. Circle the correct answers (nhìn tranh, chọn câu đúng).',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['I listen to music.', 'I do housework.', 'I study at school.'],
                                   'q': 'What do you do on Mondays?',
                                   't': 'mcq'},
                                  {'id': 'r1.10',
                                   'img': 'r1_2.png',
                                   'o': ['It’s ten fifteen.', 'It’s ten o’clock.', 'It’s ten forty-five.'],
                                   'q': 'What time is it?',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['I want some water.', 'I want some juice.', 'I want some grapes.'],
                                   'q': 'What do you want to drink?',
                                   't': 'mcq'},
                                  {'id': 'r1.12', 'img': 'r1_4.png', 'o': ['Yes, I can.', 'Yes, he can’t.', 'Yes, he can.'], 'q': 'Can he cook?', 't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'IV. Fill in the blanks (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'r2.13', 'img': 'r2_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.14', 'img': 'r2_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'img': 'r2_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'img': 'r2_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Hi. My name is Mary and I am from <b>(1) ______</b> . Today is the sixth of March. It is my birthday. I am having a '
                                   'great time. I have a big birthday <b>(2) ______</b> from my parents. Lots of friends come to my party. We eat some <b>(3) '
                                   '______</b> and drink some <b>(4) ______</b> They give me many beautiful presents.</p>'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 1 – Đề 1',
 'unit': 'GiuaKy1'}
