# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Were you at the zoo last weekend?',
 't1.10': ["No, I wasn't. I was at the zoo."],
 't1.11': 'Hôm qua bạn đã ở đâu?',
 't1.12': 'Where',
 't1.13': 'I play football.',
 't1.14': 'What',
 't1.15': ['Where were you last summer?'],
 't1.16': "No, I wasn't. I was at the campsite.",
 't1.17': 'on',
 't1.18': 'Yes, it was.',
 't1.19': 'played',
 't1.2': 'Were',
 't1.20': ['I was in Bangkok last summer.'],
 't1.3': 'I was at the zoo yesterday.',
 't1.4': 'Were',
 't1.5': ['Were you on the beach last weekend?'],
 't1.6': "It's in September.",
 't1.7': 'was',
 't1.8': 'Yes, I was.',
 't1.9': 'Where'}

EXPLANATIONS = {'t1.1': 'Đáp án: Were you at the zoo last weekend?',
 't1.10': "Câu đúng: No, I wasn't. I was at the zoo.",
 't1.11': 'Đáp án: Hôm qua bạn đã ở đâu?',
 't1.12': 'Đáp án: Where',
 't1.13': 'Đáp án: I play football.',
 't1.14': 'Đáp án: What',
 't1.15': 'Câu đúng: Where were you last summer?',
 't1.16': "Đáp án: No, I wasn't. I was at the campsite.",
 't1.17': 'Đáp án: on',
 't1.18': 'Đáp án: Yes, it was.',
 't1.19': 'Đáp án: played',
 't1.2': 'Đáp án: Were',
 't1.20': 'Câu đúng: I was in Bangkok last summer.',
 't1.3': 'Đáp án: I was at the zoo yesterday.',
 't1.4': 'Đáp án: Were',
 't1.5': 'Câu đúng: Were you on the beach last weekend?',
 't1.6': "Đáp án: It's in September.",
 't1.7': 'Đáp án: was',
 't1.8': 'Đáp án: Yes, I was.',
 't1.9': 'Đáp án: Where'}
