# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'T',
 'l1.2': 'F',
 'l1.3': 'T',
 'l1.4': 'T',
 'l2.5': 'C',
 'l2.6': 'A',
 'l2.7': 'B',
 'l2.8': 'B',
 'l3.10': ['turn left'],
 'l3.11': ['watches films', 'watches a film', 'watches movies', 'watches TV'],
 'l3.12': ['long hair'],
 'l3.9': ['Great! Let’s go', 'Great, let’s go', 'Great! Let’s go!'],
 'r1.13': 'C',
 'r1.14': 'D',
 'r1.15': 'A',
 'r1.16': 'B',
 'r1.17': 'C',
 'r2.18': ['nurse'],
 'r2.19': ['quiet'],
 'r2.20': ['Last weekend'],
 'r2.21': ['behind'],
 'r2.22': ['dance beautifully'],
 'r3.23': ['an office worker', 'office worker', 'a office worker'],
 'r3.24': ['in the evening', 'at night', 'in the night'],
 'r3.25': ['opposite'],
 'r3.26': ['lions'],
 'r3.27': ['turn left'],
 'w1.28': ['The skirt is seventy thousand dong.'],
 'w1.29': ['What are these animals?'],
 'w1.30': ['He is putting up a tent at the campsite.'],
 'w1.31': ['Do you want to go to the water park with me?'],
 'w1.32': ['Where does your mother go on Tuesdays?']}

EXPLANATIONS = {'l1.1': 'Theo bài nghe: “What does he look like? – He’s short.” → khớp với tranh.',
 'l1.2': 'Theo bài nghe: “How can I get to the supermarket? – Turn right. (tranh là tiệm bánh, không khớp)” → không khớp với tranh.',
 'l1.3': 'Theo bài nghe: “Where do you live? – I live in Tran Hung Dao Street.” → khớp với tranh.',
 'l1.4': 'Theo bài nghe: “What are these animals? – They’re crocodiles!” → khớp với tranh.',
 'l2.5': 'Theo bài nghe: “Do you want to go to the bookshop? – Sorry, I can’t.” → tranh C.',
 'l2.6': 'Theo bài nghe: “What does she look like? – She’s tall.” → tranh A.',
 'l2.7': 'Theo bài nghe: “What does it say? – It says turn right.” → tranh B.',
 'l2.8': 'Theo bài nghe: “How much is it? – It’s 90,000 dong.” → tranh B.',
 'l3.10': 'Theo bài nghe: “It says turn left.” → turn left',
 'l3.11': 'Theo bài nghe: “He watches films.” → watches films',
 'l3.12': 'Theo bài nghe: “She has long hair.” → long hair',
 'l3.9': 'Theo bài nghe: “Great! Let’s go!” → Great! Let’s go',
 'r1.13': 'policeman là nghề nghiệp; còn lại là nơi chốn.',
 'r1.14': 'between là giới từ; còn lại là địa điểm.',
 'r1.15': 'weather là danh từ; còn lại là tính từ chỉ thời tiết.',
 'r1.16': 'sunny là tính từ; còn lại là trạng từ chỉ cách thức.',
 'r1.17': 'clothes là quần áo; còn lại là con vật.',
 'r2.18': 'Đoạn văn: “my mother is a nurse”.',
 'r2.19': 'Đoạn văn: “It’s a quiet street.”',
 'r2.20': 'Đoạn văn: “Last weekend, it was rainy”.',
 'r2.21': 'Đoạn văn: “the zoo behind our house”.',
 'r2.22': 'Đoạn văn: “because they dance beautifully”.',
 'r3.23': 'Tranh người làm việc ở bàn giấy: an office worker.',
 'r3.24': 'Đồng hồ 7:30 pm, trời tối: in the evening.',
 'r3.25': 'Hiệu sách đối diện hiệu đồ thể thao: opposite.',
 'r3.26': 'Hai con sư tử: lions.',
 'r3.27': 'Biển rẽ trái: turn left.',
 'w1.28': 'Câu đúng: The skirt is seventy thousand dong.',
 'w1.29': 'Câu đúng: What are these animals?',
 'w1.30': 'Câu đúng: He is putting up a tent at the campsite.',
 'w1.31': 'Câu đúng: Do you want to go to the water park with me?',
 'w1.32': 'Câu đúng: Where does your mother go on Tuesdays?'}
