# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u6-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['Where is your school?',
                                         'Where are you?',
                                         'How many buildings are there at your school?',
                                         "What's the name of your school?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về tên trường?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['Where are you from?', 'Where are you?', 'Where is your school?', 'How many playgrounds are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi “Trường bạn ở đâu?”',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Có một khu vườn ở trường của tôi.',
                                         'Có một sân chơi ở trường của tôi.',
                                         'Có một toà nhà ở trường của tôi.',
                                         'Có một thị trấn không xa trường của tôi.'],
                                   'plain': True,
                                   'q': 'Câu “There\'s one playground at my school." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['There are two playrounds at my school.',
                                         "It's in the village.",
                                         'There is a big garden.',
                                         'We can play sports in the playground.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where’s your school?”?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['How many gardens are there at your school?',
                                         'How many playgrounds are there at your school?',
                                         'How many rooms are there at your school?',
                                         'How many buildings are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu “There are four buildings at my school." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ["Where's your school?",
                                         'How many gardens are there at your school?',
                                         'How many computers are there at your school?',
                                         'How many playgrounds are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu “There is a garden at my school." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['How many gardens are there at your school?',
                                         'How many rooms are there at your school?',
                                         'How many playgrounds are there at your school?',
                                         'How many buildings are there at your school?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Có bao nhiêu sân chơi ở trường của bạn?"',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['Our school is near two cities.',
                                         'Our school is near two towns.',
                                         'Our school is near two mountains.',
                                         'Our school is near two villages.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là “Trường học của chúng tôi ở gần hai ngôi làng.”',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['Our school is near two mountains.',
                                         'Our school is in the mountains.',
                                         'There are two mountains not far from my school.',
                                         'Our school is big.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là “Trường học của chúng tôi ở trên núi.”?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['My school is in the village.',
                                         'There is a big playground at my school.',
                                         "It's Nguyen Du Primary School.",
                                         'I loved my school!'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What\'s the name of your school?"',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['How', 'When', 'Where', 'What'], 'plain': True, 'q': 'A: ____________ is your school, Nam?', 't': 'mcq'},
                                  {'id': 'b.2',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There ____________ a big playground at my school.',
                                   't': 'mcq'},
                                  {'id': 'b.3',
                                   'o': ['room', 'garden', 'playgrounds', 'building'],
                                   'plain': True,
                                   'q': 'How many ____________ are there at your school?',
                                   't': 'mcq'},
                                  {'id': 'b.4',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There ____________ two computer rooms at my school.',
                                   't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['buildings', 'computer room', 'playground', 'class'],
                                   'plain': True,
                                   'q': 'A: How many ____________ are there at her school?',
                                   't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['villages', 'town', 'mountain', 'park'],
                                   'plain': True,
                                   'q': 'There are four ____________ near his school.',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['park', 'mountains', 'buildings', 'villages'],
                                   'plain': True,
                                   'q': 'My school is near a ____________.',
                                   't': 'mcq'},
                                  {'id': 'b.8',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There ____________ a big computer room at our school.',
                                   't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'There ____________ two supermarkets not far from my school.',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['What', 'When', 'Where', 'How'],
                                   'plain': True,
                                   'q': '____________ many gardens are there at your school?',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ["Where's her school?",
                                            "What's the name of your school?",
                                            'How many playgrounds are there at your school?',
                                            'How many gardens are there at her school?',
                                            'How many computer rooms are there at his school?'],
                                   'o': ['There is a garden at her school.',
                                         "It's in the town.",
                                         'There are two computer rooms at his school.',
                                         'Nguyen Du Primary School.',
                                         'There is a playground at my school.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chỗ trống (1):',
                                   't': 'mcq'},
                                  {'id': 'd.2',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chỗ trống (2):',
                                   't': 'mcq'},
                                  {'id': 'd.3',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chỗ trống (3):',
                                   't': 'mcq'},
                                  {'id': 'd.4',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chỗ trống (4):',
                                   't': 'mcq'},
                                  {'id': 'd.5',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chỗ trống (5):',
                                   't': 'mcq'},
                                  {'id': 'd.6',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chỗ trống (6):',
                                   't': 'mcq'},
                                  {'id': 'd.7',
                                   'o': ['playground', 'school', 'Where', 'from', 'are there', 'in', 'How'],
                                   'plain': True,
                                   'q': 'Chỗ trống (7):',
                                   't': 'mcq'}],
                        'passage': "1. A: Hello. My name is Bill.<br>B: Hi. I'm Minh. <b>(1)&nbsp;______</b> is your school, Bill?<br>A: It's in the "
                                   "city.<br>2. A: I'm <b>(2)&nbsp;______</b> Thailand. And you?<br>B: I'm from Da Nang, Viet Nam.<br>A: Where's your "
                                   "<b>(3)&nbsp;______</b>?<br>B: It's <b>(4)&nbsp;______</b> the mountains.<br>3. A: <b>(5)&nbsp;______</b> many playgrounds "
                                   'are there at your school?<br>B: There is a big <b>(6)&nbsp;______</b>.<br>4. A: How many gardens <b>(7)&nbsp;______</b> at '
                                   'your school?<br>B: There is one.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': 'Minh studies at Nguyen Khuyen Primary School.', 't': 'tf'},
                                  {'id': 'e.2', 'q': 'His school is big.', 't': 'tf'},
                                  {'id': 'e.3', 'q': 'His school is in a city.', 't': 'tf'},
                                  {'id': 'e.4', 'q': 'There are four buildings at his school.', 't': 'tf'},
                                  {'id': 'e.5', 'q': 'Minh and his friends can play badminton in the playground.', 't': 'tf'},
                                  {'id': 'e.6', 'q': 'Minh can play games in the computer room.', 't': 'tf'}],
                        'passage': "Hi, my name is Minh. I study at Nguyen Du Primary School. Our school is big. It's in a town. There are four buildings at "
                                   'our school. There is a big playground. We can play badminton and football there. There is also a big computer room. We can '
                                   'play games and surf the Internet there.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'What', 'school?', 'the', 'name', 'of', 'your']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'is', 'Where', 'school?']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'a', 'in', 'village.', 'My', 'school']},
                                  {'id': 'f.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['garden', 'There', 'big', 'a', 'are', 'and', 'two', 'school.', 'at', 'playgrounds', 'my']},
                                  {'id': 'f.5',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['your', 'buildings', 'How', 'are', 'at', 'school?', 'many', 'there']},
                                  {'id': 'f.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['are', 'two', 'our', 'school.', 'at', 'buildings', 'There']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['a', 'there.', 'big', 'is', 'There', 'playround']},
                                  {'id': 'f.8',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'We', 'play', 'sports', 'playground.', 'in', 'can']},
                                  {'id': 'f.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['There', 'far', 'from', 'my', 'school.', 'two', 'villages', 'not', 'are']},
                                  {'id': 'f.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['love', 'my', 'school.', 'I']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'},
           {'audio': True,
            'groups': [{'id': 'n',
                        'instr': 'Nghe file âm thanh và làm các câu theo số thứ tự trong bài nghe.',
                        'items': [{'id': 'n.2', 'q': "Câu 2. Where's your school, Lucy?- It's in the {_}.", 't': 'fill'},
                                  {'id': 'n.4',
                                   'o': ["It's in the city.", "It's in the town.", "It's in the village."],
                                   'plain': True,
                                   'q': "Câu 4. Where's your school?",
                                   't': 'mcq'},
                                  {'id': 'n.5', 'q': "Câu 5. Is your {_} in the mountains? - No, It's in the village.", 't': 'fill'},
                                  {'id': 'n.6',
                                   'o': ['There are two.', 'There is one.'],
                                   'plain': True,
                                   'q': 'Câu 6. How many playgrounds are there at your school?',
                                   't': 'mcq'},
                                  {'id': 'n.7',
                                   'o': ['There is one.', 'There are two.', 'There are three.'],
                                   'plain': True,
                                   'q': 'Câu 7. How many buildings are there at your school?',
                                   't': 'mcq'},
                                  {'id': 'n.8',
                                   'o': ['There is one.', 'There are two.', 'There are three.'],
                                   'plain': True,
                                   'q': 'Câu 8. How many computer rooms are there at your school?',
                                   't': 'mcq'},
                                  {'id': 'n.9', 'q': 'Câu 9. There are {_} villages near my school.', 't': 'fill'},
                                  {'id': 'n.10', 'q': 'Câu 10. There are four villages near my school.', 't': 'tf'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Luyện nghe'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi về tên trường và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>What\'s '
           "the name of your school?<br>Trường của bạn tên gì?</td><td>(Name of school.)<br>Tên trường</td></tr><tr><td>Ví dụ:<br>A: What's the name of your "
           'school?<br>Trường của bạn tên gì?<br>B: Nguyen Du Primary School.<br>Trường tiểu học Nguyễn Du.</td></tr></table><p>2. Cách hỏi về địa điểm của '
           'trường và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>- Where is your school?<br>- Trường học của '
           'bạn ở đâu?<br>- Where is her/his school?<br>Trường học của cô ấy/của cậu ấy ở đâu?</td><td>- My school is in + (địa điểm).<br>- Trường học của tôi '
           "ở.. (địa điểm).<br>- Her/His school is in + (địa điểm).<br>Trường học của cô ấy/của cậu ấy ở ….<br>hoặc<br>It's in + (địa điểm).<br>Nó ở "
           "…</td></tr><tr><td>Ví dụ:<br>1. A: Where is your school? Trường học của bạn ở đâu?<br>B: It's in the mountains. Nó ở trên núi.<br>2. A: Where's "
           "her school? Trường học của cô ấy ở đâu?<br>B: It's in the town. Nó ở trong thị trấn.</td></tr></table><p>3. Cách hỏi về số lượng cơ sở vật chất ở "
           'trường và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>How many + (tên cơ sở vật chất) + are there at '
           'your school?<br>Có bao nhiêu... ở trường của bạn?</td><td>There are + (số lượng).<br>Có...</td></tr><tr><td>Ví dụ:<br>A: How many playgrounds are '
           'there at your school?<br>Có bao nhiêu sân chơi ở trường của bạn?<br>B: There are two.<br>Có hai sân chơi.</td></tr></table>',
 'title': 'Unit 6 – Our school facilities: Luyện tập',
 'unit': 6}
