# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de10',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and number (nghe và đánh số). (Ví dụ: câu 0 – tranh B.)',
                        'items': [{'id': 'l1.1', 'o': ['A', 'B', 'C', 'D', 'E'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['A', 'B', 'C', 'D', 'E'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['A', 'B', 'C', 'D', 'E'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['A', 'B', 'C', 'D', 'E'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de10/l1.png" alt="Tranh">'},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and tick or cross (nghe, tranh đúng thì tick ✓, sai thì cross ✗).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'q': 'Nghe câu số 1: nội dung nghe có khớp với tranh không? (True = tick ✓, False = cross ✗)',
                                   't': 'tf'},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'q': 'Nghe câu số 2: nội dung nghe có khớp với tranh không? (True = tick ✓, False = cross ✗)',
                                   't': 'tf'},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'q': 'Nghe câu số 3: nội dung nghe có khớp với tranh không? (True = tick ✓, False = cross ✗)',
                                   't': 'tf'},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'q': 'Nghe câu số 4: nội dung nghe có khớp với tranh không? (True = tick ✓, False = cross ✗)',
                                   't': 'tf'}]},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen and tick true or false (nghe và chọn đúng/sai).',
                        'items': [{'id': 'l3.9', 'q': 'My brother has small eyes.', 't': 'tf'},
                                  {'id': 'l3.10', 'q': 'I clean the floor at night.', 't': 'tf'},
                                  {'id': 'l3.11', 'q': 'She goes to the sports center on Saturdays.', 't': 'tf'},
                                  {'id': 'l3.12', 'q': 'The hat is ninety-nine thousand dong.', 't': 'tf'}]},
                       {'id': 'r1',
                        'instr': 'Question 4. Read and match (đọc và nối câu với tranh). Ví dụ: “Where do you live? – I live in a village.” → B.',
                        'items': [{'id': 'r1.13',
                                   'left': [{'t': 'Does she work at a hospital? – No, she doesn’t. She works at a nursing home.'},
                                            {'t': 'What do you do in the evening? – I help my mother with the cooking.'},
                                            {'t': 'What does it say? – It says “GO”.'},
                                            {'t': 'What animals do you like? – I like lions because they roar loudly.'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de10/r1.png" alt="Tranh">'},
                       {'id': 'r2',
                        'instr': 'Question 5. Read and choose A, B or C (đọc và chọn đáp án đúng).',
                        'items': [{'id': 'r2.14',
                                   'o': ['look like', 'like', 'look'],
                                   'q': 'What does your mother ____________? – She is tall and slim.',
                                   't': 'mcq'},
                                  {'id': 'r2.15',
                                   'o': ['cinema', 'supermarket', 'swimming pool'],
                                   'q': 'My father wants some grapes and beans. He goes to the _____________.',
                                   't': 'mcq'},
                                  {'id': 'r2.16',
                                   'o': ['run quickly', 'roar loudly', 'sing merrily'],
                                   'q': 'Why do you like birds? – Because they ________________.',
                                   't': 'mcq'}]},
                       {'id': 'r3',
                        'instr': 'Question 6. Read and tick True or False (đọc đoạn văn, chọn đúng/sai).',
                        'items': [{'id': 'r3.17', 'q': 'The weather is windy and sunny.', 't': 'tf'},
                                  {'id': 'r3.18', 'q': 'My brother and I go swimming.', 't': 'tf'},
                                  {'id': 'r3.19', 'q': 'We watch films at home because it is rainy.', 't': 'tf'}],
                        'passage': '<p>Today is Sunday. The weather is windy. We are at the water park in the morning. My brother and I go swimming in the '
                                   'swimming pool. In the afternoon, we go on a picnic. My father will help my mother with cooking. But it is rainy, we must '
                                   'come back and watch films at home.</p><p><i>Ví dụ: “Today is Friday.” → False.</i></p>'},
                       {'id': 'w1',
                        'instr': 'Question 7. Reorder the letters to make a word (sắp xếp chữ cái thành từ, nhìn tranh). Ví dụ: s T i t r h → T-shirt.',
                        'items': [{'id': 'w1.20', 'img': 'w1_1.png', 'q': 'c o p i e l a n m → {_}', 't': 'fill'},
                                  {'id': 'w1.21', 'img': 'w1_2.png', 'q': 'k o p s o b o h → {_}', 't': 'fill'},
                                  {'id': 'w1.22', 'img': 'w1_3.png', 'q': 'i l c o d e r c o → {_}', 't': 'fill'},
                                  {'id': 'w1.23', 'img': 'w1_4.png', 'q': 'd o u c l y → {_}', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Question 8. Reorder the words to make complete sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w2.24',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'Turn', 'to', 'get', 'stall.', 'to', 'left', 'food']},
                                  {'id': 'w2.25', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['much', 'this', 'is', 'bag?', 'How']},
                                  {'id': 'w2.26', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'Because', 'roar', 'lions', 'loudly.']},
                                  {'id': 'w2.27',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Sundays.', 'My', 'washes', 'clothes', 'the', 'mother', 'on']}]},
                       {'id': 'w3',
                        'instr': 'Question 9. Answer the questions with the given words (trả lời bằng từ cho sẵn). Ví dụ: What does his father do? (factory '
                                 'worker) – He’s a factory worker.',
                        'items': [{'id': 'w3.28', 'q': 'What’s the weather like today? (sunny and windy)<br>{_}', 't': 'fill'},
                                  {'id': 'w3.29', 'q': 'How can I get to the cinema? (go straight, turn right)<br>{_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 10',
 'unit': 'OnHK2'}
