# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'B',
 'l1.2': 'A',
 'l1.3': 'C',
 'l1.4': 'B',
 'l2.5': '2',
 'l2.6': '4',
 'l2.7': '1',
 'l2.8': '3',
 'l3.10': '3',
 'l3.11': '4',
 'l3.12': '2',
 'l3.9': '1',
 'l4.13': ['America'],
 'l4.14': ['Maths', 'Math'],
 'l4.15': ['running'],
 'l4.16': ['January'],
 'r1.17': {'blanks': [['C'], ['E'], ['A'], ['D']]},
 'r2.18': 'B',
 'r2.19': 'A',
 'r2.20': 'C',
 'r3.21': 'T',
 'r3.22': 'F',
 'r3.23': 'F',
 'w1.24': ['chips'],
 'w1.25': ['swim'],
 'w1.26': ['Science'],
 'w2.27': ['I have breakfast at six fifteen.'],
 'w2.28': ['What do you want to eat?'],
 'w2.29': ['My school has a playground.']}

EXPLANATIONS = {'l1.1': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.2': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.3': 'Đáp án C (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.4': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l2.5': 'Tranh A ứng với câu 2 (theo đáp án của đề).',
 'l2.6': 'Tranh C ứng với câu 4 (theo đáp án của đề).',
 'l2.7': 'Tranh D ứng với câu 1 (theo đáp án của đề).',
 'l2.8': 'Tranh E ứng với câu 3 (theo đáp án của đề).',
 'l3.10': 'Tranh C ứng với câu 3 (theo đáp án của đề).',
 'l3.11': 'Tranh D ứng với câu 4 (theo đáp án của đề).',
 'l3.12': 'Tranh E ứng với câu 2 (theo đáp án của đề).',
 'l3.9': 'Tranh A ứng với câu 1 (theo đáp án của đề).',
 'l4.13': 'Đáp án: America',
 'l4.14': 'Đáp án: Maths',
 'l4.15': 'Đáp án: running',
 'l4.16': 'Đáp án: January',
 'r1.17': 'Đáp án theo đáp án của đề: grapes–C, English teacher–E, Britain–A, listen to music–D',
 'r2.18': 'Đáp án: B. can',
 'r2.19': 'Đáp án: A. play',
 'r2.20': 'Đáp án: C. and',
 'r3.21': 'Đáp án: True (theo đáp án của đề).',
 'r3.22': 'Đáp án: False (theo đáp án của đề).',
 'r3.23': 'Đáp án: False (theo đáp án của đề).',
 'w1.24': 'Từ đúng: chips',
 'w1.25': 'Từ đúng: swim',
 'w1.26': 'Từ đúng: Science',
 'w2.27': 'Câu đúng: I have breakfast at six fifteen.',
 'w2.28': 'Câu đúng: What do you want to eat?',
 'w2.29': 'Câu đúng: My school has a playground.'}
