# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de9',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and draw lines (nghe và nối từng câu số 1–4 với tranh; tranh C là ví dụ số 0).',
                        'items': [{'id': 'l1.1',
                                   'left': [{'t': 'Câu 1'}, {'t': 'Câu 2'}, {'t': 'Câu 3'}, {'t': 'Câu 4'}],
                                   'o': ['A', 'B', 'C', 'D', 'E'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on2_de9/m1.png" alt="Tranh A–E">'},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and choose True or False (nghe, chọn True hoặc False).',
                        'items': [{'id': 'l2.2', 'q': 'She looks young with short hair.', 't': 'tf'},
                                  {'id': 'l2.3', 'q': 'I play basketball with my friends in the morning.', 't': 'tf'},
                                  {'id': 'l2.4', 'q': 'The teacher is building a campfire.', 't': 'tf'},
                                  {'id': 'l2.5', 'q': 'These animals are peacocks.', 't': 'tf'}]},
                       {'id': 'l3a',
                        'instr': 'Question 3a. Listen to the passage (Lucy) and choose the correct answer (nghe và chọn đáp án đúng).',
                        'items': [{'id': 'l3a.6',
                                   'o': ['doctor / hospital', 'worker / factory', 'farmer / farm'],
                                   'q': '(1) This man is Lucy’s father. He is a ____ . He works very hard at a ____ .',
                                   't': 'mcq'},
                                  {'id': 'l3a.7',
                                   'o': ['yoga / gym', 'exercise / gym', 'yoga / sport center'],
                                   'q': '(2) Every Sunday, Lucy’s mother does ____ at the ____ .',
                                   't': 'mcq'}],
                        'passage': '<p><b>Lucy:</b> Hello. My name is Lucy. I am (0) ______ of my family. We are having dinner. This man is my father. He is a '
                                   '<b>(1) ______</b>. He works very hard at a ______. That woman is my mother. Every Sunday, my mother does <b>(2) ______</b> '
                                   'at the ______.</p><p><i>Ví dụ (0): A. drawing a picture (Lucy đang vẽ tranh).</i></p>'},
                       {'id': 'l3b',
                        'instr': 'Question 3b. Listen to the passage (Nam) and choose the correct answer (nghe và chọn đáp án đúng).',
                        'items': [{'id': 'l3b.8', 'o': ['sunny', 'windy', 'cloudy'], 'q': '(3) The weather yesterday was ____ .', 't': 'mcq'},
                                  {'id': 'l3b.9',
                                   'o': ['fifty thousand', 'forty thousand', 'thirty thousand'],
                                   'q': '(4) The books are ____ dong.',
                                   't': 'mcq'}],
                        'passage': '<p><b>Nam:</b> Hi everyone, I am Nam. The weather was <b>(3) ______</b> yesterday, so we were at a bookshop. It is next to '
                                   'the pet shop. My sister bought some books. It is <b>(4) ______</b> dong. We had a lot of fun.</p><img '
                                   'src="../../../../assets/lop4_on2_de9/p3b.png" alt="Hình" style="max-width:120px;height:auto">'},
                       {'bank': ['five o’clock', 'wash the dishes', 'with the cooking', 'in the morning'],
                        'id': 'r1',
                        'instr': 'Question 4. Fill in each blank with one given phrase of words (chọn cụm từ trong khung điền vào chỗ trống).',
                        'items': [{'id': 'r1.10', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r1.11', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r1.12', 'q': 'Chỗ trống (3): {_}', 't': 'fill'}],
                        'passage': '<p>Good morning, everyone! My name is Thuy Duong. I get up at six thirty (0) <b>in the morning</b>. I go to school at '
                                   'seven thirty. I have lunch at school with my classmates at noon. I go home at <b>(1) ______</b>. I help my mom <b>(2) '
                                   '______</b> in the evening. We have dinner at seven o’clock. After dinner, I <b>(3) ______</b>. I go to bed at nine thirty. '
                                   'Can you tell me about your daily routines?</p><img src="../../../../assets/lop4_on2_de9/p4.png" alt="Hình" '
                                   'style="max-width:130px;height:auto">'},
                       {'id': 'r2',
                        'instr': 'Question 5. Read and choose A, B or C (đọc và chọn đáp án đúng).',
                        'items': [{'id': 'r2.13', 'o': ['at', 'in', 'on'], 'q': 'Where does your brother go ____ Sundays?', 't': 'mcq'},
                                  {'id': 'r2.14', 'o': ['in', 'to', 'for'], 'q': 'Do you want to go ____ the cinema?', 't': 'mcq'},
                                  {'id': 'r2.15', 'o': ['in', 'on', 'around'], 'q': 'The kids are dancing ____ the campfire.', 't': 'mcq'},
                                  {'id': 'r2.16', 'o': ['at', 'on', 'under'], 'q': 'Nam and I are ____ the shopping centre.', 't': 'mcq'}]},
                       {'id': 'r3',
                        'instr': 'Question 6. Read and tick True or False (đọc đoạn văn, chọn True hoặc False).',
                        'items': [{'id': 'r3.17', 'q': 'The giraffes are running slowly on the field.', 't': 'tf'},
                                  {'id': 'r3.18', 'q': 'Harry likes lions because they roar loudly.', 't': 'tf'},
                                  {'id': 'r3.19', 'q': 'Linda likes peacocks because they sing merrily.', 't': 'tf'}],
                        'passage': '<p>Hello, I’m Harry. It is sunny today. I and my family are at the zoo. I and my sister like the animals at the zoo. Look! '
                                   'They are lions. I like them because they roar loudly. These are hippos. They are swimming in the pond. I can see two '
                                   'giraffes. They are running very quickly on the field. My sister, Linda, likes birds because they sing merrily. She can see '
                                   'a couple of peacocks. She likes them because they dance beautifully. We have a lot of fun at the zoo!</p><img '
                                   'src="../../../../assets/lop4_on2_de9/p6.png" alt="Hình" style="max-width:230px;height:auto">'},
                       {'id': 'w1',
                        'instr': 'Question 7. Fill in the blanks (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'w1.20', 'img': 'w1_1.png', 'q': 'Do you want to go to the {_}?<br>Great! Let’s go.', 't': 'fill'},
                                  {'id': 'w1.21', 'img': 'w1_2.png', 'q': 'Where’s the bookshop?<br>It’s {_} the bakery.', 't': 'fill'},
                                  {'id': 'w1.22', 'img': 'w1_3.png', 'q': 'What do you do in the evening?<br>I {_} in the evening.', 't': 'fill'},
                                  {'id': 'w1.23', 'img': 'w1_4.png', 'q': 'How can I get to the food stall?<br>Go straight and {_}.', 't': 'fill'}]},
                       {'id': 'w2',
                        'instr': 'Question 8. Answer the questions with the given words (dùng từ gợi ý để trả lời).',
                        'items': [{'id': 'w2.24', 'q': 'What does your sister look like? (short, big)<br>→ {_}', 't': 'fill'},
                                  {'id': 'w2.25', 'q': 'What does your mother do on Sundays? (clean the house)<br>→ {_}', 't': 'fill'},
                                  {'id': 'w2.26', 'q': 'How much is this book? (forty-five thousand dong)<br>→ {_}', 't': 'fill'}]},
                       {'id': 'w3',
                        'instr': 'Question 9. Use the given words to make sentences (dùng từ gợi ý viết thành câu hoàn chỉnh).',
                        'items': [{'id': 'w3.27', 'q': 'Why/ you/ like/ elephants?<br>→ {_}', 't': 'fill'},
                                  {'id': 'w3.28', 'q': 'Kids/ dancing/ around the campfire.<br>→ {_}', 't': 'fill'},
                                  {'id': 'w3.29', 'q': 'I/ like/ peacocks/ because/ dance beautifully.<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 9',
 'unit': 'OnHK2'}
