# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u10-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['last', 'were', 'you', 'Where', 'summer?']},
                                  {'id': 't1.2',
                                   'o': ["Yes, I wasn't.", "No, I wasn't. I was at the campsite.", 'I was in the mountains.', 'No, I was.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Were you on the beach last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'o': ['in', 'at', 'on', 'to'], 'plain': True, 'q': 'Were you _____________ the beach yesterday?', 't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['I play football.', 'Yes, it is.', 'I was at the zoo yesterday.', 'Yes, I was.', 'Yes, it was.'],
                                   'plain': True,
                                   'q': 'Was the food good?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: I _____ volleyball with my friends. How about you? Where were you last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Bangkok', 'was', 'in', 'last', 'I', 'summer.']},
                                  {'id': 't1.7',
                                   'o': ['Where were you last Sunday?', 'Were you at the zoo last Saturday?', 'Is it a big city?', "When's your sports day?"],
                                   'plain': True,
                                   'q': 'Câu “Yes, I was,” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['Where', 'What', 'When', 'How'],
                                   'plain': True,
                                   'q': 'A: _____________ were you last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['I play football.', 'Yes, it is.', 'I was at the zoo yesterday.', 'Yes, I was.', 'Yes, it was.'],
                                   'plain': True,
                                   'q': 'Is it a big city?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: What _____ you do there?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['a', 'city?', 'big', 'it', 'Was']},
                                  {'id': 't1.12',
                                   'o': ['Where were you last summer?',
                                         'Were you in the countryside last weekend?',
                                         'Where were you last weekend?',
                                         'Where were you yesterday?'],
                                   'plain': True,
                                   'q': 'Câu “I was on the beach last weekend.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['at', 'on', 'in', 'to'],
                                   'plain': True,
                                   'q': 'A: Were you _____________ the campsite yesterday?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['What', 'did', 'played', 'Were', 'painted', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: I _____ a picture.',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['there?', 'you', 'What', 'do', 'did']},
                                  {'id': 't1.16',
                                   'o': ["No, it isn't.", 'Yes, he was.', "No, I wasn't. I was on the beach last Sunday.", "No, they weren't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Were you at the campsite last Sunday?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['today', 'tomorrow', 'last summer', 'next Sunday'],
                                   'plain': True,
                                   'q': 'A: Were you in the countryside _____________?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['of', 'I', 'my', 'picture', 'painted', 'a', 'hometown.']},
                                  {'id': 't1.19',
                                   'o': ['Cuối tuần rồi bạn đã ở đâu?',
                                         'Hôm qua bạn đã ở đâu?',
                                         'Mùa hè vừa rồi bạn đã ở đâu?',
                                         'Có phải bạn ở miền quê không?'],
                                   'plain': True,
                                   'q': 'Câu “Where were you last summer" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'o': ['am', 'was', 'were', 'are'], 'plain': True, 'q': 'A: Where were you last week, Mai?', 't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 10 – Our summer holidays: Kiểm tra 2',
 'unit': 10}
