# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'Hôm nay là thứ mấy?',
 't1.10': ['It is Wednesday'],
 't1.11': 'What day is it today?',
 't1.12': 'Sundays',
 't1.13': 'I do housework.',
 't1.14': 'What',
 't1.15': ['Mai goes to school from Monday to Friday.'],
 't1.16': 'What do you do on Mondays?',
 't1.17': "seven o'clock",
 't1.18': 'Yes, she does.',
 't1.19': 'Saturday',
 't1.2': 'Wednesday',
 't1.20': ['What do you do at the weekend?'],
 't1.3': "It's Friday.",
 't1.4': 'How',
 't1.5': ['What day is it today, Mai?'],
 't1.6': 'Bạn làm gì vào các ngày thứ Bảy?',
 't1.7': 'What',
 't1.8': "It's eight o'clock.",
 't1.9': 'fine'}

EXPLANATIONS = {'t1.1': 'Đáp án: Hôm nay là thứ mấy?',
 't1.10': 'Câu đúng: It is Wednesday',
 't1.11': 'Đáp án: What day is it today?',
 't1.12': 'Đáp án: Sundays',
 't1.13': 'Đáp án: I do housework.',
 't1.14': 'Đáp án: What',
 't1.15': 'Câu đúng: Mai goes to school from Monday to Friday.',
 't1.16': 'Đáp án: What do you do on Mondays?',
 't1.17': "Đáp án: seven o'clock",
 't1.18': 'Đáp án: Yes, she does.',
 't1.19': 'Đáp án: Saturday',
 't1.2': 'Đáp án: Wednesday',
 't1.20': 'Câu đúng: What do you do at the weekend?',
 't1.3': "Đáp án: It's Friday.",
 't1.4': 'Đáp án: How',
 't1.5': 'Câu đúng: What day is it today, Mai?',
 't1.6': 'Đáp án: Bạn làm gì vào các ngày thứ Bảy?',
 't1.7': 'Đáp án: What',
 't1.8': "Đáp án: It's eight o'clock.",
 't1.9': 'Đáp án: fine'}
