# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_dc1.py"""

SET = {'grade': 4,
 'id': 'lop4-dc1-a',
 'pages': [{'groups': [{'id': 'v1',
                        'instr': 'Chọn nghĩa tiếng Việt đúng của từ / cụm từ. (Unit 1–3)',
                        'items': [{'id': 'v1.1',
                                   'o': ['nước Việt Nam', 'nước Mỹ', 'nước Xin-ga-po', 'nước Úc'],
                                   'plain': True,
                                   'q': 'Unit 1 – “America” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.2',
                                   'o': ['nước Nhật', 'nước Ma-lay-xi-a', 'nước Thái Lan', 'nước Xin-ga-po'],
                                   'plain': True,
                                   'q': 'Unit 1 – “Malaysia” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.3',
                                   'o': ['nước Úc', 'nước Anh', 'nước Thái Lan', 'nước Việt Nam'],
                                   'plain': True,
                                   'q': 'Unit 1 – “Australia” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.4',
                                   'o': ['nước Nhật', 'nước Úc', 'nước Xin-ga-po', 'nước Việt Nam'],
                                   'plain': True,
                                   'q': 'Unit 1 – “Singapore” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.5',
                                   'o': ['nước Ma-lay-xi-a', 'nước Úc', 'nước Anh', 'nước Thái Lan'],
                                   'plain': True,
                                   'q': 'Unit 1 – “Britain” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.6',
                                   'o': ['nước Úc', 'nước Nhật', 'nước Ma-lay-xi-a', 'nước Thái Lan'],
                                   'plain': True,
                                   'q': 'Unit 1 – “Thailand” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.7',
                                   'o': ['nước Nhật', 'nước Mỹ', 'nước Anh', 'nước Úc'],
                                   'plain': True,
                                   'q': 'Unit 1 – “Japan” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.8',
                                   'o': ['nước Xin-ga-po', 'nước Việt Nam', 'nước Nhật', 'nước Ma-lay-xi-a'],
                                   'plain': True,
                                   'q': 'Unit 1 – “Viet Nam” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.9',
                                   'o': ['số 30', 'trò chuyện cùng bạn', 'thức dậy', 'số 15'],
                                   'plain': True,
                                   'q': 'Unit 2 – “fifteen” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.10',
                                   'o': ['thức dậy', 'số 30', 'đi ngủ', 'số 45'],
                                   'plain': True,
                                   'q': 'Unit 2 – “get up” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.11',
                                   'o': ['ăn tối', 'số 45', 'trò chuyện cùng bạn', 'ăn trưa'],
                                   'plain': True,
                                   'q': 'Unit 2 – “forty-five” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.12',
                                   'o': ['ăn trưa', 'trò chuyện cùng bạn', 'đi học', 'đi ngủ'],
                                   'plain': True,
                                   'q': 'Unit 2 – “go to bed” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.13',
                                   'o': ['giờ đúng', 'số 45', 'đi học', 'ăn sáng'],
                                   'plain': True,
                                   'q': 'Unit 2 – “o’clock” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.14',
                                   'o': ['đi học', 'ăn tối', 'số 15', 'làm bài tập về nhà'],
                                   'plain': True,
                                   'q': 'Unit 2 – “go to school” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.15',
                                   'o': ['số 30', 'đi học', 'đi ngủ', 'làm bài tập về nhà'],
                                   'plain': True,
                                   'q': 'Unit 2 – “thirty” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.16',
                                   'o': ['giờ đúng', 'thức dậy', 'ăn sáng', 'ăn trưa'],
                                   'plain': True,
                                   'q': 'Unit 2 – “have breakfast” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.17',
                                   'o': ['đi ngủ', 'làm bài tập về nhà', 'số 30', 'ăn sáng'],
                                   'plain': True,
                                   'q': 'Unit 2 – “do homework” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.18',
                                   'o': ['giờ đúng', 'ăn trưa', 'số 45', 'trò chuyện cùng bạn'],
                                   'plain': True,
                                   'q': 'Unit 2 – “have lunch” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.19',
                                   'o': ['số 15', 'số 30', 'đi ngủ', 'trò chuyện cùng bạn'],
                                   'plain': True,
                                   'q': 'Unit 2 – “chat with friends” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.20',
                                   'o': ['ăn trưa', 'số 30', 'ăn tối', 'giờ đúng'],
                                   'plain': True,
                                   'q': 'Unit 2 – “have dinner” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.21',
                                   'o': ['xem ti vi', 'Thứ 2', 'Thứ 4', 'học ở trường'],
                                   'plain': True,
                                   'q': 'Unit 3 – “Monday” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.22',
                                   'o': ['Thứ 7', 'Thứ 6', 'nghe nhạc', 'học ở trường'],
                                   'plain': True,
                                   'q': 'Unit 3 – “listen to music” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.23',
                                   'o': ['Thứ 3', 'Thứ 7', 'Thứ 6', 'học ở trường'],
                                   'plain': True,
                                   'q': 'Unit 3 – “Tuesday” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.24',
                                   'o': ['Thứ 7', 'làm việc nhà', 'hôm nay', 'Thứ 2'],
                                   'plain': True,
                                   'q': 'Unit 3 – “do housework” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.25',
                                   'o': ['Thứ 6', 'Thứ 2', 'Chủ nhật', 'Thứ 4'],
                                   'plain': True,
                                   'q': 'Unit 3 – “Wednesday” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.26',
                                   'o': ['học ở trường', 'Thứ 7', 'ở nhà', 'xem ti vi'],
                                   'plain': True,
                                   'q': 'Unit 3 – “study at school” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.27',
                                   'o': ['Thứ 7', 'hôm nay', 'Thứ 5', 'xem ti vi'],
                                   'plain': True,
                                   'q': 'Unit 3 – “Thursday” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.28',
                                   'o': ['Chủ nhật', 'Thứ 5', 'cuối tuần', 'ở nhà'],
                                   'plain': True,
                                   'q': 'Unit 3 – “stay at home” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.29',
                                   'o': ['Thứ 6', 'làm việc nhà', 'cuối tuần', 'ở nhà'],
                                   'plain': True,
                                   'q': 'Unit 3 – “Friday” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.30',
                                   'o': ['hôm nay', 'cuối tuần', 'làm việc nhà', 'Chủ nhật'],
                                   'plain': True,
                                   'q': 'Unit 3 – “at the weekend” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.31',
                                   'o': ['làm việc nhà', 'hôm nay', 'nghe nhạc', 'Thứ 7'],
                                   'plain': True,
                                   'q': 'Unit 3 – “Saturday” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.32',
                                   'o': ['nghe nhạc', 'Thứ 4', 'học ở trường', 'xem ti vi'],
                                   'plain': True,
                                   'q': 'Unit 3 – “watch TV” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.33',
                                   'o': ['Chủ nhật', 'cuối tuần', 'Thứ 2', 'Thứ 4'],
                                   'plain': True,
                                   'q': 'Unit 3 – “Sunday” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v1.34',
                                   'o': ['Thứ 7', 'hôm nay', 'Thứ 2', 'Thứ 5'],
                                   'plain': True,
                                   'q': 'Unit 3 – “today” nghĩa là gì?',
                                   't': 'mcq'}]}],
            'id': 'tu-vung-1',
            'mode': 'practice',
            'title': 'Từ vựng Unit 1–3'},
           {'groups': [{'id': 'v2',
                        'instr': 'Chọn nghĩa tiếng Việt đúng của từ / cụm từ. (Unit 4–5)',
                        'items': [{'id': 'v2.35',
                                   'o': ['ngày sinh', 'Tháng 8', 'Tháng 1', 'Tháng 6'],
                                   'plain': True,
                                   'q': 'Unit 4 – “January” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.36',
                                   'o': ['Tháng 6', 'quả nho', 'Khoai tây chiên', 'Tháng 2'],
                                   'plain': True,
                                   'q': 'Unit 4 – “June” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.37',
                                   'o': ['Tháng 2', 'Tháng 4', 'Tháng 10', 'Tháng 1'],
                                   'plain': True,
                                   'q': 'Unit 4 – “February” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.38',
                                   'o': ['buổi tiệc', 'Tháng 1', 'Tháng 12', 'Tháng 7'],
                                   'plain': True,
                                   'q': 'Unit 4 – “July” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.39',
                                   'o': ['Tháng 1', 'Tháng 3', 'quả nho', 'nước ép'],
                                   'plain': True,
                                   'q': 'Unit 4 – “March” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.40',
                                   'o': ['Tháng 12', 'Tháng 8', 'Tháng 10', 'Tháng 4'],
                                   'plain': True,
                                   'q': 'Unit 4 – “August” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.41',
                                   'o': ['quả nho', 'Tháng 4', 'buổi tiệc', 'mứt'],
                                   'plain': True,
                                   'q': 'Unit 4 – “April” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.42',
                                   'o': ['mứt', 'Tháng 10', 'Tháng 9', 'Tháng 4'],
                                   'plain': True,
                                   'q': 'Unit 4 – “September” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.43',
                                   'o': ['nước ép', 'Tháng 11', 'buổi tiệc', 'Tháng 5'],
                                   'plain': True,
                                   'q': 'Unit 4 – “May” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.44',
                                   'o': ['ngày sinh', 'Tháng 10', 'quả nho', 'buổi tiệc'],
                                   'plain': True,
                                   'q': 'Unit 4 – “October” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.45',
                                   'o': ['Tháng 10', 'ngày sinh', 'Tháng 2', 'Tháng 3'],
                                   'plain': True,
                                   'q': 'Unit 4 – “birthday” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.46',
                                   'o': ['Tháng 11', 'Tháng 8', 'Tháng 4', 'Tháng 7'],
                                   'plain': True,
                                   'q': 'Unit 4 – “November” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.47',
                                   'o': ['Tháng 3', 'ngày sinh', 'quả nho', 'Tháng 7'],
                                   'plain': True,
                                   'q': 'Unit 4 – “grape” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.48',
                                   'o': ['Tháng 12', 'mứt', 'Khoai tây chiên', 'quả nho'],
                                   'plain': True,
                                   'q': 'Unit 4 – “December” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.49', 'o': ['mứt', 'quả nho', 'Tháng 10', 'nước'], 'plain': True, 'q': 'Unit 4 – “jam” nghĩa là gì?', 't': 'mcq'},
                                  {'id': 'v2.50',
                                   'o': ['Tháng 4', 'Tháng 8', 'mứt', 'nước chanh'],
                                   'plain': True,
                                   'q': 'Unit 4 – “lemonade” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.51',
                                   'o': ['mứt', 'Tháng 1', 'Tháng 3', 'nước ép'],
                                   'plain': True,
                                   'q': 'Unit 4 – “juice” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.52',
                                   'o': ['buổi tiệc', 'nước ép', 'Tháng 6', 'Tháng 1'],
                                   'plain': True,
                                   'q': 'Unit 4 – “party” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.53',
                                   'o': ['Tháng 1', 'Tháng 5', 'Tháng 6', 'Khoai tây chiên'],
                                   'plain': True,
                                   'q': 'Unit 4 – “chip” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.54',
                                   'o': ['Tháng 2', 'Tháng 1', 'nước', 'Tháng 4'],
                                   'plain': True,
                                   'q': 'Unit 4 – “water” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.55',
                                   'o': ['có thể, biết (làm gì)', 'trượt pa tin', 'bơi lội', 'chơi đàn ghi ta'],
                                   'plain': True,
                                   'q': 'Unit 5 – “can” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.56',
                                   'o': ['có thể, biết (làm gì)', 'cưỡi ngựa', 'nhưng', 'vẽ tranh'],
                                   'plain': True,
                                   'q': 'Unit 5 – “ride a horse” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.57',
                                   'o': ['chơi đàn ghi ta', 'vẽ tranh', 'nấu ăn', 'nhưng'],
                                   'plain': True,
                                   'q': 'Unit 5 – “cook” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.58',
                                   'o': ['trượt pa tin', 'cưỡi ngựa', 'bơi lội', 'nhưng'],
                                   'plain': True,
                                   'q': 'Unit 5 – “roller skate” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.59',
                                   'o': ['chơi đàn piano', 'nấu ăn', 'vẽ tranh', 'bơi lội'],
                                   'plain': True,
                                   'q': 'Unit 5 – “play the piano” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.60',
                                   'o': ['chơi đàn piano', 'bơi lội', 'trượt pa tin', 'nấu ăn'],
                                   'plain': True,
                                   'q': 'Unit 5 – “swim” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.61',
                                   'o': ['chơi đàn ghi ta', 'nấu ăn', 'cưỡi ngựa', 'vẽ tranh'],
                                   'plain': True,
                                   'q': 'Unit 5 – “play the guitar” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.62',
                                   'o': ['có thể, biết (làm gì)', 'trượt pa tin', 'nhưng', 'vẽ tranh'],
                                   'plain': True,
                                   'q': 'Unit 5 – “but” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.63',
                                   'o': ['đạp xe', 'nấu ăn', 'vẽ tranh', 'có thể, biết (làm gì)'],
                                   'plain': True,
                                   'q': 'Unit 5 – “ride a bike” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v2.64',
                                   'o': ['chơi đàn piano', 'nấu ăn', 'vẽ tranh', 'có thể, biết (làm gì)'],
                                   'plain': True,
                                   'q': 'Unit 5 – “draw a picture” nghĩa là gì?',
                                   't': 'mcq'}]}],
            'id': 'tu-vung-2',
            'mode': 'practice',
            'title': 'Từ vựng Unit 4–5'},
           {'groups': [{'id': 'v3',
                        'instr': 'Chọn nghĩa tiếng Việt đúng của từ / cụm từ. (Unit 6–10)',
                        'items': [{'id': 'v3.65',
                                   'o': ['phòng tin học', 'ở làng quê', 'ở thị trấn', 'ở thành phố'],
                                   'plain': True,
                                   'q': 'Unit 6 – “in the city” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.66',
                                   'o': ['ở vùng núi', 'ở thành phố', 'ở thị trấn', 'khu vườn'],
                                   'plain': True,
                                   'q': 'Unit 6 – “garden” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.67',
                                   'o': ['ở thị trấn', 'sân chơi', 'ở thành phố', 'ở vùng núi'],
                                   'plain': True,
                                   'q': 'Unit 6 – “in the mountains” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.68',
                                   'o': ['ở thị trấn', 'Tòa nhà', 'sân chơi', 'ở làng quê'],
                                   'plain': True,
                                   'q': 'Unit 6 – “playground” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.69',
                                   'o': ['ở làng quê', 'phòng tin học', 'Tòa nhà', 'ở thị trấn'],
                                   'plain': True,
                                   'q': 'Unit 6 – “in the town” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.70',
                                   'o': ['phòng tin học', 'ở vùng núi', 'ở thị trấn', 'Tòa nhà'],
                                   'plain': True,
                                   'q': 'Unit 6 – “building” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.71',
                                   'o': ['Tòa nhà', 'ở làng quê', 'ở thành phố', 'sân chơi'],
                                   'plain': True,
                                   'q': 'Unit 6 – “in the village” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.72',
                                   'o': ['ở làng quê', 'phòng tin học', 'khu vườn', 'sân chơi'],
                                   'plain': True,
                                   'q': 'Unit 6 – “computer room” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.73',
                                   'o': ['môn Tiếng Anh', 'môn Toán, toán học', 'môn Mĩ thuật', 'môn Lịch sử và Địa lí'],
                                   'plain': True,
                                   'q': 'Unit 7 – “art” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.74',
                                   'o': ['môn Tin học', 'môn Âm nhạc', 'môn Tiếng Anh', 'môn Khoa học'],
                                   'plain': True,
                                   'q': 'Unit 7 – “music” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.75',
                                   'o': ['môn học', 'môn Khoa học', 'môn Tiếng Anh', 'môn thể dục'],
                                   'plain': True,
                                   'q': 'Unit 7 – “English” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.76',
                                   'o': ['môn Mĩ thuật', 'môn học', 'môn Khoa học', 'môn Tiếng Việt'],
                                   'plain': True,
                                   'q': 'Unit 7 – “science” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.77',
                                   'o': ['môn Lịch sử và Địa lí', 'môn thể dục', 'môn Tin học', 'môn Tiếng Việt'],
                                   'plain': True,
                                   'q': 'Unit 7 – “history and geography” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.78',
                                   'o': ['môn Tiếng Việt', 'môn Toán, toán học', 'môn Âm nhạc', 'môn Khoa học'],
                                   'plain': True,
                                   'q': 'Unit 7 – “Vietnamese” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.79',
                                   'o': ['môn Tiếng Việt', 'môn Toán, toán học', 'môn Tin học', 'môn Khoa học'],
                                   'plain': True,
                                   'q': 'Unit 7 – “maths” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.80',
                                   'o': ['môn Tiếng Việt', 'môn Lịch sử và Địa lí', 'môn Tin học', 'môn Khoa học'],
                                   'plain': True,
                                   'q': 'Unit 7 – “IT” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.81',
                                   'o': ['môn học', 'môn thể dục', 'môn Khoa học', 'môn Toán, toán học'],
                                   'plain': True,
                                   'q': 'Unit 7 – “subject” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.82',
                                   'o': ['môn Tin học', 'môn Toán, toán học', 'môn học', 'môn thể dục'],
                                   'plain': True,
                                   'q': 'Unit 7 – “PE” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.83',
                                   'o': ['tại sao', 'giáo viên (dạy Tiếng Anh)', 'họa sĩ', 'ca sĩ'],
                                   'plain': True,
                                   'q': 'Unit 8 – “English teacher” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.84',
                                   'o': ['bởi vì', 'giáo viên (dạy Tiếng Anh)', 'họa sĩ', 'giáo viên (dạy Toán)'],
                                   'plain': True,
                                   'q': 'Unit 8 – “painter” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.85',
                                   'o': ['giáo viên (dạy Toán)', 'bởi vì', 'ca sĩ', 'yêu thích'],
                                   'plain': True,
                                   'q': 'Unit 8 – “maths teacher” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.86',
                                   'o': ['viết truyện', 'ca sĩ', 'tại sao', 'yêu thích'],
                                   'plain': True,
                                   'q': 'Unit 8 – “singer” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.87',
                                   'o': ['giáo viên (dạy Tiếng Anh)', 'yêu thích', 'ca sĩ', 'giáo viên (dạy Toán)'],
                                   'plain': True,
                                   'q': 'Unit 8 – “favourite” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.88',
                                   'o': ['bởi vì', 'tại sao', 'yêu thích', 'ca sĩ'],
                                   'plain': True,
                                   'q': 'Unit 8 – “because” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.89',
                                   'o': ['ca sĩ', 'tại sao', 'viết truyện', 'yêu thích'],
                                   'plain': True,
                                   'q': 'Unit 8 – “write a story” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.90',
                                   'o': ['ca sĩ', 'viết truyện', 'tại sao', 'giáo viên (dạy Tiếng Anh)'],
                                   'plain': True,
                                   'q': 'Unit 8 – “why” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.91',
                                   'o': ['thể thao', 'trò chơi', 'khác nhau', 'ngày hội thể thao'],
                                   'plain': True,
                                   'q': 'Unit 9 – “sports day” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.92',
                                   'o': ['ngày hội thể thao', 'thể thao', 'trò chơi', 'khác nhau'],
                                   'plain': True,
                                   'q': 'Unit 9 – “sports” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.93',
                                   'o': ['thể thao', 'trò chơi', 'ngày hội thể thao', 'khác nhau'],
                                   'plain': True,
                                   'q': 'Unit 9 – “games” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.94',
                                   'o': ['trò chơi', 'khác nhau', 'thể thao', 'ngày hội thể thao'],
                                   'plain': True,
                                   'q': 'Unit 9 – “different” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.95',
                                   'o': ['bãi biển', 'Xít-ni (thành phố của nước Úc)', 'To-ky-o ( thủ đô nước Nhật)', 'trước, lần trước'],
                                   'plain': True,
                                   'q': 'Unit 10 – “beach” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.96',
                                   'o': ['To-ky-o ( thủ đô nước Nhật)', 'trước, lần trước', 'Băng Cốc (thủ đô của nước Thái Lan)', 'nông thôn, vùng quê'],
                                   'plain': True,
                                   'q': 'Unit 10 – “Bangkok” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.97',
                                   'o': ['bãi biển', 'địa điểm cắm trại', 'To-ky-o ( thủ đô nước Nhật)', 'trước, lần trước'],
                                   'plain': True,
                                   'q': 'Unit 10 – “campsite” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.98',
                                   'o': ['Xít-ni (thành phố của nước Úc)', 'địa điểm cắm trại', 'trước, lần trước', 'nông thôn, vùng quê'],
                                   'plain': True,
                                   'q': 'Unit 10 – “Sydney” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.99',
                                   'o': ['Luân đôn (thủ đô nước Anh)', 'Băng Cốc (thủ đô của nước Thái Lan)', 'nông thôn, vùng quê', 'bãi biển'],
                                   'plain': True,
                                   'q': 'Unit 10 – “countryside” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.100',
                                   'o': ['bãi biển', 'To-ky-o ( thủ đô nước Nhật)', 'địa điểm cắm trại', 'Luân đôn (thủ đô nước Anh)'],
                                   'plain': True,
                                   'q': 'Unit 10 – “Tokyo” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.101',
                                   'o': ['trước, lần trước', 'bãi biển', 'To-ky-o ( thủ đô nước Nhật)', 'Băng Cốc (thủ đô của nước Thái Lan)'],
                                   'plain': True,
                                   'q': 'Unit 10 – “last” nghĩa là gì?',
                                   't': 'mcq'},
                                  {'id': 'v3.102',
                                   'o': ['Luân đôn (thủ đô nước Anh)',
                                         'To-ky-o ( thủ đô nước Nhật)',
                                         'trước, lần trước',
                                         'Băng Cốc (thủ đô của nước Thái Lan)'],
                                   'plain': True,
                                   'q': 'Unit 10 – “London” nghĩa là gì?',
                                   't': 'mcq'}]}],
            'id': 'tu-vung-3',
            'mode': 'practice',
            'title': 'Từ vựng Unit 6–10'},
           {'groups': [{'id': 'mc',
                        'instr': 'Chọn câu trả lời phù hợp với câu hỏi. (20 mẫu câu Unit 1–10)',
                        'items': [{'id': 'mc.103',
                                   'o': ['He’s/ She’s from Britain.', 'There are two./ There is one.', 'I have English and maths.', 'I’m from Viet Nam.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Where are you from?”',
                                   't': 'mcq'},
                                  {'id': 'mc.104',
                                   'o': ['I was in London.', 'It’s art.', 'He’s/ She’s from Britain.', 'It’s in September.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Where’s he/ she from?”',
                                   't': 'mcq'},
                                  {'id': 'mc.105',
                                   'o': ['Because I want to be a painter.',
                                         'Yes, she can./ No, she can’t.',
                                         'I have it on Tuesdays and Fridays.',
                                         'It’s six thirty.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “What time is it?”',
                                   't': 'mcq'},
                                  {'id': 'mc.106',
                                   'o': ['It’s in the village.', 'I get up at five forty-five.', 'Yes, I can/ No, I can’t.', 'It’s six thirty.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “What time do you get up?”',
                                   't': 'mcq'},
                                  {'id': 'mc.107',
                                   'o': ['It’s in May.', 'I was in London.', 'Yes, I was./ No, I wasn’t.', 'Yes, it is./ No, it isn’t.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “When’s your birthday?”',
                                   't': 'mcq'},
                                  {'id': 'mc.108',
                                   'o': ['I have it on Tuesdays and Fridays.', 'Yes, it is./ No, it isn’t.', 'I want some jam.', 'He’s/ She’s from Britain.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “What do you want to eat?”',
                                   't': 'mcq'},
                                  {'id': 'mc.109',
                                   'o': ['Yes, she can./ No, she can’t.', 'I have English and maths.', 'I want some lemonade.', 'Yes, it is./ No, it isn’t.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “What do you want to drink?”',
                                   't': 'mcq'},
                                  {'id': 'mc.110',
                                   'o': ['He’s/ She’s from Britain.', 'Yes, I can/ No, I can’t.', 'I’m from Viet Nam.', 'I was in London.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Can you play the guitar?”',
                                   't': 'mcq'},
                                  {'id': 'mc.111',
                                   'o': ['Yes, he can./ No, he can’t.', 'I get up at five forty-five.', 'It’s six thirty.', 'He’s/ She’s from Britain.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Can he ride a bike?”',
                                   't': 'mcq'},
                                  {'id': 'mc.112',
                                   'o': ['It’s in May.', 'Yes, she can./ No, she can’t.', 'Yes, it is./ No, it isn’t.', 'I was in London.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Can she draw a picture?”',
                                   't': 'mcq'},
                                  {'id': 'mc.113',
                                   'o': ['Yes, he can./ No, he can’t.', 'It’s in the village.', 'It’s in May.', 'I have English and maths.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Where’s your school?”',
                                   't': 'mcq'},
                                  {'id': 'mc.114',
                                   'o': ['Yes, she can./ No, she can’t.',
                                         'I have English and maths.',
                                         'There are two./ There is one.',
                                         'Yes, it is./ No, it isn’t.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “How many gardens are there at your school?”',
                                   't': 'mcq'},
                                  {'id': 'mc.115',
                                   'o': ['I have English and maths.', 'There are two./ There is one.', 'Because I want to be a painter.', 'I’m from Viet Nam.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “What subjects do you have today?”',
                                   't': 'mcq'},
                                  {'id': 'mc.116',
                                   'o': ['I want some lemonade.', 'There are two./ There is one.', 'I want some jam.', 'I have it on Tuesdays and Fridays.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “When do you have maths?”',
                                   't': 'mcq'},
                                  {'id': 'mc.117',
                                   'o': ['I have it on Tuesdays and Fridays.', 'I get up at five forty-five.', 'Yes, he can./ No, he can’t.', 'It’s art.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “What’s your favourite subject?”',
                                   't': 'mcq'},
                                  {'id': 'mc.118',
                                   'o': ['Because I want to be a painter.', 'I’m from Viet Nam.', 'I have it on Tuesdays and Fridays.', 'It’s in September.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Why do you like art?”',
                                   't': 'mcq'},
                                  {'id': 'mc.119',
                                   'o': ['Yes, it is./ No, it isn’t.', 'Yes, I can/ No, I can’t.', 'There are two./ There is one.', 'It’s in September.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Is your sports day in July?”',
                                   't': 'mcq'},
                                  {'id': 'mc.120',
                                   'o': ['It’s art.', 'It’s in September.', 'Because I want to be a painter.', 'Yes, she can./ No, she can’t.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “When’s your sports day?”',
                                   't': 'mcq'},
                                  {'id': 'mc.121',
                                   'o': ['Yes, I was./ No, I wasn’t.', 'It’s art.', 'It’s six thirty.', 'I get up at five forty-five.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Were you at the zoo last weekend?”',
                                   't': 'mcq'},
                                  {'id': 'mc.122',
                                   'o': ['Yes, it is./ No, it isn’t.', 'It’s in the village.', 'I have it on Tuesdays and Fridays.', 'I was in London.'],
                                   'plain': True,
                                   'q': 'Chọn câu trả lời phù hợp: “Where were you last summer?”',
                                   't': 'mcq'}]}],
            'id': 'mau-cau',
            'mode': 'practice',
            'title': 'Mẫu câu hỏi – đáp'},
           {'groups': [{'id': 'c1',
                        'instr': 'Look, read and circle the correct answer. (Nhìn tranh, đọc và chọn đáp án đúng.)',
                        'items': [{'id': 'c1.123',
                                   'img': 'c1_1.png',
                                   'o': ['Viet Nam', 'Japan', 'Thailand'],
                                   'q': 'A: Where are you from?<br>B: I’m from ………….',
                                   't': 'mcq'},
                                  {'id': 'c1.124',
                                   'img': 'c1_2.png',
                                   'o': ['Malaysia', 'Singapore', 'Japan'],
                                   'q': 'A: Where is he from?<br>B: He’s from ………….',
                                   't': 'mcq'},
                                  {'id': 'c1.125',
                                   'img': 'c1_3.png',
                                   'o': ['Maths', 'Art', 'English'],
                                   'q': 'A: What subjects do you have today?<br>B: I have ………….',
                                   't': 'mcq'},
                                  {'id': 'c1.126',
                                   'img': 'c1_4.png',
                                   'o': ['ride a bike', 'swim', 'ride a horse'],
                                   'q': 'A: Can you ………….?<br>B: Yes, I can.',
                                   't': 'mcq'},
                                  {'id': 'c1.127',
                                   'img': 'c1_5.png',
                                   'o': ['cook', 'do homework', 'study at school'],
                                   'q': 'A: What do you do on Mondays?<br>B: I ………….',
                                   't': 'mcq'},
                                  {'id': 'c1.128',
                                   'img': 'c1_6.png',
                                   'o': ['six fifteen', 'six thirty', 'six forty-five'],
                                   'q': 'A: What time is it?<br>B: It’s ………….',
                                   't': 'mcq'},
                                  {'id': 'c1.129',
                                   'img': 'c1_7.png',
                                   'o': ['music teacher', 'singer', 'painter'],
                                   'q': 'A: Why do you like Music?<br>B: Because I want to be a(n) ………….',
                                   't': 'mcq'},
                                  {'id': 'c1.130',
                                   'img': 'c1_8.png',
                                   'o': ['playground', 'buildings', 'gardens'],
                                   'q': 'There are three ………….. at my school.',
                                   't': 'mcq'},
                                  {'id': 'c1.131',
                                   'img': 'c1_9.png',
                                   'o': ['January', 'December', 'November'],
                                   'q': 'A: When’s your birthday?<br>B: It’s in …………',
                                   't': 'mcq'}]}],
            'id': 'nhin-tranh-chon',
            'mode': 'practice',
            'title': 'Nhìn tranh, chọn đáp án'},
           {'groups': [{'bank': ['Ben', 'birthday', 'go to school', 'Australia', 'chicken'],
                        'id': 'c2a',
                        'instr': 'Read and complete. (Đoạn 1 – chọn từ trong khung điền vào chỗ trống; từ ở (0) là ví dụ.)',
                        'items': [{'id': 'c2a.132', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'c2a.133', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'c2a.134', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'c2a.135', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>My name is (0) <u>Ben</u>. I am from <b>(1) ______</b>. I <b>(2) ______</b> from Mondays to Fridays. I do housework on '
                                   'Saturdays. I like cooking. I can cook rice, <b>(3) ______</b> and eggs. My <b>(4) ______</b> is in April. I want a big '
                                   'cake at my birthday party.</p>'},
                       {'bank': ['flowers', 'unit', 'sing', 'listen', 'sunny'],
                        'id': 'c2b',
                        'instr': 'Read and complete. (Đoạn 2 – chọn từ trong khung điền vào chỗ trống; từ ở (0) là ví dụ.)',
                        'items': [{'id': 'c2b.136', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'c2b.137', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'c2b.138', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'c2b.139', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>We have a lot of fun at school. In our English lessons, we (0) <u>listen</u> to English songs. We <b>(1) ______</b> and '
                                   'chant. We play board games to learn English. We do projects together at the end of each <b>(2) ______</b>. Today, it is '
                                   '<b>(3) ______</b>. We are in the school garden. There are many <b>(4) ______</b> and birds. We are happy.</p>'},
                       {'bank': ['activities', 'village', 'piano', 'classrooms', 'subject'],
                        'id': 'c2c',
                        'instr': 'Read and complete. (Đoạn 3 – chọn từ trong khung điền vào chỗ trống; từ ở (0) là ví dụ.)',
                        'items': [{'id': 'c2c.140', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'c2c.141', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'c2c.142', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'c2c.143', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>My name is Trung. I study at ….. Primary School. My school is in the (0) <u>village</u>. There are twenty <b>(1) '
                                   '______</b>, two computer rooms and a beautiful garden. My favourite <b>(2) ______</b> is Music. I can play the <b>(3) '
                                   '______</b> and sing with my friends. It is our sports day today. The <b>(4) ______</b> there are fun. It is very great. '
                                   'How about your school?</p>'},
                       {'bank': ['Australia', 'stay at home', 'Fridays', 'pupil', 'play football'],
                        'id': 'c2d',
                        'instr': 'Read and complete. (Đoạn 4 – chọn từ trong khung điền vào chỗ trống; từ ở (0) là ví dụ.)',
                        'items': [{'id': 'c2d.144', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'c2d.145', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'c2d.146', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'c2d.147', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>My name is Ben. I am nine years old. I am from (0) <u>Australia</u>. I am a <b>(1) ______</b> at Rose Primary School. I '
                                   'go to school from Mondays to <b>(2) ______</b>. I like sports and music. I <b>(3) ______</b> on Tuesdays. I play the '
                                   'guitar on Wednesdays. At the weekend, I <b>(4) ______</b> and do housework with my mother.</p>'}],
            'id': 'doc-dien-tu',
            'mode': 'practice',
            'title': 'Đọc và điền từ'},
           {'groups': [{'id': 'c3a',
                        'instr': 'Read and match. (Nối mỗi câu với tranh phù hợp a–i.)',
                        'items': [{'id': 'c3a.148',
                                   'left': [{'t': 'That’s Mr Long.'},
                                            {'t': 'Our Sports Day is in July.'},
                                            {'t': 'I go to school at one fifteen.'},
                                            {'t': 'I want some grapes at my birthday party.'},
                                            {'t': 'My school is in the village.'},
                                            {'t': 'She is from Japan.'},
                                            {'t': 'Today is Thursday.'},
                                            {'t': 'He can’t play badminton but he can roller skate.'},
                                            {'t': 'I have science on Wednesdays and Fridays.'}],
                                   'o': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_dc1_a/match_pics.png" alt="Tranh a–i">'},
                       {'id': 'c3b',
                        'instr': 'Read and match. (Nối câu hỏi với câu trả lời phù hợp.)',
                        'items': [{'id': 'c3b.149',
                                   'left': [{'t': 'What time is it?'},
                                            {'t': 'What time do you have music class?'},
                                            {'t': 'When’s your birthday?'},
                                            {'t': 'What do you do on Sundays?'},
                                            {'t': 'What subjects do you have today?'},
                                            {'t': 'What do you do on sports day?'},
                                            {'t': 'Where’s she from?'},
                                            {'t': 'Can your brother ride a bike?'},
                                            {'t': 'What do you want to drink?'}],
                                   'o': ['I have music class at eight fifteen.',
                                         'She’s from Singapore.',
                                         'No, he can’t.',
                                         'I have maths and Vietnamese.',
                                         'It’s six thirty.',
                                         'I want some milk and juice.',
                                         'I stay at home.',
                                         'It’s in October.',
                                         'We play sports and games.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]}],
            'id': 'doc-noi',
            'mode': 'practice',
            'title': 'Đọc và nối'},
           {'groups': [{'id': 'c4',
                        'instr': 'Order the words to make a complete sentence. (Sắp xếp từ thành câu đúng.)',
                        'items': [{'id': 'c4.150', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Day', 'is', 'in', 'Our', 'July.', 'Sports']},
                                  {'id': 'c4.151',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['music', 'There', 'my', 'school.', 'three', 'are', 'rooms', 'at']},
                                  {'id': 'c4.152',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['I', 'birthday', 'party.', 'grapes', 'at', 'want', 'my', 'some']},
                                  {'id': 'c4.153', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'favourite', 'English.', 'subject', 'My']},
                                  {'id': 'c4.154',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['his', 'subject.', 'is', 'favourite', 'not', 'Music']},
                                  {'id': 'c4.155',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['day.', 'Sports', 'play', 'on', 'They', 'basketball']},
                                  {'id': 'c4.156', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['weekend.', 'do', 'housework', 'the', 'We', 'at']},
                                  {'id': 'c4.157',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['at', 'school.', 'is', 'There', 'my', 'building', 'one']},
                                  {'id': 'c4.158',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['like', 'I', 'an', 'want', 'because', 'teacher.', 'be', 'English', 'I', 'English', 'to']},
                                  {'id': 'c4.159',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['he', 'but', 'can’t', 'ride', 'a', 'brother', 'roller', 'horse', 'can', 'skate.', 'My']},
                                  {'id': 'c4.160',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['sing.', 'but', 'can’t', 'play', 'My', 'sister', 'can', 'she', 'piano', 'the']},
                                  {'id': 'c4.161',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['have', 'dinner', 'parents', 'o’clock.', 'at', 'seven', 'My']},
                                  {'id': 'c4.162',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['to', 'Mondays', 'Fridays.', 'We', 'from', 'school', 'go', 'to']}]}],
            'id': 'sap-xep-tu',
            'mode': 'practice',
            'title': 'Sắp xếp từ thành câu'},
           {'groups': [{'id': 'c5',
                        'instr': 'Look at the picture and complete the sentences. (Nhìn tranh và hoàn thành câu.)',
                        'items': [{'id': 'c5.163', 'img': 'c5_1.png', 'q': 'I want some {_} at the party.', 't': 'fill'},
                                  {'id': 'c5.164', 'img': 'c5_2.png', 'q': 'I {_} at school on Friday.', 't': 'fill'},
                                  {'id': 'c5.165', 'img': 'c5_3.png', 'q': 'My brother can play the {_}.', 't': 'fill'},
                                  {'id': 'c5.166', 'img': 'c5_4.png', 'q': 'I have {_} on Mondays.', 't': 'fill'},
                                  {'id': 'c5.167', 'img': 'c5_5.png', 'q': 'My school is in the {_}.', 't': 'fill'},
                                  {'id': 'c5.168', 'img': 'c5_6.png', 'q': 'Lucy is from {_}.', 't': 'fill'},
                                  {'id': 'c5.169', 'img': 'c5_7.png', 'q': 'I have breakfast at six {_}.', 't': 'fill'},
                                  {'id': 'c5.170', 'img': 'c5_8.png', 'q': 'There is one {_} at my school.', 't': 'fill'},
                                  {'id': 'c5.171', 'img': 'c5_9.png', 'q': 'He is from {_}.', 't': 'fill'},
                                  {'id': 'c5.172', 'img': 'c5_10.png', 'q': 'I have {_} today.', 't': 'fill'},
                                  {'id': 'c5.173', 'img': 'c5_11.png', 'q': 'My birthday is in {_}.', 't': 'fill'},
                                  {'id': 'c5.174', 'img': 'c5_12.png', 'q': 'There is a {_}.', 't': 'fill'},
                                  {'id': 'c5.175', 'img': 'c5_13.png', 'q': 'I like art because I want to be a(n) {_}.', 't': 'fill'},
                                  {'id': 'c5.176', 'img': 'c5_14.png', 'q': 'I have {_} at six o’clock.', 't': 'fill'},
                                  {'id': 'c5.177', 'img': 'c5_15.png', 'q': 'My birthday is in {_}.', 't': 'fill'},
                                  {'id': 'c5.178', 'img': 'c5_16.png', 'q': 'I stay at home on {_}.', 't': 'fill'},
                                  {'id': 'c5.179', 'img': 'c5_17.png', 'q': 'I have music on {_}.', 't': 'fill'},
                                  {'id': 'c5.180', 'img': 'c5_18.png', 'q': 'My school is in the {_}.', 't': 'fill'}]}],
            'id': 'nhin-tranh-dien',
            'mode': 'practice',
            'title': 'Nhìn tranh, hoàn thành câu'}],
 'theory': '<h3>Đề cương ôn tập môn Tiếng Anh 4 – Học kì 1 (năm học 2024-2025)</h3><p>Nội dung: ôn tập từ vựng, mẫu câu, các điểm ngữ pháp và các bài nghe từ '
           'Unit 1 đến Unit 10. Bài kiểm tra gồm các kĩ năng nghe, nói, đọc, viết.</p><h3>Dạng câu hỏi thường gặp</h3><ul><li><b>Listening:</b> listen and '
           'number / tick / complete / match.</li><li><b>Reading:</b> look, read and complete; choose the correct answer; read and match; read and tick the '
           'correct picture.</li><li><b>Writing:</b> put the words in order; look at the picture and complete the sentences; write the missing '
           'letter.</li></ul><h3>Từ vựng Unit 1 – 10</h3><h4>Unit 1: My friends</h4><table '
           'class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>America</b></td><td>nước '
           'Mỹ</td><td><b>Malaysia</b></td><td>nước Ma-lay-xi-a</td></tr><tr><td><b>Australia</b></td><td>nước Úc</td><td><b>Singapore</b></td><td>nước '
           'Xin-ga-po</td></tr><tr><td><b>Britain</b></td><td>nước Anh</td><td><b>Thailand</b></td><td>nước Thái '
           'Lan</td></tr><tr><td><b>Japan</b></td><td>nước Nhật</td><td><b>Viet Nam</b></td><td>nước Việt Nam</td></tr></table><h4>Unit 2: Time and daily '
           'routines</h4><table class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>fifteen</b></td><td>số '
           '15</td><td><b>get up</b></td><td>thức dậy</td></tr><tr><td><b>forty-five</b></td><td>số 45</td><td><b>go to bed</b></td><td>đi '
           'ngủ</td></tr><tr><td><b>o’clock</b></td><td>giờ đúng</td><td><b>go to school</b></td><td>đi học</td></tr><tr><td><b>thirty</b></td><td>số '
           '30</td><td><b>have breakfast</b></td><td>ăn sáng</td></tr><tr><td><b>do homework</b></td><td>làm bài tập về nhà</td><td><b>have '
           'lunch</b></td><td>ăn trưa</td></tr><tr><td><b>chat with friends</b></td><td>trò chuyện cùng bạn</td><td><b>have dinner</b></td><td>ăn '
           'tối</td></tr></table><h4>Unit 3: My week</h4><table '
           'class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>Monday</b></td><td>Thứ 2</td><td><b>listen to '
           'music</b></td><td>nghe nhạc</td></tr><tr><td><b>Tuesday</b></td><td>Thứ 3</td><td><b>do housework</b></td><td>làm việc '
           'nhà</td></tr><tr><td><b>Wednesday</b></td><td>Thứ 4</td><td><b>study at school</b></td><td>học ở '
           'trường</td></tr><tr><td><b>Thursday</b></td><td>Thứ 5</td><td><b>stay at home</b></td><td>ở nhà</td></tr><tr><td><b>Friday</b></td><td>Thứ '
           '6</td><td><b>at the weekend</b></td><td>cuối tuần</td></tr><tr><td><b>Saturday</b></td><td>Thứ 7</td><td><b>watch TV</b></td><td>xem ti '
           'vi</td></tr><tr><td><b>Sunday</b></td><td>Chủ nhật</td><td><b>today</b></td><td>hôm nay</td></tr></table><h4>Unit 4: My birthday party</h4><table '
           'class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>January</b></td><td>Tháng '
           '1</td><td><b>June</b></td><td>Tháng 6</td></tr><tr><td><b>February</b></td><td>Tháng 2</td><td><b>July</b></td><td>Tháng '
           '7</td></tr><tr><td><b>March</b></td><td>Tháng 3</td><td><b>August</b></td><td>Tháng 8</td></tr><tr><td><b>April</b></td><td>Tháng '
           '4</td><td><b>September</b></td><td>Tháng 9</td></tr><tr><td><b>May</b></td><td>Tháng 5</td><td><b>October</b></td><td>Tháng '
           '10</td></tr><tr><td><b>birthday</b></td><td>ngày sinh</td><td><b>November</b></td><td>Tháng 11</td></tr><tr><td><b>grape</b></td><td>quả '
           'nho</td><td><b>December</b></td><td>Tháng 12</td></tr><tr><td><b>jam</b></td><td>mứt</td><td><b>lemonade</b></td><td>nước '
           'chanh</td></tr><tr><td><b>juice</b></td><td>nước ép</td><td><b>party</b></td><td>buổi tiệc</td></tr><tr><td><b>chip</b></td><td>Khoai tây '
           'chiên</td><td><b>water</b></td><td>nước</td></tr></table><h4>Unit 5: Things we can do</h4><table '
           'class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>can</b></td><td>có thể, biết (làm '
           'gì)</td><td><b>ride a horse</b></td><td>cưỡi ngựa</td></tr><tr><td><b>cook</b></td><td>nấu ăn</td><td><b>roller skate</b></td><td>trượt pa '
           'tin</td></tr><tr><td><b>play the piano</b></td><td>chơi đàn piano</td><td><b>swim</b></td><td>bơi lội</td></tr><tr><td><b>play the '
           'guitar</b></td><td>chơi đàn ghi ta</td><td><b>but</b></td><td>nhưng</td></tr><tr><td><b>ride a bike</b></td><td>đạp xe</td><td><b>draw a '
           'picture</b></td><td>vẽ tranh</td></tr></table><h4>Unit 6: Our school facilities</h4><table '
           'class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>in the city</b></td><td>ở thành '
           'phố</td><td><b>garden</b></td><td>khu vườn</td></tr><tr><td><b>in the mountains</b></td><td>ở vùng núi</td><td><b>playground</b></td><td>sân '
           'chơi</td></tr><tr><td><b>in the town</b></td><td>ở thị trấn</td><td><b>building</b></td><td>Tòa nhà</td></tr><tr><td><b>in the '
           'village</b></td><td>ở làng quê</td><td><b>computer room</b></td><td>phòng tin học</td></tr></table><h4>Unit 7: Our timetables</h4><table '
           'class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>art</b></td><td>môn Mĩ '
           'thuật</td><td><b>music</b></td><td>môn Âm nhạc</td></tr><tr><td><b>English</b></td><td>môn Tiếng Anh</td><td><b>science</b></td><td>môn Khoa '
           'học</td></tr><tr><td><b>history and geography</b></td><td>môn Lịch sử và Địa lí</td><td><b>Vietnamese</b></td><td>môn Tiếng '
           'Việt</td></tr><tr><td><b>maths</b></td><td>môn Toán, toán học</td><td><b>IT</b></td><td>môn Tin học</td></tr><tr><td><b>subject</b></td><td>môn '
           'học</td><td><b>PE</b></td><td>môn thể dục</td></tr></table><h4>Unit 8: My favourite subjects</h4><table '
           'class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>English teacher</b></td><td>giáo viên (dạy '
           'Tiếng Anh)</td><td><b>painter</b></td><td>họa sĩ</td></tr><tr><td><b>maths teacher</b></td><td>giáo viên (dạy '
           'Toán)</td><td><b>singer</b></td><td>ca sĩ</td></tr><tr><td><b>favourite</b></td><td>yêu thích</td><td><b>because</b></td><td>bởi '
           'vì</td></tr><tr><td><b>write a story</b></td><td>viết truyện</td><td><b>why</b></td><td>tại sao</td></tr></table><h4>Unit 9: Our sports '
           'day</h4><table class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>sports day</b></td><td>ngày '
           'hội thể thao</td><td><b>sports</b></td><td>thể thao</td></tr><tr><td><b>games</b></td><td>trò chơi</td><td><b>different</b></td><td>khác '
           'nhau</td></tr></table><h4>Unit 10: Our summer holidays</h4><table '
           'class="tb"><tr><th>Vocabulary</th><th>Meaning</th><th>Vocabulary</th><th>Meaning</th></tr><tr><td><b>beach</b></td><td>bãi '
           'biển</td><td><b>Bangkok</b></td><td>Băng Cốc (thủ đô của nước Thái Lan)</td></tr><tr><td><b>campsite</b></td><td>địa điểm cắm '
           'trại</td><td><b>Sydney</b></td><td>Xít-ni (thành phố của nước Úc)</td></tr><tr><td><b>countryside</b></td><td>nông thôn, vùng '
           'quê</td><td><b>Tokyo</b></td><td>To-ky-o ( thủ đô nước Nhật)</td></tr><tr><td><b>last</b></td><td>trước, lần '
           'trước</td><td><b>London</b></td><td>Luân đôn (thủ đô nước Anh)</td></tr></table><h3>Cấu trúc câu từ Unit 1 đến Unit 10</h3><p><b>Unit 1 – My '
           'friends</b></p><ul><li>Hỏi và trả lời ai đó đến từ đâu?</li><li>Where are you from?</li><li>I’m from Viet Nam</li></ul><p><b>Unit 2 – Time and '
           'daily routines</b></p><ul><li>Hỏi giờ?</li><li>Hỏi xem ai đó làm gì lúc mấy giờ?</li></ul><p><b>Unit 3 – My week</b></p><ul><li>Hỏi về các ngày '
           'trong tuần?</li><li>Hỏi xem ai đó làm gì vào một ngày nào đó trong tuần</li></ul><p><b>Unit 4 – My birthday party</b></p><ul><li>Hỏi xem sinh nhật '
           'ai đó vào khi nào?</li><li>Hỏi xem ai đó muốn ăn/ uống gì?</li></ul><p><b>Unit 5 – Things we can do</b></p><ul><li>Hỏi về khả năng làm gì của ai '
           'đó</li></ul><p><b>Unit 6 – Our school facilities</b></p><ul><li>Hỏi vị trí của trường học</li><li>Hỏi số lượng của danh từ đếm được trong trường '
           'học.</li></ul><p><b>Unit 7 – Our timetables</b></p><ul><li>Hỏi thời khoá biểu môn học của ngày nào đó?</li><li>Hỏi khi nào có môn gì '
           'đó?</li></ul><p><b>Unit 8 – My favourite subjects</b></p><ul><li>Hỏi và trả lời về môn học yêu thích của ai đó?</li><li>Hỏi và trả lời về lí do '
           'thích môn học nào đó?</li></ul><p><b>Unit 9 – Our sports day</b></p><ul><li>Hỏi về trả lời về thời gian diễn ra ngày hội thể '
           'thao</li></ul><p><b>Unit 10 – Our summer holidays</b></p><ul><li>Thì quá khứ đơn: Hỏi xem ai đó đã ở đâu tại một thời điểm trong quá '
           'khứ</li></ul><h3>20 mẫu câu hỏi – trả lời</h3><table class="tb"><tr><th>Hỏi</th><th>Trả lời</th></tr><tr><td>Where are you from?</td><td>I’m from '
           'Viet Nam.</td></tr><tr><td>Where’s he/ she from?</td><td>He’s/ She’s from Britain.</td></tr><tr><td>What time is it?</td><td>It’s six '
           'thirty.</td></tr><tr><td>What time do you get up?</td><td>I get up at five forty-five.</td></tr><tr><td>When’s your birthday?</td><td>It’s in '
           'May.</td></tr><tr><td>What do you want to eat?</td><td>I want some jam.</td></tr><tr><td>What do you want to drink?</td><td>I want some '
           'lemonade.</td></tr><tr><td>Can you play the guitar?</td><td>Yes, I can/ No, I can’t.</td></tr><tr><td>Can he ride a bike?</td><td>Yes, he can./ '
           'No, he can’t.</td></tr><tr><td>Can she draw a picture?</td><td>Yes, she can./ No, she can’t.</td></tr><tr><td>Where’s your school?</td><td>It’s in '
           'the village.</td></tr><tr><td>How many gardens are there at your school?</td><td>There are two./ There is one.</td></tr><tr><td>What subjects do '
           'you have today?</td><td>I have English and maths.</td></tr><tr><td>When do you have maths?</td><td>I have it on Tuesdays and '
           'Fridays.</td></tr><tr><td>What’s your favourite subject?</td><td>It’s art.</td></tr><tr><td>Why do you like art?</td><td>Because I want to be a '
           'painter.</td></tr><tr><td>Is your sports day in July?</td><td>Yes, it is./ No, it isn’t.</td></tr><tr><td>When’s your sports day?</td><td>It’s in '
           'September.</td></tr><tr><td>Were you at the zoo last weekend?</td><td>Yes, I was./ No, I wasn’t.</td></tr><tr><td>Where were you last '
           'summer?</td><td>I was in London.</td></tr></table>',
 'title': 'Đề cương HK1 (2024-25)',
 'unit': 'DeCuongHK1'}
