# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['What does your mother do?'],
 't1.10': 'do',
 't1.11': ['What does your brother look like?'],
 't1.12': "She's slim.",
 't1.13': 'your aunt',
 't1.14': ['My sister is slim and has long hair.'],
 't1.15': 'In the evening.',
 't1.16': 'clean',
 't1.17': ['When do you do the housework?'],
 't1.18': 'What does Lan do in the evening?',
 't1.19': 'does',
 't1.2': 'What does Nam do?',
 't1.20': ['Ben washes his clothes in the evening.'],
 't1.3': 'on a farm',
 't1.4': 'He watches TV in the evening.',
 't1.5': 'go',
 't1.6': ['My sister teaches at a primary school.'],
 't1.7': 'What does Mai look like?',
 't1.8': 'What',
 't1.9': 'She goes to the sports centre.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: What does your mother do?',
 't1.10': 'Đáp án: do',
 't1.11': 'Câu đúng: What does your brother look like?',
 't1.12': "Đáp án: She's slim.",
 't1.13': 'Đáp án: your aunt',
 't1.14': 'Câu đúng: My sister is slim and has long hair.',
 't1.15': 'Đáp án: In the evening.',
 't1.16': 'Đáp án: clean',
 't1.17': 'Câu đúng: When do you do the housework?',
 't1.18': 'Đáp án: What does Lan do in the evening?',
 't1.19': 'Đáp án: does',
 't1.2': 'Đáp án: What does Nam do?',
 't1.20': 'Câu đúng: Ben washes his clothes in the evening.',
 't1.3': 'Đáp án: on a farm',
 't1.4': 'Đáp án: He watches TV in the evening.',
 't1.5': 'Đáp án: go',
 't1.6': 'Câu đúng: My sister teaches at a primary school.',
 't1.7': 'Đáp án: What does Mai look like?',
 't1.8': 'Đáp án: What',
 't1.9': 'Đáp án: She goes to the sports centre.'}
