# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on1-de9',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'q1',
                        'instr': 'Listen and number (nghe và đánh số)',
                        'items': [{'id': 'q1.1', 'o': ['Tranh a', 'Tranh b', 'Tranh c'], 'q': 'Number 1:', 't': 'mcq'},
                                  {'id': 'q1.2', 'o': ['Tranh a', 'Tranh b', 'Tranh c'], 'q': 'Number 2:', 't': 'mcq'},
                                  {'id': 'q1.3', 'o': ['Tranh a', 'Tranh b', 'Tranh c'], 'q': 'Number 3:', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de9/p1.png" alt="Hình">'},
                       {'id': 'q2',
                        'instr': 'Listen and tick (nghe và chọn tranh)',
                        'items': [{'id': 'q2.4', 'o': ['Tranh a', 'Tranh b'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q2.5', 'o': ['Tranh a', 'Tranh b'], 'q': 'Nghe câu số 2.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de9/p2.png" alt="Hình">'},
                       {'id': 'q3',
                        'instr': 'Listen and number (nghe và đánh số)',
                        'items': [{'id': 'q3.6', 'o': ['Tranh d', 'Tranh a', 'Tranh c', 'Tranh b'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q3.7', 'o': ['Tranh d', 'Tranh c', 'Tranh b', 'Tranh a'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q3.8', 'o': ['Tranh d', 'Tranh c', 'Tranh b', 'Tranh a'], 'q': 'Nghe câu số 3.', 't': 'mcq'},
                                  {'id': 'q3.9', 'o': ['Tranh b', 'Tranh a', 'Tranh d', 'Tranh c'], 'q': 'Nghe câu số 4.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_on1_de9/p3.png" alt="Hình">'},
                       {'id': 'q4',
                        'instr': 'Reorder words (sắp xếp từ thành câu)',
                        'items': [{'id': 'q4.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['When’s', 'day?', 'your', 'sports']},
                                  {'id': 'q4.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['you', 'were', 'summer?', 'Where', 'last']},
                                  {'id': 'q4.12', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['subject?', 'your', 'What’s', 'favourite']},
                                  {'id': 'q4.13', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'Where’s', 'school?']},
                                  {'id': 'q4.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Can', 'badminton?', 'Linh', 'play']},
                                  {'id': 'q4.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'Thursdays?', 'you', 'on', 'What', 'do']},
                                  {'id': 'q4.16', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'What', 'you', 'time', 'up?', 'get']},
                                  {'id': 'q4.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Where', 'are', 'from?', 'you']},
                                  {'id': 'q4.18', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['have', 'you', 'time', 'do', 'breakfast?', 'What']},
                                  {'id': 'q4.19', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['skate?', 'Can', 'he', 'roller']}]},
                       {'id': 'q5',
                        'instr': 'Choose the best option (chọn đáp án đúng)',
                        'items': [{'id': 'q5.20', 'o': ["Where's", 'When', 'When’s', 'What'], 'q': '_____ your sports day?', 't': 'mcq'},
                                  {'id': 'q5.21', 'o': ['last', 'next year', 'tomorrow', 'next'], 'q': 'Where were you _______ summer?', 't': 'mcq'},
                                  {'id': 'q5.22', 'o': ['love', 'like', 'enjoy', 'favourite'], 'q': 'What’s your ______ subject?', 't': 'mcq'},
                                  {'id': 'q5.23',
                                   'o': ["Yes, She can't.", "No, I can't.", 'Yes, I can.', 'Yes, She can.'],
                                   'q': 'Can Linh play badminton?',
                                   't': 'mcq'},
                                  {'id': 'q5.24', 'o': ['of', 'on', 'in', 'at'], 'q': 'What do you do ____ Thursdays?', 't': 'mcq'},
                                  {'id': 'q5.25', 'o': ['day', 'week', 'times', 'time'], 'q': 'What ______ do you get up?', 't': 'mcq'},
                                  {'id': 'q5.26', 'o': ['had', 'have', 'has', 'do'], 'q': 'What time do you ______breakfast?', 't': 'mcq'}]},
                       {'id': 'q6',
                        'instr': 'Read and decide each sentences below is T (True) or F (False) (đọc và chọn đúng/sai)',
                        'items': [{'id': 'q6.27', 'q': 'Jack and his brothers go to the beach in the winter.', 't': 'tf'},
                                  {'id': 'q6.28', 'q': "Jack is very strong but he can't swim.", 't': 'tf'},
                                  {'id': 'q6.29', 'q': 'They play beach ball or go swimming.', 't': 'tf'},
                                  {'id': 'q6.30', 'q': 'His friend is from Australia.', 't': 'tf'}],
                        'passage': '<p>This is Jack. He is my best friend. He is from Australia. He has been in Thailand for two years. He has two older '
                                   'brothers. They all live in a big house in Bangkok. Jack and his brothers go to the beach in the summer. They play beach '
                                   'ball or go swimming. Jack is very strong and he can swim fast.</p>'}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK1 – Đề 9',
 'unit': 'OnHK1'}
