# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'B',
 'l1.2': 'C',
 'l1.3': 'A',
 'l1.4': 'B',
 'l2.5': '1',
 'l2.6': '4',
 'l2.7': '2',
 'l2.8': '3',
 'l3.9': {'blanks': [['D'], ['E'], ['A'], ['C']]},
 'l4.10': ['want'],
 'l4.11': ['campsite'],
 'l4.12': ['six', '6'],
 'l4.13': ['Japan'],
 'r1.14': {'blanks': [['D'], ['A'], ['E'], ['C']]},
 'r2.15': 'B',
 'r2.16': 'A',
 'r2.17': 'C',
 'r3.18': 'F',
 'r3.19': 'F',
 'r3.20': 'T',
 'w1.21': ['water'],
 'w1.22': ['garden'],
 'w1.23': ['English'],
 'w2.24': ['What’s your favourite subject?'],
 'w2.25': ['There are two buildings at my school.'],
 'w2.26': ['What do you do on Tuesdays?']}

EXPLANATIONS = {'l1.1': 'Đáp án B: tranh đầu bếp nấu ăn (cook).',
 'l1.2': 'Đáp án C: cờ Australia.',
 'l1.3': 'Đáp án A: sách Toán 4 (Maths).',
 'l1.4': 'Đáp án B: Big Ben và cờ Anh (Britain).',
 'l2.5': 'Tranh A ứng với câu 1 (theo đáp án của đề).',
 'l2.6': 'Tranh C ứng với câu 4 (theo đáp án của đề).',
 'l2.7': 'Tranh D ứng với câu 2 (theo đáp án của đề).',
 'l2.8': 'Tranh E ứng với câu 3 (theo đáp án của đề).',
 'l3.9': 'Đáp án theo đáp án của đề: 1–D, 2–E, 3–A, 4–C',
 'l4.10': 'Đáp án: want',
 'l4.11': 'Đáp án: campsite',
 'l4.12': 'Đáp án: six',
 'l4.13': 'Đáp án: Japan',
 'r1.14': 'Đáp án: Maths teacher – D, ride a bike – A, on the beach – E, computer room – C',
 'r2.15': 'Đáp án: B. There',
 'r2.16': 'Đáp án: A. are',
 'r2.17': 'Đáp án: C. play',
 'r3.18': 'Sai: Today is Wednesday.',
 'r3.19': 'Sai: They are having an English class now.',
 'r3.20': 'Đúng: Mrs Hoa, my mother, is our English teacher.',
 'w1.21': 'Đáp án: water',
 'w1.22': 'Đáp án: garden',
 'w1.23': 'Đáp án: English',
 'w2.24': 'Câu đúng: What’s your favourite subject?',
 'w2.25': 'Câu đúng: There are two buildings at my school.',
 'w2.26': 'Câu đúng: What do you do on Tuesdays?'}
