# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-start-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ["He's flying a kite.", "I'm fine, thank you.", "She's skipping.", 'Good morning, class.', "They're painting."],
                                   'plain': True,
                                   'q': 'What are they doing?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'playing', 'badminton.', 'They']},
                                  {'id': 't1.3',
                                   'o': ['My hobby is swimming.', 'Fly it in the sky.', 'Say goodbye, please!', 'Stand up, please!'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói về hoạt động ở ngoài trời?',
                                   't': 'mcq'},
                                  {'id': 't1.4', 'o': ['down', 'up', 'aloud', 'in'], 'plain': True, 'q': 'Read ____________, please.', 't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ["He's flying a kite.", "I'm fine, thank you.", "She's skipping.", 'Good morning, class.', "They're painting."],
                                   'plain': True,
                                   'q': "What's she doing?",
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'o': ['Nice to see you!', 'Nice to meet you too!', 'See you later.', 'Very well, thank you.'],
                                   'plain': True,
                                   'q': 'Để nói “Rất vui được gặp bạn”, chúng ta nói:',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['is', 'are', 'am', 'do'], 'plain': True, 'q': 'A: What ____________ they doing?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['Chúc ngủ ngon!', 'Hẹn gặp lại bạn sau!', 'Tạm biệt!', 'Tôi cũng khỏe.'],
                                   'plain': True,
                                   'q': '“Goodbye” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.9', 'o': ['down', 'up', 'aloud', 'in'], 'plain': True, 'q': 'Jump ____________ high.', 't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['See you tonight.', 'See you tomorrow.', 'Pleased to meet you.', 'See you later.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Hẹn gặp lại bạn sau."',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'o': ['is', 'are', 'plays', 'do'], 'plain': True, 'q': 'He ____________ running.', 't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['What are you doing?', "What's your name?", 'How are you?', 'What are they doing?'],
                                   'plain': True,
                                   'q': 'Câu “I\'m fine, thank you." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['cycle', 'cycles', 'are cycling', 'is cycling'],
                                   'plain': True,
                                   'q': "A: What's she doing?",
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['What are they doing?', 'What are you doing?', 'How are you?', "What's he doing?"],
                                   'plain': True,
                                   'q': 'Câu "He\'s riding a bike." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'o': ['well', 'tomorrow', 'thank', 'meet'], 'plain': True, 'q': 'See you ____________.', 't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['Good morning.', "What's your name?", 'This is Mary.', 'See you tomorrow.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây được dùng để chào hỏi?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'o': ['is', 'are', 'do', 'am'], 'plain': True, 'q': 'How ____________ you, Mai?', 't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ["He's flying a kite.", "I'm fine, thank you.", "She's skipping.", 'Good morning, class.', "They're painting."],
                                   'plain': True,
                                   'q': 'How are you?',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['to', 'see', 'you.', 'Nice']},
                                  {'id': 't1.20',
                                   'o': ['See you later.', 'How are you?', "I'm fine, thank you.", 'Very well, thank you.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây được dùng để hỏi thăm sức khỏe?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Bài mở đầu: Kiểm tra 2',
 'unit': 'Start'}
