# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'F',
 'l1.2': 'T',
 'l1.3': 'F',
 'l1.4': 'T',
 'l2.5': 'A',
 'l2.6': 'B',
 'l2.7': 'B',
 'l2.8': 'A',
 'l3.10': ['cooks meal', 'cooks meals', 'cooks a meal'],
 'l3.11': ['bookshop'],
 'l3.12': ['go straight'],
 'l3.9': ['at noon'],
 'r1.13': 'B',
 'r1.14': 'C',
 'r1.15': 'A',
 'r1.16': 'C',
 'r2.17': {'blanks': [['Because they run quickly.'], ['She’s taking a photo.'], ['She helps my mother with the housework.']]},
 'r3.18': 'T',
 'r3.19': 'T',
 'r3.20': 'F',
 'w1.21': ['factory'],
 'w1.22': ['hippo'],
 'w1.23': ['turn round', 'turnround', 'turn around'],
 'w1.24': ['sing merrily', 'singmerrily'],
 'w2.25': ['The girls are dancing around the campfire.'],
 'w2.26': ['The water park is in Lac Long Quan Street.'],
 'w2.27': ['My mother washes the clothes in the evening.'],
 'w3.28': ['She goes to the cinema on Saturdays.', 'She goes to the cinema.'],
 'w3.29': ['It’s sunny.', 'It is sunny.'],
 'w3.30': ['She does yoga in the morning.', 'She does yoga.']}

EXPLANATIONS = {'l1.1': 'Đáp án: False (theo đáp án của đề: ✗).',
 'l1.2': 'Đáp án: True (theo đáp án của đề: ✓).',
 'l1.3': 'Đáp án: False (theo đáp án của đề: ✗).',
 'l1.4': 'Đáp án: True (theo đáp án của đề: ✓).',
 'l2.5': 'Đáp án: Yes (theo đáp án của đề).',
 'l2.6': 'Đáp án: No (theo đáp án của đề).',
 'l2.7': 'Đáp án: No (theo đáp án của đề).',
 'l2.8': 'Đáp án: Yes (theo đáp án của đề).',
 'l3.10': 'Đáp án theo đề: cooks meal(s).',
 'l3.11': 'bookshop = hiệu sách.',
 'l3.12': 'go straight and turn left = đi thẳng rồi rẽ trái.',
 'l3.9': 'Đáp án theo đề: at noon.',
 'r1.13': 'Đáp án: B (theo đáp án của đề).',
 'r1.14': 'Đáp án: C (theo đáp án của đề).',
 'r1.15': 'Đáp án: A (theo đáp án của đề).',
 'r1.16': 'Đáp án C: đi thẳng, rẽ trái, rồi rẽ phải. (Các mũi tên được dựng lại từ ảnh gốc đã bị mất chiều.)',
 'r2.17': 'Theo đáp án của đề: 1–A, 2–D, 3–B (C là ví dụ).',
 'r3.18': 'Đúng: On Saturday afternoon … flying a kite with her father.',
 'r3.19': 'Đúng: On Sundays, the family clean the house and cook meals together.',
 'r3.20': 'Sai: họ xem tivi/nghe nhạc vào tối Chủ nhật (Sunday evening).',
 'w1.21': 'factory = nhà máy.',
 'w1.22': 'hippo = hà mã.',
 'w1.23': 'turn round = quay đầu (TURN ROUND).',
 'w1.24': 'sing merrily = hót líu lo.',
 'w2.25': 'Câu đúng: The girls are dancing around the campfire.',
 'w2.26': 'Câu đúng: The water park is in Lac Long Quan Street.',
 'w2.27': 'Câu đúng: My mother washes the clothes in the evening.',
 'w3.28': 'Câu đúng: She goes to the cinema on Saturdays.',
 'w3.29': 'Câu đúng: It’s sunny.',
 'w3.30': 'Câu đúng: She does yoga in the morning.'}
