# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'tomorrow',
 't1.10': 'This is Mai.',
 't1.11': 'down',
 't1.12': "He's flying a kite.",
 't1.13': ['This is Mary.'],
 't1.14': 'Open your books, please!',
 't1.15': 'up',
 't1.16': "They're painting.",
 't1.17': ['They are playing badminton.'],
 't1.18': 'Fly it in the sky.',
 't1.19': 'aloud',
 't1.2': 'Good morning.',
 't1.20': "She's skipping.",
 't1.3': 'are',
 't1.4': "I'm fine, thank you.",
 't1.5': ['Nice to see you.'],
 't1.6': 'How are you?',
 't1.7': 'again',
 't1.8': 'Good morning, class.',
 't1.9': ['Close your book, please.']}

EXPLANATIONS = {'t1.1': 'Đáp án: tomorrow',
 't1.10': 'Đáp án: This is Mai.',
 't1.11': 'Đáp án: down',
 't1.12': "Đáp án: He's flying a kite.",
 't1.13': 'Câu đúng: This is Mary.',
 't1.14': 'Đáp án: Open your books, please!',
 't1.15': 'Đáp án: up',
 't1.16': "Đáp án: They're painting.",
 't1.17': 'Câu đúng: They are playing badminton.',
 't1.18': 'Đáp án: Fly it in the sky.',
 't1.19': 'Đáp án: aloud',
 't1.2': 'Đáp án: Good morning.',
 't1.20': "Đáp án: She's skipping.",
 't1.3': 'Đáp án: are',
 't1.4': "Đáp án: I'm fine, thank you.",
 't1.5': 'Câu đúng: Nice to see you.',
 't1.6': 'Đáp án: How are you?',
 't1.7': 'Đáp án: again',
 't1.8': 'Đáp án: Good morning, class.',
 't1.9': 'Câu đúng: Close your book, please.'}
