# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u7-test03',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Yes, I do.', "No, I don't.", 'I have it on Tuesday and Tuesdays.', 'I have Maths and Vietnamese.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “When do you have Maths?”?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['Wednesday', 'Wednesdays', 'Saturday', 'Thursday'],
                                   'plain': True,
                                   'q': 'I have Art on ___________ and Fridays.',
                                   't': 'mcq'},
                                  {'id': 't1.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Art?', 'When', 'you', 'have', 'do']},
                                  {'id': 't1.4',
                                   'o': ['Có phải hôm nay bạn có môn toán không?',
                                         'Khi nào bạn có môn Khoa học?',
                                         'Tôi có môn Toán mỗi ngày.',
                                         'Hôm nay bạn có những môn gì?'],
                                   'plain': True,
                                   'q': 'Câu: “What subjects do you have today?” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'o': ["don't", 'am not', 'are', "aren't"], 'plain': True, 'q': 'A: Do you have Vietnamese today?', 't': 'mcq'},
                                  {'id': 't1.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['and', 'have', 'Vietnamese', 'Maths', 'We', 'today.']},
                                  {'id': 't1.7',
                                   'o': ['Có phải hôm nay bạn có môn tiếng Việt không?',
                                         'Khi nào bạn có môn tiếng Việt?',
                                         'Hôm nay bạn có những môn gì?',
                                         'Hôm nay tôi có môn tiếng Việt.'],
                                   'plain': True,
                                   'q': 'Câu “When do you have Vietnamese?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 't1.8', 'o': ['Is', 'Do', 'Does', 'Are'], 'plain': True, 'q': 'A: __________ you have Science today?', 't': 'mcq'},
                                  {'id': 't1.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Mondays', 'from', 'school', 'to', 'to', 'Fridays.', 'I', 'go']},
                                  {'id': 't1.10',
                                   'o': ['When do you have Maths?', 'What subjects do you have today?', 'When do you have Art?', 'When do you have Science?'],
                                   'plain': True,
                                   'q': 'Câu “I have Art every day” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'o': ['in', 'on', 'at', 'to'],
                                   'plain': True,
                                   'q': 'I have music ___________ Fridays and Saturdays.',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['I', 'GHI', 'NHỚ', 'much.', 'like', 'Art', 'very']},
                                  {'id': 't1.13',
                                   'o': ['When do you have Maths?',
                                         'What subjects do you have today?',
                                         'How many playgrounds are there at your school?',
                                         "Where's your school?"],
                                   'plain': True,
                                   'q': 'Câu nào hỏi ai đó hôm nay có môn học gì?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ["What's", 'What', 'When', 'Where'],
                                   'plain': True,
                                   'q': 'A: ____________ the name of your school?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['Yes, she does.',
                                         'Yes, I do.',
                                         'I have Maths, Vietnamese and Science.',
                                         'I have it on Monday and Thursdays.',
                                         "It's Wednesday."],
                                   'plain': True,
                                   'q': 'What subjects do you have today?',
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['this', 'it', 'that', 'she'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What day is _____ today?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['have', 'do', 'subjects', 'you', 'What', 'today?']},
                                  {'id': 't1.18',
                                   'o': ['When do you have English?',
                                         "Where's your school?",
                                         'What subjects do you have today?',
                                         'When do you have Maths and English?'],
                                   'plain': True,
                                   'q': 'Câu “I have Maths and English." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.19', 'o': ['it', 'this', 'that', 'there'], 'plain': True, 'q': 'What day is ____________ today?', 't': 'mcq'},
                                  {'id': 't1.20',
                                   'o': ['Yes, she does.',
                                         'Yes, I do.',
                                         'I have Maths, Vietnamese and Science.',
                                         'I have it on Monday and Thursdays.',
                                         "It's Wednesday."],
                                   'plain': True,
                                   'q': 'Do you have Art today?',
                                   't': 'mcq'}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 7 – Our timetable: Kiểm tra 3',
 'unit': 7}
