# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u16-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['I like windy days.', 'It was sunny.', "Let's go to the water park.", "I'm doing my homework."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây đề nghị hoặc rủ ai đó đi đâu cùng với mình?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['is', 'are', 'was', 'were'],
                                   'plain': True,
                                   'q': 'What ____________ the weather like last Sunday?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['It was sunny.', 'It is cloudy.', 'I was in Da Nang.', 'I want to buy some books.', "Great! Let's go."],
                                   'plain': True,
                                   'q': 'Where were you last Saturday?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Where', 'What', 'When', 'How'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. A: _____ were you last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['last', 'weekend?', 'you', 'were', 'Where']},
                                  {'id': 't1.6',
                                   'o': ['Do you want to go to the bookshop?',
                                         'What was the weather like last Sunday?',
                                         'What does she look like?',
                                         'Where do you go on Sundays?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về thời tiết trong quá khứ?',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['is', 'are', 'was', 'were'], 'plain': True, 'q': 'It ______________ rainy yesterday.', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['It was sunny.', 'It is cloudy.', 'I was in Da Nang.', 'I want to buy some books.', "Great! Let's go."],
                                   'plain': True,
                                   'q': 'What was the weather like last Saturday?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['water park', 'bookshop', 'food stall', 'sports centre'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 2. A: Do you want to go to the _____?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['last', 'Hue', 'I', 'in', 'was', 'weekend.']},
                                  {'id': 't1.11',
                                   'o': ['Where do you go on Saturdays?',
                                         'Do you want to go to the shopping centre?',
                                         "Let's go.",
                                         'What do you do on Mondays?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi bạn có muốn đi đâu đó không?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['Was', 'Were', 'Do', 'Does'],
                                   'plain': True,
                                   'q': '_____________ you want to go to the water park with me?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['It was sunny.', 'It is cloudy.', 'I was in Da Nang.', 'I want to buy some books.', "Great! Let's go."],
                                   'plain': True,
                                   'q': 'Do you want to go to the bookshop?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['bookshop', 'water park', 'bakery', 'food stall'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 3. A: I want to buy some books. Do you want to go to the _____ with me?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['weather', 'was', 'like', 'yesterday?', 'in', 'Long', 'What', 'An', 'the']},
                                  {'id': 't1.16',
                                   'o': ["She's beautiful.", 'He has a round face.', 'It was rainy.', "Let's go to the food stall."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What was the weather like yesterday?”',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['day', 'weather', 'homework', 'weekend'],
                                   'plain': True,
                                   'q': "A: What's the __________ like yesterday?",
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['It was sunny.', 'It is cloudy.', 'I was in Da Nang.', 'I want to buy some books.', "Great! Let's go."],
                                   'plain': True,
                                   'q': 'What do you want to buy?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['is', 'are', 'was', 'were'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: It _____ rainy.',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['yesterday.', 'and', 'cold', 'was', 'It', 'rainy']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 16 – Weather: Kiểm tra 1',
 'unit': 16}
