# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': {'blanks': [['a'], ['e'], ['b'], ['c']]},
 'l2.2': 'A',
 'l2.3': 'A',
 'l2.4': 'B',
 'l2.5': 'B',
 'l3.6': ['Turn left'],
 'l3.7': ['look like'],
 'l3.8': ['on a farm', 'on the farm'],
 'l3.9': ['lions'],
 'r1.10': 'C',
 'r1.11': 'A',
 'r1.12': 'B',
 'r1.13': 'A',
 'r1.14': 'C',
 'r2.15': ['shopping centre'],
 'r2.16': ['opposite'],
 'r2.17': ['wants'],
 'r2.18': ['merrily'],
 'r2.19': ['thousand'],
 'r3.20': ['bakery'],
 'r3.21': ['farmer'],
 'r3.22': ['turn left', 'turnleft'],
 'r3.23': ['crocodiles'],
 'r3.24': ['round'],
 'w1.25': ['When do you watch TV?'],
 'w1.26': ['Do you want to go to the food store?'],
 'w1.27': ['How can I get to the supermarket?'],
 'w1.28': ['She is building a campfire at the campsite.'],
 'w1.29': ['The bookshop is between the gift shop and the sports shop.']}

EXPLANATIONS = {'l1.1': 'Theo bài nghe: câu 1 “What does your father do? – He’s a farmer.” → a; câu 2 “What do you do at noon? – I wash the dishes.” → e; câu 3 “How can I '
         'get to the bookshop? – Go straight.” → b; câu 4 “Where’s the bookshop? – It’s near the bakery.” → c',
 'l2.2': 'Bài nghe: “She goes to the shopping centre.”',
 'l2.3': 'Bài nghe: “She has big e… (ears)” – không phải long hair.',
 'l2.4': 'Bài nghe: “It’s 80,000 dong.”',
 'l2.5': 'Bài nghe: “She’s a farmer.”',
 'l3.6': 'Theo bài nghe: “Turn left.” → Turn left',
 'l3.7': 'Theo bài nghe: “What does he look like? – He’s big.” → look like',
 'l3.8': 'Theo bài nghe: “He works on a farm.” → on a farm',
 'l3.9': 'Theo bài nghe: “These are lions.” → lions',
 'r1.10': 'Đáp án: C (khớp với nội dung câu).',
 'r1.11': 'Đáp án: A (khớp với nội dung câu).',
 'r1.12': 'Đáp án: B (khớp với nội dung câu).',
 'r1.13': 'Đáp án: A (khớp với nội dung câu).',
 'r1.14': 'Đáp án: C (khớp với nội dung câu).',
 'r2.15': 'going to the shopping centre.',
 'r2.16': 'It is opposite the swimming pool.',
 'r2.17': 'My mum wants to buy some food (he/she/it + wants).',
 'r2.18': 'the birds because they sing merrily.',
 'r2.19': 'eighty-eight thousand dong.',
 'r3.20': 'bakery = tiệm bánh.',
 'r3.21': 'farmer = nông dân.',
 'r3.22': 'turn left = rẽ trái.',
 'r3.23': 'crocodiles = cá sấu.',
 'r3.24': 'round = tròn (round face).',
 'w1.25': 'Câu đúng: When do you watch TV?',
 'w1.26': 'Câu đúng: Do you want to go to the food store?',
 'w1.27': 'Câu đúng: How can I get to the supermarket?',
 'w1.28': 'Câu đúng: She is building a campfire at the campsite.',
 'w1.29': 'Câu đúng: The bookshop is between the gift shop and the sports shop.'}
