# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'What does it say?',
 't1.10': ['Go straight and turn left at the cinema.'],
 't1.11': 'Go straight and turn left.',
 't1.12': 'there',
 't1.13': 'It says "stop".',
 't1.14': 'How',
 't1.15': ['Is there a water park near here?'],
 't1.16': 'Turn left.',
 't1.17': 'cinema',
 't1.18': 'I want to buy some clothes.',
 't1.19': 'bookshop',
 't1.2': 'bookshop',
 't1.20': ['There is a food stall in Pham Van Dong Street.'],
 't1.3': "I'm at the shopping centre.",
 't1.4': 'Turn',
 't1.5': ['How can I get to the sports centre?'],
 't1.6': 'How can I get to the bookshop?',
 't1.7': 'How',
 't1.8': 'Go straight and turn right.',
 't1.9': 'bakery'}

EXPLANATIONS = {'t1.1': 'Đáp án: What does it say?',
 't1.10': 'Câu đúng: Go straight and turn left at the cinema.',
 't1.11': 'Đáp án: Go straight and turn left.',
 't1.12': 'Đáp án: there',
 't1.13': 'Đáp án: It says "stop".',
 't1.14': 'Đáp án: How',
 't1.15': 'Câu đúng: Is there a water park near here?',
 't1.16': 'Đáp án: Turn left.',
 't1.17': 'Đáp án: cinema',
 't1.18': 'Đáp án: I want to buy some clothes.',
 't1.19': 'Đáp án: bookshop',
 't1.2': 'Đáp án: bookshop',
 't1.20': 'Câu đúng: There is a food stall in Pham Van Dong Street.',
 't1.3': "Đáp án: I'm at the shopping centre.",
 't1.4': 'Đáp án: Turn',
 't1.5': 'Câu đúng: How can I get to the sports centre?',
 't1.6': 'Đáp án: How can I get to the bookshop?',
 't1.7': 'Đáp án: How',
 't1.8': 'Đáp án: Go straight and turn right.',
 't1.9': 'Đáp án: bakery'}
