# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck2-de3',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'gi',
                        'instr': 'I. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'gi.1', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.2', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.3', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'gi.4', 'o': ['a', 'b', 'c', 'd'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck2_de3/gi.png" alt="Tranh a–d">'},
                       {'id': 'gii',
                        'instr': 'II. Listen and draw lines (nghe và nối nhân vật với tranh).',
                        'items': [{'id': 'gii.5',
                                   'left': [{'img': 'gii_l1.png', 't': 'LinhLinhLinhLinh'},
                                            {'img': 'gii_l2.png', 't': 'MaiMaiMaiMai'},
                                            {'img': 'gii_l3.png', 't': 'HoaHoaHoaHoa'},
                                            {'img': 'gii_l4.png', 't': 'AnAnAnAn'}],
                                   'o': ['a', 'b', 'c', 'd'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck2_de3/gii.png" alt="Tranh a–d">'},
                       {'id': 'giii',
                        'instr': 'III. Listen and complete (nghe và điền từ).',
                        'items': [{'id': 'giii.6', 'q': 'How can I get to the {_}? – Turn left.', 't': 'fill'},
                                  {'id': 'giii.7', 'q': 'How much is the {_}? – It’s 200,000 dong.', 't': 'fill'},
                                  {'id': 'giii.8', 'q': 'What are these animals? – They’re {_}.', 't': 'fill'},
                                  {'id': 'giii.9', 'q': 'What was the weather like last weekend? – It was {_}.', 't': 'fill'}]},
                       {'id': 'giv',
                        'instr': 'IV. Read and choose A, B or C (nhìn tranh, chọn đáp án đúng).',
                        'items': [{'id': 'giv.10',
                                   'img': 'giv_1.png',
                                   'o': ['Because they sing beautifully.', 'Because they roar loudly.', 'Because they are roaring.'],
                                   'q': 'Why do you like lions?',
                                   't': 'mcq'},
                                  {'id': 'giv.11',
                                   'img': 'giv_2.png',
                                   'o': ['It’s next to the gift shop.', 'It’s between the gift shop.', 'It’s behind the gift shop.'],
                                   'q': 'Where’s the food stall?',
                                   't': 'mcq'},
                                  {'id': 'giv.12',
                                   'img': 'giv_3.png',
                                   'o': ['She plays tug of war.', 'They’re playing tug of war.', 'She’s playing tug of war.'],
                                   'q': 'What is Lan doing?',
                                   't': 'mcq'},
                                  {'id': 'giv.13',
                                   'img': 'giv_4.png',
                                   'o': ['How many skirts are there?', 'How much is the skirt?', 'Where’s the skirt?'],
                                   'q': '________________ – It’s 150,000 dong.',
                                   't': 'mcq'}]},
                       {'id': 'gv',
                        'instr': 'V. Write suitable questions for the answers given (nhìn tranh, viết câu hỏi phù hợp).',
                        'items': [{'id': 'gv.14', 'img': 'gv_1.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>It’s opposite the bakery.</i><br>{_}', 't': 'fill'},
                                  {'id': 'gv.15', 'img': 'gv_2.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>They’re crocodiles.</i><br>{_}', 't': 'fill'},
                                  {'id': 'gv.16', 'img': 'gv_3.png', 'q': 'Viết câu hỏi cho câu trả lời: <i>Sorry, I can’t.</i><br>{_}', 't': 'fill'}]},
                       {'id': 'gvi',
                        'instr': 'VI. Read and write T (True) or F (False) (đọc đoạn văn, True hay False?).',
                        'items': [{'id': 'gvi.17', 'q': 'The weather was sunny.', 't': 'tf'},
                                  {'id': 'gvi.18', 'q': 'There were giraffes and hippos at the zoo.', 't': 'tf'},
                                  {'id': 'gvi.19', 'q': 'I liked the lions because they were small and cute.', 't': 'tf'}],
                        'passage': '<p>Our day at the zoo was so much fun! A zoo is a place where you can go and see the animals. It was a cloudy day and all '
                                   'kinds of animals were at the zoo. In the morning, we were able to see the crocodiles, the bears and the elephants. Next, '
                                   'there were the giraffes and the hippos. I liked the lions because they were so big and scary. I love going to the '
                                   'zoo!</p>'},
                       {'id': 'gvii',
                        'instr': 'VII. Fill in the blanks (điền từ vào chỗ trống, nhìn tranh).',
                        'items': [{'id': 'gvii.20', 'img': 'gvii_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'gvii.21', 'img': 'gvii_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'gvii.22', 'img': 'gvii_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'gvii.23', 'img': 'gvii_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>The dad and his son are on a camping trip. They walk into the woods where there are a lot of trees. The weather is '
                                   '<b>(1) ______</b> They put up a big red <b>(2) ______</b> They use some dried woods to build a <b>(3) ______</b> Soon, it '
                                   'is sunset. They enjoy telling stories and <b>(4) ______</b> around the campfire.</p>'},
                       {'bank': ['Sorry', 'dance beautifully', 'singing songs', 'turn round'],
                        'id': 'gviii',
                        'instr': 'VIII. Write suitable answers to the questions using given words (dùng từ cho sẵn để trả lời).',
                        'items': [{'id': 'gviii.24', 'q': 'What are Mai and Lan doing?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.25', 'q': 'What does it say?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.26', 'q': 'Do you want to go to the bookshop?<br>→ {_}', 't': 'fill'},
                                  {'id': 'gviii.27', 'q': 'Why do you like peacocks?<br>→ {_}', 't': 'fill'}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 2 – Đề 3',
 'unit': 'CuoiKy2'}
