# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r4-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What was the weather like yesterday?',
                                         'What does your brother loook like?',
                                         'Where do you go on Sundays?',
                                         'Do you want to go to the supermarket?'],
                                   'plain': True,
                                   'q': 'Câu “It was rainy.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['What', 'Where', 'How', 'When'],
                                   'plain': True,
                                   'q': 'A: (1) ______________ was the weather like yesterday?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["It's two hundred thousand dong.",
                                         'It was rainy.',
                                         'They are building a campfire.',
                                         'Because they are funny.',
                                         'Turn right and go straight.'],
                                   'plain': True,
                                   'q': 'What was the weather like last Saturday, Lan?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['like', 'judo', 'Where', 'Are', 'between'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 1. A: Hi, Ben. _____ were you last weekend?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['last', 'weekend,', 'you', 'were', 'Where', 'Linh?']},
                                  {'id': 't1.6',
                                   'o': ['What was the weather like in Da Lat?',
                                         'What was the weather like in Da Lat last weekend?',
                                         'Do you want to go to Da Lat?',
                                         'It was sunny in Da Lat.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Cuối tuần trước thời tiết ở Đà Lạt như thế nào?”',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['bakery', 'food stall', 'bookshop', 'pet shop'],
                                   'plain': True,
                                   'q': 'A: Do you want to go to the ______________ with me?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ["It's two hundred thousand dong.",
                                         'It was rainy.',
                                         'They are building a campfire.',
                                         'Because they are funny.',
                                         'Turn right and go straight.'],
                                   'plain': True,
                                   'q': 'How can I get to the zoo?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['like', 'judo', 'Where', 'Are', 'between'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: 2. B: What was the weather _____ in Da Lat?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['hot.', 'and', 'It', 'sunny', 'was']},
                                  {'id': 't1.11',
                                   'o': ['Go straight and turn left.',
                                         'There is a bookshop in Nguyen Thi Minh Khai Street.',
                                         'Thank you very much for your help.',
                                         'The zoo is on the right.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: How can I get to the zoo?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['cinema', 'bakery', 'food stall', 'post office'],
                                   'plain': True,
                                   'q': 'I want to buy some stamps. Is there a _____________ near here?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ["It's two hundred thousand dong.",
                                         'It was rainy.',
                                         'They are building a campfire.',
                                         'Because they are funny.',
                                         'Turn right and go straight.'],
                                   'plain': True,
                                   'q': 'How much is the skirt?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['like', 'judo', 'Where', 'Are', 'between'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: It's _____ the gift shop and the pet shop.",
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['I', 'bookshop?', 'the', 'to', 'How', 'get', 'can']},
                                  {'id': 't1.16',
                                   'o': ['Is there a post office near here?',
                                         'How can I get the the post office?',
                                         'What do you want to buy at the post office?',
                                         'Do you want to go to the post office with me?'],
                                   'plain': True,
                                   'q': 'Câu: “Go straight and turn right" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['bakery', 'bookshop', 'sports centre', 'swimming pool'],
                                   'plain': True,
                                   'q': 'I want to buy some bread. How can I get to the _____________?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ["It's two hundred thousand dong.",
                                         'It was rainy.',
                                         'They are building a campfire.',
                                         'Because they are funny.',
                                         'Turn right and go straight.'],
                                   'plain': True,
                                   'q': 'Why do you like monkeys?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['like', 'judo', 'Where', 'Are', 'between'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: B: He's doing a _____.",
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Street.', 'Hung', 'bookshop', 'a', 'There', 'Dao', 'Tran', 'is', 'in']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Review 4: Kiểm tra 1',
 'unit': 'Review4'}
