# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "They're painting.",
 't1.10': 'See you later.',
 't1.11': 'is',
 't1.12': 'How are you?',
 't1.13': 'is cycling',
 't1.14': "What's he doing?",
 't1.15': 'tomorrow',
 't1.16': 'Good morning.',
 't1.17': 'are',
 't1.18': "I'm fine, thank you.",
 't1.19': ['Nice to see you.'],
 't1.2': ['They are playing badminton.'],
 't1.20': 'How are you?',
 't1.3': 'Fly it in the sky.',
 't1.4': 'aloud',
 't1.5': "She's skipping.",
 't1.6': 'Nice to see you!',
 't1.7': 'are',
 't1.8': 'Tạm biệt!',
 't1.9': 'up'}

EXPLANATIONS = {'t1.1': "Đáp án: They're painting.",
 't1.10': 'Đáp án: See you later.',
 't1.11': 'Đáp án: is',
 't1.12': 'Đáp án: How are you?',
 't1.13': 'Đáp án: is cycling',
 't1.14': "Đáp án: What's he doing?",
 't1.15': 'Đáp án: tomorrow',
 't1.16': 'Đáp án: Good morning.',
 't1.17': 'Đáp án: are',
 't1.18': "Đáp án: I'm fine, thank you.",
 't1.19': 'Câu đúng: Nice to see you.',
 't1.2': 'Câu đúng: They are playing badminton.',
 't1.20': 'Đáp án: How are you?',
 't1.3': 'Đáp án: Fly it in the sky.',
 't1.4': 'Đáp án: aloud',
 't1.5': "Đáp án: She's skipping.",
 't1.6': 'Đáp án: Nice to see you!',
 't1.7': 'Đáp án: are',
 't1.8': 'Đáp án: Tạm biệt!',
 't1.9': 'Đáp án: up'}
