# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u14-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['What do you do?', 'What do you do in the morning?', 'When do you watch TV?', 'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi ai đó làm việc gì đó khi nào?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['What do you do in the afternoon?',
                                         'What do you do in the morning?',
                                         'What do you do in the evening?',
                                         'When do you wash the clothes?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi bạn làm gì vào buổi sáng?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Where do you work?',
                                         'What do you do in the evening?',
                                         'When do you wash your clothes?',
                                         'When do you clean the floor?'],
                                   'plain': True,
                                   'q': 'Câu “I clean the floor" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['I wash the dishes in the evening.', 'I wash my clothes.', 'Yes, I do.', 'I help my mum with the cooking.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “When do you wash the dishes?”?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['I watch TV in the evening.', 'I wash my clothes in the afternoon.', 'Yes, I do.', "No, they don't."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Do you wash your clothes?”',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['What do you do in the evening?',
                                         'When do you help mother with the cooking?',
                                         'What do you do?',
                                         'What does your mother do in the evening?'],
                                   'plain': True,
                                   'q': 'Câu “I help my mother with the cooking" trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['Tôi rửa chén dĩa.',
                                         'Tôi giúp nấu nướng.',
                                         'Tôi làm việc nhà cùng với bố mẹ tôi.',
                                         'Tôi làm bài tập về nhà với ba mẹ tôi.'],
                                   'plain': True,
                                   'q': 'Câu "I do the housework with my parents.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['She washes the dishes in the evening.',
                                         'She washes her clothes in the evening.',
                                         'She cleans the floor in the afternoon.',
                                         'She watches TV in the evening.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là “Cô ấy giặt quần áo vào buổi tối.”',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['He watches TV in the evening.',
                                         'He does the housework with his parents.',
                                         'He washes the dishes in the morning.',
                                         'He washes his clothes in the evening.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does he do in the afternoon?”?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['Yes, she does.', 'In the evening.', 'She washes her clothes.', 'She cleans the floor.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “When does she help with the cooking?”',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1',
                                   'o': ['When', 'Where', 'What', 'How'],
                                   'plain': True,
                                   'q': 'A: ____________do you do in the evening?',
                                   't': 'mcq'},
                                  {'id': 'b.2',
                                   'o': ['wash', 'washes', 'watching', 'to wash'],
                                   'plain': True,
                                   'q': 'She ______________ her clothes in the evening.',
                                   't': 'mcq'},
                                  {'id': 'b.3',
                                   'o': ['Are', 'Is', 'Do', 'Does'],
                                   'plain': True,
                                   'q': 'A: ______________ you wash your clothes in the evening?',
                                   't': 'mcq'},
                                  {'id': 'b.4', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'What ______________ she do in the morning?', 't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['watch', 'watches', 'to watch', 'watching'],
                                   'plain': True,
                                   'q': 'A: When does your brother watch TV?',
                                   't': 'mcq'},
                                  {'id': 'b.6',
                                   'o': ['clean', 'cleans', 'to clean', 'are clean'],
                                   'plain': True,
                                   'q': 'When do you ______________ the floor?',
                                   't': 'mcq'},
                                  {'id': 'b.7',
                                   'o': ['help', 'is help', 'helps', 'to help'],
                                   'plain': True,
                                   'q': 'She ______________ her mum with the cooking in the evening.',
                                   't': 'mcq'},
                                  {'id': 'b.8', 'o': ['are', 'is', 'do', 'does'], 'plain': True, 'q': 'When ______________ you do your homework?', 't': 'mcq'},
                                  {'id': 'b.9',
                                   'o': ['TV', 'books', 'housework', 'floor'],
                                   'plain': True,
                                   'q': 'I read _____________ in the evening.',
                                   't': 'mcq'},
                                  {'id': 'b.10',
                                   'o': ['make', 'watch', 'do', 'help'],
                                   'plain': True,
                                   'q': 'When do you _____________ the housework?',
                                   't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['When do you do the housework?',
                                            'What do you do on Saturdays?',
                                            'When does she wash her clothes?',
                                            'What does she do on Sundays?',
                                            'What do you do in the afternoon?'],
                                   'o': ['She cleans the floor.',
                                         'I do the housework in the morning.',
                                         'I read books in the afternoon.',
                                         'She washes her clothes in the evening.',
                                         'I watch TV.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'},
                                  {'id': 'd.6', 'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'], 'plain': True, 'q': 'Chỗ trống (6):', 't': 'mcq'}],
                        'passage': "A: Who's <b>(1)&nbsp;______</b>?<br>B: She's my cousin.<br>A: What <b>(2)&nbsp;______</b> she do?<br>B: She's a "
                                   'student.<br>A: What does she <b>(3)&nbsp;______</b> on Saturdays?<br>B: She <b>(4)&nbsp;______</b> English.<br>A: What '
                                   'does she do on Saturdays?<br>B: She <b>(5)&nbsp;______</b> the floor in the morning and washes her clothes in the '
                                   'afternoon.<br>A: What does she do in the evening?<br>B: She <b>(6)&nbsp;______</b> her mother with the cooking and washes '
                                   'the dishes.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': "Today Lan doesn't go to school.", 't': 'tf'},
                                  {'id': 'e.2', 'q': 'She does a lot of housework with her parents.', 't': 'tf'},
                                  {'id': 'e.3', 'q': 'She cleans the floor in the morning.', 't': 'tf'},
                                  {'id': 'e.4', 'q': 'She washes the dishes after having lunch.', 't': 'tf'},
                                  {'id': 'e.5', 'q': 'She washes her clothes in the evening.', 't': 'tf'},
                                  {'id': 'e.6', 'q': 'She watches TV alone.', 't': 'tf'}],
                        'passage': "Hi, I'm Lan. I study at Nguyen Khuyen Primary School. I go to school from Monday to Friday. It's Saturday today, I'm at "
                                   'home. I do a lot of housework with my parents. I wash my clothes in the morning. I wash the dishes after having lunch. In '
                                   'the afternoon, I help my mother with the cooking. In the evening, I clean the floor. Then I watch TV together with my '
                                   'parents.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ["What's", 'your', 'Minh?', 'hobby,']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['watching', 'like', 'I', 'TV.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['TV', 'the', 'in', 'evening.', 'She', 'watches']},
                                  {'id': 'f.4',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Nam', 'What', 'do', 'the', 'afternoon?', 'does', 'in']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['the', 'afternoon.', 'Minh', 'in', 'reads', 'books']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['does', 'he', 'his', 'clothes?', 'wash', 'When']},
                                  {'id': 'f.7',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['his', 'morning.', 'clothes', 'washes', 'He', 'the', 'in']},
                                  {'id': 'f.8',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'She', 'her', 'mother', 'cooking.', 'with', 'helps']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['at', 'noon.', 'cleans', 'floor', 'the', 'He']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'do', 'housework', 'in', 'the', 'I', 'morning.']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi ai đó thực hiện một hoạt động khi nào và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả '
           'lời</td></tr><tr><td>When do you + V...?<br>Bạn... khi nào?</td><td>I + V....<br>Tôi...</td></tr><tr><td>When does she/he + V...?<br>Cô ấy/Anh '
           'ấy... khi nào?</td><td>She/He + V....<br>Cô ấy/Anh ấy...</td></tr><tr><td>Ví dụ:<br>- When do you wash your clothes?<br>Bạn giặt quần áo của mình '
           'khi nào?<br>- When does she wash the dishes?<br>Cô ấy rửa chén đĩa khi nào?</td><td>I wash my clothes in the evening.<br>Tôi giặt quần áo của tôi '
           'vào buổi tối.<br>She washes the dishes at noon.<br>Cô ấy rửa chén đĩa vào buổi trưa.</td></tr></table><p>2. Cách đặt câu hỏi về hoạt động hằng '
           'ngày của ai đó và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>What do you do + /in/on + '
           '(time)?<br>Bạn làm gì vào + (khoảng thời gian trong ngày)?</td><td>I + V<br>Tôi...</td></tr><tr><td>What does she/he do + in/on + (time)?<br>Cô '
           'ấy/Anh ấy làm gì + (thời gian)?</td><td>She/He + V....<br>Cô ấy/Anh ấy...</td></tr><tr><td>Ví dụ:<br>- What do you do in the afternoon?<br>Bạn làm '
           'gì vào buổi chiều?<br>- What does she do in the evening?<br>Cô ấy làm gì vào buổi tối?</td><td>I clean the floor.<br>Tôi lau sàn nhà.<br>She '
           'watches TV with her parents.<br>Cô ấy xem TV cùng với bố mẹ của cô ấy.</td></tr></table>',
 'title': 'Unit 14 – Daily activities: Luyện tập',
 'unit': 14}
