# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'She lives in Le Lai Street.',
 'a.10': 'Dì của bạn làm gì vào các ngày thứ Bảy?',
 'a.2': "It's a small house.",
 'a.3': 'What does Mai do?',
 'a.4': 'What does Nam do?',
 'a.5': 'What does Mai look like?',
 'a.6': "She's slim.",
 'a.7': 'In the evening.',
 'a.8': 'What does Lan do in the evening?',
 'a.9': 'She goes to the supermarket on Sundays.',
 'b.1': 'does',
 'b.10': 'go',
 'b.2': 'at',
 'b.3': 'worker',
 'b.4': 'on a farm',
 'b.5': 'What',
 'b.6': 'your aunt',
 'b.7': 'clean',
 'b.8': 'does',
 'b.9': 'does',
 'c.1': {'blanks': [['She lives at 10A Oxford Street.'],
                    ['She works on a farm.'],
                    ["He's tall and thin."],
                    ['He watches TV in the evening.'],
                    ['She goes to the sports centre.']]},
 'd.1': 'Who',
 'd.2': 'Where',
 'd.3': 'is',
 'd.4': 'go',
 'd.5': 'do',
 'e.1': 'three',
 'e.2': "He's a farmer.",
 'e.3': 'He works on a farm.',
 'e.4': "She's a teacher.",
 'e.5': 'She works at a school.',
 'e.6': 'He’s a student.',
 'f.1': ['Where Mary does live?'],
 'f.10': ['What does your brother do on Sundays?'],
 'f.2': ["What's the village like?"],
 'f.3': ['What does your mother do?'],
 'f.4': ['My sister teaches at a primary school.'],
 'f.5': ['What does your brother look like?'],
 'f.6': ['My sister is slim and has long hair.'],
 'f.7': ['When do you do the housework?'],
 'f.8': ['Ben washes his clothes in the evening.'],
 'f.9': ['My father goes to the swimming pool on Saturdays.']}

EXPLANATIONS = {'a.1': 'Đáp án: She lives in Le Lai Street.',
 'a.10': 'Đáp án: Dì của bạn làm gì vào các ngày thứ Bảy?',
 'a.2': "Đáp án: It's a small house.",
 'a.3': 'Đáp án: What does Mai do?',
 'a.4': 'Đáp án: What does Nam do?',
 'a.5': 'Đáp án: What does Mai look like?',
 'a.6': "Đáp án: She's slim.",
 'a.7': 'Đáp án: In the evening.',
 'a.8': 'Đáp án: What does Lan do in the evening?',
 'a.9': 'Đáp án: She goes to the supermarket on Sundays.',
 'b.1': 'Đáp án: does',
 'b.10': 'Đáp án: go',
 'b.2': 'Đáp án: at',
 'b.3': 'Đáp án: worker',
 'b.4': 'Đáp án: on a farm',
 'b.5': 'Đáp án: What',
 'b.6': 'Đáp án: your aunt',
 'b.7': 'Đáp án: clean',
 'b.8': 'Đáp án: does',
 'b.9': 'Đáp án: does',
 'c.1': "Where does Mary live? → She lives at 10A Oxford Street.; Where does she work? → She works on a farm.; What does your cousin look like? → He's tall "
        'and thin.; What does Ben do in the evening? → He watches TV in the evening.; Where does Hoa go on Sundays? → She goes to the sports centre.',
 'd.1': 'Đáp án: Who',
 'd.2': 'Đáp án: Where',
 'd.3': 'Đáp án: is',
 'd.4': 'Đáp án: go',
 'd.5': 'Đáp án: do',
 'e.1': 'Đáp án: three',
 'e.2': "Đáp án: He's a farmer.",
 'e.3': 'Đáp án: He works on a farm.',
 'e.4': "Đáp án: She's a teacher.",
 'e.5': 'Đáp án: She works at a school.',
 'e.6': 'Đáp án: He’s a student.',
 'f.1': 'Câu đúng: Where Mary does live?',
 'f.10': 'Câu đúng: What does your brother do on Sundays?',
 'f.2': "Câu đúng: What's the village like?",
 'f.3': 'Câu đúng: What does your mother do?',
 'f.4': 'Câu đúng: My sister teaches at a primary school.',
 'f.5': 'Câu đúng: What does your brother look like?',
 'f.6': 'Câu đúng: My sister is slim and has long hair.',
 'f.7': 'Câu đúng: When do you do the housework?',
 'f.8': 'Câu đúng: Ben washes his clothes in the evening.',
 'f.9': 'Câu đúng: My father goes to the swimming pool on Saturdays.'}
