# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['Where were you last summer?'],
 't1.10': 'did',
 't1.11': ['Was it a big city?'],
 't1.12': 'Where were you last weekend?',
 't1.13': 'at',
 't1.14': 'painted',
 't1.15': ['What did you do there?'],
 't1.16': "No, I wasn't. I was on the beach last Sunday.",
 't1.17': 'last summer',
 't1.18': ['I painted a picture of my hometown.'],
 't1.19': 'Mùa hè vừa rồi bạn đã ở đâu?',
 't1.2': "No, I wasn't. I was at the campsite.",
 't1.20': 'was',
 't1.3': 'on',
 't1.4': 'Yes, it was.',
 't1.5': 'played',
 't1.6': ['I was in Bangkok last summer.'],
 't1.7': 'Were you at the zoo last Saturday?',
 't1.8': 'Where',
 't1.9': 'Yes, it is.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: Where were you last summer?',
 't1.10': 'Đáp án: did',
 't1.11': 'Câu đúng: Was it a big city?',
 't1.12': 'Đáp án: Where were you last weekend?',
 't1.13': 'Đáp án: at',
 't1.14': 'Đáp án: painted',
 't1.15': 'Câu đúng: What did you do there?',
 't1.16': "Đáp án: No, I wasn't. I was on the beach last Sunday.",
 't1.17': 'Đáp án: last summer',
 't1.18': 'Câu đúng: I painted a picture of my hometown.',
 't1.19': 'Đáp án: Mùa hè vừa rồi bạn đã ở đâu?',
 't1.2': "Đáp án: No, I wasn't. I was at the campsite.",
 't1.20': 'Đáp án: was',
 't1.3': 'Đáp án: on',
 't1.4': 'Đáp án: Yes, it was.',
 't1.5': 'Đáp án: played',
 't1.6': 'Câu đúng: I was in Bangkok last summer.',
 't1.7': 'Đáp án: Were you at the zoo last Saturday?',
 't1.8': 'Đáp án: Where',
 't1.9': 'Đáp án: Yes, it is.'}
