# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'a.1': 'Were you at the zoo last weekend?',
 'a.10': 'Hôm qua bạn ở bãi biển phải không? Bản word phát hành từ Tailieuchuan.vn',
 'a.2': "It's in September.",
 'a.3': 'Hôm qua bạn đã ở đâu?',
 'a.4': "No, I wasn't. I was at the campsite.",
 'a.5': 'Were you at the zoo last Saturday?',
 'a.6': 'Where were you last weekend?',
 'a.7': "No, I wasn't. I was on the beach last Sunday.",
 'a.8': 'Mùa hè vừa rồi bạn đã ở đâu?',
 'a.9': 'Where were you last summer?',
 'b.1': 'Were',
 'b.10': 'is',
 'b.2': 'was',
 'b.3': 'Where',
 'b.4': 'on',
 'b.5': 'Where',
 'b.6': 'at',
 'b.7': 'last summer',
 'b.8': 'was',
 'b.9': 'was',
 'c.1': {'blanks': [['I was at the zoo yesterday.'], ['Yes, I was.'], ['I play football.'], ['Yes, it was.'], ['Yes, it is.']]},
 'd.1': 'Were',
 'd.2': 'Where',
 'd.3': 'What',
 'd.4': 'played',
 'd.5': 'did',
 'd.6': 'painted',
 'e.1': 'He was in the countryside.',
 'e.2': 'It was peaceful.',
 'e.3': 'He flied a kite with his cousin.',
 'e.4': 'He played badminton.',
 'e.5': 'He went fishing with his grandfather.',
 'e.6': 'He painted a picture of the countryside.',
 'f.1': ['Were you on the beach last weekend?'],
 'f.10': ['I was at the campsite yesterday.'],
 'f.2': ["No, I wasn't. I was at the zoo."],
 'f.3': ['Where were you last summer?'],
 'f.4': ['I was in Bangkok last summer.'],
 'f.5': ['Was it a big city?'],
 'f.6': ['What did you do there?'],
 'f.7': ['I painted a picture of my hometown.'],
 'f.8': ['I played badminton with my cousin.'],
 'f.9': ['Where were you yesterday?'],
 'n.1': 'countryside',
 'n.10': 'Were you on the beach last summer?',
 'n.2': 'mountains',
 'n.3': ['London'],
 'n.4': ['Tokyo'],
 'n.5': 'Sydney',
 'n.6': 'Bangkok',
 'n.7': ['campsite'],
 'n.8': ['zoo'],
 'n.9': 'Where were you last weekend?'}

EXPLANATIONS = {'a.1': 'Đáp án: Were you at the zoo last weekend?',
 'a.10': 'Đáp án: Hôm qua bạn ở bãi biển phải không? Bản word phát hành từ Tailieuchuan.vn',
 'a.2': "Đáp án: It's in September.",
 'a.3': 'Đáp án: Hôm qua bạn đã ở đâu?',
 'a.4': "Đáp án: No, I wasn't. I was at the campsite.",
 'a.5': 'Đáp án: Were you at the zoo last Saturday?',
 'a.6': 'Đáp án: Where were you last weekend?',
 'a.7': "Đáp án: No, I wasn't. I was on the beach last Sunday.",
 'a.8': 'Đáp án: Mùa hè vừa rồi bạn đã ở đâu?',
 'a.9': 'Đáp án: Where were you last summer?',
 'b.1': 'Đáp án: Were',
 'b.10': 'Đáp án: is',
 'b.2': 'Đáp án: was',
 'b.3': 'Đáp án: Where',
 'b.4': 'Đáp án: on',
 'b.5': 'Đáp án: Where',
 'b.6': 'Đáp án: at',
 'b.7': 'Đáp án: last summer',
 'b.8': 'Đáp án: was',
 'b.9': 'Đáp án: was',
 'c.1': 'Where were you yesterday? → I was at the zoo yesterday.; Were you on the beach last Sunday? → Yes, I was.; What did you do last weekend? → I play '
        'football.; Was the food good? → Yes, it was.; Is it a big city? → Yes, it is.',
 'd.1': 'Đáp án: Were',
 'd.2': 'Đáp án: Where',
 'd.3': 'Đáp án: What',
 'd.4': 'Đáp án: played',
 'd.5': 'Đáp án: did',
 'd.6': 'Đáp án: painted',
 'e.1': 'Đáp án: He was in the countryside.',
 'e.2': 'Đáp án: It was peaceful.',
 'e.3': 'Đáp án: He flied a kite with his cousin.',
 'e.4': 'Đáp án: He played badminton.',
 'e.5': 'Đáp án: He went fishing with his grandfather.',
 'e.6': 'Đáp án: He painted a picture of the countryside.',
 'f.1': 'Câu đúng: Were you on the beach last weekend?',
 'f.10': 'Câu đúng: I was at the campsite yesterday.',
 'f.2': "Câu đúng: No, I wasn't. I was at the zoo.",
 'f.3': 'Câu đúng: Where were you last summer?',
 'f.4': 'Câu đúng: I was in Bangkok last summer.',
 'f.5': 'Câu đúng: Was it a big city?',
 'f.6': 'Câu đúng: What did you do there?',
 'f.7': 'Câu đúng: I painted a picture of my hometown.',
 'f.8': 'Câu đúng: I played badminton with my cousin.',
 'f.9': 'Câu đúng: Where were you yesterday?',
 'n.1': 'Đáp án: countryside',
 'n.10': 'Đáp án: Were you on the beach last summer?',
 'n.2': 'Đáp án: mountains',
 'n.3': 'Đáp án: London',
 'n.4': 'Đáp án: Tokyo',
 'n.5': 'Đáp án: Sydney',
 'n.6': 'Đáp án: Bangkok',
 'n.7': 'Đáp án: campsite',
 'n.8': 'Đáp án: zoo',
 'n.9': 'Đáp án: Where were you last weekend?'}
