# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_dc2.py"""

ANS = {'u11b5.15': ['live'],
 'u11b5.16': ['busy', 'big'],
 'u11b5.17': ['noisy'],
 'u11b5.18': ['quiet'],
 'u11b5.19': ['road', 'street'],
 'u11fill.5': ['live'],
 'u11fill.6': ['at'],
 'u11fill.7': ['road'],
 'u11fill.8': ['busy'],
 'u11fill.9': ['quiet'],
 'u11mcq.1': 'C',
 'u11mcq.2': 'B',
 'u11mcq.3': 'B',
 'u11mcq.4': 'A',
 'u11order.10': ['I live at Hai Ba Trung Street.'],
 'u11order.11': ['This is a noisy street.'],
 'u11order.12': ['There is a big school.'],
 'u11order.13': ['He lives on Hoang Van Thu Road.'],
 'u11order.14': ['The street is very quiet.'],
 'u12b5.34': 'B',
 'u12b5.35': 'C',
 'u12b5.36': 'A',
 'u12b5.37': 'B',
 'u12b5.38': 'C',
 'u12fill.26': ['farmer'],
 'u12fill.27': ['actor'],
 'u12fill.28': ['policeman'],
 'u12fill.29': ['hospital'],
 'u12fill.30': ['factory'],
 'u12match.25': {'blanks': [['Theatre'], ['Farm'], ['Hospital'], ['Office'], ['Nursing home']]},
 'u12mcq.20': 'B',
 'u12mcq.21': 'A',
 'u12mcq.22': 'C',
 'u12mcq.23': 'B',
 'u12mcq.24': 'A',
 'u12order.31': ['She is a nurse.'],
 'u12order.32': ['My brother works in a factory.'],
 'u12order.33': ['My dad is a policeman.'],
 'u13b5.54': 'B',
 'u13b5.55': 'B',
 'u13b5.56': 'A',
 'u13b5.57': 'C',
 'u13b5.58': 'C',
 'u13fill.44': ['tall'],
 'u13fill.45': ['big'],
 'u13fill.46': ['hair'],
 'u13fill.47': ['short'],
 'u13fill.48': ['round'],
 'u13match.43': {'blanks': [['Not fat, small body'],
                            ['You see with them'],
                            ['On your head, can be long/short'],
                            ['Not square, like a circle'],
                            ['A head with two eyes and a nose']]},
 'u13mcq.39': 'B',
 'u13mcq.40': 'C',
 'u13mcq.41': 'A',
 'u13mcq.42': 'B',
 'u13order.49': ['She has a round face.'],
 'u13order.50': ['He has long hair.'],
 'u13order.51': ['Her eyes are big.'],
 'u13order.52': ['She is very slim.'],
 'u13order.53': ['My brother is short.'],
 'u14b5.75': ['morning'],
 'u14b5.76': ['help with the cooking'],
 'u14b5.77': ['noon'],
 'u14b5.78': ['wash the clothes'],
 'u14b5.79': ['evening'],
 'u14b5.80': ['clean the floor'],
 'u14b5.81': ['wash the dishes'],
 'u14fill.65': ['morning'],
 'u14fill.66': ['noon'],
 'u14fill.67': ['wash'],
 'u14fill.68': ['help'],
 'u14fill.69': ['clean'],
 'u14match.64': {'blanks': [['Time when the sun rises'],
                            ['Time after lunch but before dinner'],
                            ['You do this to make the floor tidy'],
                            ['You do this with your mom in the kitchen'],
                            ['Time when it gets dark, dinner time']]},
 'u14mcq.59': 'B',
 'u14mcq.60': 'C',
 'u14mcq.61': 'C',
 'u14mcq.62': 'A',
 'u14mcq.63': 'A',
 'u14order.70': ['I get up early in the morning.'],
 'u14order.71': ['I help dad with the cooking.'],
 'u14order.72': ['She always washes the dishes.'],
 'u14order.73': ['They clean the floor.'],
 'u14order.74': ['I go shopping in the afternoon.'],
 'u15fill.88': ['shopping centre'],
 'u15fill.89': ['play tennis'],
 'u15fill.90': ['cook meals'],
 'u15fill.91': ['do yoga'],
 'u15fill.92': ['cinema'],
 'u15match.87': {'blanks': [['Cinema'], ['Sports centre'], ['Kitchen'], ['Swimming pool']]},
 'u15mcq.82': 'C',
 'u15mcq.83': 'B',
 'u15mcq.84': 'A',
 'u15mcq.85': 'B',
 'u15mcq.86': 'A',
 'u15order.93': ['I often go to the cinema.'],
 'u15order.94': ['They do yoga in the morning.'],
 'u15order.95': ['We always cook meals for dinner.'],
 'u15order.96': ['I play tennis at the sports centre.'],
 'u15order.97': ['We go to the swimming pool.'],
 'u16b5.114': ['cloudy'],
 'u16b5.115': ['bookshop'],
 'u16b5.116': ['supermarket'],
 'u16b5.117': ['food stall'],
 'u16fill.104': ['windy'],
 'u16fill.105': ['supermarket'],
 'u16fill.106': ['food stall'],
 'u16fill.107': ['cloudy'],
 'u16fill.108': ['water park'],
 'u16match.103': {'blanks': [['Weather with lots of rain'],
                             ['A place to buy many kinds of food'],
                             ['A place with many books to buy'],
                             ['A fun place to swim and play in water'],
                             ['Weather with strong air moving']]},
 'u16mcq.100': 'A',
 'u16mcq.101': 'B',
 'u16mcq.102': 'B',
 'u16mcq.98': 'B',
 'u16mcq.99': 'C',
 'u16order.109': ['I go to the bakery every morning.'],
 'u16order.110': ['The weather is sunny today.'],
 'u16order.111': ['I buy books at the bookshop.'],
 'u16order.112': ['It is very windy today.'],
 'u16order.113': ['We eat noodles at the food stall.'],
 'u17fill.123': ['turn'],
 'u17fill.124': ['get'],
 'u17fill.125': ['go straight'],
 'u17fill.126': ['stop'],
 'u17fill.127': ['right'],
 'u17match.122': {'blanks': [['Turn to your right side'],
                             ['Walk without turning'],
                             ['Don’t move anymore'],
                             ['Move in the opposite direction'],
                             ['Turn to your left side']]},
 'u17mcq.118': 'A',
 'u17mcq.119': 'B',
 'u17mcq.120': 'A',
 'u17mcq.121': 'B',
 'u17order.128': ['Go straight and turn left.'],
 'u17order.129': ['Turn right at the bookstore.'],
 'u17order.130': ['Stop at the red light.'],
 'u17order.131': ['I want to get to the zoo.'],
 'u17order.132': ['You can turn round.'],
 'u18b5.153': ['thousand'],
 'u18b5.154': ['opposite'],
 'u18b5.155': ['between'],
 'u18fill.144': ['gift shop'],
 'u18fill.145': ['opposite', 'behind'],
 'u18fill.146': ['skirt'],
 'u18fill.147': ['behind', 'opposite'],
 'u18fill.148': ['thousand'],
 'u18match.143': {'blanks': [['At the back of something'],
                             ['A place to buy small presents'],
                             ['A piece of clothing worn by girls'],
                             ['1,000'],
                             ['Across from, facing something']]},
 'u18mcq.138': 'B',
 'u18mcq.139': 'B',
 'u18mcq.140': 'A',
 'u18mcq.141': 'B',
 'u18mcq.142': 'C',
 'u18order.149': ['How much is the skirt?'],
 'u18order.150': ['I want to buy that T-shirt.'],
 'u18order.151': ['The gift shop is near the school.'],
 'u18order.152': ['It costs one thousand dong.'],
 'u19fill.162': ['roar'],
 'u19fill.163': ['beautifully', 'loudly'],
 'u19fill.164': ['giraffe'],
 'u19fill.165': ['crocodile'],
 'u19fill.166': ['loudly', 'beautifully'],
 'u19match.161': {'blanks': [['Making a lot of noise'],
                             ['Animal with a long neck'],
                             ['A big animal with a huge mouth in rivers'],
                             ['A big reptile with strong jaws'],
                             ['In a happy and cheerful way']]},
 'u19mcq.156': 'B',
 'u19mcq.157': 'C',
 'u19mcq.158': 'B',
 'u19mcq.159': 'A',
 'u19mcq.160': 'C',
 'u19order.167': ['The lion roared loudly.'],
 'u19order.168': ['Hippos can run quickly.'],
 'u19order.169': ['The bird sang beautifully.'],
 'u19order.170': ['The children are dancing merrily.'],
 'u19order.171': ['We saw the crocodile.'],
 'u20b5.188': ['We take a photo of the mountains.', 'We took a photo of the mountains.'],
 'u20b5.189': ['My brother plays card games by himself.'],
 'u20b5.190': ['They put up a tent next to the river.'],
 'u20b5.191': ['We sat by the fire and told a story.', 'We sat by the fire and tell a story.'],
 'u20b5.192': ['Every night, we sing songs around the campfire.'],
 'u20fill.178': ['sing songs', 'play card games', 'tell a story'],
 'u20fill.179': ['build a campfire'],
 'u20fill.180': ['play card games', 'sing songs', 'tell a story'],
 'u20fill.181': ['put up a tent'],
 'u20fill.182': ['tell a story', 'sing songs', 'play card games'],
 'u20match.177': {'blanks': [['Use wood to make fire'],
                             ['Use a camera to capture a moment'],
                             ['Set up something to sleep in outdoors'],
                             ['Tell a fun tale, maybe with a flashlight'],
                             ['Use cards to play with friends']]},
 'u20mcq.172': 'B',
 'u20mcq.173': 'A',
 'u20mcq.174': 'B',
 'u20mcq.175': 'B',
 'u20mcq.176': 'C',
 'u20order.183': ['They put up a tent.'],
 'u20order.184': ['We played card games.'],
 'u20order.185': ['I took a photo of the mountain.'],
 'u20order.186': ['They sang songs around the campfire.'],
 'u20order.187': ['He told a funny story.']}

EXPLANATIONS = {'u11b5.15': 'Đáp án: live',
 'u11b5.16': 'Đáp án: busy',
 'u11b5.17': 'Đáp án: noisy',
 'u11b5.18': 'Đáp án: quiet',
 'u11b5.19': 'Đáp án: road',
 'u11fill.5': 'Đáp án: live',
 'u11fill.6': 'Đáp án: at',
 'u11fill.7': 'Đáp án: road',
 'u11fill.8': 'Đáp án: busy',
 'u11fill.9': 'Đáp án: quiet',
 'u11mcq.1': 'Đáp án: C. in. Theo mẫu câu của đề cương: I live in + tên phố (on cũng có thể dùng trong tiếng Anh thực tế).',
 'u11mcq.2': 'Đáp án: B. noisy',
 'u11mcq.3': 'Đáp án: B. live',
 'u11mcq.4': 'Đáp án: A. quiet',
 'u11order.10': 'Câu đúng: I live at Hai Ba Trung Street.',
 'u11order.11': 'Câu đúng: This is a noisy street.',
 'u11order.12': 'Câu đúng: There is a big school.',
 'u11order.13': 'Câu đúng: He lives on Hoang Van Thu Road.',
 'u11order.14': 'Câu đúng: The street is very quiet.',
 'u12b5.34': 'Đáp án: B. On a farm',
 'u12b5.35': 'Đáp án: C. Nurse',
 'u12b5.36': 'Đáp án: A. Office worker',
 'u12b5.37': 'Đáp án: B. The sister',
 'u12b5.38': 'Đáp án: C. Keep the town safe',
 'u12fill.26': 'Đáp án: farmer',
 'u12fill.27': 'Đáp án: actor',
 'u12fill.28': 'Đáp án: policeman',
 'u12fill.29': 'Đáp án: hospital',
 'u12fill.30': 'Đáp án: factory',
 'u12match.25': 'Actor → Theatre; Farmer → Farm; Nurse → Hospital; Office worker → Office; Nurse (for elderly) → Nursing home',
 'u12mcq.20': 'Đáp án: B. farmer',
 'u12mcq.21': 'Đáp án: A. factory',
 'u12mcq.22': 'Đáp án: C. nurse',
 'u12mcq.23': 'Đáp án: B. nurse',
 'u12mcq.24': 'Đáp án: A. policeman',
 'u12order.31': 'Câu đúng: She is a nurse.',
 'u12order.32': 'Câu đúng: My brother works in a factory.',
 'u12order.33': 'Câu đúng: My dad is a policeman.',
 'u13b5.54': 'Đáp án: B. Ten',
 'u13b5.55': 'Đáp án: B. Tall and slim',
 'u13b5.56': 'Đáp án: A. Black',
 'u13b5.57': 'Đáp án: C. Helps her mom',
 'u13b5.58': 'Đáp án: C. Reads books or draws',
 'u13fill.44': 'Đáp án: tall',
 'u13fill.45': 'Đáp án: big',
 'u13fill.46': 'Đáp án: hair',
 'u13fill.47': 'Đáp án: short',
 'u13fill.48': 'Đáp án: round',
 'u13match.43': 'Slim → Not fat, small body; Eyes → You see with them; Hair → On your head, can be long/short; Round → Not square, like a circle; Face → A '
                'head with two eyes and a nose',
 'u13mcq.39': 'Đáp án: B. tall',
 'u13mcq.40': 'Đáp án: C. long',
 'u13mcq.41': 'Đáp án: A. slim',
 'u13mcq.42': 'Đáp án: B. face',
 'u13order.49': 'Câu đúng: She has a round face.',
 'u13order.50': 'Câu đúng: He has long hair.',
 'u13order.51': 'Câu đúng: Her eyes are big.',
 'u13order.52': 'Câu đúng: She is very slim.',
 'u13order.53': 'Câu đúng: My brother is short.',
 'u14b5.75': 'Đáp án: morning',
 'u14b5.76': 'Đáp án: help with the cooking',
 'u14b5.77': 'Đáp án: noon',
 'u14b5.78': 'Đáp án: wash the clothes',
 'u14b5.79': 'Đáp án: evening',
 'u14b5.80': 'Đáp án: clean the floor',
 'u14b5.81': 'Đáp án: wash the dishes',
 'u14fill.65': 'Đáp án: morning',
 'u14fill.66': 'Đáp án: noon',
 'u14fill.67': 'Đáp án: wash',
 'u14fill.68': 'Đáp án: help',
 'u14fill.69': 'Đáp án: clean',
 'u14match.64': 'Morning → Time when the sun rises; Afternoon → Time after lunch but before dinner; Clean the floor → You do this to make the floor tidy; Help '
                'with the cooking → You do this with your mom in the kitchen; Evening → Time when it gets dark, dinner time',
 'u14mcq.59': 'Đáp án: B. morning',
 'u14mcq.60': 'Đáp án: C. evening',
 'u14mcq.61': 'Đáp án: C. noon',
 'u14mcq.62': 'Đáp án: A. wash the dishes',
 'u14mcq.63': 'Đáp án: A. clean',
 'u14order.70': 'Câu đúng: I get up early in the morning.',
 'u14order.71': 'Câu đúng: I help dad with the cooking.',
 'u14order.72': 'Câu đúng: She always washes the dishes.',
 'u14order.73': 'Câu đúng: They clean the floor.',
 'u14order.74': 'Câu đúng: I go shopping in the afternoon.',
 'u15fill.88': 'Đáp án: shopping centre',
 'u15fill.89': 'Đáp án: play tennis',
 'u15fill.90': 'Đáp án: cook meals',
 'u15fill.91': 'Đáp án: do yoga',
 'u15fill.92': 'Đáp án: cinema',
 'u15match.87': 'Watch films → Cinema; Play tennis → Sports centre; Cook meals → Kitchen; Go swimming → Swimming pool',
 'u15mcq.82': 'Đáp án: C. cinema',
 'u15mcq.83': 'Đáp án: B. cook meals',
 'u15mcq.84': 'Đáp án: A. watch films',
 'u15mcq.85': 'Đáp án: B. sports centre',
 'u15mcq.86': 'Đáp án: A. shopping centre',
 'u15order.93': 'Câu đúng: I often go to the cinema.',
 'u15order.94': 'Câu đúng: They do yoga in the morning.',
 'u15order.95': 'Câu đúng: We always cook meals for dinner.',
 'u15order.96': 'Câu đúng: I play tennis at the sports centre.',
 'u15order.97': 'Câu đúng: We go to the swimming pool.',
 'u16b5.114': 'Đáp án: cloudy',
 'u16b5.115': 'Đáp án: bookshop',
 'u16b5.116': 'Đáp án: supermarket',
 'u16b5.117': 'Đáp án: food stall',
 'u16fill.104': 'Đáp án: windy',
 'u16fill.105': 'Đáp án: supermarket',
 'u16fill.106': 'Đáp án: food stall',
 'u16fill.107': 'Đáp án: cloudy',
 'u16fill.108': 'Đáp án: water park',
 'u16match.103': 'Rainy → Weather with lots of rain; Supermarket → A place to buy many kinds of food; Bookshop → A place with many books to buy; Water park → '
                 'A fun place to swim and play in water; Windy → Weather with strong air moving',
 'u16mcq.100': 'Đáp án: A. bakery',
 'u16mcq.101': 'Đáp án: B. rainy',
 'u16mcq.102': 'Đáp án: B. bookshop',
 'u16mcq.98': 'Đáp án: B. sunny',
 'u16mcq.99': 'Đáp án: C. weather',
 'u16order.109': 'Câu đúng: I go to the bakery every morning.',
 'u16order.110': 'Câu đúng: The weather is sunny today.',
 'u16order.111': 'Câu đúng: I buy books at the bookshop.',
 'u16order.112': 'Câu đúng: It is very windy today.',
 'u16order.113': 'Câu đúng: We eat noodles at the food stall.',
 'u17b5.133': 'Đáp án mẫu: Go straight, go straight, turn right, stop, get to the zoo.',
 'u17b5.134': 'Đáp án mẫu: Go straight, turn left, go straight, turn round, get to the bakery.',
 'u17b5.135': 'Đáp án mẫu: Go straight, go straight, turn right, turn left, stop.',
 'u17b5.136': 'Đáp án mẫu: Go straight, turn left, go straight, turn right, get to the hospital.',
 'u17b5.137': 'Đáp án mẫu: Turn right, go straight, stop, turn round, get to the supermarket.',
 'u17fill.123': 'Đáp án: turn',
 'u17fill.124': 'Đáp án: get',
 'u17fill.125': 'Đáp án: go straight',
 'u17fill.126': 'Đáp án: stop',
 'u17fill.127': 'Đáp án: right',
 'u17match.122': 'Turn right → Turn to your right side; Go straight → Walk without turning; Stop → Don’t move anymore; Turn round → Move in the opposite '
                 'direction; Turn left → Turn to your left side',
 'u17mcq.118': 'Đáp án: A. straight',
 'u17mcq.119': 'Đáp án: B. stop',
 'u17mcq.120': 'Đáp án: A. get to',
 'u17mcq.121': 'Đáp án: B. right',
 'u17order.128': 'Câu đúng: Go straight and turn left.',
 'u17order.129': 'Câu đúng: Turn right at the bookstore.',
 'u17order.130': 'Câu đúng: Stop at the red light.',
 'u17order.131': 'Câu đúng: I want to get to the zoo.',
 'u17order.132': 'Câu đúng: You can turn round.',
 'u18b5.153': 'Đáp án: thousand',
 'u18b5.154': 'Đáp án: opposite',
 'u18b5.155': 'Đáp án: between',
 'u18fill.144': 'Đáp án: gift shop',
 'u18fill.145': 'Đáp án: opposite',
 'u18fill.146': 'Đáp án: skirt',
 'u18fill.147': 'Đáp án: behind',
 'u18fill.148': 'Đáp án: thousand',
 'u18match.143': 'Behind → At the back of something; Gift shop → A place to buy small presents; Skirt → A piece of clothing worn by girls; Thousand → 1,000; '
                 'Opposite → Across from, facing something',
 'u18mcq.138': 'Đáp án: B. between',
 'u18mcq.139': 'Đáp án: B. opposite',
 'u18mcq.140': 'Đáp án: A. skirt',
 'u18mcq.141': 'Đáp án: B. dong',
 'u18mcq.142': 'Đáp án: C. near',
 'u18order.149': 'Câu đúng: How much is the skirt?',
 'u18order.150': 'Câu đúng: I want to buy that T-shirt.',
 'u18order.151': 'Câu đúng: The gift shop is near the school.',
 'u18order.152': 'Câu đúng: It costs one thousand dong.',
 'u19fill.162': 'Đáp án: roar',
 'u19fill.163': 'Đáp án: beautifully',
 'u19fill.164': 'Đáp án: giraffe',
 'u19fill.165': 'Đáp án: crocodile',
 'u19fill.166': 'Đáp án: loudly',
 'u19match.161': 'Loudly → Making a lot of noise; Giraffe → Animal with a long neck; Hippo → A big animal with a huge mouth in rivers; Crocodile → A big '
                 'reptile with strong jaws; Merrily → In a happy and cheerful way',
 'u19mcq.156': 'Đáp án: B. roar',
 'u19mcq.157': 'Đáp án: C. neck',
 'u19mcq.158': 'Đáp án: B. quickly',
 'u19mcq.159': 'Đáp án: A. quickly',
 'u19mcq.160': 'Đáp án: C. merrily',
 'u19order.167': 'Câu đúng: The lion roared loudly.',
 'u19order.168': 'Câu đúng: Hippos can run quickly.',
 'u19order.169': 'Câu đúng: The bird sang beautifully.',
 'u19order.170': 'Câu đúng: The children are dancing merrily.',
 'u19order.171': 'Câu đúng: We saw the crocodile.',
 'u20b5.188': 'Câu đúng: We take a photo of the mountains.',
 'u20b5.189': 'Câu đúng: My brother plays card games by himself.',
 'u20b5.190': 'Câu đúng: They put up a tent next to the river.',
 'u20b5.191': 'Câu đúng: We sat by the fire and told a story.',
 'u20b5.192': 'Câu đúng: Every night, we sing songs around the campfire.',
 'u20fill.178': 'Đáp án: sing songs',
 'u20fill.179': 'Đáp án: build a campfire',
 'u20fill.180': 'Đáp án: play card games',
 'u20fill.181': 'Đáp án: put up a tent',
 'u20fill.182': 'Đáp án: tell a story',
 'u20match.177': 'Build a campfire → Use wood to make fire; Take a photo → Use a camera to capture a moment; Put up a tent → Set up something to sleep in '
                 'outdoors; Tell a story → Tell a fun tale, maybe with a flashlight; Play card games → Use cards to play with friends',
 'u20mcq.172': 'Đáp án: B. built a campfire',
 'u20mcq.173': 'Đáp án: A. play card games',
 'u20mcq.174': 'Đáp án: B. put up a tent',
 'u20mcq.175': 'Đáp án: B. sing songs',
 'u20mcq.176': 'Đáp án: C. took a photo',
 'u20order.183': 'Câu đúng: They put up a tent.',
 'u20order.184': 'Câu đúng: We played card games.',
 'u20order.185': 'Câu đúng: I took a photo of the mountain.',
 'u20order.186': 'Câu đúng: They sang songs around the campfire.',
 'u20order.187': 'Câu đúng: He told a funny story.'}
