# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'When do you watch TV?',
 't1.10': ['I like watching TV.'],
 't1.11': 'What do you do in the evening?',
 't1.12': 'Do',
 't1.13': 'She washes her clothes in the evening.',
 't1.14': 'do',
 't1.15': ['She watches TV in the evening.'],
 't1.16': 'I wash the dishes in the evening.',
 't1.17': 'does',
 't1.18': 'She cleans the floor.',
 't1.19': 'studies',
 't1.2': 'What',
 't1.20': ['What does Nam do in the afternoon?'],
 't1.3': 'I do the housework in the morning.',
 't1.4': 'that',
 't1.5': ["What's your hobby, Minh?"],
 't1.6': 'What do you do in the morning?',
 't1.7': 'washes',
 't1.8': 'I watch TV.',
 't1.9': 'does'}

EXPLANATIONS = {'t1.1': 'Đáp án: When do you watch TV?',
 't1.10': 'Câu đúng: I like watching TV.',
 't1.11': 'Đáp án: What do you do in the evening?',
 't1.12': 'Đáp án: Do',
 't1.13': 'Đáp án: She washes her clothes in the evening.',
 't1.14': 'Đáp án: do',
 't1.15': 'Câu đúng: She watches TV in the evening.',
 't1.16': 'Đáp án: I wash the dishes in the evening.',
 't1.17': 'Đáp án: does',
 't1.18': 'Đáp án: She cleans the floor.',
 't1.19': 'Đáp án: studies',
 't1.2': 'Đáp án: What',
 't1.20': 'Câu đúng: What does Nam do in the afternoon?',
 't1.3': 'Đáp án: I do the housework in the morning.',
 't1.4': 'Đáp án: that',
 't1.5': "Câu đúng: What's your hobby, Minh?",
 't1.6': 'Đáp án: What do you do in the morning?',
 't1.7': 'Đáp án: washes',
 't1.8': 'Đáp án: I watch TV.',
 't1.9': 'Đáp án: does'}
