# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r1-test02',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['she', 'time', 'does', 'What', 'have', 'breakfast?']},
                                  {'id': 't1.2',
                                   'o': ["I get up at six o'clock.",
                                         'She gets up at five thirty.',
                                         "Let's have breakfast.",
                                         "I have breakfast at seven o'clock."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What time do you have breakfast?"',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ["It's Sunday today.", 'I do housework.', "She's from Thailand.", 'I go to school on Mondays.'],
                                   'plain': True,
                                   'q': 'A: What do you do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['I go to school.', "I'm from England.", "No, I can't.", "She goes to school at seven o'clock.", 'I want some water.'],
                                   'plain': True,
                                   'q': 'What do you want to drink, Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'o': ['Japan', 'English', 'Korea'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: Lan: Wow. So you're _____.",
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ["o'clock", 'at', 'lunch', 'have', 'at', 'eleven', 'school.', 'They']},
                                  {'id': 't1.7',
                                   'o': ['What time is it?', 'What day is it today?', 'What do you do on Wednesdays?', 'What time does she go to school?'],
                                   'plain': True,
                                   'q': "Câu “It's Saturday” trả lời cho câu hỏi nào sau đây?",
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['She wants to drink some lemonade.', 'I want some grapes.', "It's in December.", 'She wants some chips.'],
                                   'plain': True,
                                   'q': 'A: What does Mai want to eat?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['I go to school.', "I'm from England.", "No, I can't.", "She goes to school at seven o'clock.", 'I want some water.'],
                                   'plain': True,
                                   'q': 'Can you play the guitar, Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['When', 'Who', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Mary: Yes, I am. And you? _____ are you from?',
                                   't': 'mcq'},
                                  {'id': 't1.11', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Lan', 'Sundays?', 'do', 'does', 'on', 'What']},
                                  {'id': 't1.12',
                                   'o': ['I visit my grandparents on Saturdays.',
                                         'He does his housework.',
                                         'She does housework on Saturdays.',
                                         'She goes to school on Mondays.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does Mai do on Saturdays?"',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ["It's in November.", 'I want some juice.', 'Linh wants some water.', 'I study at school.'],
                                   'plain': True,
                                   'q': "A: When's your birthday, Linh?",
                                   't': 'mcq'},
                                  {'id': 't1.14', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Mary', 'on', 'Sundays?', 'do', 'What', 'does']},
                                  {'id': 't1.15',
                                   'o': ["It's in May.", "It's Monday today.", "She gets up at six o'clock.", 'She studies at school.'],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “When's her birthday?”?",
                                   't': 'mcq'},
                                  {'id': 't1.16',
                                   'o': ['in', 'at', 'on', 'with'],
                                   'plain': True,
                                   'q': 'A: What does Mai do _____________ Sunday mornings?',
                                   't': 'mcq'},
                                  {'id': 't1.17', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Ben?', 'you', 'are', 'doing,', 'What']},
                                  {'id': 't1.18',
                                   'o': ['I want some lemonade.', 'He wants some water.', 'They want some grapes.', 'She wants some milk.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does Lan want to drink?”?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['Saturday', 'today', 'December', 'afternoon'],
                                   'plain': True,
                                   'q': 'A: What do you do on Sunday _____________, Ben?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'birthday?', "When's", "brother's"]}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Review 1: Kiểm tra 2',
 'unit': 'Review1'}
