# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['Why do you like Art?'],
 't1.10': 'Because',
 't1.11': ['What subjects do you have today?'],
 't1.12': 'Because I want to be a singer.',
 't1.13': 'Art',
 't1.14': ['I have Vietnamese, English and Maths.'],
 't1.15': 'Why do you like Art?',
 't1.16': 'Music',
 't1.17': ['I have Music on Fridays.'],
 't1.18': 'Why do you like English?',
 't1.19': 'subject',
 't1.2': 'Why do you like Music?',
 't1.20': ['Why do you like English?'],
 't1.3': 'PE',
 't1.4': 'I have it on Friday.',
 't1.5': 'Art',
 't1.6': ['Because I want to become a painter.'],
 't1.7': 'Because I want to be a Maths teacher.',
 't1.8': 'Why',
 't1.9': 'Because I want to be a maths teacher.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: Why do you like Art?',
 't1.10': 'Đáp án: Because',
 't1.11': 'Câu đúng: What subjects do you have today?',
 't1.12': 'Đáp án: Because I want to be a singer.',
 't1.13': 'Đáp án: Art',
 't1.14': 'Câu đúng: I have Vietnamese, English and Maths.',
 't1.15': 'Đáp án: Why do you like Art?',
 't1.16': 'Đáp án: Music',
 't1.17': 'Câu đúng: I have Music on Fridays.',
 't1.18': 'Đáp án: Why do you like English?',
 't1.19': 'Đáp án: subject',
 't1.2': 'Đáp án: Why do you like Music?',
 't1.20': 'Câu đúng: Why do you like English?',
 't1.3': 'Đáp án: PE',
 't1.4': 'Đáp án: I have it on Friday.',
 't1.5': 'Đáp án: Art',
 't1.6': 'Câu đúng: Because I want to become a painter.',
 't1.7': 'Đáp án: Because I want to be a Maths teacher.',
 't1.8': 'Đáp án: Why',
 't1.9': 'Đáp án: Because I want to be a maths teacher.'}
