# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u13-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What does your brother look like?', 'Do you have a brother?', 'Is he your brother?', 'Where does he live?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn có anh trai không?.”',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['do', 'does', 'is', 'are'], 'plain': True, 'q': 'What ____________ she look like?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['Yes, I do.', 'He is big and short.', "It's my brother.", "He's a student.", 'She is tall and slim.'],
                                   'plain': True,
                                   'q': "Who's that?",
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['How much', 'How many', 'How old', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ people are there in your family?',
                                   't': 'mcq'},
                                  {'id': 't1.5',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['brother', 'have', 'Mai?', 'sister,', 'you', 'or', 'a', 'a', 'Do']},
                                  {'id': 't1.6',
                                   'o': ['What does she do?', 'Where does she live?', 'Where does she work?', 'What does she look like?'],
                                   'plain': True,
                                   'q': 'Câu “She is slim." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['old', 'high', 'much', 'many'], 'plain': True, 'q': 'How ____________ is your mother, Lan?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['Yes, I do.', 'He is big and short.', "It's my brother.", "He's a student.", 'She is tall and slim.'],
                                   'plain': True,
                                   'q': 'What does he do?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['two', 'three', 'four', 'five'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: There are _____ people: my parents, my brother and me.',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['look', 'brother', 'What', 'your', 'does', 'like?']},
                                  {'id': 't1.11',
                                   'o': ["He's a teacher.", "He's tall and thin.", 'He works on a farm.', 'He lives in a busy street.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does he look like?"',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'o': ['big', 'tall', 'fat', 'round'], 'plain': True, 'q': 'My sister is __________ and slim.', 't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['Yes, I do.', 'He is big and short.', "It's my brother.", "He's a student.", 'She is tall and slim.'],
                                   'plain': True,
                                   'q': 'Do you have a sister, Lan?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['How', 'What', 'How old', 'How many'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ is your brother?',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['tall', 'brother', 'and', 'face.', 'has', 'a', 'My', 'round', 'is']},
                                  {'id': 't1.16',
                                   'o': ['What does she do?', 'What does she look like?', 'Where does she work?', 'Where does she live?'],
                                   'plain': True,
                                   'q': 'Câu: "She has a long hair" trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['What', 'Where', 'How', 'When'],
                                   'plain': True,
                                   'q': '____________ does your teacher look like?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['Yes, I do.', 'He is big and short.', "It's my brother.", "He's a student.", 'She is tall and slim.'],
                                   'plain': True,
                                   'q': 'What does she look like?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['is', 'does', 'do', 'are'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What _____ she look like?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['father', 'short', 'hair.', 'My', 'has']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 13 – Appearance: Kiểm tra 1',
 'unit': 13}
