# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u14-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['What do you do?', 'What do you do in the morning?', 'When do you watch TV?', 'What day is it today?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi ai đó làm việc gì đó khi nào?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['When', 'Where', 'What', 'How'],
                                   'plain': True,
                                   'q': 'A: ____________do you do in the evening?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['She cleans the floor.',
                                         'I do the housework in the morning.',
                                         'I read books in the afternoon.',
                                         'She washes her clothes in the evening.',
                                         'I watch TV.'],
                                   'plain': True,
                                   'q': 'When do you do the housework?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'],
                                   'plain': True,
                                   'q': "Chọn từ cho chỗ trống: A: Who's _____?",
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'Minh?', 'hobby,', "What's"]},
                                  {'id': 't1.6',
                                   'o': ['What do you do in the afternoon?',
                                         'What do you do in the morning?',
                                         'What do you do in the evening?',
                                         'When do you wash the clothes?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi bạn làm gì vào buổi sáng?',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['wash', 'washes', 'watching', 'to wash'],
                                   'plain': True,
                                   'q': 'She ______________ her clothes in the evening.',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['She cleans the floor.',
                                         'I do the housework in the morning.',
                                         'I read books in the afternoon.',
                                         'She washes her clothes in the evening.',
                                         'I watch TV.'],
                                   'plain': True,
                                   'q': 'What do you do on Saturdays?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What _____ she do?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['watching', 'I', 'TV.', 'like']},
                                  {'id': 't1.11',
                                   'o': ['Where do you work?',
                                         'What do you do in the evening?',
                                         'When do you wash your clothes?',
                                         'When do you clean the floor?'],
                                   'plain': True,
                                   'q': 'Câu “I clean the floor" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['Are', 'Is', 'Do', 'Does'],
                                   'plain': True,
                                   'q': 'A: ______________ you wash your clothes in the evening?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['She cleans the floor.',
                                         'I do the housework in the morning.',
                                         'I read books in the afternoon.',
                                         'She washes her clothes in the evening.',
                                         'I watch TV.'],
                                   'plain': True,
                                   'q': 'When does she wash her clothes?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: What does she _____ on Saturdays?',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['evening.', 'TV', 'the', 'She', 'in', 'watches']},
                                  {'id': 't1.16',
                                   'o': ['I wash the dishes in the evening.', 'I wash my clothes.', 'Yes, I do.', 'I help my mum with the cooking.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “When do you wash the dishes?”?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'What ______________ she do in the morning?',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['She cleans the floor.',
                                         'I do the housework in the morning.',
                                         'I read books in the afternoon.',
                                         'She washes her clothes in the evening.',
                                         'I watch TV.'],
                                   'plain': True,
                                   'q': 'What does she do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['do', 'helps', 'that', 'cleans', 'studies', 'does'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: She _____ English.',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['do', 'afternoon?', 'in', 'the', 'does', 'What', 'Nam']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 14 – Daily activities: Kiểm tra 1',
 'unit': 14}
