# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'l1.1': 'C',
 'l1.2': 'A',
 'l1.3': 'B',
 'l1.4': 'C',
 'l2.5': '2',
 'l2.6': '4',
 'l2.7': '1',
 'l2.8': '3',
 'l3.10': '1',
 'l3.11': '4',
 'l3.12': '2',
 'l3.9': '3',
 'l4.13': ['painter'],
 'l4.14': ['Thailand'],
 'l4.15': ['school'],
 'l4.16': ['Friday', 'Fridays'],
 'r1.17': {'blanks': [['D'], ['A'], ['E'], ['C']]},
 'r2.18': 'A',
 'r2.19': 'C',
 'r2.20': 'B',
 'r3.21': 'T',
 'r3.22': 'F',
 'r3.23': 'T',
 'w1.24': ['running'],
 'w1.25': ['grapes'],
 'w1.26': ['mountains'],
 'w2.27': ['Where is she from?'],
 'w2.28': ['My birthday is in February.'],
 'w2.29': ['I get up at five forty-five.']}

EXPLANATIONS = {'l1.1': 'Đáp án C (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.2': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.3': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l1.4': 'Đáp án C (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'l2.5': 'Tranh A ứng với câu 2 (theo đáp án của đề).',
 'l2.6': 'Tranh C ứng với câu 4 (theo đáp án của đề).',
 'l2.7': 'Tranh D ứng với câu 1 (theo đáp án của đề).',
 'l2.8': 'Tranh E ứng với câu 3 (theo đáp án của đề).',
 'l3.10': 'Tranh C ứng với câu 1 (theo đáp án của đề).',
 'l3.11': 'Tranh D ứng với câu 4 (theo đáp án của đề).',
 'l3.12': 'Tranh E ứng với câu 2 (theo đáp án của đề).',
 'l3.9': 'Tranh A ứng với câu 3 (theo đáp án của đề).',
 'l4.13': 'Đáp án: painter',
 'l4.14': 'Đáp án: Thailand',
 'l4.15': 'Đáp án: school',
 'l4.16': 'Đáp án: Friday',
 'r1.17': 'Đáp án theo đáp án của đề: birthday party–D, buildings–A, study at school–E, play the guitar–C',
 'r2.18': 'Đáp án: A. from',
 'r2.19': 'Đáp án: C. September',
 'r2.20': 'Đáp án: B. When’s',
 'r3.21': 'Đáp án: True (theo đáp án của đề).',
 'r3.22': 'Đáp án: False (theo đáp án của đề).',
 'r3.23': 'Đáp án: True (theo đáp án của đề).',
 'w1.24': 'Từ đúng: running',
 'w1.25': 'Từ đúng: grapes',
 'w1.26': 'Từ đúng: mountains',
 'w2.27': 'Câu đúng: Where is she from?',
 'w2.28': 'Câu đúng: My birthday is in February.',
 'w2.29': 'Câu đúng: I get up at five forty-five.'}
