# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-r3-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['They live in Nguyen Kiem street.',
                                         'You live in Phan Van Tri Street.',
                                         'She lives in Le Lai Street.',
                                         "It's a big house."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: Where does Mai live?',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['is', 'are', 'do', 'does'], 'plain': True, 'q': 'A: Where Nam live?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['He watches TV in the evening.',
                                         'She lives at 10A Oxford Street.',
                                         'She goes to the sports centre.',
                                         'She works on a farm.',
                                         "He's tall and thin."],
                                   'plain': True,
                                   'q': 'Where does Mary live?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['What', 'Who', 'When', 'Where'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ is that girl, Nam?',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Mary', 'live?', 'does', 'Where']},
                                  {'id': 't1.6',
                                   'o': ['I live in a small house.',
                                         'He lives in a big house in a village.',
                                         "It's a small house.",
                                         'She lives in a big house.'],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi: “What's the house like?”",
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['on', 'at', 'in', 'with'],
                                   'plain': True,
                                   'q': 'He lives _______________ 311 Le Loi Street.',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['He watches TV in the evening.',
                                         'She lives at 10A Oxford Street.',
                                         'She goes to the sports centre.',
                                         'She works on a farm.',
                                         "He's tall and thin."],
                                   'plain': True,
                                   'q': 'Where does she work?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['What', 'Where', 'When', 'How'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: _____ does he live?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['village', "What's", 'like?', 'the']},
                                  {'id': 't1.11',
                                   'o': ['Where does she live?', 'What does Mai do?', 'Where does she work?', 'Where does your brother work?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi về nghề nghiệp của ai đó?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['farmer', 'nurse', 'worker', 'student'],
                                   'plain': True,
                                   'q': "My father works at a factory. He's a ____________.",
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['He watches TV in the evening.',
                                         'She lives at 10A Oxford Street.',
                                         'She goes to the sports centre.',
                                         'She works on a farm.',
                                         "He's tall and thin."],
                                   'plain': True,
                                   'q': 'What does your cousin look like?',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['do', 'does', 'is', 'are'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: B: He _____ a student.',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do?', 'your', 'What', 'mother', 'does']},
                                  {'id': 't1.16',
                                   'o': ['What do you do?', 'Where does Nam work?', 'Where does your father work?', 'What does Nam do?'],
                                   'plain': True,
                                   'q': 'Câu: “He’s a policeman.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['at a factory', 'on a farm', 'at a primary school', 'in a hospital'],
                                   'plain': True,
                                   'q': 'My aucle is a farmer. He works ____________.',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['He watches TV in the evening.',
                                         'She lives at 10A Oxford Street.',
                                         'She goes to the sports centre.',
                                         'She works on a farm.',
                                         "He's tall and thin."],
                                   'plain': True,
                                   'q': 'What does Ben do in the evening?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['go', 'to go', 'goes', 'going'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: A: Where does he _____ on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['at', 'school.', 'a', 'primary', 'sister', 'My', 'teaches']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Review 3: Kiểm tra 1',
 'unit': 'Review3'}
