# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u1-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ["What's your name?", "Who's that?", 'How are you?', 'Where are you from?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây dùng để hỏi tên của bạn?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['How are you today?', 'Where are you from?', "Where's he from?", "Where's she from?"],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi bạn đến từ đâu?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ["I'm fine, thank you.", "She's nine.", "I'm from Malaysia.", "She's from Thailand."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where’s she from?"',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['Bạn đến từ Singapore.', 'Cô ấy đến từ Singapore.', 'Anh ấy đến từ Singapore.', 'Tôi đến từ Singapore.'],
                                   'plain': True,
                                   'q': 'Câu “He\'s from Singapore." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['Bạn đến từ đâu?', 'Cô ấy đến từ đâu?', 'Anh ấy đến từ đầu?', 'Họ đến từ đâu?'],
                                   'plain': True,
                                   'q': 'Câu “Where\'s he from?" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ["I'm from Japan.", "He's from Japan.", "They're from Japan.", "She's from Japan."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi “Where\'s he from?"',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ["Where's she from?", "Where's he from?", 'Where are you from?', 'Where are they from?'],
                                   'plain': True,
                                   'q': 'Câu "I\'m from Australia" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ["I'm fine, thank you.", "I'm from Australia.", "It's my new friend.", "She's from Japan."],
                                   'plain': True,
                                   'q': "Câu nào sau đây trả lời cho câu hỏi “Who's that”?",
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['Bạn tôi đến từ Nhật Bản.', 'Đó là bạn mới của tôi.', 'Cô ấy đến từ đâu?', 'Bạn mới của tôi đến từ Nhật Bản.'],
                                   'plain': True,
                                   'q': 'Câu “It’s my new friend." có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ["Where's he from?", "Who's that?", 'Where are you from?', "Where's she from?"],
                                   'plain': True,
                                   'q': 'Câu “She’s from Malaysia." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['is', 'am', 'are', 'do'], 'plain': True, 'q': 'Where __________ you from?', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['are', 'is', 'am', 'does.'], 'plain': True, 'q': 'Where __________ he from?', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['are', 'is', 'am', 'does'], 'plain': True, 'q': 'Where __________ Ben and Mary from?', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['is', 'am', 'are', 'do'], 'plain': True, 'q': 'Where __________ Helena from?', 't': 'mcq'},
                                  {'id': 'b.5', 'o': ['are', 'is', 'am', 'does'], 'plain': True, 'q': 'Where __________ they from?', 't': 'mcq'},
                                  {'id': 'b.6', 'o': ['are', 'is', 'am', 'does'], 'plain': True, 'q': 'She __________ from Spain.', 't': 'mcq'},
                                  {'id': 'b.7', 'o': ['are', 'is', 'am', 'does'], 'plain': True, 'q': 'I __________ from Japan.', 't': 'mcq'},
                                  {'id': 'b.8', 'o': ['is', 'am', 'do', 'are'], 'plain': True, 'q': 'They __________ from the USA.', 't': 'mcq'},
                                  {'id': 'b.9', 'o': ['is', 'am', 'are', 'do'], 'plain': True, 'q': 'John __________ from Australia.', 't': 'mcq'},
                                  {'id': 'b.10', 'o': ['is', 'does', 'are', 'am'], 'plain': True, 'q': 'Lucy __________ from Malaysia.', 't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['How are you, Mai?', "Where's Mary from?", "Who's that?", 'Where are Ben and Bill from?', "Where's Minh from?"],
                                   'o': ["They're from Australia.", "I'm fine, thank you.", "He's from Vietnam.", "She's from America.", "It's my new friend."],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['too', 'friend', 'Bill', 'from', 'Australia'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['too', 'friend', 'Bill', 'from', 'Australia'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['too', 'friend', 'Bill', 'from', 'Australia'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['too', 'friend', 'Bill', 'from', 'Australia'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['too', 'friend', 'Bill', 'from', 'Australia'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': "Nam: Hello, I'm Nam.<br>Bill: Hello, Nam. I'm <b>(1)&nbsp;______</b>.<br>Nam: Where are you <b>(2)&nbsp;______</b>, "
                                   "Bill?<br>Bill: I'm from <b>(3)&nbsp;______</b>, And you?<br>Nam: I'm from Vietnam. Who's that?<br>Bill: It's my "
                                   "<b>(4)&nbsp;______</b>, Lucy. She's from England.<br>Nam: Nice to see you, Lucy.<br>Lucy: Nice to see you, "
                                   '<b>(5)&nbsp;______</b>.'}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and tick T (True) or F (False). (Đọc và chọn Đúng/Sai.)',
                        'items': [{'id': 'e.1', 'q': 'Aki is nine years old.', 't': 'tf'},
                                  {'id': 'e.2', 'q': 'Aki is from Korea.', 't': 'tf'},
                                  {'id': 'e.3', 'q': 'Adam is from Thailand.', 't': 'tf'},
                                  {'id': 'e.4', 'q': 'Mary is from England.', 't': 'tf'},
                                  {'id': 'e.5', 'q': 'Malee is from Malaysia.', 't': 'tf'}],
                        'passage': "Hello. I'm Aki. I'm nine years old. I'm from Japan. I have three new friends, Adam, Mary and Malee. Adam is from Malaysia. "
                                   'Mary is from England and Malee is from Thailand. They are my good friends.'}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['My', 'name', 'Minh.', 'is']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['years', 'eight', "I'm", 'old.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['England.', 'from', 'Peter', 'is']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['from?', 'Where', 'she', 'is']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['America.', 'is', 'Lisa', 'from']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'Mary.', 'my', 'friend,', 'This']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'from?', 'he', 'Where']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Thailand.', 'Malee', 'from', 'is']},
                                  {'id': 'f.9', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['friends.', 'good', 'are', 'my', 'They']},
                                  {'id': 'f.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'you', 'from?', 'Where']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'},
           {'audio': True,
            'groups': [{'id': 'n',
                        'instr': 'Nghe file âm thanh và làm các câu theo số thứ tự trong bài nghe.',
                        'items': [{'id': 'n.1',
                                   'o': ["Hi, I'm from Australia.", "Hi, I'm from America."],
                                   'plain': True,
                                   'q': 'Câu 1. Hi. Where are you from?',
                                   't': 'mcq'},
                                  {'id': 'n.2',
                                   'o': ["Hi. I'm from America.", "Hi. I'm from Britain."],
                                   'plain': True,
                                   'q': 'Câu 2. Hello. Where are you from?',
                                   't': 'mcq'},
                                  {'id': 'n.3', 'o': ["I'm from America.", "I'm from Thailand."], 'plain': True, 'q': 'Câu 3. Where are you from?', 't': 'mcq'},
                                  {'id': 'n.4',
                                   'o': ["I'm from Singapore.", "I'm from Vietnam."],
                                   'plain': True,
                                   'q': 'Câu 4. Where are you from?',
                                   't': 'mcq'},
                                  {'id': 'n.5', 'q': "Câu 5. 1- I'm from {_}", 't': 'fill'},
                                  {'id': 'n.6',
                                   'q': "Câu 6. 2- He's from {_} Hello, I'm (7)_________________. I'm from (8)______________. Where are you from? Hello, Minh. "
                                        "I'm (9)__________________. I'm from (10)_________________.",
                                   't': 'fill'},
                                  {'id': 'n.7', 'q': 'Câu 7. {_}', 't': 'fill'},
                                  {'id': 'n.8', 'q': 'Câu 8. {_}', 't': 'fill'},
                                  {'id': 'n.9', 'q': 'Câu 9. {_}', 't': 'fill'},
                                  {'id': 'n.10', 'q': 'Câu 10. {_}', 't': 'fill'},
                                  {'id': 'n.11', 'o': ['America', 'Malaysia'], 'plain': True, 'q': "Câu 11. 1- She's from ______________.", 't': 'mcq'},
                                  {'id': 'n.12', 'o': ['Britain', 'Australia'], 'plain': True, 'q': "Câu 12. 2- He's from________________.", 't': 'mcq'}]}],
            'id': 'nghe',
            'mode': 'practice',
            'title': 'Luyện nghe'}],
 'theory': '<h3>Ghi nhớ</h3><p>1. Cách hỏi bạn đến từ đâu và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>Where '
           "are you from?<br>(Bạn đến từ đâu?)</td><td>I am/ I'm + from + tên nước thành phố...<br>(Tôi đến từ......)</td></tr><tr><td>Ví dụ:<br>A: Where are "
           'you from? (Bạn đến từ đâu?)<br>B: Im from Japan. (Tôi đến từ Nhật Bản.)</td></tr></table><p>2. Cách hỏi một người nào đó đến từ đâu và cách trả '
           'lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>Where is she/he/(tên riêng) from?<br>(Cô ấy/Anh ấy/(tên riêng) '
           'đến từ đâu?)</td><td>She/He/(tên riêng) is + from + tên nước/ thành phố/...<br>(Cô ấy/Anh ấy/(tên riêng) đến từ....)</td></tr><tr><td>Ví dụ:<br>A: '
           'Where is she from? (Cô ấy đến từ đâu?)<br>B: She is from Japan. (Cô ấy đến từ Nhật Bản.)</td></tr></table><p>3. Cách hỏi một nhóm người nào đó đến '
           'từ đâu và cách trả lời:</p><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>Where are they from?<br>(Họ đến từ '
           'đâu?)</td><td>They are + from + tên nước/ thành phố/...<br>(Họ đến từ......)</td></tr><tr><td>Ví dụ:<br>A: Where are they from? (Họ đến từ '
           'đâu?)<br>B: They are from Japan. (Họ đến từ Nhật Bản.)</td></tr></table>',
 'title': 'Unit 1 – My friends: Luyện tập',
 'unit': 1}
