# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-on2-de14',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'Question 1. Listen and tick or cross (nghe, tranh đúng thì tick ✓, sai thì cross ✗). Ví dụ: 0 – ✗.',
                        'items': [{'id': 'l1.1',
                                   'img': 'l1_1.png',
                                   'q': 'Nghe câu số 1: nội dung nghe có khớp với tranh không? (True = tick ✓, False = cross ✗)',
                                   't': 'tf'},
                                  {'id': 'l1.2',
                                   'img': 'l1_2.png',
                                   'q': 'Nghe câu số 2: nội dung nghe có khớp với tranh không? (True = tick ✓, False = cross ✗)',
                                   't': 'tf'},
                                  {'id': 'l1.3',
                                   'img': 'l1_3.png',
                                   'q': 'Nghe câu số 3: nội dung nghe có khớp với tranh không? (True = tick ✓, False = cross ✗)',
                                   't': 'tf'},
                                  {'id': 'l1.4',
                                   'img': 'l1_4.png',
                                   'q': 'Nghe câu số 4: nội dung nghe có khớp với tranh không? (True = tick ✓, False = cross ✗)',
                                   't': 'tf'}]},
                       {'id': 'l2',
                        'instr': 'Question 2. Listen and circle A, B or C (nghe và chọn tranh đúng).',
                        'items': [{'id': 'l2.5',
                                   'img': 'l2_1.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 1 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.6',
                                   'img': 'l2_2.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 2 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.7',
                                   'img': 'l2_3.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 3 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'l2.8',
                                   'img': 'l2_4.png',
                                   'o': ['A', 'B', 'C'],
                                   'plain': True,
                                   'q': 'Nghe câu số 4 và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'l3',
                        'instr': 'Question 3. Listen and complete (nghe và hoàn thành câu). Ví dụ: What do you do in the morning? → I wash my clothes.',
                        'items': [{'id': 'l3.9', 'q': 'Do you want to go to the food store?<br>→ {_}', 't': 'fill'},
                                  {'id': 'l3.10', 'q': 'What does it say?<br>→ It says “{_}”.', 't': 'fill'},
                                  {'id': 'l3.11', 'q': 'What does he do on Sundays?<br>→ He {_}.', 't': 'fill'},
                                  {'id': 'l3.12', 'q': 'What does she look like?<br>→ She has {_}.', 't': 'fill'}]},
                       {'id': 'r1',
                        'instr': 'Question 4. Read and odd one out (chọn từ khác loại). Ví dụ: Street – Road – City – Busy → D.',
                        'items': [{'id': 'r1.13', 'o': ['nursing home', 'bank', 'policeman', 'hospital'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'r1.14', 'o': ['swimming pool', 'cinema', 'water park', 'between'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'r1.15', 'o': ['weather', 'cloudy', 'rainy', 'windy'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'r1.16', 'o': ['beautifully', 'sunny', 'loudly', 'merrily'], 'q': 'Chọn từ khác loại.', 't': 'mcq'},
                                  {'id': 'r1.17', 'o': ['crocodile', 'giraffe', 'clothes', 'hippo'], 'q': 'Chọn từ khác loại.', 't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'Question 5. Read and complete with one word or phrase (đọc và hoàn thành). Ví dụ: Her name is Jenny.',
                        'items': [{'id': 'r2.18', 'q': 'Jenny’s mother is a {_}.', 't': 'fill'},
                                  {'id': 'r2.19', 'q': 'The street is {_}.', 't': 'fill'},
                                  {'id': 'r2.20', 'q': '{_}, it was rainy.', 't': 'fill'},
                                  {'id': 'r2.21', 'q': 'The zoo is {_} the house.', 't': 'fill'},
                                  {'id': 'r2.22', 'q': 'Jenny loves peacocks because they {_}.', 't': 'fill'}],
                        'passage': '<p>I’m Jenny. My father is a farmer and my mother is a nurse. We live at 8 Thanh Nam Street. It’s a quiet street. My '
                                   'father works on the farm every day but my mother doesn’t work at a hospital at the weekend. Last weekend, it was rainy but '
                                   'today it’s sunny. We are going to the zoo behind our house. I love peacocks there because they dance beautifully.</p>'},
                       {'id': 'r3',
                        'instr': 'Question 6. Look and write (nhìn tranh và hoàn thành câu). Ví dụ: What does it say? – It says “go straight”.',
                        'items': [{'id': 'r3.23', 'img': 'r3_1.png', 'q': 'What does he do?<br>He is {_}.', 't': 'fill'},
                                  {'id': 'r3.24', 'img': 'r3_2.png', 'q': 'When do you watch TV?<br>I watch TV {_}.', 't': 'fill'},
                                  {'id': 'r3.25', 'img': 'r3_3.png', 'q': 'Where’s the book shop?<br>It’s {_} the sports shop.', 't': 'fill'},
                                  {'id': 'r3.26', 'img': 'r3_4.png', 'q': 'What are these animals?<br>They are {_}.', 't': 'fill'},
                                  {'id': 'r3.27', 'img': 'r3_5.png', 'q': 'How can I get to the supermarket?<br>Go straight and {_}.', 't': 'fill'}]},
                       {'id': 'w1',
                        'instr': 'Question 7. Rearrange the words to make complete sentences (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'w1.28',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['is', 'dong.', 'thousand', 'seventy', 'The', 'skirt']},
                                  {'id': 'w1.29', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['these', 'animals?', 'What', 'are']},
                                  {'id': 'w1.30',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['He', 'a', 'up', 'at', 'is', 'tent', 'the', 'putting', 'campsite.']},
                                  {'id': 'w1.31',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Do', 'the', 'want', 'to', 'me?', 'go', 'park', 'to', 'you', 'with', 'water']},
                                  {'id': 'w1.32',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['mother', 'does', 'on', 'Tuesdays?', 'go', 'your', 'Where']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Ôn HK2 – Đề 14',
 'unit': 'OnHK2'}
