# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4_dc2.py"""

SET = {'grade': 4,
 'id': 'lop4-dc2-a',
 'pages': [{'groups': [{'id': 'e1',
                        'instr': 'Exercise 1. Match each question with a suitable answer. (Nối câu hỏi với câu trả lời phù hợp.)',
                        'items': [{'id': 'e1.1',
                                   'left': [{'t': 'Where does she live?'},
                                            {'t': 'Do you live at 9 Quang Trung Road?'},
                                            {'t': 'Where was he last weekend?'},
                                            {'t': 'What’s the city like?'},
                                            {'t': 'Is the village noisy?'}],
                                   'o': ['No, it isn’t. It is quiet and beautiful.',
                                         'She lives in Le Lai Street.',
                                         'Yes, I do.',
                                         'He was at Green Hotel.',
                                         'It’s big and busy.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'e2',
                        'instr': 'Exercise 2. Read and circle the best answer. (Chọn đáp án đúng nhất.)',
                        'items': [{'id': 'e2.2', 'o': ['What', 'When', 'Where', 'How'], 'q': '______ do you live?', 't': 'mcq'},
                                  {'id': 'e2.3', 'o': ['you', 'I', 'we', 'she'], 'q': 'Where does ______ live?', 't': 'mcq'},
                                  {'id': 'e2.4', 'o': ['do', 'does', 'was', 'are'], 'q': 'Where ______ they live?', 't': 'mcq'},
                                  {'id': 'e2.5', 'o': ['in', 'on', 'at', 'from'], 'q': 'I live ______ 88 Hai Ba Trung Street.', 't': 'mcq'},
                                  {'id': 'e2.6', 'o': ['live', 'lives', 'lived', 'living'], 'q': 'He ______ in Oxford Road.', 't': 'mcq'},
                                  {'id': 'e2.7', 'o': ['busy', 'noisy', 'small', 'quiet'], 'q': 'Hoa lives in a ______ flat.', 't': 'mcq'},
                                  {'id': 'e2.8', 'o': ['in', 'on', 'at', 'from'], 'q': 'My grandmother lives ______ a big city', 't': 'mcq'},
                                  {'id': 'e2.9', 'o': ['is', 'am', 'are', 'do'], 'q': 'What ______ city like?', 't': 'mcq'},
                                  {'id': 'e2.10',
                                   'o': ['quiet', 'nice', 'excellent', 'busy'],
                                   'q': 'It’s a ______ road. There are so many cars and motorbikes.',
                                   't': 'mcq'},
                                  {'id': 'e2.11',
                                   'o': ['quiet', 'beautiful', 'excellent', 'noisy'],
                                   'q': 'It’s a ______ street. No one lives there.',
                                   't': 'mcq'}]},
                       {'id': 'e3',
                        'instr': 'Exercise 3. Reorder the words to make sentences. (Sắp xếp từ thành câu.)',
                        'items': [{'id': 'e3.12', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['street', 'is', 'What', 'the', 'like?']},
                                  {'id': 'e3.13',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Street.', 'lives', 'in', 'Hai', 'She', 'Ba', 'Trung']},
                                  {'id': 'e3.14',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['is', 'and', 'quiet', 'a', 'It', 'beautiful', 'village.']},
                                  {'id': 'e3.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['at', 'My', 'Hotel.', 'are', 'Green', 'parents']},
                                  {'id': 'e3.16',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['in', 'aunt', 'a', 'house', 'beautiful', 'My', 'garden.', 'lives', 'big', 'with', 'a']}]},
                       {'id': 'e4',
                        'instr': 'Exercise 4. Match each question with a suitable answer. (Nối câu hỏi với câu trả lời phù hợp.)',
                        'items': [{'id': 'e4.17',
                                   'left': [{'t': 'What does your mother do?'},
                                            {'t': 'Does she work on a farm?'},
                                            {'t': 'Where does he work?'},
                                            {'t': 'Do they work at a factory?'},
                                            {'t': 'How many people are there in your family?'}],
                                   'o': ['She works at a nursing home.',
                                         'No. She works at a school.',
                                         'Yes, they do.',
                                         'She is a policeman.',
                                         'There are four people.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'e5',
                        'instr': 'Exercise 5. Read and circle the best answer. (Chọn đáp án đúng nhất.)',
                        'items': [{'id': 'e5.18', 'o': ['people', 'peoples', 'teacher', 'teachers'], 'q': 'There are five ______ in my family.', 't': 'mcq'},
                                  {'id': 'e5.19', 'o': ['do', 'does', 'did', 'done'], 'q': 'What ______ he do?', 't': 'mcq'},
                                  {'id': 'e5.20', 'o': ['do', 'does', 'did', 'done'], 'q': 'What ______ you do?', 't': 'mcq'},
                                  {'id': 'e5.21', 'o': ['Why', 'Where', 'How', 'When'], 'q': '______ does he work? – He works at a factory.', 't': 'mcq'},
                                  {'id': 'e5.22', 'o': ['they', 'he', 'she', 'it'], 'q': 'Where do ______ work?', 't': 'mcq'},
                                  {'id': 'e5.23', 'o': ['work', 'works', 'worked', 'working'], 'q': 'My mother ______ at primary school.', 't': 'mcq'},
                                  {'id': 'e5.24', 'o': ['work', 'works', 'is', 'are'], 'q': 'My grandparents ______ teachers.', 't': 'mcq'},
                                  {'id': 'e5.25', 'o': ['from', 'in', 'on', 'at'], 'q': 'Does your aunt work ______ a farm?', 't': 'mcq'},
                                  {'id': 'e5.26', 'o': ['from', 'in', 'on', 'at'], 'q': 'She works ______ a hospital.', 't': 'mcq'},
                                  {'id': 'e5.27', 'o': ['students', 'student', 'pupiles', 'pupil'], 'q': 'We are ______.', 't': 'mcq'}]}],
            'id': 'unit-11-12',
            'mode': 'practice',
            'title': 'Unit 11–12'},
           {'groups': [{'id': 'e6',
                        'instr': 'Exercise 6. Read and circle the best answer. (Chọn đáp án đúng nhất.)',
                        'items': [{'id': 'e6.28', 'o': ['Do', 'Does', 'Did', 'Done'], 'q': '______ you have a brother?', 't': 'mcq'},
                                  {'id': 'e6.29', 'o': ['he', 'they', 'you', 'we'], 'q': 'What does ______ look like?', 't': 'mcq'},
                                  {'id': 'e6.30', 'o': ['have', 'has', 'had', 'haves'], 'q': 'My brother ______ long hands.', 't': 'mcq'},
                                  {'id': 'e6.31', 'o': ['a', 'an', 'the'], 'q': 'I have ______ round face.', 't': 'mcq'},
                                  {'id': 'e6.32', 'o': ['have', 'has', 'had', 'haves'], 'q': 'Does he ______ a sister, Jim?', 't': 'mcq'},
                                  {'id': 'e6.33', 'o': ['big', 'slim', 'tall', 'round'], 'q': 'She’s ______. She weigh 36 kilos', 't': 'mcq'},
                                  {'id': 'e6.34', 'o': ['tall', 'short', 'round', 'small'], 'q': 'He’s ______. He is 180 cm in height', 't': 'mcq'},
                                  {'id': 'e6.35', 'o': ['big', 'tall', 'thin', 'long'], 'q': 'His father has ______ eyes.', 't': 'mcq'},
                                  {'id': 'e6.36', 'o': ['He', 'She', 'Her', 'Him'], 'q': '______ face is round.', 't': 'mcq'},
                                  {'id': 'e6.37', 'o': ['I', 'They', 'He', 'We'], 'q': '______ has short black hair.', 't': 'mcq'}]},
                       {'id': 'e7',
                        'instr': 'Exercise 7. Complete these sentences by filling in the blank. (Điền từ vào chỗ trống.)',
                        'items': [{'id': 'e7.38', 'q': 'How {_} is your father? – He’s forty.', 't': 'fill'},
                                  {'id': 'e7.39', 'q': 'What {_} he look like?', 't': 'fill'},
                                  {'id': 'e7.40', 'q': '{_} you have a brother?', 't': 'fill'},
                                  {'id': 'e7.41', 'q': 'My sister has {_} round face.', 't': 'fill'},
                                  {'id': 'e7.42', 'q': 'My mother is {_}. She is 145 cm in height.', 't': 'fill'},
                                  {'id': 'e7.43', 'q': 'My grandfather and grandmother {_} old.', 't': 'fill'}]},
                       {'id': 'e8',
                        'instr': 'Exercise 8. Find mistakes in each sentence and correct them. (Tìm lỗi sai và viết lại cả câu cho đúng.)',
                        'items': [{'id': 'e8.44', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>Today is on Monday.</i><br>{_}', 't': 'fill'},
                                  {'id': 'e8.45', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>He has a long hair.</i><br>{_}', 't': 'fill'},
                                  {'id': 'e8.46', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>She have a small face.</i><br>{_}', 't': 'fill'},
                                  {'id': 'e8.47', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>What do your mother look like?</i><br>{_}', 't': 'fill'},
                                  {'id': 'e8.48', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>My father has an round face.</i><br>{_}', 't': 'fill'},
                                  {'id': 'e8.49', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>My little sister have big eyes.</i><br>{_}', 't': 'fill'},
                                  {'id': 'e8.50', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>My mother has beautiful hand.</i><br>{_}', 't': 'fill'},
                                  {'id': 'e8.51', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>My grandfather are slim.</i><br>{_}', 't': 'fill'},
                                  {'id': 'e8.52', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>Does you have a sister?</i><br>{_}', 't': 'fill'},
                                  {'id': 'e8.53', 'q': 'Tìm lỗi sai và viết lại câu đúng: <i>No, I do. I have a brother.</i><br>{_}', 't': 'fill'}]}],
            'id': 'unit-13',
            'mode': 'practice',
            'title': 'Unit 13: Appearance'},
           {'groups': [{'id': 'e9',
                        'instr': 'Exercise 9. Read and circle the best answer. (Chọn đáp án đúng nhất.)',
                        'items': [{'id': 'e9.54', 'o': ['in', 'on', 'at', 'from'], 'q': 'I wash the dish ______ noon.', 't': 'mcq'},
                                  {'id': 'e9.55', 'o': ['watches', 'does', 'cleans', 'washes'], 'q': 'She ______ the floor everyday.', 't': 'mcq'},
                                  {'id': 'e9.56', 'o': ['helps', 'listens', 'reads', 'watches'], 'q': 'My dad ______ my mom with the cooking.', 't': 'mcq'},
                                  {'id': 'e9.57',
                                   'o': ['do', 'does', 'help', 'helps'],
                                   'q': 'I usually ______ homework before watching TV in the evening.',
                                   't': 'mcq'},
                                  {'id': 'e9.58', 'o': ['read', 'reads', 'reading', 'reades'], 'q': 'My family ______ books every Sunday morning.', 't': 'mcq'},
                                  {'id': 'e9.59', 'o': ['When', 'What', 'How', 'Which'], 'q': '______ do you watch TV?', 't': 'mcq'},
                                  {'id': 'e9.60', 'o': ['do', 'does', 'did', 'done'], 'q': 'What ______ she do in the morning?', 't': 'mcq'},
                                  {'id': 'e9.61', 'o': ['do', 'does', 'did', 'done'], 'q': 'What ______ they do at noon?', 't': 'mcq'},
                                  {'id': 'e9.62',
                                   'o': ['you', 'she', 'they', 'I'],
                                   'q': 'Do you wash the dishes in the evening? – Yes, ______ do.',
                                   't': 'mcq'},
                                  {'id': 'e9.63',
                                   'o': ['clean', 'cleans', 'cleaning', 'cleaned'],
                                   'q': 'Does your father ______ the floor in the morning?',
                                   't': 'mcq'}]},
                       {'id': 'e10',
                        'instr': 'Exercise 10. Read and number the sentences in the correct order. (Đọc và đánh số thứ tự câu trong hội thoại.)',
                        'items': [{'id': 'e10.64',
                                   'o': ['1', '2', '3', '4', '5', '6'],
                                   'plain': True,
                                   'q': 'Câu A đứng ở vị trí thứ mấy trong đoạn hội thoại?',
                                   't': 'mcq'},
                                  {'id': 'e10.65',
                                   'o': ['1', '2', '3', '4', '5', '6'],
                                   'plain': True,
                                   'q': 'Câu B đứng ở vị trí thứ mấy trong đoạn hội thoại?',
                                   't': 'mcq'},
                                  {'id': 'e10.66',
                                   'o': ['1', '2', '3', '4', '5', '6'],
                                   'plain': True,
                                   'q': 'Câu C đứng ở vị trí thứ mấy trong đoạn hội thoại?',
                                   't': 'mcq'},
                                  {'id': 'e10.67',
                                   'o': ['1', '2', '3', '4', '5', '6'],
                                   'plain': True,
                                   'q': 'Câu D đứng ở vị trí thứ mấy trong đoạn hội thoại?',
                                   't': 'mcq'},
                                  {'id': 'e10.68',
                                   'o': ['1', '2', '3', '4', '5', '6'],
                                   'plain': True,
                                   'q': 'Câu E đứng ở vị trí thứ mấy trong đoạn hội thoại?',
                                   't': 'mcq'},
                                  {'id': 'e10.69',
                                   'o': ['1', '2', '3', '4', '5', '6'],
                                   'plain': True,
                                   'q': 'Câu F đứng ở vị trí thứ mấy trong đoạn hội thoại?',
                                   't': 'mcq'}],
                        'passage': '<p><b>A:</b> It’s summer vacation now. Do you have any plans for summer?</p><p><b>B:</b> I do it in the morning. How about '
                                   'you? Do you have any plans yet?</p><p><b>C:</b> Cool. I wish I can cook delicious meals for my family, '
                                   'too.</p><p><b>D:</b> Sure. I plan to read more English books and help my mom with the housework.</p><p><b>E:</b> Yes, I '
                                   'do. I will spend time listening to music and cook meals for my family.</p><p><b>F:</b> It’s so nice. When do you read '
                                   'English books?</p>'},
                       {'id': 'e11',
                        'instr': 'Exercise 11. Reorder the words to make sentences. (Sắp xếp từ thành câu.)',
                        'items': [{'id': 'e11.70', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'morning?', 'do', 'in', 'the', 'you', 'What']},
                                  {'id': 'e11.71',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['mother', 'with', 'cooking.', 'my', 'I', 'help', 'the']},
                                  {'id': 'e11.72',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'My', 'together', 'watches', 'in', 'TV', 'evening.', 'family']},
                                  {'id': 'e11.73',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['the', 'in', 'you', 'clothes', 'Do', 'your', 'wash', 'afternoon?']},
                                  {'id': 'e11.74',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['I', 'parents.', 'with', 'do', 'my', 'housework', 'the']}]}],
            'id': 'unit-14',
            'mode': 'practice',
            'title': 'Unit 14: Daily activities'},
           {'groups': [{'id': 'e12',
                        'instr': 'Exercise 12. Match each question with a suitable answer. (Nối câu hỏi với câu trả lời phù hợp.)',
                        'items': [{'id': 'e12.75',
                                   'left': [{'t': 'Where does your brother go on Sundays?'},
                                            {'t': 'What does she do there?'},
                                            {'t': 'Where do you go on Saturdays?'},
                                            {'t': 'Do you go to the shopping centre?'},
                                            {'t': 'What do you do at the weekends?'}],
                                   'o': ['She does yoga.',
                                         'No. I stay at home.',
                                         'He goes to the gym.',
                                         'I cook meals for my family.',
                                         'I go the the cinema on Saturdays.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'e13',
                        'instr': 'Exercise 13. Read and circle the best answer. (Chọn đáp án đúng nhất.)',
                        'items': [{'id': 'e13.76', 'o': ['do', 'does', 'did', 'done'], 'q': 'Where ______ your father go on Saturdays?', 't': 'mcq'},
                                  {'id': 'e13.77', 'o': ['do', 'does', 'did', 'done'], 'q': 'Where ______ you go on Sundays?', 't': 'mcq'},
                                  {'id': 'e13.78', 'o': ['go', 'goes', 'went', 'going'], 'q': 'He ______ to the sports centre.', 't': 'mcq'},
                                  {'id': 'e13.79', 'o': ['go', 'goes', 'went', 'going'], 'q': 'I ______ to the cinema.', 't': 'mcq'},
                                  {'id': 'e13.80', 'o': ['he', 'they', 'you', 'we'], 'q': 'What does ______ do there?', 't': 'mcq'},
                                  {'id': 'e13.81', 'o': ['he', 'she', 'you', 'it'], 'q': 'What do ______ do there?', 't': 'mcq'},
                                  {'id': 'e13.82', 'o': ['In', 'On', 'At', 'To'], 'q': '______ Sundays, I usually watch films with my parents.', 't': 'mcq'},
                                  {'id': 'e13.83', 'o': ['in', 'on', 'at', 'to'], 'q': '______ the weekends, my sister does yoga in the morning.', 't': 'mcq'},
                                  {'id': 'e13.84',
                                   'o': ['sport centre', 'cinema', 'shopping centre', 'gym'],
                                   'q': 'Minh goes to the ______ to buy groceries.',
                                   't': 'mcq'},
                                  {'id': 'e13.85', 'o': ['yoga', 'tennis', 'cook', 'swimming pool'], 'q': 'Hoa goes to the ______ on Saturdays.', 't': 'mcq'}]},
                       {'id': 'e14',
                        'instr': 'Exercise 14. Reorder the words to make sentences. (Sắp xếp từ thành câu.)',
                        'items': [{'id': 'e14.86', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'on', 'Where', 'mother', 'your', 'Sunday?']},
                                  {'id': 'e14.87',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['she', 'in', 'does', 'What', 'the', 'do', 'morning?']},
                                  {'id': 'e14.88', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['television', 'We', 'Sundays.', 'on', 'watch']},
                                  {'id': 'e14.89',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['goes', 'sports', 'father', 'On', 'Sundays,', 'to', 'centre.', 'my']},
                                  {'id': 'e14.90', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['do', 'does', 'there?', 'What', 'he']}]},
                       {'id': 'e15',
                        'instr': 'Exercise 15. Match each question with a suitable answer. (Nối câu hỏi với câu trả lời phù hợp.)',
                        'items': [{'id': 'e15.91',
                                   'left': [{'t': 'What’s the weather like today?'},
                                            {'t': 'Was it a snowy day last Sunday?'},
                                            {'t': 'Do you want to go to the waterpark?'},
                                            {'t': 'What was the weather like yesterday?'},
                                            {'t': 'Does she want to go to the shopping centre?'}],
                                   'o': ['Great! Let’s go.', 'It was a stormy day.', 'It’s sunny', 'No, it wasn’t.', 'Sorry, I can’t. It’s rainy today.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'e16',
                        'instr': 'Exercise 16. Read and circle the best answer. (Chọn đáp án đúng nhất.)',
                        'items': [{'id': 'e16.92', 'o': ['is', 'was', 'are', 'were'], 'q': 'What ______ the weather like today?', 't': 'mcq'},
                                  {'id': 'e16.93', 'o': ['is', 'was', 'are', 'were'], 'q': 'What ______ the weather like last weekend?', 't': 'mcq'},
                                  {'id': 'e16.94', 'o': ['today', 'Sunday', 'yesterday', 'Monday'], 'q': 'It was rainy ______.', 't': 'mcq'},
                                  {'id': 'e16.95', 'o': ['is', 'was', 'are', 'were'], 'q': 'Kate ______ at the bookshop last week.', 't': 'mcq'},
                                  {'id': 'e16.96', 'o': ['go', 'goes', 'going', 'went'], 'q': 'Let’s ______ to the food stall. I am so hungry.', 't': 'mcq'},
                                  {'id': 'e16.97', 'o': ['Do', 'Does', 'Did', 'Done'], 'q': '______ you want to go to the bakery?', 't': 'mcq'},
                                  {'id': 'e16.98', 'o': ['Do', 'Does', 'Did', 'Done'], 'q': '______ he want to go to the swimming pool?', 't': 'mcq'},
                                  {'id': 'e16.99', 'o': ['go', 'going', 'goes', 'went'], 'q': 'Do you want to ______ to the water park with me?', 't': 'mcq'},
                                  {'id': 'e16.100',
                                   'o': ['bakery', 'bookshop', 'food stall', 'shopping centre'],
                                   'q': 'Do you want to go to the ______? I want to buy some clothes.',
                                   't': 'mcq'},
                                  {'id': 'e16.101', 'o': ['can', 'can’t', 'could', 'couldn’t'], 'q': 'Sorry, I ______. I’m doing my homework.', 't': 'mcq'}]},
                       {'id': 'e17',
                        'instr': 'Exercise 17. Reorder the words to make sentences. (Sắp xếp từ thành câu.)',
                        'items': [{'id': 'e17.102', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['today?', 'the', 'weather', 'like', 'What’s']},
                                  {'id': 'e17.103', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sunny', 'It’s', 'today.']},
                                  {'id': 'e17.104',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['to', 'you', 'to', 'bookshop?', 'the', 'go', 'want', 'Do']},
                                  {'id': 'e17.105', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['water', 'to', 'the', 'park.', 'Let’s', 'go']},
                                  {'id': 'e17.106',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['all', 'it’s', 'can’t', 'day.', 'outside', 'because', 'play', 'rainy', 'I']}]}],
            'id': 'unit-15-16',
            'mode': 'practice',
            'title': 'Unit 15–16'},
           {'groups': [{'id': 'e18',
                        'instr': 'Exercise 18. Reorder the words to make sentences. (Sắp xếp từ thành câu.)',
                        'items': [{'id': 'e18.107',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['campsite?', 'get', 'How', 'can', 'I', 'the', 'to']},
                                  {'id': 'e18.108', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['The', 'the', 'is', 'bookshop', 'left.', 'on']},
                                  {'id': 'e18.109', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Go', 'turn', 'straight', 'left.', 'and']},
                                  {'id': 'e18.110',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['here?', 'a', 'Is', 'food', 'stall', 'there', 'near']},
                                  {'id': 'e18.111',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['There', 'Oxford', 'in', 'is', 'swimming', 'a', 'pool', 'Street.']}]},
                       {'id': 'e19',
                        'instr': 'Exercise 19. Read and decide whether these sentences are True (T) or False (F). (Đọc đoạn văn, True hay False?)',
                        'items': [{'id': 'e19.112', 'q': 'She studies at Archimes primary school.', 't': 'tf'},
                                  {'id': 'e19.113', 'q': 'The school is near her house.', 't': 'tf'},
                                  {'id': 'e19.114', 'q': 'She has to leave home early.', 't': 'tf'},
                                  {'id': 'e19.115', 'q': 'She has to turn right at the Lotte centre.', 't': 'tf'},
                                  {'id': 'e19.116', 'q': 'She has to turn left at the crossroad', 't': 'tf'}],
                        'passage': '<p>My name is Victoria. I am a pupil at Archimes primary school. My house is far from my school. It is about 12 km so I '
                                   'have to go to school early. I usually leave home at half past six. This is how to go to school every day. I go straight on '
                                   'the road, turn right at the Lotte centre, continue to go straight for about 5 minutes, then turn right at the crossroad '
                                   'and keep going straight for about 5 metres. And finally, I cycle along the trees from where I can see my school across the '
                                   'street.</p>'},
                       {'id': 'e20',
                        'instr': 'Exercise 20. Match each question with a suitable answer. (Nối câu hỏi với câu trả lời phù hợp.)',
                        'items': [{'id': 'e20.117',
                                   'left': [{'t': 'What are these animals?'},
                                            {'t': 'Why do you like lions?'},
                                            {'t': 'What is this animal?'},
                                            {'t': 'Why do you like peacocks?'},
                                            {'t': 'Why do you like giraffes?'}],
                                   'o': ['This’s a hippo.',
                                         'Because they run quickly.',
                                         'They’re crocodiles.',
                                         'Because they dance beautifully.',
                                         'Because they roar loudly.'],
                                   'q': 'Nối (chọn đáp án đúng cho từng dòng):',
                                   't': 'match'}]},
                       {'id': 'e21',
                        'instr': 'Exercise 21. Read and circle the best answer. (Chọn đáp án đúng nhất.)',
                        'items': [{'id': 'e21.118', 'o': ['this', 'that', 'there', 'these'], 'q': 'What are ______ animals?', 't': 'mcq'},
                                  {'id': 'e21.119', 'o': ['peacock', 'peacocks', 'peacockes', 'peacocking'], 'q': 'Why do you like ______?', 't': 'mcq'},
                                  {'id': 'e21.120', 'o': ['Because', 'Why', 'When', 'What'], 'q': '______ they dance beautifully.', 't': 'mcq'},
                                  {'id': 'e21.121', 'o': ['is', 'am', 'are', 'be'], 'q': 'What are those animals? – They ______ lions.', 't': 'mcq'},
                                  {'id': 'e21.122',
                                   'o': ['crocodiles', 'crocodile', 'hippo', 'hippoes'],
                                   'q': 'What are these animals? – They are ______.',
                                   't': 'mcq'},
                                  {'id': 'e21.123',
                                   'o': ['strong', 'run quickly', 'sing merrily', 'dance beautifully'],
                                   'q': 'Why do you like birds? – Because they ______.',
                                   't': 'mcq'},
                                  {'id': 'e21.124', 'o': ['Do', 'Does', 'Did', 'Done'], 'q': '______ giraffes run quickly?', 't': 'mcq'},
                                  {'id': 'e21.125', 'o': ['quickly', 'loudly', 'beautifully', 'merrily'], 'q': 'These lions are roaring ______.', 't': 'mcq'},
                                  {'id': 'e21.126', 'o': ['merrily', 'happily', 'strong', 'loud'], 'q': 'The hippos look ______.', 't': 'mcq'},
                                  {'id': 'e21.127', 'o': ['look', 'looked', 'looking', 'looks'], 'q': 'This lion ______ brave.', 't': 'mcq'}]},
                       {'id': 'e22',
                        'instr': 'Exercise 22. Reorder the words to make sentences. (Sắp xếp từ thành câu.)',
                        'items': [{'id': 'e22.128', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['What', 'animals?', 'are', 'those']},
                                  {'id': 'e22.129', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['quickly.', 'running', 'animals', 'Those', 'are']},
                                  {'id': 'e22.130', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['These', 'roaring', 'lions', 'are', 'loudly.']},
                                  {'id': 'e22.131',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['beautifully.', 'dance', 'peacocks', 'Rose', 'loves', 'they', 'because']},
                                  {'id': 'e22.132',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['What', 'see?', 'your', 'brother', 'does', 'animals', 'like', 'to']}]}],
            'id': 'unit-17-19',
            'mode': 'practice',
            'title': 'Unit 17–19'},
           {'groups': [{'id': 'e23',
                        'instr': 'Exercise 23. Read and circle the best answer. (Chọn đáp án đúng nhất.)',
                        'items': [{'id': 'e23.133', 'o': ['Is', 'Am', 'Are', 'Be'], 'q': '______ John and Bill at the campsite?', 't': 'mcq'},
                                  {'id': 'e23.134', 'o': ['What', 'When', 'Where', 'Why'], 'q': '______ is she doing at home?', 't': 'mcq'},
                                  {'id': 'e23.135', 'o': ['Is', 'Am', 'Are', 'Be'], 'q': '______ you playing card games now?', 't': 'mcq'},
                                  {'id': 'e23.136', 'o': ['is', 'am', 'are', 'be'], 'q': 'Linda ______ dancing around the campfire.', 't': 'mcq'},
                                  {'id': 'e23.137', 'o': ['is', 'am', 'are', 'be'], 'q': 'They ______ playing tug of war together.', 't': 'mcq'},
                                  {'id': 'e23.138', 'o': ['sing', 'sings', 'singing', 'sang'], 'q': 'We are ______ “ Happy Birthday” songs', 't': 'mcq'},
                                  {'id': 'e23.139', 'o': ['playing', 'singing', 'dancing', 'taking'], 'q': 'He is ______ hide-and-seek.', 't': 'mcq'},
                                  {'id': 'e23.140', 'o': ['tent', 'campfire', 'story', 'photo'], 'q': 'No one is putting up a ______.', 't': 'mcq'},
                                  {'id': 'e23.141', 'o': ['story', 'stories', 'song', 'songs'], 'q': 'Mr. Long is telling us a wonderful ______.', 't': 'mcq'},
                                  {'id': 'e23.142', 'o': ['in', 'on', 'at', 'from'], 'q': 'Let’s email our friends ______ the weekend.', 't': 'mcq'}]},
                       {'id': 'e24',
                        'instr': 'Exercise 24. Reorder the words to make sentences. (Sắp xếp từ thành câu.)',
                        'items': [{'id': 'e24.143',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['What', 'at', 'are', 'campsite?', 'doing', 'they', 'the']},
                                  {'id': 'e24.144',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['campfire.', 'is', 'a', 'up', 'putting', 'and', 'He', 'tent', 'building', 'a']},
                                  {'id': 'e24.145',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['visit', 'They', 'their', 'grandparents', 'summer.', 'the', 'in']},
                                  {'id': 'e24.146',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['friends', 'is', 'the', 'at', 'He', 'his', 'weekend.', 'emailing']},
                                  {'id': 'e24.147',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['playing', 'of', 'war.', 'are', 'his', 'tug', 'friends', 'and', 'John']}]},
                       {'id': 'e25',
                        'instr': 'Exercise 25. Read the passage and answer the questions. (Đọc đoạn văn và trả lời câu hỏi – tự viết, xem đáp án mẫu.)',
                        'items': [{'id': 'e25.148', 'q': 'Where are they today?', 't': 'open'},
                                  {'id': 'e25.149', 'q': 'What are they doing in the morning?', 't': 'open'},
                                  {'id': 'e25.150', 'q': 'What do Bill and Kong do in the afternoon?', 't': 'open'},
                                  {'id': 'e25.151', 'q': 'What is Loan doing at 7 P.M?', 't': 'open'},
                                  {'id': 'e25.152', 'q': 'Are they having a lot of fun?', 't': 'open'}],
                        'passage': '<p>My name is Hazel . Today is Sunday. My classmates and I are at the campsite. In the morning, we put up a tent and take '
                                   'photos. In the afternoon, Helen and I play card games together. Bill and Kong help Mr. Long build a campfire. Some of my '
                                   'other friends are playing tug of war. It’s 7 P.M. We are sitting around the campfire and singing songs. Loan is telling us '
                                   'an interesting story about her adventure. We are having a lot of fun.</p>'}],
            'id': 'unit-20',
            'mode': 'practice',
            'title': 'Unit 20: At summer camp'}],
 'theory': '<h3>Đề cương ôn tập Tiếng Anh lớp 4 – Kì 2 (Global Success)</h3><h3>Unit 11 – My home</h3><p><b>Cách hỏi xem bạn mình sống ở đâu</b></p><table '
           'class="tb"><tr><td>Để hỏi:</td><td>Where do you live?</td></tr><tr><td>Để trả lời:</td><td>I live + prep + place</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>Where do you live?</td><td>Bạn sống ở đâu?</td></tr><tr><td>B:</td><td>I live in Tran Hung '
           'Dao street.</td><td>Tớ ở phố Trần Hưng Đạo.</td></tr></table><p><b>Cách hỏi xem ai đó sống ở đâu</b></p><table class="tb"><tr><td>Để '
           'hỏi:</td><td>Where does he/she live?</td></tr><tr><td>Để trả lời:</td><td>He/She lives + prep + place</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>Where does Minh live?</td><td>Bạn sống ở đâu?</td></tr><tr><td>B:</td><td>He lives at 9 '
           'Quang Trung road.</td><td>Tớ ở số 9 đường Quang Trung.</td></tr></table><p><b>Cách hỏi xem nơi đó như thế nào</b></p><table class="tb"><tr><td>Để '
           'hỏi:</td><td>What’s the + place + like?</td></tr><tr><td>Để trả lời:</td><td>It’s + a/an + adjective + place.</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What’s the street like?</td><td>Con phố đó như thế nào?</td></tr><tr><td>B:</td><td>It’s a '
           'busy street.</td><td>Nó là một con phố bận rộn.</td></tr></table><h3>Unit 12 – Jobs</h3><p><b>Cách hỏi về nghề nghiệp của ai đó</b></p><table '
           'class="tb"><tr><td>Để hỏi:</td><td>What does he/she do?</td></tr><tr><td>Để trả lời:</td><td>He/She is + a/an + job.</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What does Amy do?</td><td>Amy làm nghề gì?</td></tr><tr><td>B:</td><td>She is a '
           'nurse.</td><td>Cô ấy làm y tá.</td></tr></table><p><b>Cách hỏi về nơi làm việc của ai đó</b></p><table class="tb"><tr><td>Để hỏi:</td><td>Where '
           'does he/she work?</td></tr><tr><td>Để trả lời:</td><td>He/She works + place.</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>Where does he work?</td><td>Anh ấy làm việc ở đâu?</td></tr><tr><td>B:</td><td>He works on '
           'a farm.</td><td>Anh ấy làm việc ở nông trại.</td></tr></table><h3>Unit 13 – Appearance</h3><p><b>Cách hỏi về ngoại hình của ai đó</b></p><table '
           'class="tb"><tr><td>Để hỏi:</td><td>What does he/she look like?</td></tr><tr><td>Để trả lời:</td><td>He/She has + adjective.</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What does he look like?</td><td>Anh ấy trông như thế nào?</td></tr><tr><td>B:</td><td>He '
           'has a round face.</td><td>Anh ấy có khuôn mặt tròn.</td></tr><tr><td>A:</td><td>What does your mother look like?</td><td>Mẹ của bạn trông như thế '
           'nào?</td></tr><tr><td>B:</td><td>She has long hair.</td><td>Mẹ có mái tóc dài.</td></tr></table><p><b>Mở rộng:</b></p><p><b>Cách tạo nên một cụm '
           'danh từ miêu tả</b></p><p><b>Với danh từ đếm được số ít</b></p><table class="tb"><tr><td></td><td>a/ an + adjective + singular countable '
           'noun</td></tr><tr><td>Example:</td><td>a round face.</td></tr></table><p><b>Với danh từ đếm được số nhiều</b></p><table '
           'class="tb"><tr><td></td><td>adjective + plural countable noun</td></tr><tr><td>Example:</td><td>big eyes</td></tr></table><p><b>b. Với danh từ '
           'không đếm được</b></p><table class="tb"><tr><td></td><td>adjective + uncountable noun</td></tr><tr><td>Example:</td><td>long '
           'hair</td></tr></table><p><i>Lưu ý: Với những bộ phận trên cơ thể có 2 cái trở lên ta luôn phải sử dụng số nhiều Khi miêu tả (eyes/ '
           'ears/…)</i></p><h3>Unit 14 – Daily activities</h3><p><b>Cách hỏi thời gian bạn làm việc gì đó</b></p><table class="tb"><tr><td>Để '
           'hỏi:</td><td>When do you + Vo?</td></tr><tr><td>Để trả lời:</td><td>I + Vo + time.</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>When do you clean the floor?</td><td>Bạn lau sàn khi nào?</td></tr><tr><td>B:</td><td>I '
           'clean the floor in the morning.</td><td>Mình lau sàn vào buổi sáng.</td></tr></table><p><b>Cách hỏi thời gian ai đó làm việc gì đó</b></p><table '
           'class="tb"><tr><td>Để hỏi:</td><td>When does he/she + Vo?</td></tr><tr><td>Để trả lời:</td><td>He/She + V(s/es) + time.</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>When does your mother clean the floor?</td><td>Mẹ bạn lau sàn khi '
           'nào?</td></tr><tr><td>B:</td><td>She cleans the floor in the evening.</td><td>Mẹ lau sàn vào buổi tối.</td></tr></table><p><b>Cách hỏi bạn làm gì '
           'vào thời gian cụ thể</b></p><table class="tb"><tr><td>Để hỏi:</td><td>What do you do + time?</td></tr><tr><td>Để trả lời:</td><td>I + '
           'Vo.</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What do you do in the morning?</td><td>Bạn làm gì vào buổi '
           'sáng?</td></tr><tr><td>B:</td><td>I go to school.</td><td>Mình đi tới trường.</td></tr></table><p><b>Cách hỏi ai đó làm gì vào thời gian cụ '
           'thể</b></p><table class="tb"><tr><td>Để hỏi:</td><td>What does he/she do + time?</td></tr><tr><td>Để trả lời:</td><td>He/She '
           'V(s/es).</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What does Mr. Andrew do in the evening?</td><td>Thầy Andrew làm '
           "gì vào buổi tối?</td></tr><tr><td>B:</td><td>He watches TV.</td><td>Thầy xem ti vi.</td></tr></table><h3>Unit 15 – My family's "
           'weekends</h3><p><b>Cách hỏi xem ai đó ở đâu vào cuối tuần.</b></p><table class="tb"><tr><td>Để hỏi:</td><td>Where does he/she go on Saturdays/ '
           'Sundays?</td></tr><tr><td>Để trả lời:</td><td>He/ She goes to the + place.</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>Where does she go on Sundays?</td><td>Cô ấy đi đâu vào các Chủ '
           'Nhật?</td></tr><tr><td>B:</td><td>She goes to the cinema.</td><td>Cô ấy đi xem phim.</td></tr></table><p><b>Cách hỏi xem ai đó làm cái gì vào cuối '
           'tuần.</b></p><table class="tb"><tr><td>Để hỏi:</td><td>What does he/she do on Saturdays/ Sundays?</td></tr><tr><td>Để trả lời:</td><td>He/ She + '
           'V(s/es)</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What does he do on Saturdays?</td><td>Anh ấy làm gì vào các thứ '
           'Bẩy.</td></tr><tr><td>B:</td><td>He plays tennis.</td><td>Anh ấy chơi tennis.</td></tr></table><h3>Unit 16 – Weather</h3><p><b>Cách hỏi về thời '
           'tiết ở một thời điểm trong quá khứ</b></p><table class="tb"><tr><td>Để hỏi:</td><td>What was the weather like last + time?</td></tr><tr><td>Để trả '
           'lời:</td><td>It was + adjective about weather.</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What was the weather like '
           'last weekend?</td><td>Thời tiết cuối tuần trước thế nào?</td></tr><tr><td>B:</td><td>It was sunny.</td><td>Trời nắng.</td></tr></table><p><b>Cách '
           'hỏi khi mời ai đó đi chơi đâu đó</b></p><table class="tb"><tr><td>Để hỏi:</td><td>Do you want to go to the + place?</td></tr><tr><td>Để trả '
           'lời:</td><td>Great! Let’s go. ( đồng ý)</td></tr><tr><td></td><td></td><td>Sorry, I can’t. ( từ chối)</td></tr><tr><td '
           'colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>Do you want to go to the bakery?</td><td>Bạn có muốn đi tiệm bánh mì '
           'không?</td></tr><tr><td>B:</td><td>Great! Let’s go.</td><td>Thật tuyệt! Đi thôi.</td></tr></table><h3>Unit 17 – In the city</h3><p><b>Cách hỏi về '
           'nội dung của biển báo</b></p><table class="tb"><tr><td>Để hỏi:</td><td>What does it say?</td></tr><tr><td>Để trả lời:</td><td>It says + “ '
           'signs”</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What does it say?</td><td>Nó nói gì '
           'vậy?</td></tr><tr><td>B:</td><td>It says “go straight”</td><td>Nó nói hãy đi thẳng</td></tr></table><p><b>Cách hỏi đường đến nơi nào '
           'đó</b></p><table class="tb"><tr><td>Để hỏi:</td><td>How can I get to the + place?</td></tr><tr><td>Để trả lời:</td><td>(show the '
           'direction)</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>How can I get to the bookshop?</td><td>Mình đến hiệu sách như '
           'thế nào?</td></tr><tr><td>B:</td><td>Go straight and turn left.</td><td>Đi thẳng rồi rẽ trái.</td></tr></table><h3>Unit 18 – At the shopping '
           'centre</h3><p><b>Cách hỏi về vị trí của nơi nào đó</b></p><table class="tb"><tr><td>Để hỏi:</td><td>Where is the + place?</td></tr><tr><td>Để trả '
           'lời:</td><td>It’s + position of place.</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>Where’s the bookshop?</td><td>Hiệu '
           'sách ở đâu vậy?</td></tr><tr><td>B:</td><td>It’s near the gift shop.</td><td>Nó ở gần cửa hàng quà tặng.</td></tr><tr><td>Để hỏi:</td><td>How much '
           'is the + thing?</td></tr><tr><td>Để trả lời:</td><td>It’s + price.</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>How '
           'much is the T-shirt?</td><td>Cái áo phông này giá bao nhiêu?</td></tr><tr><td>B:</td><td>It’s 50.000 dong.</td><td>Nó có giá năm mươi nghìn '
           'đồng.</td></tr></table><h3>Unit 19 – The animal world</h3><table class="tb"><tr><td>Để hỏi:</td><td>What are these animals?</td></tr><tr><td>Để '
           'trả lời:</td><td>They’re + name of the animal.</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What are these '
           'animals?</td><td>Những con vật này là con gì?</td></tr><tr><td>B:</td><td>They’re giraffes.</td><td>Chúng là những con hươu cao '
           'cổ.</td></tr><tr><td>Để hỏi:</td><td>Why do you like + name of the animal?</td></tr><tr><td>Để trả lời:</td><td>Because they + '
           'reason.</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>Why do you like birds?</td><td>Tại sao bạn lại thích loài '
           'chim?</td></tr><tr><td>B:</td><td>Because they sing merrily.</td><td>Bởi vì chúng hát vui vẻ.</td></tr></table><h3>Unit 20 – At summer '
           'camp</h3><p><b>Cách hỏi xem ai đó đang làm gì</b></p><table class="tb"><tr><td>Để hỏi:</td><td>What tobe + S+ doing?</td></tr><tr><td>Để trả '
           'lời:</td><td>S + tobe + V-ing.</td></tr><tr><td colspan="3"><b>Example:</b></td></tr><tr><td>A:</td><td>What is he doing?</td><td>Anh ấy đang làm '
           'gì?</td></tr><tr><td>B:</td><td>He’s putting up a tent.</td><td>Anh ấy đang dựng lều.</td></tr><tr><td>A:</td><td>What are you doing?</td><td>Bạn '
           'đang làm gì?</td></tr><tr><td>B:</td><td>I am playing card games.</td><td>Minh đang chơi bài.</td></tr><tr><td>A:</td><td>What are they '
           'doing?</td><td>Họ đang làm gì</td></tr><tr><td>B:</td><td>They are playing tug of war.</td><td>Họ đang chơi kéo co.</td></tr></table>',
 'title': 'Đề cương HK2 (24-25) A – Global: Unit 11–20',
 'unit': 'DeCuongHK2'}
