# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "What's the name of your school?",
 't1.10': ['Where is your school?'],
 't1.11': 'Có một sân chơi ở trường của tôi.',
 't1.12': 'playgrounds',
 't1.13': 'There is a playground at my school.',
 't1.14': 'school',
 't1.15': ['My school is in a village.'],
 't1.16': "It's in the village.",
 't1.17': 'are',
 't1.18': 'There is a garden at her school.',
 't1.19': 'in',
 't1.2': 'Where',
 't1.20': ['There are two playgrounds and a big garden at my school.'],
 't1.3': "It's in the town.",
 't1.4': 'Where',
 't1.5': ['What is the name of your school?'],
 't1.6': 'Where is your school?',
 't1.7': 'is',
 't1.8': 'Nguyen Du Primary School.',
 't1.9': 'from'}

EXPLANATIONS = {'t1.1': "Đáp án: What's the name of your school?",
 't1.10': 'Câu đúng: Where is your school?',
 't1.11': 'Đáp án: Có một sân chơi ở trường của tôi.',
 't1.12': 'Đáp án: playgrounds',
 't1.13': 'Đáp án: There is a playground at my school.',
 't1.14': 'Đáp án: school',
 't1.15': 'Câu đúng: My school is in a village.',
 't1.16': "Đáp án: It's in the village.",
 't1.17': 'Đáp án: are',
 't1.18': 'Đáp án: There is a garden at her school.',
 't1.19': 'Đáp án: in',
 't1.2': 'Đáp án: Where',
 't1.20': 'Câu đúng: There are two playgrounds and a big garden at my school.',
 't1.3': "Đáp án: It's in the town.",
 't1.4': 'Đáp án: Where',
 't1.5': 'Câu đúng: What is the name of your school?',
 't1.6': 'Đáp án: Where is your school?',
 't1.7': 'Đáp án: is',
 't1.8': 'Đáp án: Nguyen Du Primary School.',
 't1.9': 'Đáp án: from'}
