# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': 'In the evening.',
 't1.10': 'Dì của bạn làm gì vào các ngày thứ Bảy?',
 't1.11': 'go',
 't1.12': ['What does your brother do on Sundays?'],
 't1.13': 'She lives in Le Lai Street.',
 't1.14': 'does',
 't1.15': 'She lives at 10A Oxford Street.',
 't1.16': 'Who',
 't1.17': ['Where Mary does live?'],
 't1.18': "It's a small house.",
 't1.19': 'at',
 't1.2': 'clean',
 't1.20': 'She works on a farm.',
 't1.3': ['When do you do the housework?'],
 't1.4': 'What does Lan do in the evening?',
 't1.5': 'does',
 't1.6': ['Ben washes his clothes in the evening.'],
 't1.7': 'She goes to the supermarket on Sundays.',
 't1.8': 'does',
 't1.9': ['My father goes to the swimming pool on Saturdays.']}

EXPLANATIONS = {'t1.1': 'Đáp án: In the evening.',
 't1.10': 'Đáp án: Dì của bạn làm gì vào các ngày thứ Bảy?',
 't1.11': 'Đáp án: go',
 't1.12': 'Câu đúng: What does your brother do on Sundays?',
 't1.13': 'Đáp án: She lives in Le Lai Street.',
 't1.14': 'Đáp án: does',
 't1.15': 'Đáp án: She lives at 10A Oxford Street.',
 't1.16': 'Đáp án: Who',
 't1.17': 'Câu đúng: Where Mary does live?',
 't1.18': "Đáp án: It's a small house.",
 't1.19': 'Đáp án: at',
 't1.2': 'Đáp án: clean',
 't1.20': 'Đáp án: She works on a farm.',
 't1.3': 'Câu đúng: When do you do the housework?',
 't1.4': 'Đáp án: What does Lan do in the evening?',
 't1.5': 'Đáp án: does',
 't1.6': 'Câu đúng: Ben washes his clothes in the evening.',
 't1.7': 'Đáp án: She goes to the supermarket on Sundays.',
 't1.8': 'Đáp án: does',
 't1.9': 'Câu đúng: My father goes to the swimming pool on Saturdays.'}
