# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a1.1': 'B',
 'a1.2': 'A',
 'a1.3': 'A',
 'a1.4': 'B',
 'a2.5': 'C',
 'a2.6': 'A',
 'a2.7': 'D',
 'a2.8': 'B',
 'a3.10': 'T',
 'a3.9': 'F',
 'a4.11': ['skip'],
 'a4.12': ['Wednesdays', 'Wednesday'],
 'b1.13': 'B',
 'b1.14': 'B',
 'b1.15': 'A',
 'b1.16': 'B',
 'b1.17': 'A',
 'b2.18': ['It’s in the village.', 'In the village.', 'In the village', 'village'],
 'b2.19': ['There are three.', 'There are three buildings.', 'three', '3'],
 'b2.20': ['Yes, there is.', 'Yes'],
 'b2.21': ['It’s in the city.', 'In the city.', 'In the city', 'city'],
 'b2.22': ['There are two.', 'There are two computer rooms.', 'two', '2'],
 'c1.23': ['maths', 'math'],
 'c1.24': ['countryside'],
 'c1.25': ['5.45', 'five forty-five', 'five forty five'],
 'c1.26': ['listen to music'],
 'c1.27': ['grapes'],
 'c2.28': ['There is a big playground at my school.'],
 'c2.29': ['I want some lemonade.'],
 'c2.30': ['I have breakfast at 6.30.'],
 'c2.31': ['I was at the zoo yesterday.'],
 'c2.32': ['I have maths and music on Mondays.']}

EXPLANATIONS = {'a1.1': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.2': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.3': 'Đáp án A (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a1.4': 'Đáp án B (theo đáp án của đề). Nghe lại file âm thanh và đối chiếu với tranh.',
 'a2.5': 'Câu 1 ứng với tranh C (theo đáp án của đề).',
 'a2.6': 'Câu 2 ứng với tranh A (theo đáp án của đề).',
 'a2.7': 'Câu 3 ứng với tranh D (theo đáp án của đề).',
 'a2.8': 'Câu 4 ứng với tranh B (theo đáp án của đề).',
 'a3.10': 'Đáp án: True (theo đáp án của đề: ✓).',
 'a3.9': 'Đáp án: False (theo đáp án của đề: ✗).',
 'a4.11': 'Đáp án: skip',
 'a4.12': 'Đáp án: Wednesdays',
 'b1.13': 'Đáp án: B (theo đáp án của đề).',
 'b1.14': 'Đáp án: B (theo đáp án của đề).',
 'b1.15': 'Đáp án: A (theo đáp án của đề).',
 'b1.16': 'Đáp án: B (theo đáp án của đề).',
 'b1.17': 'Đáp án: A (theo đáp án của đề).',
 'b2.18': 'Đáp án: It’s in the village.',
 'b2.19': 'Đáp án: There are three.',
 'b2.20': 'Đáp án: Yes, there is.',
 'b2.21': 'Đáp án: It’s in the city.',
 'b2.22': 'Đáp án: There are two.',
 'c1.23': 'Đáp án: maths',
 'c1.24': 'Đáp án: countryside',
 'c1.25': 'Đáp án: 5.45',
 'c1.26': 'Đáp án: listen to music',
 'c1.27': 'Đáp án: grapes',
 'c2.28': 'Câu đúng: There is a big playground at my school.',
 'c2.29': 'Câu đúng: I want some lemonade.',
 'c2.30': 'Câu đúng: I have breakfast at 6.30.',
 'c2.31': 'Câu đúng: I was at the zoo yesterday.',
 'c2.32': 'Câu đúng: I have maths and music on Mondays.'}
