# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u13-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['What does your brother look like?', 'Do you have a brother?', 'Is he your brother?', 'Where does he live?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Bạn có anh trai không?.”',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['What does she do?', 'Where does she live?', 'Where does she work?', 'What does she look like?'],
                                   'plain': True,
                                   'q': 'Câu “She is slim." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ["He's a teacher.", "He's tall and thin.", 'He works on a farm.', 'He lives in a busy street.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does he look like?"',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ['What does she do?', 'What does she look like?', 'Where does she work?', 'Where does she live?'],
                                   'plain': True,
                                   'q': 'Câu: "She has a long hair" trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['Cô ấy có gương mặt tròn.', 'Cô ấy có mái tóc dài.', 'Cô ấy có đôi mắt to.', 'Cô ấy có đôi mắt nhỏ.'],
                                   'plain': True,
                                   'q': 'Câu: “She has big eyes" có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['What does he do?', 'Where does he work?', 'Who does he live with?', 'What does he look like?'],
                                   'plain': True,
                                   'q': "Câu: “He's big.” trả lời cho câu hỏi nào sau đây:",
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['What does your brother do?', 'Where does your brother work?', 'What does your brother look like?', "Who's that?"],
                                   'plain': True,
                                   'q': 'Câu: “He has a round face.” trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ["He's thin and tall.", "She's a nurse.", "She's slim.", "He's a worker."],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What does your sister look like?”',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['Chị tôi có gương mặt tròn và đôi mắt nhỏ.',
                                         'Chị tôi có gương mặt tròn và đôi mắt to.',
                                         'Chị tôi cao và có đôi mắt to.',
                                         'Chị tôi mảnh mai và có đôi mắt to.'],
                                   'plain': True,
                                   'q': 'Câu: “My sister has a round face and big eyes.” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['What does your mother do?',
                                         'What does your mother look like?',
                                         'Where does your mother work?',
                                         'Is your mother slim?'],
                                   'plain': True,
                                   'q': 'Câu: “She has long hair" trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['do', 'does', 'is', 'are'], 'plain': True, 'q': 'What ____________ she look like?', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['old', 'high', 'much', 'many'], 'plain': True, 'q': 'How ____________ is your mother, Lan?', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['big', 'tall', 'fat', 'round'], 'plain': True, 'q': 'My sister is __________ and slim.', 't': 'mcq'},
                                  {'id': 'b.4',
                                   'o': ['What', 'Where', 'How', 'When'],
                                   'plain': True,
                                   'q': '____________ does your teacher look like?',
                                   't': 'mcq'},
                                  {'id': 'b.5',
                                   'o': ['tall', 'big', 'high', 'long'],
                                   'plain': True,
                                   'q': 'My grandfather is ____________ and short.',
                                   't': 'mcq'},
                                  {'id': 'b.6', 'o': ['does', 'are', 'is', 'has'], 'plain': True, 'q': 'A: What does your brother look like?', 't': 'mcq'},
                                  {'id': 'b.7', 'o': ['is', 'be', 'look', 'have'], 'plain': True, 'q': 'A: What does she ____________ like?', 't': 'mcq'},
                                  {'id': 'b.8', 'o': ['your sister', 'they', 'we', 'you'], 'plain': True, 'q': 'What does ____________ look like?', 't': 'mcq'},
                                  {'id': 'b.9', 'o': ['Are', 'Is', 'Do', 'Does'], 'plain': True, 'q': '___________ you have a brother, Mai?', 't': 'mcq'},
                                  {'id': 'b.10', 'o': ['is', 'has', 'have', 'does'], 'plain': True, 'q': 'My sister _____________ long hair.', 't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ["Who's that?",
                                            'What does he do?',
                                            'Do you have a sister, Lan?',
                                            'What does she look like?',
                                            'What does your father look like?'],
                                   'o': ['Yes, I do.', 'He is big and short.', "It's my brother.", "He's a student.", 'She is tall and slim.'],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]},
                       {'id': 'd',
                        'instr': 'Read the dialogue and choose the correct option to complete each blank. (Chọn từ điền vào chỗ trống.)',
                        'items': [{'id': 'd.1', 'o': ['How much', 'How many', 'How old', 'What'], 'plain': True, 'q': 'Chỗ trống (1):', 't': 'mcq'},
                                  {'id': 'd.2', 'o': ['two', 'three', 'four', 'five'], 'plain': True, 'q': 'Chỗ trống (2):', 't': 'mcq'},
                                  {'id': 'd.3', 'o': ['How', 'What', 'How old', 'How many'], 'plain': True, 'q': 'Chỗ trống (3):', 't': 'mcq'},
                                  {'id': 'd.4', 'o': ['is', 'does', 'do', 'are'], 'plain': True, 'q': 'Chỗ trống (4):', 't': 'mcq'},
                                  {'id': 'd.5', 'o': ['short', 'high', 'old', 'slim'], 'plain': True, 'q': 'Chỗ trống (5):', 't': 'mcq'}],
                        'passage': 'A: <b>(1)&nbsp;______</b> people are there in your family?<br>B: There are <b>(2)&nbsp;______</b> people: my parents, my '
                                   "brother and me.<br>A: <b>(3)&nbsp;______</b> is your brother?<br>B: He's nineteen years old.<br>A: What "
                                   "<b>(4)&nbsp;______</b> she look like?<br>B: She's tall and <b>(5)&nbsp;______</b>."}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'e',
                        'instr': 'Read the text and choose the correct answers. (Đọc và chọn đáp án đúng.)',
                        'items': [{'id': 'e.1',
                                   'o': ['three', 'four', 'five', 'six'],
                                   'plain': True,
                                   'q': "How many people are there in Lan's family?",
                                   't': 'mcq'},
                                  {'id': 'e.2',
                                   'o': ["He's a worker.", "He's a policeman.", "He's a farmer.", "He's a driver."],
                                   'plain': True,
                                   'q': 'What does her father do?',
                                   't': 'mcq'},
                                  {'id': 'e.3',
                                   'o': ['He is short.', 'He is tall and big.', 'He is old.', 'He is slim.'],
                                   'plain': True,
                                   'q': 'What does he look like?',
                                   't': 'mcq'},
                                  {'id': 'e.4',
                                   'o': ["She's a nurse.", "She's a doctor.", "She's an office worker.", "She's a farmer."],
                                   'plain': True,
                                   'q': 'What does her mother do?',
                                   't': 'mcq'},
                                  {'id': 'e.5',
                                   'o': ['She is tall.', "She's short.", 'She has short hair.', "She's slim and has long hair."],
                                   'plain': True,
                                   'q': 'What does her mother look like?',
                                   't': 'mcq'},
                                  {'id': 'e.6',
                                   'o': ["He's a worker.", "He's a pupil.", "He's a student.", "He's a policeman."],
                                   'plain': True,
                                   'q': 'What does her brother do?',
                                   't': 'mcq'},
                                  {'id': 'e.7',
                                   'o': ["He's short.", "He's tall.", "He's tall and has short hair.", "He's big."],
                                   'plain': True,
                                   'q': 'What does her brother look like?',
                                   't': 'mcq'},
                                  {'id': 'e.8',
                                   'o': ["She's tall and had round face.", "She's short and has big eyes.", "She's slim.", "She's short and has round face."],
                                   'plain': True,
                                   'q': 'What does Lan look like?',
                                   't': 'mcq'}],
                        'passage': 'Hi, my name is Lan. There are six people in my family: my grandparents, my parents, my brother and me. My grandparents are '
                                   'old. My father is a worker. He is tall and big. My mother is an office worker. She is slim and has long hair. My brother '
                                   "is a student. He is tall and has short hair. I'm a pupil. I'm short and has big eyes."}],
            'id': 'doc-hieu',
            'mode': 'practice',
            'title': 'Đọc hiểu'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['a', 'Mai?', 'have', 'Do', 'you', 'sister,', 'brother', 'or', 'a']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['your', 'What', 'like?', 'does', 'brother', 'look']},
                                  {'id': 'f.3',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['and', 'My', 'tall', 'has', 'a', 'face.', 'round', 'brother', 'is']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['short', 'My', 'has', 'father', 'hair.']},
                                  {'id': 'f.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['look', 'like?', 'What', 'sister', 'does', 'your']},
                                  {'id': 'f.6', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['sister', 'is', 'and', 'slim.', 'beautiful', 'My']},
                                  {'id': 'f.7', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['big', 'hair.', 'eyes', 'has', 'She', 'long', 'and']},
                                  {'id': 'f.8', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'My', 'very', 'tall.', 'father']},
                                  {'id': 'f.9',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['are', 'in', 'family.', 'my', 'people', 'four', 'There']},
                                  {'id': 'f.10',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['hair.', 'is', 'and', 'slim', 'has', 'long', 'My', 'mother']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '<h3>Ghi nhớ</h3><table class="tb"><tr><td>Cách hỏi</td><td>Cách trả lời</td></tr><tr><td>What does she/he look like?<br>Cô ấy/Anh ấy trông như thế '
           'nào?</td><td>She/He is + (adjective)<br>Cô ấy/Anh ấy...<br>She/He has...<br>Cô ấy/Anh ấy có …</td></tr><tr><td>Ví dụ:<br>A: What does she look '
           'like? Cô ấy trông như thế nào?<br>B: She’s beautiful. Cô ấy xinh đẹp.<br>A: What does he look like? Anh ấy trông như thế nào?<br>B: He has short '
           'hair. Anh ấy có mái tóc ngắn.</td></tr></table>',
 'title': 'Unit 13 – Appearance: Luyện tập',
 'unit': 13}
