# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk1-de3',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'l1',
                        'instr': 'I. Listen and circle the correct words (nghe và chọn từ đúng).',
                        'items': [{'id': 'l1.1', 'o': ['Saturday', 'study', 'music'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.2', 'o': ['water', 'grapes', 'January'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.3', 'o': ['yes', 'jam', 'Wednesday'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'},
                                  {'id': 'l1.4', 'o': ['March', 'bed', 'get'], 'q': 'Nghe và chọn từ em nghe được.', 't': 'mcq'}]},
                       {'id': 'l2',
                        'instr': 'II. Listen and put a ✓ (True) or ✗ (False) (nghe, tranh có khớp với câu nghe được không?).',
                        'items': [{'id': 'l2.5', 'img': 'l2_1.png', 'q': 'Tranh 1: nội dung bài nghe có khớp với tranh không?', 't': 'tf'},
                                  {'id': 'l2.6', 'img': 'l2_2.png', 'q': 'Tranh 2: nội dung bài nghe có khớp với tranh không?', 't': 'tf'},
                                  {'id': 'l2.7', 'img': 'l2_3.png', 'q': 'Tranh 3: nội dung bài nghe có khớp với tranh không?', 't': 'tf'},
                                  {'id': 'l2.8', 'img': 'l2_4.png', 'q': 'Tranh 4: nội dung bài nghe có khớp với tranh không?', 't': 'tf'}]},
                       {'id': 'r1',
                        'instr': 'III. Tick the correct questions (chọn câu hỏi đúng).',
                        'items': [{'id': 'r1.9',
                                   'img': 'r1_1.png',
                                   'o': ['When’s your birthday?', 'What day is it today?'],
                                   'q': 'Chọn câu hỏi phù hợp với câu trả lời: ____?  It’s in May.',
                                   't': 'mcq'},
                                  {'id': 'r1.10',
                                   'img': 'r1_2.png',
                                   'o': ['Can he cook?', 'Can she cook?'],
                                   'q': 'Chọn câu hỏi phù hợp với câu trả lời: ____?  No, he can’t.',
                                   't': 'mcq'},
                                  {'id': 'r1.11',
                                   'img': 'r1_3.png',
                                   'o': ['What do you want to eat?', 'What do you want to drink?'],
                                   'q': 'Chọn câu hỏi phù hợp với câu trả lời: __________________?  I want some lemonade.',
                                   't': 'mcq'},
                                  {'id': 'r1.12',
                                   'img': 'r1_4.png',
                                   'o': ['What do you do on Sundays?', 'What time do you listen to music?'],
                                   'q': 'Chọn câu hỏi phù hợp với câu trả lời: ____?  I listen to music.',
                                   't': 'mcq'}]},
                       {'id': 'r2',
                        'instr': 'IV. Fill in the blanks (nhìn tranh, điền từ vào chỗ trống).',
                        'items': [{'id': 'r2.13', 'img': 'r2_1.png', 'q': 'Chỗ trống (1): {_}', 't': 'fill'},
                                  {'id': 'r2.14', 'img': 'r2_2.png', 'q': 'Chỗ trống (2): {_}', 't': 'fill'},
                                  {'id': 'r2.15', 'img': 'r2_3.png', 'q': 'Chỗ trống (3): {_}', 't': 'fill'},
                                  {'id': 'r2.16', 'img': 'r2_4.png', 'q': 'Chỗ trống (4): {_}', 't': 'fill'}],
                        'passage': '<p>Hello, my name is Alice. I’m from <b>(1) ______</b> I speak English.In my country, we like to <b>(2) ______</b> or '
                                   'baseball. Our favourite food is fish and <b>(3) ______</b> Most people like tea or coffee, but my favourite drink is '
                                   '<b>(4) ______</b></p>'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 1 – Đề 3',
 'unit': 'GiuaKy1'}
