# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['Peter is from England.'],
 't1.10': 'too',
 't1.11': ['Lisa is from America.'],
 't1.12': "He's from Japan.",
 't1.13': 'is',
 't1.14': ['This is my friend, Mary.'],
 't1.15': 'Where are you from?',
 't1.16': 'am',
 't1.17': ['Where is he from?'],
 't1.18': "It's my new friend.",
 't1.19': 'are',
 't1.2': 'Anh ấy đến từ Singapore.',
 't1.20': ['Malee is from Thailand.'],
 't1.3': 'is',
 't1.4': "They're from Australia.",
 't1.5': 'friend',
 't1.6': ['Where is she from?'],
 't1.7': 'Anh ấy đến từ đầu?',
 't1.8': 'are',
 't1.9': "He's from Vietnam."}

EXPLANATIONS = {'t1.1': 'Câu đúng: Peter is from England.',
 't1.10': 'Đáp án: too',
 't1.11': 'Câu đúng: Lisa is from America.',
 't1.12': "Đáp án: He's from Japan.",
 't1.13': 'Đáp án: is',
 't1.14': 'Câu đúng: This is my friend, Mary.',
 't1.15': 'Đáp án: Where are you from?',
 't1.16': 'Đáp án: am',
 't1.17': 'Câu đúng: Where is he from?',
 't1.18': "Đáp án: It's my new friend.",
 't1.19': 'Đáp án: are',
 't1.2': 'Đáp án: Anh ấy đến từ Singapore.',
 't1.20': 'Câu đúng: Malee is from Thailand.',
 't1.3': 'Đáp án: is',
 't1.4': "Đáp án: They're from Australia.",
 't1.5': 'Đáp án: friend',
 't1.6': 'Câu đúng: Where is she from?',
 't1.7': 'Đáp án: Anh ấy đến từ đầu?',
 't1.8': 'Đáp án: are',
 't1.9': "Đáp án: He's from Vietnam."}
