# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-gk1-nghe3',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'q1',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q1.1', 'o': ['Today is Sunday.', 'Today is Monday.', 'Today is Tuesday.'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q1.2', 'o': ['Today is Sunday.', 'Today is Monday.', 'Today is Tuesday.'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q1.3', 'o': ['Today is Sunday.', 'Today is Monday.', 'Today is Tuesday.'], 'q': 'Nghe câu số 3.', 't': 'mcq'}]},
                       {'id': 'q2',
                        'instr': 'Listen And Write (nghe và điền từ)',
                        'items': [{'id': 'q2.4', 'q': "What day is it today?- It's {_}", 't': 'fill'},
                                  {'id': 'q2.5', 'q': "When's your birthday?- It's in {_}", 't': 'fill'},
                                  {'id': 'q2.6', 'q': 'Can he play the {_}?', 't': 'fill'},
                                  {'id': 'q2.7', 'q': "No, he can't. But he can play the {_}.", 't': 'fill'},
                                  {'id': 'q2.8', 'q': "What time is it?- It's {_} forty-five.", 't': 'fill'},
                                  {'id': 'q2.9', 'q': 'Can your sister {_}?', 't': 'fill'},
                                  {'id': 'q2.10', 'q': "No, she can't. But she can play the {_}.", 't': 'fill'}]},
                       {'id': 'q3',
                        'instr': 'Listen And Choose (nghe và chọn đáp án đúng)',
                        'items': [{'id': 'q3.11', 'o': ['do housework', 'Saturday', 'listen to music'], 'q': 'Nghe câu số 1.', 't': 'mcq'},
                                  {'id': 'q3.12', 'o': ['do housework', 'Saturday', 'listen to music'], 'q': 'Nghe câu số 2.', 't': 'mcq'},
                                  {'id': 'q3.13', 'o': ['do housework', 'Saturday', 'listen to music'], 'q': 'Nghe câu số 3.', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_gk1_nghe3/p3.png" alt="Hình">'}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 3}],
 'theory': '',
 'title': 'Giữa kỳ 1 – Luyện nghe phần 3',
 'unit': 'GiuaKy1'}
