# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': "It's a small village.",
 't1.10': 'Tôi sống ở số 64 đường Nguyễn Huệ.',
 't1.11': 'in',
 't1.12': ['He lives with his parents and grandparents.'],
 't1.13': 'Where do you live?',
 't1.14': 'do',
 't1.15': 'I live in Bui Minh Truc Street.',
 't1.16': 'in',
 't1.17': ['Where do you live, Minh?'],
 't1.18': "It's a small road.",
 't1.19': 'live',
 't1.2': 'with',
 't1.20': "It's a busy street.",
 't1.3': ['She lives at 15 Le Lai Street.'],
 't1.4': 'She lives in Nguyen Van Troi Street.',
 't1.5': 'Who',
 't1.6': ['They live in a big house with their grandparents.'],
 't1.7': 'Cậu ấy sống trong một căn nhà nhỏ cùng với dì của cậu ấy.',
 't1.8': 'like',
 't1.9': ['Who does he live with?']}

EXPLANATIONS = {'t1.1': "Đáp án: It's a small village.",
 't1.10': 'Đáp án: Tôi sống ở số 64 đường Nguyễn Huệ.',
 't1.11': 'Đáp án: in',
 't1.12': 'Câu đúng: He lives with his parents and grandparents.',
 't1.13': 'Đáp án: Where do you live?',
 't1.14': 'Đáp án: do',
 't1.15': 'Đáp án: I live in Bui Minh Truc Street.',
 't1.16': 'Đáp án: in',
 't1.17': 'Câu đúng: Where do you live, Minh?',
 't1.18': "Đáp án: It's a small road.",
 't1.19': 'Đáp án: live',
 't1.2': 'Đáp án: with',
 't1.20': "Đáp án: It's a busy street.",
 't1.3': 'Câu đúng: She lives at 15 Le Lai Street.',
 't1.4': 'Đáp án: She lives in Nguyen Van Troi Street.',
 't1.5': 'Đáp án: Who',
 't1.6': 'Câu đúng: They live in a big house with their grandparents.',
 't1.7': 'Đáp án: Cậu ấy sống trong một căn nhà nhỏ cùng với dì của cậu ấy.',
 't1.8': 'Đáp án: like',
 't1.9': 'Câu đúng: Who does he live with?'}
