# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u19-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['They look brave.', 'They are giraffes.', 'They look strong.', 'I like them.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “What are these animals)”:',
                                   't': 'mcq'},
                                  {'id': 't1.2', 'o': ['do', 'does', 'is', 'are'], 'plain': True, 'q': 'A: What ____________ these animals?', 't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['I want to see giraffes.',
                                         'They are lions.',
                                         'He wants to see hippos.',
                                         'Because they are scary.',
                                         'Because they dance beautifully.'],
                                   'plain': True,
                                   'q': 'What are these animals?',
                                   't': 'mcq'},
                                  {'id': 't1.4',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: Wow, those _____ are so beautiful.',
                                   't': 'mcq'},
                                  {'id': 't1.5', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['animals,', 'Minh?', 'those', 'are', 'What']},
                                  {'id': 't1.6',
                                   'o': ['They are lions.', 'They look strong.', 'They are giraffes.', 'Because they roar loudly.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like lions?”',
                                   't': 'mcq'},
                                  {'id': 't1.7', 'o': ['are', 'do', 'is', 'does'], 'plain': True, 'q': 'Why ____________ you like peacocks?', 't': 'mcq'},
                                  {'id': 't1.8',
                                   'o': ['I want to see giraffes.',
                                         'They are lions.',
                                         'He wants to see hippos.',
                                         'Because they are scary.',
                                         'Because they dance beautifully.'],
                                   'plain': True,
                                   'q': 'Why do you like peacocks?',
                                   't': 'mcq'},
                                  {'id': 't1.9',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: _____ animals do you like?',
                                   't': 'mcq'},
                                  {'id': 't1.10', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['are', 'They', 'giraffes.']},
                                  {'id': 't1.11',
                                   'o': ['Why do you like lions?', 'What are these animals?', 'What do you want to see?', 'Why do you like birds?'],
                                   'plain': True,
                                   'q': 'Câu “They\'re birds." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 't1.12',
                                   'o': ['What', 'Where', 'Why', 'When'],
                                   'plain': True,
                                   'q': 'A: ________________ do you like birds?',
                                   't': 'mcq'},
                                  {'id': 't1.13',
                                   'o': ['I want to see giraffes.',
                                         'They are lions.',
                                         'He wants to see hippos.',
                                         'Because they are scary.',
                                         'Because they dance beautifully.'],
                                   'plain': True,
                                   'q': "Why doesn't Lan like crocodiles?",
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Minh: I like _____.',
                                   't': 'mcq'},
                                  {'id': 't1.15', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['quickly.', 'are', 'Those', 'running', 'giraffes']},
                                  {'id': 't1.16',
                                   'o': ["They're peacocks.", 'Because they run quickly.', 'Because they roar loudly.', 'Because they dance beautifully.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Why do you like peacocks?”',
                                   't': 'mcq'},
                                  {'id': 't1.17',
                                   'o': ['because it', 'because they', 'because', 'because that'],
                                   'plain': True,
                                   'q': 'I like peacocks __________ dance beautifully.',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['I want to see giraffes.',
                                         'They are lions.',
                                         'He wants to see hippos.',
                                         'Because they are scary.',
                                         'Because they dance beautifully.'],
                                   'plain': True,
                                   'q': 'What animals do you want to see?',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['Why', 'giraffes', 'like', 'peacocks', 'hippos', 'strong', 'What'],
                                   'plain': True,
                                   'q': 'Chọn từ cho chỗ trống: Nam: _____ do you like peacocks?',
                                   't': 'mcq'},
                                  {'id': 't1.20', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['lions', 'roaring', 'loudly.', 'Those', 'are']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': 'Unit 19 – The animal world: Kiểm tra 1',
 'unit': 19}
