# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

SET = {'grade': 4,
 'id': 'lop4-ck1-de19',
 'pages': [{'audio': True,
            'audio_max_plays': 3,
            'groups': [{'id': 'a1',
                        'instr': 'I. Listen and tick (nghe và chọn tranh đúng).',
                        'items': [{'id': 'a1.1', 'img': 'a1_1.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.2', 'img': 'a1_2.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.3', 'img': 'a1_3.png', 'o': ['A', 'B'], 'plain': True, 'q': 'Nghe và chọn tranh đúng.', 't': 'mcq', 'wide': True},
                                  {'id': 'a1.4',
                                   'img': 'a1_4.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'Nghe và chọn tranh đúng.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'a2',
                        'instr': 'II. Listen and number (nghe và chọn tranh cho từng câu).',
                        'items': [{'id': 'a2.5', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 1: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.6', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 2: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.7', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 3: câu đó ứng với tranh nào?', 't': 'mcq'},
                                  {'id': 'a2.8', 'o': ['A', 'B', 'C', 'D'], 'plain': True, 'q': 'Nghe câu số 4: câu đó ứng với tranh nào?', 't': 'mcq'}],
                        'passage': '<img class="wide" src="../../../../assets/lop4_ck1_de19/a2.png" alt="Tranh A-D">'},
                       {'id': 'a3',
                        'instr': 'III. Listen and tick or cross (nghe, nội dung nghe có khớp với tranh không?).',
                        'items': [{'id': 'a3.9', 'img': 'a3_1.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'},
                                  {'id': 'a3.10', 'img': 'a3_2.png', 'q': 'Nội dung nghe có đúng với tranh không? (đúng = True, sai = False)', 't': 'tf'}]},
                       {'id': 'a4',
                        'instr': 'IV. Listen and write (nghe và điền từ).',
                        'items': [{'id': 'a4.11', 'q': 'A: I can fly a kite.<br>B: I can {_}.', 't': 'fill'},
                                  {'id': 'a4.12', 'q': 'A: What do you do on {_}?<br>B: I go to school.', 't': 'fill'}]},
                       {'id': 'b1',
                        'instr': 'I. Look, read and tick the correct picture (đọc câu và chọn tranh đúng).',
                        'items': [{'id': 'b1.13',
                                   'img': 'b1_1.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'A: What day is it today? B: It’s Tuesday.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'b1.14',
                                   'img': 'b1_2.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'My favourite subject is PE.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'b1.15',
                                   'img': 'b1_3.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'A: What time do you go to school? B: I go to school at 7.15.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'b1.16',
                                   'img': 'b1_4.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'I was at the campsite last weekend.',
                                   't': 'mcq',
                                   'wide': True},
                                  {'id': 'b1.17',
                                   'img': 'b1_5.png',
                                   'o': ['A', 'B'],
                                   'plain': True,
                                   'q': 'A: What do you want to eat? B: I want some jam.',
                                   't': 'mcq',
                                   'wide': True}]},
                       {'id': 'b2',
                        'instr': 'II. Read the passage and answer the questions (đọc và trả lời câu hỏi).',
                        'items': [{'id': 'b2.18', 'q': 'Where is Duong’s school?<br>{_}', 't': 'fill'},
                                  {'id': 'b2.19', 'q': 'How many buildings are there at his school?<br>{_}', 't': 'fill'},
                                  {'id': 'b2.20', 'q': 'Is there a garden at his school?<br>{_}', 't': 'fill'},
                                  {'id': 'b2.21', 'q': 'Where is Nam’s school?<br>{_}', 't': 'fill'},
                                  {'id': 'b2.22', 'q': 'How many computer rooms are there at Nam’s school?<br>{_}', 't': 'fill'}],
                        'passage': '<p>Hello, everyone. My name is Duong and I’m 10 years old. I’m a student at a primary school. It’s big and it is in the '
                                   'village. There are three buildings and a large garden at our school. The garden has a lot of trees and flowers. There is a '
                                   'big and beautiful playground at my school, too. Students often play sports and games there at break time. Nam is my penpal '
                                   'friend. His school is in the city. It’s a big and modern school in Ha Noi. There are two computer rooms and four high '
                                   'buildings at his school. I wish I will have a chance to visit his school some day.</p>'},
                       {'id': 'c1',
                        'instr': 'I. Look and complete (nhìn tranh, điền từ).',
                        'items': [{'id': 'c1.23', 'img': 'c1_1.png', 'q': 'I have {_} and Vietnamese on Mondays.', 't': 'fill'},
                                  {'id': 'c1.24', 'img': 'c1_2.png', 'q': 'I was in the {_} last weekend.', 't': 'fill'},
                                  {'id': 'c1.25', 'img': 'c1_3.png', 'q': 'I get up at {_} everyday.', 't': 'fill'},
                                  {'id': 'c1.26', 'img': 'c1_4.png', 'q': 'A: What do you do on Sundays?<br>B: I {_}.', 't': 'fill'},
                                  {'id': 'c1.27', 'img': 'c1_5.png', 'q': 'A: What do you want to eat?<br>B: I want some {_}.', 't': 'fill'}]},
                       {'id': 'c2',
                        'instr': 'Reorder the words (sắp xếp từ thành câu đúng).',
                        'items': [{'id': 'c2.28',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['big', 'There', 'a', 'is', 'at', 'playground', 'school.', 'my']},
                                  {'id': 'c2.29', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['some', 'want', 'lemonade.', 'I']},
                                  {'id': 'c2.30', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['breakfast', 'I', 'at', '6.30.', 'have']},
                                  {'id': 'c2.31', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['zoo', 'I', 'at', 'the', 'was', 'yesterday.']},
                                  {'id': 'c2.32',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['Mondays.', 'maths', 'I', 'and', 'music', 'have', 'on']}]}],
            'id': 'kiem-tra',
            'minutes': 35,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 5}],
 'theory': '',
 'title': 'Cuối kỳ 1 – Đề 19 (25-26)',
 'unit': 'CuoiKy1'}
