# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-u15-test01',
 'pages': [{'groups': [{'id': 't1',
                        'instr': 'Làm 20 câu. Nộp bài để xem điểm và đáp án.',
                        'items': [{'id': 't1.1',
                                   'o': ['Where are you?', 'Where do you go?', 'What do you do in the morning?', 'Where do you work?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi ai đó đi đâu?',
                                   't': 'mcq'},
                                  {'id': 't1.2',
                                   'o': ['is', 'are', 'do', 'does'],
                                   'plain': True,
                                   'q': 'Where ____________ your brother go on Saturdays?',
                                   't': 'mcq'},
                                  {'id': 't1.3',
                                   'o': ['He plays tennis on Sundays.',
                                         'He goes to the sport centre.',
                                         'She does yoga on Sundays.',
                                         'I go to the swimming pool.',
                                         'She cooks meals on Saturdays.'],
                                   'plain': True,
                                   'q': 'What does your mother do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['go', 'Sundays?', 'do', 'Where', 'on', 'you']},
                                  {'id': 't1.5',
                                   'o': ['What do you do on Sundays?',
                                         'Where does she go on Sundays?',
                                         'Where does he go on Sundays?',
                                         'What does she look like?'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây hỏi: “Cô ấy đi đâu vào các ngày Chủ nhật?”?',
                                   't': 'mcq'},
                                  {'id': 't1.6',
                                   'o': ['go', 'goes', 'going', 'to go'],
                                   'plain': True,
                                   'q': 'My sister ____________ to the shopping centre on Sundays.',
                                   't': 'mcq'},
                                  {'id': 't1.7',
                                   'o': ['He plays tennis on Sundays.',
                                         'He goes to the sport centre.',
                                         'She does yoga on Sundays.',
                                         'I go to the swimming pool.',
                                         'She cooks meals on Saturdays.'],
                                   'plain': True,
                                   'q': 'What does your father do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.8',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['on', 'Sundays.', 'to', 'the', 'I', 'go', 'sports', 'centre']},
                                  {'id': 't1.9',
                                   'o': ["She's beautiful.",
                                         'She goes to the swimming pool on Saturdays.',
                                         'She goes to the cinema on Sundays.',
                                         'She washes the floor on Sundays.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây trả lời cho câu hỏi: “Where does she go on Sundays?”?',
                                   't': 'mcq'},
                                  {'id': 't1.10',
                                   'o': ['are', 'is', 'do', 'does'],
                                   'plain': True,
                                   'q': 'What _____________ your father do on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.11',
                                   'o': ['He plays tennis on Sundays.',
                                         'He goes to the sport centre.',
                                         'She does yoga on Sundays.',
                                         'I go to the swimming pool.',
                                         'She cooks meals on Saturdays.'],
                                   'plain': True,
                                   'q': 'What does your sister do on Saturdays?',
                                   't': 'mcq'},
                                  {'id': 't1.12', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Sundays?', 'What', 'on', 'do', 'you', 'do']},
                                  {'id': 't1.13',
                                   'o': ['Where does she go on Sundays?',
                                         'What does she do in the morning?',
                                         'What does she look like?',
                                         'What does she do on Sundays?'],
                                   'plain': True,
                                   'q': 'Câu "She plays tennis on Sundays."',
                                   't': 'mcq'},
                                  {'id': 't1.14',
                                   'o': ['play', 'plays', 'do', 'does'],
                                   'plain': True,
                                   'q': 'Mai _____________ yoga on Saturdays evenings.',
                                   't': 'mcq'},
                                  {'id': 't1.15',
                                   'o': ['He plays tennis on Sundays.',
                                         'He goes to the sport centre.',
                                         'She does yoga on Sundays.',
                                         'I go to the swimming pool.',
                                         'She cooks meals on Saturdays.'],
                                   'plain': True,
                                   'q': 'Where does your brother go on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.16', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['friends.', 'with', 'play', 'my', 'I', 'football']},
                                  {'id': 't1.17',
                                   'o': ['What does he look like?', 'What does he do?', 'Where does he come from?', 'Where does he go on Saturdays?'],
                                   'plain': True,
                                   'q': 'Câu “He goes to the sports centre." trả lời cho câu hỏi nào sau đây:',
                                   't': 'mcq'},
                                  {'id': 't1.18',
                                   'o': ['cooks', 'cook', 'is cook', 'cooking'],
                                   'plain': True,
                                   'q': 'She ____________ meals on Sundays.',
                                   't': 'mcq'},
                                  {'id': 't1.19',
                                   'o': ['He plays tennis on Sundays.',
                                         'He goes to the sport centre.',
                                         'She does yoga on Sundays.',
                                         'I go to the swimming pool.',
                                         'She cooks meals on Saturdays.'],
                                   'plain': True,
                                   'q': 'Where do you go on Sundays?',
                                   't': 'mcq'},
                                  {'id': 't1.20',
                                   'q': 'Sắp xếp thành câu đúng:',
                                   't': 'order',
                                   'words': ['father', 'Saturdays?', 'go', 'on', 'does', 'Where', 'your']}]}],
            'id': 'kiem-tra',
            'minutes': 15,
            'mode': 'test',
            'title': 'Làm bài',
            'warn_at': 2}],
 'theory': '',
 'title': "Unit 15 – My family's weekends: Kiểm tra 1",
 'unit': 15}
