# -*- coding: utf-8 -*-
"""Sinh bởi tools/g4_exam.py"""

ANS = {'a.1': 'C',
 'a.2': 'A',
 'a.3': 'C',
 'a.4': 'C',
 'b.5': 'C',
 'b.6': 'D',
 'b.7': 'C',
 'b.8': 'A',
 'c.10': 'B',
 'c.11': 'A',
 'c.12': 'C',
 'c.13': 'D',
 'c.14': 'D',
 'c.15': 'A',
 'c.16': 'A',
 'c.17': 'C',
 'c.18': 'B',
 'c.9': 'B',
 'd.19': {'blanks': [['bloomed']]},
 'd.20': {'blanks': [['rotated']]},
 'd.21': {'blanks': [['isn’t walking']]},
 'd.22': {'blanks': [['aren’t watching']]},
 'd.23': {'blanks': [['Does'], ['dance']]},
 'd.24': {'blanks': [['Does'], ['swim']]},
 'd.25': {'blanks': [['play']]},
 'd.26': {'blanks': [['cooks']]},
 'd.27': {'blanks': [['Did'], ['sleep']]},
 'd.28': {'blanks': [['Did'], ['bark']]},
 'e.29': {'blanks': [['Good night, Dad and Mom.'], ['Yes. I have three chickens.'], ['I’m Korean.'], ['It’s the first of October.'], ['I’m from England.']]},
 'f.35': 'F',
 'f.36': 'F',
 'f.37': 'F',
 'f.38': 'T',
 'f.39': 'T',
 'g.40': ["She doesn't read books every night."],
 'g.41': ["We don't go swimming on Saturdays."],
 'g.42': ['Birds are not singing in the winter.'],
 'g.43': ['Cats are not sleeping outside.'],
 'g.44': ['Did I play soccer yesterday?'],
 'wrfix.30': ['Do I play soccer after school?'],
 'wrfix.31': ['Does she read books every night?'],
 'wrfix.32': ['I didn’t play soccer yesterday.'],
 'wrfix.33': ['She didn’t read a book last night.'],
 'wrfix.34': ['We are not visiting grandma next week.']}

EXPLANATIONS = {'a.1': 'Đáp án: C. kites',
 'a.2': 'Đáp án: A. has',
 'a.3': 'Đáp án: C. read',
 'a.4': 'Đáp án: C. fish',
 'b.5': 'Đáp án: C. p<u>u</u>ll',
 'b.6': 'Đáp án: D. classm<u>a</u>te',
 'b.7': 'Đáp án: C. p<u>e</u>rson',
 'b.8': 'Đáp án: A. <u>th</u>at',
 'c.10': 'Đáp án: B. go',
 'c.11': 'Đáp án: A. bloom',
 'c.12': 'Đáp án: C. sleeps',
 'c.13': 'Đáp án: D. sets',
 'c.14': 'Đáp án: D. rises',
 'c.15': 'Đáp án: A. traveled',
 'c.16': 'Đáp án: A. are going to',
 'c.17': 'Đáp án: C. am learning',
 'c.18': 'Đáp án: B. playing',
 'c.9': 'Đáp án: B. visited',
 'd.19': 'Đáp án: bloomed',
 'd.20': 'Đáp án: rotated',
 'd.21': 'Đáp án: isn’t walking',
 'd.22': 'Đáp án: aren’t watching',
 'd.23': 'Đáp án: Does / dance',
 'd.24': 'Đáp án: Does / swim',
 'd.25': 'Đáp án: play',
 'd.26': 'Đáp án: cooks',
 'd.27': 'Đáp án: Did / sleep',
 'd.28': 'Đáp án: Did / bark',
 'e.29': '1–C; 2–A; 3–E; 4–B; 5–D (theo đáp án của đề).',
 'f.35': 'Đáp án: False (theo đáp án của đề).',
 'f.36': 'Đáp án: False (theo đáp án của đề).',
 'f.37': 'Đáp án: False (theo đáp án của đề).',
 'f.38': 'Đáp án: True (theo đáp án của đề).',
 'f.39': 'Đáp án: True (theo đáp án của đề).',
 'g.40': "Câu đúng: She doesn't read books every night.",
 'g.41': "Câu đúng: We don't go swimming on Saturdays.",
 'g.42': 'Câu đúng: Birds are not singing in the winter.',
 'g.43': 'Câu đúng: Cats are not sleeping outside.',
 'g.44': 'Câu đúng: Did I play soccer yesterday?',
 'h.45': 'Đáp án mẫu (theo đáp án của đề): <b>How many classes does your school have?</b>',
 'h.46': 'Đáp án mẫu (theo đáp án của đề): <b>That is a small classroom.</b>',
 'h.47': "Đáp án mẫu (theo đáp án của đề): <b>Mary is Peter's sister.</b>",
 'h.48': 'Đáp án mẫu (theo đáp án của đề): <b>There are four floors in my house.</b>',
 'h.49': 'Đáp án mẫu (theo đáp án của đề): <b>John is the son of Mr. and Mrs. Black.</b>',
 'wrfix.30': 'Sửa lỗi: Does → Do. Câu đúng: Do I play soccer after school?',
 'wrfix.31': 'Sửa lỗi: reads → read. Câu đúng: Does she read books every night?',
 'wrfix.32': 'Sửa lỗi: don’t → didn’t. Câu đúng: I didn’t play soccer yesterday.',
 'wrfix.33': 'Sửa lỗi: doesn’t → didn’t. Câu đúng: She didn’t read a book last night.',
 'wrfix.34': 'Sửa lỗi: visit → visiting. Câu đúng: We are not visiting grandma next week.'}
