# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

ANS = {'t1.1': ['They are putting up a tent.'],
 't1.10': 'doing',
 't1.11': ['He is flying a kite.'],
 't1.12': "They're singing songs.",
 't1.13': 'building',
 't1.14': ['Son is watching TV.'],
 't1.15': "She's at the campsite.",
 't1.16': "isn't",
 't1.17': ['Nam and his friends are playing tug of war.'],
 't1.18': "They're putting up a tent.",
 't1.19': 'playing',
 't1.2': "What's Mai doing?",
 't1.20': ['Are Mai and Lan singing songs?'],
 't1.3': 'they are',
 't1.4': 'She is studing English.',
 't1.5': 'playing',
 't1.6': ['What is Mark doing, Mai?'],
 't1.7': 'What are Mai and Lan doing?',
 't1.8': 'playing',
 't1.9': 'Yes, she is.'}

EXPLANATIONS = {'t1.1': 'Câu đúng: They are putting up a tent.',
 't1.10': 'Đáp án: doing',
 't1.11': 'Câu đúng: He is flying a kite.',
 't1.12': "Đáp án: They're singing songs.",
 't1.13': 'Đáp án: building',
 't1.14': 'Câu đúng: Son is watching TV.',
 't1.15': "Đáp án: She's at the campsite.",
 't1.16': "Đáp án: isn't",
 't1.17': 'Câu đúng: Nam and his friends are playing tug of war.',
 't1.18': "Đáp án: They're putting up a tent.",
 't1.19': 'Đáp án: playing',
 't1.2': "Đáp án: What's Mai doing?",
 't1.20': 'Câu đúng: Are Mai and Lan singing songs?',
 't1.3': 'Đáp án: they are',
 't1.4': 'Đáp án: She is studing English.',
 't1.5': 'Đáp án: playing',
 't1.6': 'Câu đúng: What is Mark doing, Mai?',
 't1.7': 'Đáp án: What are Mai and Lan doing?',
 't1.8': 'Đáp án: playing',
 't1.9': 'Đáp án: Yes, she is.'}
