# -*- coding: utf-8 -*-
"""Sinh bởi tools/gen_lop4.py"""

SET = {'grade': 4,
 'id': 'lop4-start-luyentap',
 'pages': [{'groups': [{'id': 'a',
                        'instr': 'Choose the correct option. (Chọn đáp án đúng.)',
                        'items': [{'id': 'a.1',
                                   'o': ['Good morning.', "What's your name?", 'This is Mary.', 'See you tomorrow.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây được dùng để chào hỏi?',
                                   't': 'mcq'},
                                  {'id': 'a.2',
                                   'o': ['See you later.', 'How are you?', "I'm fine, thank you.", 'Very well, thank you.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây được dùng để hỏi thăm sức khỏe?',
                                   't': 'mcq'},
                                  {'id': 'a.3',
                                   'o': ['Nice to meet you.', "I'm fine, thank you.", 'This is Mai.', 'Open your book, please!'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây giới thiệu một người bạn?',
                                   't': 'mcq'},
                                  {'id': 'a.4',
                                   'o': ["I'm ten years old.", 'Jump up!', "He's skating.", 'Open your books, please!'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói về một hoạt động trong lớp học?',
                                   't': 'mcq'},
                                  {'id': 'a.5',
                                   'o': ['My hobby is swimming.', 'Fly it in the sky.', 'Say goodbye, please!', 'Stand up, please!'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây nói về hoạt động ở ngoài trời?',
                                   't': 'mcq'},
                                  {'id': 'a.6',
                                   'o': ['Nice to see you!', 'Nice to meet you too!', 'See you later.', 'Very well, thank you.'],
                                   'plain': True,
                                   'q': 'Để nói “Rất vui được gặp bạn”, chúng ta nói:',
                                   't': 'mcq'},
                                  {'id': 'a.7',
                                   'o': ['Chúc ngủ ngon!', 'Hẹn gặp lại bạn sau!', 'Tạm biệt!', 'Tôi cũng khỏe.'],
                                   'plain': True,
                                   'q': '“Goodbye” có nghĩa là:',
                                   't': 'mcq'},
                                  {'id': 'a.8',
                                   'o': ['See you tonight.', 'See you tomorrow.', 'Pleased to meet you.', 'See you later.'],
                                   'plain': True,
                                   'q': 'Câu nào sau đây có nghĩa là: “Hẹn gặp lại bạn sau."',
                                   't': 'mcq'},
                                  {'id': 'a.9',
                                   'o': ['What are you doing?', "What's your name?", 'How are you?', 'What are they doing?'],
                                   'plain': True,
                                   'q': 'Câu “I\'m fine, thank you." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'},
                                  {'id': 'a.10',
                                   'o': ['What are they doing?', 'What are you doing?', 'How are you?', "What's he doing?"],
                                   'plain': True,
                                   'q': 'Câu "He\'s riding a bike." trả lời cho câu hỏi nào sau đây?',
                                   't': 'mcq'}]},
                       {'id': 'b',
                        'instr': 'Choose the correct option to complete each blank. (Chọn đáp án để hoàn thành câu.)',
                        'items': [{'id': 'b.1', 'o': ['is', 'are', 'do', 'am'], 'plain': True, 'q': 'How ____________ you, Mai?', 't': 'mcq'},
                                  {'id': 'b.2', 'o': ['later', 'well', 'again', 'tomorrow'], 'plain': True, 'q': 'Nice to see you ____________.', 't': 'mcq'},
                                  {'id': 'b.3', 'o': ['to', 'down', 'in', 'aloud'], 'plain': True, 'q': 'Sit ____________, please.', 't': 'mcq'},
                                  {'id': 'b.4', 'o': ['up', 'down', 'aloud', 'to'], 'plain': True, 'q': 'Stand ____________, please.', 't': 'mcq'},
                                  {'id': 'b.5', 'o': ['down', 'up', 'aloud', 'in'], 'plain': True, 'q': 'Read ____________, please.', 't': 'mcq'},
                                  {'id': 'b.6', 'o': ['is', 'are', 'am', 'do'], 'plain': True, 'q': 'A: What ____________ they doing?', 't': 'mcq'},
                                  {'id': 'b.7', 'o': ['down', 'up', 'aloud', 'in'], 'plain': True, 'q': 'Jump ____________ high.', 't': 'mcq'},
                                  {'id': 'b.8', 'o': ['is', 'are', 'plays', 'do'], 'plain': True, 'q': 'He ____________ running.', 't': 'mcq'},
                                  {'id': 'b.9', 'o': ['cycle', 'cycles', 'are cycling', 'is cycling'], 'plain': True, 'q': "A: What's she doing?", 't': 'mcq'},
                                  {'id': 'b.10', 'o': ['well', 'tomorrow', 'thank', 'meet'], 'plain': True, 'q': 'See you ____________.', 't': 'mcq'}]}],
            'id': 'trac-nghiem',
            'mode': 'practice',
            'title': 'Trắc nghiệm'},
           {'groups': [{'id': 'c',
                        'instr': 'Read and match each sentence in A with the appropriate sentence in B. (Nối câu.)',
                        'items': [{'id': 'c.1',
                                   'left': ['How are you?', 'Good morning, Mr Long.', "What's he doing?", 'What are they doing?', "What's she doing?"],
                                   'o': ["He's flying a kite.", "I'm fine, thank you.", "She's skipping.", 'Good morning, class.', "They're painting."],
                                   'q': 'Nối câu ở cột A với câu phù hợp ở cột B:',
                                   't': 'match'}]}],
            'id': 'noi-hoi-thoai',
            'mode': 'practice',
            'title': 'Nối & hội thoại'},
           {'groups': [{'id': 'f',
                        'instr': 'Reorder the words to make meaningful sentences. (Bấm các từ để xếp thành câu.)',
                        'items': [{'id': 'f.1', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['Nice', 'to', 'you.', 'see']},
                                  {'id': 'f.2', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['book,', 'your', 'Close', 'please.']},
                                  {'id': 'f.3', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['is', 'Mary.', 'This']},
                                  {'id': 'f.4', 'q': 'Sắp xếp thành câu đúng:', 't': 'order', 'words': ['badminton.', 'They', 'playing', 'are']}]}],
            'id': 'sap-xep-cau',
            'mode': 'practice',
            'title': 'Sắp xếp câu'}],
 'theory': '',
 'title': 'Bài mở đầu: Luyện tập',
 'unit': 'Start'}
