# -*- coding: utf-8 -*-
"""Dữ liệu nội dung SET (sinh từ file Word bằng tools/gen_units.py rồi có thể chỉnh tay).
Đáp án + giải thích: xem file *_dapan.py cùng tên."""

SET = {'id': 'lop11-mt1-test12',
 'title': 'Test 12 – Mid-term 1',
 'grade': 11,
 'unit': 'MidTerm1',
 'theory': '',
 'pages': [{'id': 'kiem-tra',
            'title': 'Làm bài',
            'mode': 'test',
            'minutes': 45,
            'audio': True,
            'groups': [{'id': 'g1',
                        'instr': 'I/ Listening (2 points) – Listen and complete the summaries of the two viewpoints.',
                        'passage': '<p>According to the pessimistic viewpoint, our future cities will not be safe and <b>(1) ______</b> places to '
                                   'live in. Governments have no <b>(2) ______</b> ways to control pollution, which will continue to be a serious '
                                   'problem in the future. Moreover, cities will become <b>(3) ______</b>, which means there will be more waste and '
                                   'heavier traffic.</p><p>According to the optimistic viewpoint, city dwellers will have a better life thanks to '
                                   'advances in technology and <b>(4) ______</b>. Furthermore, the environmental problems will be solved. <b>(5) '
                                   '______</b> energy sources will gradually replace fossil fuels in the next twenty years.</p>',
                        'items': [{'id': 'g1.1', 't': 'fill', 'q': 'Blank (1): {_}'},
                                  {'id': 'g1.2', 't': 'fill', 'q': 'Blank (2): {_}'},
                                  {'id': 'g1.3', 't': 'fill', 'q': 'Blank (3): {_}'},
                                  {'id': 'g1.4', 't': 'fill', 'q': 'Blank (4): {_}'},
                                  {'id': 'g1.5', 't': 'fill', 'q': 'Blank (5): {_}'}]},
                       {'id': 'g2',
                        'instr': 'Ex 2: Listen to the recording and choose the correct answer A, B, C or D.',
                        'items': [{'id': 'g2.6',
                                   't': 'mcq',
                                   'q': 'One hundred years ago, what percentage of the human population lived in cities?',
                                   'o': ['10%', '20%', '40%', '80%']},
                                  {'id': 'g2.7',
                                   't': 'mcq',
                                   'q': 'What led to the development of the first semi-permanent settlements?',
                                   'o': ['Changes in the global climate',
                                         'An increase in fresh water supplies',
                                         'Improvements in healthcare',
                                         'Advancements in agriculture']},
                                  {'id': 'g2.8',
                                   't': 'mcq',
                                   'q': 'Which of these technologies developed because of the desire to trade with other cities?',
                                   'o': ['Tractors', 'City walls', 'Roads', 'Aqueducts']},
                                  {'id': 'g2.9',
                                   't': 'mcq',
                                   'q': 'Why did people first move into cities?',
                                   'o': ['Jobs', 'Fun', 'Safety', 'More farmland']},
                                  {'id': 'g2.10',
                                   't': 'mcq',
                                   'q': 'The global population is expected to peak at ______ billion.',
                                   'o': ['7', '6', '9', '10']}]},
                       {'id': 'g3',
                        'instr': 'II/ Trắc nghiệm (3 points) – Circle A, B, C or D to indicate the word whose underlined part differs from the other '
                                 'three in pronunciation.',
                        'items': [{'id': 'g3.11', 't': 'mcq', 'q': '', 'o': ['m<u>u</u>scle', 's<u>u</u>ffer', 'yogh<u>u</u>rt', 'instr<u>u</u>ct']},
                                  {'id': 'g3.12', 't': 'mcq', 'q': '', 'o': ['fr<u>e</u>sh', 'di<u>e</u>t', 'fl<u>e</u>sh', '<u>e</u>xercise']}]},
                       {'id': 'g4',
                        'instr': 'Circle A, B, C, or D to indicate the word that differs from the other three in the position of the primary stress.',
                        'items': [{'id': 'g4.13', 't': 'mcq', 'q': '', 'o': ['asleep', 'avoid', 'formal', 'remind']},
                                  {'id': 'g4.14', 't': 'mcq', 'q': '', 'o': ['robot', 'sensor', 'impress', 'urban']}]},
                       {'id': 'g5',
                        'instr': 'Ex 3. Read the following text and choose the best answer.',
                        'passage': '<p>The family dynamic evolves as a teen matures, and can test the parent-teen relationship. With both sides '
                                   'feeling mixed emotions, this time can be challenging.</p><p>Puberty brings lots of emotions for teens, and is a '
                                   "time of readjustment for the whole family. Parents have a huge influence on a young child's values and "
                                   'interests, and so it can often feel hard for them to separate from their teen, who wants to develop their own '
                                   'identity and to have new freedoms. <b><u>This</u></b> may lead to conflict, as both parents and teens need time '
                                   'to figure out how to adapt the relationship.</p><p>As teens get older, it is important for them to take on '
                                   'responsibilities. This highlights the valuable contribution each family member makes to a home, and teaches '
                                   "teens about what it's like to be an adult. Setting clear rules about routine and home life helps teens to know "
                                   "what's expected of them—even if they do complain or resist. Expectations go both ways, however, and so constant "
                                   'communication and flexibility when necessary will help avoid conflict.</p><p>It is important for parents and '
                                   "teens to overcome life's many distractions in order to spend quality time together. For parents, maintaining a "
                                   'close relationship with a teen who is preprogrammed to separate from them can be tricky, but it helps to be '
                                   'present and <b><u>willing</u></b>. Talking about the things that are going well is as helpful as discussing '
                                   'areas of conflict.</p>',
                        'items': [{'id': 'g5.15',
                                   't': 'mcq',
                                   'q': 'What is the main idea of the passage?',
                                   'o': ['Puberty of teenagers',
                                         "Teens' romantic relationship",
                                         'Parent-teen relationship',
                                         "Teens' responsibilities"]},
                                  {'id': 'g5.16',
                                   't': 'mcq',
                                   'q': 'The word "<b>this</b>" in paragraph 2 refers to:',
                                   'o': ['Puberty brings lots of emotions for teens',
                                         "Parents have a huge influence on a young child's values and interests",
                                         'Both parents and teens need time to adapt the relationship',
                                         'Parents cannot separate from their teens who want to be free']},
                                  {'id': 'g5.17',
                                   't': 'mcq',
                                   'q': 'The word "<b>willing</b>" is CLOSEST in meaning to',
                                   'o': ['shocked', 'ready', 'strict', 'sympathetic']},
                                  {'id': 'g5.18',
                                   't': 'mcq',
                                   'q': 'Which of the following is <b>NOT TRUE</b> about the solution as teens get older?',
                                   'o': ['Complain and resist',
                                         'Communicate constantly',
                                         'Set rules about routine and home life',
                                         'Ask teens to take on responsibilities']}]},
                       {'id': 'g6',
                        'instr': 'Ex 4. Circle A, B, C or D to indicate the correct answer to each of the following questions.',
                        'items': [{'id': 'g6.19',
                                   't': 'mcq',
                                   'q': 'I have never played badminton before. This is the first time I ______ to play it.',
                                   'o': ['try', 'tried', 'have tried', 'am trying']},
                                  {'id': 'g6.20',
                                   't': 'mcq',
                                   'q': 'We ______ eat as much fruit as possible in order to get enough vitamins for our bodies.',
                                   'o': ['had better', 'should', 'ought to', 'All are correct']},
                                  {'id': 'g6.21',
                                   't': 'mcq',
                                   'q': 'Your parents appear ______ with you, but also very fair.',
                                   'o': ['strictly', 'strict', 'strictness', 'open-minded']},
                                  {'id': 'g6.22',
                                   't': 'mcq',
                                   'q': 'At present, I ______ calm.',
                                   'o': ['remain', 'remained', 'is remaining', 'was remaining']}]},
                       {'id': 'g7',
                        'instr': 'III/ Tự luận (5 points) – Ex 1. Complete the following sentences with the correct forms of the words in capitals.',
                        'items': [{'id': 'g7.23', 't': 'fill', 'q': 'Raw meat and poultry may contain harmful {_}. <b>(BACTERIUM)</b>'},
                                  {'id': 'g7.24',
                                   't': 'fill',
                                   'q': 'Food with a lot of sugar is not very good for your skin, so you should cut down on {_} desserts and drinks. '
                                        '<b>(SUGAR)</b>'},
                                  {'id': 'g7.25',
                                   't': 'fill',
                                   'q': 'Many important {_} documents were destroyed when the library was burned. <b>(HISTORY)</b>'},
                                  {'id': 'g7.26', 't': 'fill', 'q': '{_} is one of the common characteristics of Generation Y. <b>(CURIOUS)</b>'},
                                  {'id': 'g7.27',
                                   't': 'fill',
                                   'q': 'Environmentalists say there is a high risk of {_} from the landfill site. <b>(POLLUTE)</b>'},
                                  {'id': 'g7.28',
                                   't': 'fill',
                                   'q': 'The disease spread quickly among the poor slum {_} of the city. <b>(DWELL)</b>'}]},
                       {'id': 'g8',
                        'instr': 'Ex 2. Rewrite the following sentences as long as the meaning is unchanged.',
                        'items': [{'id': 'g8.29', 't': 'fill', 'q': "Why don't we go camping this summer?<br>How about {_}?", 'long': True},
                                  {'id': 'g8.30',
                                   't': 'fill',
                                   'q': 'It is forbidden for students to cheat in the exam.<br>Students {_}.',
                                   'long': True},
                                  {'id': 'g8.31', 't': 'fill', 'q': "He hasn't played basketball for 6 months.<br>The last time {_}.", 'long': True},
                                  {'id': 'g8.32',
                                   't': 'fill',
                                   'q': 'It was such a dirty beach that I decided not to stay.<br>The beach {_}.',
                                   'long': True}]}]}]}
