# -*- coding: utf-8 -*-
"""Dữ liệu nội dung SET (sinh từ file Word bằng tools/gen_units.py rồi có thể chỉnh tay).
Đáp án + giải thích: xem file *_dapan.py cùng tên."""

SET = {'id': 'lop11-mt1-test13',
 'title': 'Test 13 – Mid-term 1',
 'grade': 11,
 'unit': 'MidTerm1',
 'theory': '',
 'pages': [{'id': 'kiem-tra',
            'title': 'Làm bài',
            'mode': 'test',
            'minutes': 45,
            'audio': True,
            'groups': [{'id': 'g1',
                        'instr': 'PHẦN NGHE (2.0 pts) – Part 1: Listen and choose the correct information.',
                        'items': [{'id': 'g1.1',
                                   't': 'mcq',
                                   'q': 'What is the interview mainly about?',
                                   'o': ['Advantages of living in a smart city.',
                                         'Problems of living in a smart city.',
                                         'Attractions of urban lifestyles.',
                                         'Comforts of urban lifestyles.']},
                                  {'id': 'g1.2',
                                   't': 'mcq',
                                   'q': 'How are cameras and sensors used in a smart city?',
                                   'o': ['To collect information about city dwellers and their activities.',
                                         'To collect information about the government and some companies.',
                                         "To improve city dwellers' safety and security.",
                                         'To show the problems the police.']},
                                  {'id': 'g1.3',
                                   't': 'mcq',
                                   'q': 'What do the government and some companies have?',
                                   'o': ['So much information about city life',
                                         'So much information about night life',
                                         'So much private information about city residents',
                                         'So much information about crimes.']},
                                  {'id': 'g1.4',
                                   't': 'mcq',
                                   'q': 'Why does it take Miss Stevens a long time to get familiar with all the smart devices at home?',
                                   'o': ['She has some friends to help.',
                                         "She doesn't have any neighborhood friends for help.",
                                         'She gets some support from neighbors.',
                                         'She does not know how to use smart devices.']},
                                  {'id': 'g1.5',
                                   't': 'mcq',
                                   'q': 'Why does Ms Stevens feel lonely?',
                                   'o': ["Because she doesn't interact with many people.",
                                         "Because she can't use the smart devices.",
                                         "Because she doesn't like her neighbourhood.",
                                         "Because she doesn't go out."]}]},
                       {'id': 'g2',
                        'instr': 'Part 2: Listen and complete the form below. No more than two words for each answer.',
                        'passage': '<p>According to the pessimistic viewpoint, our future cities will not be safe and <b>(6) ______</b> places to '
                                   'live in. Governments have no <b>(7) ______</b> ways to control pollution, which will continue to be a serious '
                                   'problem in the future. Moreover, cities will become <b>(8) ______</b>, which means there will be more waste and '
                                   'heavier traffic.</p><p>According to the optimistic viewpoint, city dwellers will have a better life thanks to '
                                   'advances in technology and <b>(9) ______</b>. Furthermore, the environmental problems will be solved. Renewable '
                                   'energy sources will gradually replace <b>(10) ______</b> in the next twenty years.</p>',
                        'items': [{'id': 'g2.6', 't': 'fill', 'q': 'Blank (6): {_}'},
                                  {'id': 'g2.7', 't': 'fill', 'q': 'Blank (7): {_}'},
                                  {'id': 'g2.8', 't': 'fill', 'q': 'Blank (8): {_}'},
                                  {'id': 'g2.9', 't': 'fill', 'q': 'Blank (9): {_}'},
                                  {'id': 'g2.10', 't': 'fill', 'q': 'Blank (10): {_}'}]},
                       {'id': 'g3',
                        'instr': 'PHẦN TRẮC NGHIỆM – I. Write the letter A, B, C, or D to indicate the word whose underlined part differs from the '
                                 'other three in pronunciation. (0.5 pt)',
                        'items': [{'id': 'g3.11', 't': 'mcq', 'q': '', 'o': ['pr<u>i</u>vate', 'publ<u>i</u>c', 'c<u>i</u>ty', '<u>i</u>nteract']},
                                  {'id': 'g3.12',
                                   't': 'mcq',
                                   'q': '',
                                   'o': ['<u>s</u>olar', 'infra<u>s</u>tructure', 'de<u>s</u>igner', 'focu<u>s</u>']}]},
                       {'id': 'g4',
                        'instr': 'II. Write the letter A, B, C, or D to indicate the word that differs from the other three in the position of '
                                 'primary stress. (0.5 pt)',
                        'items': [{'id': 'g4.13', 't': 'mcq', 'q': '', 'o': ['apartment', 'emission', 'location', 'harmony']},
                                  {'id': 'g4.14', 't': 'mcq', 'q': '', 'o': ['article', 'privacy', 'quality', 'solution']}]},
                       {'id': 'g5',
                        'instr': 'III. Write the letter A, B, C, or D to indicate the correct answer to each of the following questions. (1.5 pts)',
                        'items': [{'id': 'g5.15',
                                   't': 'mcq',
                                   'q': 'Have you been ______ by the doctor yet?',
                                   'o': ['fixed', 'examined', 'investigated', 'repaired']},
                                  {'id': 'g5.16',
                                   't': 'mcq',
                                   'q': "Life ______ for smokers is shorter than for people who don't smoke.",
                                   'o': ['strength', 'expectation', 'expectancy', 'routine']},
                                  {'id': 'g5.17',
                                   't': 'mcq',
                                   'q': 'There are agreed rules in each family that its members ______ follow.',
                                   'o': ["don't have to", 'must', "mustn't", 'had to']},
                                  {'id': 'g5.18',
                                   't': 'mcq',
                                   'q': "My father ______ of going on a diet. He's put on weight recently.",
                                   'o': ['thinks', 'is thinking', 'thought', 'has thought']},
                                  {'id': 'g5.19',
                                   't': 'mcq',
                                   'q': 'Your store needs a bold sign that will catch the ______ of anyone walking down the street. That may help to '
                                        'sell more products.',
                                   'o': ['eye', 'peek', 'flash', 'glimpse']},
                                  {'id': 'g5.20',
                                   't': 'mcq',
                                   'q': 'The government ______ the infrastructure of big cities to boost the economy recently.',
                                   'o': ['has improved', 'improved', 'should improve', 'improves']}]},
                       {'id': 'g6',
                        'instr': 'IV. Read the following passage and mark the letter A, B, C or D to indicate the correct answer to each of the '
                                 'questions. (1.5 pts)',
                        'passage': "<h4>The best time to exercise</h4><p>We all know the importance of exercise as a healthy habit. But what's the "
                                   'best time to exercise? Research has shown that morning, afternoon, or evening workouts have their own benefits. '
                                   'When you work out in the morning, you burn more fat. In fact, those who start their exercise routine on an empty '
                                   'stomach can burn about 20 per cent more body fat than those exercising later in the day. Morning exercise also '
                                   'helps many people sleep better at night.</p><p>Afternoon or evening workouts can also bring benefits. Remember '
                                   'that your temperature is the highest between 2 p.m. and 6 p.m. This temperature helps increase your muscle '
                                   'strength and endurance. In the afternoon or evening, your reaction time is at its quickest, while your heart '
                                   'rate and blood pressure are the lowest. Exercising at this time decreases your chances of injury while improving '
                                   'your performance. So, depending on your schedule and preferences, you can choose the best time to work out.</p>',
                        'items': [{'id': 'g6.21',
                                   't': 'mcq',
                                   'q': 'What is the text mainly about?',
                                   'o': ['Workouts at different times and their benefits.',
                                         'Drawbacks of afternoon workouts.',
                                         'Advantages of evening workouts.',
                                         'Benefits of morning workouts and injuries.']},
                                  {'id': 'g6.22',
                                   't': 'mcq',
                                   'q': 'Which of the following is a benefit of a morning workout?',
                                   'o': ['You put on weight.',
                                         'You gain more body fat.',
                                         "You have a better night's sleep.",
                                         'You have an empty stomach.']},
                                  {'id': 'g6.23',
                                   't': 'mcq',
                                   'q': "The word 'endurance' in paragraph 2 means ______.",
                                   'o': ["the ability to see problems and solve them quickly without others' support",
                                         'the ability to continue doing something painful or difficult for a long period of time',
                                         'the ability to work both on your own and in a group',
                                         'the ability to live a balanced life']},
                                  {'id': 'g6.24',
                                   't': 'mcq',
                                   'q': 'Which of the following is a benefit of an afternoon or evening workout?',
                                   'o': ['Your body temperature is the lowest.',
                                         'Your reaction time is slow.',
                                         'Your heart rate and blood pressure are the highest.',
                                         'You can avoid the risk of injury.']},
                                  {'id': 'g6.25',
                                   't': 'mcq',
                                   'q': "The word 'its' in paragraph 2 refers to ______.",
                                   'o': ['afternoon', 'evening', 'reaction time', 'heart rate']},
                                  {'id': 'g6.26',
                                   't': 'mcq',
                                   'q': "The phrase 'blood pressure' in paragraph 2 means ______.",
                                   'o': ['a measure of the force with which blood flows through the body',
                                         'the number of times the heart beats per minute',
                                         'the pressure on your chest',
                                         'the stress that can cause heart problems']}]},
                       {'id': 'g7',
                        'instr': 'PHẦN TỰ LUẬN – I. Complete the sentences using the correct forms of the verbs in brackets. (1 pt) (Ở câu 27 và 28, '
                                 'điền cả hai chỗ trống quanh động từ: trợ động từ và dạng đúng của động từ.)',
                        'items': [{'id': 'g7.27', 't': 'fill', 'q': '{_} scientists <b>(discover)</b> {_} a new cancer drug yet?'},
                                  {'id': 'g7.28', 't': 'fill', 'q': 'I {_} <b>(buy)</b> {_} all the ingredients. Can you help me cook the dish now?'},
                                  {'id': 'g7.29',
                                   't': 'fill',
                                   'q': 'John {_} <b>(build)</b> muscles since he {_} <b>(start)</b> working out at the gym. He looks really fit '
                                        'now.'}]},
                       {'id': 'g8',
                        'instr': 'II. Supply the correct form of the given word in each of the following questions to make meaningful sentences. '
                                 '(1.0 pt)',
                        'items': [{'id': 'g8.30',
                                   't': 'fill',
                                   'q': "This is a 'green city' designed to reduce its {_} impact on the environment. <b>(NEGATE)</b>"},
                                  {'id': 'g8.31',
                                   't': 'fill',
                                   'q': 'AI technologies, such as cameras and smart sensors, will be installed to help the city operate more {_}. '
                                        '<b>(EFFICIENCY)</b>'},
                                  {'id': 'g8.32',
                                   't': 'fill',
                                   'q': 'My grandparents hold {_} views about male jobs and gender roles. <b>(TRADITION)</b>'},
                                  {'id': 'g8.33', 't': 'fill', 'q': 'He is receiving {_} for his health problem. <b>(TREAT)</b>'}]},
                       {'id': 'g9',
                        'instr': 'III. For each question, complete the new sentence so that it means the same as the given one(s). (2 pts)',
                        'items': [{'id': 'g9.34',
                                   't': 'fill',
                                   'q': 'It is not a good idea for women to leave their jobs after getting married. <b>(should not)</b><br>Women {_} '
                                        'married.',
                                   'long': True},
                                  {'id': 'g9.35',
                                   't': 'fill',
                                   'q': 'It is important for all family members to follow the family house rules. <b>(must)</b><br>All family '
                                        'members {_}.',
                                   'long': True},
                                  {'id': 'g9.36',
                                   't': 'fill',
                                   'q': "It has been a long time since we last called each other.<br>We haven't {_}.",
                                   'long': True},
                                  {'id': 'g9.37', 't': 'fill', 'q': 'When did you start the treatment?<br>How long {_}?', 'long': True}]}]}]}
