# -*- coding: utf-8 -*-
"""Đáp án + giải thích – Ôn tập đề cương Mid-term 1 (Tiếng Anh 11 Global Success).
Nguồn Word (dc2223, dc2324, dc2425, tn) KHÔNG có khoá đáp án => toàn bộ đáp án tự giải độc lập.
Quy ước: mcq: chữ cái (list = nhiều đáp án đều đúng); fill: list đáp án chấp nhận hoặc {"blanks": [[..],[..]]}; open: chỉ có EXPLANATIONS (đáp án mẫu)."""

GHI_CHU_RA_SOAT = ['pa1 (tn "hold/follow/force/notice"): chữ gạch chân của "follow" là o CUỐI (/əʊ/) → khoá = force (C); nguồn không có khoá, tự giải.',
 'pa1 (tn "nutrient"): i trong nutrient đọc /i/ (khác /ɪ/ của ingredient, vitamin, mineral) – giữ khoá B, hơi tinh tế.',
 'tv1 (2324 U3 #19 "city ___ to use public transport"): city dwellers (C) và city commuters (A) đều hợp lý → chấp nhận cả A, C.',
 'tv1 (tn "treatment ___ cancer"): cụm chuẩn là "treatment for/of cancer"; đề không có "for" → chọn of (C).',
 'tv3 (2223 well-informed): ill-informed (D) là từ chuẩn, badly-informed (B) cũng được dùng → chấp nhận B, D.',
 'tv3 (2324 U2 #19 concentrate): phương án thấy trong nguồn bị tách dòng (A focus, B abandon, C neglect, D permit) – chọn neglect (C), hơi mơ hồ.',
 'ng1 (2425 Ex3 #26): đáp án lý tưởng là "was playing"; đề không có → chọn played (A).',
 'ng2 (2425 Ex3 #15): shouldn\'t / ought not to cũng đúng ngữ pháp nhưng yếu hơn; khoá lấy mustn\'t (C) theo nghĩa "cấm trong khi thi".',
 'ng3 (tn "Although the dish melt ___"): "melt" là lỗi gõ của "smelt" (smell, quá khứ); khoá chọn good (B).',
 'ng3 (minh hoạ #12): đúng chuẩn là "were sewn"; đề chỉ có "were sewed" nên chọn B.',
 'ng4 (2425 Writing I #5): "That Super Junior (appear) suddenly … makes its fans overjoyed" – dạng đúng là appearing (chủ ngữ danh động từ); chấp nhận thêm '
 'appeared.',
 'ng4 (2425 Writing I #6, #7): think about / smell là động từ có hai nghĩa: ở nghĩa "cân nhắc / ngửi" dùng được tiếp diễn → is thinking; are … smelling.',
 'er1 (2324 U2 #5 "had better not"): câu gốc khó xác định lỗi (nhãn A–D lệch); chọn C (had better not → mustn\'t) – hơi mơ hồ.',
 'er1 (2324 U2 #6): nguồn gạch chân 5 đoạn nhưng chỉ có nhãn A–D; đã gộp "don\'t have to" thành một mục C.',
 'er1 (2324 U1 #34): nguồn không gạch chân "haven\'t played"; đã chuyển gạch chân sang cụm này (đáp án A).',
 'dt7 (tn cloze 6 #1): feel well (A) và feel good (B) đều đúng → chấp nhận A, B.',
 'dt8 (2425 Ex4 #12): reserve (A) và secure (C) đều đúng nghĩa "giữ chỗ" → chấp nhận A, C.',
 'dt12 (2425 #28): harness (C) và utilize (D) đều hợp nghĩa → chấp nhận C, D.',
 'dt13 (2425 minh hoạ Q22): thứ tự hợp lý nhất theo đề là b-c-a-e-d-f (B); phương án C (b-e-d-a-c-f) cũng đọc được nhưng lời mời xuất hiện quá sớm → giữ B, '
 'hơi mơ hồ.',
 'dh4 (2223 reading 4 #3): đáp án A là phương án sát nhất, nhưng cách diễn đạt khá rộng – khoá tự suy luận.',
 'dh9 (2425 minh hoạ #29, title): các tiêu đề đều chưa hoàn toàn khớp; chọn C (bao quát nhất) – hơi mơ hồ.',
 'dh10 (2425 minh hoạ #35): đề ghi "South America", đã sửa thành "the American South" theo bài; đáp án D.',
 'dh10 (2425 minh hoạ #37 outlawed): made legal (C) và allowed (D) đều trái nghĩa → chấp nhận C, D.',
 'dh10 (2425 minh hoạ #38 EXCEPT): C và D đều không đúng với bài → chấp nhận C, D; B cũng chưa chính xác về trình tự.',
 'vi2 (tn Transformation a #2): nguồn gợi ý bắt đầu bằng "I" nhưng câu gốc nói về "us" → đổi thành "We".',
 'gt1 (2425 Ex3 #28): với "Do you mind if…?" cách đồng ý chuẩn là "Of course not / No, go ahead"; đề không có nên chọn A (Of course you can).']

ANS = {'pa1.1': 'B',
 'pa1.2': 'D',
 'pa1.3': 'D',
 'pa1.4': 'B',
 'pa1.5': 'D',
 'pa1.6': 'B',
 'pa1.7': 'A',
 'pa1.8': 'C',
 'pa1.9': 'B',
 'pa1.10': 'A',
 'pa1.11': 'B',
 'pa1.12': 'B',
 'pa1.13': 'C',
 'pa1.14': 'A',
 'pa1.15': 'D',
 'pa1.16': 'A',
 'pa1.17': 'D',
 'pa1.18': 'A',
 'pa1.19': 'B',
 'pa1.20': 'D',
 'pa1.21': 'D',
 'pa1.22': 'D',
 'pa1.23': 'A',
 'pa2.1': 'A',
 'pa2.2': 'B',
 'pa2.3': 'C',
 'pa2.4': 'D',
 'pa2.5': 'D',
 'pa2.6': 'C',
 'pa2.7': 'A',
 'pa2.8': 'D',
 'pa2.9': 'D',
 'pa2.10': 'C',
 'pa2.11': 'D',
 'pa2.12': 'A',
 'pa2.13': 'A',
 'pa2.14': 'D',
 'pa2.15': 'B',
 'pa2.16': 'C',
 'pa2.17': 'D',
 'pa2.18': 'B',
 'pa2.19': 'D',
 'pa2.20': 'A',
 'pa2.21': 'D',
 'pa2.22': 'C',
 'pa2.23': 'D',
 'pa2.24': 'C',
 'pa2.25': 'C',
 'pa2.26': 'A',
 'tv1.1': 'B',
 'tv1.2': 'B',
 'tv1.3': 'D',
 'tv1.4': 'A',
 'tv1.5': 'D',
 'tv1.6': 'B',
 'tv1.7': 'A',
 'tv1.8': 'A',
 'tv1.9': 'B',
 'tv1.10': 'A',
 'tv1.11': 'A',
 'tv1.12': 'C',
 'tv1.13': 'A',
 'tv1.14': 'B',
 'tv1.15': 'C',
 'tv1.16': 'D',
 'tv1.17': 'D',
 'tv1.18': 'B',
 'tv1.19': 'B',
 'tv1.20': 'C',
 'tv1.21': 'B',
 'tv1.22': 'B',
 'tv1.23': 'D',
 'tv1.24': 'C',
 'tv1.25': 'A',
 'tv1.26': 'D',
 'tv1.27': 'B',
 'tv1.28': 'D',
 'tv1.29': 'A',
 'tv1.30': 'C',
 'tv1.31': 'B',
 'tv1.32': 'A',
 'tv1.33': 'C',
 'tv1.34': 'D',
 'tv1.35': 'C',
 'tv1.36': 'B',
 'tv1.37': 'D',
 'tv1.38': 'A',
 'tv1.39': 'C',
 'tv1.40': 'B',
 'tv1.41': 'C',
 'tv1.42': 'B',
 'tv1.43': 'C',
 'tv1.44': 'C',
 'tv1.45': 'C',
 'tv1.46': 'C',
 'tv1.47': 'B',
 'tv1.48': 'C',
 'tv1.49': 'B',
 'tv1.50': 'C',
 'tv1.51': 'A',
 'tv1.52': 'C',
 'tv1.53': 'C',
 'tv1.54': 'D',
 'tv1.55': 'A',
 'tv1.56': 'B',
 'tv1.57': 'D',
 'tv1.58': 'A',
 'tv1.59': 'C',
 'tv1.60': 'C',
 'tv1.61': 'C',
 'tv1.62': 'B',
 'tv1.63': 'B',
 'tv1.64': 'B',
 'tv1.65': 'B',
 'tv1.66': 'C',
 'tv1.67': 'B',
 'tv1.68': 'A',
 'tv1.69': 'A',
 'tv1.70': 'A',
 'tv1.71': 'B',
 'tv1.72': 'A',
 'tv1.73': 'A',
 'tv1.74': 'B',
 'tv1.75': 'A',
 'tv1.76': 'C',
 'tv1.77': 'D',
 'tv1.78': 'C',
 'tv1.79': 'C',
 'tv1.80': 'C',
 'tv1.81': 'C',
 'tv1.82': 'A',
 'tv1.83': 'D',
 'tv1.84': 'A',
 'tv1.85': 'B',
 'tv2.1': 'B',
 'tv2.2': 'C',
 'tv2.3': 'D',
 'tv2.4': 'C',
 'tv2.5': 'D',
 'tv2.6': 'B',
 'tv2.7': 'B',
 'tv2.8': 'D',
 'tv2.9': 'A',
 'tv2.10': 'A',
 'tv2.11': 'A',
 'tv2.12': 'B',
 'tv2.13': 'D',
 'tv2.14': 'C',
 'tv2.15': 'A',
 'tv3.1': 'B',
 'tv3.2': 'C',
 'tv3.3': ['B', 'D'],
 'tv3.4': 'B',
 'tv3.5': 'D',
 'tv3.6': 'D',
 'tv3.7': 'B',
 'tv3.8': 'C',
 'tv3.9': 'C',
 'tv3.10': 'D',
 'tv3.11': 'B',
 'tv3.12': 'C',
 'tv3.13': 'B',
 'tv4.1': ['individuality', 'individualism'],
 'tv4.2': ['renewable'],
 'tv4.3': ['digital'],
 'tv4.4': ['generations'],
 'tv4.5': ['conservative'],
 'tv4.6': ['unhealthy'],
 'tv4.7': ['expectancy'],
 'tv4.8': ['infection', 'infections'],
 'tv4.9': ['beautiful', 'beautifully'],
 'tv4.10': ['success'],
 'ng1.1': 'C',
 'ng1.2': 'B',
 'ng1.3': 'C',
 'ng1.4': 'C',
 'ng1.5': 'C',
 'ng1.6': 'B',
 'ng1.7': 'B',
 'ng1.8': 'A',
 'ng2.1': 'A',
 'ng2.2': 'B',
 'ng2.3': ['C', 'D'],
 'ng2.4': 'B',
 'ng2.5': ['B', 'D'],
 'ng2.6': 'B',
 'ng2.7': ['B', 'C'],
 'ng2.8': 'B',
 'ng2.9': 'C',
 'ng2.10': 'C',
 'ng2.11': 'B',
 'ng3.1': 'A',
 'ng3.2': 'A',
 'ng3.3': 'C',
 'ng3.4': 'C',
 'ng3.5': 'A',
 'ng3.6': 'B',
 'ng3.7': 'A',
 'ng3.8': 'B',
 'ng3.9': 'B',
 'ng3.10': 'A',
 'ng3.11': 'C',
 'ng3.12': 'C',
 'ng3.13': 'A',
 'ng3.14': 'A',
 'ng3.15': 'B',
 'ng3.16': 'C',
 'ng4.1': ['looks', 'looked'],
 'ng4.2': ['become'],
 'ng4.3': ['grow'],
 'ng4.4': ['is getting', "'s getting"],
 'ng4.5': ['appearing', 'appeared'],
 'ng4.6': ['is thinking'],
 'ng4.7': {'blanks': [['are'], ['smelling']]},
 'ng4.8': ['lost'],
 'ng4.9': ['has just taken', 'has taken', "'s just taken"],
 'ng4.10': ['participants'],
 'ng4.11': ['bought'],
 'ng4.12': ['have been', "'ve been"],
 'ng4.13': ['have known'],
 'er1.1': 'A',
 'er1.2': 'A',
 'er1.3': 'C',
 'er1.4': 'A',
 'er1.5': 'D',
 'er1.6': 'C',
 'er1.7': 'C',
 'er1.8': 'D',
 'er1.9': 'A',
 'er1.10': 'C',
 'er1.11': 'C',
 'er1.12': 'A',
 'er1.13': 'B',
 'er1.14': 'B',
 'er1.15': 'B',
 'er1.16': 'B',
 'er1.17': 'A',
 'er1.18': 'C',
 'er1.19': 'C',
 'er1.20': 'A',
 'er1.21': 'A',
 'er1.22': 'C',
 'er1.23': 'B',
 'er1.24': 'A',
 'er1.25': 'C',
 'er1.26': 'B',
 'er1.27': 'A',
 'er1.28': 'A',
 'er1.29': 'A',
 'er1.30': 'A',
 'dt1.1': 'A',
 'dt1.2': 'B',
 'dt1.3': 'D',
 'dt1.4': 'C',
 'dt1.5': 'A',
 'dt2.1': 'A',
 'dt2.2': 'C',
 'dt2.3': 'B',
 'dt2.4': 'A',
 'dt2.5': 'D',
 'dt3.1': 'C',
 'dt3.2': 'B',
 'dt3.3': 'C',
 'dt3.4': 'A',
 'dt3.5': 'A',
 'dt4.1': 'C',
 'dt4.2': 'B',
 'dt4.3': 'B',
 'dt4.4': 'D',
 'dt4.5': 'B',
 'dt5.1': 'D',
 'dt5.2': 'A',
 'dt5.3': 'C',
 'dt5.4': 'B',
 'dt5.5': 'A',
 'dt6.1': 'B',
 'dt6.2': 'A',
 'dt6.3': 'D',
 'dt6.4': 'B',
 'dt6.5': 'C',
 'dt7.1': ['A', 'B'],
 'dt7.2': 'C',
 'dt7.3': 'B',
 'dt7.4': 'D',
 'dt7.5': 'C',
 'dt8.1': 'C',
 'dt8.2': 'D',
 'dt8.3': ['A', 'C'],
 'dt9.1': 'A',
 'dt9.2': 'B',
 'dt9.3': 'C',
 'dt10.1': 'B',
 'dt10.2': 'A',
 'dt10.3': 'A',
 'dt11.1': 'A',
 'dt11.2': 'A',
 'dt11.3': 'A',
 'dt12.1': 'A',
 'dt12.2': 'B',
 'dt12.3': 'B',
 'dt12.4': 'D',
 'dt12.5': ['C', 'D'],
 'dt13.1': 'A',
 'dt13.2': 'B',
 'dt13.3': 'D',
 'dh1.1': 'D',
 'dh1.2': 'B',
 'dh1.3': 'C',
 'dh1.4': 'C',
 'dh1.5': 'A',
 'dh2.1': 'D',
 'dh2.2': 'C',
 'dh2.3': 'A',
 'dh2.4': 'A',
 'dh2.5': 'B',
 'dh3.1': 'A',
 'dh3.2': 'A',
 'dh3.3': 'C',
 'dh3.4': 'B',
 'dh3.5': 'D',
 'dh4.1': 'C',
 'dh4.2': 'A',
 'dh4.3': 'A',
 'dh4.4': 'D',
 'dh4.5': 'B',
 'dh5.1': 'B',
 'dh5.2': 'A',
 'dh5.3': 'D',
 'dh5.4': 'C',
 'dh5.5': 'C',
 'dh6.1': 'C',
 'dh6.2': 'C',
 'dh6.3': 'D',
 'dh6.4': 'B',
 'dh6.5': 'A',
 'dh7.1': 'A',
 'dh7.2': 'C',
 'dh7.3': 'B',
 'dh7.4': 'D',
 'dh7.5': 'B',
 'dh8.1': 'A',
 'dh8.2': 'D',
 'dh8.3': 'C',
 'dh8.4': 'B',
 'dh8.5': 'D',
 'dh8.6': 'C',
 'dh9.1': 'C',
 'dh9.2': 'B',
 'dh9.3': 'A',
 'dh9.4': 'C',
 'dh9.5': 'B',
 'dh10.1': 'A',
 'dh10.2': 'D',
 'dh10.3': 'B',
 'dh10.4': ['C', 'D'],
 'dh10.5': ['C', 'D'],
 'dh10.6': 'A',
 'dh10.7': 'A',
 'vi1.1': ['I met her was three years ago', 'I met her was 3 years ago'],
 'vi1.2': ['I saw her was in 2000', 'I saw her was 2000'],
 'vi1.3': ['have never attended such an enjoyable wedding party before',
           'have not attended such an enjoyable wedding party before',
           "haven't attended such an enjoyable wedding party before",
           'had never attended such an enjoyable wedding party before'],
 'vi1.4': ['have never been abroad before', 'have not been abroad before', "haven't been abroad before"],
 'vi1.5': ['my student has come to such a big city as Seoul',
           'my student has been to such a big city as Seoul',
           'my student has come to a big city like Seoul'],
 'vi1.6': ['her children have joined such an attractive party',
           'her children have joined such an attractive party like that',
           'her children have joined an attractive party like that'],
 'vi1.7': ['has never been abroad before', 'has not been abroad before', "hasn't been abroad before", 'has never gone abroad before'],
 'vi1.8': ['has learnt driving for 1 month',
           'has learned driving for 1 month',
           'has been learning driving for 1 month',
           'has learnt to drive for a month',
           'has learned to drive for one month',
           'has been learning to drive for 1 month'],
 'vi1.9': ['have been eating since it started to rain', 'have eaten since it started to rain', 'have been eating since it began to rain'],
 'vi1.10': ['had my hair cut since I left her', 'had my hair cut since i left her'],
 'vi1.11': ['have not met for a long time',
            "haven't met for a long time",
            "haven't seen each other for a long time",
            'have not seen each other for a long time'],
 'vi1.12': ['years since i last cheated in an exam',
            'years since i cheated in an exam',
            'years since i last cheated in exam',
            'years since i cheated in exam',
            'years since i last cheated in exams'],
 'vi1.13': ['did she start living in danang',
            'did she begin living in danang',
            'did she move to danang',
            'did she start to live in danang',
            'did she begin to live in danang',
            'did she come to danang'],
 'vi1.14': ['smoked 2 years ago', 'smoked two years ago'],
 'vi1.15': ['started learning french 3 years ago',
            'began learning french 3 years ago',
            'started to learn french 3 years ago',
            'began to learn french 3 years ago',
            'started learning french three years ago',
            'began learning french three years ago',
            'started to learn french three years ago',
            'began to learn french three years ago'],
 'vi1.16': ['i met her was 5 days ago', 'i met her was five days ago'],
 'vi1.17': ['worked at this office for 5 years',
            'worked at this office for five years',
            'been working at this office for 5 years',
            'been working at this office for five years'],
 'vi1.18': ['not had a business meeting with him since february', "haven't had a business meeting with him since february"],
 'vi1.19': ['not seen her for 2 years', 'not seen her for two years', 'never seen her for 2 years'],
 'vi1.20': ['time i heard from him was in august', 'time i heard him was in august', 'time i heard of him was in august', 'time i heard from him was august'],
 'vi2.1': ['should spend more time talking with your children', 'should spend more time talking to your children'],
 'vi2.2': ['should write to him'],
 'vi2.3': ["mustn't use that computer", 'must not use that computer'],
 'vi2.4': ["mustn't go out at night", 'must not go out at night'],
 'vi2.5': ["mustn't smoke or eat in the office",
           'must not smoke or eat in the office',
           "can't smoke or eat in the office",
           'cannot smoke or eat in the office'],
 'vi2.6': ["mustn't take photographs in the museum",
           'must not take photographs in the museum',
           "can't take photographs in the museum",
           'cannot take photographs in the museum',
           "mustn't take photos in the museum"],
 'vi2.7': ["doesn't have to call ben today", "needn't call ben today", 'need not call ben today', 'does not have to call ben today'],
 'vi2.8': ["doesn't have to water these flowers", "needn't water these flowers", 'need not water these flowers', 'does not have to water these flowers'],
 'vi2.9': ['use his smartphone during the lesson', 'use his smartphone in the lesson'],
 'vi2.10': ['check their luggage before leaving the airport'],
 'vi2.11': ['should tell the truth to your family', 'ought to tell the truth to your family'],
 'vi2.12': ["don't have to wear uniforms every day",
            "needn't wear uniforms every day",
            'do not have to wear uniforms every day',
            'need not wear uniforms every day'],
 'vi2.13': ["mustn't drive without wearing a helmet",
            'must not drive without wearing a helmet',
            "can't drive without wearing a helmet",
            'cannot drive without wearing a helmet'],
 'vi2.14': ['must plan their future career carefully',
            'have to plan their future career carefully',
            'need to plan their future career carefully',
            'should plan their future career carefully'],
 'vi2.15': ['must do well at school', 'have to do well at school', 'should do well at school', 'need to do well at school'],
 'vi2.16': ['should share the housework with your mother', 'ought to share the housework with your mother'],
 'vi2.17': ["mustn't cheat in the exam",
            'must not cheat in the exam',
            "aren't allowed to cheat in the exam",
            'are not allowed to cheat in the exam',
            "can't cheat in the exam",
            'cannot cheat in the exam'],
 'vi2.18': ["needn't clean the flat", 'need not clean the flat', "doesn't need to clean the flat", 'does not need to clean the flat'],
 'vi2.19': ['must have been surprised when you heard all the news', 'must have been surprised when you heard the news'],
 'vi2.20': ['him to leave after they had questioned him'],
 'gt1.1': 'A',
 'kt.1': 'B',
 'kt.2': 'A',
 'kt.3': 'A',
 'kt.4': 'A',
 'kt.5': 'A',
 'kt.6': 'B',
 'kt.7': 'B',
 'kt.8': 'C',
 'kt.9': 'B',
 'kt.10': 'C',
 'kt.11': 'C',
 'kt.12': 'B',
 'kt.13': 'B',
 'kt.14': 'D',
 'kt.15': 'B',
 'kt.16': 'C',
 'kt.17': 'B',
 'kt.18': 'B',
 'kt.19': 'B',
 'kt.20': 'C',
 'kt.21': 'A',
 'kt.22': 'A',
 'kt.23': 'B',
 'kt.24': 'C',
 'kt.25': 'B',
 'kt.26': 'A',
 'kt.27': 'C',
 'kt.28': 'B',
 'kt.29': 'C',
 'kt.30': 'A',
 'kt.31': 'D',
 'kt.32': 'A',
 'kt.33': 'C',
 'kt.34': 'B',
 'kt.35': 'A',
 'kt.36': 'A',
 'kt.37': 'C',
 'kt.38': 'B',
 'kt.39': 'D',
 'kt.40': 'B'}

EXPLANATIONS = {'pa1.1': 'sure /ʃʊə/, sugar /ˈʃʊɡə/, machine /məˈʃiːn/ → đều /ʃ/; soup /suːp/ → /s/. Chọn <b>soup</b>.',
 'pa1.2': 'study /ˈstʌdi/, ready /ˈredi/, puppy /ˈpʌpi/ → -y đọc /i/; occupy /ˈɒkjupaɪ/ → -y đọc /aɪ/. Chọn <b>occupy</b>.',
 'pa1.3': 'maintain /meɪnˈteɪn/, game /ɡeɪm/, integrate /ˈɪntɪɡreɪt/ → /eɪ/; tradition /trəˈdɪʃn/ → /ə/. Chọn <b>tradition</b>.',
 'pa1.4': 'follow /ˈfɒləʊ/ (o đầu), problem /ˈprɒbləm/, confident /ˈkɒnfɪdənt/ → /ɒ/; romantic /rəʊˈmæntɪk/ → /əʊ/. Chọn <b>romantic</b>.',
 'pa1.5': 'casual /ˈkæʒuəl/, flashy /ˈflæʃi/, attitude /ˈætɪtjuːd/ → /æ/; table /ˈteɪbl/ → /eɪ/. Chọn <b>table</b>.',
 'pa1.6': 'amazing /əˈmeɪzɪŋ/, female /ˈfiːmeɪl/, taste /teɪst/ → /eɪ/; charge /tʃɑːdʒ/ → /ɑː/. Chọn <b>charge</b>.',
 'pa1.7': 'belief /bɪˈliːf/ → /ɪ/; generation /ˌdʒenəˈreɪʃn/, extended /ɪkˈstendɪd/, elegant /ˈelɪɡənt/ → /e/. Chọn <b>belief</b>.',
 'pa1.8': 'achievement /əˈtʃiːvmənt/, appearance /əˈpɪərəns/, initiative /ɪˈnɪʃətɪv/ → /ə/; enthusiastic /ɪnˌθjuːziˈæstɪk/ → /æ/. Chọn <b>enthusiastic</b>.',
 'pa1.9': 'fresh /freʃ/, flesh /fleʃ/, exercise /ˈeksəsaɪz/ → /e/; diet /ˈdaɪət/ → /aɪə/. Chọn <b>diet</b>.',
 'pa1.10': 'yoga /ˈjəʊɡə/ → /ə/; fatty /ˈfæti/, balance /ˈbæləns/, habit /ˈhæbɪt/ → /æ/. Chọn <b>yoga</b>.',
 'pa1.11': 'ingredient /ɪnˈɡriːdiənt/, vitamin /ˈvɪtəmɪn/, mineral /ˈmɪnərəl/ → /ɪ/; nutrient /ˈnjuːtriənt/ → i đọc /i/ (nutri-ent). Chọn <b>nutrient</b>.',
 'pa1.12': 'gap, grandparent, great → /ɡ/; generation /ˌdʒenəˈreɪʃn/ → /dʒ/. Chọn <b>generation</b>.',
 'pa1.13': 'hold /həʊld/, follow /ˈfɒləʊ/ (o cuối), notice /ˈnəʊtɪs/ → /əʊ/; force /fɔːs/ → /ɔː/. Chọn <b>force</b>.',
 'pa1.14': 'footstep /ˈfʊtstep/ → /ʊ/; roof /ruːf/, food /fuːd/, fool /fuːl/ → /uː/. Chọn <b>footstep</b>.',
 'pa1.15': 'believe /bɪˈliːv/, extend /ɪkˈstend/, respect /rɪˈspekt/ → /ɪ/; gender /ˈdʒendə/ → /e/. Chọn <b>gender</b>.',
 'pa1.16': 'special /ˈspeʃl/ → c đọc /ʃ/; common, consist, conflict → c đọc /k/. Chọn <b>special</b>.',
 'pa1.17': 'dweller /ˈdwelə/, sensor /ˈsensə/, energy /ˈenədʒi/ → /e/; reduce /rɪˈdjuːs/ → /ɪ/. Chọn <b>reduce</b>.',
 'pa1.18': 'design /dɪˈzaɪn/ → i đọc /aɪ/; impact /ˈɪmpækt/, public /ˈpʌblɪk/, traffic /ˈtræfɪk/ → /ɪ/. Chọn <b>design</b>.',
 'pa1.19': 'healthy /ˈhelθi/, strength /streŋθ/, mental /ˈmentl/ → /e/; fitness /ˈfɪtnəs/ → /ɪ/ (hoặc /ə/). Chọn <b>fitness</b>.',
 'pa1.20': 'health /helθ/, enthusiasm /ɪnˈθjuːziæzəm/, strength /streŋθ/ → /θ/; without /wɪˈðaʊt/ → /ð/. Chọn <b>without</b>.',
 'pa1.21': 'gap /ɡæp/, application /ˌæplɪˈkeɪʃn/, value /ˈvæljuː/ → /æ/; behavior /bɪˈheɪvjə/ → /eɪ/. Chọn <b>behavior</b>.',
 'pa1.22': 'extend /ɪkˈstend/, between /bɪˈtwiːn/, believe /bɪˈliːv/ → /ɪ/; member /ˈmembə/ → /e/. Chọn <b>member</b>.',
 'pa1.23': 'accept /əkˈsept/ → cc đọc /ks/; nuclear /ˈnjuːkliə/, discuss /dɪˈskʌs/, include /ɪnˈkluːd/ → c đọc /k/. Chọn <b>accept</b>.',
 'pa2.1': 'prevent /prɪˈvent/ nhấn âm 2; injure /ˈɪndʒə/, balance /ˈbæləns/, suffer /ˈsʌfə/ nhấn âm 1. Chọn <b>prevent</b>.',
 'pa2.2': 'disease /dɪˈziːz/ nhấn âm 2; fitness /ˈfɪtnəs/, treatment /ˈtriːtmənt/, headache /ˈhedeɪk/ nhấn âm 1. Chọn <b>disease</b>.',
 'pa2.3': 'immune /ɪˈmjuːn/ nhấn âm 2; longer, fatal /ˈfeɪtl/, careful /ˈkeəfl/ nhấn âm 1. Chọn <b>immune</b>.',
 'pa2.4': 'infectious /ɪnˈfekʃəs/, essential /ɪˈsenʃl/, resistant /rɪˈzɪstənt/ nhấn âm 2; properly /ˈprɒpəli/ nhấn âm 1. Chọn <b>properly</b>.',
 'pa2.5': 'infection /ɪnˈfekʃn/ nhấn âm 2; nutrient /ˈnjuːtriənt/, vitamin /ˈvɪtəmɪn/, mineral /ˈmɪnərəl/ nhấn âm 1. Chọn <b>infection</b>.',
 'pa2.6': 'expression /ɪkˈspreʃn/, example /ɪɡˈzɑːmpl/, superior /suːˈpɪəriə/ nhấn âm 2; friendliness /ˈfrendlinəs/ nhấn âm 1. Chọn <b>friendliness</b>.',
 'pa2.7': 'value /ˈvæljuː/ nhấn âm 1; afford /əˈfɔːd/, depend /dɪˈpend/, impose /ɪmˈpəʊz/ nhấn âm 2. Chọn <b>value</b>.',
 'pa2.8': 'influence /ˈɪnfluəns/, attitude /ˈætɪtjuːd/, counselor /ˈkaʊnsələ/ nhấn âm 1; decision /dɪˈsɪʒn/ nhấn âm 2. Chọn <b>decision</b>.',
 'pa2.9': 'donate /dəʊˈneɪt/, compare /kəmˈpeə/, campaign /kæmˈpeɪn/ nhấn âm 2; limit /ˈlɪmɪt/ nhấn âm 1. Chọn <b>limit</b>.',
 'pa2.10': 'experience /ɪkˈspɪəriəns/, mobility /məʊˈbɪləti/, priorities /praɪˈɒrətiz/ nhấn âm 2; independence /ˌɪndɪˈpendəns/ nhấn âm 3. Chọn '
           '<b>independence</b>.',
 'pa2.11': 'romantic /rəʊˈmæntɪk/, infectious /ɪnˈfekʃəs/, protective /prəˈtektɪv/ nhấn âm 2; elegant /ˈelɪɡənt/ nhấn âm 1. Chọn <b>elegant</b>.',
 'pa2.12': 'limit /ˈlɪmɪt/ nhấn âm 1; obey /əˈbeɪ/, forbid /fəˈbɪd/, impose /ɪmˈpəʊz/ nhấn âm 2. Chọn <b>limit</b>.',
 'pa2.13': 'design /dɪˈzaɪn/ nhấn âm 2; model /ˈmɒdl/, future /ˈfjuːtʃə/, question /ˈkwestʃən/ nhấn âm 1. Chọn <b>design</b>.',
 'pa2.14': 'impress /ɪmˈpres/, install /ɪnˈstɔːl/, begin /bɪˈɡɪn/ nhấn âm 2; sensor /ˈsensə/ nhấn âm 1. Chọn <b>sensor</b>.',
 'pa2.15': 'solution /səˈluːʃn/, effective /ɪˈfektɪv/, electric /ɪˈlektrɪk/ nhấn âm 2; camera /ˈkæmərə/ nhấn âm 1. Chọn <b>camera</b>.',
 'pa2.16': 'negative /ˈneɡətɪv/, vehicle /ˈviːəkl/, operate /ˈɒpəreɪt/ nhấn âm 1; pollution /pəˈluːʃn/ nhấn âm 2. Chọn <b>pollution</b>.',
 'pa2.17': 'efficiently /ɪˈfɪʃntli/, sustainable /səˈsteɪnəbl/, pedestrian /pəˈdestriən/ nhấn âm 2; vegetable /ˈvedʒtəbl/ nhấn âm 1. Chọn <b>vegetable</b>.',
 'pa2.18': 'activity /ækˈtɪvəti/, technology /tekˈnɒlədʒi/, convenient /kənˈviːniənt/ nhấn âm 2; information /ˌɪnfəˈmeɪʃn/ nhấn âm 3. Chọn <b>information</b>.',
 'pa2.19': 'follow /ˈfɒləʊ/, gender /ˈdʒendə/, footstep /ˈfʊtstep/ nhấn âm 1; belief /bɪˈliːf/ nhấn âm 2. Chọn <b>belief</b>.',
 'pa2.20': 'behave /bɪˈheɪv/ nhấn âm 2; differ /ˈdɪfə/, argue /ˈɑːɡjuː/, follow /ˈfɒləʊ/ nhấn âm 1. Chọn <b>behave</b>.',
 'pa2.21': 'amount /əˈmaʊnt/ nhấn âm 2; healthy /ˈhelθi/, problem /ˈprɒbləm/, mental /ˈmentl/ nhấn âm 1. Chọn <b>amount</b>.',
 'pa2.22': 'complain /kəmˈpleɪn/ nhấn âm 2; lifestyle /ˈlaɪfstaɪl/, frequent /ˈfriːkwənt/, balance /ˈbæləns/ nhấn âm 1. Chọn <b>complain</b>.',
 'pa2.23': 'technology /tekˈnɒlədʒi/, environment /ɪnˈvaɪrənmənt/, economy /ɪˈkɒnəmi/ nhấn âm 2; architecture /ˈɑːkɪtektʃə/ nhấn âm 1. Chọn '
           '<b>architecture</b>.',
 'pa2.24': 'population /ˌpɒpjuˈleɪʃn/, operation /ˌɒpəˈreɪʃn/, exhibition /ˌeksɪˈbɪʃn/ nhấn âm 3 (trước -tion); infrastructure /ˈɪnfrəstrʌktʃə/ nhấn âm 1. '
           'Chọn <b>infrastructure</b>.',
 'pa2.25': 'device /dɪˈvaɪs/, complain /kəmˈpleɪn/, allow /əˈlaʊ/ nhấn âm 2; limit /ˈlɪmɪt/ nhấn âm 1. Chọn <b>limit</b>.',
 'pa2.26': 'teenager /ˈtiːneɪdʒə/ nhấn âm 1; computer /kəmˈpjuːtə/, conclusion /kənˈkluːʒn/, supporting /səˈpɔːtɪŋ/ nhấn âm 2. Chọn <b>teenager</b>.',
 'tv1.1': 'conservative (bảo thủ) → ông không bao giờ <b>change his mind</b> (thay đổi ý kiến) về lối sống. Các phương án còn lại không hợp nghĩa "bảo thủ".',
 'tv1.2': '<b>cope with</b> = đối phó/vượt qua. "deal" phải đi với "with" (deal with); set up = thành lập; look after = chăm sóc.',
 'tv1.3': '<b>self-reliant</b> = tự lực, không dựa dẫm. reliable = đáng tin cậy; protective = hay bảo vệ; humanitarian = nhân đạo.',
 'tv1.4': '<b>decisive</b> = quyết đoán (đưa ra quyết định nhanh, tự tin).',
 'tv1.5': '<b>turn into</b> = biến thành. bring about = gây ra; put up = dựng lên; take over = tiếp quản.',
 'tv1.6': '<b>counselor</b> = chuyên viên tư vấn → đi gặp để xin lời khuyên.',
 'tv1.7': 'Sau động từ "live" cần trạng từ: <b>independently</b> (một cách độc lập).',
 'tv1.8': "Thành ngữ <b>follow in someone's footsteps</b> = nối nghiệp, theo bước chân ai.",
 'tv1.9': '<b>dating services</b> = dịch vụ hẹn hò (danh từ ghép: V-ing + N).',
 'tv1.10': 'Sống chung nhiều thế hệ thường có <b>generation gap</b> (khoảng cách thế hệ).',
 'tv1.11': '<b>be reconciled with</b> = làm lành/hòa giải với nhau.',
 'tv1.12': 'Thành ngữ <b>lend a sympathetic ear</b> = lắng nghe một cách thông cảm.',
 'tv1.13': 'Kết bạn dễ dàng → kỹ năng <b>giao tiếp liên cá nhân</b> (interpersonal communication).',
 'tv1.14': '<b>Single-sex education</b> = giáo dục đơn giới (chỉ nam hoặc chỉ nữ).',
 'tv1.15': '<b>concentrate on</b> = tập trung vào. depend on / insist on có nghĩa khác.',
 'tv1.16': '<b>interact with</b> = tương tác với bạn bè đồng trang lứa (peers).',
 'tv1.17': '<b>work out</b> = tập thể dục.',
 'tv1.18': '<b>be good for</b> = tốt cho.',
 'tv1.19': '<b>suffer from</b> = chịu đựng/bị (bệnh, chấn thương).',
 'tv1.20': 'Trước danh từ "diseases" cần tính từ: <b>infectious diseases</b> (bệnh truyền nhiễm).',
 'tv1.21': 'Cần tính từ bổ nghĩa cho "changes": <b>dietary changes</b> (thay đổi trong chế độ ăn).',
 'tv1.22': 'Tính từ đứng trước danh từ: <b>different viruses</b>.',
 'tv1.23': '<b>prevent the spread of diseases</b> = ngăn chặn sự lây lan của bệnh.',
 'tv1.24': 'Vật nhỏ cỡ 0,4 micron là <b>bacteria</b> (vi khuẩn).',
 'tv1.25': 'Vitamins và minerals là các <b>nutrients</b> (chất dinh dưỡng).',
 'tv1.26': '<b>give off</b> = phát ra (ánh sáng, mùi, nhiệt). give out = phân phát; give in = nhượng bộ.',
 'tv1.27': 'Nhiều thế hệ sống chung = <b>extended family</b> (gia đình nhiều thế hệ).',
 'tv1.28': '<b>work out</b> = tập luyện. run out = hết; work on = nỗ lực làm.',
 'tv1.29': '<b>concentrate on</b> + V-ing.',
 'tv1.30': 'Sau tính từ "aggressive" cần danh từ: <b>aggressive behaviour</b> (hành vi hung hăng).',
 'tv1.31': 'Tính từ bổ nghĩa cho "views": <b>traditional views</b> (quan điểm truyền thống).',
 'tv1.32': '<b>complain about</b> = phàn nàn về.',
 'tv1.33': '<b>rely on</b> = dựa vào.',
 'tv1.34': 'Sau "His" cần danh từ: <b>belief</b> (niềm tin).',
 'tv1.35': '<b>follow advice</b> = nghe theo lời khuyên.',
 'tv1.36': '<b>extended families</b> = gia đình nhiều thế hệ.',
 'tv1.37': '<b>different viewpoints of lifestyle</b> = những quan điểm khác nhau về lối sống.',
 'tv1.38': "<b>follow in someone's footsteps</b> = nối nghiệp ai.",
 'tv1.39': 'Luôn nghĩ ra ý tưởng mới → <b>creative</b> (sáng tạo).',
 'tv1.40': '<b>traditional views</b> = quan điểm truyền thống về cách sống.',
 'tv1.41': 'Những thứ được truyền lại qua các thế hệ → <b>cultural values</b> (giá trị văn hoá).',
 'tv1.42': 'Sau "will be" cần tính từ: <b>sustainable</b> (bền vững).',
 'tv1.43': 'Bổ nghĩa cho động từ "operate" cần trạng từ: <b>effectively</b>.',
 'tv1.44': 'Song song với danh từ "traffic jams" → danh từ <b>pollution</b>.',
 'tv1.45': '<b>greenhouse gas emissions</b> = khí thải nhà kính.',
 'tv1.46': '<b>be made up of</b> = được tạo thành từ.',
 'tv1.47': '<b>a solution to</b> + vấn đề.',
 'tv1.48': '<b>city dwellers</b> = người dân thành phố (từ vựng Unit 3). "commuters" cũng có thể chấp nhận.',
 'tv1.49': '<b>get round</b> = đi lại, di chuyển quanh thành phố.',
 'tv1.50': '<b>pour into</b> = đổ xô vào (số lượng lớn).',
 'tv1.51': '<b>go into</b> = đi sâu vào, bàn kỹ về.',
 'tv1.52': '<b>infrastructure</b> = cơ sở hạ tầng.',
 'tv1.53': '<b>renewable energy</b> = năng lượng tái tạo.',
 'tv1.54': '<b>life expectancy</b> = tuổi thọ trung bình.',
 'tv1.55': '<b>balanced diet</b> = chế độ ăn cân bằng (hợp với "healthy life").',
 'tv1.56': '<b>stretch your muscles</b> = giãn cơ.',
 'tv1.57': '<b>work out</b> = tập thể dục.',
 'tv1.58': '<b>eco-friendly</b> = thân thiện với môi trường (tính từ sau "more").',
 'tv1.59': '<b>livable</b> = đáng sống.',
 'tv1.60': '<b>treatment of cancer</b> = điều trị ung thư. (Phương án "for" không có trong đề; "of" là đáp án phù hợp nhất.)',
 'tv1.61': '<b>city dwellers</b> = cư dân thành phố (collocation cố định). citizens cũng gặp nhưng "city dwellers" là từ Unit 3.',
 'tv1.62': '<b>impose something on someone</b> = áp đặt cho ai.',
 'tv1.63': 'Bổ nghĩa cho động từ "exercise" cần trạng từ <b>regularly</b> (tập luyện đều đặn).',
 'tv1.64': '<b>conflict</b> = mâu thuẫn, xung đột (do bất đồng).',
 'tv1.65': '<b>current fashion trend</b> = xu hướng thời trang hiện nay.',
 'tv1.66': '<b>obey the rules</b> = tuân thủ luật. "conform" cần giới từ "to".',
 'tv1.67': '<b>judge someone by their appearance</b> = đánh giá ai qua vẻ bề ngoài.',
 'tv1.68': '<b>the norm</b> = chuẩn mực, điều phổ biến.',
 'tv1.69': 'Cha mẹ cho rằng không hợp lứa tuổi → váy <b>tight</b> (bó sát) là hợp lý nhất.',
 'tv1.70': '<b>flashy</b> = loè loẹt, quá sặc sỡ.',
 'tv1.71': '<b>alternative sources of energy</b> = nguồn năng lượng thay thế.',
 'tv1.72': '<b>city dwellers</b> = cư dân thành phố ("inhabitants" thường dùng với "of + địa danh").',
 'tv1.73': 'Cụm cố định: <b>On the contrary</b> = trái lại (phủ nhận ý câu trước).',
 'tv1.74': '<b>become home to</b> = trở thành nơi sinh sống của.',
 'tv1.75': 'Sau "Constant" cần danh từ: <b>threat of attack</b> = nguy cơ bị tấn công.',
 'tv1.76': '<b>a balanced diet</b> = chế độ ăn cân bằng.',
 'tv1.77': '<b>suffer from</b> + bệnh.',
 'tv1.78': '<b>lead a healthier lifestyle</b> = sống lành mạnh hơn.',
 'tv1.79': '"more ... diseases" so với cảm lạnh → bệnh <b>serious</b> (nghiêm trọng) hơn.',
 'tv1.80': '<b>home remedy</b> = bài thuốc/phương pháp chữa tại nhà.',
 'tv1.81': '<b>food poisoning</b> = ngộ độc thực phẩm.',
 'tv1.82': '<b>argue over</b> = tranh cãi về → phản ánh khác biệt quan điểm. bond over = gắn kết nhờ.',
 'tv1.83': '3 thế hệ sống chung = <b>extended family</b>.',
 'tv1.84': '<b>exhaust fumes</b> = khí thải/khói xả của xe.',
 'tv1.85': 'Sẵn sàng nghe ý tưởng mới → <b>open-minded</b> (cởi mở).',
 'tv2.1': '<b>oppose</b> = phản đối ≈ <b>forbid</b> (cấm đoán). assist = giúp; ignore = phớt lờ; preserve = bảo tồn.',
 'tv2.2': '<b>assignments</b> = bài tập/nhiệm vụ được giao ≈ <b>exercises</b>.',
 'tv2.3': '<b>reliable</b> = đáng tin cậy ≈ <b>dependable</b>.',
 'tv2.4': '<b>self-respect</b> = lòng tự trọng ≈ <b>self-esteem</b>.',
 'tv2.5': '<b>exercise</b> = tập thể dục ≈ <b>work out</b>.',
 'tv2.6': '<b>life expectancy</b> = tuổi thọ ≈ <b>longevity</b>.',
 'tv2.7': '<b>obesity</b> = béo phì ≈ <b>being overweight</b>.',
 'tv2.8': '<b>force</b> = ép buộc ≈ <b>oblige</b> (bắt buộc).',
 'tv2.9': '<b>experience</b> = trải qua ≈ <b>go through</b>.',
 'tv2.10': '<b>hire</b> = thuê ≈ <b>employ</b>.',
 'tv2.11': '<b>renewable</b> = tái tạo được ≈ <b>inexhaustible</b> (không bao giờ cạn).',
 'tv2.12': '<b>generate</b> = tạo ra ≈ <b>produce</b>.',
 'tv2.13': '<b>be involved in</b> = tham gia ≈ <b>be engaged in</b>.',
 'tv2.14': '<b>boost</b> = tăng cường ≈ <b>increase</b>.',
 'tv2.15': '<b>step by step</b> = từng bước ≈ <b>gradually</b> (dần dần).',
 'tv3.1': '<b>dependent on</b> (phụ thuộc vào) ↔ <b>self-reliant</b> (tự lực).',
 'tv3.2': '<b>depressed</b> (chán nản) ↔ <b>satisfied</b> (hài lòng).',
 'tv3.3': '<b>well-informed</b> (am hiểu) ↔ <b>ill-informed / badly-informed</b> (thiếu hiểu biết). "bad-informed" sai ngữ pháp.',
 'tv3.4': '<b>conflict</b> (xung đột) ↔ <b>harmony</b> (hòa thuận).',
 'tv3.5': '<b>lose weight</b> ↔ <b>gain weight</b> (tăng cân).',
 'tv3.6': '<b>stretch</b> (giãn ra) ↔ <b>shrink</b> (co lại).',
 'tv3.7': '<b>cause</b> (gây ra) ↔ <b>result from</b> (là do/kết quả của). result in và lead to đồng nghĩa với cause.',
 'tv3.8': '<b>extended family</b> (gia đình nhiều thế hệ) ↔ <b>nuclear family</b> (gia đình hạt nhân: bố mẹ và con).',
 'tv3.9': '<b>concentrate</b> (tập trung) ↔ <b>neglect</b> (lơ là, không chú ý). focus là đồng nghĩa.',
 'tv3.10': '<b>urban</b> (đô thị) ↔ <b>rural</b> (nông thôn).',
 'tv3.11': '<b>livable</b> (đáng sống) ↔ <b>uninhabitable</b> (không thể sống được).',
 'tv3.12': '<b>neglect</b> (bỏ bê) ↔ <b>focus on</b> (tập trung vào).',
 'tv3.13': '<b>sustainable</b> (bền vững, lâu dài) ↔ <b>short-term</b> (ngắn hạn).',
 'tv4.1': 'Sau động từ "values" cần danh từ: <b>individuality</b> (cá tính, tính cá nhân) – hoặc individualism (chủ nghĩa cá nhân).',
 'tv4.2': 'Tính từ bổ nghĩa cho "energy": <b>renewable</b> (tái tạo).',
 'tv4.3': '<b>digital natives</b> = thế hệ sinh ra trong thời đại số.',
 'tv4.4': 'Sau "three" cần danh từ số nhiều: <b>generations</b> (thế hệ).',
 'tv4.5': 'Sau "are more" cần tính từ: <b>conservative</b> (bảo thủ, thận trọng).',
 'tv4.6': 'Tính từ trước "diet" và trái nghĩa với "good": <b>unhealthy</b> (không lành mạnh).',
 'tv4.7': '<b>life expectancy</b> = tuổi thọ trung bình.',
 'tv4.8': 'Sau động từ "fight" cần danh từ: <b>infection</b> (sự nhiễm trùng).',
 'tv4.9': 'Sau linking verb "looked" cần tính từ: <b>beautiful</b>.',
 'tv4.10': 'Sau giới từ "in" cần danh từ: <b>success</b> (thành công).',
 'ng1.1': 'Mệnh đề sau <b>since</b> chỉ mốc thời gian trong quá khứ ("ten years ago") → dùng quá khứ đơn: <b>left</b>. Cấu trúc: S + have/has + V3 + since + S '
          '+ V2.',
 'ng1.2': 'Có <b>since + mốc quá khứ</b> → hiện tại hoàn thành; chủ ngữ "We" → <b>haven\'t met</b>.',
 'ng1.3': '<b>this month</b> (khoảng thời gian chưa kết thúc) và kết quả ở hiện tại ("feels exhausted") → hiện tại hoàn thành: <b>has stayed</b>.',
 'ng1.4': 'Hành động vừa xong, kết quả còn ở hiện tại ("now she feels exhausted") → <b>has run</b>.',
 'ng1.5': 'Vế trước "since": hiện tại hoàn thành (<b>have lost</b> touch); vế sau "since" có "three years ago" → quá khứ đơn <b>left</b>.',
 'ng1.6': 'Mốc thời gian xác định trong quá khứ (<b>in 1982</b>) → quá khứ đơn: <b>met</b>.',
 'ng1.7': "<b>Since + mệnh đề quá khứ đơn</b> → mệnh đề chính dùng hiện tại hoàn thành: <b>haven't heard</b>.",
 'ng1.8': 'Hai hành động xảy ra song song trong quá khứ; vế "was listening … while" → quá khứ tiếp diễn hoặc quá khứ đơn. Trong các phương án chỉ '
          '<b>played</b> hợp ngữ pháp và nghĩa ("was watching video games" không hợp).',
 'ng2.1': 'Sau <b>must</b> dùng động từ nguyên mẫu không "to": <b>pay</b>.',
 'ng2.2': 'Sau <b>have to</b> dùng động từ nguyên mẫu: <b>show</b>.',
 'ng2.3': "Đồ uống không tốt → lời khuyên/cấm: <b>ought not to</b> hoặc <b>mustn't</b> (không nên/không được). should/ought to khẳng định sai nghĩa.",
 'ng2.4': 'Lời khuyên "I think you …" → <b>should</b>. ought not to / shouldn\'t phủ định sai nghĩa; must quá mạnh.',
 'ng2.5': 'Quy định bắt buộc ("it is a rule") → <b>have to</b> hoặc <b>must</b>.',
 'ng2.6': "Biển cảnh báo → điều bị cấm: <b>mustn't</b>. don't have to = không cần thiết (sai nghĩa).",
 'ng2.7': 'Quy định của trường (bắt buộc) → <b>must</b> hoặc <b>have to</b>. should chỉ là lời khuyên; can = có thể.',
 'ng2.8': "Điều cấm → <b>mustn't</b> (không được). don't have to = không cần.",
 'ng2.9': "Quy chế thi cấm xem tài liệu → <b>mustn't</b> (cấm). don't have to = không cần thiết (sai nghĩa).",
 'ng2.10': 'Lời khuyên chung → <b>should</b> (nên). have to/must quá mạnh; might = có thể.',
 'ng2.11': 'Cấu trúc <b>suggest (that) + S + (should) + V</b> → should be encouraged.',
 'ng3.1': '<b>look</b> là linking verb → theo sau là tính từ (worried). Dùng hiện tại đơn cho trạng thái/ấn tượng nên chọn <b>looks so worried</b>.',
 'ng3.2': 'Câu bị động ("căn phòng được sơn") + <b>since</b> → hiện tại hoàn thành bị động: <b>has been painted</b>.',
 'ng3.3': '<b>seem</b> là linking verb + tính từ; chủ ngữ là sự vật (lifestyle) → tính từ V-ing: <b>exciting</b>.',
 'ng3.4': '<b>look</b> + tính từ; nghĩa "có chuyện gì thế" → <b>unhappy</b>.',
 'ng3.5': 'Lông mèo mềm là điều nhìn/cảm nhận được → <b>looks</b> (sounds/smells/tastes không hợp nghĩa).',
 'ng3.6': 'Cảm giác lạnh trên chân → <b>felt</b> cool (linking verb + tính từ).',
 'ng3.7': '<b>smell</b> là linking verb → tính từ <b>bad</b>; "needs cleaning" bổ nghĩa bằng trạng từ <b>immediately</b>.',
 'ng3.8': '<b>looked</b> + tính từ (angry); "talking … so ___" bổ nghĩa cho động từ talk → trạng từ <b>impolitely</b>.',
 'ng3.9': '<b>smell</b> + tính từ. "Although" chỉ sự tương phản: món ăn thơm (<b>good</b>) nhưng anh vẫn từ chối vì không đói.',
 'ng3.10': '<b>taste</b> + tính từ: <b>awful</b> (kinh khủng).',
 'ng3.11': '<b>look</b> + tính từ; "We must do something" → tình hình xấu → <b>bad</b>.',
 'ng3.12': 'Chỉ cảm xúc của người → tính từ V-ed: <b>disappointed</b>.',
 'ng3.13': '<b>taste</b> (linking verb) + tính từ → <b>good</b>.',
 'ng3.14': '<b>sound</b> là động từ trạng thái, không dùng tiếp diễn; chủ ngữ số ít → <b>sounds</b>.',
 'ng3.15': 'Bị động + "by my aunt" (hành động đã xảy ra): <b>were sewed</b> (chuẩn hơn là were sewn; đề không có phương án này).',
 'ng3.16': 'Quyết định đưa ra ngay tại lúc nói ("I think I … I\'m a little tired") → <b>will stay</b>.',
 'ng4.1': '<b>look</b> là linking verb, chia hiện tại đơn: <b>looks</b> (cũng chấp nhận looked nếu hiểu là câu kể quá khứ).',
 'ng4.2': 'want to + V nguyên mẫu: <b>become</b>.',
 'ng4.3': 'Mệnh đề thời gian với "when" chỉ chân lý chung → hiện tại đơn: they <b>grow</b> older.',
 'ng4.4': 'Diễn tả sự thay đổi đang diễn ra → hiện tại tiếp diễn: <b>is getting</b> hotter and hotter.',
 'ng4.5': 'Chủ ngữ là mệnh đề danh hoá "That + S + V …" hoặc danh động từ; cách dùng thông thường: <b>appearing</b> (Super Junior xuất hiện bất ngờ làm fan '
          'vui sướng).',
 'ng4.6': '<b>think about</b> (cân nhắc, đang nghĩ đến) là hành động → có thể dùng tiếp diễn: <b>is thinking</b>.',
 'ng4.7': '<b>smell</b> (ngửi bằng mũi – hành động chủ động) có thể dùng tiếp diễn: Why <b>are</b> you <b>smelling</b> the flowers?',
 'ng4.8': 'Mốc quá khứ xác định (<b>last night</b>) → quá khứ đơn: <b>lost</b>.',
 'ng4.9': 'Hành động vừa xảy ra, kết quả ở hiện tại (xe không còn) → hiện tại hoàn thành: <b>has just taken</b>.',
 'ng4.10': 'Sau "How many" cần danh từ số nhiều chỉ người: <b>participants</b> (người tham gia).',
 'ng4.11': 'Mốc quá khứ xác định (<b>last week</b>) → quá khứ đơn: <b>bought</b>.',
 'ng4.12': '<b>since + mốc</b> → hiện tại hoàn thành: <b>have been</b>.',
 'ng4.13': '<b>since they were children</b> → hiện tại hoàn thành; "know" là động từ trạng thái nên dùng <b>have known</b> (không dùng tiếp diễn).',
 'er1.1': 'Phủ định của <b>ought to</b> là <b>ought not to</b>. Sửa: ought to not → ought not to.',
 'er1.2': "Có giới hạn tốc độ → điều bị cấm nên phải dùng <b>mustn't</b> (không được), không phải needn't (không cần). Sửa: needn't → mustn't.",
 'er1.3': 'Chủ nhật không phải đến trường → "không cần" = <b>didn\'t have to</b> (quá khứ). Sửa: mustn\'t → didn\'t have to.',
 'er1.4': "Khu vực hạn chế → bị cấm chụp ảnh → <b>mustn't</b>. Sửa: don't have to → mustn't.",
 'er1.5': 'Sau <b>became quite</b> cần tính từ: <b>obvious</b>, không phải trạng từ obviously.',
 'er1.6': '<b>feel</b> là linking verb → dùng tính từ song song với "excited": <b>nervous</b>. Sửa: nervously → nervous.',
 'er1.7': '<b>felt</b> + tính từ: felt <b>happy</b>. Sửa: felt happily → felt happy.',
 'er1.8': '<b>smell</b> là linking verb → tính từ: smelled <b>awful</b>. Sửa: smelled awfully → smelled awful.',
 'er1.9': 'Có <b>yesterday</b> → quá khứ đơn: wash → <b>washed</b>.',
 'er1.10': "Có <b>yet</b> → hiện tại hoàn thành: didn't make → <b>haven't made</b>.",
 'er1.11': 'Hành động trong quá khứ ("a few minutes ago") → can → <b>could</b> (hoặc "was able to").',
 'er1.12': "Có mốc quá khứ <b>when I was at school</b> → quá khứ đơn: haven't played → <b>didn't play</b>.",
 'er1.13': 'Trước danh từ "habitat" cần tính từ: particularly → <b>particular</b>.',
 'er1.14': 'Sau <b>suggest (that)</b> dùng (should) + V nguyên mẫu: must do → <b>should do</b>.',
 'er1.15': 'Sau <b>have to</b> dùng động từ nguyên mẫu: made → <b>make</b>.',
 'er1.16': "Sau <b>mustn't</b> dùng động từ nguyên mẫu: uses → <b>use</b>.",
 'er1.17': '"Không cần" là <b>don\'t have to</b> (không có "haven\'t to"). Sửa: haven\'t to stop → don\'t have to stop.',
 'er1.18': 'Theo luật chơi (<b>according to the rules</b>) là điều bị cấm → dùng <b>mustn\'t</b>; "had better not" chỉ là lời khuyên.',
 'er1.19': "Đánh nhau là điều bị cấm → <b>mustn't</b>, không phải don't have to (không cần).",
 'er1.20': '<b>think</b> với nghĩa "cho rằng" là động từ trạng thái, không dùng tiếp diễn: am thinking → <b>think</b>.',
 'er1.21': "<b>see</b> (nhìn thấy) không dùng tiếp diễn: am not seeing → <b>don't see</b> (hoặc can't see).",
 'er1.22': '<b>look</b> là linking verb → tính từ: adorably → <b>adorable</b>.',
 'er1.23': '<b>smell</b> là linking verb → tính từ: terribly → <b>terrible</b>.',
 'er1.24': 'Cần danh từ ghép "waste disposal system" (hệ thống xử lý rác): disposed → <b>disposal</b>.',
 'er1.25': '"one of the most … cities" cần tính từ <b>livable</b> (đáng sống), không phải "living".',
 'er1.26': 'look là linking verb + tính từ: worriedly → <b>worried</b>.',
 'er1.27': '"Đang cân nhắc mua căn hộ" là hành động → dùng tiếp diễn: think → <b>am thinking</b> (think about = suy nghĩ về).',
 'er1.28': '<b>have</b> (sở hữu) là động từ trạng thái, không dùng tiếp diễn: is having → <b>has</b>.',
 'er1.29': '<b>remember</b> là động từ trạng thái: Are you remembering → <b>Do you remember</b>.',
 'er1.30': '<b>see</b> (hiểu) là động từ trạng thái: am seeing → <b>see</b>.',
 'dt1.1': '<b>Although</b> + mệnh đề: "Mặc dù số giờ mẹ ở nhà giảm … nhưng sự quan tâm cho mỗi đứa tăng". However đứng đầu câu với dấu phẩy; unless = nếu '
          'không.',
 'dt1.2': '<b>individual attention</b> = sự quan tâm riêng cho từng đứa trẻ.',
 'dt1.3': '<b>including those who work</b> = bao gồm cả những người đi làm.',
 'dt1.4': 'Đại từ quan hệ thay cho "people" (chủ ngữ): <b>who raised children</b>.',
 'dt1.5': '<b>spend time + V-ing</b>: spend more time <b>helping</b> with homework.',
 'dt2.1': '<b>golden rule</b> = quy tắc vàng.',
 'dt2.2': "<b>be rated (as) Europe's most fortunate</b> = được xếp hạng/đánh giá là may mắn nhất châu Âu.",
 'dt2.3': '<b>opinions are valued</b> (ý kiến được trân trọng), song song với "wishes respected".',
 'dt2.4': '<b>Some would argue that …</b> = Một số người sẽ cho rằng.',
 'dt2.5': '<b>turn … into</b> = biến … thành (turned a whole generation into spoilt brats).',
 'dt3.1': 'He is the <b>person</b> who provides … (người cung cấp tiền cho gia đình).',
 'dt3.2': '<b>be useful for + V-ing</b>; <b>take you in the car to</b> parties = chở bạn đến (bring dùng cho hướng về người nói).',
 'dt3.3': '<b>complain about</b> = phàn nàn về thời gian nói chuyện điện thoại.',
 'dt3.4': '<b>support you in an argument</b> = ủng hộ bạn trong cuộc tranh cãi.',
 'dt3.5': '<b>school report</b> = phiếu báo/nhận xét học tập.',
 'dt4.1': "<b>each other's differences</b> = những điểm khác biệt của nhau (sở hữu cách).",
 'dt4.2': 'Bổ nghĩa cho động từ "communicate": trạng từ <b>effectively</b>.',
 'dt4.3': 'Song song với "rational and …" (tính từ) và hợp nghĩa giải quyết xung đột: <b>non-violent way</b>.',
 'dt4.4': 'Chủ ngữ là hành động duy trì mối quan hệ: <b>requires skills</b> = đòi hỏi kỹ năng.',
 'dt4.5': '<b>growing up</b> = lớn lên (song song với "a lack of these skills, and growing up in a society …").',
 'dt5.1': '<b>take up</b> a sport = bắt đầu chơi/theo một môn thể thao.',
 'dt5.2': 'Thay cho "those" (người) làm chủ ngữ: <b>those who</b> like to be with other people.',
 'dt5.3': 'Vế sau đối lập với vế trước (thích đi cùng người khác ↔ thích ở một mình) → <b>However,</b>.',
 'dt5.4': 'Chủ ngữ của "isn\'t important" → danh động từ <b>winning</b> (việc chiến thắng).',
 'dt5.5': '<b>an enjoyable challenge</b> = một thử thách thú vị, không cần hơn ai.',
 'dt6.1': '<b>sound like</b> = nghe có vẻ như (something from the future).',
 'dt6.2': '<b>warn the driver if</b> they are slipping out of the right lane = cảnh báo tài xế nếu xe trượt khỏi làn.',
 'dt6.3': 'Vượt xe khác một cách <b>safely</b> (an toàn) – hợp với ưu điểm xe tự lái.',
 'dt6.4': 'So sánh hơn: <b>much closer to each other</b> (nhấn mạnh bằng "much").',
 'dt6.5': '<b>human error</b> = lỗi do con người.',
 'dt7.1': '<b>feel well / feel good</b> đều đúng (sau linking verb "feel" dùng tính từ; well = khoẻ mạnh).',
 'dt7.2': '<b>play sports</b> = chơi thể thao.',
 'dt7.3': '<b>take care of</b> = chăm sóc.',
 'dt7.4': 'Đại từ quan hệ thay cho "things" (vật): <b>things that can harm us</b>.',
 'dt7.5': 'Song song với "have more fun, … happier": <b>getting</b> happier (ngày càng hạnh phúc hơn).',
 'dt8.1': '<b>regular practice</b> = việc luyện tập đều đặn, phù hợp thói quen hằng ngày.',
 'dt8.2': '<b>a balanced and peaceful life</b> = cuộc sống cân bằng và bình yên.',
 'dt8.3': '<b>reserve / secure your spot</b> = giữ chỗ. cancel = huỷ; postpone = hoãn.',
 'dt9.1': '<b>We are pleased to announce that …</b> = chúng tôi vui mừng thông báo rằng.',
 'dt9.2': 'Giới từ chỉ ngày: <b>on March 15th</b>.',
 'dt9.3': 'Sau "It is also" cần tính từ: <b>advisable</b> (nên làm).',
 'dt10.1': '<b>with experience of 7 years</b> – "experience" không đếm được, không cần mạo từ.',
 'dt10.2': '<b>leading International schools</b> = các trường quốc tế hàng đầu (tính từ).',
 'dt10.3': '<b>fluent in English</b>.',
 'dt11.1': '<b>Take a minute to</b> locate … = dành chút thời gian để tìm …',
 'dt11.2': 'Đảo ngữ điều kiện loại 1: <b>Should the cabin experience</b> sudden pressure loss (= If the cabin should experience …). Động từ "experience" ở '
           'dạng nguyên mẫu nên không dùng "if".',
 'dt11.3': '<b>While we wait for take-off</b> = trong lúc chờ máy bay cất cánh.',
 'dt12.1': '<b>both … challenges and opportunities</b>.',
 'dt12.2': '<b>compared to</b> = so với (rút gọn bị động).',
 'dt12.3': 'Vế sau đối lập với vế trước (khoảng cách → cơ hội học hỏi) → <b>However,</b>.',
 'dt12.4': '<b>By + V-ing</b> = bằng cách (by fostering open dialogue …).',
 'dt12.5': '<b>harness / utilize the positive aspects</b> = tận dụng những mặt tích cực. bring/earn không đi với cụm này.',
 'dt13.1': 'e (câu mở đầu giới thiệu chủ đề) → c (also: uống nhiều nước) → a (in addition: tránh thuốc lá, rượu) → d (furthermore: khám sức khoẻ) → b '
           '(Overall: kết luận). Đáp án <b>e - c - a - d - b</b>.',
 'dt13.2': 'b mở đầu thư (có "Dear Jane"); c giới thiệu bữa tiệc sẽ có gì → a quy mô khách mời → e thời gian, địa điểm → d lời mời "Would you like to come?" → '
           'f đề nghị báo lại và kết thư. Đáp án <b>b - c - a - e - d - f</b>.',
 'dt13.3': 'e (câu chủ đề) → c (Firstly) → a (Also) → b (In addition to this) → d (Last but not least). Đáp án <b>e - c - a - b - d</b>.',
 'dh1.1': 'Bài chỉ nói "some students <i>learn better</i> at night / in the morning" (học tốt hơn), không phải "need to study" (bắt buộc). A, B, C đều đúng '
          'với đoạn 1. Chọn <b>D</b>.',
 'dh1.2': '"Why must teaching only be conducted in a classroom? You can teach a child without him ever coming to school." → dạy học <b>không nhất thiết phải '
          'diễn ra trong lớp</b>.',
 'dh1.3': '"They don\'t have to learn to read and write at an early age." → không dạy đọc, viết cho trẻ nhỏ. (A, D trái bài; B sai: ở một số trường giáo viên '
          'không được dùng sách.)',
 'dh1.4': '"Even two-year-old children can learn to play difficult pieces of classical music … They do <u>this</u> by watching and listening" → <b>playing '
          'difficult pieces of music</b>.',
 'dh1.5': '<b>involved</b> = có tham gia ≈ <b>engaged</b> (tham gia, gắn bó).',
 'dh2.1': '"Teenagers go to their friends for help or to ask questions that they could not ask their parents about." → <b>D</b>.',
 'dh2.2': '"Some start to fail in school because they are hanging out with their boyfriend or girlfriend instead of doing their work." → <b>C</b>.',
 'dh2.3': 'Bài chỉ nói trẻ có gia đình tan vỡ "<i>may</i> have lower achievements"; "<b>always</b> slow" là tuyệt đối hoá → sai. Chọn A.',
 'dh2.4': 'Cả bài nói các mối quan hệ ảnh hưởng đến nhiều khía cạnh trong cuộc sống thiếu niên → <b>A</b>.',
 'dh2.5': 'Bài bàn về tác động của các mối quan hệ (bạn bè, cha mẹ, tình yêu) lên cuộc sống thiếu niên → <b>B</b>.',
 'dh3.1': '62% đồng ý rằng gặp người trên mạng dễ hơn các cách khác → A đúng. B, C trái bài; D sai (nam giới có khả năng tìm thấy tình yêu nhiều hơn).',
 'dh3.2': '<b>imperative</b> = cấp thiết, bắt buộc ≈ <b>crucial</b>.',
 'dh3.3': '"But with the popularity of online dating, it is imperative we understand the factors …" → Dr. Gavin nói hẹn hò trực tuyến ngày càng phổ biến → '
          '<b>C</b>.',
 'dh3.4': 'Nội dung chính: nghiên cứu cho thấy hẹn hò trực tuyến là cách gặp gỡ tốt → <b>B</b>.',
 'dh3.5': 'Cả bài nói về hẹn hò trực tuyến (<b>online dating</b>).',
 'dh4.1': '"If ongoing medical … treatment is needed, arrangements should be made in advance" → <b>make arrangements</b>.',
 'dh4.2': '<b>ongoing</b> = đang tiếp diễn ≈ <b>continuing</b>.',
 'dh4.3': 'Bài nhấn mạnh kỹ năng, cấu trúc (môi trường, học tập, xã hội) ở đại học khác trung học → <b>A</b> là ý sát nhất; C, D trái bài.',
 'dh4.4': 'Bài khuyên sinh viên "be comfortable asking for help when needed" → D ("should not ask for help") sai.',
 'dh4.5': '<b>overwhelming</b> = quá sức, choáng ngợp ≈ <b>confusing</b> (gây rối); các từ còn lại là nghĩa trái ngược.',
 'dh5.1': 'Bài nói căng thẳng giữa các thế hệ ở Mỹ <b>đã được giảm bớt</b> (alleviated) ngày nay → B.',
 'dh5.2': '"… they were exposed to various forms of social media … <u>They</u> got access to huge sources of new ideas" → <b>teenagers</b>.',
 'dh5.3': '"… exposed to various forms of social media like television and radios" → <b>D</b>.',
 'dh5.4': '"many older people were conservative and didn\'t accept differences disturbing their normal life" → <b>C</b>.',
 'dh5.5': 'Người già học dùng laptop/smartphone từ con cháu giúp giảm căng thẳng → có thể suy ra <b>C</b>. A, B tuyệt đối hoá; D không có trong bài.',
 'dh6.1': 'Bài bàn về mối quan hệ cha mẹ – thiếu niên và cách duy trì tốt → <b>C</b>.',
 'dh6.2': '"Parents have a huge influence on a young child\'s values and interests" → <b>their parents</b>.',
 'dh6.3': 'Câu trước: cha mẹ khó tách rời khỏi con trong khi con muốn tự do → "<u>This</u> may lead to conflict" chỉ <b>D</b>.',
 'dh6.4': '<b>willing</b> = sẵn lòng ≈ <b>ready</b>.',
 'dh6.5': 'Giải pháp gồm: giao trách nhiệm, đặt quy tắc rõ ràng, giao tiếp thường xuyên. "Complain and resist" là phản ứng của thiếu niên, không phải giải '
          'pháp → <b>A</b>.',
 'dh7.1': 'Bài so sánh lợi ích của tập luyện buổi sáng, chiều, tối → <b>A</b>.',
 'dh7.2': '"Morning exercise also helps many people sleep better at night." → <b>C</b>.',
 'dh7.3': '<b>endurance</b> = sức bền, khả năng chịu đựng làm việc khó nhọc trong thời gian dài → <b>B</b>.',
 'dh7.4': '"Exercising at this time decreases your chances of injury" → <b>D</b>.',
 'dh7.5': '"your reaction time is at <u>its</u> quickest" → <b>reaction time</b>.',
 'dh8.1': "Cả bài kể về thí nghiệm ăn toàn đồ ăn nhanh McDonald's của Spurlock → <b>A</b>.",
 'dh8.2': "Ông ăn McDonald's ba bữa mỗi ngày, phải chọn Super Size khi được mời → <b>D</b>.",
 'dh8.3': '<b>giant</b> = khổng lồ ≈ <b>big</b>.',
 'dh8.4': '"The only thing that got rid of his headaches … was another McDonald\'s meal" → <b>B</b>.',
 'dh8.5': 'Ông bị trầm cảm, mất năng lượng, tim và gan có vấn đề → "relaxed and energetic" không phải kết quả → <b>D</b>.',
 'dh8.6': '"Just after <u>its</u> showing in 2004 …" → bộ phim <b>Super Size Me</b>.',
 'dh9.1': 'Bài đề cập sự khác biệt thế hệ ở nơi làm việc (công nghệ, kỳ vọng công việc, phong cách lãnh đạo, giao tiếp) – ý bao quát nhất là về lực lượng lao '
          'động nhiều thế hệ → <b>C</b>. A, D chỉ là một khía cạnh.',
 'dh9.2': '"younger generations often prefer collaborative and inclusive leadership styles, valuing input from all levels" → <b>B</b>.',
 'dh9.3': '"Younger generations, such as Millennials and Generation Z … <u>They</u> readily embrace new tools" → <b>younger generations</b>.',
 'dh9.4': '<b>thrive</b> = phát triển mạnh ≈ <b>succeed</b>.',
 'dh9.5': 'Chính <b>thế hệ trẻ</b> mới ưu tiên sự linh hoạt và cân bằng công việc–cuộc sống; thế hệ lớn tuổi coi trọng sự ổn định → B sai.',
 'dh10.1': 'Bài kể về sự ra đời và lịch sử thành công của Coca-Cola → <b>A</b>.',
 'dh10.2': '"the birthplace of cola was the hot and humid American South" → <b>hot and humid</b>. (Đề gốc ghi nhầm "South America".)',
 'dh10.3': '"Deciding that … would look well in advertising, <u>he</u> named it Coca-Cola" → <b>Pemberton</b>.',
 'dh10.4': '<b>outlawed</b> = bị cấm (làm cho bất hợp pháp) ↔ <b>made legal</b> hoặc <b>allowed</b>.',
 'dh10.5': 'Pemberton phản đối rượu và làm "French Wine of Coca" từ lá coca; sau đó mới kết hợp lá coca với hạt cola để tạo Coca-Cola (không phải rượu). C '
           '(làm rượu từ coca và cola) hoàn toàn sai; D (làm từ hạt cola) cũng sai. Chấp nhận C, D.',
 'dh10.6': '<b>catch on</b> = trở nên phổ biến, được ưa chuộng ≈ <b>became popular</b>.',
 'dh10.7': '"The drink enjoyed additional success since there was a large and popular temperance movement" → <b>A</b>.',
 'vi1.1': 'Cấu trúc: S + have/has not + V3 + for + khoảng thời gian = <b>The last time + S + V2 + was + khoảng thời gian + ago</b>. Đáp án: The last time <b>I '
          'met her was three years ago</b>.',
 'vi1.2': 'S + have not + V3 + since + mốc = The last time + S + V2 + was + (in) mốc. Đáp án: The last time <b>I saw her was in 2000</b>.',
 'vi1.3': 'This is the first time + S + have V3 = <b>S + have never + V3 … before</b>. Đáp án: I <b>have never attended such an enjoyable wedding party '
          'before</b>.',
 'vi1.4': 'This is the first time + S + have V3 = S + have never + V3 … before. Đáp án: I <b>have never been abroad before</b>.',
 'vi1.5': "S + hasn't + V3 + before = This is the first time + S + has/have + V3. Đáp án: This is the first time <b>my student has come to such a big city as "
          'Seoul</b>.',
 'vi1.6': 'This is the first time + S + have V3. Đáp án: This is the first time <b>her children have joined such an attractive party</b>.',
 'vi1.7': 'This is the first time + S + has V3 → S + has never + V3 + before. (Đề gốc dùng "went"; dạng chuẩn là "has been/gone abroad".) Đáp án: He <b>has '
          'never been abroad before</b>.',
 'vi1.8': 'Started … 1 month ago → hiện tại hoàn thành + <b>for 1 month</b>. Đáp án: She <b>has learnt (been learning) to drive for 1 month</b>.',
 'vi1.9': 'Mốc bắt đầu: when it started → <b>since it started to rain</b> + hiện tại hoàn thành (tiếp diễn). Đáp án: We <b>have been eating since it started '
          'to rain</b>.',
 'vi1.10': "last … when = hiện tại hoàn thành phủ định + since. Đáp án: I haven't <b>had my hair cut since I left her</b>.",
 'vi1.11': "It is a long time since + S + last + V2 = S + haven't + V3 + for a long time. Đáp án: We <b>haven't met for a long time</b>.",
 'vi1.12': "S + haven't + V3 + for + khoảng thời gian = It is + khoảng thời gian + since + S + (last) + V2. Đáp án: It is <b>years since I last cheated in an "
           'exam</b>.',
 'vi1.13': 'How long + hiện tại hoàn thành ↔ <b>When did + S + start/begin + V-ing</b>. Đáp án: When <b>did she start living in Danang</b>?',
 'vi1.14': "S + hasn't + V3 + for + khoảng thời gian = S + last + V2 + khoảng thời gian + ago. Đáp án: He last <b>smoked 2 years ago</b>.",
 'vi1.15': 'have + V3 + for 3 years = started/began + V-ing + 3 years ago. Đáp án: I <b>started learning French 3 years ago</b>.',
 'vi1.16': 'The last time + S + V2 + was + khoảng thời gian + ago. Đáp án: The last time <b>I met her was 5 days ago</b>.',
 'vi1.17': 'started … 5 years ago → hiện tại hoàn thành + for 5 years. Đáp án: Mr. Minh has <b>worked (been working) at this office for 5 years</b>.',
 'vi1.18': "The last time + S + V2 + was + mốc = S + haven't + V3 + since + mốc. Đáp án: I have <b>not had a business meeting with him since February</b>.",
 'vi1.19': "last … 2 years ago = haven't + V3 + for 2 years. Đáp án: I have <b>not seen her for 2 years</b>.",
 'vi1.20': "S + haven't + V3 + since + mốc = The last time + S + V2 + was + (in) mốc. Đáp án: The last <b>time I heard from him was in August</b>.",
 'vi2.1': 'If I were you, I would … = <b>You should …</b>. Đáp án: You <b>should spend more time talking with your children</b>.',
 'vi2.2': 'If I were you, I would … = You should …. Đáp án: You <b>should write to him</b>.',
 'vi2.3': "Không được phép = <b>mustn't</b> + V. Đáp án: John <b>mustn't use that computer</b>.",
 'vi2.4': "Đáp án: She <b>mustn't go out at night</b>.",
 'vi2.5': "not allowed to = mustn't. Đáp án: Staff <b>mustn't smoke or eat in the office</b>.",
 'vi2.6': "Đáp án: You <b>mustn't take photographs in the museum</b>.",
 'vi2.7': "It is not necessary for S to V = S <b>needn't</b> V / S <b>doesn't have to</b> V. Đáp án: Jack <b>needn't call Ben today</b>.",
 'vi2.8': "Đáp án: John <b>doesn't have to / needn't water these flowers</b>.",
 'vi2.9': "It would not be good for S to V = S shouldn't V. Đáp án: Your classmate shouldn't <b>use his smartphone during the lesson</b>.",
 'vi2.10': 'be advised to V = should V. Đáp án: Customers should <b>check their luggage before leaving the airport</b>.',
 'vi2.11': "I'd advise you to … = You should …. Đáp án: You <b>should tell the truth to your family</b>.",
 'vi2.12': 'not necessary = don\'t have to / needn\'t. Đáp án: We <b>don\'t have to wear uniforms every day</b>. (Đề gốc bắt đầu bằng "I" – đã sửa thành "We" '
           'cho khớp nghĩa.)',
 'vi2.13': "not allowed to = mustn't. Đáp án: We <b>mustn't drive without wearing a helmet</b>.",
 'vi2.14': 'It is necessary for S to V = S must / have to / need to V. Đáp án: Young people <b>must plan their future career carefully</b>.',
 'vi2.15': 'It is very important for S to V = S must / should V. Đáp án: We <b>must do well at school</b>.',
 'vi2.16': 'It would be a good idea for you to … = You should …. Đáp án: You <b>should share the housework with your mother</b>.',
 'vi2.17': "Chủ động → bị động/khuyết thiếu: Students <b>aren't allowed to cheat / mustn't cheat</b> in the exam.",
 'vi2.18': "Dùng <b>need</b> như khuyết thiếu (phủ định): Nancy <b>needn't clean the flat</b>.",
 'vi2.19': '<b>must have + V3</b> = chắc hẳn đã (suy đoán chắc chắn về quá khứ). Đáp án: You <b>must have been surprised when you heard all the news</b>.',
 'vi2.20': 'let sb V = allow sb to V. Đáp án: The police allowed <b>him to leave after they had questioned him</b>.',
 'vi3.1': 'Đáp án mẫu: <b>Drinking lots of water is good for our health.</b>',
 'vi3.2': 'Đáp án mẫu: <b>Watching too much TV is not good for your eyes.</b>',
 'vi3.3': 'Đáp án mẫu: <b>Doing exercise regularly helps you stay healthy.</b>',
 'vi3.4': 'Đáp án mẫu: <b>Eating healthily is an important part of maintaining good health.</b>',
 'vi3.5': 'Đáp án mẫu: <b>Building a smart city seemed impossible to everyone 50 years ago.</b> (seem + tính từ; dùng quá khứ vì có "50 years ago")',
 'vi3.6': "Đáp án mẫu: <b>I don't think living in a smart city is good for everyone.</b> (think là động từ trạng thái, không dùng tiếp diễn)",
 'vi3.7': 'Đáp án mẫu: <b>Poverty and overcrowding ruin the life of people in many big cities.</b>',
 'vi3.8': 'Đáp án mẫu: <b>Due to poverty and overcrowding, the life of people in many big cities is ruined.</b> (bị động)',
 'vi4.1': '<b>Bài mẫu:</b> <i>Last Sunday, my best friend Lan and I went to the city library to prepare for our English test. At about 4 p.m., Lan suddenly '
          'realised that she had lost her wallet with her student card inside. She felt really worried and almost cried. I felt sorry for her, so we retraced '
          'our steps and asked the librarian for help. Fortunately, a boy had found the wallet near the entrance and handed it in. Lan thanked him warmly and '
          'we were both relieved. I felt happy that honest people still exist. I wish everyone would be careful with their belongings, and I hope that the boy '
          'will always be rewarded for his kindness.</i><br>Gợi ý: nêu rõ <b>what/when/where/who</b>, cảm xúc (worried, relieved), ước muốn (I wish …) bằng '
          'thì quá khứ đơn, khoảng 140–160 từ.',
 'vi4.2': '<b>Bài mẫu:</b> <i>Being independent has many benefits for teenagers. Firstly, independent people can make their own decisions and solve problems '
          'without relying on others, so they become more confident and responsible. Secondly, they learn useful life skills such as time management and '
          'housekeeping, which help them live well on their own in the future. To become more independent, teenagers should start with small tasks like doing '
          'the housework, managing their pocket money and planning their study schedule. They should also learn to think carefully before making decisions and '
          'accept the results. In short, independence helps us grow up and prepare for adult life.</i>',
 'vi4.3': "<b>Bài mẫu:</b> <i>There are several rules in my family. First, I must be home before 9 p.m. and I mustn't use my phone during meals. Second, I "
          'have to do my homework before watching TV, and I ought to help my mother with the housework at weekends. My parents set these rules because they '
          'want me to stay safe, study well and become responsible. At first I felt a little uncomfortable, but now I understand that the rules are for my own '
          "good, so I always try to obey them.</i> (Dùng modal verbs: must, mustn't, have to, ought to.)",
 'vi4.4': '<b>Bài mẫu:</b> <i>Hi Nam, a new fitness club has just opened near our school. It has a gym and a swimming pool. You should join it with me! Do you '
          'prefer to go with me in the morning or in the afternoon? Let me know soon. Bye!</i>',
 'vi4.5': "<b>Bài mẫu:</b> <i>I disagree that parents should strictly limit their children's screen time. Firstly, teenagers can benefit a lot from screens: "
          'they can learn online, research for school projects and keep in touch with friends. Strict limits would take these benefits away. Secondly, too '
          'many rules may make the gap between parents and children wider, because teenagers feel they are not trusted and may hide what they do. Instead of '
          'banning screens, parents should talk with their children, agree on reasonable time and guide them to use technology safely.</i>',
 'vi4.6': '<b>Bài mẫu:</b> <i>Roof gardens bring several advantages to city life. Firstly, they help improve air quality because plants absorb dust and carbon '
          'dioxide. They also create habitats for wildlife such as birds and butterflies. Moreover, city dwellers can interact and connect with nature, which '
          'reduces stress. However, there are some disadvantages. The gardens increase the weight on the structure of the building, so the roof must be very '
          'strong. In addition, they are difficult to repair and maintain. In conclusion, roof gardens are useful but need careful planning.</i>',
 'gt1.1': 'Đây là câu xin phép; cách đáp lại phù hợp nhất trong các phương án là đồng ý: <b>Of course you can.</b> (Thường nói chuẩn hơn là "Of course not" '
          'khi trả lời "Do you mind if…". Các phương án B, D không hợp ngữ cảnh; C là câu hỏi thêm.)',
 'gt2.1': "Đáp án mẫu: <b>Mum, can I go to my friend's birthday party on Saturday evening?</b>",
 'gt2.2': 'Đáp án mẫu: <b>Is it OK if I stay the night at her house after the party?</b>',
 'gt2.3': "Đáp án mẫu: <b>Would you mind if I opened the windows? It's too stuffy in here.</b> (Would you mind if + S + V quá khứ đơn)",
 'gt2.4': 'Đáp án mẫu: <b>Dad, do you mind if I color my hair?</b> (Do you mind if + S + V hiện tại đơn)',
 'gt2.5': 'Đáp án mẫu: <b>Mum, would you mind if I went out with my friends this weekend?</b>',
 'gt3.1': 'Gợi ý: <i>Some unhealthy habits are staying up late, eating too much junk food, skipping breakfast, smoking and spending too much time in front of '
          'screens.</i>',
 'gt3.2': 'Gợi ý: <i>Healthy habits include eating a balanced diet, drinking enough water, doing exercise regularly, getting enough sleep and having regular '
          'check-ups.</i>',
 'gt3.3': 'Gợi ý: <i>To live a long and healthy life, we should eat a balanced diet, work out regularly, sleep at least eight hours, avoid smoking and '
          'alcohol, keep a positive attitude and have regular medical check-ups.</i>',
 'gt3.4': 'Gợi ý: <i>First, stand straight with your feet together and your arms by your sides. Next, jump up and spread your legs and arms out wide at the '
          'same time. Then jump again and bring your feet and arms back to the starting position. Repeat this about ten to twenty times and breathe '
          'regularly.</i>',
 'gt3.5': 'Gợi ý: <i>There are three generations in my family: my grandparents, my parents and me. My grandparents are traditional and hard-working, while my '
          'parents are modern and open-minded. Sometimes my grandparents disagree with me about clothes and screen time, but we solve the conflicts by talking '
          'and listening to each other.</i>',
 'gt3.6': 'Gợi ý: <i>I use my smartphone every day, mostly to chat with friends, look up information for my homework and listen to music – about two hours a '
          'day.</i>',
 'gt3.7': 'Gợi ý (đồng ý): <i>I think parents should limit screen time because too much time on screens harms our eyes, sleep and study. (Không đồng ý): It is '
          'better to guide teenagers than to ban them.</i>',
 'gt3.8': 'Gợi ý: <i>Green cities reduce their impact on the environment. City dwellers use public transport such as trams and electric buses, which reduces '
          'traffic jams and pollution. They also have lots of parks and use renewable energy.</i>',
 'gt3.9': 'Gợi ý: <i>AI technologies such as cameras, robots and smart sensors are installed to help the city operate more effectively, for example '
          'controlling traffic and saving energy.</i>',
 'gt3.10': 'Gợi ý: <i>City dwellers may lose their right to privacy in public areas. It is not easy for some people to get familiar with and use smart '
           'devices. People may also feel lonely because there are many AI technologies around them.</i>',
 'gt3.11': 'Gợi ý: <i>I prefer a green city because it has fresh air, many trees and less noise, which is better for health. However, a smart city is also '
           'convenient because technology makes life easier.</i>',
 'kt.1': 'amazing /əˈmeɪzɪŋ/, female /ˈfiːmeɪl/, taste /teɪst/ → /eɪ/; charge /tʃɑːdʒ/ → /ɑː/. Chọn <b>charge</b>.',
 'kt.2': 'design /dɪˈzaɪn/ → i đọc /aɪ/; impact /ˈɪmpækt/, public /ˈpʌblɪk/, traffic /ˈtræfɪk/ → /ɪ/. Chọn <b>design</b>.',
 'kt.3': 'value /ˈvæljuː/ nhấn âm 1; afford /əˈfɔːd/, depend /dɪˈpend/, impose /ɪmˈpəʊz/ nhấn âm 2. Chọn <b>value</b>.',
 'kt.4': 'behave /bɪˈheɪv/ nhấn âm 2; differ /ˈdɪfə/, argue /ˈɑːɡjuː/, follow /ˈfɒləʊ/ nhấn âm 1. Chọn <b>behave</b>.',
 'kt.5': "Thành ngữ <b>follow in someone's footsteps</b> = nối nghiệp, theo bước chân ai.",
 'kt.6': 'Tính từ đứng trước danh từ: <b>different viruses</b>.',
 'kt.7': '<b>extended families</b> = gia đình nhiều thế hệ.',
 'kt.8': '<b>pour into</b> = đổ xô vào (số lượng lớn).',
 'kt.9': '<b>conflict</b> = mâu thuẫn, xung đột (do bất đồng).',
 'kt.10': '<b>lead a healthier lifestyle</b> = sống lành mạnh hơn.',
 'kt.11': '<b>self-respect</b> = lòng tự trọng ≈ <b>self-esteem</b>.',
 'kt.12': '<b>generate</b> = tạo ra ≈ <b>produce</b>.',
 'kt.13': '<b>conflict</b> (xung đột) ↔ <b>harmony</b> (hòa thuận).',
 'kt.14': '<b>urban</b> (đô thị) ↔ <b>rural</b> (nông thôn).',
 'kt.15': 'Có <b>since + mốc quá khứ</b> → hiện tại hoàn thành; chủ ngữ "We" → <b>haven\'t met</b>.',
 'kt.16': 'Vế trước "since": hiện tại hoàn thành (<b>have lost</b> touch); vế sau "since" có "three years ago" → quá khứ đơn <b>left</b>.',
 'kt.17': "<b>Since + mệnh đề quá khứ đơn</b> → mệnh đề chính dùng hiện tại hoàn thành: <b>haven't heard</b>.",
 'kt.18': 'Sau <b>have to</b> dùng động từ nguyên mẫu: <b>show</b>.',
 'kt.19': "Biển cảnh báo → điều bị cấm: <b>mustn't</b>. don't have to = không cần thiết (sai nghĩa).",
 'kt.20': 'Lời khuyên chung → <b>should</b> (nên). have to/must quá mạnh; might = có thể.',
 'kt.21': 'Câu bị động ("căn phòng được sơn") + <b>since</b> → hiện tại hoàn thành bị động: <b>has been painted</b>.',
 'kt.22': 'Lông mèo mềm là điều nhìn/cảm nhận được → <b>looks</b> (sounds/smells/tastes không hợp nghĩa).',
 'kt.23': '<b>smell</b> + tính từ. "Although" chỉ sự tương phản: món ăn thơm (<b>good</b>) nhưng anh vẫn từ chối vì không đói.',
 'kt.24': 'Chỉ cảm xúc của người → tính từ V-ed: <b>disappointed</b>.',
 'kt.25': 'Bị động + "by my aunt" (hành động đã xảy ra): <b>were sewed</b> (chuẩn hơn là were sewn; đề không có phương án này).',
 'kt.26': "Khu vực hạn chế → bị cấm chụp ảnh → <b>mustn't</b>. Sửa: don't have to → mustn't.",
 'kt.27': "Có <b>yet</b> → hiện tại hoàn thành: didn't make → <b>haven't made</b>.",
 'kt.28': "Sau <b>mustn't</b> dùng động từ nguyên mẫu: uses → <b>use</b>.",
 'kt.29': '<b>look</b> là linking verb → tính từ: adorably → <b>adorable</b>.',
 'kt.30': '<b>have</b> (sở hữu) là động từ trạng thái, không dùng tiếp diễn: is having → <b>has</b>.',
 'kt.31': '<b>take up</b> a sport = bắt đầu chơi/theo một môn thể thao.',
 'kt.32': 'Thay cho "those" (người) làm chủ ngữ: <b>those who</b> like to be with other people.',
 'kt.33': 'Vế sau đối lập với vế trước (thích đi cùng người khác ↔ thích ở một mình) → <b>However,</b>.',
 'kt.34': 'Chủ ngữ của "isn\'t important" → danh động từ <b>winning</b> (việc chiến thắng).',
 'kt.35': '<b>an enjoyable challenge</b> = một thử thách thú vị, không cần hơn ai.',
 'kt.36': 'Bài so sánh lợi ích của tập luyện buổi sáng, chiều, tối → <b>A</b>.',
 'kt.37': '"Morning exercise also helps many people sleep better at night." → <b>C</b>.',
 'kt.38': '<b>endurance</b> = sức bền, khả năng chịu đựng làm việc khó nhọc trong thời gian dài → <b>B</b>.',
 'kt.39': '"Exercising at this time decreases your chances of injury" → <b>D</b>.',
 'kt.40': '"your reaction time is at <u>its</u> quickest" → <b>reaction time</b>.'}
