# -*- coding: utf-8 -*-
"""Dữ liệu Lớp 3 – Unit 3, 4, 5 (Tiếng Anh 3 Global Success). Nguồn: sách giáo khoa + Bài Tập TA 3 HK1 (đáp án do soạn lại)."""

U3 = {
 'n': 3, 'title': 'Our friends',
 'vocab': [('friend', 'bạn', '👫'), ('teacher', 'giáo viên', '👩‍🏫'), ('Mr', 'ông, thầy', '👨'), ('Ms', 'cô', '👩'), ('this', 'đây, cái này (ở gần)', '👇'), ('that', 'kia, cái kia (ở xa)', '👉'),
           ('yes', 'vâng, đúng', '✅'), ('no', 'không', '❌'), ('it', 'nó', '')],
 'pattern': ('<ul><li><b>This is Mary.</b> – Đây là Mary. &rarr; <b>Hi, Mary.</b></li><li><b>That\'s Mr Long.</b> – Kia là thầy Long. &rarr; <b>Hello, Mr Long.</b></li>'
             '<li><b>Is this Bill?</b> – Đây có phải Bill không? &rarr; <b>Yes, it is.</b> / <b>No, it isn\'t.</b></li>'
             '<li><b>Is that Nam?</b> &rarr; <b>No, it isn\'t. It\'s Minh.</b></li><li>It\'s = It is &nbsp; | &nbsp; It isn\'t = It is not</li></ul>'),
 'qa': [('Is this Bill?', 'Yes, it is.'), ('Is that Nam?', "No, it isn't. It's Minh."), ('This is Mary.', 'Hi, Mary.'), ("That's Mr Long.", 'Hello, Mr Long.'), ('How are you?', "I'm fine, thank you.")],
 'odd': [(['Mr', 'Ms', 'yes'], 'yes', 'Mr, Ms dùng trước tên người; yes là "vâng".'), (['friend', 'teacher', 'this'], 'this', 'friend, teacher là người; this là "đây".'),
         (['yes', 'no', 'Mr'], 'Mr', 'yes, no là trả lời; Mr là "ông/thầy".'), (['this', 'that', 'no'], 'no', 'this, that chỉ người/vật; no là "không".')],
 'fills': [
  ("How are you, Minh? – I'm fine, {_}.", ['thank you', 'thanks'], "I'm fine, thank you."),
  ("{_} this Lan? – No, it isn't. It's Lucy.", 'Is', 'Câu hỏi bắt đầu bằng Is: Is this Lan?'),
  ('Is {_} Mai? – Yes, it is.', 'that', 'Is that Mai? (người ở xa)'),
  ("That's {_} Long. – Hello, Mr Long.", 'Mr', 'Mr Long = thầy/ông Long.'),
  ('This is my {_} Nam. – Hi, Nam.', 'friend', 'my friend Nam = bạn Nam của tôi.'),
  ("That's my teacher, {_} Hoa.", ['Ms', 'Miss'], 'Ms/Miss Hoa = cô Hoa.'),
  ('Is that Mr Long? – {_}, it is.', 'Yes', 'Yes, it is.'),
  ("Is this Lan? – {_}, it isn't. It's Mary.", 'No', "No, it isn't."),
  ("That's Lucy. – {_}, Lucy.", ['Hello', 'Hi'], 'Chào lại: Hello / Hi.'),
  ('Hi, Lucy. – This {_} Nam.', 'is', 'This is Nam.'),
  ("That's my teacher, Mr Long. – {_}, Mr Long.", ['Hello', 'Hi'], 'Chào thầy: Hello, Mr Long.'),
  ('{_} is Mary. (người ở gần)', 'This', 'This is Mary.'),
  ("{_}'s Mr Long. (người ở xa)", 'That', "That's Mr Long."),
  ("Is this Bill? – Yes, it {_}.", 'is', 'Yes, it is.')],
 'sents': ['This is my friend Linh.', "That's my teacher, Ms Hoa.", 'Is this Bill?', 'Yes, it is.', "No, it isn't.", 'Is that Mai?', 'Thank you, Ben.', "That's Mr Long.", 'Hello, Mr Long.', 'This is Mary.'],
 'mcq': [('Is this Bill? – ___', ['Yes, it is.', 'Yes, I am.', 'Fine, thanks.'], 'Yes, it is.', 'Is this …? → Yes, it is.'),
         ('This ___ my friend.', ['is', 'are', 'am'], 'is', 'This is …'),
         ("Is that Nam? – No, it ___. It's Minh.", ["isn't", 'is', 'am'], "isn't", "No, it isn't."),
         ('___ is Mary. (người ở gần)', ['This', 'That', 'It'], 'This', 'This = ở gần.'),
         ("___ Mr Long. (người ở xa)", ["That's", "This's", 'Are'], "That's", "That's = kia là."),
         ('Hi, Mary. This is my friend Nam. – ___', ['Hi, Nam.', 'Goodbye.', 'Yes, it is.'], 'Hi, Nam.', 'Được giới thiệu thì chào lại.'),
         ("That's Ms Hoa. – ___", ['Hello, Ms Hoa.', "It's Nam.", "I'm fine."], 'Hello, Ms Hoa.', 'Chào cô Hoa.'),
         ('Is that Mr Long? – ___', ['Yes, it is.', "I'm Long.", 'Goodbye.'], 'Yes, it is.', 'Trả lời Yes/No.'),
         ('Chọn từ nghĩa "giáo viên":', ['teacher', 'friend', 'Mr'], 'teacher', 'teacher = giáo viên.'),
         ('Is this Lan? – No, it isn\'t. ___ Lucy.', ["It's", 'Is', 'This'], "It's", "It's Lucy."),
         ('Chọn từ nghĩa "bạn":', ['friend', 'teacher', 'that'], 'friend', 'friend = bạn.'),
         ('___ you, Ben. – (cảm ơn)', ['Thank', 'This', 'That'], 'Thank', 'Thank you.')],
 'dlg': ["Nam: Hello, I'm Nam.", "Quan: Hi, Nam. I'm Quan.", 'Nam: Is that Ms Hoa, Quan?', "Quan: Yes, it's Ms Hoa, my English teacher.", 'Nam: Ms Hoa is my English teacher, too.'],
 'read': [("<p>Hello. I'm Nam. This is my friend, Linh. That is my teacher, Ms Hoa.</p>",
           [('Linh is Nam\'s friend.', 'T', 'This is my friend, Linh.'), ('Ms Hoa is Nam\'s friend.', 'F', 'Ms Hoa là cô giáo (teacher).'), ('Nam is a teacher.', 'F', 'Nam giới thiệu bạn và cô giáo; Nam không phải giáo viên.')]),
          ("<p><b>Mary:</b> Is this Bill?<br><b>Nam:</b> No, it isn't. It's Tom.<br><b>Mary:</b> Is that Mr Long?<br><b>Nam:</b> Yes, it is.</p>",
           [('This is Tom.', 'T', "No, it isn't. It's Tom."), ('This is Bill.', 'F', "No, it isn't Bill."), ('That is Mr Long.', 'T', 'Yes, it is.'), ('Nam says "No" to the second question.', 'F', 'Câu hỏi thứ hai Nam trả lời Yes.')])],
}

U4 = {
 'n': 4, 'title': 'Our bodies',
 'vocab': [('face', 'khuôn mặt', '🙂'), ('nose', 'mũi', '👃'), ('eye', 'mắt', '👁️'), ('ear', 'tai', '👂'), ('hand', 'bàn tay', '✋'), ('mouth', 'miệng', '👄'),
           ('hair', 'tóc', '💇'), ('touch', 'sờ, chạm', ''), ('open', 'mở, há', '')],
 'pattern': ('<ul><li><b>What\'s this?</b> – Đây là gì? &rarr; <b>It\'s a nose.</b> / <b>It\'s an eye.</b> (dùng <i>an</i> trước a, e, i, o, u)</li>'
             '<li><b>What\'s that?</b> – Kia là gì? &rarr; <b>It\'s a face.</b></li><li><b>Touch your nose!</b> – Hãy sờ mũi của bạn!</li><li><b>Open your mouth!</b> – Hãy há miệng ra!</li></ul>'),
 'qa': [("What's this?", "It's a nose."), ("What's that?", "It's an eye."), ('How are you?', "I'm fine, thanks."), ("What's your name?", "My name's Mai."), ('Is this Bill?', 'Yes, it is.')],
 'odd': [(['eye', 'ear', 'open'], 'open', 'eye, ear là bộ phận cơ thể; open là "mở".'), (['nose', 'mouth', 'touch'], 'touch', 'nose, mouth là bộ phận cơ thể; touch là "sờ".'),
         (['face', 'hand', 'open'], 'open', 'face, hand là bộ phận cơ thể.'), (['touch', 'open', 'ear'], 'ear', 'touch, open là động từ; ear là danh từ.')],
 'fills': [
  ("What's {_}? – It's a face.", 'this', "What's this? (vật ở gần)"), ("What's {_}? – It's an eye. (vật ở xa)", 'that', "What's that?"),
  ("It's {_} eye.", 'an', 'eye bắt đầu bằng nguyên âm → an.'), ("It's {_} nose.", 'a', 'nose bắt đầu bằng phụ âm → a.'), ("It's {_} ear.", 'an', 'ear bắt đầu bằng nguyên âm → an.'),
  ("👃 Touch your {_}.", 'nose', 'nose = mũi'), ("👂 Touch your {_}.", 'ear', 'ear = tai'), ("👄 Open your {_}.", 'mouth', 'mouth = miệng'),
  ("👁️ It's an {_}.", 'eye', 'eye = mắt'), ("✋ It's a {_}.", 'hand', 'hand = bàn tay'), ("🙂 It's a {_}.", 'face', 'face = khuôn mặt'),
  ('{_} your hair!', 'Touch', 'Touch your hair!'), ('{_} your mouth!', 'Open', 'Open your mouth!'), ("💇 Touch your {_}.", 'hair', 'hair = tóc')],
 'sents': ["It's a nose.", "It's an eye.", "It's a face.", 'Open your mouth.', 'Touch your ears.', 'Open your eyes.', 'Touch your hair.', "What's this?", "What's that?", 'Touch your nose.'],
 'mcq': [("It's ___ ear.", ['an', 'a', 'the'], 'an', 'ear bắt đầu bằng nguyên âm → an.'), ("It's ___ nose.", ['a', 'an', 'is'], 'a', 'nose → a.'),
         ("What's this? – ___", ["It's a hand.", 'Open your mouth.', "I'm fine."], "It's a hand.", 'Hỏi "đây là gì" → It\'s a …'),
         ('___ your mouth! (há miệng)', ['Open', 'Touch', 'This'], 'Open', 'Open = mở / há.'), ('___ your nose! (sờ mũi)', ['Touch', 'Open', 'That'], 'Touch', 'Touch = sờ.'),
         ("What's that? 👁️ – It's ___ eye.", ['an', 'a', 'no'], 'an', 'an eye.'), ("What's this? 🙂 – It's ___ face.", ['a', 'an', 'is'], 'a', 'a face.'),
         ('Chọn từ nghĩa "tai":', ['ear', 'eye', 'hand'], 'ear', 'ear = tai.'), ('Chọn từ nghĩa "miệng":', ['mouth', 'nose', 'face'], 'mouth', 'mouth = miệng.'),
         ('Open your ___. (há ra)', ['mouth', 'hair', 'hand'], 'mouth', 'Ta há miệng (mouth).'), ('Chọn từ nghĩa "mũi":', ['nose', 'mouth', 'face'], 'nose', 'nose = mũi.'),
         ('Chọn từ nghĩa "tóc":', ['hair', 'hand', 'ear'], 'hair', 'hair = tóc.')],
 'dlg': ["A: What's this?", "B: It's a hand.", "A: What's that?", "B: It's a nose.", 'A: Thank you.'],
 'read': [("<p>This is my face. I have two eyes, one nose and one mouth. I have two ears, too.</p>",
           [('I have two eyes.', 'T', 'two eyes = 2 mắt.'), ('I have two noses.', 'F', 'one nose = 1 mũi.'), ('I have one mouth.', 'T', 'one mouth.'), ('I have two ears.', 'T', 'two ears, too.')]),
          ("<p><b>Teacher:</b> Touch your nose.<br><b>Teacher:</b> Open your mouth.<br><b>Teacher:</b> Touch your ears.</p>",
           [('Students touch their noses.', 'T', 'Touch your nose.'), ('Students open their hands.', 'F', 'Cô nói Open your mouth.'), ('Students touch their ears.', 'T', 'Touch your ears.')])],
}

U5 = {
 'n': 5, 'title': 'My hobbies',
 'vocab': [('singing', 'hát', '🎤'), ('dancing', 'nhảy, múa', '💃'), ('drawing', 'vẽ', '✏️'), ('swimming', 'bơi', '🏊'), ('cooking', 'nấu ăn', '🍳'), ('walking', 'đi bộ', '🚶'),
           ('painting', 'tô màu, sơn', '🖌️'), ('running', 'chạy', '🏃'), ('hobby', 'sở thích', ''), ('like', 'thích', '')],
 'pattern': ('<ul><li><b>What\'s your hobby?</b> – Sở thích của bạn là gì? &rarr; <b>It\'s singing.</b> – Là hát.</li><li><b>I like dancing.</b> – Mình thích nhảy.</li>'
             '<li><b>She likes singing.</b> – Bạn ấy thích hát. (ngôi thứ ba thêm <i>s</i>: likes)</li><li><b>Our hobbies are swimming and cooking.</b> – Sở thích của chúng mình là bơi và nấu ăn.</li></ul>'),
 'qa': [("What's your hobby?", "It's singing."), ("What's your hobby, Mary?", "It's drawing."), ('I like dancing.', 'Me too.'), ('How are you?', "I'm fine, thanks."), ("What's your name?", "My name's Nam.")],
 'odd': [(['singing', 'dancing', 'hobby'], 'hobby', 'singing, dancing là hoạt động cụ thể; hobby là "sở thích".'), (['running', 'walking', 'like'], 'like', 'running, walking là hoạt động; like là "thích".'),
         (['drawing', 'painting', 'swimming'], 'swimming', 'drawing, painting là hoạt động vẽ/tô; swimming là bơi.'), (['cooking', 'singing', 'hobby'], 'hobby', 'hobby là danh từ chung.')],
 'fills': [
  ("What's your {_}? – It's singing.", 'hobby', 'hobby = sở thích'), ('I {_} dancing.', 'like', 'I like … = Mình thích …'), ('She likes singing {_} dancing.', 'and', 'and = và'),
  ('Our {_} are swimming and cooking.', 'hobbies', 'hobbies = các sở thích'), ("🎤 It's {_}.", 'singing', 'singing = hát'), ("💃 It's {_}.", 'dancing', 'dancing = nhảy'),
  ("🏊 It's {_}.", 'swimming', 'swimming = bơi'), ("🍳 It's {_}.", 'cooking', 'cooking = nấu ăn'), ("🏃 I like {_}.", 'running', 'running = chạy'), ("🚶 I like {_}.", 'walking', 'walking = đi bộ'),
  ("✏️ My hobby is {_}.", 'drawing', 'drawing = vẽ'), ("🖌️ I like {_}.", 'painting', 'painting = tô màu'), ('What\'s your hobby, Mary? – It\'s {_}.', ['drawing', 'singing', 'dancing', 'cooking', 'swimming', 'walking', 'painting', 'running'], 'Trả lời bằng một sở thích, ví dụ: It\'s drawing.'),
  ('He {_} running.', 'likes', 'He/She + likes')],
 'sents': ["What's your hobby?", "It's singing.", 'I like dancing.', 'I like swimming.', 'My hobby is painting.', 'She likes singing and dancing.', 'Our hobbies are swimming and cooking.', "It's cooking.", 'I like running.', 'He likes walking.'],
 'mcq': [("What's your hobby? – ___", ["It's singing.", "I'm fine.", 'Yes, it is.'], "It's singing.", 'Hỏi sở thích → It\'s + hoạt động.'), ('I ___ dancing.', ['like', 'likes', 'is'], 'like', 'I like …'),
         ('She ___ singing.', ['likes', 'like', 'am'], 'likes', 'She + likes'), ('Our ___ are swimming and cooking.', ['hobbies', 'hobby', 'like'], 'hobbies', 'Số nhiều: hobbies.'),
         ('Chọn từ nghĩa "bơi":', ['swimming', 'running', 'walking'], 'swimming', 'swimming = bơi.'), ('Chọn từ nghĩa "vẽ":', ['drawing', 'painting', 'cooking'], 'drawing', 'drawing = vẽ.'),
         ('Chọn từ nghĩa "nấu ăn":', ['cooking', 'singing', 'dancing'], 'cooking', 'cooking = nấu ăn.'), ("What's your ___? – It's singing.", ['hobby', 'like', 'friend'], 'hobby', "What's your hobby? – It's singing."),
         ("I like singing. – ___", ['Me too.', 'Goodbye.', 'Yes, it is.'], 'Me too.', 'Me too = mình cũng vậy.'), ('He ___ running.', ['likes', 'like', 'are'], 'likes', 'He + likes'),
         ("What's your hobby? 🏃 – It's ___.", ['running', 'swimming', 'cooking'], 'running', '🏃 = running.'), ("What's your hobby? 💃 – It's ___.", ['dancing', 'singing', 'drawing'], 'dancing', '💃 = dancing.')],
 'dlg': ["Mary: What's your hobby, Nam?", "Nam: It's running. What's your hobby?", "Mary: It's drawing.", 'Nam: I like drawing, too.', 'Mary: Thank you.'],
 'read': [("<p>Hello. I'm Mai. My hobby is drawing. I like painting, too. My friend Nam likes swimming.</p>",
           [('Mai\'s hobby is drawing.', 'T', 'My hobby is drawing.'), ('Mai likes cooking.', 'F', 'Mai thích drawing và painting.'), ('Nam likes swimming.', 'T', 'My friend Nam likes swimming.')]),
          ("<p><b>Mary:</b> What's your hobby?<br><b>Tom:</b> It's singing. I like dancing, too.<br><b>Mary:</b> Me too!</p>",
           [('Tom\'s hobby is singing.', 'T', "It's singing."), ('Tom likes running.', 'F', 'Tom thích singing và dancing.'), ('Mary likes dancing, too.', 'T', 'Me too!')])],
}
UNITS = [U3, U4, U5]
